# Часть I. Бессонница {-}

# &nbsp; {#chapter-1}

Как правило, после внепланового завершения серьезных отношений даже сильные люди впадают в своего рода эмоциональную спячку. Так или иначе, приходится изолироваться от несостоявшейся второй половинки. Перебороть истерики и утихомириться в какой-нибудь тесной квартирке с мусорным ведром под раковиной, микроволновкой для полуфабрикатов, своими немногочисленными пожитками и бутылкой, о которой ты уже толком и не помнишь, что внутри, но к которой все равно продолжаешь периодически прикладываться с крайне отсутствующим видом. 

Сколько бы лет тебе не было, – двадцать пять или пятьдесят, неважно – вдруг начинаешь вести жизнь завтрашнего пенсионера. Прекращаешь слушать музыку, за едой думаешь исключительно о еде и никогда не выключаешь телевизор. Последний ты даже не смотришь, но все равно оставляешь телек трещать на фоне. Чтобы чувствовать себя менее одиноко.

В моменты как этот всякая деятельность обращается бездействием. С каждым днем ты все больше и больше теряешь интерес к жизни, но все чаще начинаешь задумываться о смерти, которая становится чем-то ожидаемым. Логичным завершением одного тотального фиаско под названием твоя собственная жизнь.

Мать моего отца умерла за месяц до моего рождения. Дедушка же прожил еще полторы декады. Все эти годы он спал со включенным телевизором, который толком не смотрел. Еще дед никогда не смеялся и очень редко улыбался. Разве что мне. После его смерти я нашла коробку со старыми снимками. Практически на каждом из них лицо моего деда освещала широченная улыбка, но отец лишь пожал плечами. Сказал только, что со дня похорон своей жены дед так ни разу не засмеялся. 

Он умер хмурым январским утром. Сгорел от внезапно давшего о себе знать рака. Дед пережил голодомор, войну, распад Советского Союза и трех украинских президентов, а потом почувствовал острую боль в желудке и умер спустя месяц. Это вообще легально? 

— Я люблю тебя — сказала я дедушке, и вышла из палаты.

Знай я, что это будут последние слова, которые он от меня услышит, выбрала бы что-нибудь пооригинальней. 

Тем не менее, я до последнего не верила, что рак заберет его так быстро. Мне только исполнилось пятнадцать, дедушке – восемьдесят три. Он продолжал работать, бегал по утрам и выглядел лет на двадцать моложе своего возраста. 

Затем болезнь впервые дала о себе знать. Какие-то две-три недели и недостающие года тут же отразились в чертах его лица.

Тем вечером за окном бушевал ветер. Выходя из палаты, я слышала, как по подоконнику забарабанили первые капли дождя.

— Надеюсь, это случится не завтра, — вдруг сказал дедушка. — Мне бы очень не хотелось умереть в такую погоду.

— Это не случится завтра, — спокойно сказала я и наклонилась, чтобы поцеловать дедушкину щеку. — Я люблю тебя.

И я ушла. Вышла под дождь и медленно зашагала в сторону дома.

Проснувшись следующим утром, я подошла к окну. За ним по-прежнему было темно, и я с удивлением осознала, что впервые в жизни встала раньше будильника. Фактически, утро еще не наступило. До школы оставалось несколько часов, а в душе засело ноющее чувство тревоги. Я взяла книгу – кажется, это был Лавкрафт – и устроилась на подоконнике. 

Помнится, по радио то и дело передавали штормовое предупреждение, и по мере приближение рассвета мне открывались переполненные водой улицы. Вода и грязь, сопровождаемые возгласами ветра, заполняли собой все вокруг.

Дедушка не умер на следующий день. Он умер той ночью. Думаю, от этого я и проснулась.

Сейчас, спустя десять лет, я с ужасом осознаю, что не могу припомнить, как звучал голос моего деда. Я закрываю глаза и стараюсь расслабить сознание, вспоминая детство, проведенном в его доме. Вижу старый топчан, покрытые пылью ордена и желтую занавесь, что висела у входа в дедушкину спальню. За ними тянется старого образца гостиная. Она ничем не отличается от тех, что можно увидеть в домах других стариков из рабочего класса: раскладной диван, ковер на стене, кресла по обе стороны журнального столика, накрытого плетеной циновкой, и древний телевизор, который никогда не замолкает. 

Мне вспоминается крохотная прихожая с обогревателем; я слышу яркий запах цитрусовых, чьи корки дедушка каждую зиму сушил для своей настойки. Вспоминается кухня, пиалка из хрусталя, неизменно полная конфет и гигантская копия наручных часов, висевшая в углу. На столе меня ждет чугунная сковорода времен Феликса Дзержинского, а в ней – традиционная утренняя яичница с молодой картошкой, вкусней которой и быть не может. 

По старой привычке, дедушка ест стоя. Он добавляет в картошку соли и с довольным видом наблюдает за тем, как я уплетаю завтрак. Чайник на плите уже начинает посвистывать, привлекая внимания котов, что всю ночь где-то пропадали, а теперь лениво дремлют на подоконнике. 

Лежавший в тарелке завтрак вскоре исчез, как исчезнет и сковорода, и стол, на котором она стоит, кухня, и все остальные комнаты. На месте ветхого домика уже давно стоит другой, но память о нем никуда не делась. Я вспоминаю дедушку, заботливо перемешивающего сахар в моей чашке с чаем. Вижу, как он замечает пустую тарелку, и знаю, что будет дальше. Сейчас дед поставит передо мной чай и предложит добавки. Тогда я делаю глубокий вдох и стараюсь не думать ни о чем другом. Все жду, что голос сам всплывет в памяти. 

Но он не всплывает, как не старайся. С пугающей точностью я помню слова, интонации, произношение. Короче говоря, что угодно, то только не то, что хочу вспомнить. И, все-таки, мне кажется, услышь я дедушкин голос хоть на мгновенье, – случайно, и не подозревая, кому он принадлежит – я бы обязательно его вспомнила.

Так вот, все эти годы дед жил со включенным телевизором. Прошло еще восемь лет, прежде чем я поняла, почему.

