# &nbsp; {#chapter-2}

Приближался день рождения Адама, которого я не видела два с половиной года. Очередной день в баре. К тому времени я уже привыкла находиться по другую сторону стойки и читала что-то от Буковски, периодически поглядывая в сторону поддатых посетителей. 

– Освежи мне! – заплетающимся языком произнес один из них.

После чего толкнул пивной бокал в обратную от меня сторону. Тот проехал пару метров вдоль барной стойки, ударился о стену и с характерным звоном рассыпался на тысячи блестящих стеклышек.

Мне вдруг очень захотелось стать этим бокалом.

На самом деле мне даже нравилось работать за барной стойкой. Если не учитывать шестнадцатичасовой рабочий день, мизерную зарплату, постоянные недостачи и полное отсутствие чаевых, а также клиентов, в большинстве своем доводящих до исступления… О чем я говорила? Ах да, все не так уж плохо.

Сложно сказать почему, но, стоило мне надеть фартук и впервые перешагнуть эту заветную черту, отделяющую мир бармена от общества простых смертных, я моментально почувствовала себя в своей тарелке. Разбираться в винных сортах, изучать миксологию, работать над созданием собственных коктейлей и временами баловаться флейрингом – было в этом что-то особенное. Я без труда могла рассказать о любом из напитков куда больше, чем указано на этикетке, посоветовать вино или удивить гостя чем-нибудь экзотичным. Такая работа и впрямь была мне по душе, но, быть может, так скажет любой алкоголик.

Увы, несмотря на престижность заведения, где я работала, (а также на тот факт, что местная стойка считалась самой дорогой во всем городе), платили здесь плачевно мало. Настолько мало, что едва хватало на еду и коммуналку. С другой стороны, работа занимала у меня все время, так что, будь у меня лишние деньги, я все равно не успевала бы их потратить. Вероятно, в этом и был секрет выживания сотрудников «Штиля».

– Плесни еще на посошок, – на этот раз горе-метатель казенной посуды обошелся без спецэффектов. 

Залпом расправился с последней порцией пива и вскоре исчез, оставив «Штиль» без единого посетителя.

– Итак, на чем мы остановились…

Десять страниц, пятнадцать, двадцать. Ничего не менялось. В зале по-прежнему было пусто. 

Как и в моем сердце.

Не то чтоб я ежеминутно думала о своем бывшем. Эти времена уже прошли. Я месяцев семь как выкарабкалась из затяжной депрессии и всячески старалась загрузить себя работой. Как я уже сказала, платили в «Штиле» смехотворно мало. Ну кто будет так рвать задницу ради каких-то ста пятидесяти баксов в месяц?

К счастью, работа всецело меня выматывала, что оказалось главным из ее достоинств. После смены на всё про всё оставалось часов шесть, и это без учета дороги, а потом обратно за стойку. Знаете, нелегко быть в депрессии, когда на нее просто не остается времени. Мне чуть ли не заранее приходилось планировать свои нервные срывы.

Так вот, наступило двадцатое апреля две тысячи шестнадцатого года – день толерантности марихуаны, а по совместительству и день рождения одного небезызвестного немецкого политика еврейского происхождения. День обещал быть куда более радужным, чем карьера последнего. Мне хотелось выглянуть на улицу, но за стойкой, само собой, окон не было. 

Не было их и в зале-ресторане. Не было в боулинге, и на кухне тоже ни одного окошка не наблюдалось. Мне это всегда казалось странным. Будто у проектировщиков имелась какая-то тайная нелюбовь к сквозным отверстиям. С другой стороны, в зале ежедневно околачивались стриптизерши, проститутки, эскортницы и прочего рода содержанки, так что что-то здесь явно не вяжется.

В любом случае, за стойкой было темно, как в причинном месте. Приходилось читать в свете неоновых вывесок с изображениями Моргана, Бушмилса, Дэниэлса и прочих хорошо мне знакомых парней. Если алое освещение надоест, можно чуток подвинуться влево. Пара шагов вдоль стойки, и алые страницы становятся зелеными в свете лозунгов Егеря, Бехеровки или Ксенты.

Говорят, человеку нужно всего три недели, чтобы привыкнуть к дискомфорту или избавиться от вредной привычки. Увы, я провела в «Штиле» не один год, но так и не смогла свыкнуться с отсутствием окон.

Единственным приятным моментом, помимо доступа к алкоголю, была входная дверь. Сплошь стеклянная, она находилась слева от моего рабочего места и открывала взгляду небольшой клочок улицы. Судя по всему, за пределами «Штиля» и впрямь стояла восхитительная погода. Сияло весеннее солнце; деревья уже позеленели и, движимые легким ветерком, отбрасывали причудливые тени на аллейку. Отсюда мне был виден каменный фонтан да пара скамеек. Брызги воды прямо-таки светились под лучами полуденного солнца. От этой радужной картины в душе сделалось как-то грустно, так что я отправилась варить кофе.

– Ты будешь делать кофе? – моментально среагировала одна из официанток, которых в «Штиле» звали просто фицами.

– Кофе? – эхом отозвались из зала.

Каким-то мистическим образом они всегда это чувствовали. Девушки по инерции стекались у барной стоило мне лишь подумать о том, чтобы варить кофе.

– Буду.

– И мне сделай, Лизочек, – Вера сняла с полки пустую чашку, чмокнула меня в щеку и побежала обслуживать очередной столик.  

Терпеть не могла, когда меня так называли.

За ней оживились и другие сотрудники развлекательного комплекса. Стало ясно, что одной чашкой кофе здесь не обойдется. 

Вернувшись на прежнее место, я заметила, что у фонтана появился бездомный. Уже наполовину раздетый, он продолжал смущать прохожих и неспешно стягивал с себя одежду, пока наконец не остался в чем мать родила. Затем товарищ без лишних раздумий погрузился в фонтан, лениво растянулся, опираясь на бортик, и уже беззаботно потягивал пивасик.

Вот, в принципе, и все, что вам нужно знать о городе, в котором я родилась.

<div style="text-align: center;">***</div>

Звонил телефон. Кассир сняла трубку и тут же передала ее мне со словами:

– Это по твою душу.

Этажом ниже просили сделать пятнадцать детских мохито и четыре взрослых. Намечался очередной детский день рождения. С ума сойти. В мое время мы дарили друг другу наклейки и радовались мороженому из «МакДональдса», а не арендовали целый этаж в ночном клубе вместе с аниматорами, лайт-джеями и диджеями. А ведь мне едва ли исполнилось двадцать два года.

– И побыстрее! Мелюзга уже вовсю вопит! – голос хриплый, чуть ли не потусторонний, и прямо-таки гавкает, а не говорит.

Почти два десятка мохито – не самый удачный выбор, когда за стойкой нет крашмейкера. Единственный работающий аппарат находился в ночном клубе, так что мне постоянно приходилось бегать туда-сюда за колотым льдом.

Официантка уже стояла на раздаче, когда я положила трубку.

– Я бы тебе помогла, – сказала Вера, – но начальство велело даже в туалет не выходить. Я в зале одна осталась. 

– Ничего, я схожу вниз… 

– Пипец. Скоро обоссусь.

– А ты пока принеси стаканы.

Вероника кивнула и уже собиралась уходить, когда я позвала ее по имени.

– Слушай, а кто звонил?

– Ну, Рыжая.

Я вскинула бровь.

– Ты уверена?

– Еще б мне не быть уверенной. Здесь только мы и есть. По одной на этаж. А чё такое?

– Да голос, блин, какой-то жуткий. Как с того света, честное слово. Это точно Рыжая? Как-то на нее не похоже.

– Чего не похоже? На Рыжую не похоже? Да она опять до шести утра в клубе бухала!

Вера закатила глаза и, прихватив поднос, ушла на мойку. Порой создавалось впечатление, что та завидует коллеге. 

Как ни странно, внизу меня действительно ждала Тоня.

– Привет, Рыжик, как твое похмелье?

Милая девушка, только временами врывается как гром среди ясного неба. Говорила она много, громко и очень быстро. Словом, Тоня с легкостью могла бы стать отличным примером экспрессии в бытовой речи.

– ЛИЗА, ЛИЗА, ЛИЗА! – закричала она, перекрывая шумы клубного подземелья. – Сделай мне чего-нибудь этакого!

– Этакакого?

– Ну, чтоб получше стало, а то я щаз точно ласты откину! Вот увидишь, откину! – она наполнила хайбол льдом и теперь жадно прижимала его к своему лицу. – Так и шо? Ты сделаешь?

– Сделаю. Как с заказом закончу.

– Пожа-а-алуйста, сделай сейчас, а? А я тебе лёд пока замучу.

Ну как тут откажешь?

До окончания дня оставалось еще немало. Я как раз колдовала над своим противопохмельным отваром, когда телефон в кармане моих джинс завибрировал. На экране меня ждало входящее сообщение от очередного бородатого незнакомца. 

Его звали Вениамин.

«Как жизнь молодая?» – спрашивал он.

Обычно я игнорирую подобные попытки знакомства, но… То ли дело здесь было в четыре-двадцать, то ли в том, что мне осточертело стоять за стойкой, а может, в том, что образ Адама то и дело упрямо выныривал из памяти, – понятия не имею. В общем, я ответила.

