# &nbsp; {#chapter-3}

Все та же душная мгла повисла над городом, заботливо обволакивая каждую из его составляющих. До рассвета оставалось еще минимум шесть часов, что вовсе не мешало местной пьяни устраивать под окнами традиционные субботние концерты. Они орали и галдели так, словно эта ночь была последним шансом напиться. 

Растянувшись поперек кровати, я пыталась сосредоточиться на книге. В ней говорилось о зимних лесах с их невероятными пейзажами, конных упряжках, размашистых балах и дворцах, одетых в блестящее убранство. А за окном лаяли псы, неслись машины и шумели районные алкоголики, напоминая мне, где на самом деле я нахожусь. Вероятно, дело было в моем душевном расстройстве: маниакальная фаза сменилась депрессивной. Мне вдруг стало неописуемо грустно и обидно за то, какой жизнью приходится жить. Еще и Адам постоянно лез в голову.

*Не думай о нем.*

Чертов Адам с его обаятельной улыбкой да ямочками на щеках.

Захлопнув книгу, я отважилась закрыть окно 

(я говорю «отважилась» потому, как термометр показывал под тридцать, а кондиционера в моей квартирке отродясь не водилось) 

чтобы хоть немного приглушить раздражающие вопли. Подавляющему большинству людей всегда было плевать на беспредел, творящийся в этом районе. Несколько лет назад в парке под моим домом до смерти забили женщину. Другую изнасиловали и задушили чуть подальше, оставив валяться среди ив, кленов и прочей растительности, что окружала аллею. Нашли ее полностью голую около семи утра. Я прекрасно помню то утро потому, что именно в это время шла через парк поздравить своего отца с юбилеем, а еще потому, что я эйдетик.

Помнится, третью женщину убили как раз-таки на отрезке пути, что вел от одного из этих парков к другому. Она лежала в сквере у онкологического отделения. Снега той зимой были нешуточные, так что несчастную обнаружили лишь в апреле. Вид у нее был, прямо говоря, не очень, отчего распознать черты лица уже не представлялось возможным. Труп опознать не могли, и убитая номер три провела еще года полтора в морге той самой больницы пока дело, наконец, не закрыли. 

Есть еще один небольшой парк за детским садом, где я когда-то училась падать с велосипеда. Там тоже кого-то отправили в мир иной. Еще один – в пяти минутах ходьбы и в нем вообще регулярно находят трупы. Половина из них, конечно, местные торчки, которые не могут правильно рассчитать дозу, но есть и те, кто умер слегка менее приятной и чуть более насильственной смертью. К примеру, начальник районного отделения полиции.

Кстати говоря, по дороге от моего дома в сторону последней из описанных локаций тоже есть парк. Не знаю, что там у них насчет убийств, но однажды у меня закончились сигареты, и я вышла на их поиски. Как раз достигла середины этого крохотного, тянувшегося вдоль проезжей части сквера, когда незнакомый мужчина подбежал ко мне и со всей дури заехал в челюсть.

Я ошалело взглянула на незнакомца и расхохоталась. 

Потное, осунувшееся лицо, зрачки как блюдца и челюсть пошла ходуном – да это тип был явно под белым. Он, не моргая, таращился на меня, очевидно, прикидывая, стоит ли нанести повторный удар. Потом как будто о чем-то вспомнил. Схватился за голову и кинулся прочь. 

– Постой, паровоз! – кулаки у меня чесались еще с вечера. – Куда ты погнал? 

– А НУ СТОЯТЬ, ПЕДРИЛА! – заорала моя мания.

Ей было все равно на то, что тот тип мог уложить меня одной правой. 

– Я не усну, пока не узнаю, зачем ты меня двинул!

Но мужик оказался бывалый. Он перепрыгнул через забор и довольно быстро исчез из поля зрения, так что мне пришлось возобновить поиски никотина.

Короче говоря, парки в этом районе так себе.

Так вот, обычно местный ночной беспредел меня едва ли волновал. Порой я даже сама являлась его частью. Но не сегодня. Этим вечером моя психика была особенно уязвима.

*Не думай о нем.*

Биполярка вообще странная штука. То ты пляшешь, поешь, и трахаешься как под спидами, а затем на полставки подрабатываешь комиком и опять трахаешься. Не можешь спать (слишком перевозбужден) и не можешь есть потому, что чувство голода куда-то улетучивается. Тем не менее, окружающие считают тебя душой компании и вечно зовут на тусовки. Самые отважные умудряются еще и влюбиться. 

Затем наступает депрессивный период, и ты опять не можешь спать, потому как слишком печален. Есть, кстати, не хочется по той же причине. Все самые страшные и болезненные воспоминания вырываются наружу, так что истерикам нет предела. Сначала это кратковременная злость, затем пара гордых слезинок, а потом истерика, сменяющаяся полноценной панической атакой. Длится она от пары минут до одного-двух часов, в зависимости от окружения и желания жить в целом. Зачастую, в борьбе с припадками, мне приходилось оставлять на конечностях порезы и ссадины различной глубины. Чтобы хоть как-то угомониться. 

По весне завидев шрамы, люди почему-то думают, что я каждый день начинаю с того, что сажусь на край кровати с намерением вскрыть себе вены. Как будто я не в курсе, где эти самые вены находятся. Все дело в том, что временами острая физическая боль становится единственным способ отвлечь себя от печали. Порезы – это не страшно. Разбитое сердце, душевная боль, одиночество и, в конечном итоге, немое отчаяние – вот это куда страшнее, ведь именно они вызывают желание распрощаться с жизнью. 

Такими днями общаться с людьми совершенно невозможно. Они мало что понимают. Вечно ждут от тебя забавных историй, обилия шуток и прочих признаков веселья. Люди привыкли видеть меня такой. Всегда и везде. Это смешно, но порой, соприкасаясь со мной во время депрессивной фазы, некоторые из них чуть ли не злятся на мою грусть и молчаливость. Капризничают и топают ножками, требуя веселья, к которому так привыкли. Разочаровываются, называют скучной и оскорбляются нежеланием вести бурную ораторскую деятельность. Проверку депрессией проходят единицы, но даже они не способны меня спасти. 

В итоге внутри не остается ничего кроме боли. И скоро ты вновь призраком слоняешься по городу в кромешном одиночестве.

Биполярное аффективное расстройство – вот официальное название того, чем я страдаю. Или наслаждаюсь. Этот вопрос никогда толком не проясняется. Впервые увидев список симптомов БАР-а, я, мягко говоря, охренела. Выглядело все так, словно кто-то просто наблюдал за мной на протяжении двадцати лишним лет, а затем собрал воедино все черты моего характера и назвал это биполярным расстройством. Отвратительное, скажу вам, чувство. Вот живешь ты себе, жалуешься на жару, пьешь вино и пишешь свои книги, а затем вдруг понимаешь, что никакая ты не творческая личность, а всего лишь очередная психбольная. Все твои достоинства, отрицательные качества, привычки и даже так называемые изюминки – это все лишь признаки психического расстройства, которым болеет 2,4 % земного населения. Как вам такая новость?

Кухонные часы показывали полночь. 

Суббота закончилась. Пьяницы остались.

