# 4{-}

Тринадцатое утро мая две тысячи шестнадцатого года встретило меня умеренной погодой – редкое явление в моих родных краях. За окном обнадеживающе светило солнце, но было довольно прохладно. Самое то для дальней поездки. Дни работы за стойкой приучили меня выползать из постели сразу же после пробуждения. Или вообще в нее не ложиться, если чувствуешь, что не сможешь проснуться вовремя.

Это работало, даже если я уснула с рассветом, так что я в кои-то веки не пропустила свой автобус и даже на него не опаздывала. Сказать больше, мне удалось сделать укладку и нарисовать шикарные стрелки. Вот они, прелести выходного дня.

Выпив кофе, я прихватила небольшой, но довольно увесистый чемодан и поспешила покинуть пределы родного гетто. Уже на улице остановилась напротив сигаретного киоска, который, казалось, находился здесь всю жизнь. 

Я позволила себе слегка забыть о времени, зачем-то разглядывая многочисленные ряды пестрых сигаретных пачек. К тому моменту я не курила уже практически пять месяцев и, как мне думалось, не собиралась. Но что-то заставило меня потянуться в карман за парочкой купюр. Наверное, все дело было в волнении, а точнее, в его отсутствии. Мне всегда думалось, что встречи с незнакомцами тем и прекрасны: ты ничего от них не ждешь. Как и внутри, внешне я оставалась абсолютно спокойной. Только вот внутренний голос откуда-то из глубин подсознания мягко напоминал, что обычно паника подкрадывается ко мне в последний момент. Меньше всего на свете мне хотелось обнаружить себя поддающейся нервному припадку где-нибудь на границе двух внезапно враждующих стран. 

– Пачку «Винстона». Синего.

Я без особых зазрений совести расплатилась за сигареты. Так и закончилась моя борьба с никотиновой зависимостью.

Автобус отходил в четверть десятого, и теперь я таки на него опаздывала. В салон я вошла за секунду до отправления, соблюдая старые добрые традиции. Такой вот я человек: ну просто ненавижу ждать, а потому никогда не выхожу из дому заранее. На этот раз мне повезло. Дверь за моей спиной захлопнулась, автобус тронулся, и спустя четверть часа я уже наблюдала за бесконечными полями да деревьями, что проносились за окном. Тем днем я читала «Бродяг Дхармы», что очень кстати описывало наступивший период моей жизни. Книга уже подходила к середине, а мы все ехали и ехали. Несколько раз проезжали какие-то населенные пункты – ПГТ или вроде того, – но было заметно, что до Крыма по-прежнему как до Луны. 

Откровенно говоря, в Крыму я не была лет шесть, да и настоящих отношений у меня уже года три как не было. Словом, я понятия не имела, что меня ждет. Жизненный опыт подсказывал, что надежней всего будет не ждать ничего. В конце концов, рушащиеся надежды – это всегда неприятно, и лучший способ избежать подобной ситуации – попросту их не иметь. 

Часов через шесть автобус наконец остановился. Водитель объявил, что через полчаса будем на границе, и отправился пить кофе. Внутри меня что-то ёкнуло. Впервые за много-много лет. Это меня обескуражило и я поспешила выйти на свежий воздух.

Одного быстрого взгляда хватило, чтобы понять, что я нахожусь прямиком в центре какого-то украинского захолустья. Здесь люди курили под табличками «Не курить!», громко ругались матом при детишках и сидели на асфальте, когда рядом пустовала скамейка. В принципе, ничего необычного. Мы, южане, и не такое видали.

До отправления оставалось минут двадцать пять, так что я заглянула в одну из местных лавчонок. Это крохотное помещение едва превышало размеры туалета хрущевки. Все же каким-то мистическим образом в него вместилась барная стойка, кофемашина, парочка стульев со столиком, телевизор и даже одно окно. Правда небольшое. 

Еще внутри безымянного заведения обнаружились бармен, бариста, повар, продавец, кассир и фиц в одном лице. Девушка так резко выпрыгнула из-за стойки, что я бы обязательно подскочила, не будь я в тот момент где-то далеко в своих мыслях.

– Посетитель! – радостно воскликнула девушка. – Вы – наш первый посетитель за сегодня! Что будете?

Я слегка удивилась отсутствию акцента, характерного для подобных поселений. Затем взглянула на часы. Дело шло к вечеру. Поздновато как для первого посетителя.

– Капучино.

– Но у нас только латте и американо…

– Латте вполне подойдет.

Девушка кивнула и принялась возиться с кофемашиной. Та издавала предсмертные звуки, и я очень надеялась, что успею выпить кофе, прежде чем она развалится.

– Меня зовут Тома, – представилась девушка. – Вы недавно у нас?

По всем канонам современного бодипозитивного общества Тома выглядела вполне привлекательно. Это была высокая брюнетка с яркими губами и практически под ноль стриженными волосами. Не толстая и не худая. О таких обычно говорят «в теле». Черты лица – очень выразительные и чувственные. Все это в совокупности с откровенно мужиковатой одеждой походило на стиль, популярный во времена Твигги.

– Проездом, –  ответила я и расплатилась за кофе.

Тома окинула меня взглядом.

– Красивые волосы, – заметила она. – Настоящие?

Что ж, дамы и господа, а вот и лидер среди наиболее часто задаваемых мне вопросов.

– Более чем.

– А далеко едешь-то?

– В Севастополь.

– Ух, далековато. И что там, в Севастополе?

Этот вопрос вызвал в моей голове небезызвестную цитату из «От заката до рассвета», но я как-то удержалась.

– Мужчина.

– Хороший?

– Не исключено, что моей мечты, – я пожала плечами. – Но это не точно.

Протяжно вздохнув, Тома облокотилась о стойку.

– Я тоже была здесь проездом, –  заметила она.

– И что так?

– И у меня тоже был мужчина. Как раз возвращалась к нему, когда парня встретила. Влюбилась. Вот разводимся с ним сейчас.

– С которым из них? – не поняла я.

Незнакомцы отчего-то так любят изливать мне душу. Возможно, как-то ощущают мою эмпатию, но в подобные моменты я всегда чувствую себя неловко, если у меня вдруг все в порядке. 

Что ни говори, я в кои-то веки не страдала из-за разбитого сердца, не болталась на дне депрессии, куда обычно приводят творческие амбиции, и даже была немножечко счастлива. Мне сделалось неудобно. Пожалуй, никому не должно быть неловко за отсутствие жизненного дерьма, но мне почему-то стало. Я подумала, что, возможно, именно так себя и чувствовали мои друзья на протяжении парочки последних лет.

– Да со вторым уже.

Я подняла стаканчик с кофе.

– За несбывшиеся мечты.

Тома улыбнулась, но как-то грустно. Можно понять.

Я вспомнила о времени. Минута до отправления. Ну, все как обычно.

– Мне пора. Спасибо за кофе.

– Как тебя звать-то? – вспомнила Тома.

– Елизавета Васляева.

– Ну, удачи тебе, Елизавета Васляева. Главное, замуж не выходи.

– Постараюсь, – уже в дверях ответила я.

