# 5 {-}

Мы подъезжали к украинско-русской границе. Народ уже толпился у выхода из автобуса. Люди так настойчиво прокладывали себе путь, что я удивилась, как это еще никто не умер. Какая-то масштабная мадам, правда, завалилась на себе подобную, и вскоре обе уже распластались вдоль салона. 

Всего нас было тридцать три человека, не считая водителя. Прямо как годиков одному знаменитому божьему сыну. Тридцать человек спорили у входа, пытаясь первыми проникнуть к отделу с багажом. Еще две женщины поднимались с пола. Они выглядели сонными и обессиленными, но по инерции продолжали браниться. Завершая общую картину, я сидела в самом конце салона. Читала книгу и краем глаза поглядывала на происходящее вокруг. Багаж – если таковым можно назвать чемоданчик размером с ноутбук – и так был при мне. 

Украинско-российская граница, как выяснилось, больше походила на декорации к первому сезону «Ходячих мертвецов», нежели на хорошо охраняемое место переправы. То тут, то там виднелись полуметровые цементные блоки и целая куча хаотично разбросанной колючей проволоки. Еще одним фактором, производившим странное впечатление, выступали припаркованные повсюду автомобили. Большинство из них были с распахнутыми дверцами и опущенными стеклами, тогда как водителей внутри не наблюдалось. Те растерянно бегали от одной будки к другой, пытаясь правильно заполнить целую стопку бумажек, каждая из которых нужна лишь для получения следующей.

У импровизированного начала границы стояло несколько военных. Ребята были при параде, включая дубинки и огнестрельное. Фонари горели как-то вяло и, хотя солнце еще только подумывало садиться, становилось ясно, что освещается лишь первая пара метров переправы. Кстати говоря, такой же участок пути имел более-менее вменяемое дорожное покрытие. За ним пешеходов ожидали овраги, трещины, камни и прочие достопримечательности моего родного края. 

Учитывая обстоятельства с ручной кладью, к пункту проверки документов я подошла первая. Вернее, поначалу мне так казалось. Но довольно возрастная женщина внезапно воткнулась прямо передо мной и уже самодовольно махала рукой какому-то не поспевающему за ней мужчинке. По ту сторону границы нас ждал другой автобус. До отправления оставалось больше часа, так что особой нужды в такой спешке не было. Как, видимо, и в вежливости. 

– Куда едете? – спросил не поддающийся определению по половому признаку голос из будки.

– Севастополь.

– Причина визита?

– Пока под вопросом.

Пауза.

Окошко распахнулось, и на свет божий выползло заспанное личико немногим старше моего собственного. 

– Назовите причину визита, – раздраженно повторила барышня. 

– Просто хочу кое-что проверить.

– Нет, так нельзя.

– А как можно?

– Бизнес, туризм или личная.

Так я совершенно неожиданным для себя образом узнала, как можно. Что бы это ни значило.

– Что пишем? – напомнил о себе голос из окошка.

Я призадумалась. Очевидно, что мой визит относился к категории личных. Однако опыт минувших взаимоотношений с другими представителями земной расы показал, что ни в коем случае нельзя вешать ярлыки. Никакие. Даже если все кажется идеальным. Нет, особенно если все кажется идеальным! Более того, дело здесь не в возможной реакции других людей, а в твоем собственном подсознании. Я имею в виду, как только ты называешь мужчину своим молодым человеком, ты подсознательно начинаешь ждать от него определенную модель поведения. И чем больше его действия походят на те, что ты там себе успела придумать, тем сильнее ты расслабляешься. И тем болезненнее в дальнейшем будет принять суровую реальность. 

Словом, в я только-только свыклась с мыслью об отсутствии разбитого сердца в моей грудной клетке и никак не была готова признать связь с Вениамином личной. Поэтому я ответила:

– Бизнес.

– Во-о-от как, – работница таможни подняла бровь с той самой грациозностью, с какой бывалая проститутка поднимает юбку по окончанию тяжелого рабочего дня. Вроде как и лень, но по статусу положено. – И кем вы работаете? 

– Я писатель. 

– Вот как, – повторила она. – И что, прямо пишите?

– Преимущественно. 

– Вот как.

Мне вдруг стало очень смешно. 

– А работаете-то кем? – не унималась мадам.

Я положительно не хотела слышать четвертое «вот как», поэтому решила сдаться.

– Барменом.

– Так и напишем, – подытожив, она протянула мне небольшой бланк. – Распишитесь внизу.

В графе причина въезда был подчеркнут «личный визит». Я выдохнула:

– Вот как…

<div style="text-align: center;">***</div>

Ох, чего только я не наслушалась перед выездом. Одни рассказывали мне душетрепательные истории о том, что на границе рвут документы. Вторые убеждали, что стоит мне запеть гимн Украины, и меня тут же повалят на асфальт. Не то чтобы я каждый день занималась подобными развлекательными программами, но кто это проверил и зачем? Была еще история про курицу.

Вообще в моей жизни как-то подозрительно много бесполезных историй, что так или иначе связаны с курами. Понятия не имею, что это значит, но, пожалуй, что ничего. Так вот, подруга матери бывшего администратора «Штиля» решила поехать к племяннику, который остался жить на полуострове. Будучи коренной украинской бабулей, она прихватила с собой целую кучу еды, включая сырую курицу огромных размеров. Увы, правила запрещали перевозить продукты. В случае их обнаружения нарушителя заставляли пройти весь путь обратно – от российской границы до украинской – и оставить еду там, заполнив соответствующие бумаги. Если же ты спешишь на автобус, можно просто отдать еду пограничникам. К чему это я? Легенда гласит, что суровая бабуля съела свою злополучную курицу прямиком при служащих таможни. Сырой.

Стоя в очереди позади лишенной такта женщины, я мысленно решила, что она вполне могла бы быть той самой бабулей, и теперь изо всех сил старалась не рассмеяться: перед глазами уже вовсю плясали живописные образы.

Проверка багажа не заняла много времени. Сникерс у меня не отняли и на откупоренную в дороге бутылку виски тоже никто не позарился. Подхватив платье свободной рукой, я шагала по широкой, отвратительно вымощенной дороге, которая с каждым новым метром становилась все хуже. Мелкие камешки то и дело норовили застрять в подошве моих ботинок. По обе стороны от этой недотрассы тянулись небольшие овраги. За ними – высоченный забор из нержавеющей проволоки. Дальше виднелись бесхозные поля, кустарники и кое-какие деревья. 

По мере моего приближения к русской границе забора становилось все меньше, а деревьев – больше. Вскоре они уже занимали все пространство вдоль дороги. Благодаря размерам своего чемодана, я неплохо оторвалась от других пассажиров. Порой на пути мне встречались люди, идущие в противоположном направлении. Еще реже проезжали автомобили, но в основном я шла одна.

Раскинувшиеся по обе стороны дороги виды создавали иллюзию заброшенности. Казалось, я была единственной, чья нога ступала на эту землю на протяжении последних десятилетий. Тишина, покой и нетронутая природа. Все это напоминало мне пейзажи из документалок о Чикатило, которые я любила смотреть в детстве. Окончательно картину дополнил проржавевший автомобиль, наполовину утонувший в грязи. Стекол на нем не было, как и колес. Сквозь дверцы уже успели прорасти впечатляющих размеров сорняки. Как ни странно, машина удачно вписывалась в обстановку. Думаю, она и сейчас там стоит.

*Самое то для внеплановой медитации*, решила я и забралась на крышу бесхозной машины.

Благодаря эйдетической памяти и своей творческой натуре я без труда могла переместиться куда угодно. Вот только не всегда могла это контролировать. Воображение, на этот раз слишком живое, унесло меня к глубоко похороненным страхам прошлого, так что от медитации пришлось отказаться. 

В воздухе запахло морем. Наконец вдалеке стали видны какие-то светящиеся вышки. Спустя минут семь мне преградил путь шлагбаум в компании молодого солдата. Парень попросил показать паспорт. 

– Наркотики, оружие, спиртное перевозите? – серьезно спросил он.

– Целую кучу, –  ответила я.

Чемодан открывать не стали.

– Дальше по дороге идти нельзя, – заметил солдат. Я вопросительно подняла брови. – Такие правила. Пройдите во-о-он туда.

Он указал на начало очередного забора. Подойдя ближе, я ужаснулась. Нет, я, конечно, знала, что в России мало сторонников демократии, но не до такой же степени! В общем, вы в курсе, как выглядят наружные тюремные коридоры? Те, по которым зеков обычно ведут из одного крыла в другое? Такие узенькие площадки максимум метр в ширину, с двух сторон огражденные высоченным забором все с той же колючей проволокой на верхушке. Именно так выглядит начало российской границы. 

Оценив ситуацию, я подкурила.

<div style="text-align: center;">***</div>

Спустя полчаса я наконец забралась во второй автобус. До отправления оставалось более двадцати минут, и я понятия не имела, как их провести. В другой ситуации я бы, наверное, уже давно умерла со скуки. Но не сегодня. Сегодня у меня был виски.

Конечно, я в сотый раз повторяла себе, что не стоит ждать ничего серьезного от предстоящей встречи. И все-таки я ждала. Вернее, та часть меня, которая заставляла мою внутреннюю феминистку забиться в угол. Предвкушения чего-то хорошего – вот к чему я питала особую зависимость. Только в подобные волнительные моменты я могла почувствовать себя живой. 

Откровенно говоря, и спустя годы, вспоминая вечер на таможне, я все так же чувствую послевкусие той необъяснимой эйфории, которая настигла меня за несколько часов до встречи с Вениамином. Автобус больше не казался мне душным, погода жаркой, а жизнь дерьмовой. Я сидела в конце салона, наблюдая за тем, как уже успевшая полюбиться мне лесополоса принимает солнечные ванны, и чувствовала себя как никогда восхитительно.

Это меня расслабило. Вскоре я прикрыла глаза и позволила памяти ненадолго вернуть меня в прошлое.
