# &nbsp; {#chapter-7}

Никто понятия не имел, когда должен прийти мой автобус. По предварительным расчетам время прибытия – около шести часов вечера. Но зная отечественную пунктуальность, я в этом очень сомневалась. Веня жил в пяти минутах езды от автовокзала, так что мы условились на том, что я поймаю вай-фай где-нибудь на подъезде к Севастополю. 

Как ни странно, мы ехали без остановок, если не считать внезапной поломки автобуса. Следующий пришлось ждать посреди какого-то захолустья, так что вай-фаем там и не пахло. В итоге до пункта назначения я добралась лишь когда стрелка на часах стремительно приближалась в десяти вечера.

И вот автобус наконец остановился. Я выбралась на улицу и сладко потянулась. Первым, что привлекало внимание, был свежий морской воздух. Вдохнув его, я вдруг поняла, как же сильно истосковалась по бризу. 

Солнце, конечно, уже давно село, прихватив с собой тепло весеннего дня. На мне было легкое платье в пол со спущенными плечами, которое теперь мелодично колыхалось в такт ветру. Становилось как-то прохладно. Вдоволь надышавшись морем, я осмотрелась в поисках подходящего заведения. По-прежнему никаких признаков беспроводного интернета. Естественно, местной сим-карты у меня тоже не было, а моя уже часа четыре как перестала быть активной.

В какой-то степени тот факт, что на вокзале не было Вениамина, сыграл мне на руку. Таким образом я могла еще раз все обдумать. И все же, казалось, кто-то уже давно обдумал все за меня. Несмотря на бешеную усталость и практически полное отсутствие сна, я все еще чувствовала себя отлично. Вполне нормальный расклад. В рассвете бессонницы настоящая усталость обычно накрывает день на третий, а то и пятый, когда к ней подключается светомузыка.

К сожалению, здание вокзала не смогло вместить в себя что-либо кроме касс да комнаты ожидания. Пройдя сквозь нее, я вышла на улицу с обратной стороны и обнаружила, что пошел дождь. Стоило сделать пару шагов к проспекту, как ко мне тут же подбежала организованная группировка таксистов. Тут-то я и вспомнила о том, что адрес Вениамина остался в переписке, так что без интернета было не обойтись.

Как вы уже поняли, я никогда не отличалась привычкой планировать наперед. Если дело касалось работы, тут я стратег высшего разряда, но когда речь заходит о личном комфорте – только хардкор, только импровизация.

– Подвезти, красавица? – хором спросило сразу несколько мужчин.

Я улыбнулась их синхронности. Города меняются, а таксисты везде одинаковые.

Вдалеке я заметила заправку. Она находилась в паре светофоров от меня и походила на те, в которых обычно продаются подозрительно дорогие хот-доги. И есть вай-фай. Таксисты еще что-то продолжали спрашивать, когда я ступила на первый пешеходный переход.

– У вас виски есть? 

– Только кофе с виски.

– Давайте самый большой.

Если верить табличке на входе, до закрытия оставалось всего ничего. Но стоявшая за прилавком женщина никуда не спешила.

– Паспорт с собой? – спросила она.

– Паспорт?

Я даже не сразу сообразила, в чем здесь дело.

– Да, покажите паспорт. Лицам моложе восемнадцати выпивать не положено.

– Да вы гоните! 

Даже не знаю, что меня удивило больше: проверка документов на заправке или то, что кто-то назвал ирландский кофе выпивкой. Я еще немного повыделывалась, прежде чем предъявить документы.

Здесь и впрямь был беспроводной интернет. Только вот доступ к нему ты мог получить лишь через местную сим-карту, которой у меня, как мы все уже поняли, не было. Еще и виски ненастоящий! С таким же успехом я обошла еще несколько заведений. Дождь заметно усилился и вот-вот обещал обратиться ливнем. Тогда-то на моем пути встретился какой-то местный фастфуд.

Внутри было пусто. Три столика и все свободны. За прилавком стояла полная девушка. Она красила ногти в желтый цвет и, кажется, была не слишком рада моему визиту.

– Мы закрываемся через шесть минут.

– Мне нужно иметь сим-карту, чтоб подключиться к вашему вай-фаю? – на одном дыхании выпалила я.

Девушка взглянула на меня как на умалишенную. Мне, в общем-то, было не привыкать.

– Нет. Но вам как бы надо бы чё-та купить.

– Латте, – заказала я. – Самый большой.

Людей на улицах было поразительно мало, что создавало особенно приятную, тихую атмосферу. Сидя за столиком у окна, я наблюдала за тем, как потоки дождевой воды текут вдоль улицы, и наслаждалась тремя минутами, оставшимися до закрытия заведения. Мне наконец удалось подключится к сети, и я ужаснулась количеству входящих сообщения. Кажется, Вениамин не на шутку разволновался. Я опоздала на четыре часа, а внезапно разыгравшийся шторм изрядно добавлял ситуации трагизма. 

Успокоив Веню, я пообещала ждать в холле вокзала. Вечер обещал быть интересным.
