# &nbsp; {#chapter-8}

Эта сцена не раз мелькала в моих мыслях до нашей первой встречи с Вениамином. Слушая его голос, собираясь на последний перед отпуском рабочий день, стоя за барной, отправляясь ко сну, сидя за рукописями и бегая за постоянно заканчивающимся льдом, я представляла, как впервые увижу его. Но еще чаще я думала о нашем с Веней знакомстве уже после того, как оно состоялось. Когда наполняла бокал вином, готовила ужин, гуляла около моря, ждала свой кофе в какой-нибудь забегаловке, смотрела, как он точит ножи или засыпает прямо посреди комнаты… 

И особенно сильно я думала о том вечере после очередной ссоры. Как бы ни обстояли дела, несмотря на всю горечь обиды, одно лишь это воспоминание было способно растопить лед, возникший в моем сердце. 

Скажи мне кто-нибудь, что писать о собственной жизни будет так сложно – ни за что бы не поверила. Казалось бы, ничего не нужно, ведь ты и так все знаешь и помнишь до мелочей. Ты часть истории, по отношению к которой твои собственные пожелания, по сути, не имеют никакого отношения. В этом-то и проблема. Произошло то, что произошло и все, что тебе остается – проанализировать события и отойти в сторонку, притворившись обычным наблюдателем. Есть второй вариант, не подразумевающий сохранения ясности ума, так что мы его опустим. 

Говорят, мне повезло с памятью. Я помню все имена, даты, события, диалоги и так далее до подробнейших деталей. Могу без труда вспомнить, во что был одет человек пять лет назад, что он говорил, с каким настроением и почему. Могу сказать, какая за окном стояла погода, что за музыка играла в проезжающей мимо машине и о чем я в тот момент думала. Эйдетизм подразумевает собой особый вид памяти. Совокупность зрительных образов с показаниями остальных счетчиков твоего организма: слуховых, вкусовых, тактильных, обонятельных, двигательных и даже интуитивных. При правильной концентрации можно перенестись в любое место, достаточно лишь разок побывать там, но есть у эйдетики один жирный минус. В справочниках, правда, он подается как большой плюс, но что они в этом смыслят: «эйдетические образы отличаются от образов восприятия тем, что человек как бы продолжает воспринимать предмет в момент его отсутствия».

Отсутствие – ключевое слово.

<div style="text-align: center;">***</div>

Звуки и запахи – это вообще отдельный разговор. Правильное сочетание этих элементов буквально открывает мне окно в прошлое. С такими манипуляциями памяти не мудрено влипнуть в депрессию.

Спустя год после болезненного расставания с Адамом мне нужно было съездить в Черниговскую область. Добиралась я, естественно, таким же разваливающимся поездом, каким когда-то добиралась к своему молодому человеку. Был прохладный осенний вечер сродни тем вечерам, когда я только раздумывала о перспективе отношений с Адамом. Тогда у меня были духи с запахом лаванды. Они пылились на полке с две тысячи тринадцатого, и черт меня дернул воспользоваться ими тогда, оправляясь на железнодорожный вокзал. 

Запах парфюма и шум поезда буквально свели меня с ума. Картина перед глазами оставалась прежней, но в какой-то момент, я была уверена в том, что мне все еще девятнадцать, а поезд везет меня в Москву, и уже утром меня встретит туман Киевского вокзала. Из толпы на перроне покажется Адам –  в своей старой кожаной куртке – и поспешит навстречу, чтобы помочь спустить с поезда тяжелый чемодан.

Не мудрено, что Шульц так ярко описывал приступы шизофрении с примесью самоубийств, возникшие в итоге настойчивых попыток вызвать из памяти эйдетические образы. Но что делать, когда они всплывают против твоей воли?

История закончилась тем, что я вылетела на улицу при первой же возможности, а затем стояла посреди какой-то неизведанной сельской местности и наблюдала за тем, как состав плавно удаляется в сторону заката.  

Последнее, кстати, вовсе не метафора. В этот момент солнце действительно опускалось за горизонт, приглушая осенние оттенки. Я смотрела на исчезающий за небосводом алый диск, опавшие листья и разноцветные деревья, колышущиеся на ветру. Смотрела и думала, какая же я дура.

<div style="text-align: center;">***</div>

Вернемся к относительной реальности.

Первая половина мая шестнадцатого подходила к концу. Закинув ногу на ногу, я сидела в крохотном зале ожидания, который, по совместительству был холлом, а также единственной комнатой в здании севастопольского вокзала. Кроме меня здесь никого не было, так что я позволила себе дважды покурить. Честно говоря, я настолько волновалась, что курнула бы еще не раз и отнюдь не табака, но как-то не хотелось создавать вокруг себя газовую камеру. Под дождь выходить тоже не хотелось, и я просто продолжала сидеть, закинув ногу на ногу. Сперва мне думалось, что я читаю, но спустя минут пять пришлось признать, что я уже раз семнадцатый начинаю один и тот же абзац, но так и не добираюсь до середины.

*Произносить в голове маячащий перед глазами текст и думать о чем-то на фоне – поразительная, но такая бесполезная способность человеческого мозга*, подумала я, и оставила книгу в покое.

По обе стороны от меня находились большущие старые окна, в которые я то и дело поглядывала. К тому моменту мои каштановые волосы уже были достаточно длинными и объемными, дабы за ними спрятаться. При этом они были вьющимися, что позволяло мне откинуть парочку прядей и незаметно бросать пристальные взгляды то вправо, то влево. Стоит ли говорить, что сидела я при этом прямо и расслабленно, упорно соблюдая видимость чтения? 

Вопреки всем моим усилиям, размытые потоки воды да отблески проезжающих по проспекту машин были всем, что я видела. В итоге я решила забить на это неблагодарное дело и попыталась еще раз погрузиться в книгу. К тому же, до окончания «Бродяг» оставалось всего ничего. Только вот я сама уже давно чувствовала себя той еще бродягой, но только сейчас впервые всерьез задалась вопросом: куда эта Дхарма меня приведет?

Я отбросила с лица надоедливую прядь волос – прядь в действительности крайне надоедлива, так что вы еще не раз прочитаете о том, как я ее отбрасываю – и склонилась над дорожным романом, когда дверь слева от меня распахнулась. Естественно, я знала, кто сейчас в нее войдет, но не стала поспешно отрываться от чтения. 

Знаете, говорят, что женщина может думать миллион мыслей одновременно. Вообще-то, так и есть. За те несколько секунд, которые понадобились Вениамину, чтобы подойти к моему креслу, я задала себе как минимум десять вопросов. 

*Подправила ли я помаду? До конца ли высохли мои волосы? Где мой паспорт? Зачем мне сейчас паспорт? Успела ли я втянуть живот? Не прилипло ли платье к груди? А если прилипло, то насколько это сексуально? Достаточно ли непринужденно я сижу? Не слишком ли непринужденно я сижу? Пахну ли я также хорошо, как пять минут назад?*

И так далее, и тому подобное. Не поверите, но я даже успела запомнить номер страницы, на которой остановилась. Сейчас это кажется мне смешным. Как и многое другое.

Позже Веня говорил, что я держалась с ним так, словно мне было глубоко насрать, и это его окончательно очаровало. Такой вот у меня бесполезный талант: выглядеть хладнокровно, когда на самом деле внутри все сжимается от волнения и сердце скачет как курс доллара в Украине с наступлением военного положения. Видимо, по этой простой причине я неплохой игрок в покер.

Так вот, дверь распахнулась. Спустя пару мгновений я позволила себе поднять глаза. Передо мной стоял высокий блондин с зелеными глазами и хемингуэевский бородой. На нем была фланелевая клетчатая рубашка, которую затем я видела так часто, что та успела мне надоесть, и невероятно ласковая улыбка, которую я видела еще чаще. Она мне никогда не надоедала. 

Откровенно говоря, я всегда думала, что предпочитаю длинноволосых брюнетов со смуглой кожей. Однако, увидев Вениамина, я поняла, что никогда не встречала мужчину прекраснее. У него была бледная кожа, длинный андеркат и профиль настоящего викинга. Волосы частично скрывала небольшая шляпа с полями. 

Веня улыбнулся мне еще шире, и я вдруг осознала, что пялюсь на него уже с добрых полминуты. С другой стороны, он занимался тем же, так что все было в порядке. Когда наши взгляды встретились, Вениамин развел руки, предлагая мне окунуться в его объятья. Хотя, учитывая путь, который я проделала тем днем, правильней было бы сказать «упасть».

Он обнял меня, не говоря ни слова. Так мы и стояли в полнейшей тишине пустующего вокзала. Где-то очень далеко продолжали шуметь автомобили, а дождь играл ночную мелодию на оконных стеклах и тротуаре.
