# 9 {-}

– Твой самый большой недостаток? – спросила я. 

Мы шли вдоль стеллажей небольшой винной лавки. 

– Я алкоголик, – спокойно ответил Веня. – Алкоголь – моя единственная проблема. Порой я не ведаю, что творю, отчего друзья зовут меня Невероятный Алк. Но в остальном я идеален.

Он ухмыльнулся.

Я обвела взглядом стеклянные бутылки.

– С вином тоже проблемы?

Он покачал головой.

– В основном с водкой.

– Отлично, – я протянула руку к красному полусладкому. – Тогда берем две.

Определившись с выпивкой, мы все так же продолжали прогуливаться вдоль винных полок. Веня держал меня за руку. Периодически я ловила на себе его смущенные взгляды. За прошедшие годы мужчины смотрели на меня по-разному. Большинство с желанием. Некоторые как на полнейшую стерву, но все с тем же желанием. Были даже те, в чьем взгляде читалось восхищение, но все это казалось мне поддельным. И вот, разгуливая по алкогольному кварталу, я осознала, что уже очень давно никто не смотрел на меня так.

– А твой? – поинтересовался мой спутник.

– Мой самый большой недостаток?

– Ага.

– У меня биполярное расстройство.

– Что это?

– Маниакально-депрессивный психоз, – объяснила я. – Мне это название даже больше нравится. Оно звучит понятней, но теперь считается оскорбительным, так что…

– Хорошо, давай поменяем правила, – предложил Веня. – Твой самый большой плюс.

Теперь пришла моя очередь ухмыльнуться.

– У меня биполярное расстройство.

– И в чем здесь проблема?

– Всегда по-разному.

– Например? – не унимался Веня.

Я вздохнула и закатила рукава, демонстрируя выдающуюся коллекцию шрамов с обеих сторон рук.

– И всего-то? – еще одна ласковая улыбка.

Я подняла рукав выше.

– Еще, бывает, сигареты об себя тушу. Это не симптом, а скорей последствия, но, говорят, окружающих напрягает. 

Мой спутник вручил мне бутылки и принялся закатывать рукава. Руки под рубашкой украшало куда большее количество шрамов. Они выглядели на удивление красиво, если не считать парочки партаков, одним из которых была эмблема супермена. Вот как нужно производить впечатление на женщину. Спрашиваешь о ее недостатке, а затем даешь понять, что для тебя это всего лишь пустяк. 

Я весело рассмеялась. То ли шрамам, то ли татуировке.

– Серьезно? – спросила я, вскинув бровь. – Супермен? 

– Как видишь. Терпеть его не могу.

– Так что же не перебьешь?

– Ну так в этом-то и смысл, – парировал Вениамин, направляясь в сторону кассы.

<div style="text-align: center;">***</div>

Звездное небо раскинулось над самым прекрасным из всех городов. Я видела в Севастополе уйму недостатков, но никогда не прекращала любить его. Думаю, с Вениамином было так же. 

Очарованные вечером и компанией друг друга, мы сидели на парапете посреди пустой улицы. Несмотря на то, что дождь практически закончился, Вениамин держал надо мной зонтик. Все это время мы то без умолку болтали, то не могли прекратить целоваться. Обе винные бутылки стояли рядом. Никто к ним даже не притронулся.

Первым молчание нарушил Вениамин.

– Твои волосы еще красивее, чем на фото.

– А что насчет остальных частей меня? – я повернулась к (своему?) мужчине, изображая пристальный взгляд.

– Ты очень красивая, Васляева. Именно такой я тебя и представлял. И ты лучший в мире собеседник. Я окончательно очарован.

Я покраснела. Впервые за долгие годы существу мужского пола удалось меня смутить. Заметив это, Веня лишь крепче прижал меня к себе.

Море находилась совсем недалеко. Ночной ветер доносил до нас его ностальгические нотки, создавая иллюзию оазиса. Я набрала полные легкие свежего воздуха и медленно выдохнула.

– Люблю я море.

– А я – тебя, – отозвался Веня.

Здесь мне должен был вспомниться Адам, то, как я призналась ему в любви на второй день знакомства и все такое прочее. Но он мне почему-то не вспомнился. Я вообще напрочь забыла о его существовании.

– Что ты сейчас сказал?  

Я в удивлении отстранилась, на что Веня лишь развел руками.

– Я люблю тебя, Васляева. 

– Секундочку. Ты признаешься мне в любви в первый день знакомства?

– Так и есть. Ничего не могу с этим поделать. Да и формально мы знакомы гораздо дольше…

*Где-то я это уже слышала.*

Казалось, вся моя болтливость иссякла. Я просто сидела, переводя взгляд с Вени на сигарету в его руке и обратно. Затем пришла к самому мудрому в сложившихся обстоятельствах решению и подкурила.

Тем временем Вениамин взглянул на часы.

– Совсем забыл о времени, ты ведь устала! – спохватился он. – Пойдем.

Так мы стали жить вместе, фактически зная друг друга не больше трех часов. 
