# &nbsp; {#chapter-10}

Следующее утро мы как-то пропустили. Нежились в объятьях друг друга, пока не заметили, что дело близится к вечеру. Вино так и стояло закрытым.

– Чем хочешь заняться? – спросил Веня, наблюдая за тем, как я выбираюсь из ванной.

– Хочу прогуляться.

– Поехали в центр? – предложил он.

И мы поехали. Несмотря на то, что солнце только-только село, снаружи отнюдь не было людно. Причем чем ближе мы подходили к центру, тем меньше пешеходов встречалось на нашем пути. Вероятно, это была старая часть города потому, как местами увиденное очень напоминало переулки Львова, что так дороги моему сердцу. Отсутствие публики создавало сказочное впечатление, словно не только этот вечер, но и все улочки, скамейки, парки – все это принадлежало лишь нам двоим. Словно мы – Маленький Принц, гуляющий по собственной планете.

– Я покажу тебе свое новое любимое заведение, – пообещал Вениамин.

– Питейное?

– Ну, а то! Тебе понравится.

Оказалось, что все горожане прятались по кафешкам. Мы проходили мимо множества баров, пабов, пиццерий и прочих угодий гедонизма, и в каждом из них виднелись переполненные залы. 

Должна признать, «Фикус» и впрямь был миленьким местом. Снаружи он выглядел как крохотное ретро-кафе, но на деле оказался куда больше. Выполненный в моих излюбленных тонах интерьер не мог не ласкать глаз: черные диванчики и такие же черные столики с матовым покрытием. В этом радужном месте мы сделали наше первое совместное фото. 

Шоты принесли на самом настоящем бревне, что было слегка необычно. И я говорю не обо всех этих выточенных подносах, что так популярны в социальных сетях, нет. Я говорю о самом настоящем бревне, которое можно встретить в лесу. 

Вслед за шотами за наш столик пожаловало пиво для Вениамина и винишко для Елизаветы. Девица за соседним столиком бесстыдно пожирала моего спутника взглядом на протяжении всего вечера, тогда как взгляд Вениамина не отрывался от меня. 

*Барышня, вы меня сейчас выбесите*, сказал мой взгляд.

Но девица не отреагировала. Она постоянно поправляла волосы, закусывала губу и оттягивала майку как можно ниже. 

Веня отлучился в уборную, и девица тут же подорвалась следом. Вероятно, она надеялась «случайно» столкнуться с ним в дверном проеме. Знаю я эти ваши женские штучки. Короче говоря, долго не думая, я запустила в уже начинавшую меня подбешивать барышню перечницей, после чего та села на место и тупо уставилась в пол. Как ни в чем не бывало. Неужели обязательно было до этого доводить?

Вскоре принесли ужин.

– За мою ненаглядную деточку, – произнес Вениамин, поднимая бокал. 

– За моего крымского дровосека, – ответила я.

Разрезав пиццу, Веня потянулся за солью и…

– Милая, а куда делся перец? – изумленно спросил он.

– Понятия не имею, – ответила я и приложилась к вину.

<div style="text-align: center;">***</div>

– Что не так? – спросил Веня, когда мы возвращались домой последним троллейбусом. 

Время стояло позднее, и мы опять были совсем одни.

Я лишь отмахнулась.

– Пожалуйста, скажи мне. В чем дело, любимая?

*Любимая*. Это слово вызвало во мне ураган противоречивых чувств, в основном состоящий от всяческих производных счастья и страха.

– Ты мне очень нравишься, – наконец, ответила я, – но люди слишком часто разбивают мне сердце.

– Черт. Ты любишь кого-то другого?

– Вовсе нет. Просто я боюсь открыться тебе. Боюсь своих чувств и того, какие у них могут быть последствия.

– И это тебя печалит?

– Не совсем. Мне кажется, что этот страх мешает мне почувствовать настоящую радость от того, что между сейчас нами происходит. Ты понимаешь?

– Я понимаю, что кто-то очень сильно тебя обидел.

Я вздохнула.

– Когда закончились твои последние отношения? – я пристально посмотрела на Веню. 

На этот раз по-настоящему.

– Перед новым годом.

– Но ты виделся с ней и после, не так ли?

Вениамин удивленно взглянул на меня.

– Нет, не виделся.

– Уверен?

Он слабо кивнул.

– А я вот думаю, виделся.

– С чего это ты взяла? – осторожно спросил он.

– С того, что большинство мужиков так делает. Спит со своими бывшими потому, что это удобно. Но только с теми, с кем они состояли в длительных отношениях. Когда секс уже входит в привычку.

– Ладно. Ты права.

– Так, когда ты в последний раз с ней виделся? – спокойно спросила я.

– В марте.

– Значит, два месяца. И ты считаешь, что уже готов к новым отношениям?

– Абсолютно, – без малейшей заминки ответил Веня.

– Ты ведь понимаешь, что это глупо вступать в новые отношения, когда ты еще не оправился от предыдущих? 

– Это не тот случай.

– Почему?

– Я ее не любил.

– А почему так уверен, что меня любишь?

– Твою мать! – внезапно воскликнул Веня. – Мы проехали остановку!

Я посмотрела в окно. Действительно, дом Вениамина остался позади, в свете ночных фонарей.

Пришлось возвращаться пешком.

– Послушай, я несколько лет переживала болезненный разрыв отношений, которые и длились то не особо долго. А все потому, что и до этого со мной поступали не самым лучшим образом. Сейчас я в порядке. Не как другие люди, конечно, но в порядке по сравнению с тем, как было. Но я не чувствую, что могу справиться с подобной ситуацией еще раз. К тому же, с каждым разом чувства все сильнее, а значит, и боль становится глубже. Иногда мне кажется, что от моего сердца уже совсем ничего не осталось. Одни лишь осколки, но затем оп, и новое предательство. И вновь эта режущая боль. Но это, наверное, хорошо. Значит, есть чему биться.

Вениамин слушал меня с самым серьезным видом. Он молчал и лишь подкуривал одну за другой.

– Я не обижу тебя, – уверенно произнес он. – Буду собирать твое разбитое сердце по кусочкам до тех пор, пока ты не почувствуешь себя в безопасности. 

Его голос звучал настолько искренне, что я с трудом сдерживала слезы.

– А потом?

– А потом просто буду любить тебя. Хотя постой… Я ведь уже люблю.

<div style="text-align: center;">***</div>

– Ну, так что, Васляева, ты дашь мне шанс? – спросил Вениамин.

Мы сидели на балконе. По правую руку расположилось море, по левую чернел лес, впереди мерцал ночной Севастополь. 

Я выпила целую чашку кофе прежде чем ответить на этот вопрос.

– И вот еще что, – между тем произнесла я. – Никогда не ври мне.

Он уже открыл рот, дабы что-то сказать, но я тут же продолжила.

– Нет, я серьезно. Никогда не думай врать мне. Особенно по мелочам как сегодня. Меня достаточно обманывали, чтобы я могла распознать ложь. Я это ненавижу. На самом деле, я многое могу простить, но не обман.

– Я тебя понял, – виновато произнес Веня.

– Так, когда ты в последний раз виделся со своей бывшей?

Он сделал небольшую паузу.

– Три недели назад.

– Хорошо.

– Так вот… Ты дашь мне шанс?

– Да, кажется, уже дала.

Услышав это, Веня буквально засиял. Даже в полумраке была видна его довольная улыбка. Мы еще долго целовались, слушая, как где-то вдалеке волны бьются о берег. 
