# 11 {-}

Сколько бы воды ни утекло, я по сей день считаю, что самые обворожительные вечера можно встретить лишь в Севастополе. В какой бы части города ты ни находился, бриз найдет тебя. Морской воздух и волшебные закаты. Слушая меня, можно решить, что все дело в моей любви к Вениамину Ларионову. Что ж, первые припадки взрослых чувства я испытала задолго до описываемых событий. Было это на родине Булгакова, Пастернака, Маяковского, Мандельштама… Список можно продолжать до следующей главы, но итог один: в Москву я так и не влюбилась. 

Севастополь же мигом покорил мое сердце. Этот горный городок с его извилистыми дорогами, сумасшедшим трафиком, гранитными набережными и залитыми солнцем скверами вызывал у меня необъяснимое чувство ностальгии. Вы когда-нибудь окунались в прозу Брэдбери? Я имею в виду не сай-фай, а настоящие, автобиографические тексты вроде «Вина из одуванчиков» и «Лето, прощай!»? Душевная теплота и приятная меланхолия с едва заметной толикой грусти – вот что несут в себе эти книги. Вот что несет в себе Севастополь. Здесь солнце садится гораздо позже привычного времени, а море практически никогда не замолкает. И как же поразительно севастопольское небо!

Тем не менее, дни в Крыму оказались куда более жаркими, чем мне представлялось. Будучи уроженкой юга, я все равно умирала от жары.

– Зачем вообще строить города в месте, где настолько жарко? – капризно спрашивала я, но Веня лишь рассмеялся.

Одним из таких убийственно жарких дней мы растянулись в постели. Веня лежал вдоль кровати, как и подобает нормальному человеку. Я же расположилась поперек, уложив голову на бедра своего благоверного и закинув ноги на стенку. Оба абсолютно голые. Я читала, Веня смотрел какое-то видео.

– Сестра написала, – сказал он.

– И что там?

– Говорит, бабушка уже обзвонила всех родственников. Рассказывает им, что я с невестой живу.

– С невестой? 

– Ну!

– А где она? Ты нас не представишь? – я улыбнулась, не отрываясь от книги.

<div style="text-align: center;">***</div>

Знаете, Жорж Санд ежедневно трудилась над своими романами до половины одиннадцатого утра. Она не останавливалась, даже если заканчивала книгу, а лишь откладывала ее в сторонку и бралась за новую. Вот так просто, без набросков, творческих перерывов и традиционных писательских сумасшествий в честь законченного романа. С другой стороны, Хемингуэй писал по пятьсот слов в день. Минимум. Он брался за работу с первыми лучами солнца и, бывало, засиживался до полудня. Буковски тоже здоровски писал, от десяти до тридцати страниц за ночь, которые потом вычитывал в разгар полуденного похмелья. Ну, и, конечно, Стивен Кинг – гуру писательского тайм-менеджмента. Пишет систематически да при любом удобном случае уже, должно быть, лет шестьдесят.

Подобных историй миллион, и я всегда мысленно восхищалась такими людьми. Дело здесь не в организованности и воодушевлении, с которым каждый божий день они начинали творить. Я говорю как раз о том, что в назначенное время все эти авторы могли спокойно закончить работу и вернуться к жизни. Что же касается меня… 

Это скорей напоминало распорядок дня Хантера Томпсона. Только на кокаин не всегда хватало, так что его приходилось заменять депрессией. Это, конечно, шутки, но! Томпсон вставал в 3 часа дня и активно начинал закидываться виски, коксом и табаком, изредка прерываясь на кофе, обед и курение травы, «чтобы снять напряжение дня». Затем снова кокаин, Чивас, трава и сигареты, к которым добавились капли кислоты и французского ликера, и вуаля:

*12:00, полночь, Хантер С. Томпсон готов писать.*

Такая же хрень преследовала меня по жизни. Процесс переключения с официально признанной реальности на мою собственную требовал чуть ли не отшельничества, а потому в бытовых условиях работы, проблем и социума занимал немало времени. Но стоит мне переключиться – к ужину не ждите и к завтраку тоже.

У меня есть отличная для писателя и ужасная для остальных аспектов моей жизни привычка. Я не могу оторваться от писанины, даже если знаю, что ужасно опаздываю. Прекрасно вижу, который час, осознаю, что должна была выйти из дома еще двадцать минут назад, но упорно продолжаю сидеть за рукописью, потому что все остальное становится чертовки неважным. И дело здесь не в том, чтобы просто закончить предложение, диалог или даже целую главу. На самом деле я попросту не могу остановиться, пока чувствую, что мне по-прежнему есть что сказать. 

Порой мне кажется, что ничего не изменится, случись хоть конец света. По сторонам будут раздаваться взрывы, мелькать вспышки и пролетать травмоопасные предметы, а я все так же преспокойненько продолжу сидеть, склонившись над текстом. Такой вот я человек.

Кстати, это касается не только письма. Чтение также частенько берет надо мной верх. С самого детства, о чем бы ни оповестили меня родители, я автоматически отвечала:

– Сейчас. Только главу дочитаю.

И не важно, что до конца этой главы может быть еще страниц пятьдесят. 

Скажу больше, однажды я даже проехала нужную остановку. Было это не где-нибудь в городе, а за его чертой, в незыблемой глуши наполовину заброшенных дачных товариществ. Прекрасно помню этот вечер. На улице стояла зима, минусовая температура. Мне было двадцать, и я обещала Мишель приехать последним транспортом. 

И вот я сижу у окна катившей прочь из города маршрутки. Вокруг все завалено снегом. На улице собачий холод и транспорт ходит ужасно. Мне повезло встретить водителя, дом которого находился в нужной стороне, так что я сижу у окна и читаю мемуары вдовы Йена Кёртиса. Кто-то в салоне заказывает мою остановку, и я уже вижу, что до нее остается парочка метров. Маршрутка останавливается, люди начинают выходить. 

*Сейчас, только страницу дочитаю*, говорит внутренний голос.

Следующее, что я помню – напрочь ошарашенный вид подруги, что ждала меня на остановке. Рот открыт, нижняя губа отвисла, глаза широко распахнуты. Ее лицо словно говорило: «Какого хуя?». Я пытаюсь подавить приступ подкатывающего смеха, но Мишель уже исчезает за горами снега, а маршрутное такси увозит меня в направлении загородного дурдома.

<div style="text-align: center;">***</div>

Спустя два года и одну незабываемую весну Веня задал мне какой-то вопрос. Случилось это как раз когда я достигла середины свежего кинговского рассказа. И я ответила в лучших традициях Елизаветы Васляевой: 

– Сейчас. Только главу дочитаю.

Мой ответ почему-то развеселил Вениамина. Он заулыбался, словно ребенок, и принялся покрывать мое лицо поцелуями. До сих пор не знаю, о чем Веня спросил меня тем душным майским днем. Хотя кое-какие подозрения все-таки имеются.

Наконец, на смену дню пришел вечер, которого – я уверена – с нетерпением ждали все четыреста шестнадцать тысяч двести шестьдесят три человека, проживающих в Севастополе весной две тысячи шестнадцатого. Жара отступила.

Вениамин недавно вышел из душа. Он курил, облокотившись на поручни балкона, а я сидела в тени, глядя на то, как его волосы цвета пшеницы игриво переливаются в закатных лучах. Мы много говорили, рассказывая друг другу о прошлом. Делились душевными переживаниями, открывали свои маленькие тайны и отвечали на неловкие вопросы. 

А еще мы много болтали. Щебетали обо всем подряд. Мы прожили вместе всего три дня, но, казалось, были знакомы вечность.

– Я словно знаю тебя всю жизнь, – сказал Веня. 

Он определенно читал мои мысли. 

– Ты просто перевернула мое представление о женщинах. Я никогда не думал, что могу быть так счастлив. И я так сильно люблю тебя.

– Ох, Веня…

– А ты со мной счастлива?

И я заплакала. От счастья. Впервые за миллионы световых лет.

<div style="text-align: center;">***</div>

Секс с Вениамином был потрясающим. Мы занимались им часами, прерываясь лишь на кофе и сигареты. До знакомства с Веней я особо не понимала, отчего вокруг куни создают так много шума. Оказалось, никто из моих бывших любовников просто не знал, как это делается. Но вот наступил тот день, когда миф о существовании оргазма от куннилингуса наконец перестал быть мифом.

О своей любви Вениамин говорил невероятно часто. Более того, он даже стал называть меня не иначе как «любовь моя», лишь изредка прерываясь на «деточку» и «любимую». Я же ни разу не сказала Вене о своих чувствах. Их становилось все больше, но у каждого из нас есть свои незавершенные гештальты, так что я просто не могла вымолвить эти три слова. Порой мне даже становилось от этого неловко.

– Итадакимас! – радостно крикнул Веня, доедая омлет, а затем добавил более спокойным тоном: – Было очень вкусно.

– Делов-то.

Он стал застегивать рубашку.

– Неля поднесет прайсы к остановке. Заберу их и сразу к тебе, – Веня уже натягивал джинсы.

В те дни Вениамин работал в одной относительно известной компании. Он был региональным супервайзером. Распространял продукцию для салонов красоты и барбершопов. Вопреки громкому названию, по Крыму у него было только двое подчиненных и большую часть работы Веня по-прежнему делал сам. 

Прекрасно помню наш первый телефонный разговор. Он состоялся за несколько недель до встречи. Это был день рождения моего бывшего, и я чувствовала себя крайне паршиво. Узнав об этом, Вениамин решил меня подбодрить. Я была на работе, в «Штиле», и Вене пришлось ждать до трех часов ночи, пока моя смена, наконец, не закончилась, после чего он как ни в чем не бывало принялся рассказывать все, что знал об оттенке моих волос. Монолога вышло минут на тридцать.

Я крепко поцеловала его и чмокнула в щеку. Для уверенности.

– Я люблю тебя, – весело попрощался Вениамин.

Не дожидаясь пока входная дверь захлопнется, я проскочила за ним в коридор.

– Венечка, – начала я. – Ты мне безумно нравишься, но ты ведь понимаешь, что сейчас я не могу ответить тебе тем же? 

Из-за этого я чувствую себя неловко каждый раз, когда ты говоришь, что любишь меня. Не пойми меня неправильно, но мне очень сложно привыкнуть.

– Привыкнуть к чему?

– К тому, что обо мне заботятся. К тому, что я кому-то дорога. К тому, что меня любят, в конце концов.

У Вени зазвонил телефон. Видимо, Неля уже ждала его на остановке. Не обращая на это никакого внимания, Веня сжал мою руку.

– Я буду ждать, – пообещал он, глядя в мои глаза.

Ждать пришлось недолго. 


