# &nbsp; {#chapter-12}

После обеда мы решили отправиться в лес. В распоряжении Вениамина была дряхленькая рабочая «Таврия». Сперва машина меня ужаснула (не столько потому, что я предпочитаю менее отечественного производителя, а лишь потому, что детство мое прошло в такой вот тарахтайке, а ребенком я и метра не могла проехать без того, чтоб меня не укачало), но вскоре эти поездки стали приносить нам немалую радость. В основном благодаря реакции окружающих. 

Просто представьте эту картину! С одной стороны Вениамин, сидящий за рулем, в своей несменной пижонской шапочке, с хвостом золотистых волос, одетый в рваные джинсы, вечную клетчатую рубашку и грубые незашнурованные ботинки; его руки в бесконечных шрамах и браслетах, а пальцы – в кольцах – весело стучат по баранке в такт музыке. С другой стороны я, сидящая на пассажирском, с мастерски уложенной шевелюрой, неизменными алыми губами, в макияже, достойном ковровой дорожки, и с огромным стаканом кофе в руках. Оба с сигаретами. Оба в татуировках. Оба влюблены. Несемся куда-то в разваливающейся на ходу «Таврии» да распеваем странные песни. 

  *When the truth is found to be lies*
  *And all the joy within you does…*

Короче говоря, реакция была что надо.

*Don’t you want somebody to love?*

– Давно ты водишь? – спросила я.

– Шесть лет, – ответил Веня, лихо выворачивая баранку.

Прежде чем объединиться с природой, мы остановились на заправке. Прогулялись вдоль рядов с безделушками, пообедали горячими сосисками и пополнили запас кофе. Так начались наши заправочные путешествия. На протяжении последующих месяцев мы с Вениамином побывали на множестве заправок и стали экспертами в вопросах вроде «где выбор шоколада больше, а пенка в капучино выше».

Веня всегда любил эспрессо, максимум – американо. Обычно вместе с ними давали крохотные шоколадки. Я же с подросткового возраста не признавала кофе без молока, но, в отличие от Вени, обожала шоколад. Порой у меня создавалось впечатление, словно он вовсе не хочет кофе и берет его лишь для того, чтобы порадовать меня очередной миниатюрной сладостью.

Нам нравилось завтракать на заправках. Была в этом какая-то особая романтика. 

В итоге мы отдалились от жилой зоны и теперь ехали вдоль деревьев с широкими кронами, что по обе стороны покрывали обочину. Вскоре мой Шумахер свернул на усыпанную песком тропинку. Вокруг все так и кипело зеленью. Приглушив музыку, мы полностью опустили стекла и какое-то время ехали молча, наслаждаясь умиротворяющей обстановкой. 

Разодетые в зелень деревья ласково шептались, периодически касаясь друг друга ветвями. Птицы щебетали невозможно громко. Их голоса перекрывали предзакатные порывы ветра. В воздухе по-прежнему пахло морем, но теперь к этому добавились еще и запахи лесных деревьев. Опьяняющее сочетание.

Придерживая страницы пальцем, я цитировала Вене Керуака: 

*Так бывает в лесах, они всегда кажутся знакомыми, давно забытыми, как лицо умершего родственника, как давний сон, как принесенный волнами обрывок позабытой песни, и, больше всего – как золотые вечности прошедшего детства или прошлой жизни, всего живущего и умирающего, миллион лет назад вот так же щемило сердце, и облака, проплывая над головой, подтверждают это чувство своей одинокой знакомостью.*

– Красиво, – заключил Веня.

Временами он бывал молчалив. Даже слишком. Я часами болтала, рассказывая о детстве, книгах, напитках, путешествиях и планах на будущее, а мой спутник лишь внимательно слушал. Однако чем ближе подбирался вечер, тем оживленнее становился Вениамин. Порой я даже уставала от его внезапной активности.

Спустя несколько минут тропинка стала совсем узкой. Мы вышли из машины. Подкурив, Веня тут же уселся на капот, привычно скрестив ноги. Он смотрел куда-то вдаль и затягивался своей до невозможности крепкой сигаретой. Таким я видела его миллион раз: в парках, дворах, у кофеен, на парковке, около моря и на проспекте. Махатма Ганди двадцать первого века.

Пройдя сквозь сосны, мы вышли на холмистую поляну, со всех сторон окруженную деревьями. Впереди был неглубокий овраг, и мы теперь шли вдоль него, взявшись за руки. Помимо шляпы, на Вене были классические брюки, черная рубашка и серая старомодная жилетка. Картину довершал алый атласный галстук. Неожиданный наряд для вечерней прогулки по лесу.

Закат близился, так что Веня уже увлеченно рассказывал мне что-то о маленьких острых перцах под названием халапеньо. В отличие от меня, он обожал острую еду. И, говоря это, я не имею в виду васаби или зернистую горчицу. 

– Я люблю что-то менее острое, – ответила я, когда Веня закончил свой монолог.

– А я – тебя.

Опять двадцать пять.

Сказав это, он продолжал весело шагать через поляну. 

– Правда?

– Что?

Я остановилась и взглянула на Вениамина со всей серьезностью, которая только может быть присуща двадцати двух летней девушке.

– Ты действительно любишь меня?

Он обхватил мое лицо руками и улыбнулся.

– Ну, конечно, люблю, деточка.

Сложно объяснить, что я почувствовала в тот момент. Кажется, я впервые восприняла его слова серьезно и разрешила себе мысли о мелькающем впереди хэппи-энде. Несмотря на то, что пошел дождь и на улице заметно похолодало, мне никогда в жизни не было так тепло.

Мы едва успели добежать до машины, когда дождь обратился ливнем.

<div style="text-align: center;">***</div>

Над городом бушевал настоящий шторм. Небо затянуло широкой серой пеленой, и только вдали виднелся крохотный просвет. Скопившиеся над Севастополем облака сочетали в себе все оттенки серого. Море превратилось в дребезжащее полотно; его синева сделалась почти черной. Одетые лишь наполовину, мы сидели, прислонившись к балконной стене, и наблюдали за разыгравшейся непогодой. 

– Очевидно, этим вечером придется остаться дома, – заметила я.

Веня ответил не сразу. Глядя в окно, он витал где-то в своих собственных мыслях. 

Тем временем я не отрывала глаз от Вениамина. Как и у меня, суммарно у Вени было три законченных татуировки. Ни одна из них мне не пришлась по душе, но недавно он сделал четвертую – античный профиль бородатого мужчины в венке, окутанный листьями. Татуировка мне нравилась. Она занимала целое предплечье, и временами во время секса я любила шутить, что из кустов за нами подсматривает какой-то мужик. 

За окнами стремительно темнело. Дождь сменился градом. На балконе стало слишком шумно и ветрено. Вспомнив о вине, мы поспешили внутрь.

До встречи со мной Вениамин провел в Севастополе всего пару месяцев. Сам он был родом из Керчи и, закончив одни и без того обреченные, по его словам, отношения, захотел переехать. Начальство предложило ему работать в Севастополе, на что Веня согласился без лишних раздумий. 

Теперь единственным интернетом, который оказался в распоряжении Вени, был мобильный, но и тот не особо гладко работал из-за расположенных неподалеку вышек. Мне нравилась такая изоляция. Никаких тебе обновлений, соцсетей и сомнительных сообщений от дальних родственников. Никаких сталкеров, хейтеров и прочих онлайн-личностей, о которых я даже не знала, чем заслужила такое внимание. 

Вместо этого каждый день, в одно и то же время, мы ходили в какое-нибудь тихое заведение. Я ловила вай-фай и созванивалась с близкими. Правда денег не всегда хватало, так что иногда мы делали вид, что читаем меню. Изучали его так долго, что я могла полноценно поговорить с подругами, а затем громко решали, что пойдем в другое место. Помню, как-то раз в поисках вай-фая мы даже зашли в кинотеатр и притворились, что ждем свой сеанс.

Как я сказала, мне даже нравился подобного рода интерактив. Но Веня уже успел истосковаться по прелестям беспроводной сети. В основном потому что он уже очень давно не смотрел хороших фильмов. Благодаря открытому интернету близлежащего паба мы обзавелись несколькими, и теперь мы погрузились в один из них.

– Как вино? – поинтересовался Веня, не успела я сделать первый глоток.

– Неплохо.

Вино оказалось паршивым, и это еще очень мягко сказано, но мы пили его так, словно это было какое-нибудь Inglenook Cabernet Sauvignon. Выдержанно, с наслаждением в глазах. Светский прием продлился ровно полбокала, после чего мы переглянулись и расхохотались.

– Дерьмо редкостное, – сквозь смех произнесла я.

– За девять лет алкоголизма не встречал такого дерьмового вина! – радостно согласился Веня.

Вениамину пришло сообщение. Очередной родственник удивлялся тому, что он женится. 

Вениамин удивлялся не меньше.

– Бабушка снова рассказывает, что я уже живу с невестой, – объяснил он.

Мы опять рассмеялись.

– Как вам такая новость, Елизавета Ларионова?

– Блестяще, Вениамин Алексеевич!

К тому моменту фильм уже закончился, и мы оба что-то читали.

– Слушай, – начал Веня спустя восемь страниц и один бокал. – Так а как ты на самом деле на это смотришь?

– М? – не отрываясь от книги, ответила я.

– Выходи за меня, – сказал Вениамин.

Книгу пришлось отложить.

