# &nbsp; {#chapter-13}

– Пойдем в ЗАГС? – весело предложил Вениамин.

Я рассмеялась. Он тоже улыбался, но как-то спокойно. Словно и впрямь ожидал от меня ответа.

– Постой. Ты это, что ли, серьезно?

– Более чем, – заверил Веня.

Я опешила настолько, что выпустила из руки бокал. Видимо, Веня был к этому готов потому, что успел его подхватить.

– Мы знакомы всего три дня, Веня…

– …И я за всю жизнь не был так счастлив, как за эти три дня.

Я молчала.

– Я, наверное, не так начал.

Вениамин встал с кровати, на которой мы сидели в обнимку, и опустился передо мной на колени. 

*А, ну это, конечно, меняет дело*, прокомментировал внутренний голос. Тот самый, который всегда говорил с сарказмом.

*Он встал на колени, и теперь это предложение совсем не выглядит странным.*

*ОН ВСТАЛ НА КОЛЕНИ! ОН ВСТАЛ НА КОЛЕНИ!* – заверещала в моей голове какая-то сумасшедшая.  

Вениамин взял мою руку, поднес ее к губам и трепетно поцеловал.

– Любовь моя, ты станешь моей женой? – он снял одно из своих колец, готовясь надеть его на мой безымянный палец. 

И я согласилась.

Чертов поцелуй руки. Всегда срабатывает.

<div style="text-align: center;">***</div>

Знаете эту старую песню, где девушка перечисляет вещи, о которых она думает, когда становится грустно? В моей вариации там были бы пёсики, лес, качественно приготовленный кофе, кладбища, бонги, горные просторы, пост-панк и, конечно же, литература. А еще в этот список непременно бы попал секс во время дождя. Ничего так не расслабляет, как монотонный звук барабанящих по подоконнику капель. Кроме, разве что, травки.

Следующая ночь показала, что секс после помолвки нравится мне куда больше. Просто ввиду очевидных причин я не имела об этом ни малейшего представления.

Наступившее утро встретило меня неожиданно солнечной погодой. Разбросав волосы на подушке, я сладко потягивалась, когда в спальню вошел Веня. Довольный и окрыленный. 

– Доброе утро, Венечка.

– Доброе утро, любовь моя.

Вскоре мы переместились на балкон и разделили между собой последнюю сигарету. Погода стояла невообразимая. Кажется, вчерашний шторм открыл этот тонкий портал между весной и летом. Море вновь было тихим, ветер мягким, небо ясным, а я – счастливой. 

– Как настроение? – спросила я. – Готов к рабочему дню?

Вениамин кивнул.

– А ты готова? Посмотришь, как я работаю.

Я кинула в ответ. Вслед за этим в комнате прозвенел будильник.

– Мы проснулись раньше будильника? – удивленно спросила я.

– Знаешь, сегодня я встал на рассвете. Вышел на балкон и просто наблюдал за тем, как над морем поднимается солнце. Я вижу этот пейзаж каждый день, но до сегодняшнего утра не понимал, насколько он прекрасен. Потом солнце встало. Я обернулся и увидел, как ты сладко спишь в моей постели. Солнце падало на твои локоны, отчего они становились медными. И ты улыбалась. Даже во сне. Тогда я понял, что это еще прекраснее, чем все рассветы и закаты мира. Хотя они меня никогда не волновали. Я стоял в дверном проеме и наблюдал за тем, как ты спишь, когда услышал в голове собственный голос. Он сказал: «Вот, Веня, там спит твоя жена». После этого я ощутил такое счастье и спокойствие, каких не испытывал ни разу в жизни.

Во-первых, это была самая длинная лирическая реплика из всех, что я когда-либо слышала от Вениамина, а во-вторых… Эти простые, но до невозможности греющие душу слова накрепко впечатались в мое подсознание. Словно кто-то взял волшебное перо и написал их прямиком на моем сердце.

<div style="text-align: center;">***</div>

Наш автобус плавно приближался к противоположной части города. Обед, а по совместительству и час пик. Салон переполнен. Солнце беспощадно слепило пассажиров, что сидели или стояли, или впечатались в спины друг друга. Вениамин занял одиночное место, сразу возле выхода. Я умостилась у него на руках. 

Соблюдая лучшие традиции пост-советского пространства, люди ссорились, обсуждали политику, проклинали погоду и выясняли, почем сайра на базаре. Большинство из них сидели, показывая сердитые, неудовлетворенные жизнью лица. Остальная часть пассажиров просто ехала с крайне отсутствующим видом.

Разделив наушники поровну, мы слушали старые рок-н-ролльные песни. И обнимались. Удивленные такой беспечностью, пассажиры то и дело бросали в нашу сторону не доверительные (а порой даже осуждающие) взгляды. 

Реакция, конечно, не такая яркая, как в случае с «Таврией», но тоже ничего.

– Мы самые крутые в автобусе, – шепнула я Вене.

В ответ на это он натянул на нос свои квадратные солнцезащитные очки и артистично подмигнул мне.

<div style="text-align: center;">***</div>

Ехали мы долго. Наконец, автобус притормозил на нужной остановке. Еще один спальный район, очень похожий на то место, в котором я выросла: многочисленные бетонные здания без малейшего намека на культурное развитие, куча гастрономов, парикмахерских и парочка супермаркетов. Кое-где, правда, были признаки озелененной части пространства, чуть более воодушевляющие, чем пятнадцатиметровые николаевские скверы.

Веня мотался по салонам, принимал заявки и относил заказы. Раз или два я заходила с ним, но чаще всего ждала на улице со своим привычным парадно-выходным набором: книга, кофе и сигарета. Помню, как я сидела на парапете, углубившись в чтение, и чувствовала тяжесть кольца, появившегося на руке прошлой ночью. Оно было вылито из серебра, широченное и очень тяжелое. Но это была приятная тяжесть.

Так прошло больше пяти часов. Впереди оставался лишь один заказ, покончив с которым, можно было с чистой совестью отправляться на ужин. Видимо, из-за отсутствия машины, сегодня мы оделись попроще: оба в старых джинсах и толстовках. У Вени был черный спортивный рюкзак, который тот повсюду таскал с собой. Была еще огромная палитра – глянцевая книженция с образцами красок его фирмы. Внутрь та не помещалась, так что Веня любил втискивать ее между спиной и рюкзаком. Я же шла налегке, если не считать дамской сумочки. 

Решив, что бетонная зараза нам положительно надоела, Вениамин и я прошли несколько остановок через уютную лесопосадку. Высокие деревья с двух сторон отделяли ее от шума дороги и захудалых двориков, так что можно было представить, что ты находишься в лесу. Кстати говоря, деревьями этими были не какие-нибудь там тополя, а самые настоящие ели и сосны. Землю под ними усыпали сотни шишек и тысячи сухих иголок. Черт его знает где Вениамин раздобыл здоровенную изогнутую палку и теперь шел рядом, изображая друида. 

– До KFC парочка кварталов, – сказал Веня.

Как выяснилось позже, где-то на этом отрезке пути я на него и запала. Окончательно и бесповоротно.

