# 16 {-}

Ближе к полудню я нехотя выбралась из постели. Вене предстояло обойти долгий список салонов, и мой жених уже вовсю носился по квартире. Одной рукой он держал чашку со вчерашним кофе, второй сжимал неглаженый галстук. Вениамин бегал между ванной и балконом. Он что-то рассказывал, периодически размахивая своим алым галстуком. Да так, словно хотел привлечь внимание всех быков полуострова.

– Вот поэтому я не люблю быть один. Мне с собой скучно, – разобравшись с гардеробом, подытожил Веня. – Невыносимо скучно. Как ты меня выносишь?

Он вернул свое внимание галстуку, повертел его в руках и со словами «Совсем мятый!» швырнул обратно в шкаф.

– Можем идти! – откуда-то из прихожей провозгласил Вениамин.

И я вдруг поняла, что по-прежнему сижу в кресле в одном белье.

Веня тоже это заметил и, по всей видимости, поспешил исправить ситуацию. Но что-то пошло не так, и вскоре мои трусики уже присоединились к галстуку. Склонившись над креслом, Вениамин опустил ладони на мои плечи. Его пальцы неспешно скользили по коже. Они коснулись шелковых бретелек моей майки. Оправили их, словно невзначай, и продолжили скользить вниз по телу, утягивая за собой остатки одежды. 

От этих прикосновений голова шла кругом. При каждом вдохе тело покрывалось сладостным ознобом, и мне подумалось, что завтрак придется пропустить. Затем Вениамин принялся покрывать мою грудь поцелуями, и думать мне больше не приходилось. 

<div style="text-align: center;">***</div>

Большая часть салонов из списка находилась в районе Северной и еще парочка – в центре. Вопреки тому, что это были два разных конца города, находились они напротив. Каждые полчаса к берегу подходил видавший виды паром, перевозивший горожан на соседний берег через Севастопольскую бухту. Назывался он «Адмирал Ларионов», что не могло не вызвать улыбки на моем лице.

И вот мы вновь бродим солнечными улочками Севастополя. Конечно, Вене нужно было работать, но это никак не нарушало внезапной атмосферы праздника. На самом деле мне нравилось просто гулять по городу. Плевать, куда ты идешь, когда рядом любимый человек. 

– Такое чувство, что у меня сегодня выходной, – признался последний.

Покончив с центром, мы сделали короткую остановку в очередной кофейне, решив расположиться снаружи. Заведение было крохотным, его терраса – еще меньше. Зато цены были довольно высокими, что вполне объясняло отсутствие посетителей. Заказав кофе, мы опустились в плетеные кресла и принялись обсуждать литературу. 

Единственным жанром, который нравился Вениамину, было фэнтези. Я же предпочитала классику, философию, постмодернизм, гонзо, старые детективы и Стивена Кинга, чье творчество не поддается классификации. Еще я души не чаяла в поэзии, которую Веня совершенно не понимал. Словом, почва для дискуссии оказалась бесценной. Увлекшись разговором на любимую тему, я даже не заметила, как принесли кофе. 

Более того, вскоре я осознала, что мы вдруг начали планировать свадьбу. Причем планировал по большей части Вениамин, а я лишь увлеченно слушала и периодически кивала. В отличие от предыдущего разговора, наши мнения касательно свадьбы более чем сходились. За исключением одного момента.

– Никогда не хотела пышную свадьбу, – сказала я, когда Веня наконец прервался на кофе. – Я их попросту не понимаю. То есть даже если опустить финансовый вопрос, на кой черт приглашать людей, которые и дня твоего рождения не вспомнят? Мне всегда казалось, что свадьба – это очень личное. Если честно, глядя на пиршества своих бывших одноклассниц, я вынесла такое впечатление, словно они делают это вовсе не для себя.

– Ты права, любовь моя, – лучшая фраза из тех, что женщина может услышать от своего избранника. – Я бы пригласил папу, сестру и, возможно, парочку старых приятелей.

Я подняла бровь.

– Уверен?

– Конечно, – заверил меня Веня.

Он всегда как-то по-особенному произносил это слово. С придыханием и каким-то милым воодушевлением.

– Эх, а я-то хотела предложить тебе взять кредит, который мы не сможем выплатить и спустя двадцать лет после развода…

– А что насчет места? Я бы предпочел природу.

– Фиолент, – внезапно для самой себя ответила я. – И столик в каком-нибудь уютном ресторанчике.

– Я поражен, - искренне произнес Вениамин. – Боялся, ты захочешь что-то более публичное. 

Обсудив еще несколько деталей, мой благоверный с радостью заявил:

– Повторюсь, Васляева, ты – моя идеальная женщина!

Как я уже говорила, в этой жизни мало что могло заставить меня залиться краской. Смущение – явно не мой конек. Было странно смущаться из-за ласковых слов мужчины, с которым живешь с первого дня знакомства. Но я смутилась.

– Тогда завтра можем отнести заявление в ЗАГС, – довольно подытожил Веня.

Тут то и всплыл наш персональный камень преткновения. Учитывая то, что прежде я никогда не мечтала о замужестве, было довольно сложно свыкнуться с мыслями о предстоящей свадьбе. Еще сложнее мне было свыкнуться с мыслями о столь скорой свадьбе.

– Ты сомневаешься, – не спросил, скорее сказал Веня, увидев мое лицо.

Конечно, я сомневалась. Не в своих чувствах к Вениамину и даже не в его чувствах ко мне. Я неподдельно верила в нас. Верила тому, что он любит меня, и тому, что он действительно хочет быть со мной. И все же хотеть и быть – немного разные вещи. А еще я не понаслышке знала, какими переменчивыми могут быть мужчины.

Нет, я любила Вениамина всем сердцем. Все, что когда-либо происходило в моей жизни, любые конфликты, трудности и прощания – все это вдруг стало таким несущественным. Даже не выспавшись, будучи усталой, без стабильного финансового положения, простуженной, страдающей от сезонной аллергии или извечной мигрени, настигшей меня после сотрясения мозга, я постоянно находилась в прекрасном настроении. Пожалуй, так говорят о каждой новой пассии, но я в действительности никогда не чувствовала себя так, как чувствовала рядом с Веней. Я смотрела на него, сидящего в соломенном кресле, с этими волосами цвета золотистой пшеницы и едва различимой за ними одинокой серьгой, чуть более темной бородой, которую не мешало бы подстричь, с многочисленными браслетами, утратившими цвет татуировками, что то тут, то там выглядывали из-под футболки, в поношенных джинсах, на карманах которых виднелись контуры ножа и ручки, в дырявых ботинках, с которых все время свисали шнурки, в квадратных солнцезащитных очках, которые шли ему так, как не шли ни одному хипстеру, и с рубашкой, повязанной на бедрах, что так походила на куртку дровосека. Смотрела и понимала, что любовь – слишком скудное слово, чтобы передать все то, что поселилось в моем сердце благодаря этому мужчине. Я любила его всей душой и тем, что осталось от моего сердца. Любила, и именно поэтому предпочла бы не сковывать себя узами брака. Слишком ценила эти отношения, чтобы добровольно делать столь амбициозные, необдуманные шаги.

– Просто не хочу все испортить, – наконец, ответила я. – К тому же, я с рождения плохо переношу жару, – и это было абсолютной правдой. – Не люблю лето и люблю осень. 

– Как ты можешь что-то испортить? Своим согласием ты сделаешь меня самым счастливым мужчиной на свете.

– Любимый, – я взяла его за руку, – ты и в самом деле удумал стать моим мужем?

– Спрашиваешь!

– В таком случае нам нужно провести какое-то время вместе. В конце концов, я вроде как не собираюсь выходить замуж дважды.

– Переезжай ко мне, – просто сказал Веня.

Я улыбнулась.

– Но… я и так живу с тобой.

– Нет, осчастливь родителей, набей чемодан всякими своими Ремарками, Бродскими и Паланиками и переезжай насовсем! 

Я не знала, что сказать. Замуж выходить – так я первая, а вот переезд казался мне очень ответственным делом. 

– Надеюсь, ты не будешь тосковать по работе в баре?

– По шестнадцатичасовому рабочему дню, вечным недостачам, уйме обязанностей, мизерной зарплате и полному отсутствию чаевых? Даже не знаю.

<div style="text-align: center;">***</div>

– Может, все-таки, передумаешь? – не унимался Веня. – Отнесем заявление завтра, и у тебя еще будет целых два месяца убедиться в том, что я прав. Ты же еще не передумала стать Елизаветой Ларионовой?

Он опустил очки к носу и весело подмигнул мне.

– Думаешь, два месяца – достаточный промежуток времени для того, чтобы принять такое решение?

– Я свое уже принял. Дело за тобой.

– Что ж, Вениамин Алексеевич, в таком случае, если ты задашь мне этот вопрос через два месяца, мы пойдем в ЗАГС и напишем это чертово заявление.

На протяжении последних минут десяти, позади нас то и дело раздавался шорох, природу которого мне никак не удавалось распознать. Учитывая серьезность нашего разговора, никто и не думал оглядываться. Шорох затих так же неожиданно как появился. Затем в нашу сторону покатилось нечто, плавно тарахтевшее по деревянному полу террасы. Наконец обернувшись, я увидела у своих ног круглый коричневый предмет, впоследствии оказавшийся баночкой краски. Вслед за ней уже мчался средних лет мужчина, одновременно шумно ругаясь и извиняясь на ходу. Был он седовласый, жилистый, не особенно опрятный, с локонами, собранными в пучок, двухнедельной щетиной и весь перепачканный краской. Одним словом, на первый взгляд – полубомж, который завтра мог бы оказаться в тренде.

Художник расположился за соседним и единственным, помимо нашего, занятым столиком. Там уже находились краски, палитры, мольберт, банка с кистями и прочие неотъемлемые атрибуты его ремесла. Писал мужчина очередные городские пейзажи вроде тенистых аллей и кафешек с цветочными клумбами. Такие обычно продают вдоль набережных. Подобные картины всегда привлекали меня в реальной жизни, но никак не на бумаге. Милые, идеально прорисованные картинки. И все одинаковые, словно их создатели целенаправленно избегали малейших проявлений собственного стиля. Или самих себя.

Да, пейзажи вроде этого меня не интересовали. Но вот сам мужчина, он оказался крайне интересным. Я имею в виду то, как он нервно вышагивал вокруг мольберта, не прекращая бранить себя. Он буквально ругал себя за все на свете: от плохого цвета, света или тона и заканчивая тем, что руки дрожат и краски вылетают из них на землю. Вот где и в самом деле экспрессии было побольше, чем во всех его вместе взятых картинах. Все это на миг перенесло меня в прошлое. Я вспомнила Эрика и то, с какой скрупулёзностью он писал музыку.

Вениамину позвонили из офиса, и он уже диктовал кому-то очередную заявку, а я допивала кофе и не сводила взгляд с этого удивительного полубомжа-полухудожника. Смотрела и думала великие думы о том, что порой вокруг готового продукта искусства устраивают слишком много шума. Иногда бывает и так, что этот самый предмет искусства ровным счетом не имеет никакого значения и по сути толком не является таковым, тогда как за творцом наблюдать куда приятнее. Выходит, что именно действие или бездействие в попытках создания и является настоящим искусством. Разве это новость? Мировое искусство кишит подобными сюжетами. Взять хотя бы Хантера Томпсона – уникальный человек и тот еще нарколыга. Однажды, он поехал в Лас-Вегас, чтобы осветить предстоящие гонки, и случайно написал культовое и наиболее узнаваемое произведение в жанре гонзо. Говорят, что статью он так и не закончил. Есть еще буддисты. Они-то давненько в курсе такого расклада событий. Путь и есть счастье, и все такое прочее.

– Что это за лицо на тебе такое? – между тем поинтересовался Вениамин.

Я рассказала о том, что думаю. Постаралась, чтобы моя мысль звучала менее пафосно, и самонадеянно заявила, что пора бы ему начинать за мной записывать.

<div style="text-align: center;">***</div>

Покончив с делами, мы прошли вдоль причала Северной бухты и уселись на самом краю. День выдался свежим, но тихим. Вокруг не было ни души. Перед нами простиралось море с едва уловимыми лазурными волнами. Они изредка мелькали на поверхности воды, напоминая складки на шелковом одеяле. Словно подобранное в тон морю, небо поражало глаза своей яркостью. Кое-где застыло несколько пушистых белоснежных облаков. На ближайшем берегу виднелись бесконечные обрывы, уйма зелени и парочка построек. Рядом со мной – облаченный в капюшон и солнцезащитные очки – сидел Вениамин. Мы курили по второй сигарете подряд. Время поджимало, но никому не хотелось покидать этот открывающий умиротворенную панораму уголок.

Внезапно из-за плеча моего суженого появился его водоплавающий однофамилец. 

– Прокатимся? – игриво спросил Веня, указывая на медленно движущийся паром. 

Я взглянула на эту сомнительную конструкцию, которая, казалось, внезапно для себя самой вместила на борту добрую десятину города, переправляя ее в Артбухту – еще одно место, в котором мы частенько гуляли. Кстати, официально Вениамин сделал мне предложение на набережной Корнилова, что прилегает к этой самой бухте. Правда между неофициальным и официальным предложениями руки и сердца прошло менее десяти часов.

– Сегодня я прокачусь только на одном Ларионове, и этот парнишка, – я указала на паром, – явно не мой тип.

