# &nbsp; {#chapter-17}

Живя вместе, мы привыкли пропускать завтрак. Обычно просто просыпались, занимались сексом и выпивали по чашечке кофе. Затем отправлялись в город, чтобы выпить еще по одной. И лишь ближе к вечеру, когда с работой было покончено, и Вениамин с облегчением прятал блокнот для заявок, мы вдруг вспоминали, что неплохо бы было поесть.

Однако, этот день выдался не таким. Хотя бы потому, что сегодня Вене нужно было работать как раз в том районе, где мы жили. Сказать больше, все нужные ему салоны находились в десяти минутах ходьбы от дома. Над городом еще сияло полуденное солнце, когда возвращались домой. Веня купил несколько банок пива и теперь шел с довольным видом, приканчивая одну из них. Я разбавила свой кофе приличной порцией коньяка и поместила все это во флягу, с которой, казалось, меня связывало куда больше, чем с любым другим неодушевленным предметом. 

В общем, прихватив с собой алкоголь, любовь и прочие атрибуты простого человеческого счастья, мы расположились в небольшом парке. Солнечные лучи норовили проскользнуть сквозь пышную крону дуба, под которым мы сидели; в ветвях щебетали птицы, яркая трава щекотала лодыжки, а из переносной колонки доносился голос Боба Марли. Здесь не было ни души. Вдали виднелся проспект, вдоль которого то и дело бегали озабоченные работой люди, а мы попивали свои напитки, дышали свежим майским воздухом и радовались тому, что не являемся частью этой суеты.

Одурманивающая атмосфера уединения продержалась около часа. Затем местные мамочки получили сигнал, который был слышен лишь им одним, и как по команде стали появляться со всех сторон парка. Мы ушли, не сговариваясь. 

Через несколько остановок находился круглосуточный гастроном, куда мы еженощно захаживали. Сегодня же мы впервые появились там днем. Скорее по привычке и из желания пройтись, ведь в радиусе двадцати метров от сквера было множество работающих магазинов. 

Внутри магазина можно было встретить огромного старого пса, одинокого кота и видавшую виды продавщицу. Она являла собой классический пример представительниц торговли девяностых годов: выжженные перекисью волосы, фиолетовые тени, которые тянулись до самых бровей и даже куда-то выше, и полнейшее отсутствие банальных знаний этикета сферы обслуживания. Если вы, как и я, росли в девяностые, один разговор с такой особью способен отворить вам удивительный портал в детство.

Не обращая никакого внимания на грубость продавщицы, Вениамин поглаживал кота. Тот сидел у прилавка и подобно хозяйке заведения излучал полнейшее безразличие ко всему, что происходило вокруг. Мне же всегда доставался пес. Хотя, скорее, я – ему. Увидев меня, старый дворняга радостно вилял хвостом, и тут же падал на спину, ненавязчиво предлагая мне почесать его живот.

На пути домой нам всегда встречалась уйма уличных животных. И, все же, наиболее оживленное место представлял собой финальный отрезок пути – широкая каменная лестница. Она имела несколько пролетов. На каждом обитало по семейству котиков. Подойдя ближе, Веня углубил руку в свой бесконечных размеров рюкзак, и достал огромную пачку сухого корма.

– Зачем…

«…так много?» – собиралась спросить я, но замолчала на полуслове.

Стоило моему мужчине высыпать его на землю, как из близрастущих кустов показалась еще пара кошек. А затем еще пятеро, еще трое и снова двое. В конечном счете, их оказалось не меньше двух десятков, если не считать тех, что к нашему появлению уже были на лестнице.

– Такие дела, – сказал Веня, видя мое удивление.

<div style="text-align: center;">***</div>

Лестничные кошки были третьей к концу остановкой. За ними шли дворовые, откормленные местными старушками животные. Последней станцией был Марсианин – огромный камышовый кот, которые уже долгие годы жил на чердаке дома. Заходя в подъезд, мы пропускали его в лифт и подвозили на последний этаж. Тогда Марсик неспешно выходил из кабинки, оборачивался, словно хотел поблагодарить нас. Но потом вспоминал, что ему не до этого и поспешно поднимался по ведущим на чердак ступеням.

Словом, каждый совместный выход из дома оказывался небольшой экскурсией по местной фауне. Мне это нравилось.

Как я уже сказала, обычно до обеда мы о еде не вспоминали. Этот лишенный работы день стал исключением.

Чайник закипал, свиные ребрышки жарились, а картошка остывала на плите. Я услышала звук сработавшего фотоаппарата, и в замешательстве обернулась.

– Елизавета Васляева стоит у плиты, – прокомментировал Вениамин. – Однажды репортеры неплохо наградят меня за такое фото.

Я рассмеялась, залившись румянцем.

– Хорошо всмотрись в эту картину потому, что ты видишь ее в первый и последний раз, – предупредила я.

И, как всегда, ошибалась. 

<div style="text-align: center;">***</div>

– Мы прямо-таки семья, – заметила я, глядя за тем, с каким энтузиазмом Веня поедает приготовленный мною ужин. – Уплетаем картошечку под покровом ночи и все такое.

Кстати говоря, его порции – это было что-то с чем-то. Вкратце, она представляет собой дневной рацион питания какой-нибудь многодетной татарской семьи. К своим двадцати двум годам я видала разных людей, но ни одному из них не удавалось есть так много и выглядеть так подтянуто, не посещая при этом тренажерный зал. Веня же буквально ел суп кастрюлями, макароны пачками, а единственной приемлемой яичницей для него была та, в которую входило не менее шести яиц.

– Я прямо-таки собираюсь на тебе жениться, – напомнил Веня.

– Прости. Все время об этом забываю.

И это было правдой. С непривычки я постоянно забывала о том, куда зашли наши отношения. Просто наслаждалась моментом до той самой минуты, которой Вениамин называл меня своей невестушкой. Тогда пространство вокруг меня замирало, и я начинала отчетливо осознавать ситуацию, слегка ее побаиваясь. Но, в основном, на душе становилось невероятно тепло. Я краснела от смущения и подолгу смотрела на Веню влюбленным взглядом.

– Но ты права. Я тоже что-то почувствовал, – отозвался Вениамин. 

– Наверное, это потому, что мы впервые едим дома.

И правда, все дело было в ночной картошечке. Ну, и в любви, которая то и дело витала в пропитанном специями воздухе.

– Ну, ты же моя невестушка, помнишь?

– Да как тут не помнить?

– А мне вот, все-таки, кажется ты не всегда об этом помнишь…

– Ладно-ладно, ты меня раскусил, – я убрала со стола пустые тарелки и улыбнулась своему возлюбленному виноватой улыбкой. – Я правда не всегда об этом помню.

– Почему? Я думал, это у меня проблемы с краткосрочной памятью.

– Не в этом дело, Веня. Я просто никак не могу привыкнуть к мыслям о замужестве. Или о помолвке. Это как если бы ты однажды выкрасил волосы в черный…

– В черный? 

Вениамин искренне изумился своему гипотетическому выбору нового цвета волос. 

– Да, именно. Ты бы стал брюнетом, но мысленно еще долго позиционировал себя как блондина. Потому, что всю свою жизнь ты был блондином и никогда не думал о себе, как о брюнете, понимаешь?

– Допустим.

– Вот и я никогда не думала о себе, как о жене или невесте. 

– Ну, так скажи это! 

– Что?

– Я слышал, что в таком случае мысли надо озвучивать, – объяснил Веня. – Когда ты не можешь с чем-то свыкнуться, надо это просто произнести.

– Это еще зачем?

*Нельзя вешать ярлыки. Никакие. Даже если все кажется идеальным. Нет, особенно если все кажется идеальным!*

Я и так знала, зачем. Просто тянула время. 

*Как только ты называешь мужчину своим молодым человеком, ты подсознательно начинаешь ждать от него определенную модель поведения. И чем больше его действия походят на те, что ты там себе успела придумать, тем сильнее ты расслабляешься. *

*И тем болезненнее в дальнейшем будет принять суровую реальность. *

Чьи это мысли? Я не могла вспомнить, хотя, казалось, слышала их совсем недавно.

Похоже, что мои.

– Слова обретают смысл, когда произносишь их вслух, или что-то вроде того. Короче, если что-то кажется тебе нереальным, нужно это просто озвучить. Ты услышишь собственную мысль несколько раз и быстрее поймешь ее смысл. Давай же, попробуй! Скажи, что ты теперь невестушка!

Стоит ли говорить, что этот процесс не обошелся без заминок? Мне понадобилось пять попыток, две сигареты и новый слой укрывшего щеки румянца, чтобы на полном серьезе сказать вслух эти два несложных слова. 

– Я – невеста, – медленно произнесла я, едва ли веря собственному голосу.

Вениамин заулыбался от умиления тому, насколько по-детски это прозвучало. 

Веня – что за человек это был? Таинственный как ночь и предсказуемый как утренняя тошнота после знатной попойки. Он часто использовал в речи одни и те же фразы, произнося их с одинаковыми интонациями, так что вскоре предугадать следующее слово сделалось проще простого. Он не любил пиво, но потреблял его с завидной регулярностью, вероятно, бастуя против системы. Любил складные ножи и таскал с собой целую кучу холодного оружия, заботливо раскиданного по карманам джинс. При этом Вениамин имел крайне двойственную репутацию: малознакомые люди (в частности, женщины) его чуть ли не боготворили, тогда как в родном городе моего избранника буквально считали отбросом общества. Он несколько раз попадал в участок, (и каждый раз это происходило из-за неадекватного поведения в нетрезвом состоянии) убегал от приставов, пару раз просыпался рядом с совершенно незнакомыми ему людьми, а однажды пришел домой в одних штанах и понятия не имел, куда делось все остальное, включая документы и телефон. Веня всегда выходил покурить после третьей стопки, обожал коктейли с абсентом и домашние настойки. Не то чтоб его можно было назвать гурманом… В отношении алкоголя мой мужчина руководствовался простым правилом: чем крепче – тем лучше, благодаря чему состоял в черном списке многих питейных заведений разных городов Крыма.

Он носил шелковые рубашки, старомодную шляпу и не менее старомодные жилетки, не вылезая при этом из треснувших по швам ботинок. Последние, кстати, были демисезонными. По какой-то странной причине, Веня чрезмерно долго завязывал шнурки и делал это явно не так, как все нормальные люди. По этой же причине обычно он и вовсе не зашнуровывал свои ботинки. А еще Вениамин практически никогда не давал логически обоснованных ответов.

– Зачем ты их носишь в такую жару? – не прекращала спрашивать я, указывая на уже давно отжившие свое ботинки.

– Они водонепроницаемые, – отвечал Веня так, словно это многое объясняло.

Он обожал все острое и закидывался халапеньо как семечками, редко вылезал из любимой одежды и еще реже соглашался залезть под душ. Я никогда с точностью не могла понять, умный он или глупый. С одной стороны, Веня довольно много знал. Он мог рассказать мне кучу вещей о любой сфере деятельности. С другой – мой жених имел крайне ограниченный круг интересов, сводящийся к алкоголю, фильмам, работе, котикам и мне. Правда, слегка в другом порядке.

Как и все мужчины, Вениамин был до невозможности противоречив. Забавней всего было то, что утром он мог выразить мне какую-то мысль, а к вечеру начинал активно ее оспаривать. Да еще и с таким рвением, словно и впрямь забывал, что мысль-то – его. Видимо, противоречивость – это обязательное качество каждого представителя сильного пола. Что-то вроде критических дней, которые нахрен никому не упали, но и без них тоже никуда. Только для мальчиков. Я знаю очень многих мужчин. Я с ними работала, дружила, встречалась, жила, имела родственные связи и все такое прочее. Но я не знаю ни одного мужчины, который бы, в конечном счете, не оказался противоречивым. Порой они сами себя так называют, а на следующий день отрицают это до последнего.

Наверное, в этом и есть смысл.


