# &nbsp; {#chapter-19}

Однажды мы сидели в парке, попивали холодный кофе и разговаривая по душам. По сравнению с остальными днями жара стояла умеренная. Вениамин растянулся поперек скамейки. Я же лежала, умостив голову ему на колени.

Вскоре к нам подбежала толпа местных бойскаутов. Во главе у них была стеснительная женщина с огромным фотоаппаратом.

– Мы ищем парня с большой бородой, – запыхавшись, произнес один из детей.

– Кто ж не ищет? – с улыбкой ответила я.

– Правильно говорить «длинной», – поправила его женщина.

Веня дружелюбно развел руками, как бы говоря: «Вот он я!».

Ко мне обратился другой ребёнок.

– Вы можете заплести ему косу? – увидев замешательство на моем лице, мальчик добавил: – Пожалуйста! Мы очень отстали! До конца квеста аж целых два задания!

Я поднялась и взглянула на своего суженого.

– Ты не против?

– Вообще нет.

Веня снял шляпу, и я уже запустила пальцы в его спутавшиеся волосы, когда вновь заговорил первый ребёнок.

– Вы не поняли. Коса нужна из большой бороды.

– Длинной, – снова напомнила женщина.

– Ага. Длинной.

Дети в ожидании смотрели на нас. Я с трудом сдерживала желание расхохотаться, завидев выражение лица Вениамина. Какое-то время он пытался отказаться, но вскоре детишки его уговорили.

Я засучила рукава и принялась плести косу.

Из толпы вышла девочка. Она восторженно смотрела на мою левую руку.

– Нам ещё нужна девушка с большой татуировкой!	

– Правильно говорить… – начала женщина, но в итоге подвисла.

Вот это детишкам повезло. Они сфотографировались с нами и умчались в сторону фонтана, переполненные той особенной, искренней радостью к ничего не значащим вещам, которую мы можем испытывать лишь в детстве.

<div style="text-align: center;">***</div>

– Ты никогда не рассказывал мне о своих родителях, – вдруг поняла я, глядя за тем, как бойскауты покидают парк.

– У меня не очень благополучная семья.

– Не хочешь говорить об этом? Я не обижусь.

– А вот и нет. Сегодня мне впервые в жизни хочется об этом поговорить, – внезапно ответил Веня.

И он начал свой долгий рассказ. Как оказалось, отец Вениамина на протяжении многих лет изменял своей жене. Он был не прочь выпить и, кажется, даже пару раз поднимал на нее руку. При этом Веня продолжал считать отца своим лучшим другим. Он говорил о нем с уважением и каким-то странным для меня благоговением. С другой стороны, мать Вениамина была отнюдь не подарком. Со слов мужа, за ней имелся какой-то пунктик помешательства на деньгах, что очень напрягало всех членов семьи. Со временем это переросло в настоящую манию. Она принялась скупать кучу золота и укладывать его в большую хрустальную чашу. К тому же она постоянно выдумывала какие-то гадости (сначала о своём муже, а затем и о сыне), которые затем рассказывала большому количеству посторонних людей.

– Было много неприятных моментов, – грустно произнес Веня.

– Например, каких?

– Ну, например, в детстве мне приходилось самому готовить. Когда мне было лет десять, мама вдруг стала готовить отдельно для себя и моей сестры. Просто ставила перед ней еду, а остальное уносила к себе.

Я в ужасе посмотрела на жениха.

– И это далеко не самое худшее, – заверил он.

Однажды отец Вени – Алексей Вениаминович – устал от такой обстановки и объявил жене, что хочет развода. В ответ та схватила дочь, все деньги и драгоценности, которые смогла найти, и испарилась в неизвестном направлении.

– Она меня бросила. За все эти годы ни разу не приехала ко мне. Отцовская любовница и то проявила ко мне больше заботы.

Его голос звучал отрешенно. Так, словно Вениамин рассказывал мне услышанную где-то историю. То, что произошло с кем угодно, только не с ним самим.

– Ты до сих пор с ней не общаешься? – спросила я.

– Она вернулась год назад. Сказала, что снова будет жить в нашей квартире, потому что закончились деньги. А отец переехал на дачу.

Затем Веня рассказал ещё море не менее ужасных историй, после чего меня нежданно-негаданно стало одолевать желание встречать его вкусными ужинами, будить пахнущими завтраками и все такое прочее. В общем, мне внезапно захотелось стать примерной женой образца пятидесятых и потратить каждую минуту своей жизни исключительно на заботу об этом мужчине.

Слава богу, это был всего лишь мимолётный порыв.

– Она отвратительная женщина.

– Ты ее простил?

– Мне абсолютно наплевать. Уже давно, – отчеканил Веня.

Я ему не поверила.


