# 20 {-}

Весна стремительно близилась к своему завершению. С каждым мгновением солнечные лучи делались все настойчивей, асфальт плавился, а воздух становился горячее. Тем не менее мы все так же проводили дни за долгими разговорами, распитием спиртного и прогулками через весь город. Еще мы подолгу валялись в постели, предаваясь любви друг к другу. Откровенно говоря, секса было так много, что по приезду домой я увидела, что моя талия заметно уменьшилась в размерах. 

Но и до моего отъезда успело произойти еще немало чудесных вещей.

В конце рабочей недели мы решили прогуляться по слегка необычному маршруту. Напротив остановки около нашего дома находился супермаркет, где мы часто делали покупки, по-детски радуясь этому семейному процессу. Помню, первым, что мы купили, стала пара бокалов и формочки для льда – ну кто бы сомневался. По традиции, около входа в магазин находилась крохотная кофейня с хорошим кофе и плохой баристой. Приходя туда, я каждый раз взбивала молоко вместо нее. С правой стороны от маркета виднелся ряд магазинов, плавно перетекающий в толпу баров и кафешек.

Так вот, пройдя несколько метров между этими строениями, ты попадаешь на идеально прямую дорогу. С краю стоит заправочная станция, а за ней находится просторный путь, уводящий в соседний район. Первую половину дороги понемногу спускаешься вниз. Затем спуск становится резче, а на пути встречается старый пешеходный мост, перекинутый через некогда существующую реку, на месте которой теперь нет ничего, кроме пустоши. Второй отрезок пути – зеркальное отражение своего предшественника. Сначала тебя ждет резкий, в после – более плавный подъем. Никаких развилок и поворотов. Таким образом, маршрут представляет собой букву С, лежащую на спине. 

Еще стоя в самом начале пути, мы прекрасно видели все, что находилось на другом конце. В основном это были высотки вперемешку с привычными двориками, полными растительности, лавочек и качелей. 

Такой вот маршрут мы выбрали. Вернее, нам пришлось это сделать потому, что на другом конце Веню ждала клиентка, припозднившаяся на склад. Она должна была отдать деньги за купленные в начале недели краски для волос, или что-то вроде того. Сумма была неплохой, Вене причиталось получить свои пятнадцать процентов.

Мы вышли вечером, около половины восьмого. На удивление, нужная нам улица оказалась пустынной. За все время пути нам не встретилось ни души.

– Какой он, твой родной город? – спросила я, подкуривая первую за вечер сигарету.

– Красивый и маленький, – после небольших раздумий ответил Вениамин. – Прямо как мой член.

И пускай мы оба знали о том, что его агрегат нельзя назвать маленьким, Веня никак не мог прекратить шутить на эту тему.

– И что в нем красивого? Я имею в виду…

Он не дал мне закончить.

– Не знаю, но женщинам нравится.

– …Керчь.

Наконец-таки осознав, что в двадцать пятый раз шутки про пенис уже не кажутся смешными, Вениамин ответил:

– Поехали, сама увидишь.

*О, мой многословный мужчина!*

– Когда?

Я обожала поездки всех видов и направлений. Частенько ездила куда-то в моменты печали, творческого упадка или душевных терзаний. Бывало, даже не знала конечного пункта назначения, но все равно ехала, потому что в итоге всегда чувствовала себя лучше. Как ни крути, а в дороге одиночество ощущается куда меньше. Наверное, дело здесь в том, что любое движение подразумевает наличие цели. Отправляясь в путь, ты временно обеспечиваешь себя каким-никаким, а все-таки смыслом жизни. Это иллюзорное чувство спокойствия не раз позволяло мне отвлечься от тоски и сосредоточиться на решении других, более материальных проблем.

В общем, к тому времени я уже была специалистом по всякого рода одиноким поездкам. Думаю, моих знаний вполне хватило бы на то, чтоб распределить их на категории и создать собственную программу семинаров. Что-то вроде «Куда поехать, если с вами расстались в скайпе?», «Как преодолеть потерю работы с помощью билета в один конец?» и так далее, и тому подобное.

Чего я, собственно, не знала, так это каково путешествовать с любимым человеком. Несмотря на наличие бывших возлюбленных, с этим пунктом у меня как-то не сложилось. Но мне всегда представлялось, что совместные поездки – это что-то удивительное. Пожалуй, именно поэтому я так быстро соглашалась со всеми бредовыми идеями жениха.

Мои размышления прервал голос Вени.

– Поехали в следующем месяце? Мне как раз нужно будет съездить в Керчь.

Я вздохнула.

– Ты же знаешь, что к тому моменту я уже уеду.

– А ты возвращайся.

Он сказал это спокойно и ласково. Так, словно мы уже миллион лет были в месте. Словно не боялся моего отказа и точно знал, что все у нас будет хорошо. Вениамин вел себя так на протяжении всего времени, что мы были знакомы. Спокойствие и уверенность, безусловно, входили в список вещей, за которые я его обожала. Если я ломала ноготь, слышала какую-то грубость, не находила своего размера в магазине одежды, получала очередной отказ от издательства, встречала резкую критику или попадала в любую другую неприятную ситуацию, стоило мне посмотреть на Вениамина, и раздражение проходило. Казалось, ничто не могло заставить его унывать.

Вот и сейчас, глядя на него, я не могла спрятать улыбку.

– Я бы взглянула на Керчь.

– Познакомлю тебя с папой, покажу каменоломни и свой любимый бар.

– Куда же без этого.

Он развел руками. 

– И на пляж сходим?

– И на пляж сходим.

– Есть одно но… – сказал Веня.

Видно было, что жениху неловко, и он не особо хочет заканчивать эту фразу.

– Ну что там еще такое?

– В Керчи обо мне ходит не самая лучшая слава.

Как будто я этого не знала.

– Ты хочешь сказать, на меня все будут смотреть с сожалением?

– Ну, вроде того.

– А потом отводить в сторонку и уговаривать бежать от тебя, куда глаза глядят?

Он улыбнулся.

– Именно так все и будет.

Я поцеловала своего мужчину.

Веня был значительно выше меня. Закинув руку мне на плечо и обняв за шею, он спокойно мог продолжить свой путь, не чувствуя при этом дискомфорта. Так мы и шли, приближаясь к пешеходному мостику. 

– Пускай болтают. А я буду улыбаться и потягивать винишко, – ответила я. – Расскажу им о нашем медовом месяце в Шотландии и о том, что мы сделаем одинаковые футболки со своим фото.

– И о двух прелестных детишках, – подхватил Веня. – Белокурой девочке и кареглазом мальчике.

– Скажу, что в свои девять Йозеф в идеале знает четыре языка. А потом извинюсь, согнусь в реверансе и объявлю, что мне пора идти. Забрать Аглаю Вениаминовну из музыкальной школы, которую она заканчивает в следующем году. 

– Она играет на рояле, флейте и кларнете.

– Одновременно.

После этой реплики мы разразились звонким смехом.

– Аглая Вениаминовна… – сквозь смех произнес Веня. – Где ты вообще это взяла?

– Подсмотрела у Достоевского.

Мы шагнули на мост, по-прежнему оставаясь единственными пешеходами во всей округе. С правой стороны уже запоздало садилось солнце. Его оранжевые лучи заливали отрезок, по которому много лет назад протекала то ли река, то ли ручей. Купающееся в золоте, это место больше не выглядело таким забытым. Мне даже стало немного жаль того, что солнце скоро сядет и местность у моих ног вновь обратится никому не нужной пустошью. Так ведь и с людьми бывает.

Я озвучила свою мысль. Веня ее одобрил.

– Запиши это как-нибудь, – сказал он.

Я так и сделала. Пускай и с заметной задержкой.

<div style="text-align: center;">***</div>

Обсуждая призрачное совместное будущее, мы, сами того не замечая, подошли к высоткам. Вениамин отыскал нужный дом и отзвонился клиентке. Та сказала, что сейчас подойдет, и жених исчез в уютной мгле дворика, последовавшей за закатом.

Я осталась ждать у дороги, разглядывая местность. Вокруг были невысокие кустарники, детские площадки, магазин, аптека, неработающий сигаретный киоск и ряд придорожных фонарей, которые как раз начинали загораться. В какой бы город я ни приезжала, все спальные районы бывших советских стран всегда выглядели одинаково. При этом, несмотря на серую монотонность, было в них что-то приятно печальное. Как воспоминания о детских днях, которым никогда не суждено вернуться.

Несколько минут прошли в полнейшем одиночестве. Я все так же стояла, думая свои прозаические думы и всматриваясь в темноту двора, когда краем глаза заметила какое-то движение. Откуда-то из-за угла появилась женщина лет на пятнадцать старше меня. На ней была пижама и что-то очень странное, при ближайшем рассмотрении оказавшееся термобигудями в виде плюшевых пенисов. Я прямо-таки обалдела.

– Вы – Вениамин? – громко спросила женщина.

Я прямо-таки обалдела во второй раз и даже обернулась по сторонам, дабы убедиться, что позади меня не стоит Веня. Само собой, никакого Вени около меня не наблюдалось. Должна признать, на протяжении жизни я встречала разных людей (по большей части, не очень хороших), и как они только меня ни называли! Но Вениамином – никогда.

Даже не стану акцентировать внимание на том, что тем днем на мне было надето платье, а волосы как обычно волнами ниспадали на плечи. В общем, мне понадобилось секунд пять для того, чтобы собраться с мыслями. 

*Она назвала меня Вениамином?*

*Какая разница, когда у нее члены в волосах!*

И еще десять на то, чтоб не расхохотаться.

– Нет, – ответила я, стараясь звучать максимально нейтрально. – Вениамин – мой жених.

Не вдаваясь в расспросы, женщина 

*(ЧЛЕНЫ В ВОЛОСАХ!)*

изъяла стопку денег откуда-то из-за пазухи и протянула ее мне.

– Ну, по-всякому в жизни бывает, – сказала она и вскорости исчезла за углом дома.

*Не то слово, мамзеля*, подумала я.

Как только эта внезапная воительница за права трансгендеров скрылась с горизонта, из злополучного дворика появился мой благоверный. Растерянный и одинокий он медленно подошел ко мне, подкуривая очередную сигарету.

– Нашел свою клиентку? – с улыбкой спросила я.

– Да.

– Забрал деньги?

Он помедлил.

– Нет. Она сказала, что отдала их… Вениамину.

Больше не в силах скрывать улыбку, я отдала ему конверт.

– Вообще-то я подумывала однажды взять твою фамилию, – сказала я. – Но вышло немного иначе.

Оставшуюся часть вечера мы провели, раскачиваясь на качелях. 


