# &nbsp; {#chapter-21}

Временами я смотрела на Веню абсолютно восторженным взглядом. Особенно привлекательным он казался мне, занимаясь своими делами. Будь это работа, чистка ботинок или вождение. Словом, любая сосредоточенность добавляла мужчине сразу несколько баллов по шкале очарования. Самым поразительным в этой ситуации было то, что Веня, казалось, и вовсе не догадывался о существовании собственной харизмы. 

– Ты у меня такой красивый, – говорила я в такие моменты.

– Все ты неправильно говоришь. – поправлял Веня. – правильно говорить: мы с тобой такая красивая пара.

Он любил, когда я носила очки, пускай мы оба знали о том, что со зрением у меня все не так плохо. А ещё Вениамин обожал, когда я подбирала волосы, закалывая их на макушке. Все, кому не лень, говорили, что так я выгляжу лучше. Знаете, открытое лицо и все такое, но мне это вообще не нравилось. Честно говоря, я по сей день терпеть не могу то, как смотрюсь с собранными волосами, так что если я это и делала, то исключительно для Вени. Или потому, что этого требовал этикет работы за барной стойкой.

Помнится, однажды, в первые дни моего приезда, мы как обычно околачивались в центре. Мне полюбилась одна придорожная пекарня, которую окружали салоны, парикмахерские, магазины и прочие пристанища клиентов Вениамина. Как и все мои любимые заведения, пекарня была совсем небольшой, если не сказать маленькой. Треть зала занимали высокие стойки и витрины, на которых красовалась выложенная в ряды выпечка. Всевозможные кексы, пончики, пирожные, рогалики, ватрушки, пирожки и печенье наполняли воздух праздничным ароматом. В углу стояла кофе-машина, а вдоль стеклянных стен тянулась стойка, предназначенная для клиентов. Здесь я проводила по несколько часов в день. В большинстве своём за кофе и чтением.

Был у пекарни и задний дворик. А ещё там был открытый вай-фай, так что порой, когда в карманах не наблюдалось лишних денег, мы с Вениамином устраивались на заднем крылечке и подключались к сети. Напротив были захудалые дворики в вперемешку с не менее захудалыми гаражами, а около ступеней каждый день стоял чей-то ржавеющий москвич.

Одним из таких дней я ждала прихода Вениамина. Тот отвез товар и теперь стоял около гаражей. На нем были все те же рваные джинсы, чёрная футболка, которая выигрышно обтягивала торс, и огромные солнцезащитные очки. Позади золотились высокие купола стоящей неподалёку церкви. Волосы Веня перекинул на правую сторону, и они сияли на солнце в тон куполам. Ещё не полностью отделавшись от рабочего духа, Вениамин прикуривал правой рукой. В левой он держал прайсы, которые внимательно просматривал. Вид у него был до ужаса деловой. И до ужаса обворожительный.

Желая поймать момент, я тихонько сфотографировала своего жениха. Позже, глядя на этот снимок, я не прекращала поражаться очарованию Вениамина, лучшей деталью которого было то, что вид этот Веня принимал вполне естественно. И знать об этом не знал.

<div style="text-align: center;">***</div>

– Мое любимое мороженное, – гордо заявил Веня, протягивая мне внушительных видов рожок. Тот был двухцветным и сочетал в себе ягодное и медовое мороженое. – Я за ним ездил сюда из самой Керчи. Все детство.

А это было без малого шесть часов пути, если не учитывать пробки и остановку в столице. Я терпеть не могла плодово-ягодное мороженное, но так и не решилась сказать об этом Вене. Уж слишком довольное и по-детски радостное у него было лицо при виде этой сладости. 

Взяв любимого под руку, я шла вдоль Приморского бульвара. Справа от нас виднелся памятник затопленным кораблями. Это был утес из гранитных глыб, искусственно выложенный на воде. Выше – светлая колонна, на капители которой восседал двуглавый орел. Присмотревшись, на головах птицы можно было увидеть императорскую корону, а в клювах – внушительных масштабов венок из желудей, лавровых и дубовых листьев. Еще одной примечательной деталью памятника затопленным кораблям был якорь. Утонченный, тот крепился к венку и ниспадал на цепи.

Около монумента толпились туристы. Некоторые бродили сами по себе, периодически делая селфи. Другие были в сопровождении гидов и внимательно следили за их рассказами. Со всех сторон до моих ушей доносились обрывки фраз, взятых из путеводителя.

– …культурное наследие Крыма…

– …проект скульптора академика…

–  …в тысяча девятьсот пятом…

– …эмблема Севастополя…

– …в честь пятидесятилетия обороны города…

И так далее, до бесконечности.

Плавной дугой бульвар сворачивал направо. Подле него покоились отточенные водой каменные глыбы. То и дело дул бодрящий ветер. Волны игриво касались языками цементных глыб, омывая бульвар. Со всех сторон показывалась морская пена. Она ударялась о крохотные скалы и тут же исчезала, чтобы через мгновенье вновь предстать нашим взорам. 

И, все же, казалось, все было наоборот, и это бульвар омывал могущественное синее море.

Вдоволь налюбовавшись туристами, мы поднялись по закругляющейся лестнице и вскоре оказались на смотровой площадке. Отсюда бульвар, памятник, да и линия воды казались какими-то сказочными. Никогда не перестану изумляться красоте моря. Где бы я не находилась, и какие бы мысли не тяготили мне душу, шум прибоя способен унести за собой любые тревоги. Всему виной море с его неизмеримыми широтами, игривыми волнами, пеной, что томно остается на берегу как легкое воспоминание о прошедшем шторме. Море с его волнительными закатами и упоительными рассветами, лазурной гладью, парящими чайками, и теплыми огнями, украдкой зовущими тебя в далекие края. Море с его бескрайними берегами, оживленными причалами, старыми портами и тихими бухтами. И прежде всего – с его манящей таинственностью. Никогда не перестану изумляться красоте моря. Глядя на него, я словно заглядываю в свою душу, позволяя сознанию многое переосмыслить. 

Конечно, Бродский как всегда был прав, советуя каждому страждущему сесть в поезд и высадиться у моря. Эти строки знают все, однако мало кого интересует их окончание. 

*Оно обширнее. Оно*

*и глубже. Это превосходство*

*не слишком радостное. Но*

*уж если чувствовать сиротство, *

*то лучше в тех местах, чей вид *

*волнует, нежели язвит.*

– так заканчивается его «С видом на море». 

Сколько себя помню, меня всегда снедало одиночество. В большинстве своем, это было вызвано отсутствием родственной души, которую я, неистово исповедуя культ любви, искала в будущем избраннике. Стряслось это со мной годиков в тринадцать, и чем больше лет проходило, тем более одинокой я себя чувствовала. Вокруг всегда было много людей разных интересов и возрастных категорий. Друзья, приятели, знакомые, парни… К семнадцати годам я окончательно осознала, что мне плевать на их внимание. Пару раз я встречала мужчин, которые завладевали моим сердцем, не прикладывая при этом особых усилий. Первым оказался Эрик. Ему тогда было семнадцать, мне – пятнадцать. Мы общались несколько лет, и я не могла не замечать, что Эрика ко мне постоянно тянуло. Но что-то вечно мешало ему разобраться в своих чувствах. Так у нас ничего и не сложилось, а я все ждала и ждала, когда же он одумается. Меня нисколько не интересовали другие ухажеры, число которых увеличивалось с каждым годом. 

Думаю, еще в те дни в моей голове ясно укрепилась идея о том, что в одиночестве счастлив не будешь. Печальный настрой, на самом деле. Я любила путешествовать, но не видела в этом смысла, если рядом нет любимого человека. С кем тогда я буду делить свою радость? Ведомая немалыми амбициями, я почему-то отказывала себе во многом, считая это пустым. При этом я никогда не мечтала стать чьей-нибудь женой и ни разу не думала о свадьбе. Мысль о том, что счастье должно вытекать из самодостаточности и оставаться в тебе вне зависимости от окружения или его отсутствия пару раз приходила мне в голову, но я настойчиво ее прогоняла. Все, чего мне хотелось – быть с близким по духу человеком, а Эрик мне виделся именно таким. 

Прошло несколько лет прежде, чем я смогла окончательно забыть об Эрике. Расставшись с очередной девушкой, он тут же искал со мной общения. Затем находил новую пассию и все повторялось. Перешагнув восемнадцатилетний рубеж, я, наконец, осознала свою глупость. Так я распрощалась со своей школьной любовью, чтобы в девятнадцать вновь влюбиться как последняя школьница. На этот раз в Адама. И теперь чувства были сильнее. К тому же, они оказались взаимными, и я с трепетом размышляла о нашем будущем. Мне хотелось совместных поездок, душевных разговоров и, конечно же, обсуждения творчества друг друга. Как и моя первая любовь, Адам был музыкантом. Я уже говорила, что он ушел от меня за неделю до моего двадцатилетия и это действительно расстроило меня до глубины души. Лишь по прошествии времени я поняла, что три года – слишком долгий срок для того, чтобы убиваться по мужчине. Но так было с Эриком. Так случилось и с Адамом.

Не поймите меня неправильно, я никогда толком не бегала за мужчиной. Не кричала о своей любви после разрыва отношений. Увы, это вовсе не значит, что она исчезала. Любовь была для меня неотъемлемой частичкой гармонии не только с внешним миром, но и с самой собой. Пожалуй, именно в этом и крылась проблема, но я была так верна идее вечной любви, что просто не замечала таких очевидностей. Будучи по природе своей склонной к самоанализу, я, тем не менее, не так давно осознала причины собственных сердечных трагедий. 

