# 22 {-}

Случилось это за полгода  до нашего знакомства с Вениамином. Сама того не желая, я внезапно уличила в предательстве близкую подругу. Ту самую, чье имя уже давно было вытатуировано на моей руке. Уставшая от постоянной лжи, слез и боли я наконец-таки явно почувствовала, как же сильно мне осточертели эти депрессии. Почувствовала и буквально заставила себя пойти на постоянную работу, которая отнимает все время. 

*Депрессия? У меня нет на нее времени.*

Что бы там ни говорили о трудоголизме, но он явно помог мне начать ценить свободные минутки. Это привело к тому, что я и впрямь начала осознавать ценность таких простых, но приятных вещей, как вечерние чтение и утренняя чашка кофе. В один из редких выходных две тысячи пятнадцатого я сидела, раскурившись марихуаной, и наблюдала за зимним рассветом. За окнами стоял глухой февраль. Я сделала глубокую тягу и, задержав дым в легких, продолжила размышлять о смысле жизни. Тогда я лишь начинала всерьез увлекаться буддизмом и с радостью штудировала все его источники. Особенно сильно я ценила многовековые книги.

Было раннее воскресное утро, но солнце все никак не хотело показываться за горизонтом, как всегда бывает в феврале. Стоявшие неподалеку дома продолжали дремать под снежным одеялом, и лишь кое-где понемногу начинал зажигаться свет. Пустынные улицы также покрывал толстый слой снега. Снег шел всю ночь. Никем еще не тронутый, он блестел и переливался в свете уличных фонарей. Временами дул легкий ветер, с нежностью поднимал крошечные снежинки, разнося их по округе. 

Укутавшись в плед, я сидела на крыше дома, что был соседним от моего. В отличие от остальных домов этого района, здесь вход на крышу всегда оставался незапертым. К тому же с нее открывался неплохой вид на все те же парки, аптеки, дороги и игровые площадки. Подо мной было девять этажей, если не считать чердака, а на коленях торжественно покоился недокуренный косяк. 

Хотя на улице по-прежнему было мрачно и явно стоял минус, холод практически не ощущался. Мыслями я находилась где-то очень далеко, но подсознательно поглядывала на восток в ожидании того, что солнце покажет свои первые лучи.

Само собой, я думала об Адаме, 

*Чертов Адам с его ореховыми глазами и очаровательными ямочками на щеках!*

а вместе с ним и обо всех своих вместе взятых несчастных отношениях. О людях и о местах, которые когда-то были так дороги моему сердцу. 

*There are places I remember*

*All my life though some have changed…*

Меня всегда поражало то, с какой легкостью люди заводят новые отношения, будь то любовные или дружеские связи. Ведь если я люблю, то всегда самоотверженно, всей душой. Иначе я попросту не вижу смысла в отношениях. Все или ничего, смекаете? Не удивительно, что при таком раскладе у меня уходили годы на восстановление после разрыва с близким человеком. И даже поле того, как я о нем напрочь забуду, порой какой-то предмет, звук или запах вызывает во мне старые воспоминания. Убитая любовь вылезает из могилы, и вот что-то уже тихонько отзывается в моей груди. Ноет, не позволяя забыть о прошлом.

Сидя на крыше и то и дело поглядывая на восток, я вспоминала нашу первую встречу. 

<div style="text-align: center;">***</div>

Октябрь только начинал одевать деревья в золото, когда я вышла в коридор поезда, что направлялся в Москву. Дорога заняла сутки. То были часы, наполненные всеми ужасами, какие только может предоставить украинская железная дорога. Естественно, я их не заметила. Я была влюблена и счастлива, так что даже самая неудобная полка в поезде казалась мне мягким диваном, а самое грязное стекло поражало прекрасными видами осенних пейзажей. Считая себя сильным человеком, я всегда подсознательно тянулась к тем, кто морально был еще сильнее меня. Сила духа, творческая жилка и преданность своему делу – вот первые признаки, которые я искала в своем спутнике жизни. 

Рядом со мной ехала светловолосая миниатюрная девушка по имени Анастасия. Вероятно, ей было очень скучно, потому как Настя всячески пыталась завести со мной диалог. Помимо невероятно узкой талии, таинственно сочетающейся с бюстом пятого размера, я не заметила в ней ничего необычного. Знакомиться с кем-то совсем не хотелось, но мой центральный орган кровообращения томился в сладостном предвкушении грядущей встречи. Словом, настроение у меня было чудесное, так что я машинально поддержала диалог.

– Никак к парню едешь? – спросила Настя, видя мои горящие глаза.

Что ж, на протяжении всей взрослой жизни я старательно пыталась замаскировать свои чувства. Не подавать признаков влюбленности хотя бы до того момента, пока она не окажется взаимной. Наверное, мне просто не хотелось выглядеть дурой в глазах окружающих, если что-то пойдет не так. В сравнении с другими девушками мне это удавалось на ура. Я размышляла спокойно, мало жестикулировала и говорила без резких, будоражащих слух интонаций, которые так часто выдают влюбленных. Помнила, куда иду и зачем, и никогда не терялась на середине мысли. И все же я ничего не могла поделать со своими глазами, которые то и дело светились радостью предвкушения грядущей встречи.  

– К знакомому, – уклончиво ответила я. – И к подруге.

Последнее, кстати, было правдой.

– А я же от разводиться еду, – удрученно вздохнула Настя.

Она захлопнула свой «Космополитан» и принялась в деталях пересказывать мне последние два года своей жизни. За это время я успела трижды выпить чай, выкурить пять сигарет и придумать несколько имен для персонажей будущей книги. Односторонний разговор моей новой знакомой был таким долгим и беспощадным, что я даже не сразу поняла, что Настя его закончила. Временами она делала большие паузы. То ли для пущего трагизма, то ли для того, чтоб скушать очередную котлету. Ими же, кстати, она настойчиво пыталась накормить и меня, а я никогда не могла есть перед важным событием. Дальше в ход пошла картошка, яйца и шоколад. В отличии от Насти, я не была обладательницей крохотной талии, так что я каждый раз отказывалась под предлогом диеты.

*Я не могу есть при посторонних. Не могу есть, когда волнуюсь. Не могу есть, пока не разрешу важный вопрос* – настоящий аргумент звучал бы стремно, согласитесь.

– А ты собсно чим занимаешься? – беспечно поинтересовалась Настя. 

Так, словно ее полуторачасового монолога и вовсе не было.

К слову, у Насти был очень странный говор. Местами она говорила четко, как бы стараясь воспроизвести московское произношение с рвением прилежного студента, а затем забывалась, и в рассказах девушки начинали проскакивать деревенские словечки. В итоге выходила лютая смесь русского и украинского, которая не поддавалась правилам грамматики ни одного из этих языков. В моих краях такую речь называли суржиком.

– Я пишу книги.

– Так ты отой, писатель?

– С чего ты взяла? – не удержалась я, и спутница посмотрела на меня в глубоком замешательстве. 

С нечеловеческим усилием воли и божьей помощью мне удалось подавить ухмылку.

– Всего лишь шучу, – поспешно объяснила я. – Да, я писатель.

Настя призналась, что за свою жизнь не прочитала ни одной книги, если не считать кратких пересказов, которые она просматривала вместо чтения школьной программы. При этом ее почему-то жутко заинтересовали мои опусы. Ведомая этим непонятным порывом, собеседница принялась засыпать меня уймой вопросов.

Как часто я пишу? – стоит прийти вдохновению, и я хватаюсь за книгу, где бы ни была.

Как я пишу? – от руки; в бесконечных блокнотах хорошо заточенным карандашом. 

Как я знаю, что надо сделать перерыв? – когда понимаю, что закончила каждую из появившихся мыслей – все до единой – и мне просто больше нечего сказать; писатель всегда сам чувствует, когда нужно отложить работы и подзарядиться идеями от реальной жизни.

Как я придумываю имена для основных персонажей? – обычно если герой является моим альтер-эго, его или ее имя будет начинаться заглавную букву моего имени, а фамилия должна непременно начинаться с Р.

– Почему Р?

– Чтоб никто не догадался.

– Смысле?

– Потому что я ее не выговариваю, - спокойно ответила я и улыбнулась. 

Шутка, которую понимают только в узких кругах.

– Правда что ле? А я и не замитыла.

– Никто не замечает, пока я сама не скажу.

– Как так?

– Это потому, что я не картавлю. Я просто ее игнорирую, заменяя каким-нибудь похожим звуком, – сказала я уже наверное в пятисотый раз за последние девятнадцать лет. – Хотя местами бывает сложно. Особенно если после «р» идет мягкий знак и они находятся в конце слова. Тогда меня просто никто не понимает.

Спустя еще одну чашку чая с расспросами было покончено. Настя вернулась к своему журналу, и я не без облегчения откинулась на стену и поспешила надеть наушники на случай если девушка передумает. Уши обволакивали шуршащие нотки «Интерпола». Наконец можно вернуться к греющим душу думам: о наступающем утре, об Адаме, нашей первой встрече и том, как он меня поцелует.

*Интересно, сколько он продержится без поцелуя?* – подумалось мне. 

Я взглянула в собственное отражение, улыбающееся мне со стального поручня, и поняла, что недолго.


