# 26 {-}

Пожалуй, нужно и впрямь быть осторожнее со своими желаниями. Так или иначе, той осенью я получила свой двухнедельный роман, который не могла забыть последующие годы. Вернемся же к зиме пятнадцатого и ко мне, беспечно покуривающей косяк на крыше соседней многоэтажки.

Со дня встречи с Адамом прошло два года и четыре месяца. На улице стояло тихое, снежное утро февраля. Как и все мои феврали, этот был мрачным и одиноким. Сидя на крыше и потягивая принесенный из дома в термосе глинтвейн, я вдруг спросила себя: 

*Будут ли мои феврали такими же одинокими, когда я отыщу свою родственную душу? *

Первые полгода после расставания с Адамом я еще как-то держалась. Окрашивание волос в алый цвет стало первым, что я сделала после его прощального звонка. Зачем? Сама не знаю, но мне понравилось. Я накупила себе целую кучу новых туфель и появлялась на людях исключительно при полном параде. Мои губы всегда были подведены алой помадой, а на глазах виднелись осторожно выведенные стрелки. Словом, меня внезапно настиг новый образ, очень походивший на современный пин-ап. Мало кто знал о том, что я продолжала переживать по поводу Адама. В те дни это было известно разве что Мишель – моей ближайшей, пускай в дальнейшем и не очень галантно поведшей себя подруге да парочке старых знакомых, которым я проговорилась по пьяни. В общем и целом, ни мое окружение, ни, конечно же, сам предмет моих воздыханий не догадывались о том, что я чувствую. При этом какая-то часть моего сознаний по-детски продолжала верить в то, что нас еще ждет счастливый конец.

Большой вклад в попытки восстановить мое душевное здоровье внесла литература. Без сомнений, ее позиция в рейтинге вещей, имеющих смысл в моей жизни, укрепилась еще сильнее. Оставшись одна, я ни дня не проводила без писательства и поражалась тому, что еще в начале осени жаловалась на отсутствие вдохновения. Ложечка душевной боли, щепотка разбитых сердец, приправить суицидиком, и я становлюсь самым продуктивным автором на свете. Независимо от моего желание, главный мужской персонаж романа постепенно приобретал черты былого возлюбленного, и чем больше я этому противилась, тем сильней мой герой походил на Адама.

– Что бы там ни произошло, я никогда этого не забуду, – дрожащим голосом произнес Адам за ночь до того, как мне нужно было покинуть Москву.

– Я тоже. Ни за что не забуду, – пообещала я, чувствуя, как к глазам подступают слезы. 

Последние я сдерживала изо всех сил, но одинокая слеза таки набралась смелости скатиться по моей щеке, и мужчина тут же смахнул ее.

– Пришлешь мне экземпляр своей книги, когда закончишь? – спросил Адам.

Я покачала головой.

– Посмотрим, понравится ли она мне.

– А может не понравится? – изумился Адам.

– Конечно.

– Но ты все равно пришли. Даже если это будет худшей из твоих идей. Я хочу ее увидеть.

– Почему?

– Потому, что она развивалась в твоей голове в то время, как ты была со мной, – просто объяснил Адам.

Я улыбнулась.

– Какое самолюбование!

– Так что, пришлешь? 

– Давай так, – предложила я. – Я не стану обещать, что покажу тебе эту книгу, но могу пообещать, что посвящу ее тебе. И если у книги дела пойдут лучше, чем у наших отношений, ты узнаешь о ней. Откроешь, и поймешь, что она для тебя.

Так уж сложилось, что у книги дела и впрямь пошли лучше, чем у наших отношений. Правда я так и не решилась ее издать, но в отличии от нашего с Адамом романом, мое творение прожило гораздо дольше и обрело нуждающийся в продолжении конец. Как я уже говорила, все мои персонажи так или иначе отображали меня и мое окружение. И хотя книга была вовсе не о любви, без влюбленной парочки здесь не обошлось. Думаю, и так понятно, кто был прототипами этих ребят.

*Пускай хотя бы у них все будет в порядке!* – думала я каждый раз, которым бралась за книгу.

<div style="text-align: center;">***</div>

Так пронеслась зима, а вслед за ней и несколько недель весны. Я опомнилась лишь в апреле четырнадцатого, когда книга была дописана. Это вынудило меня вернуться к безжалостной реальности. Пожалуй, тогда я впервые по-настоящему осознала, что больше никогда не увижу Адама.

Знаю, бывают вещи и хуже этой и с многими из них мне только предстояло встретиться. Тем не менее, я чувствовала себя слишком грустной и старой для того, чтобы жить спокойной жизнью. К тому же, мой мозг почему-то непрестанно идеализировал образ бывшего возлюбленного, всячески отрицая его негативные качества. Тогда я только начала подозревать о своём психическом расстройстве, которое в юношеские годы казалось обыденными перепадами настроения. Знаете, подросткам свойственно горевать из-за мелочей, но я уже не была подростком, а депрессия становилась все более затяжной.

Я и прежде слышала о биполярном расстройстве, но никогда не относила эти истории к себе, пока однажды не прочитала книгу, где вскользь упоминались присущие заболеванию симптомы. К тому моменту мне уже исполнилось двадцать, и я, наконец, нашла объяснения большей части тех вещей, что происходили со мной на протяжении многих лет.

Весь последующий год я посещала различных докторов, принимала лекарства и проходила терапии. В общем и целом, я сменила около восьми психологов и шести психотерапевтов, одному из которых все же удалось упечь меня в лечебницу. Ни один док толком не мог мне помочь. Рано или поздно становилось ясно: о моем расстройстве местным эскулапам известно меньше, чем мне. Я читала слишком много философов, с детства интересовалась психиатрией, имела толерантность к препаратам и, в отличие от докторов, владела еще и практическими знаниями. Так что с появлением диагноза все это сложилось в один мрачный пазл под названием «Внутри Елизаветы Васляевой», собрать и разобрать который могла только я.

Один терапевт, все же, смог мне помочь. Его звали Сиддхартха Гаутама, а для друзей – просто Будда.

Все это время меня окружали разные люди, и многие мужчины одаривали меня недвусмысленным вниманием. На протяжении пары летних месяцев я даже виделась со своей школьной любовью. Мы пили мятные настойки, будучи абсолютно голыми, и рассказывали друг другу забавные истории, которые произошли с нами за прошедшие годы. Как и я, Эрик очень изменился внешне, но в душе оставался все тем же беспечным шалопаем. Общаясь с ним, я едва ли могла представить этого молодого человека в серьезной связи. Эрик, который тогда только закончил самые долгие в своей жизни отношения, тоже не имел на меня серьезных видов. Было весело.

И, все же, я хранила обещание, данное себе в девятнадцать лет и не желала строить отношения с тем, к кому не испытывала хоть сколько-нибудь сильных чувств.

«Я буду вместе лишь с тем мужчиной, которого смогу полюбить сильнее, чем Адама» – однажды написала я в своём дневнике.

Так и получилось.

Так вот, ни алкоголь, ни стремительно растущий круг знакомых, ни впечатляющее разнообразие прописанных докторами таблеток не смогли помочь мне. Бывают в жизни моменты отчаяния, когда ты тупо сидишь на заднице. Уставший, удрученный и побитый судьбой, просто сидишь и ждешь, когда кто-нибудь войдет в дверь, чтобы наладить твою жизнь. В таком состоянии я написала лучшую в своем творчестве трагикомедию, но никто не появился в дверном проеме. Не протянул мне руку и не кинулся решать мои проблемы. Тоска по Адаму, которого я не видела уже больше двух лет, отчаянно не хотела меня покидать. Тогда-то и произошло чудо, по внезапности своей сравнимое лишь со вторым пришествием. За дело взялся единственный человек, способный мне помочь. Как ни странно, этим человеком оказалась я сама.

Случилось это в феврале пятнадцатого, на той самой крыше, о которой я говорила. Не знаю, было здесь дело в травке, буддизме, или рассвете, – а может мне просто вдруг стало тошно от собственных печалей – но я внезапно поняла, как должен быть устроен мой внутренний мир. Я больше не стремилась отыскать истинную любовь и не хотела вернуть расположение своего бывшего. Все, чего мне хотелось, так это просто стать счастливой. Тогда-то я и осознала, что счастье не должно быть изменчивым. Какой бы ценной мне не казалась любовь, человек должен уметь быть счастливым вне зависимости от того, состоит он в отношениях или нет. Первое, что должно тебя волновать, – это отношения с самим собой, второе – с миром вокруг. Лишь добившись внутренней гармонии можно стать по-настоящему счастливым. В конце концов, счастье – это не какая-нибудь шаткая переменная. Счастье – это константа, понимание себя и внутреннее спокойствие, которое находятся с тобой все время. Только приняв себя со всеми изъянами и недостатками можно построить крепкие отношения с другим человеком. 

*Прежде, чем ладить с другим, научись ладить с собой*, шепнул мне внутренний голос. 

Увы, даже высокая самооценка не является залогом внутренней гармонии. На самом деле, ее наличие довольно легко проверить. Для этого нужно лишь запереться в комнате, отказавшись от социальных сетей и прочих иллюзий чьего-либо присутствия.

Вот так, выдыхая смешанный с марихуаной табак на фоне поднимающегося зимнего солнца, я внезапно стала собственной аудиторией. Мне больше не требовалось литературное признание, верность накануне предавшей меня подруги и наличие спутника жизни. Я вспомнила Адама, его добрые глаза, очаровательные ямочки на щеках, сладкий запах туалетной воды, бархатный голос, кожаную куртку и волосы, ниспадающие на плечи. Его родинку над верхней губой, постоянную щетину, плавно переходящую в бороду, пошлый взгляд и семейки с коняшками. Вспомнила все до мельчайших деталей и мысленно попрощалась с этим человеком.


