# &nbsp; {#chapter-27}

Сколько воды утекло прежде, чем я обнаружила себя здесь, на смотровой площадке Севастополя, расположенной напротив памятника затопленным кораблям. Стоя под руку с Вениамином, я внезапно вспомнила о том, каким потерянным было мое состояние до того, как я удосужилась откорректировать собственной мировоззрение. Более того, глядя на своего жениха, я не без шока отметила, что он, видимо, и есть тот цепляющий взгляд ламберсексуал, о котором я грезила во времена депрессии. Это, конечно же, удивило меня, но не расстроило. Просто еще одна деталь громадной мозаики, которая поможет в очередной раз переосмыслить общую картину. Еще тысяча таких вот деталей всплывет прежде, чем я стану прахом. И каждый раз конечный результат будет все более и более удивительным. Наверное, в этом и кроется прелесть жизни. Ее смысл в том, что смысла нет.

Передо мной лоснилось море. Оно шумело и смеялось, унося все тревоги, скопившиеся в головах прогуливающихся по бульвару людей. Я выросла в местах, где море видела почти так же часто как небо. И, все-таки, здесь и сейчас оно казалось мне исключительно прекрасным. Стоя у воды, я жадно впитывала бриз и наслаждалась открывающимся пейзажем с видом молодого лорда Байрона, созерцающего берега родной Англии.

Ничего на свете больше не имело значения. Были лишь солнце и волны, скалы да море, морская пена и тот особенный аромат, который источают исключительно крымские берега. А еще была я и Вениамин, стоявший рядом. Солнце по привычке играло в его волосах, превращая их из пшеничных в ярко золотые, а я была гораздо счастливей, чем могла когда-нибудь вообразить. Стоя здесь, в объятьях любимого человека, я знала, что однажды все это исчезнет. Не будет ни меня, ни моих проблем. Останутся лишь берега и долины, обрамляющие море. Сколько бы лет ни прошло, люди все так же будут приходить к морю в моменты радости и печали. Просто потому, что эта чистота волн и непоколебимость морских глубин помогают нам многое переосмыслить.

Да что тут и говорить: мир построен на одном лишь переосмыслении. Мой так точно.

