# 29 {-}

Близился день моего отъезда. Как и всегда, конец отпуска подкрадывался незаметно, но очень стремительно. Так за бесконечными разговорами, прогулками по городу, распитием вина, проводами закатов и бессонными ночами пролетел остаток весны. Лето уже вовсю давало о себе знать, а значит, пришла пора ехать домой – к родным, собакам и бару. Последний особенно нуждался во мне: изо дня в день коллеги и приятели заваливали меня вопросами о том, когда же я наконец вернусь. 

На протяжении первых месяцев две тысячи шестнадцатого года я была единственным барменом в ресторане, если не считать мимолетных стажеров. Юные и напуганные предстоящей работой, они исчезали так же быстро, как и появлялись. Я говорю «юные», хотя многие из них были на пару-тройку лет старше меня. 

И все-таки в моих глазах они были юными, не привыкшими к тяжелой работе молодыми людьми. Некоторые не выдерживали и пары часов, тогда как самые отважные простаивали пару смен. Стоит ли говорить, что каждый из них был со странностями. 

«Мы все странные, – любил говаривать Веня. – А кто не странный, тот странный».

Однако странности моих потенциальных сменщиков таили в себе качества едва ли совместимые с родом их будущей деятельности. К примеру, был один айтишник. Занудный, инфантильный, но в общем-то ответственный парень. Проблема крылась в том, что он не мог никому отказать. Угощал всех сотрудников бесплатным кофе и, стоило им только попросить, наливал чего покрепче. Ввиду то ли врожденного, то ли приобретенного в бывшей сфере деятельности задротства, которое нынче принято называть стеснительностью, он не мог сказать «нет». Так даже самый жалкий и захудалый сотрудник «Штиля» приобретал в глазах моего временного коллеги небывалый авторитет. Что уж говорить о барменах, работающих в клубе? По вечерам они ленились ходить на склад и непрестанно поднимались в ресторан, дабы перед предстоящей ночью запастись алкогольными и безалкогольными напитками. 

Как и все представители клуба, помощники барменов и официанты были существами грубыми, не особо обремененными вежливостью. Первые месяцы моей работы в «Штиле» прошли в этом чертовом клубе. Меня не страшило ни отсутствие чаевых, ни график с восьми вечера до шести утра, ни смехотворный оклад, духота и толпы пьяных отбросов, снующие туда-сюда и кричащие что-то невразумительное мне, себе и друг другу. Откровенно говоря, меня не смущали и стриптизеры с танцовщицами, которые периодически подрабатывали проститутками. Даже тот факт, что стоя на рабочем месте, ты извечно видишь либо задницы, либо пироги, обтянутые узкими стрингами и танцующие прямиком на стойке всю ночь напролет, не мог испортить мне настроение. Говоря о клубе, меня напрягали лишь две вещи: громкая, лишенная вкуса и смысла музыка да неадекватный персонал. Включили бы «Пинк Флойд» – другое дело!

Порой у меня складывалось впечатление, что во время собеседования будущих сотрудников развлекательного комплекса проверяли на вменяемость, а затем всех, кто провалил тест, ссылали вниз, в клуб. Если не считать парочки старых, дружелюбных барменов, которых все уважали за количество лет, проведенных в «Штиле», персонал клуба представлял собой сборище неуравновешенных, крикливых и злых людей. В основном, девиц. Особенно ярко эти качества проявлялись среди кассиров и официантов, в то время как стриптизерши оказались самыми тихими и воспитанными представительницами коллектива. 

Подгоняемые какой-то неведомой здравому уму силой, работники нижнего этажа «Штиля» ни с кем не здоровались, толкались, топтали друг другу ноги и разговаривали исключительно при помощи крика. Они терпеть не могли друг друга и все вокруг. Даже рабочая запара не была в силах сплотить этих идеальных пациенток Карла Юнга. Единственное, что могло заставить их держаться вместе, – появление нового человека в коллективе. 

Официанты ненавидели барменов за то, что те были более эрудированными и выполняли, по их мнению, легкую работу, которая не предполагала беготни среди танцующей и изрядно выпившей толпы. А также за то, что те частенько давали им различного рода поручения, (к примеру, унести подносы с грязной посудой, принести с мойки чистые стаканы или пополнить запасы льда), которые официантам приходилось выполнять. Конечно же, они в равной степени ненавидели и стриптизерш, и танцовщиц по вполне предсказуемым причинам. Другие фицы и, в частности, новоприбывшие лица также незамедлительно подвергались моральному насилию. На самом деле, проще сказать, кого не ненавидели официанты цокольного этажа. 

Как бы там ни было, осенью две тысячи пятнадцатого предметом их ненависти стала я. Сложно сказать, почему это произошло. В основном они просто злились на то, что их зарплата была на пару сотен меньше моей. К тому же на все заведение я оказалась единственной девушкой, занимавшей должность бармена. Среди официанток клуба не было ни одного мужчины, и, гонимые слегка ограниченной логикой, они считали, что я нарушаю какие-то невидимые рамки. В те дни у меня был пирсинг – над губой и в брови – и несколько татуировок, кокетливо виднеющихся из-под рабочей формы. Они также добавляли масла в огонь. 

Пожалуй, все это не имело особого смысла потому, как официанток ничуть не меньше раздражала моя шевелюра, а происходило это даже в те ночи, когда я собирала ее в объемный пучок или две идеально зачесанных гульки. 

<div style="text-align: center;">***</div>

Половину времени я работала рядом с Антоном – главным барменом «Штиля». Это был высокий, молчаливый мужчина с грустными синими глазами. Мы познакомились за полгода до того как я попала в развлекательный комплекс. Антон был руководителем школы барменов, где я стала одной из первых учениц. Он отвечал за практическую часть обучения и проводил трехчасовые тренировки по флейрингу, в котором стал общепризнанным мастером и многократным чемпионом.

Несмотря на всегда галантную одежду, приятную внешность и неприкрытый талант, Антон сперва мне не понравился. Слишком уж холодными казались мне его глаза, а взгляд часто был каким-то отсутствующим. Добавьте к этому дефицит эмоций и получите мое первое впечатление о будущем начальнике. 

Определенно, в первые дни обучения Антон Качанников казался мне не очень приятной личностью: я никогда не была склонна доверять тихим, безэмоциональным людям. Порою мне даже делалось не по себе от одного его присутствия. Так было до того дня, пока учитель не собрал всех в тренировочном зале, где я вновь оказалась единственной представительницей слабого пола.

– Почему вы решили стать барменами? – спросил Антон.

Казалось, вся серьезность этого бренного мира собралась в его вопросе, и стоявшие напротив ученики принялись отвечать с не менее солидным видом.

– Я считаю, что эта работа открывает широкие перспективы.

– Мне с детских лет хотелось стать барменом.

– По-моему, работа барменом дает кучу возможностей…

И так далее. Кто-то даже сказал, что ему очень хочется работать с людьми.

Все это время лицо Антона оставалось бесстрастным. Он лишь кивал, услышав очередной ответ, и молча переводил взгляд на следующего ученика.

– Мне кажется, это так интересно, – ответил стоявший рядом со мной парень.

– Ну а я просто люблю бухать, – сказала я. – Люблю я алкоголь и хочу знать о нем все. 

– Правда? – тень улыбки скользнула по губам Антона.

– Ага. Так всегда бывает, если я что-то люблю. И вообще я вовсе не собираюсь становиться барменом.

На мгновение огромные глаза нашего тренера стали еще больше. А затем его лицо впервые на моей памяти осветила широчайшая из улыбок. Тут-то я и поняла, что мы, наверное, подружимся. 

