# &nbsp; {#chapter-30}

Да, я действительно любила алкоголь, и на то был целый ряд причин, о содержании которого вам расскажет любой более-менее вменяемый алкоголик. Впервые мысль стать барменом посетила меня в начале две тысячи пятнадцатого. 

Тем вечером я привычно шагала мимо широких полок супермаркета, что были вдоль и поперек уставлены стеклянными бутылками. Виски, коньяк, ром, абсент, бренди, текила, джин, ликеры, бальзамы, настойки и, конечно же, вино – все это я употребляла с завидной регулярностью и в отношении каждого из перечисленных выше напитков у меня были любимчики. 

Не любила я только водку и то лишь благодаря детской травме. 

<div style="text-align: center;">***</div>

Мне было лет семь. Одним жарким летним днем я примчалась с речки и пулей влетела в дачный домик, ну просто умирая от жажды. Сколько себя помню, я всегда пила воду в огромных количествах. Или, по крайней мере, так было прежде, чем я переключилась на алкоголь. Так, я могла залпом опустошить литровую бутылку и не напиться. Смеясь, родители называли меня водохлебом. 

Так произошло и в то лето. Я вбежала на кухню, распахнула холодильник, схватила стоявшую внутри бутылку минералки и, прежде, чем мама успела мне что-либо сказать, жадно к ней приложилась. Волею судьбы, бутылка минералки оказалась бутылкой из-под минералки, в которую утром налили содержимое кем-то надбитой бутылки водки. Естественно, всего этого я знать не могла. Сложно сказать, когда именно я поняла, что что-то пошло не так. Жидкость была ледяной и пила я ее очень быстро. Большими глотками. Взахлеб. Бутылка опустела миллилитров на двести, а лицо матушки сделалось совсем испуганным, когда мой мозг, наконец, распознал подмену. 

Ротовую полость словно обдало кипятком, а язык мгновенно онемел. Но все это меркло и бледнело по сравнению с тем, что происходило ниже. Внутри все горело, и я вдруг с ужасом поняла, что не могу дышать. Пошатываясь, я неуклюже привалилась к стене и принялась тупо таращиться на бутылку. Та по-прежнему оставалась в моих руках. Судорожно пытаясь втянуть в себя хоть глоток воздуха, я принялась кашлять. По лицу беспрерывно текли слезы. Сначала от боли, затем от обиды, ну, и в конце из-за страха. Перед глазами все плыло, а голова раскалывалась почти так же сильно, как раскалывалась голова одного из античных богов, о котором я читала тем летом. Вскоре из черепа его появилась дочь, а я вот просто стояла и задыхалась. При этом продолжала с ужасом смотреть на пластиковую бутылку – источник всех моих мучений. Тогда я была уверена, что по какой-то страшной ошибке выпила самый настоящий яд.

Так я впервые попробовала водку. В первый и в последний раз. И так я поняла, что, несмотря на то, что обещанное похмелье, почему-то обошло меня стороной, водку я терпеть не могу. Словом, вопреки ярому пристрастию к алкоголю, я всячески избегала этот продукт. В коктейлях – без проблем, но только попробуйте подсунуть мне это пойло в чистом виде!

*Ну все*, обреченно подумалось семилетней мне. *Меня отравили.*

Испуганное лицо матери сделалось расплывчатым силуэтом, к которому вскоре присоединился силуэт примчавшегося на ее крик отца.

*Я их достала и они меня отравили*, решила я прежде чем шлепнуться лицом в пол.

<div style="text-align: center;">***</div>

Уже в двадцатилетнем возрасте, плавно разгуливая вдоль алкогольных прилавков, я вдруг осознала, что совсем не разбираюсь в алкоголе. Чертовски хотелось выпить чего-нибудь эдакого, но я понятия не имела, как это эдакое должно выглядеть. Я где-то слышала о том, что текст, написанный на обороте бутылки, не имеет никакого значения. Верить можно лишь передней части этикетки, а ее, как бы странно это не прозвучало, нужно уметь читать.

Вот я повертела в руках сначала одну бутылку, затем другую… Увы, чтение этикетки говорило мне не больше, чем тексты Die Antwoord. Меня это разозлило, ведь в годы новообретенной взрослости мне почему-то казалось, что нет ничего хуже, чем опростоволоситься перед самой собой. 

Тем вечером я ушла домой с пустыми руками, а с приходом весны уже числилась в недавно открывшейся школе барменов. В итоге я оказалась не только единственной, кто честно ответил на вопрос Антона, но и единственной, кто сдал все экзамены на отлично и с первого раза получил диплом.

– Это для той, которая не хочет быть барменом и просто любит бухать, – с гордостью произнес Кочанчиков, протягивая мне документ. – Аплодисменты, товарищи!

Тренер принялся хлопать в ладоши, а вслед за ним и собравшиеся на вручение дипломов ученики.

– Теперь я сертифицированный алкоголик! – с довольным лицом ответила я, тем же вечером закинула диплом в какой-то ящик и с тех пор его не видела.

Как я уже сказала, мое недоверие к Антону улетучилось. Я искренне восхищалась волшебством, которое он проделывал с бутылками, шейкерами, стаканами и прочими предметами во время флейринг-шоу. Сказать больше, я даже научилась нескольким связкам и с гордостью демонстрировала новое умение по поводу и без. 

Спустя несколько недель я познакомилась с семьей своего учителя – красавицей женой и славным мальчуганом, которому вскоре предстояло пойти в первый класс. А под конец обучения я узнала, что у жены Антона был рак. Ей требовалось срочное лечение в столичной клинике, которое стоило не один десяток местных зарплат. Услышав об этом, я тут же поняла причины всех этих затуманенных взглядов Антона, его отрешенности и отсутствующего вида. Поняла и внезапно устыдилась того, что когда-то испытывала неприязнь к этому трудолюбивому и несчастному человеку. Еще более неловко мне стало, когда ученики школы принялись собирать средства на помощь семье Качанниковых. Они, конечно, скидывались кто сколько мог, но ни один не дал меньше трех сотен. Я же к тому моменту уже второй год была на мели, собирая мелочь на сигареты, а последние сбережения ушли на оплату обучения.

В конце концов, я успокоила себя, дав обещание, что помогу Антону при первой же возможности. 


