# &nbsp; {#chapter-32}

Работа без выходных – само по себе занятие не из приятных. Еще менее приятным его делал тот факт, что работала я не меньше двенадцати часов. Порой клиенты засиживались до самого утра, делая мой рабочий день, скажем, шестнадцатичасовым. После таких смен я понимала, что ехать домой – так себе затея, и укладывалась в подсобке, чтобы проспать заслуженные четыре часа.

Никто не мог понять, с какой радости я стала таким трудоголиком, памятуя о моем хроническом упрямстве, идущим под руку с выдающимся самомнением, которое в итоге вызывало у меня отвращение перед всем, что представляло собой «бесполезную работу, которую нужно работать, находясь на работе». Конечно, все как-то с этим живут, но я слишком ценила свое время, дабы добровольно отдавать его на подобного рода нужды. 

При этом нельзя сказать, что я слыла ленивым или безответственным сотрудником. Напротив, я всегда старалась подобрать более-менее интересную для себя вакансию и с энтузиазмом приступила к делу. Но, что уж таить, весь этот энтузиазм тут же улетучивался в ту самую минуту, когда я понимала, что обзавелась достаточным багажом знаний и опыта и что текущая работа едва ли сможет научить меня чему-то новому. По этой простой причине я не единожды меняла сферу деятельности. Ведь я могла разбираться в чем угодно, но в действительности считала, что единственное мое ремесло – это  писательство. Так что, со временем тоска по перу брала надо мной верх. Я незамедлительно увольнялась без малейших зазрений совести. Так происходило каждый раз, и, конечно же, «Штиль» не стал исключением.

<div style="text-align: center;">***</div>

Первый тревожный звоночек раздался за месяц до того, как я встретила Вениамина. Южноукраинская весна уже вовсю давала знать о стремительно приближающемся лете. В воздухе не было прохлады, не было влаги и свежести, из-за которых мне так нравилось бродить по улицам в эту пору года, как не было и клиентов в любом из залов «Штиля». Ресторан пустовал уже который день. Единственными посетителями были редкие парочки, пришедшие поиграть в боулинг. 

Стрелка часов уже давно перевалила за полдень, когда мы с Линой уселись на заднем дворе развлекательного комплекса. Привычным жестом я забросила уставшие ноги на некогда пивной столик, и протянула подруге наполненный льдом стакан холодного чая. К тому моменту мы обе бросили курить, (как всегда, временно) так что теперь выходили на воздух просто для того, чтобы им дышать. 

Лина была лучшим из того, что дала мне работа в «Штиле». И, пожалуй, единственным положительным моментом.

Мы познакомились минувшей зимой. Тогда Лина еще работала в гардеробе клуба и осветляла волосы, что делало их чересчур неестественными. Родом она была из соседнего ПГТ и при первом же знакомстве, объявила мне, что она – «проста як дверi». Так оно и было, но, все же, Лина оказалась так не похожа не всех тех грубых, несдержанных и прямо-таки оголтелых сельских девиц, которых я встречала прежде. Она была веселой, прямолинейной и рассудительной, чем мне и понравилась. Было в ней еще кое-что примечательное: спокойный, но пристальный взгляд, которому так не хватало проницательности. Глаза Лины говорили о том, что в ее жизни было немало трагических событий, а также о том, что она смогла их пережить. И это мне понравилось еще больше.

Так вот, тем днем мы сидели на заднем дворике «Штиля» и чего только здесь не было! Вокруг виднелись самые неожиданные предметы: топоры, тележки и супермаркета, дрова, автомобильные запчасти… На груде бревен красовались бутафорные березы, выполненные в розовых тонах. За ними грудились пласты никому не нужного искусственного снега, а рядом блестел на солнце побитый жизнью штурвал. 

– Что я здесь делаю? – монотонно произнесла я, разглядывая покосившиеся ветви искусственных деревьев.

– Сидишь. Бросаешь курить. Дышишь воздухом, – Лина улыбнулась и, отхлебнув моего холодного чая, спросила: – Слух, а это точно чай?

– Да, это Лонг-айленд.

И я повторила свой вопрос.

– Та шо ты от меня хочешь? Я не пойму тебя. Ты спрашиваешь это уже четвертый день подряд.

– Но я имею в виду, что я делаю здесь…

– В «Штиле»?

– В «Штиле», вне «Штиля». Такое чувство, что теперь моя жизнь делится лишь на два временных пространства. А я все так же не понимаю, что я в этой жизни делаю.

Внезапно мне очень захотелось закурить. Впервые с начала года.

– Лиза, – Лина громко выдохнула, от чего ее пухлые губы сделались огромными, – я задаю себе этот вопрос уже много лет. Если бы я знала на него ответ, я бы тебе его сказала. Только ты не забывай, шо мне скоро тридцать, а тебе только двадцать два. 

И в самом деле, я частенько забывала о том, что ей не двадцать. Лина вовсе не выглядела на свой возраст. Как, в общем-то, и я.

– Тебе двадцать семь, – напомнила я. – Не тридцать.

– И шо?

– А то, что ты тоже можешь изменить свою жизнь.

Лина окинула меня взглядом усталого родителя, который смотрит на надоедливого ребенка, но так ничего и не сказала. Слишком многое ей пришлось пережить и еще больше было того, что Лине пришлось забыть. 

Подруге было около двадцати, когда ее жених погиб в автокатастрофе. После его смерти Лина так и не смогла заставить себя завести отношения с мужчиной. Да, в общем-то, ей это и не требовалось: Лина обнаружила, что выступает за обе команды. Теперь она была по девушкам. Тем не менее, вслед за катастрофой ее настигли крайне болезненные отношения. Эта связь продлилась четыре года и буквально выпила из Лины все соки. Добавьте к этому смерть младшего брата, бабушку, которая, не одно десятилетие лежала парализованная, тяжелый сельский труд и отца-алкоголика, обрекшего семью на голодное существование, а затем и вовсе завел любовницу и заделал той ребенка.

И, все же, Лина продолжала жить. Она сидела напротив меня, потягивая ледяной коктейль, и мечтательно улыбалась, рассказывая о предстоящем пикнике. Я слушала о том, что в деревне скоро зарежут молочного поросенка, о том, как правильно мариновать мясо, чтобы шашлык получился мягким… Видела, с какой легкостью она радуется мелочам, и не могла не уважать свою подругу. 

*Я считаю себя сильным человеком*, однажды сказал мне Адам. *Потому я подсознательно тянусь к таким же сильным людям. *

Услышав это, я вдруг осознала, что Адам, сам того не ведая, в паре слов описал всю суть моих взаимоотношений с другими людьми. С детских лет я была мизантропом. Мне претило общество с его глупыми устоями и двуличными стереотипами. По этой простой причине в отношении друзей я была крайне избирательна, но если уж встречала своего человека, то до конца оставалась верной нашей дружбе.

– Ты сильная, – настойчиво повторяла Лина каждый раз, когда слезы угрожали выступить на моих щеках. 

Когда я ходила по острию ножа депрессии подруга продолжала говорить о моей силе духа и о том, что я самый крепкий и целеустремленный человек из тех, что она знала. Словом, я не могла ее подвести. Вместо этого рассказала ей о своем психическом расстройстве. Лина отнеслась к нему с пониманием, что было так несвойственно жителям моего родного города.

Мне хотелось плакать, чертовски хотелось, но я не могла позволить себе расклеиться. Стоило слезам подступить к глазам, а предательскому кому образоваться в горле, и мне вдруг становилось очень стыдно за свою слабость. Понемногу желание это начинало улетучиваться, а затем и вовсе сходило на нет.

Уже которую неделю подряд мы выползали на солнышко, закидывали ноги на покрывшийся ржавчиной пивной стол и говорили обо всем на свете.

– Я словно от сердца отрываю каждый час, который зачем-то просиживаю за барной. Посетителей нет, банкетами и не пахнет… Черт, так ведь даже на дом никто ничего не заказывает! И на кой хрен тогда нам тут торчать? Просто я слишком ценю свое время, я тебе это уже говорила. Наверное, в этом и есть моя проблема. На протяжении последних лет я измеряю свое время не событиями, эмоциями и планами, а лишь объемом писательской работы, которую могла бы проделать, если бы не страдала хуйней вроде ежедневных походов на не писательскую работу. Вот даже сейчас я торчу здесь и понимаю, что за это время могла бы написать не одну главу.

Лина посмотрела на меня с сочувствием. Вроде как хотела дать совет, но в последний момент передумала.

– Выпей-ка лучше своего «чаю», – сказала она, протягивая мне стакан.

<div style="text-align: center;">***</div>

Прошла еще одна рабочая неделька. На город обрушились непрекращающиеся ливни, и клиенты вновь вернулись в стены «Штиля». Как и следовало ожидать, даже новый наплыв работы не мог заставить меня забыть об авторских амбициях. Процесс осознания неправильности происходящего был запущен. Перо истосковалось по мне, и я то и дело слышала его зов.

– Ну, так и зачем же ты тут сидишь? – спросила Лина.

Вопреки тому, что я так часто задавалась подобными вопросами, я, все же, продолжала отдавать работе подавляющую часть собственного времени. Ответ был прост. Однажды я обнаружила, что многочасовой и выматывающий труд положительно влияет на мое душевное состояние. Это работало ничуть не хуже буддизма, который я стремилась постичь с начала прошлого года. 

Наполненные суетой, рутиной и усталостью дни летели один за другим. Из-за постоянной беготни и сомнительного отдыха мои ноги непрестанно болели. Происходило это так часто, что вскоре я и вовсе прекратила обращать внимание на боль, сковывающую ступни и плавно поднимающуюся вверх по икрам. Вместе с болью ушло еще кое-что – я с искренним удивлением обнаружила, что вдруг избавилась от многолетней депрессии. Сложно сказать, когда именно это произошло. Я была слишком увлечена работой да попытками задержаться на этом свете, но факт оставался фактом. Физически измотанная, я внезапно поняла, что моральная усталость покинула меня. Не было бессонных ночей, среди которых я бесцельно бродила по дому и его окрестностям. Не было слез, которые прежде то и дело выступали на моих глазах, стоило мне остаться наедине с удушающими воспоминаниями. Не было и мыслей о самоубийстве.

– Уже незачем, – чуть слышно ответила я.

Перепрыгнула через барную стойку и принялась радостно тискать подругу.

– Чего-чего?

– Мне больше не нужно здесь быть, Лина! Миссия выполнена.

– Я нихера не понимаю, но я за тебя очень рада, – ответила девушка.

– Будешь кофе?

Но Лина не успела ответить: зазвонил телефон, и кассир поспешила снять трубку.

– Это по твою душу, – сказала Лина, протягивая мне аппарат.

В подземелье хотели пятнадцать детских мохито и четыре взрослых. 

*Блядские мохито. Ну кто вообще справляет детские дни рождения в клубе?*

– И побыстрее! Мелюзга уже вовсю вопит! – голос хриплый, чуть ли не потусторонний, и прямо-таки гавкает, а не говорит.

Когда я положила трубку, Вера уже стояла на раздаче, обещая вскоре обоссаться.

– Я бы тебе помогла, но начальство велело даже в туалет не выходить. Я в зале одна осталась. 

– Ничего, я схожу вниз... А ты пока принеси стаканы. Слушай, а кто звонил?

– Ну, Рыжая.

– Ты уверена? – я подняла бровь.

– Еще б мне не быть уверенной. Здесь только мы и есть. По одной на этаж. А чё такое?

– Да голос, блин, какой-то жуткий. Как с того света, честное слово. Это точно Рыжая? Как-то на нее не похоже.

Но внизу меня действительно ждала Тоня, а в телефоне входящее сообщение от незнакомца.

«Как жизнь молодая?» – спрашивал будущий муж.


