# 33 {-}

Вскоре незнакомец превратился в жениха, и вот теперь «Штиль» – с его крошечными подсобками, барными стойками, пыльными полками, абсурдным задним двориком, морем алкоголя и уставшими сотрудниками – ждал меня где-то там далеко, за несколько сотен километров от солнечного Севастополя. 

Вдохновленная вновь обретенной любовью не только к Вениамину, но и к жизни в целом, я оставалась спокойной. Эту полезную черту я переняла у Вени. Теперь, казалось, ничто не могло омрачить мое существование или хотя бы испортить настроение. Всей душой, всем сердцем, всем своим многострадальным естеством я чувствовала, что все будет хорошо. 

Последний день отпуска подходил к концу, плавно перевоплощаясь в теплый крымский вечер. Несмотря на близящийся отъезд, на душе у меня было так же как и за окном – легко и тихо, чего, увы, нельзя было сказать о Вениамине. На протяжении всего дня он мотался по городу на своей видавшей виды «Таврии». Севастопольский трафик никогда не отличался медлительностью, но сегодня Веня вжимал педаль газа с такой силой, словно с самого утра опаздывал на тот свет. Впервые за долгое время он был молчалив и крайне задумчив. Глядя на эти прищуренные зеленые глаза и широкие светлые брови, намертво сошедшиеся на переносице, можно было бы подумать, что прямо сейчас судьба всего мира решается в голове моего жениха. 

Все это время я сидела около Вениамина. Читала книгу, любовалась пейзажами и еще больше своим спутником – первой и единственной моей сбывшейся мечтой. Стоит ли говорить, я прекрасно понимала, о чем сейчас думает Веня? Даже если бы не было работы, которая приносила ему немалый доход, он не смог бы поехать со мной. В сущности, после того как Крым официально стал частью Российской Федерации, Веня вообще не мог покинуть его пределы. 

Прошлой зимой Вениамину исполнилось двадцать пять. Его украинский паспорт требовал обновления, без которого был недействительным. Само собой, обновить его теперь было негде, кроме как в Украине, куда Вениамину – молодому человеку призывного возраста, добровольно принявшему русское гражданство, – едва ли следовало въезжать. Мы оба понимали, что в лучшем случае его прямиком на границе заберут на фронт. И мы оба этого не хотели. Вместе с тем, русский паспорт Вени, как и все недавно выданные крымчанам паспорта, также был недействительным во всех городах и странах, не считая самой России.

Короче говоря, Веня не мог поехать со мной, даже если бы от этого зависела его жизнь. Однако, моего возлюбленного пугала другая сторона медали. Он вдруг осознал, что не сумеет поехать и за мной в случае ссоры или конфликта. Или моего желания разорвать наши отношения. Как ни крути, но даже при всей глубине любви ко мне, Веня оставался алкоголиком со страхом одиночества. Находясь в трезвом состоянии, он прекрасно понимал, какие минусы влечет за собой подобное пристрастие. И, все-таки, даже не думал от него отказываться.

Наконец, за окнами уже совсем стемнело. Жара спала, и я смогла распустить огромных размеров пучок, в котором весь день покоились мои волосы. Веня припарковал «Таврию» вблизи дома, и вскоре, позабыв об ужине, мы плюхнулись в постель.

По никому не известным причинам, Вениамин терпеть не мог обсуждать чьих бы то ни были бывших. Той ночью он впервые спросил у меня об Адаме. Затем об Эрике и лишь узнав, как долго я оставалась им верной, более-менее успокоился. 

Мы не покидали объятья друг друга до самой полуночи. Теперь до автобуса оставалось меньше девяти часов, и мы вроде как понимали, что неплохо было бы поспать. Тем не менее, ни мне, ни Вениамину не удалось сомкнуть глаз. Под покровом ночи наша комнатка выглядела серой и холодной.

– Ты вернешься ко мне? – спросил Вениамин.

Спросил так грустно, словно я вовсе и не собиралась возвращаться. Мне вспомнилось наше прощание с Адамом. 

<div style="text-align: center;">***</div>

За ночь до поезда мы лежали в постели, крепко держась за руки. В комнате было тихо, как и за ее пределами. Пространство вокруг освещал лишь крохотный светильник. Он отбрасывал на стены причудливые тени и те плавно танцевали под сопровождение завывающего за окном ветра.

– Я хочу, чтобы ты знала, – ласково произнес Адам, и я в который раз умилилась то ли тембру его голоса, то ли произношению, то ли всему и вместе, – я никогда этого не забуду.

– Я тоже, сладкий, – пообещала я. – Как бы ни сложилась наша жизнь в дальнейшем, я этого не забуду.

Мне хотелось добавить: «Ведь я люблю тебя!», но я вовремя сумела сдержать этот лирический порыв. Думаю, он и так об этом знал. 

Адам лежал напротив меня, прижимаясь щекой к подушке. Его большие карие глаза смотрели на меня тем же печальным взглядом, какой позже будет у Вениамина в ночь нашего прощания. 

Возлюбленный молчал так долго, что мне стало не по себе. При этом в сердце поселилась такая тоска, что я не могла и слова вымолвить: боялась, как бы мой голос не дрогнул. Не без усилий, но мне удалось прогнать слезы, что, то и дело, подступали к глазам. Я как раз пыталась подобрать нужные слова, когда Адам вдруг отвернулся. Его могучие плечи беззвучно дернулись, и я с ужасом поняла, что он плачет.

Наступившим утром мы отправились на вокзал. Это был конец октября, самая что ни на есть золотая осень. Последние теплые деньки подходили к концу. Казалось, природа решила вложить в них всю свои красоту – так очаровательны были скверы, улочки и аллеи Москвы тем уютным утром. Что ни говори, природа явно пребывала в гармонии с погодой. Наблюдая эта красоту, я жадно впитывала каждую деталь. Боялась что-нибудь упустить. Сама не знаю, почему. Наверное, я просто не хотела думать о предстоящей разлуке, которая беспощадно приближалась с каждой минутой.

Так длилось до тех пор, пока нога моя не коснулась Киевского вокзала. Поезд уже ждал на перроне. Отправление через двадцать четыре минуты. Напоследок оглянувшись по сторонам, я глубоко вздохнула. Пожалуй, мне было бы легче, увидь я вокруг себя грязные, залитые дождем улицы, сломанные ветви и прочие признаки надвигающегося шторма. 

Это утро было слишком красивым для прощаний.

Адам подхватил мой чемодан. Я взяла его под руку и вскоре мы скрылись в вокзальном павильоне. Чем меньше времени у нас оставалось, тем сложнее мне было сдерживать нахлынувший поток эмоций. С каждым новым шагом я чувствовала, как сердце подскакивает в моей груди. Однако, внешне я оставалось спокойной и даже смогла искренне улыбнуться, когда Адам сказал, что при нашей следующей встрече разница в возрасте уже будет менее заметной. Через месяц мне исполнялось двадцать.

Я знала, что стоит мне позволить себе хотя бы одну слезинку, и я тут же расплачусь. А мне ужасно не хотелось, чтоб Адам запомнил меня такой, слабой и с заплаканными глазами. 

– А ты боялась, что история нашего знакомства будет не романтичной, – заметил Адам. – Ты только посмотри на это, Елизаветушка! Поезд, перрон, последние дни золотой осени…

Он произнес это с привычным весельем в голосе. Если бы не печаль, скрытая в его глазах, я бы могла поверить в то, что Адам и в самом деле не ощущает одолевающей меня грусти. Мои вещи уже давно были уложены на полку поезда. До отправления оставались считанные минуты, и мы оказались последней парочкой, душевно прощающейся на перроне. 

– Как в старых черно-белых фильмах, – заметила я и улыбнулась.

Стоявший на ступенях поезда проводник настойчиво повторил, что отправление через одну минуту. Улыбка у меня получилось грустной. Я поняла это по выражению лица своего любимого, и тут же поспешила добавить:

– А теперь поцелуй меня. Как персонаж чертового черно-белого фильма.

Было это три года назад. С того дня я больше никогда не видела Адама, но подвернись мне шанс что-нибудь изменить, я бы едва ли смогла придумать для нас более подходящее прощание.


