# &nbsp; {#chapter-34}

– Ты вернешься ко мне? – спрашивал Вениамин.

Он лежал напротив, подложив локоть под голову. Несмотря на поздний час, на улице по-прежнему было жарко. Дверь на балкон оставалась распахнутой, и ночной ветерок то и дело играл с прозрачной занавесью. Сквозь нее в комнату проникал лунный свет, освещая постель. 

Я поспешно перевела взгляд на окно, стараясь избавиться от навязчивых воспоминаний давно ушедших лет. Да и какой смысл был в том, чтобы их хранить? В конце концов, теперь они не навевали ничего кроме тоски. Зачастую проблема воспоминаний как раз и состоит в том, что это счастливые моменты, о которых говорят исключительно в прошедшем времени. Чьи это слова? Я напрягла свое сонное сознание, пытаясь вспомнить какого-то забытого автора, когда вдруг поняла, чьи эти слова – мои. Я написала их несколько зим назад и только сейчас, кажется, в действительности осознала смысл написанного.

Повернувшись к жениху, я увидела, что тот все так же смотрит на меня в ожидании ответа. Взяла его за руку, и изумилась тому, какой горячей она была.

– Вернусь, – пообещала я, стараясь вложить в свой голос максимальную порцию спокойствия.

На самом же деле, к концу дня молчаливая меланхолия Вениамина распространилась и на меня. Подкрепленная усталостью, горьким опытом и алкоголем, она достигла немалых размеров. Внутри меня все горело, и только  вновь обретенная любовь и обещание сохранять внутреннюю гармонию в любой непонятной ситуации, что я однажды дала себе, удерживали меня от слез. Стоило мне вспомнить об исходе предыдущих романов, о прощаниях, что, казалось бы, сулили новые встречи, о любви, – сильнейшем и упрямейшем из всех чувств, на которое было способно мое агоническое сердце – восторге и сладостных переживаниях, которые приводили к бесконечному списку надежд. Надежд на моральный покой, взаимопонимание и обретение долгих счастливых лет совместной жизни. Ничему из этого не было суждено сбыться, и я знала, что стоит допустить хоть одну печальную мысль, стоит хоть разочек себя пожалеть, и мои глаза тут же наполнятся слезами. А я не могла позволить себе расплакаться. Теперь вовсе не потому, что переживала о том, какой запомнит меня Веня в случае, если мы больше не увидимся.

Мне нельзя было плакать просто потому, что я понимала: стоит только начать, и я уже не смогу остановиться. На этот раз по-настоящему.

Боялась ли я вновь остаться с разбитым сердцем? Боялась ли я опять не распознать обман и двуличие, которые всегда были коньком моих любимых? Боялась ли я снова довериться не тому человеку? Чертовски, блядь, боялась! Но я уже впустила Вениамина в свое сердце, так что у меня попросту не было выбора. И пускай отношения у меня всю жизнь не клеились, в любви я кое-что понимала. 

Хотя, наверное, и в любви я как раз таки и понимала просто потому, что слишком часто бывала из-за нее несчастной. Наблюдая за окружающими меня людьми, я как-то вдруг поняла, что тот, кто всегда был счастлив, не прикладывая усилий, едва ли может противостоять серьезным проблемам. Несчастья – это, конечно, плохо, но они нужны взрослому человеку так же, как ребенку нужна школа. Никто не хочет подвергаться хулиганству и оскорблениям, но только с их помощью можно научиться давать отпор.

*И понять как не нужно делать*, подумала я, вспоминая Марту.

<div style="text-align: center;">***</div>

Мне шел двадцать первый год, когда Марта вернулась со Львова и самоотверженно заявила, что влюбилась. Подруга была старше меня всего на год, но никогда прежде не состояла ни в серьезных, ни в несерьезных отношениях. Дело здесь было вовсе не в том, что с Мартой было что-то не так. Отнюдь. Она была высокой, стройной и хорошо образованной. Просо всю свою жизнь эта девушка посвящала учебе, карьере, поездкам, покупкам и саморазвитию. На любовь у нее просто не оставалось времени. За полтора года до того, как она встретила Семена, пытаясь поймать такси, мы сидели в «Перекрестке» – тусклом, плохо отапливаемом баре, который так прекрасно вписывался в общий вид Николаева.

К тому моменту прошло меньше трех месяцев после нашего с Адамом прощания. Февраль, четырнадцатое число – мой наиненавистнейший из всех ненавистных дней в году. Само собой, город заполняли влюбленные парочки. Они были на скамейках, в магазинах, на дорогах и, конечно же, в заведениях. Взявшись за руки, сотни тысяч людей гуляли под непрекращающимся вторую неделю снегом.

И без того грустная, теперь я принялась с ума сходить от одиночества. Хотела запереться дома, но и здесь, в четырех стенах, мне все напоминало о бывшем. Тогда, наспех одевшись, я вылетела на улицу. На мне было лишь легкое пальто, наброшенное поверх домашней одежды – привычный прикид для затянувшейся депрессии. Никакой снегопад не мог помешать мне появиться в таком виде на людях. Не зная, куда еще податься, я спряталась в этом унылом, забытом богом и николаевцами баре. 

Спустя несколько стопок текилы ко мне присоединилась Марта. Она заметила, что нынче вид у меня был еще более отстраненный, чем обычно, спросила, в чем дело, и тогда я впервые рассказала ей о своих чувствах к Адаму. Выложила все подчистую.

– Я думала, тебе на него уже давно наплевать! – изумилась подруга.

Все так думали, хотя не прошло и трех месяцев. Я носила макияж и каблуки, от которых потом болели суставы, старательно укладывала волосы, что к тому моменту покраснели, регулярно бывала в оживленных местах и веселила всякого встречного. Что же касается тех дней, когда я просто не могла скрывать свою боль… Что ж, в такие моменты я забивалась в самый дальний угол. Пары пальцев хватило бы на то, чтобы сосчитать людей, знавших о моих душевных терзаниях.

Словом, нельзя было винить общество за то, что оно не было в курсе моих переживаний.

– Я завидую тебе! – призналась Марта. – Завидую твоим романам, твоему разбитому сердцу, твоим чувствам и печалям. Завидую тому, что ты пишешь книги и тому, что у тебя не бывает денег. Тебе, как ты говоришь, не трудно и в бомжах ходить, если это дает время на книги. А я берегу каждую копейку. Ты знаешь, каково это – любить. А я вот не знаю ничего. Я возвращаюсь домой и захожу на сайт «Розетки», чтобы выбрать какую-то технику. Хоть что-нибудь купить и порадовать себя этим. Это всегда работало, но вот вчера я получила зарплату, и внезапно поняла, так ведь у меня уже все есть! У меня есть телефоны, ноутбуки, планшеты, колонки и еще куча всякой всячины. Я была во всех странах, которые хотела посетить. И я поеду куда-нибудь еще раз, если мне захочется. А мне вот не хочется. Я знаю так много всего, но я понятия не имею, что такое любовь. И от этого у меня чувство, что я не знаю ничего. Так я ведь даже никогда и не влюблялась толком. Никто никогда мне не нравился и я без понятия, что такое страсть.

Она глубоко вздохнула и повторила:

– Как же я тебе завидую, Лиза! Ох, как бы мне хотелось хоть раз узнать, что такое разбитое сердце.

Я исподлобья взглянула на Марту, смутно представляя, каким должен быть мой ответ. Я была грустным, психически неуравновешенным писателем, у которого не было ни денег, ни литературного признания. В те дни все, что у меня было, сводилось к вышеупомянутому разбитому сердцу и стопке никому не нужных рукописей. Каждое мое утро начиналось с поисков мелочи, в надежде, что ее хватит на самую дешевую пачку сигарет. Но Марта не лицемерила. Я знала, что слова ее были искренними. Это-то меня и пугало.




