# 36 {-}

– Ты ведь вернешься? – вновь спрашивал Веня последней ночью моего отпуска.

Спрашивал так, словно у меня был выбор. Словно я вовсе не отдала ему своё сердце несколько недель назад. 

Конечно, я вернусь. Разве я могу поступить иначе? И я повторила свой ответ. 

Услышав мое обещание во второй раз, Вениамин, казалось, наконец ему поверил. Я уже начала проваливаться в сон, когда заметила, что мой мужчина плачет. Он не отворачивался и не пытался прикрыть глаза рукой. Веня просто безмолвно плакал, сжимая мою руку с такой силой, что вскоре я и вовсе перестала ее чувствовать. 

Лежа рядом, я совершенно не знала что сказать, кроме слов любви, которая и без того была очевидной. Смотрела на то, как слезы текут по бородатым щекам этого крепкого мужчины. Было что-то трогательное в его приступе сентиментальности. Слишком трогательное для того, чтобы позволить себе не воспринимать эти чувства всерьез.

Следующим утром я никуда не уехала.

<div style="text-align: center;">***</div>

Прошло еще немало времени, прежде чем нам удалось уснуть. Казалось, даже во сне я продолжала чувствовать пальцы Вениамина, крепко сжимающие мою руку. 

– Прости, что испортил нашу последнюю ночь, – краснея, произнес Веня следующим утром.

Я лишь отмахнулась. Безусловно, с отъездом вышла накладка (теперь у меня не останется времени на сон и буквально придется прыгать за барную стойку прямиком из автобуса), но разве это можно назвать проблемой, учитывая спокойствие, которое, наконец, поселилось в наших сердцах? Прошлой ночью все страхи и опасения вырвались наружу. Теперь мы оба понимали, что прощаться будет гораздо проще.

Автобус по-прежнему уходил в девять утра. На этот раз мы даже купили билет, потому как прекрасно знали, что мне нельзя его упустить. Впереди нас ждал еще один прощальный вечер. Долго не думая, мы решили провести его в «Среде Обитания» – ламповом баре, что по счастливой случайности находился в двух шагах от дома. Усевшись за столик, мы болтали обо всем на свете: о литературе, автомобилях и о том, как правильно готовить шоты, чтобы алкоголь лег красочными слоями, а не превратился в одно бесцветное месиво. Короче говоря, мы говорили о чем угодно, только не о грядущем прощании.

Под конец вечера Вениамин куда-то исчез. Он отсутствовал минут двадцать, а затем появился в дверном проеме, держа в руках охапку крымских роз. Последние были явно похищены из чьего-то огорода. Об этом свидетельствовали не только грубо обрезанные ветви, но и лицо моего жениха, побагровевшее от бега. Один цветок Веня заправил за ленту своей шляпы, а остальные деловито преподнес мне. К тому моменту он был уже чертовски пьян, но когда это мешало нам весело проводить время?

<div style="text-align: center;">***</div>

Я любила абсент. Меньше чем вино, но больше, чем водку. Хотя я, наверное, что угодно любила больше, чем водку, за исключением бабочек, жары и точных наук. Вениамин же совершенно не понимал абсентной эстетики, но очень любил крохотные коктейли, сделанные на основе этого напитка. Ими-то он и надрался в мой последний вечер в Севастополе. В то время как я мирно попивала винишко, жених прикончил одиннадцать шотов, а затем еще вернулся в бар, чтобы выпить двенадцатый.

Мы возвращались домой пустынными улочками. В домах по обе стороны от дороги свет был погашен. Жившие в них люди уже видели десятый сон. Единственным источником света оказались разбросанные по улицам фонари. Их мягкое свечение, отсутствие других пешеходов и повисшая в воздухе тишина практически летней ночи придавали пространству вокруг схожесть с киношным павильоном. 

Тем временем Вениамин продолжал заниматься самым романтичным видом городского вандализма. Он без стыда срывал каждый цветок, которому не посчастливилось встретиться на нашем пути.

Наконец мы вернулись домой. По-настоящему последний день отпуска официально подошел к концу. Небо все еще оставалось звездным, но где-то вдалеке, за морем, уже проступали алые полосы. Докуривая сигарету, я вдруг поняла, что близится наш первый совместный рассвет. Вслед за этой мыслью Вениамин, какое-то время сидевший в полной тишине, принялся старательно изучать содержимое своих карманов. Он вытащил пять складных ножей, и теперь внимательно рассматривал их лезвия.

– Этот! – сказал Веня, в конце концов определившись.

Он протянул мне стальной нож с самым что ни на есть спокойным видом. По присущей всем уставшим людям привычке, я сначала взяла протянутый предмет, а уж потом спросила, зачем тот, собственно, мне нужен.

Под влиянием обильного количества алкоголя оттенок глаз моего жениха переменился. Зачастую это был уже привычный мне лазурный или холодный зеленый. Реже – ярко-голубой. Сейчас же Вениамин смотрел на меня широко распахнутыми глазами, которые едва ли можно было назвать изумрудными. Они вдруг приобрели темный болотный оттенок. Все это на пару с усталостью и выпивкой, делало Венькин взгляд крайне мутным. 

Слабо сжимая в руке нож и начиная догадываться о том, зачем мне его вручили, я не отрывала взгляда от лица Вениамина. Было в нем что-то чужое, скрытые черты или привычки, о которых я не знала. Эти перемены нельзя было увидеть невооруженным глазом, настолько они были незначительными. К примеру, речь стала быстрее, тембр голоса был чуточку выше обычного, а сменившие оттенок глаза то и дело оказывались неестественно распахнутыми. Безусловно, взятые отдельно друг от друга, такие вещи наверняка остались бы без внимания. 

Но я слишком хорошо знала Вениамина и отчетливо понимала, что в совокупности такие детали имеют смысл. Они настойчиво вызвали в моей душе неприятное чувство. Ощущение ноющей тревоги. Не имея видимых мотивов, это опасение периодически увеличивалось в размерах. В какой-то момент мне даже стало трудно дышать. Это показалось мне таким глупым, ведь я даже не знала, чего боюсь. Тогда я постаралась разобраться, что конкретно меня волнует. Однако все внутренние тревоги казались довольно абстрактными. Они сводились к единственной мысли, что то и дело раздавалась в разных уголках моего сознания.

*Что-то пошло не так*, гласила мысль. 

*Что-то плохое происходит прямо сейчас, и это что-то от тебя умело скрывают.*

Как ни старалась я утихомирить свой внутренний голос, эти фразы настойчиво повторялись. И дело было вовсе не в ноже, о котором я уже и думать забыла. Дело было в самом Вениамине, его взгляде и… в чем-то еще. 

*Бредовое расстройство*, отрешенно подумала я. *У меня бредовое расстройство.*

ЧТО-ТО ПЛОХОЕ ПРОИСХОДИТ ПРЯМО СЕЙЧАС, И ЭТО ЧТО-ТО ОТ ТЕБЯ УМЕЛО СКРЫВАЮТ!

Предложение это звенело внутри меня с назойливостью августовских мух, доживающих последние дни лета. Длилось это до тех пор, пока мысль не стала предельно громкой. Такой громкой, что от нее разболелась голова. Тогда я в последний раз услышала прогудевшие в моей голове слова, а затем все смолкло. С приходом тишины исчезла и тревога. Совсем непонятный мне страх тоже куда-то испарился, так и не раскрыв своих мотивов.  

Сразу после этого я почувствовала прилив угрызений совести. 

