# 37 {-}

Конечно, у маниакально-депрессивного психоза имеется довольно богатый список симптомов. Практически каждый из них я многократно ощущала на собственной шкуре, в том числе и навязчивые идеи, не имеющие особого основания, и удручающие, депрессивные мысли, которые мгновенно пускали корни, старательно отравляя мне жизнь. И первые и последние были поразительно правдоподобными, отчего у меня почти никогда не возникало сомнений на этот счет. Из-за этого я частенько ловила себя на том, что больше не хочу жить. Мысли о смерти и явное отсутствие будущих перспектив сводили меня с ума. 

Поначалу я еще как-то могла с ними бороться, но спустя проведя большую часть жизни с биполяркой, о наличии которой я не знала, мое внутренне состояние явно ухудшилось. Череда повторяющихся неудач, обид и потерь привела к нервному срыву, а болезнь его только усугубила. Затем я страдала не только по достойным внимания причинам. Сущие пустяки и мелочи, на которые здоровая версия меня плюнула бы без лишних раздумий, ранили меня ничуть не меньше. Как и все упрямые люди, я продолжала бороться, но чем больше усилий я прикладывала, тем хуже становилась моя жизнь. 

В конечном счете, я очень злилась, после чего впадала в долгое отчаянье, которое сменялось лютой печалью, чтобы однажды перерасти в самую настоящую истерику. Все, что шло после гнева, так или иначе вызывало во мне мысли о самоубийстве. Как-то я поняла, что единственный способ остановить этот поток заключался в нанесении себе телесных повреждений. Я уже об этом говорила. Резкая физическая боль была единственным фактором, способным отвлечь меня в такие минуты. И я это знала. 

Поэтому на пике очередного приступа, я кое-как умудрялась отыскать в себе последние признаки просветления, и хватала в руки лезвия, ножи, молотки и любые другие вспомогательные предметы. Чаще всего, я делала это машинально и приходила в себя уже после того, как чувствовала первые порезы. Иногда под рукой не оказывалось нужных предметов. В таких случаях, приходилось импровизировать. Помнится, однажды я стояла у края крыши многоэтажного дома, готовая к тому, чтобы сделать последний шаг. Валил сильный снег, а на мне не было ни пальто, ни даже свитера. Режущих или хоть сколько-нибудь травмирующих предметов при мне также не наблюдалось. В итоге пришлось заставить себя хорошенько разогнаться и вписаться головой в бетонную стену трансформаторной будки. Было больно, но я прекрасно понимала: либо это, либо асфальт.

Общество никогда не было в состоянии понять мотивов моих поступков. Окружающие и представления не имели о природе этих проблем. Появление новых увечий, как и вид старых шрамов, вызывало на их лицах выражение неподдельного шока. 

– Ты же такая веселая, – говорили они. 

Словом, люди всегда открыто глазели на меня, желая лучше рассмотреть последствия селфхарма, но никогда не осмеливались спросить о них. Очевидно, задавать подобные вопросы сегодня столь же неприлично как интересоваться количеством половых партнеров. Так что, люди просто пялились, а в разговорах показательно старались не смотреть на место пореза, делая вид, что и вовсе его не заметили. 

Никто из окружающих меня людей и понятия не имел о том, что мне приходится причинять себе вред под влиянием инстинкта самосохранения, как бы странно это не звучало. Ведь как бы бодро я не выглядела, большую часть времени мне приходилось бороться с настойчивым желанием наложить на себя руки. Они не могли понять эту простую истину просто потому, что были психически здоровы. А еще потому, что в принципе не были способны думать шире собственных представлений о жизни.

Всем хотелось знать, почему я пыталась свести счеты с жизнью. Кто-то говорил о любви, долгах и наркотиках, тогда как правда была куда более банальной и очевидной. По крайней мере, для меня. Я намеревалась убить себя просто потому, что видела в смерти единственный способ избавиться от одолевавшей меня боли. Она росла с каждым днем, разрывая сердце на куски, и вскоре я уже была готова отдать что угодно, только бы больше это не чувствовать. В том числе, и свою жизнь. Наступил день, когда я уже и сама толком не могла сказать, почему так страстно желаю собственной смерти. Само это желание обратилось каким-то важным пунктом в моем списке дел, и внутренний таймер то и дело присылал напоминания.

Тем не менее, я вновь и вновь была вынуждена вступать в битву с самой навязчивой из своих идей. Должно быть, проблема заключалась в том, что на самом деле я никогда не выходила из этого боя победителем. Я лишь брала тайм-аут и тянула время в надежде, что когда-нибудь смогу найти выход из положения. 

В общем, к тому моменту я многое успела повидать и во многом травмироваться,  но – если не считать ночных вылазок, которые я пару раз совершала, переборщив с марихуаной – я никогда прежде не имела дела с паранойей. Паранойя – именно так я и подумала о тревожных мыслях, что одолели меня последней перед отъездом ночью. Подобно всем людям, обнаружившим, что у них проблемы с головой, и прикладывающим море усилий для их лечения, я тут же усомнилась в адекватности своего восприятия. Что же касается Вениамина, в остальном он был все тем же. Веня обращался ко мне привычными уху теплыми словами, произнесенными хорошо знакомым тоном. Он улыбался мне, целовал и признавался в любви снова и снова, оставляя на моих губах такой же привычный вкус недавно выпитого спиртного. И, как это всегда бывает с параноиками или влюбленными, вскоре я напрочь забыла о так внезапно нахлынувших на меня опасениях.

