# 40 {-}

Теперь мы уже бежали вместе: Вита – все на тех же несчастных шпильках – и я со стаканом кофе в руках, который, к тому же, зачем-то старалась не расплескать.

– Там моя сумочка! – кричала Вера. – В ней все документы! И деньги. И мамины сережки! И мобилка!

*И электронная книга*, подумала я, но ничего не ответила.

Сложно говорить, когда ты, истерически смеясь умираешь от боли в боку, но продолжаешь бежать под проливным дождем.

Мы срезали напрямик через вокзал и практически догнали автобус. Асфальт под ногами сменился слякотью обочины и мне уже были видны лица сидящих в салоне людей. Это были тучные женщины далеко за сорок с мордами-лопатами, которые просто смотрели за тем, как мы бежим за автобусом и размахиваем руками. За ними сидел одинокий дед. Он оказался куда более приветливым. Дед просто улыбался и махал нам в ответ. Следом шло целое семейство с синдромом Дауна и к ним у меня, в общем-то, нет никаких претензий.

Я наблюдала всех этих людей последние часов десять. Мы вместе ехали в первом автобусе, стояли в очередях и все такое прочее. Кто-то их этих людей даже спрашивал у меня ручку. Но сейчас никто и не думал предложить водителю остановиться. Они просто сидели. 

И смотрели.

Возможно, даже делали ставки на то, как скоро кто-нибудь из нас поскользнется в грязи. Где-то там, на выезде из автовокзала, между попытками не задохнуться, я попыталась их возненавидеть. Но вышло так себе. 

Почему?

А теперь просто представьте открывающуюся этим людям картину: грязь, какой-то вечный ливень и мы – фанатки группы Кисс с пугающими начесами и соответствующим макияжем – настойчиво преследуем общественный транспорт. Так, должно быть, выглядели группи, бежавшие за гастрольным автобусом вышеупомянутой группы.

Будь я старухой с мордой-лопатой, пожалуй, я бы тоже постаралась убедить себя в том, что увиденного не существует. Быть может, что мы с Витой до сих пор им снимся.

<div style="text-align: center;">***</div>

Мы бежали вдоль обочины, несмотря на то, что автобус стремительно продолжал отдаляться. К тому моменту осваивать йогу я начинала только в мыслях, и моя физическая подготовка по-прежнему оставляла желать лучшего. Левый бок исходил конвульсиями, а легкие пылали так сильно, что, казалось, я вот-вот задохнусь. Наконец, тот факт, что за автобусом нам не угнаться, стал более чем очевиден. 

Именно в этот момент из-за поворота появилось такси. В салоне уже сидели пассажиры.

– Тормози, – простонала я Вите.

Хотя, на самом деле, вышло что-то куда менее членораздельное. Вита меня не поняла, а времени на объяснения совсем не оставалось. Машина уже была метрах в пяти от нас. Пришлось импровизировать. Я сделала лучшее из того, что только могло придти в мою затуманенную, промерзшую до нитки, уставшую голову – выскочила на встречную полосу. Таксист остановился в каком-то полуметре от меня, и спустя мгновенье мы уже сидели в салоне авто вместе с недоумевающими пассажирами.

– Вам… куда…? – не столько спросил, сколько плавно произнес ошарашенный таксист.

Тут у женщины-пассажира вдруг прорезался голос.

– Шо значит куда? – завизжала она. – Вы совсем пооболдевали так на дорогу прыгать? У меня тут все яйца покоцаются!

– Ну, так не покоцались же, – ответила я.

Женщина деловито исчезла в немыслимых размерах клетчатой сумке. Не той, которая от Louis Vuitton, разумеется. А в той, которая годов с восьмидесятых, если не раньше, является неотъемлемым атрибутом похода на рынок каждой уважающей себя совдеповки. В общем, дамочка пропала где-то в недрах сумки, но вскоре вновь явила себя миру.  

– И правда, не покоцались… – задумчиво произнесла она.

Люблю подкидывать людям поводы для раздумий.

Водитель откашлялся.

– Так это… Вам куда? – успевший оправиться от шока, он принялся нас разглядывать. – Девочки, с вами все окей? 

На Виту было больно смотреть. Выглядела она так, словно все это время бежала по полям и огородам от самой границы. Да и я, пожалуй, воодушевляла взгляды не многим больше. 

Водитель напустил серьезность и понизил голос.

– За вами там часом никто не гонится?

– Нет, – говорю я. – Это мы гонимся. За автобусом.

<div style="text-align: center;">***</div>

Наверное, в этот момент я должна была почувствовать себя одним из братьев МакКормиков, внезапно для самого себя догнавшим автобус Боно. Каких-то секунд пять водитель еще не решался открыть дверь. Он остановил автобус у обочины и теперь просто смотрел на то, как я выхожу из такси со стаканом кофе, который, кстати, я так и не пролила. Вита – с разбитой коленкой, в испачканном платье и с отсутствующим каблуком – хромала рядом. Мы подошли к автобусу и теперь тупо смотрели на водителя, который, в свою очередь, продолжал смотреть на нас.

Дождь вроде как все еще лил, но теперь это и впрямь казалось комичным.

Что было сил, моя спутница ударила кулаком по стеклянной двери автобуса, оставив на ней отпечаток перепачканных пальцев. Тут водитель опомнился и дверца отъехала. Вита мигом накинулась на виновника нашей незапланированной пробежки.

– Ты че, мразь, вообще охуел? – поинтересовалась она поразительно жутким для такой милой женщины голосом. – Ты вообще, блядь, мозгами тронулся, дядя? Двадцать минут. ТЫ ЖЕ СКАЗАЛ ДВАДЦАТЬ МИНУТ! ТАК КАКОГО…

И так далее, и тому подобное.

Я стояла у входа в автобус, Вита – на ступеньках. Она все кричала и кричала, пытаясь добиться вменяемого ответа от невменяемого водителя. 

Я попробовала кофе. Совсем холодный.

– Да зачем ты его все это время носишь? – раздраженно спросила спутница.

Она, наконец, поняла, что разговор с водителем бесполезен, и теперь продолжила подниматься по ступеням. Я последовала за Витой, и остановилась около водительского кресла.

– Да вот за этим, – ответила я, и плеснула кофе в лицо водителю.

Он все равно остыл.

<div style="text-align: center;">***</div>

Знаю-знаю, здесь я как бы должна извиниться и признать, что никакой кофе я ни на кого не выплескивала. Однако, именно так все и было. Сложно сказать, в какой момент своей жизни из шаблонного холерика я превратилась в настоящего меланхолика, который, к тому же, периодически проявляет признаки агрессии в самый неожиданный момент, но это и не важно. Пускай во мне жило несколько личностей, настоящая Лиза была лишь одна, и та вообще являлась сангвиником. Вот только по жизни ее поджидали увлекательнейшие метаморфозы. Когда мне было пятнадцать… 

Черт, как же много моих историй начинается именно с этой фразы.

Так вот, когда мне было пятнадцать, я безответно влюбилась в парня по имени Эрик. Он был высоким, задумчивым и таинственным. И он стал первым, кому по-настоящему удалось украсть мое сердечко и прочие составляющие супового набора. Вы, конечно, помните Эрика. Как помните и мои последующие еще такие детские страдания.

Мне было семнадцать, когда я впервые осознала, что что-то изменилась. В душе я по-прежнему воспринимала себя как вспыльчивую и очень характерную особу, но толком об этом не задумывалась. Две тысячи одиннадцатый год выдался слишком философским, чтобы тратить его на самоанализ. 

Однажды, где-то в самый разгар октября, я пила кофе во дворике университета, когда ко мне подошла Нина, моя бывшая одноклассница и будущая супермодель. Было это в начале второго курса, факультета английской филологии с правом преподавания. 

– Что с тобой произошло? – спросила Нина.

Вот так вот просто. Без приветствий и прочих социально приемлемых заигрываний в начале диалога. Я всегда ценила подобного рода минимализм, так что просто сказала:

– Жизнь.

А она ответила:

– Да ну.

И я заметила:

– Ну да.

Так мы и стояли еще минуты три, пока я не достала из кармана пачку сигарет. В те дни я курила красный «Лакки» – сигареты, которые ассоциировались у меня с Эриком. Грустила, кашляла, но продолжала курить.

Нина убедилась в том, что поблизости нет никого из знакомых, и только потом подкурила. Меня всегда поражали такие люди, о чем я тут же и сообщила однокласснице. Ведь если у тебя нет смелости заявить о том, что ты куришь, то как же быть с более серьезными вещами? Неужели одобрение общества до сих пор в тренде? Разве жизнь, прожитая в притворстве, имеет какой-то смысл?

Это было еще до того, как мне стало плевать на все на свете. 

До того, как я встретила Адама.

До того, как я вновь встретила Эрика.

До того, как я встретила Веню.

– Может, и нет, – ответила Нина. – Но моя репутация должна быть безупречной.

Кажется, я как раз собиралась поинтересоваться, на кой черт кому-то в двадцать первом веке может понадобиться репутация, но Нина меня опередила. Она перевела тему.

– Женщина, ты мне лучше скажи, что такое с тобой стряслось?

Я не очень поняла, о чем она, так что вопросительно подняла бровь.

– Ну, знаешь. Когда я впервые увидела тебя на лекции, я думала это кто-то другой. А потом ты что-то сказала преподу, и я слышу, голос ведь твой. Ну, тут я поворачиваюсь к Василисе… Ты же помнишь Василису? Из параллельного класса. Поворачиваюсь и говорю: гляди, там Лиза Васляева в третьем ряду сидит и ведет себя совершенно спокойно. А она мне отвечает: да быть такого не может!

Стоит ли говорить о том, какое прекрасное мнение на окружающих произвела я в школьные годы? Пожалуй, что нет.

– Мы с ней даже немножко поругались, – продолжала Нина.

Затем она назвала меня молчаливой, задумчивой и таинственной и вновь поинтересовалась, что со мной произошло. А произошел со мной Эрик, которого я когда-то тоже считала молчаливым, задумчивым и таинственным.

Так я узнала, что официально покинула ряды местных сумасшедших.

Теперь я была среди грустненьких.

Надолго ли?

<div style="text-align: center;">***</div>

Вернемся же к водителю злополучного, если не сказать хуже, автобуса. И к тому факту, что ему еще понадобилось какое-то время, чтобы вернуться за руль. Пройдя вглубь салона, я увидела, что наши места оккупировало семейство каких-то азиатов с тремя детишками. Они либо умело делали вид, либо действительно ничегошеньки не понимали по-русски, то ли оказались по-славянски наглыми. Короче, вставать ребята не хотели. Я просто вытащила из-под одного из них свой чемодан и со словами «сесе нинь дэ гуанчжоу!» села прямиком в проходе салона.

Младшая из детей взглянула на меня как на дуру.

– Это на китайском, – объяснила девочка. – А мы японцы.

Так и знала, что они меня поняли!

– А как сказать по-японски «это мое место, засранцы»?

– Кацира га вата…

На этом мать семейства шлепнула дочку по лбу и больше со мной никто не говорил.

*Ну и хрен с ним*, подумала я. *Можно и на полу посидеть*

В конце концов, до Николаева оставался всего час езды.

Я вытянула перед собой ноги, загородив добрую часть прохода, и вскоре уснула.



