# 41 {-}

Возвращаться в свой родной – этот откровенно уездный – город было и грустно и весело. Весело потому, что мне хотелось выпрыгнуть из автобуса и бросаться на шею каждого встречного, рассказывая ему или ей о Вениамине. О том безграничном счастье, что я ощущала и о той любви, что нежданно-негаданно вспыхнула в моем сердце.

Когда слишком долго находишься в депрессии, она становится полноценной частью тебя. Ты и депрессия, вы теперь – одно целое, так что, почувствовал улучшение, я сразу ощутила некий дискомфорт, вызванный столь неожиданной ментальной стабильностью. Как будто кто-то пытался вытолкнуть меня из мрачного, но такого привычного и безопасного пристанища.

Пришло время показаться на работе. Я шла по залитым теплом, уже практически летним улицам своего родного города. Пение птиц больше не раздражало мой слух, солнечный свет не ослеплял, а наоборот приятно согревал кожу. Он скользил по стенам и играл в листве, создавая причудливые тени. 

И все вокруг мне казалось прекрасным.

Даже перевернутые по старой доброй традиции мусорники, вроде бы, не так отравляли воздух. Тут-то я и напряглась. Прежде со мной такое бывало лишь при умопомрачительной влюбленности. А влюблялась я, как вы уже поняли, раз в пятилетку. 

И все это время я всерьез полагала, что по-настоящему счастливым можно быть лишь по уши погрязнув в любви. Искренне поражалась людям, которые не состоят в отношениях, но при этом регулярно следят за собой, развлекаются и куда-то ходят. В общем, выглядят так, словно они счастливы самим себе. Я смотрела на них с изумлением, а на деле все страдала, страдала и страдала. В основном от одиночества и неразделенных писательских амбиций.

Так вот, мне понадобилось угробить лучшие годы своей жизни, (или, по крайней мере, те, о которых принято говорить, что они лучшие) чтобы осознать собственную неправоту. И еще какое-то время на то, чтобы с ней смириться. Но когда это, наконец, свершилось, я вдруг оказалась безгранично влюбленной. Незапланированно влюбленной. 

Затем почувствовала себя не в своей тарелке. Быть выспавшейся, веселой и жизнерадостной казалось мне очень странным. Я и прежде бывала гиперактивной, но это была нездоровая радость. Ввиду моего диагноза, не более того. А теперь я и впрямь чувствовала, что я в порядке. Это началось еще тогда в «Штиле», до знакомства с Веней, но, почему-то не прекращалось и по сей день. И это было жутко. Как будто кто-то просто забрал все, что у меня было, и подсунул взамен жизнь какой-то другой, менее проблемной девушки.

А была у меня, очевидно, только депрессия.


