# 42 {-}

Как выяснилось, решение выйти замуж далось мне куда легче, чем перспектива объяснить это самое решение другим людям. Меня поддержали лишь Марта, встречи с которой я ждала со дня на день, да Лина. Но первая все так же не знала негативного жизненного опыта, а вторая… Думаю, она сделала это только потому, что слишком меня любила.

– Ты мне смотри, – сказала она. – Если он что тебе сделает, я приеду в Крым и оторву его бородку к чертовой матери. Отак ему и передай.

В прошлом Лина была чемпионом по борьбе. В нынешнем – лесбиянкой и моей хорошей подругой. Я знала, что в случае чего именно так она и поступит.

– Ты его вообще сколько дней знаешь? – спросил мой брат и закатил глаза.

На самом деле Олег был моим кузеном. К тому же не по крови: дядя усыновил его в раннем детстве. И все-таки он был моим братом. Самым близким и любимым из всех моих многочисленных кузенов. 

Прошел почти год, прежде чем мы вновь заговорили друг с другом.

Мишель – самая близкая и самая давняя из моих подруг – сделала вид, что рада за меня. А я, в свою очередь, сделала вид, что верю ей. Наша дружба дала трещину еще в пятнадцатом, но в двадцать лет я набила татуировку с ее именем, и пока еще не успела придумать, как мне быть дальше.

Короче говоря, чем больше людей узнавало о моей радости и чем больше реакций я видела, тем сильней сужался круг гостей, которых я бы хотела видеть на своей свадьбе. А вместе с тем и круг моего общения. Никто из моих многочисленных друзей, приятелей, коллег и знакомых не был рад тому, что я в кои-то веки счастлива. Тогда я и вспомнила то, что успела забыть за годы одиночества: почему я с самого детства терпеть не могла людей – в них нет эмпатии, только тонны эгоизма.

Было неприятно, но все же терпимо.

<div style="text-align: center;">***</div>

В начале того лета мы сидели с Линой в закрывшемся баре. Дело шло к половине четвертого утра. Я как раз закончила перемывать инвентарь и теперь была рада оказаться по другую сторону стойки. Мы пили «Ксенту Супириор». Сил на то, чтобы брать чашу для абсента, вновь доставать стаканы, искать специальную ложку, класть на нее кубик сахара, а затем еще что-то там прокапывать, у меня не наблюдалось. 

У Лины же явно не было желания ждать, пока я проделаю весь этот скрупулезный ритуал, а потом напрягу ее мыть посуду. Так что мы просто сидели в темном зале и пили этот дорогущий алкоголь абсолютно варварским способом – прямиком из горла. Зато именно так в нем чувствовались все обещанные на этикетке семьдесят оборотов и даже больше.

Я отхлебнула обжигающий напиток и протянула «Ксенту» Лине. Та ее не взяла. Она смотрела не на абсент, а на мою руку, державшую бутылку. В баре было жарко, так что рубашки на мне не было. Только майка.

– Что у тебя с рукой? – спросила Лина.

– Ничего, – ответила я.

– Не-е-ет, - протянула подруга и, наконец, взяла из моих рук бутылку. – У тебя стопудово что-то не так с рукой.

– Кажись, за тобой прилетели феи.

Подруга продолжила настаивать на своем. Она настойчиво тыкала в сторону моей правицы. 

– А это, – до меня, наконец, дошло. – Это все Тарзан виноват.

Затем мы выпили (поочередно, как и полагается бухарикам, не признающим посуду), и я рассказала ей, может, и не лучшую, но первую из своих бесконечных историй.

<div style="text-align: center;">***</div>

Незадолго после того, как мне исполнилось четыре года, я сломала руку. Просто посмотрела «Тарзана» по черно-белому ящику и вылезла на шкаф, прихватив с собой пояс от какого-то халата.

Со мной в тот день сидела няня. Не такая, каких обычно показывают в кино. Это была хмурая, тучная женщина, которая должна была гулять со мной, заниматься чтением и чем-то там ещё, а на деле просто закрывала меня в зале со включенным на целый день телевизором и уходила в соседнюю комнату заниматься своими делами. Звали ее Света.

Мы пробыли вместе не так уж долго. От силы пару месяцев, которые родители пахали без выходных, но за это время я успела выучить наизусть все рекламные ролики, что крутили на украинском телевидении в девяносто седьмом. Я до сих пор их помню.

У моей семьи не было денег на то, чтобы позволить одному из родителей сидеть дома, а отправляться в детский сад я категорически отказывалась. До этого я провела там дней пять и вскоре пришла к выводу, что все вокруг какие-то конченные и находиться в обществе других детей мне ну никак не хочется. Что ж, до определенного возраста я была уверена, что терпеть не могу детей. Затем я выросла и поняла, что моя неприязнь относится не к детям, а к человечеству в целом.

О том, что такое мизантропия и как с этим жить, я тогда ещё не знала.

Выросла я в семье разведенных, но продолжающих поддерживать дружеские отношения родителей – выходцев рабочего класса. Они очень много работали, но толку от этого было мало. За окном стояли суровые девяностые. Папа в те дни был следователем, и ему, как и многим сотрудникам органов, регулярно задерживали зарплату на полгодика, а то и дольше. А затем выдавали не деньгами, а тушёнкой, кашей и конфетами с мармеладом. С тех пор я видеть не могу ни тушенку, ни мармелад.

Так вот, Света должна была наблюдать за мной до самого вечера, но она практически никогда этого не делала. Одним из таких дней я вооружилась чужим поясом и каким-то феерическим образом забралась на шкаф, воображая себя то ли Тарзаном, то ли кем-то из его мира. Пояс должен был послужить мне лианой. О том, что его следовало бы как-то закрепить, я, конечно, не подумала. Да и разве об этом принято задумываться, когда тебе четыре?

Словом, я прыгнула. Следующим моим воспоминанием стала довольно красочная картина: я лежу на полу, лампа – все та же лампа гостиной горе-няньки – бьет мне в глаза, а справа от меня лужа крови, которая, к тому же, растет в размерах. Я пытаюсь отодвинуться от этой лужи, но ни рука, ни даже плечо меня не слушаются, и кровь уже забирается в материю моего вязаного свитера. Изображенные на нем Том и Джерри, прежде увлеченные погоней, уже никуда не спешат. Лишь таращатся на алую лужу, что все увеличивается и увеличивается.

Затем они смотрят куда-то ниже. Во взглядах проскальзывает ужас. Я тоже туда смотрю и вижу, что в районе сгиба руки виднеется что-то светлое, но не понимаю, что это что-то – моя локтевая кость. 

Тем временем, вокруг уже бегают санитары скорой помощи. Они пытаются надеть на меня кислородную маску, но я всячески сопротивляюсь. Кричу, отбиваюсь одной рукой, (вторую я не чувствую) топаю ногами и даже кого-то кусаю. 

Как я уже говорила, Света частенько оставляла меня наедине с телевизором. Никто не фильтровал поток просматриваемых мной фильмов. Многие из них сегодня явно имеют рейтинг R. В итоге я знала одно: если на тебя надевают кислородную маску, не жди ничего хорошего. Скорее всего, ты проснешься в холодном подвале, раздетый и прикованный в батарее. Возможно, уже трижды изнасилованный. Весь пол будет залит ледяной водой, смешанной с кровью и дерьмом. На стенах окажется ржавчина, а окон как таковых и вовсе не будет. Рядом с тобой могут быть и другие люди, но не факт, что живые. У кого-нибудь вполне может недоставать глаза или даже половины головы, а затем ты вдруг обнаружишь отсутствие одной-двух конечностей на собственном теле.

В общем, я брыкалась, кусалась и орала. Вскоре в комнату вошли новые санитары. Общими усилиями им удалось надеть на меня маску, и я отключилась.

Картина, которую я увидела после пробуждения, не особо отличалась от описанных выше ужасов: я была в государственной больнице. И я не могла встать с постели или даже пошевелиться. Моя пострадавшая рука оказалась подвешенной к потолку. Со всех сторон ее пронзали какие-то спицы и штифты, эти шрамы останутся со мной на всю жизнь. Левая рука, а также мои ноги были закреплены кожаными ремнями. Как вы уже поняли, у меня случился открытый перелом. Мама не один год работала в сфере медицины и была знакома со многими достойными врачами, но Света не стала рассказывать ей или папе о произошедшем. Она представилась медикам моей родственницей, и меня передали первому попавшемуся травматологу. Родители узнали о случившемся, лишь когда я проснулась от наркоза, увидела медсестру и начала требовать позвать маму и папу.

Папу и маму, если быть точнее. 

Конечно, к тому моменту меня уже прооперировали. Света, завидев моих родителей, ретировалась в первую попавшуюся дверь, и больше ее никто не видел. Как выяснилось позже, с врачом мне повезло не больше, чем с нянькой. Однажды его уволили, но случилось это уже после того, как он сложил мою правую руку. И сделал это неправильно.

Я провела на больничной койке ровно пять недель и ни разу за это время не могла встать на ноги. Когда наконец пришло время вынимать все эти средневековые железные крепления, что как минимум достойны упоминания в списке декораций «Восставшего из ада», мне было позволено встать на ноги. Тут-то и выяснилось, что я разучилась ходить. К счастью, это умение вернулось ко мне спустя несколько дней, чего нельзя было сказать о моей правой руке. Горе-доктор обещал, что мне понадобится пара недель на реабилитацию. Затем рука вновь сможет чувствовать, держать предметы и все такое прочее. Короче говоря, функционировать. 

– Не переживайте, ничего делать не надо, – говорил он взволнованной матушке. – Само пройдет.

Прошел месяц. Затем еще один. Я стала левшой. Моя сломанная и заново сложенная рука не хотела работать. Хуже того, она также не желала расти вместе со мной. Пальцы становились какими-то скрюченными и очень тонкими. Они практически не разгибались, а сама рука была очень бледной. Нет, мне не ампутировали конечность, ничего такого, ведь это кем надо быть, чтобы заявить о таком лишь в середине книги? 

В конечном счете нашлась талантливая доктор, которая помогла поправить ситуацию, и год спустя я вновь стала правшой. Осталась лишь одна проблема, решить которую не смогли даже более удачливые доктора: моя рука не могла согнуться так, как следовало. Вместо этого она проворачивалась в локте и изгибалась каким-то совершенно неестественным образом, но никто не хотел заново ломать руку четырехлетнему ребенку. Да и шансы на то, что это поможет, были малы. С момента заживления прошло слишком много времени.

Так я и осталась: с испорченной рукой и поломанной психикой.

