# 43 {-}

– Так и че с садиком? – спросила Лина.

К тому моменту наш запас алкоголя успел наполовину сократиться. И я ответила, что вскоре мне все же пришлось туда пойти.

– Первые недели три было несложно. Во время обеденных прогулок и прочих местных игрищ я просто уходила куда подальше, отворачивалась от других и делала вид, что их не существует…

Тут Лина залилась звонким смехом.

– Ты и сейчас так делаешь!

– …Знаешь, песни там пела и все такое. Но период социально приемлемой адаптации прошел, и от меня стали требовать непосредственного общения с другими детьми. А они все так же казались мне идиотами.

– Кстати об идиотах, – вдруг вспомнила подруга и икнула почти так же звонко, как смеялась. – Что там твой Веня, молчит?

Молчит он или делает чего похуже, я не знала, потому что отключила телефон еще в начале вечера. Пожалуй, здесь стоит объясниться.

<div style="text-align: center;">***</div>

Вениамин позвонил мне в начале первого, что само по себе уже было странным. Он знал, что после полуночи за стойкой начинается самая настоящая запара. Если мы и общались в это время, то только посредством переписки.

Тем не менее Веня позвонил. Я спряталась в шкафу для алкоголя и взяла трубку со словами:

– Что стряслось?

– Им не удалось меня поймать, – вдруг заявил мой жених.

Голос его был странным. Чужим и отрешенным. Как тогда, на балконе, когда одному из нас пришло в голову провести кельтский колдовской ритуал. И этот голос принялся рассказывать мне совершенно несвязную историю. Она звучала как обрывки фраз, услышанные от разных людей в переполненном помещении. Но что еще хуже, создавалось впечатление, что этот голос – а вместе с ним и Веня – явно куда-то бежит.

– Где ты? – было первым, что я спросила.

– Я… во… во… дворах, – раздался прерывистый ответ.

Как я и говорила, у меня уже имелся немалый опыт общения с невменяемыми людьми. В какой-то степени я и сама была одной из них. В общем, я сделала вид, что все нормальненько, и постаралась разобрать всю ту бессвязную ахинею, которую говорил жених. Мой краткий и, можно сказать, авторский перевод гласил следующее. Несколько часов назад (когда точно, было не ясно, ведь здесь мнения объекта повествования здорово так расходились) Вениамин закончил работать. Вместо того чтобы отправиться домой, он решил заскочить в «Среду обитания» – тот самый бар, где прошел один из моих последних вечеров в Севастополе, как раз перед клятвой на крови. Сперва все шло как обычно, а затем местный бармен настойчиво стал требовать, чтобы Веня убрал свой нож.

– Нож? – переспросила я.

– Нет, не нож.

– А что тогда?

– Ножи! – гордо и как-то обиженно исправил меня Вениамин. 

Как будто это в корне меняло дело.

Было это после пятнадцатого или шестнадцатого шота с водкой, отчего становилось ясно, что ножи были нужны Вениамину явно не для того, чтобы вырезать фигурки из бесплатного хлеба, который некоторые заведения все еще держат на барной. Пробелов в истории было еще больше, чем неясностей. Закончилось все тем, что сотрудники заведения вызвали милицию. Когда та приехала, вся стойка была в дырках и царапинах от ножа, зал опустел, и только Вениамин, как ни в чем не бывало, сидел на вращающемся стуле, продолжая кутить в одиночестве. Ножи, кстати говоря, торчали рукоятками вверх вдоль барной стойки.

Так вот, в итоге моему жениху было предъявлено обвинение в ношении холодного оружия, порче чужого имущество, плюс что-то там о разбое. Далеко не впервой, но! Когда пришло время оформлять моего красавца, тот резко поднялся со стула, выскочил в дверь и убежал в темноту как был: без сорочки и с рюмкой руке.

Так, очевидно, он и бегал по близлежащим дворам до того, как позвонил мне.

Спустя два месяца я решилась выпить кофе в «Среде обитания». Бармен узнал меня и, посмеявшись вдоволь, спросил, почему же мой суженый больше к ним не заходит. После чего подтвердил рассказанную выше историю, и я узнала, что в перечне поставивших Вениамина в черный список заведений стало одним баром больше.

– Им меня не догнать, – отдышавшись, повторил Вениамин.

Затем он сказал, что ему холодно и что он скучает. Кажется, даже всплакнул. В дверь моего алкошкафа уже вовсю стучали заждавшиеся заказов официантки, а Веня все спрашивал, когда же я приеду.

– Если бы я только знала, – сказала я.

Две недели, которые мне полагалось отработать перед увольнением, давно прошли. Никто не спешил нанимать и обучать нового бармена. А вместе с тем и не спешил выдавать мне зарплату. Мое заявление об увольнении по собственному желанию все так же пылилось на ресепшене. Его до сих пор не подписали. 

– У нее там личный разговор! – вдруг услышала я голос Лины.

Он звучал очень громко, и я поняла, что подруга стоит прямиком у шкафа, в котором я все это время сидела.

– Мне без тебя жить не хочется, – тоскливо произнес Веня.

В этот момент дверь шкафа распахнулась. На пороге стояла управляющая. Вид у нее был совсем не дружелюбный. Из-за плеча женщины выглядывали фицы с пустыми подносами.

– Прости, – прошептала я в трубку. – Мне нужно бежать. Напиши мне, когда будешь дома.

И я отключилась.

<div style="text-align: center;">***</div>

Прошло больше часа. Я выполнила все заждавшиеся меня заказы. А следом за ними еще несколько новых. Затем еще и еще. Количество посетителей ресторана начинало уменьшаться. В конечном счете остался всего один столик, вальяжно распивающий пятую бутылку коньяка, да местный алкаш, дремлющий за стойкой в компании надпитой рюмки.

Вениамин все не звонил. Его телефон был отключен на протяжении последних сорока минут. Стрелка настенных часов уже успела перевалить за отметку «2». В начале третьего Веня объявился. Как выяснилось, все это время он провел дома у Нели – той самой подчиненной, заказавшей при мне в KFC восемь бургеров и что-то там еще. Как он туда попал, было неясно, ведь бар находился в часе с лишним езды от дома женщины, а транспорт в Севастополе ходит лишь до полуночи. Зачем он туда попал – тоже хороший вопрос, ведь «Среда обитания» находилась через дорогу от дома, где жил Вениамин.

– И что там делаешь? – спросила я.

– Пью водку, курю траву…

– Водка закончилась! – услышала я на фоне раскатистый голос Нели. – Мы идем в магазин!

Шальной и угашенный, как вся моя жизнь.

– Водка закончилась, – повторил за ней Вениамин. – Мы идем в магазин.

– Постой, Веня! Ты где ночевать-то будешь?

– Я буду ночевать там, где будет водка! – крикнул он, рассмеялся и повесил трубку.

Я спрятала телефон.

– Все нормально? – спросила Лина. 

Она как раз занималась финальным отчетом.

– Нет, – ответила я.

И рассмеялась. Смех получился каким-то нервозным. Оно и неудивительно.

– Поня-я-я-тно, – протянула подруга. – Уже через минуту заканчиваю. Неси Егеря.

<div style="text-align: center;">***</div>

Спустя минут пятнадцать, очевидно, пополнив свои заветные запасы, Вениамин позвонил снова. Чтобы сообщить, что мы переезжаем жить в Симферополь. Кто это «мы» и зачем мы туда переезжаем, было не очень ясно. Как и все остальное. Разговор оборвался так же внезапно, как начался, и я решила отключить телефон, прежде чем Веня позвонит еще раз, чтобы рассказать мне о смене пола или, скажем, своем внезапном решении усыновить сиамских близнецов из Башкирии.

– Если он только хочет переехать, все не так-то плохо, – прокомментировала Лина. – Но то, что он ночует у этой бабы... Как там ее звать-то? Короче, пофиг, ты ее вообще знаешь?

– Ага, – ответила я.

Настроения у меня больше не было. «Егермейстера» к тому моменту тоже. Пришлось идти за абсентом.


