# &nbsp; {#chapter-44}

Прошло еще двадцать восемь дней прежде, чем мое заявление об уходе было подписано. Двадцать с лишним дней, подавляющую часть которых я провела за стойкой. Находиться здесь мне совершенно не хотелось. Не только потому, что платили барменам настолько мало, что я даже подумывала вернуться в IT. И не только потому, что Вениамин не мог ко мне приехать. Наверное, к тому моменту мне просто все надоело. 

Надоело работать по четырнадцать, а то и шестнадцать часов в сутки, постоянно находиться в шуме, таскать ящики с товаром со склада двумя этажами ниже, строить вежливость и по несколько часов к ряду развлекать сидящих за стойкой алкашей, которые все равно не оставят тебе чаевых. А если вдруг оставят, то этих денег не хватит и на пачку сигарет. Да, каких сигарет, на проезд не хватит! Пожалуй, самое обидное в моей работе было даже не отсутствие чаевых, а то, как мне их преподносили. Какой-то захудалый пьяница оставлял на стойке свои копейки с таким видом, словно оплачивал мне год учебы в Оксфорде.

Середина июня уже давно была позади, а я все так же продолжала торчать здесь, сама не зная зачем. И вот однажды я вошла в двери этой богадельни как, в общем-то, делала каждое утро. На часах было ровно пол одиннадцатого утра. Кассир, сменщица Лины, как раз переодевалась в подсобке. Это была сорокалетняя женщина по имени Галя, работавшая в «Штиле» с самого его открытия вот уж без малого тринадцать лет.

– Привет! – раздалось из подсобки.

– Доброе утро, – ответила я и начала завязывать волосы.

После жалких чаевых, это был мой самый ненавистный аспект работы барменом.

– Я говорю, привет! – настойчиво повторила Галя.

– Я отвечаю: доброе утро!

От постоянного гула музыки и от криков постояльцев слух Галины явно подкосил. Приходилось практически кричать, чтобы до кассира дошел смысл моих слов. Сама она, кстати, почему-то говорила очень тихо. При всем при этом Галя всегда была в курсе последних новостей. Она слышала различные сплетни, знала, кто кому изменяет, помнила все грандиозные (и не очень) попойки и все такое прочее. По всей видимости, острый слух, все-таки, возвращался к Галине при нужных обстоятельствах. Но, что было еще лучше, все эти внутренние проблемы и откровения мало волновали бывалую кассиршу, так что если она и выдавала какой-нибудь факт, то только по делу.

– ПРИВЕТ! – еще громче крикнула кассир.

Я подвязала волосы, надела фартук и подошла к самой двери подсобки. Приоткрыла ее и только тогда завопила:

– ДОБРОЕ УТРО!

На что Галя ответила мне:

– О, привет. А я уж было думала, ты меня так и не заметишь.

Иногда складывалось впечатление, что она надо мной издевается.

– Я спущусь на склад, а потом сразу кофе. Тебе делать? – я уже сверяла полный список алкогольной продукции с тем, что было в наличии за стойкой.

– Делай, – ответила Галя и вдруг заговорческим тоном добавила: – И долго ты здесь еще будешь?

– Где?

Кассир обвела взглядом бар, потолки и стены ресторана.

– Надеюсь, нет, – произнесла я. – А что?

Следующую свою реплику Галя начала с моей любимой фразы. Она сказала:

– Да тут поговаривают… – и тут же замолчала.

Пришлось крайне выразительно поднять брови и на какое-то время задержать их в таком состоянии, чтобы услышать продолжение.

– Поговаривают, что тебе работа твоя не нравится.

– Ничего себе проницательность! 

Сарказма Галя не оценила. Лишь повторила сказанное.    

– Поговаривают, что тебе работа твоя не нравится.

– Так это же прекрасно! – заметила я.

– Прекрасно? Почему?

– Может, эта мысль как-то приведет их к моему заявлению. И его хоть кто-то подпишет.

Галина завертела головой.

– Нет-нет-нет, ты же не знаешь ничего. Поговаривают, что тебе работа твоя не нужна и что ты на нее ходишь от скуки. Что у тебя папа известный в городе адвокат и деньги тебе не нужны. Просто тебе скучно. Вот ты и решила сюда устроиться.

Будь я персонажем старых мультфильмов Диснея, моя челюсть уже болталась бы где-то на уровне пяток.

– Поэтому начальство не подпишет заявление. Ира сказала, что ты должна лично попросить ее об этом. Они уже округлили твою зарплату в обратную сторону и начислили какой-то штраф.

Что ж, думаю, где-то в этот момент все мое дружелюбие в сторону Антона, гуру бартендинга, окончательно улетучилось. Мне стало все равно, где он будет искать новых сотрудников и почему так трудно это сделать. 

– Понятно, – говорю я.

Затем традиционно скидываю с себя фартук, бросаю его куда-то в сторону и иду в зал ресторана. Несмотря на то, что до открытия минут десять, за угловым столиком уже сидит первый посетитель. Иностранец в очках-полумесяцах. Он медленно пьет эспрессо и что-то читает на планшете. За столиком у другой стены сидит Ирина Валентиновна, управляющая. О ней тоже поговаривают. Особенно о том, как из зеленой официантки она вдруг стала управляющей целого развлекательного комплекса меньше чем за сезон. Никто так и не понял, кто кому изменил: настолько быстро все произошло. А мне было ка-то не до этих сплетен. Да и, отчего-то, не верилось. Стоит женщине добиться успеха, и о ней уже тут же начинают поговаривать.

Вот иду к Ире, но не затем, чтобы рассказать эту увлекательную историю и свой взгляд на ее карьерный рост. По пути захватываю заявление, забытое всеми на рецепции. Управляющая сидит с опущенной вниз головой. Она увлечена своими записями и до последнего момента совершенно не замечает моего присутствия.

– Доброе утро! – звонко здороваюсь я.

Женщина подскакивает, а я сажусь за столик прежде, что Ира успевает что-то ответить. Она явно удивлена. 

– Не помешаю?

Управляющая ничего не отвечает, так что я просто протягиваю ей заявление об уходе, написанное двадцать восемь дней назад.

– Мне кажется, вы его не заметили, и я решила лично попросить вашей подписи.

– Зачем такая спешка? – интересуется Ира. – Ты же знаешь, у нас нет свободных барменов.

Ее губы растягиваются в самой широкой в мире улыбке.

– Я согласилась подождать только из уважения к Антону, но свои положенные две недели я отработала… – я задумалась над базовыми подсчетами. – Две недели назад. Больше я ждать не хочу.

– Может, тебя у нас что-то не устраивает? – голос управляющей звучит почти заботливо.

Она продолжала улыбаться, и я улыбнулась в ответ. Своей самой широкой в мире улыбкой. Вот они и встретились – две фальшивые улыбки. Настолько блестящие, что, кажется, будто свет от ресторанной люстры-штурвала просто не знает, в каком месте ему нужно отразиться.

– Вы знаете, мне на самом деле не нужны деньги. Мой папа известный в городе адвокат и я нашла эту работу просто от скуки. Я знаю раздел трудовой Кодекса Украины наизусть. Как и то, что штрафы запрещены Законом. Рассчитайте меня сегодня же.

Я все так же улыбаюсь. Управляющая – нет. 

<div style="text-align: center;">***</div>

Меня рассчитали в тот же день. Поставили отметку в трудовой книжке и почему-то не стали проводить проверку товара. Они даже забыли потребовать сдать форму. Та до сих пор пылиться где-то на даче.

Несмотря на то, что Добби подарили обещанный носок, день выдался слишком насыщенным. Оттого мне так приятно было его прожить. Часы неслись, работа кипела, а у меня даже не было времени присесть на минутку. За пару часов до закрытия в бар вошла Лина. Меня всегда поражали люди, который даже в свой выходной приходят на работу, сидят там весь вечер, общаются с коллегами и листают соцсети. Но Лина была исключением, ведь она приходила, чтобы поболтать со мной.

– Вот это ты выдала! – прокомментировала подруга, узнав, что сегодня мой последний рабочий день.

Я уже смешивала ей авторский коктейль под названием «Для Друзей Бармена». Прекрасное сочетание всего, что осталось с банкетов, а также того, что можно списать, не привлекая лишнего внимания. 

– Так, и шо же я теперь тут делать буду? Ты не подумай, я рада твоей личной жизни. И ты наконец-то отстанешь от меня с этим своим «Что-о-о я здесь делаю?»...Но я поднялась работать в ресторан только из-за тебя.

– В качестве извинения, – сказала я и протянула Лине коктейль.

– Одним тут не отделаешься, – ответила она.

<div style="text-align: center;">***</div>

Следующие часа три прошли за приканчиванием личных алкогольных запасов. Понятия не имею, как долго это длилось, но, когда мы вышли на ступени «Штиля», за окном все уже выглядело так, словно вот-вот начнет светать. Усталость, наконец, дала о себе знать. Спать хотелось невыносимо, но мы еще какое-то время постояли у крыльца, зная, что таких посиделок больше не будет. 

Странная штука работа. Ты словно состоишь с ней в каких-то сложных, чуть ли не абьюзивных отношениях. Ненавидишь, всячески увиливаешь от своих обязанностей и считаешь, что только попусту тратишь время. Но стоит тебе бросить это дело, вдруг понимаешь, что вот оно, еще одна крохотная эра твоей жизни закончилось. Так как прежде уже не будет. И тебе даже становится грустно, но вскоре и это проходит.

Так вот, мы еще немного постояли, вдыхая прохладный утренний воздух. После двадцати часов, проведенных в помещение без окон он казался роскошью. Затем мы взяли такси. Мой телефон издал конвульсию входящего сообщения.

– Машина подъехала, – прочитала я.

Как-то подозрительно быстро для такого раннего часа. Дорога перед нами была пустой.

– Опять счетчик хотят пораньше…

Подруга не успела закончить мысль: из-за угла выплыл бежевый лимузин. Из салона доносилась музыка, а окна машины переливались неоновыми гирляндами. Нормальное дело для ночного клуба, скажите вы. Вот только клуб к тому моменту уже закрылся. Водительское окно опустилось. Я увидела пожилого усатого мужчину за рулем.

– Девочки, такси заказывали? – спросил тот.

Мы переглянулись, затем синхронно пожали плечами и залезли в авто. Внутри оказалось много гирлянд. Куда больше, чем я предполагала. Они сияли и выразительно отбивались в горчичных глазах моей подруги. У окна стояло шампанское, а из колонок доносилась Staying Alive Би Джиз. Мы с Веней частенько под нее отплясывали.

– Это что за подарок судьбы? – спросила я у шофера.

– Выпускные в Могилянке, – ответил тот. – Возвращался вот с заказа домой и решил вас подкинуть.

Могилянку я так и не закончила. Бросила на третьем курсе, когда понадобились деньги, так что и выпускного у меня не было.

Несмотря на то, что дороги пустовали, машина ехала медленно. Бутылка шампанского была открыта. Как и люк, в который я вскоре высунулась вместе с вышеупомянутым напитком. Staying Alive, казалось, звучала еще громче. Мы пели вместе с Барри Гиббом, смеялись и прикладывались к шампанскому. Лимузин как раз выезжал на проспект, когда я увидела своих теперь уже бывших сотрудниц. Тех самых официанток из клуба. Они шли вдоль трассы, навстречу машине, но тут же встали как вкопанные, увидев, чья физиономия возвышается над лимузином в сопровождении Би Джиз и шампанского.

После той ночи мне ни разу не было грустно от того, что я так и не побывала на университетском выпускном. Самое эффектное увольнение в моей жизни.

