# 48 {-}

У каждого автора есть такой «блокнот в винных пятнах». Ты постоянно носишь его с собой и практически никогда не перечитываешь, но если что и записываешь – всегда в точку. Нет, я не хочу сказать, что писательству нужен алкоголь, как в случае с Буковски, Ремарком, Томпсоном, По, Фитцджеральдом, Хемингуэем, Керуаком, Джойс, Есениным, или даже О.Генри с его извечно позитивным настроем. 

В общем, список можно продолжать бесконечно. И, хотя факты говорят об обратном, я никогда не считала, что алкоголь – обязательная часть писательства. Неважно чем именно был перепачкан блокнот, – хоть крошками протеинового батончика – он непременно есть у каждого, кто однажды решил связать свою жизнь с самой требовательной женщиной в мире – литературой. Свой блокнот я забросила еще в средине лета. Чего никак нельзя было сказать об алкоголе.

– Ты интересно пишешь. Мне нравится, – однажды сказал Веня.

И вроде как, это должно было меня порадовать. Увы, он говорил о всего лишь о наших письмах, не о моих книгах. 

– Мне стыдно за свое скудоумие, – добавил он, как бы извиняясь за то, что до сих пор не знаком с творчеством женщины, на которой решил жениться. – Я читаю только фантастику.

Не знаю, что меня удивило больше: фантастика, или то, что Веня впервые употребил в разговоре такое слово, как «скудоумие», но я только спросила:

– Зачем же себя так ограничивать? 

– Беда в том, что больше меня ничего не затягивает.

И, все-таки, кое-что он прочитал. Я узнала об этом, когда вторая неделя моего возвращения подходила к концу. Мы как раз заканчивали ужинать на балконе, и речь зашла об этом.

– И как тебе?

– Очень странный этот твой жанр, трагикомедия, – признался Вениамин. – Я смог прочитать только третью часть книги, но…

– Но?

– Я просто не понимаю, как человеку может быть весело, когда его жизнь так печальна? Ты грустишь, когда все плохо и веселишься, когда все хорошо. Не думаю, что в реальной жизни бывает по-другому… Хочешь еще картошечки?

– Нет. Но так ведь в этом то и весь смысл! 

– В чем?

– В том, чтобы продолжать шутить, когда тебе дерьмово. 

– Разве кто-то так на самом деле делает?

– Ну, я делаю. И чем мне хуже, тем мне лучше.

Вениамин завис на минутку, после чего повторил:

– Очень странный жанр.

И он принялся старательно подкладывать еду в мою тарелку.

– Знаешь, – не отступала я, – если бы в реальной жизни все было так, как ты говоришь, меня бы скорей всего здесь не было.

– Ты бы не рискнула приехать к незнакомому мужчине?

– Нет, этого у меня уж никак не отнять. Скорей всего, сейчас я бы пыталась соорудить заточку из антистрессовой головоломки. Где-нибудь на Володарского. Или покоилась бы с миром на старом городском кладбище, но это вряд ли потому как захоронения на нем сейчас проводят только в крайних случаях, да и я предпочитаю кремацию.

– Ну, ты – это другое, – не отрываясь от ужина, ответил Веня.

Спокойствие в голосе этого человека было одной из многих причин, по которым я так его любила. Ну, какой еще мужчина станет нормально относиться к упоминанию трупиков за столом?

– Другое?

– Ага. С тобой законы физики не работают.

– Ах, если бы только физики, – ответила я и подлила себе еще винишка.

Проблема состояла в том, что я практически никогда не пьянела. Алкоголь, как и большинство наркотиков, едва ли мог на меня повлиять. Это была самая дерьмовая суперспособность из всех, что только можно было придумать. Ведь трезвость так ужасна! Для меня же единственный способ избежать ее включал в себя систематическое принятие спиртного (примерно каждые десять минут) и постоянное экспериментирование с крепостью выпитого.

– Как, черт возьми, тебе удается бухать круглые сутки и так хорошо выглядеть? – однажды спросила меня Дана, старая подруга из Казани. – Я выпиваю бокал шампанского, и лицо уже куда-то плывет.

– Весь секрет в том, что я практически не пьянею, так что мне приходится подливать себе что-то каждые пятнадцать минут. Если я хочу соответствовать окружающей меня публике, конечно. 

– И все что ли? Вот он твой великий совет: больше пить?

– А еще от алкоголя у меня опухают только губы. От этого я кажусь симпатичней. 

На самом деле, я слишком часто слышу этот вопрос, дабы знать на него правильный ответ. Видимо, таков вот мой бесполезный талант номер двадцать три. Прекрасная почва для алкоголизма.

– А этот пленительный блеск в глазах? – с недоверием спросила Дана. – Еще скажи, что и тут алкоголь виноват!

– О, нет! Блеск в глазах – это другое. 

Я выставила указательный палец и с серьезным видом постучала им в районе виска.

– Попрошу не путать! Всему виной проблемы с кукуней. У психов всегда глаза блестят, ты разве не замечала?

<div style="text-align: center;">***</div>

Одним июльским утром я проснулась в подавленном настроении. Это было как раз то самое мерзкое состояние, когда ты сам не знаешь, чего хочешь, и при этом ощущаешь острую нехватку чего бы там ни было. В такие моменты мне сразу вспоминалась одна из тех странных сказок, что папа читал мне в глубоком детстве. Называлась она «Поди туда, не знаю куда». В ходе сюжета лирическому герою было велено было пойти туда – не знаю, куда и принести то – не знаю, что. 

Именно это мне и хотелось ответить Вениамину, который настойчиво интересовался, чем он может мне помочь.

– Давай найдем какой-нибудь уютный паб? – предложила я. – В Севастополе ведь еще остались заведения, в которых тебе разрешено появляться?

– Да целая куча! 

– А питейные заведения?

– Ну, таких поменьше будет, – признался Вениамин. – Но они все равно есть.

– Тогда, вперед! - решила я.

Тем не менее, в тот день мы так ничего и не нашли. Уже с приближением вечера мы бродили крохотной лесопосадкой, что тянулась вдоль дороги. Здесь пахло хвоей и прохладой, а земля была усеяна шишками, желудями и мхом. Если в правильный момент закрыть глаза, создавалось ощущение, что ты находишься на какой-нибудь лесной опушке. Уши, кстати говоря, тоже стоило бы закрыть. В паре метров от нас была находилась трасса, и даже густая стена деревьев не была в силах скрыть ее гул.

Насколько я помнила, любовь настигла меня где-то здесь, на выходе из импровизированной городской чащи. Выходя из дома тем прекрасным майским утром, я всего лишь хотела позавтракать в КФЦ, а вместо этого обнаружила себя по уши встрескавшейся в мужчину, которого я едва знала и который, накануне сделал мне предложение. 

Что ни говори, а люди, воюющие с фастфудом, видимо, не так уж и ошибаются.

– О чем это ты там задумалась? – поинтересовался Вениамин.

Он курил, опершись на ствол какого-то старого дерева.

– Возможно, мне и правда нужно перейти на правильное питание, – ответила я. 

– А я бы сейчас скушал пяток бургеров…

– Пяток?

– И это далеко не мой рекорд, – довольно заявил Веня. – Как-то я прикончил двадцать девять бургеров!

Я остановилась и не без подозрения взглянула на своего спутника.

– Ты умял двадцать девять бургеров?! 

– Ага, – Вениамин похлопал костяшками пальцев по прессу, ради которого он и пальцем не шелохнул.

Я всегда считала, что жизнь слишком снисходительная к мужчинам.

– И что, ты был настолько голоден?

– Нет, я наелся еще после четвертого. Остальные я съел на спор.

– Понятно, – протянула я, пытаясь прикинуть, сможет ли Веня когда-нибудь сам для себя готовить. – И на что вы спорили?

– На бургер.

– То есть ты заплатил за двадцать девять бургеров и съел их просто ради того, чтобы получить еще один?

– Ну да, тридцатый, – как ни в чем не бывало ответил мой жених. 

В итоге я решила, что нет, готовить для себя Веня точно не способен. Разве что яичницу из дюжины яиц на завтрак.

– А вот и КФЦ! – объявил Вениамин, когда мох под нашими ногами сменился асфальтом.

Знаете, есть много романов с вполне посредственной завязкой. Конечно, далеко не все персонажи любовных историй встречаются на сверхважных государственных заданиях или пытаясь укрыться от ядерного взрыва. Однако ни тем прекрасным майским днем, ни, собственно, любым другим днем своей жизни, я никак не думала, что наша история любви начнется в отделении ближайшего фастфуда.

Поразительно.

<div style="text-align: center;">***</div>

Как я уже сказала, в жизни каждого автора бывают такие дни, когда история не пишется и тебе буквально приходится выдавливать из себя каждое слово. Подобным образом я провела около двух недель. Я была счастлива с Вениамином, но писать у меня, почему-то, не получалось. О том, что эти вещи могут быть связаны, я как-то сразу не подумала.

*Печаль – хлеб поэта*, напомнил мне внутренний голос.	

А ведь так оно и было! Все свои лучшие строки – все то, что имело для меня хоть какую-то художественную ценность – я писала в состоянии глубочайшей депрессии, одиночества и эмоциональной подавленности. Большую часть взрослой жизни я провела подобным образом. Стоило мне впасть в отчаянье, и слова лились из меня так, словно они уже где-то существовали. В такие моменты я забывала обо всем на свете и не отрывалась от писанины до тех пор, пока чувствовала, что мне есть что сказать.

– Тебе не кажется, что это как-то нечестно? – спросила Марта, когда я поделилась с ней причинами своего творческого кризиса. – Да и не кризис это вовсе. Просто творческий застой. 

– Да, какая собственно разница? Творческий кризис, творческий застой, творческий ступор… Это все писательский блок как его не назови!

– Какая разница? Спроси у Гёте, Сэлинджера или Флобера! Такое со всеми бывает.

– Если ты думаешь, что от перечня известных авторов, которые десятилетиями писали свои хиты, мне станет как-то легче... – начала я. – А хотя знаешь, мне и правда стало легче.

Марта рассмеялась, и мы еще какое-то время болтали о пустяках. Существует бездонный список вещей, о которых можно вести преинтереснейшие разговоры, но работает это лишь в компании близкого друга.

Увы, наш разговор не мог длиться вечно. Марта ушла развлекать своего мужа, а я вновь вернулась к мукам творчества.  Гёте, Сэлинджер, Флобер, Толкин, Манн, а также мой наркозависимый однофамилец – все они давно были мертвы. Отстрадали свое и уже успели стать полноценной частью истории. 

– Вот почему просто нельзя как-то обойти всю эту систему? – угрюмо размышляла я, разрывая очередной лист бумаги и швыряя его останки в другой конец комнаты. – Почему просто нельзя перейти к тому моменту, где я уже умерла, а мои книги приобрели литературную ценность? 

Еще одна рукописная страница отправилась вслед за своей предшественницей. Я сидела и пялилась в невидимую точку посреди своего новенького неразлинованного блокнота, добрая часть страниц которого уже заполняла пол кухни. Не знаю, сколько часов я провела подобным образом, кто их вообще считает? Но в определенный момент мне стало казаться, что я схожу с ума. Мозг буквально спекся от перенапряжения. Следом за этим появилась острая головная боль.

Все эти классики, имеющие явные проблемы со скоростью написания своих лучших творений, по-прежнему были мертвы и известны, а я все сидела у подоконника и сверлила взглядом очередной белоснежный лист. За окном уже проступили поздние сумерки, но я и не думала двигаться с места. Головная боль, по традиции, переросла в самую настоящую мигрень. С наступлением темноты мысли у меня перепутались настолько, что я уже не понимала, какие из них мои.

*Я сижу у окна. За окном осина*, произнес Бродский своим монотонным голосом. 

Это случалось со мной с самого детства. Стоило моему котелку перегреться, или если я просто не спала по несколько суток к ряду, подсознание начинало выдавать рандомную поэзию. Чаще всего это был Пастернак, Бродский, Маяковский или Буковски, но случалось и что-нибудь из средневековья, а то и из античной литературы. Порой я забывалась и озвучивала эти строки.

*Я любил немногих. Однако – сильно.*

Помнится, на третьем курсе я пришла в университет после ночной смены в техподдержке и что-то не поделила с главой кафедры филологии. Она сказала мне:

– Васляева, я по-вашему на дуру похожа?!

А я ответила:

– Неужто зреньем бог меня обидел, чтоб я на небе солнца не увидел?

Так вот, когда Вениамин появился в свете фонарей, я продолжала сидеть у окна, пристально глядя на чистый лист. Наверное, надеялась, что, в конечном счете, он воспламенится, и, как это произошло с кольцом всевластия, из огня появятся какой-нибудь идеально выведенный текст.

Увы, подобного не случилось.

Тем летом я толком ничего и не написала.

