# 50 {-}

За окнами по-прежнему стояла невообразимая жара. Лето лениво растянулось вдоль нашей улицы, уходя далеко за ее пределы. Что ж, Крым, вроде как, славится своими морскими красотами. Вот только никто не говорил мне о том, что, несмотря на наличие всех этих водоемов, климат здесь истерически сухой. 

Веня сидел в дверном проходе советских времен спаленки, которая в те дни была нашим домом. Крохотное, ободранное помещение с разваливающейся мебелью и облезлыми обоями. 

Мое любимое помещение.

Помнится, когда мы только начинали жить вместе, бабуля Вениамина торжественно передала нам древнюю кровать с деревянным дном. Это действо она сопроводила следующими словами:

– На этой кровати уже трое померло. Думала, четвертой буду, пользуйтесь.

Ну, вот мы и пользовались.

Солнце лишь недавно опустилось за горизонт, и я вышла на незастекленный балкон. Такой же потасканный, как и спальня, которая к нему вела. И, все-таки, он стал местом, где прошли лучшие дни моей жизни. 

Что ни говори, а панорама здесь и впрямь была живописной. Подкурив сигарету, я наблюдала за тем, как по всему городу, один за другим, зажигались очаровательные огоньки чьих-то спален, кухонь и гостиных. По правую руку от меня виднелось море. Величественное и черное. Мне всегда нравилось смотреть на него. 

Удивительный город – Севастополь. С одной стороны, он неоспоримо погряз в останках постсоветского пространства, в серости зданий, консервативных идиллиях и чертовски запущенной экономике. И, все же, он неповторим. Я знаю мужчин, которые всерьез утверждают, что любили многих женщин, каждую по-своему. И каждой они оставили частичку своей души. Что ж, у меня сложилась похожая ситуация с городами. 

К тому моменту мы жили здесь больше месяца, если не считать моего весеннего отпуска. Естественно, я уже успела сообразить, что к чему: идти до центра было ой как далеко. Дорога занимала около пяти часов. К тому же, шагать почти все время нужно было вверх. Приятного мало, согласитесь. 

Тем не менее, картинка из окна выглядела так, словно вот оно море, прямо у тебя под рукой. 

Если долго бродить по Севастополю, он начинает напоминать вычурную спираль, что окружает воду и горы. Мы же поселились где-то у ее основания.

– Деточка, – послышался голос из спальни. – Ну, сколько можно курить?

Я сделала еще пару затяжек и покинула балкон. 

За пару часов до этого мы с Веней зашли в винную лавку. Продавщица уже давно успела нас запомнить. Не удивительно. Думаю, в этом мире не так много людей, которые приходят в винные лавки за виски, ромом, коньяком, или водкой, а потом покупают все и сразу, прихватив еще парочку бутылок полусладкого. Мол, это же винная лавка, как-никак.  

Короче, в магазине была какая-то акция, и вместо намеченных полутора литров Веня взял шесть бутылок рома. Расправившись с первой бутылкой, он принялся просить меня включить какое-нибудь арт-хаусное старье, и я включила «Влюбленного гробовщика».

– Херня какая-то, – продекламировал Вениамин спустя четверть часа. 

Кинематографический критик.

Здесь стоит признать: Веня никогда не понимал книг, фильмов, музыки и прочих частичек искусства, которые были мне дороги. Стоит ли говорить о чем-то более экзотическом? Тафофилии, буддизме или пост-модерне? Нет, муж определенно всего этого не понимал.

Хуже того, даже не пытался понять. Просто молча наблюдал за происходящим на экране и то не особо внимательно. 

<div style="text-align: center;">***</div>

Незадолго до нового года мы решим устроить себе маленький праздник. Закажем домой огромную пиццу, купим бутылку вина и литра три дешевого портвейна. К тому моменту мы уже переберемся в Симферополь, так что доставщик по традиции полчаса будет нарезать круги вокруг дома, и пицца вновь достанется нам холодной. 

Заглянем же на мгновенье в этот зимний день.

Устроившись на полу, мы обнимаемся и потягиваем винишко. Все это чувствуется как долгожданное спокойствие. Я вроде как вновь счастлива. На экране показывают мой любимый момент – финальную сцену, в которой основные персонажи таки догнали свой поезд. Для этого им пришлось избавиться от чемоданов с вещами покойного отца, которые братья весь фильм таскали за собой. Занятно, что в самом начале фильма была идентичная ситуация, только тогда старшему брату удалось догнать поезд вместе со всеми этими чемоданами. В финале он же и предложил от них избавиться. Такая вот незаметная метафора о принятии прошлого и избавлении от старой боли.  

Все это я пытаюсь объяснить Вениамину, который явно не желает искать в фильме метафор. К моему изумлению, его лицо не выражает ничего кроме, быть может, скуки. 

Я вздыхаю. Потом спрашиваю:

– Тебе не понравилось? 

– Понравилось, – тихо отвечает Веня.

И все же, весь его вид говорит обратное. На лице мужа четко читаются вопросы вроде «зачем мы вообще смотрим на этих людей?» и «почему они весь фильм ничего не делают кроме как куда-то едут?»

– Ты не понимаешь фильмов Уэса Андерсона, – с грустью говорю я. – А я-то ещё удивляюсь тому, что ты не понимаешь меня...

Случится это спустя несколько месяцев.

<div style="text-align: center;">***</div>

Сейчас же мы сидели севастопольской квартирке бабушки Вениамина. Последний как раз выключил очередной из моих любимых фильмов, так толком в него и не всмотревшись. На столе стояло еще четыре полных бутылки рома и одна наполовину выпитая. Или наполовину не выпитая. В принципе, какая разница, если вскоре она тоже опустеет? 

– Ну и чем думаешь заняться? – спросила я. 

Мне нравилось напиваться с Веней как минимум потому, что я любила алкоголь самой неприкрытой любовью. Веню я тоже любила, а пьяный секс с ним казался мне превосходным. На трезвую голову любимый бывал слишком ласковым, когда мне хотелось всех этих ролевых грубостей. Конечно, нежный секс нравился мне ничуть не меньше, но ещё больше нравилось находить ту самую золотую середину. 

Вениамин указал на открытую бутылку. Он разом опустошил ее, выпив ром прямиком из горла. 

– Схожу в душ и прилягу к тебе. 

Мне хотелось обнять мужа, утащить в сторону постели. И все же, по одному ему известной причине, Веня не очень-то жаловал банные процедуры. Порой приходилось чуть ли не силой заталкивать его в ванную, так что я, само собой, обрадовалась такому внезапному заявлению. 

– Буду тебя ждать, – ответила я.

Венька лукаво подмигнул и удалился.

Что ж, на этой многообещающей ноте я решила воспользоваться рекламной паузой, и запрыгнула в своё любимое кружевное боди. Это был полупрозрачный корсет чёрного цвета. И тем вечером он как нельзя кстати пришелся в компании чулок с подвязками и пояса для них, который я как раз натягивала. Мне нравилось носить нуарное белье, не знаю почему. А Вене нравилось, как я в нем выгляжу. Да, многим нравилось, на самом деле. 

Прошло уже приличное количество времени, а Вениамин все не появлялся. Повертевшись и покрутившись с полчаса на кровати, я провалилась в сон. Сложно сказать, что мне снилось. Да и снилось ли мне вообще что-нибудь, или я просто дремала? 

Бессонница, дающая знать о себе изредка, лишь делает людей нервными. Говоря же о систематической бессоннице, она превращает мозг человека в холодец, жидкий и при этом напрочь застывший. Чем меньше ты спишь, тем более сюрреалистичным становится мир вокруг. В итоге, ты проводишь так много часов в попытках сомкнуть глаза, что уже попросту не понимаешь, удалось ли тебе уснуть.

Мне показалось, что я уснула.


