# 51 {-}

Сквозь сон моих до ушей доносился чужой голос. 

– Когда это было? – требовательно спрашивал он. – Когда это было? Когда это было? Когда…

И так раз за разом.

Распахнув глаза, я увидела, что голос исходил от Вениамина. Однако он принадлежал явно не тому человеку, за которого я согласилась выйти замуж. Чужими были интонации, манера разговора и даже сам тембр голоса. Обычно меня не так-то просто разбудить, но сознание мигом отреагировало на новый источник звука.  

Я села на кровати. 

Передо мной стоял Веня. Он был полностью голым, если не считать полотенца, небрежно накинутого на бедра. Волосы – все еще влажные – падали на лицо. В полумраке прикроватного ночника они сливались с густой бородой, скрывая большую часть лица. Исподлобья на меня смотрел, нет, прямо-таки таращился одинокий глаз моего муженька. Но даже он казался мне чужим. 

В голове мельком пронеслось какое-то воспоминание. Еще не до конца сформировавшийся флешбек. Это почему-то показалось мне важным, но я так и успела развить эту мысль. Очевидно, вдохновившись моим пробуждением, Веня сменил пластинку.

– Ты говорила, – гробовым голосом произнес он.

В первую неделю знакомства Вениамин рассказал, что у него глаза-хамелеоны. Меняются в зависимости от настроения, как те дурацкие кольца, что были так популярны в моем детстве. Среди перечисленных цветов был серый. Он подразумевал ярость. Я хорошо запомнила это просто потому, что никогда не видела Веню с серыми глазами и смутно представляла себе эту картину. Сейчас же (без пяти минут) муж глядел на меня с неприкрытой ненавистью. Его глаза были не просто серыми. Они были стальными. Даже при тусклом свете ночника я могла ясно рассмотреть этот нездоровый блеск.

*Oh, you’ve got green eyes,*

*Oh, you’ve hot blue eyes,*

*Oh, you’ve got grey eyes.*

Сон как рукой сняло, но картинка в моей голове по-прежнему была мутной, как Ингул во время весенних отливов. Вместе с тем, поведение Вениамина едва ли выручало.

– Ты чего? – прохрипела я и прошлась по комнате быстрым взглядом. 

– Ты говорила во сне, – вновь с ненавистью бросил он.

В исполнении Вениамина эти слова звучали как приговор.

На столе недоставало одной бутылки рома. Теперь она одиноко лежала на полу у кровати. Пустая. Такой расклад мне совсем не понравился. И этот голос. Он звучал неестественно глубоко и как-то слишком медленно. Так звучат поврежденные пластинки.

– Правда? – наивно спросила я.

Что ж, временами, в моменты эмоционального и физического истощения, я действительно разговаривала во сне. Причем делала это отнюдь не сонным, а очень даже бодрым и довольно правдоподобным голосом. Эта привычка образовалась у меня с наступлением совершеннолетия. Тогда я устроилась на свою первую официальную работу. Занималась ею ночью, а утром отправлялась в университет. Само собой, на сон при таком графике отводилось всего ничего, так что за неимением срочных звонков и писем я могла вырубиться прямиком на рабочем месте. Именно тогда я и научилась дрыхнуть, не подавая виду.

– Лизочка, – глаза сами открывались, как только кто-то из сотрудников называл мое имя. 

Стоило менеджеру подойти ко мне, и какая-то часть мозга тут же просыпалась. Она молниеносно реагировала на различную активность и вела вполне конструктивные диалоги с другими людьми, в то время как я продолжала спать. Кстати говоря, я почти никогда этого не помнила и в принципе отлично высыпалась. Так что все, что мне известно о своей сонной болтовне, поступило со слов очевидцев. Более того, во всех случаях моих зафиксированных припадков ночной общительности другие люди первыми начинали разговор.

Как ни странно, прошло много лет с тех пор, как мне в последний раз рассказывали, что я говорю во сне. По словам Вени, когда он зашел в спальню, я уже общалась с кем-то. Причем называла этого анонима любимым и рассказывала, что мы знакомы много-много лет. Якобы мы встретились каким-то летним днем, но начали отношения лишь этой осенью. На минуточку, за окном стояло лето две тысячи шестнадцатого года.

Стоит ли говорить, что у меня не было никакого романа на стороне? Как не было и бывшего возлюбленного, подходившего под это описание. И все-таки Вениамин упорно отказывался мне верить. Я выползла из постели и попыталась обнять его, но Веня лишь отстранился. 

– Врешь, – упрямо заявил он.

После чего хмыкнул и окинул меня каким-то оценивающим взглядом. Словно другой человек. В тот момент я была слишком сонной и обескураженной, дабы разозлиться. Прежде мужчины никогда не разговаривали со мной в таком тоне, и я просто не знала, как на это реагировать, несмотря на все эти ваши феминизмы.

*Oh, you’ve got grey eyes.*

Веня резко подорвался с кровати и направился на балкон, прихватив с собой очередную бутылку. Я поспешила за ним, окончательно позабыв о том, что на мне надето. Если полтора года за стойкой меня чему и научили, так это тому, что спорить с алкоголиками – дело крайне бесполезное. Словом, я не стала отрицать слов Вениамина и решила посмотреть, что будет дальше.

Дальше оказалось хуже.

Сероглазый двойник моего мужа хранил молчание. Он расправился с пятью сигаретами, не проронив ни слова, и периодически прикладываясь к бутылке. Когда и четверная сигарета отжила свое, Веня вдруг заговорил. Его слова все еще звучали медленно и как-то безэмоционально.

– Ты до сих пор его любишь.

– Кого? 

– Адама, – подозрительно быстро ответил Вениамин.

И я поняла, что именно об этом он так старательно думал на протяжении пяти сигарет, курение которых пришлось на двадцать жутких минут гробовой тишины.

– Конечно, нет! Я о нем уже давно и думать забыла, Венька.

Но мой жених не унимался. Совершенно внезапно он принялся меня допрашивать. Прежде Веня старательно избегал любых разговоров, что так или иначе были связаны с любовью, моими бывшими и прошлыми отношениями. Как и большинству мужчин, которых я знала, Вениамину была противна сама мысль и том, что когда-то его девчонка могла быть с кем-то еще. И, как и всех упомянутых выше мужчин, тот факт, что у меня было впятеро меньше партнеров, чем у него самого, никак не утешало моего жениха.

Сейчас же он сделался невероятно заинтересованным. Веня задавал миллион вопросов о моем бывшем и делал это с такой несвойственной ему внимательностью к деталям.

– Когда ты его в последний раз видела?

– Когда мне было девятнадцать.

– Когда?

– В две тысячи тринадцатом году.

– Точно?

Я кивнула.

– И что, трахается он лучше меня?

– Вообще нет, – тут мне даже врать не пришлось.

– Так когда ты его видела?

– Три года назад.

– Летом! – чуть ли не ликующе выкрикнул Вениамин.

– Нет, осенью.

– И как это произошло? Ты ведь ему что-то сказала на прощанье?

- Нет, – просто ответила я.

– Почему?

– Потому что тогда я не знала, что это наша последняя встреча.

Вениамин подкурил энную сигарету и вернулся к допросу.

– А он? 

– Думаю, он тоже этого не знал.

– Нет. Что он сказал тебе. Ты помнишь?

Конечно, я помнила. Поезд, опустевший перрон и последние дни золотой осени.

*А ты боялась, что история нашего знакомства будет неромантичной*, говорит мне Адам. 

Поезд издает финальный гудок, и Адам улыбается.

– А теперь поцелуй меня. Как персонаж чертового черно-белого фильма.

Тогда я запрыгнула в поезд и что было сил старалась не оглядываться. Боялась, что если увижу Адама еще хоть разок, непременно разревусь. Само собой, я помнила этот день. И дело здесь не только в моей исключительной памяти. Как можно не помнить последних слов, сказанных на прощанье человеком, которого ты когда-то так сильно любил?

– Я не помню, – наконец ответила я.

Тем вечером я впервые соврала Вениамину.

<div style="text-align: center;">***</div>

– Поклянись, что любишь меня, – не столько попросил, сколько потребовал мой жених.

Вечер уже обратился ночью, а мы все так же торчали на балконе. Я – в белье и с заплаканными глазами, Вениамин – в явном алкогольном опьянении и с ранее упомянутой бутылкой в левой руке. Правой он коснулся моей щеки и смахнул с нее одинокую слезинку. Его большой палец все еще поглаживал меня по лицу, тогда как остальные крепко обхватили заднюю часть моей шеи. 

Вениамин пристально посмотрел на меня, и я нехотя встретилась взглядом с его глазами. Все еще серыми. И такими чужими. 

Тогда он повторил последнюю фразу.

– Поклянись, что любишь меня.

И тут я вспомнила. Алкоголь, балкон, ночь, кельтский колдовской ритуал, чужие глаза и слова любви – все это уже было. Я поняла, что именно меня так настораживало на протяжении последних пары часов. Далекая мысль, посетившая меня той весенней ночью, когда жениху взбрело в голову дать клятву на крови, вернулась.

– Я люблю тебя, Венька, – ответила я, не отводя взгляд.

– Ах ты сука! - прорычал Вениамин. – Могла бы хоть раз сказать мне правду, – сухо добавил он в ответ на мой удивленный взгляд.

У меня буквально не было слов, так что я сделала то, что стоит делать писателю, когда ему ничего сказать, – удалилась.

