# 53 {-}

– Это хорошо, что ты не спишь.

Голос незнакомца возвращает меня к реальности. Я не сплю, просто лежу в постели с распахнутыми глазами, находясь где-то далеко-далеко, в самых заветных уголках своей памяти. Со мной такое частенько бывает.

– Вот как, – машинально отвечаю я, хотя на самом деле я до сих пор еще где-то там, у себя в голове.

– Да, вот так.

Его голос уже звучит куда привычней, но я все равно не могу отделаться от этого мерзкого чувства – коктейля из досады, обиды и печали с толикой самобичевания и привкусом типичной бабской усталости. 

Мне захотелось заплакать. Хотелось разреветься что есть сил и плакать до тех пор, пока во мне совсем не останется слез. Порой от этого и правда становится легче. Я попыталась припомнить, когда я в последний раз так плакала, но не смогла. Моя извечная борьба с психическим расстройством не предполагала подобных опций. Я прекрасно помнила, что стоит мне позволить себе хоть всхлипнуть, и вскоре это перерастет в настоящую истерику. А если у меня начнется истерика, то все, пиши пропало. 

Внешне я оставалась спокойной, но горький ком уже поднимался к горлу, а перед глазами предательски продолжали всплывать флешбеки из нашего совместного прошлого. Все эти теплые воспоминания мешали мне участвовать в разговоре. 

На самом деле мне вовсе не хотелось отвечать Вениамину. Если я чему и научилась в «Штиле», так это тому, что с пьяницами нет толку разговаривать, пока они во власти алкогольного делирия. Сказать больше, в большинстве случаев общаться с людьми в подобном состоянии – идея не из лучших. Ты словно ходишь по краю нагревающегося вулкана, где каждая сказанная тобой фраза равносильна таким опрометчивым действиям, как погружение какой-нибудь конечности в раскаленную лаву. 

В итоге даже если ты вдруг окажешься самым стойким к боли человеком, какой толк мучиться? Во всех твоих страданиях просто не будет никакого смысла. Все равно первую осмысленную фразу алкоголик произнесет только после того, как вдоволь отоспится. К тому же сейчас я как никогда ощущала, как же сильно я устала. От людей, от их слов и от их действий, за которые никто потом не хочет нести ответственность. Короче говоря, я продолжала молчать. Видимо, это не на шутку зацепило моего муженька. В ожидании ответа Вениамин стоял у балконной двери со сложенными на груди руками. Вскорости он, кажется, понял, что разговорить меня не удастся. Тогда Веня мигом преодолел несколько метров, которые нас разделяли, и развалился в кровати. 

– Ты все еще в тех чулках? – между тем поинтересовался Вениамин и, не дожидаясь ответа, стащил с меня одеяло.

Он принялся плавно водить пальцами по внутренней стороне моего бедра, едва касаясь кожи.

– У тебя очень красивые ноги, – вдруг сказал Веня.

– Странно, что ты только сейчас это заметил, – отрезала я.

– И чулки красивые. И подвязки. Тебе идет.

Становилось ясно, что дальше молчать не получится. Я как раз пыталась придумать какой-то нейтральный ответ и в уме уже перебирала все возможные варианты, когда муж спросил:

– Для него ты их тоже одевала?

– Надевала, – не удержалась я.

Я произнесла всего одно слово, но для моего избранника этого оказалось достаточно. Он резко выпрямился, сел на кровати и одарил меня самым презрительным взглядом, на какой только может быть способен человек в начале пятого утра после пяти с лишним бутылок акционного рома. 

– Ты… – начал Веня.

Его еще недавно затуманенные глаза вновь обрели стальной блеск, а дыхание сделалось громким и тяжелым. Казалось, оно заполнило все пространство вокруг. Мне стало не хватать свежего воздуха. 

– Ты… Ты такая же, как они все! – заявил Вениамин. – Лживая самовлюбленная шлюха с комплексом самоубийцы – вот ты кто! 

Я бы с легкостью могла пропустить все это мимо ушей, вот только его глаза… Они продолжали бурить во мне дыры. Не думаю, что прежде хоть одно живое существо смотрело на меня так, как сейчас смотрел Вениамин. От этого взгляда мне сделалось по-настоящему страшно – столько нескрываемой злобы и ненависти сквозило в глазах мужа.

Тем не менее Вениамин не останавливался.

– Ты говоришь, что ты писатель! Ха-ха! Все, что ты делаешь круглыми днями – это сидишь на диване и отращиваешь жирную задницу. 

Мне почему-то подумалось, что еще чуть-чуть и я потеряю сознание. 

– А потом еще ждешь, что я приду домой и трахну тебя как следует. А ты, сука, вообще в курсе, каково это – целый день общаться с людьми? – он перешел на крик. – С людьми, которых ты ненавидишь! Но у меня, блядь, нет выбора! Я должен с ними общаться! Я делаю это ради тебя! Потому что нам нужно на что-то жить! А потом я прихожу домой и слышу твое нытье о том, что сегодня ты ничего не написала! Да кого это вообще ебет?

– Меня ебет, – только и успела вставить я.

– Я провожу с этими мразями целый день! И на хера? Чтобы прийти домой и узнать, что ты любишь какого-то левого мужика! И с хуя ли я должен после этого тебя трахать? Что ты мне на это скажешь, Васляева?

Вениамин продолжал кричать, но я уже его не слушала. Теперь и мое дыхание стало каким-то тяжелым. Я поняла, что время метафор прошло: мне и впрямь становится сложно дышать. В голове уже начинало гудеть, а где-то на фоне пролетела мысль о том, что неплохо бы сейчас выкурить сигаретку.

*С ганжей.*

Последней у меня не было уже месяца два.

В общем, я выбралась из постели, схватила халат и собралась на балкон. Увы, я успела сделать только шаг в сторону выхода. Что-то крепко схватило меня за плечо, а через секунду Вениамин уже швырнул меня обратно в кровать. 

– Мне нужно на воздух, – собиралась сказать я, но на деле вышло что-то куда менее членораздельное.

– НЕ СМЕЙ ОТ МЕНЯ УХОДИТЬ!

От его ора меня начинало трясти. Происходящее настолько обескуражило, что я даже не сразу заметила, что плачу. Я пойму это только спустя несколько минут, когда коснусь лицом намокшей от слез подушки.

Я еще раз попыталась подняться. На этот раз не так быстро. Вопреки всем законам физики и, несмотря на количество выпитого спиртного, Вениамин среагировал мгновенно. Он выпрыгнул из одеял и с бешеной силой сжал мне руку. Запястье тут же взвыло, но в следующий момент это уже не имело никакого значения. Вениамин развернул меня на сто восемьдесят градусов и отвесил тяжелую пощечину.

Это не была пощечина из разряда тех, которыми женщины награждают друг друга во время жарких споров. Это даже не была та пощечина, какой обычно награждают мужчин, уличенных в измене. И уж тем более это не была одна из тех страстных пощечин, которые мне порой так нравились в сексе.

Нет, это был самый настоящий удар, от которого я тут же улетела в сторону прикроватной стены. За этим последовала адская головная боль, сильней которой было разве что острое чувство обиды и непонимания происходящего, мигом возникшее у меня в голове. 

Насилие – всегда страшно. Об этом знает каждый, но… Как выяснилось, насилие вдвойне ужасно, если оно исходит от твоего любимого человека. От того, кому ты всецело доверяешь. От того, с чьей стороны ты наоборот подсознательно ждешь защиты. Конечно, я не раз слышала о семьях, где домашнее насилие является чуть ли не частью каждодневной рутины. Но слышать о подобном и пережить это – абсолютно несравнимые вещи. Никаких слов не хватит, чтобы описать леденящий душу ужас, что сковал меня вслед за ударом.

Где-то на задворках моего подсознания мелькнула смутно знакомая мысль.

*Что-то плохое происходит прямо сейчас*, шепнула она.

Как бы там ни было, Вениамин не дал углубиться в раздумья. Он тут же схватил меня за волосы. Я попыталась вырваться из этой хватки, но Веня уже с силой швырял меня лицом в постель. Он несколько раз грубо тряхнул меня за волосы и лишь после этого плотно прижал лицом к подушке. 

– ДА…СКОЛЬКО…ТЫ…БЛЯДЬ… ЕЩЕ…БУДЕШЬ… 

Сероглазый двойник мужчины, которого я любила, продолжал кричать. Он прямо-таки орал, надрывисто выплевывая каждое слово. Правда, голос этот быстро отошел на задний план, уступая место разыгравшейся в моей черепушке мигрени.

Моя щека коснулась чего-то влажного. Вот тут-то я и выяснила, что уже реву.

Возможно, я предприняла еще одну попытку встать. Возможно, нет. Когда с тобой происходят ситуации сродни этой, подобные детали делаются бесполезными. 

– МНЕ ПОЕБАТЬ, ЛИЗА…

Поток слез все никак не желал останавливаться, отчего дышать было практически невозможно. Одной рукой Вениамин продолжал держать меня за волосы. Вторая рука мужа скользнула вниз по моей шее и мертвой хваткой застыла у ее основания. 

– ДА Я ТЕБЯ ПОСЛЕ ЭТОГО И КРАЕМ ГЛАЗА ВИДЕТЬ НЕ ХОЧУ!

Продолжая выкрикивать ругательства, разобрать которые я не смогла бы при всем желании, Веня что было силы сжал мне шею, перекрыв и без того слабый поток воздуха. 

– Не смей от меня уходить! – эта фраза была одной из немногих, что мне удалось разобрать. Вениамин продолжал повторять ее снова и снова.

Понятия не имею, как долго это длилось. Как выяснилось, время замирает не только во время первого поцелуя. Котелок раскалывался, щека горела, кожа головы изнывала от боли, шея ныла, а легкие пекли от невозможности вдохнуть. Стоит ли говорить, что все это меркло и бледнело в сравнении с тем, что творилось в моей душе?

Вениамин еще разок тряхнул меня за волосы и убрал руку с шеи. Вторая рука оставалась на месте, когда ее хозяин склонился надо мной.  	

– ЛЕЖИ, БЛЯДЬ, КОГДА Я С ТОБОЙ РАЗГОВАРИВАЮ! – прошипел он мне на ухо.

Я жадно хватала ртом воздух, чувствуя, что слез на глазах становится все больше и больше. Комната и все ее наполняющие стремительно поплыли перед взглядом, когда Веня поднял меня за волосы. Прижал себе так сильно, что я слышала каждую каплю спирта, выпитую им прошедшим вечером. 

– ТЫ МЕНЯ ПОНЯЛА?

Думаю, будь у меня алкотестер, он бы непременно показал все семь промилле. 

Вениамин не обращал никакого внимания на подкрадывающуюся ко мне истерику. Вместо того он продолжил браниться, а затем вновь спросил, поняла ли я его. Суть вопроса, как, в общем-то, и всего происходящего, дошла до меня отнюдь не сразу. Раскрасневшийся от гнева муж нетерпеливо тряхнул меня за плечи.

– Ты меня поняла?

Только после этого я сообразила кивнуть.

– ДАЖЕ НЕ ДУМАЙ ОТ МЕНЯ УХОДИТЬ! – еще раз выкрикнул Вениамин.

После этого он, наконец, убрал вторую руку. Я мертвым грузом упала на сбившиеся от потасовки подушки. Веня лег где-то рядом. Пелена слез, скопившихся в преддверье глаз, скрыла от меня его лицо, и я была за это благодарна. Еще одной встречи с этим испепеляющим и таким чужим взглядом серых глаз я бы точно не пережила.

Щека коснулась чего-то влажного. Подушка подо мной оказалась насквозь промокшей. Я лежала на ней без единого движения, ожидая момента, когда мой сожитель замолчит. Брань его становилась все менее яростной, а голос постепенно затихал, пока Веня совсем не умолк.

Теперь можно, отрешенно подумала я, и позволила слезам вырваться наружу.

