# 54 {-}

– Посмотри на меня, – тоном, не требующим повторения, сказал муж.

На сей раз его голос звучал спокойно, но я уже успела убедиться в непостоянности этого спокойствия. Оно продлилось с четверть часа, после чего Вениамин вдруг решил вернуться к старой теме. Теперь он крепко обнимал меня за талию, продолжая задавать все те же вопросы и выкрикивая ругательства, что едва ли отличались оригинальностью. Веня держал меня всего одной рукой, но делал это с завидной для пьяницы ловкостью. 

Я лежала на боку, спиной к своему возлюбленному, и изо всех сил пыталась притвориться спящей.

– Посмотри на меня, деточка.

Пальцы жениха скользнули вверх и тут же обосновались на моем предплечье. Малейшее движение делалось от этой хватки невозможным. До этого момента, я и не подозревала, насколько он сильный. Даже нашла в себе силы искренне этому удивиться. 

– Если ты еще хоть раз попытаешься уйти от меня во время разговора… ТЫ МЕНЯ СЛЫШИШЬ, ВАСЛЯЕВА?! ЕСЛИ ТЫ ЕЩЕ ХОТЬ РАЗ, ХОТЬ РАЗ ПОПЫТАЕШЬСЯ ОТ МЕНЯ СБЕЖАТЬ, Я, БЛЯДЬ, НЕ ЗНАЮ, ЧТО С ТОБОЙ СДЕЛАЮ!

Выкрикнув это, Вениамин ослабил хватку, а затем без лишних церемоний развернул меня лицом к себе. Слезы обжигали глаза. Мне совершенно не хотелось их открывать. Я чувствовала на лице горячее дыхание любимого, но все, чего мне сейчас хотелось, – это бежать. Вот так, в чем есть. Только халат сверху накинуть, да и то не обязательно. Бежать в ночь, в волны, в неизвестность. Может быть, сбить ноги о камни или даже сброситься со скалы – не важно. 

Что угодно, лишь бы только вновь не проживать этот момент.

– ТЫ МЕНЯ ПОНЯЛА? – с этими словами пальцы делившего со мной постель мужчины коснулись моих волос, чтобы мигом исчезнуть в их волнах.

Мне стоило немалых усилий открыть глаза. Конечно, сначала все вокруг было очень мутным из-за пелены слез, что накрыла мое лицо. Силуэт Вениамина грозно нависал надо мной. В тусклом свете одинокой настольной лампы он выглядел крайне устрашающе и больше походил на проклятье старого призрака, какими детей пугают перед сном.

Не проронив ни слова, я наблюдала эту картину еще с полминуты, пока в глазах у меня окончательно не прояснилось. Видимо, Веня тоже этого ждал потому, как он тут же зашевелился и придвинулся еще ближе. 

– Ты меня поняла? – повторил он.

На этот раз без крика.

Его рука до сих пор была в моих волосах. Пальцы судорожно сжимались и разжимались. Руки Вениамина все так же продолжали дрожать, но это меня не удивило. Я и сама дрожала. Тряслась как осиновый лист впервые за двадцать два года.

– Деточка? – напомнил о себе Вениамин.

*Деточка.* От упоминания самого этого слова мне захотелось плюнуть ему в лицо.

Веня опустил руку, и я заметила, что несколько прядей моих волос остались торчать зажатыми между его пальцев. Вероятно, они запутались в кольцах, но это не очень меня волновало, чего нельзя было сказать о Вене. Несколько секунд он с удивлением рассматривал оторванные частички моей шевелюры с полным недоверием на лице.

*Он не помнит*, поняла я. 

Эта мысль напугала меня гораздо сильнее всех вместе взятых криков, пощечин и вырванных прядей. Тем временем, Веня продолжал разглядывать клок волос, намотанный вокруг объемного серебряного кольца. Того самого, которое прошлой весной он надел на безымянный палец моей правой руки.

– Это я сделал? – уже с меньшим недоверием спросил Веня.

Вопрос вполне мог сойти за риторический, так что я не стала на него отвечать.

– Прости, что вырвал тебе волосы, – неожиданно произнес Вениамин. – Я этого не хотел.

Откровенно говоря, я понятия не имела, что следует говорить в таких ситуациях. Я вообще вроде как никогда не планировала в них попадать, так что я просто кивнула.

Вениамин продолжал за мной наблюдать. Возможно, ждал, когда я сорвусь и наброшусь на него с обвинениями. А может быть, просто мысленно оценивал нанесенный ущерб, одновременно пытаясь припомнить, каким именно образом он этот самый ущерб нанес.

– Ты вся дрожишь, – заметил Веня после продолжительной паузы. 

*Да ладно! Скажите, Шерлок, откуда такие методы? Это дедукция или индукция?*

Он попытался меня обнять, но я инстинктивно отстранилась. Вениамин моментально изменился в лице.

– Ты что, боишься меня? – без особого доверия спросил он, но, заглянув в мои глаза, сам понял ответ. – Ты меня боишься.

Прежде я никогда не испытывала такого чувства. Я вообще сомневалась в том, что могу настолько сильно чего-то бояться. Но это был самый настоящий страх, беспощадный и всеобъемлющий. Дикий ужас, сопровождаемый тупым оцепенением. Теперь я как никогда отчетливо могла ощутить это состояние. Оно распространилось по всему телу, затрагивая каждый нерв, каждую мышцу и каждую клеточку.

– Нет, – едва слышно ответила я.

Так плохо я еще никогда не врала.

– Тебе нечего бояться, – отмахнулся Вениамин, но язык его тела говорил об обратном. 

Чем ближе было утро, тем сильнее мой суженый походил на привычного глазу пьянчужку. Постепенно взгляд Вениамина делался мутным, речь становилась медленной, а язык заплетался все сильнее и сильнее. Он вновь положил руку мне на бедро, коснулся губами плеча и несколько раз плавно провел пальцами по разгоряченной коже. 

Несмотря на разыгравшуюся ситуацию, – на страх, который так никуда и не ушел, на слезы, которые еще толком не высохли, на пульсирующую мигрень, прочую физическую боль и обиду, которая без остановки меня грызла – я чувствовала, как от этих прикосновений по моей коже предательски побежали мурашки. Следом за ними появились и другие. Они плавно накрыли собой каждый миллиметр моей кожи, и я ощутила, как кровь приливает к низу моего живота. Всего один поцелуй, и жар вспыхнул. Меня охватило мгновенное возбуждение. Такое яркое, что я сама себе ужаснулась.

Вениамин тоже это заметил. Он стремительно поднялся выше и принялся стягивать с меня белье. Расстегнуть корсет у него так и не получилось. В конце концов, Веня решил переключиться на те части меня, что не были скрыты под одеждой. Он принялся покрывать поцелуями мои плечи и шею, постепенно приближаясь к декольте. 

– Я люблю тебя, – не прерываясь произнес Веня.

Его пальцы уже проникли мне под одежду, а я все так же лежала, бесцельно глядя в потолок. Впервые в жизни, находясь в постели с любимым мужчиной, я чувствовала возбуждение, которое не хотела чувствовать. И я сопротивлялась этому как могла, чего нельзя было сказать о моем муже. Казалось, Веня и вовсе забыл, с чего началась эта ночь. Ему все-таки удалось сорвать с меня белье. Легким движением руки Вениамин отшвырнул его в сторону и склонился надо мной.

Склонился точно так же, как когда душил меня в этой самой постели каких-то полтора часа назад. Эта картина моментально всплыла у меня перед глазами, как будет всплывать еще не один раз. Все произошло совсем недавно. Пожалуй, я напоминала сжавшийся комок нервов, который напрягался при малейшем шорохе. Сколько бы Веня не целовал меня, по-прежнему хотелось плакать.

Еще несколько минут он покрывал мое тело поцелуями, повторяя слова любви. Увы, сейчас все эти речи казались мне абсолютно ненастоящими, что делало их крайне бесполезными. Разгоревшаяся во мне похоть быстро затмила страх. Лежа в объятьях Вениамина и чувствуя, как пространство между ног становится все мокрее, я внезапно для себя самой поняла, что злюсь.

Как раз в этот момент Вениамин расправил плечи, закинул на них мои ноги, и вошел в меня. Сделав несколько рывков внутри, он попытался меня поцеловать, но к этому моменту ступор наконец прошел, и я успела слегка осмелеть. 

– Любовь моя, – сладко проворковал мой жених и это окончательно меня доконало.

В общем, я собралась духом и оттолкнула его в тот самый момент, когда губы Вениамина вот-вот должны были коснуться моих.

На лице мужа отразилось полнейшее недоумение.

– Что опять не так?! – с раздражением спросил он и, не дожидаясь ответа, предпринял новую попытку заняться со мной сексом.

Вениамин окончательно захмелел. Сейчас этого уже нельзя было не заметить. Тем не менее он все с тем же упорством пытался мной овладеть. В какой-то момент, я даже подумала, что можно просто спокойно лежать и ничего не делать. Судя по всему, его бы вряд ли надолго хватило, а у меня уже просто не было сил сопротивляться. 

К тому же моей нервной системе сегодня нехило досталась. Как выяснилось, вопреки сильному возбуждению, я ничегошеньки не чувствовала внизу живота. Черт возьми, я даже не сразу смогла понять, вошел он в меня или нет – настолько плохо у меня этим утром обстояли дела с чувствительностью. 

– Я так люблю тебя, – вновь пробормотал Веня.

<div style="text-align: center;">***</div>

Поразительно! Как много лет я провела, изнывая от одиночества. Все эти годы я особенно не верила, что смогу полюбить еще раз, полюбить сильнее. Ни на мгновенье не забывала, к чему приводит любовь, а оттого смутно могла представить мужчину, ради которого еще раз соглашусь поддаться ее чарам. Тем не менее не любить я толком никогда не умела. Без этого чувства в душе делалось пусто, а жизнь казалась до невозможности бессмысленной. Это был тот самый отвратительный момент, когда ты уже познал все беды от любви и ох как от них устал, но все никак не можешь искоренить в себе такое простое, понятное каждому желание – любить и быть любимым.

Что же касалось любовной идиллии, я убедила себя в том, что это невозможно, еще задолго до начала работы в «Штиле». В те дни я страдала больше обычного, а потому и пила больше обычного. И вот где-то между третьей бутылкой крепленого и ночным походом в магазин за пачкой сигарет я увидела высокого худого парня и девчонку вдвое ниже его. 

Я видела их и прежде. На протяжении последней пары лет они встречались мне то целующимися остановке, то гуляющими за руку по парку, то делающими покупки в ближайшем супермаркете. Вскорости выяснилось, что высокий парень и маленького роста девушка еще и живут вместе. Их балкон выходил в тот же двор, что и мой, и я уже не первый год наблюдала в окне соседского дома эти счастливые лица. 

Теперь же они обнимались под своими окнами. Так, словно совсем не живут вместе, а то и вовсе видятся раз в месяц. Пожалуй, для нормального человека это может прозвучать дико, но подобные любовные картины не раз вгоняли меня в депрессию. Все эти мельком встреченные на улицах парочки, целующиеся, обнимающиеся и держащиеся за руки люди, что были счастливы в своей любви, постоянно нагоняли на меня тоску. Парни и девушки, которым, в отличие от меня, было дано любить и быть любимыми. Вряд ли хотя бы половина встреченных мною влюбленных на самом деле знала, как сильно им повезло. 

Некоторые распоряжались любовью как чем-то само собой разумеющимся. Чем-то совершенно неважным и незначительным, что не могло меня не злить. В такие моменты мне хотелось подскочить к рассорившимся голубкам и приняться орать на них что есть духу. Мне хотелось кричать обо всем том, что приносит в наши жизни любовь, напомнить, как много они получают в своих отношениях и как глупо растрачивают их на ерундовые скандалы и бытовые конфликты. Короче говоря, мне было больно смотреть, как люди изо дня в день топтали и пинали любовь, ради которой никто, по сути, и пальцем не шелохнул.

Пожалуй, похожие чувства должна испытывать бесплодная женщина. Она мечтает о детях и проклинает небеса каждый раз, когда слышит об абортах.

Не то чтобы я ненавидела всех этих взаимно любящих друг друга женщин и мужчин, или мужчин и мужчин, или женщин и женщин. Скорей меня не устраивала сама ситуация. Без сомнений, ссорящееся по пустякам и регулярно расстающиеся друг с другом пары могли вызвать во мне раздражение. Но куда чаще они всего-навсего вгоняли меня в уныние. Когда ты одинок и болен душой, такие вещи воспринимаются чуть ли не на уровне личностной обиды.

И не без причины.

– У тебя этого никогда не будет, – негромко произнесла двадцатилетняя я, наблюдая за соседской парой.

Впервые в жизни эта мысль не принесла мне боли. Более того, она меня вполне устроила. 

Оказалось, отношения – это гораздо больше, чем просто дарить тепло и получать его. Если опустить детские глупости и взглянуть на мою взрослую и не очень жизнь, становится ясно, что я никогда не отношалась с человеком, которого не любила. Не строила серьезных отношений с тем, кто бы мне нравился, был симпатичен, или кого мне попросту хотелось затащить в постель. Нет-нет-нет, жизнь не раз показывала мне, чем это дело заканчивается. Отношения несли за собой огромный риск. Здесь не было места легким симпатиям и нереализованным постельным амбициям. Если что и могло меня втянуть в подобное дерьмо, так это любовь.

*Love.*

*Love will tear us apart.*

*Again.*

Я слишком долго страдала от неразделенной любви, измен, расставаний и обманов, лжи, недосказанности и поспешно разорванных отношений, стараясь прикрыть раны в сердце выпивкой и новыми знакомствами. Пыталась много работать, да так, чтоб у меня и времени на депрессию не возникало. Ну, и, конечно же, я пару раз пыталась забыть любимого человека, прыгая в постель с другими мужчинами. 

Как бы там ни было, в итоге я все равно заканчивала тем, что могла разреветься по практически любому поводу, если тот наводил меня на мысли о собственном одиночестве. Катализаторами, к примеру, могли послужить парные футболки, двойной разъем для наушников или последний свободный столик в ресторане, который, ох, простите, доступен только для двоих. Черт возьми, даже небрежно выброшенный кем-то из окна автомобиля презерватив, что как-то встретился мне по пути на работу, напоминал об одиночестве.

Словно я когда-то могла о нем забыть!

Пускай тогда мне так и не удалось вытрахать из себя Адама, я поняла кое-что важное. Так уж вышло, что я изнывала от любви слишком долго, и одним разом все это мне просто осточертело. Впредь я больше не пыталась заткнуть свое одиночество. Да и какой смысл в том, чтобы его прятать? 

*Пускай звенит*, думала я.

Каждый раз, когда, находясь в эмоционально уязвимом состоянии, я сталкивалась лицом к лицу с каким-нибудь очередным проявлением любовной идиллии, псы в моем сердце уже не лаяли. Они лишь начинали тихонько поскуливать, а я повторяла себе одну и ту же фразу.

– У тебя этого никогда не будет.

Как ни странно, эти слова меня успокаивали. От правды мне всегда становилось легче. Трудней всего оказалось ее признать.

<div style="text-align: center;">***</div>

– Я так люблю тебя, – горячее дыхание Вениамина обжигало мне шею.

Слушая его, я понимала, что еще каких-то пару лет назад вряд ли могла представить себе ситуацию, при которой выражение чувств со стороны любимого мужчины привело бы меня в ярость. 

*Лет?* – тут же отозвался внутренний голос.

Всегда такой правильный, такой хладнокровный в своих суждениях.

Лет? Пришлось признать, что речь, скорей, идет о месяцах. Если не о неделях. На протяжении всей своей жизни я считала любовь самой важной вещью на свете, но она едва ли отвечала мне взаимностью. Говоря о любви, я имею в виду не только свои чувства к мужчинам. Я говорю о всяких взаимоотношениях с людьми. Кем бы ни были мои друзья, я любила их ничуть не меньше мужчин. С той же слепой верой и не всегда здоровой самоотдачей. По сути, дружба была для меня так же важна, как и сама любовь. Без них моя жизнь мигом теряла последние краски. Взять хотя бы Мишель.

<div style="text-align: center;">***</div>

Мы познакомилась так давно, что точной даты уже не припомнить. Произошло это то ли в конце девяностых, то ли на рассвете двухтысячных. Словом, дело было в раннем детстве, еще до того как кто-либо из нас пошел в школу. С Мишей мы встретились прямиком у воды, неподалеку от ее загородного дома, где впоследствии пройдут лучшие, а вместе с тем и худшие дни моего отрочества. 

Странно звучит, я знаю. Но порой так действительно бывает.

Существуют воспоминания, предысторию которых вспомнить сложно, и ты не можешь с уверенностью утверждать, что было до или даже после описываемого события, а вот сам момент отпечатывается глубоко в подсознании. Всего одно мгновение, но оно настолько чисто и реально, словно это произошло прошлым вечером. Ты помнишь все, от случайно брошенных реплик, витавших в воздухе запахов – именно это происходит со мной, когда я думаю о нашем знакомстве. 

Так вот, мы встретились жарким летним днем. Должно быть, стоял август, потому как вдоль пляжа уже вовсю цвела амброзия, делая воздух чуть ли не ядом для моих легких. Место действия – пересечение двух старых дачных кооперативов. 

Я сидела у самой воды. Лицом к горизонту, спиной к этим жутким растениям. В те дни здесь все еще ходили катера, а все дома в близлежащем поселке были жилыми. Местная детвора собиралась на пляже, приводя с собой младших братьев и сестер, которых родители оставили им на попечение. Катер всегда появлялся в одном и том же месте, но, высматривая очередной корабль, ребятишки каждый раз спорили о том, откуда он должен появиться. Они плескали друг в друга водой и кидались песком, отстаивая свою правоту. Так было, пока чей-то звонкий голос не крикнул:

– Идет!   

Всего одно слово, и дети – все как по команде – сливались на причал, что в те дни только начинал покрываться ржавчиной. С энтузиазмом носились взад-вперед, оставляя за собой шлейф раздражающего топота. Длилось это до тех пор, пока последний пассажир не поднимался на борт. И лишь когда тень катера скрывалась за поворотом, детвора нехотя начинала разбредаться по сторонам.

Идентичная картина открывалась мне каждые выходные. Шумиха сельской детворы уже успела стать неотъемлемой частью пляжа, и я быстро потеряла к ней всяческий интерес. Так что же оставалось?  

Вокруг пахло пивом и сушеной рыбой, а вместе с тем покрывшимися потом телами. Пляж, кстати, был маленьким. Метров пятьдесят на тридцать, или около того. С причалом с одной стороны и зарослями бурьяна, что служили отдыхающим туалетом, с другой. Было там еще несколько деревьев и обшарпанного вида сарай для лодок, который, судя по всему, оставался нетронутым еще с советских времен. Что же касается людей...   

В основном, меня окружали жирные вечно смеющиеся и что-то жующие тетки, абсолютно сумасшедшего вида дети возрастом до десяти лет, а также третьи – волосатые, ноющие и вечно недовольные существа, не поддающиеся никакой идентификации. Впоследствии выяснилось, что это были всего лишь мужчины. 

Сомнительная получалась романтика. 

Тем жарким летним днем толстая светловолосая девочка оказалась единственным не издающим шума ребенком. Она уселась на мели и, отвернувшись от солнца, сосредоточенно рыла ямку в песке. В своем процессе девочка выглядела крайне одиноко, но занятного здесь также было мало, так что я как-то вернула свое внимание реке.

Водорослей на виду еще не появилось, но вода, и без того никогда не отличавшаяся чистотой, сделалась заметно мутной. Здесь это всегда происходило раньше положенного срока. Словно река могла предчувствовать приближение бабьего лета. Понятия не имею, почему у меня не было при себе книги. Я просто сидела на берегу, наблюдая за тем, как волны медленно лижут песок, оставляя на нем темные следы.

Помнится, в тот момент я затаила дыхание и изо всех сил пыталась унять зуд. Но тот уже безбожно нарастал под переносицей. Мне было лет шесть, но я уже знала то, что знает каждый аллергик: стоит потерять бдительность, чихнуть хоть разок, и можешь смело запасаться салфетками, потому как в последующие полчаса это произойдет с тобой еще как минимум раз сорок.

Пройдет еще немало лет прежде, чем я пойму, что и со слезами ситуация у меня обстоит подобным образом.

Волны выпрыгивали из реки и тут же исчезали обратно, едва успевая коснуться песка. Так я и сидела, в крайне мрачном расположении духа и , пожалуй, с самым идиотским из всех возможных выражением лица разглядывала реку, когда заметила около себя какое-то движение. Толстая девочка выбралась из воды. Теперь она неуверенной походкой шла в мою сторону, а я до последнего момента делала вид, что не замечаю этого.

– Привет, я Миша.

Я повернула голову, чтобы увидеть пару зеленых глаз, приветливо улыбающихся мне против солнца. 

– Давай дружить, – на удивление уверенно произнесла девочка.

Забавно, но эта наивная в своей детскости фраза не несла в себе и малейшего намека на вопрос.

Я посмотрела на воду, затем поглядела на кучкующихся на пляже аборигенов, на зеленые глаза и их обладательницу, которой, по всей видимости, наскучило рыть в песке ямы.

*Миша так Миша*, подумала я.

Вновь бросила взгляд на реку и кивнула.    

На этом мое воспоминание обрывается.

Но у меня есть множество других. О прогулках с собаками, приступах кулинарии, походах по барам, каких-то поездках, совместных чтениях вслух, о бесконечном потоке шуток и танцев и о том, как Мишель доставала меня из петли. Однажды на моей руке появилась татуировка с ее именем. К тому моменту обеим из нас было по двадцать.

Я показала татуировку Мише, еще толком не успев спрыгнуть с велосипеда. Та растрогалась настолько, что заплакала прямиком посреди парковки торгового центра, где мы обычно встречались по субботам.

– Почему именно я? – удивилась Мишель. – Почему из всех своих друзей ты выбрала именно мое имя?

Она все спрашивала и спрашивала, но у меня не было ответа. Я не знала, как объяснить, почему наша дружба так много для меня значит. Мы всегда были вместе, что бы ни случилось, и я просто не смогла найти слов, способных передать это ни с чем несравнимое ощущение родства, которое испытываешь только рядом с лучшим другом. 

Потому-то мне было так странно, так больно узнать о предательстве своей лучшей подруги. Услышать все то, что она так ни разу и не решилась сказать мне в лицо, но не стеснялась говорить остальным.

Меня бросали и предавали даже те, кто был рядом не одно десятилетие. Близкие люди отворачивались от меня с наступлением трудных времен. Они брали все, что только можно было взять, а затем с легкостью забывали об этом, как только мне требовалась поддержка. Мне так много врали, изменяли и вставляли палки в колеса те, ради которых я, не задумываясь, отдала бы свою жизнь. Пускай она для меня и не много значила.

Однако, сколько бы печалей и стенаний мне ни принесла любовь, сколько бы слез я ни проливала бессонными ночами, исход был один. Я по-прежнему оставалась верной идеалам любви и дружбы.

И была по этому поводу беспросветной дурой.  

