# 55 {-}

– Ты любовь всей моей жизни, – произнес Вениамин.

Его разогретое спиртом дыхание еще раз коснулось моей шеи, и опустилось ниже. Мне подумалось, что Веня будет признаваться мне в любви до тех пор, пока я не отвечу тем же. Да, быть может еще каких-то пару недель назад я вряд ли могла представить себе ситуацию, при которой выражение чувств со стороны любимого привело бы меня в ярость. 

Тем не менее, в свете последних событий, включавших в себя крики, обвинения, брань и побои, о которых я до этого знала разве что из книг да новостей, а также последовавшую за ними пропажу половой чувствительности, которая не могла меня не взволновать, слова Вениамина меня разозлили. Пускай я и чувствовала исходившее от мужа тепло, которому так хотелось поддаться, я никак не могла избавиться от мысли, что рука, поглаживающая меня по лицу, была той самой рукой, которая не так давно таскала меня за волосы, душила и отвешивала пощечины.  

*Что-то пошло не так*, подумалось мне.

И я вновь оттолкнула Веню, не говоря ни слова. Во второй раз вышло куда лучше. В стену я, конечно, никого не швыряла, но смогла пнуть мужа достаточно сильно для того, чтобы с меня он слез. Я дождалась, пока муженек окончательно сполз на соседнюю подушку, и тут же выскочила с постели. Затем схватила свой халат и, наспех в него укутавшись, отправилась за сигаретой. 

До балкона оставалось всего пару шагов, когда я услышала за спиной какое-то движение. Вениамин медленно приподнялся на локтях. На протяжении нескольких секунд он тупо смотрел на меня затуманенным взглядом, пытаясь понять, что произошло, а потом вдруг пулей вылетел из-под одеяла и ринулся в мою сторону. 

*Что-то пошло не так*, заметил отдаленно знакомый. *Что-то плохое происходит прямо сейчас.*

Очевидная, бесполезная мысль. Она настойчиво продолжала гудеть в моей голове, становясь все громче и громче.  

Вслед за этим на меня обрушился раскатистый бас Вениамина. 

– СДУРЕЛА ЧТО ЛИ?

*Что-то пошло не так. Что-то плохое происходит прямо сейчас.*

– ЧТО Я ТЕБЕ ГОВОРИЛ?! – выкрикнул он. – ЧТО Я ТЕБЕ ГОВОРИЛ?! НЕ СМЕЙ ОТ МЕНЯ УХОДИТЬ! 

*Что-то пошло не так. Что-то плохое происходит прямо сейчас.*

Муж повторял эти слова так много раз, что они уже начали казаться мне до невозможности смешными. А еще мне почему-то подумалось, что, быть может, у Вени с головой совсем плохо, так что он и понятия то не имеет, с чего вдруг я его оттолкнула и куда собственно я направлялась. Возможно, он и впрямь не осознает, что я иду на балкон, и до глубины души уверен в том, что я от него ухожу? Иначе я просто не знала, как еще можно объяснить столь бурную реакцию.

– НЕ СМЕЙ ОТ МЕНЯ УХОДИТЬ! – снова сказал Веня.

Я даже знала, какой будет его следующая фраза.

– ДАЖЕ НЕ ДУМАЙ ОТ МЕНЯ УХОДИТЬ!

Здесь я уже не смогла скрыть улыбку. Зря.

Понятия не имею, как ему это удалось, но через секунду Веня оказался возле меня. Он уже протянул ко мне руки, и я с ужасом осознала, что сейчас все повторится. Спустя мгновенье муж схватит меня за волосы, чтобы швырнуть обратно в постель, зажать шею в мертвую хватку или отвесить мне пару-тройку оплеух. Вероятно, он полагал будто делает это в наказание за то, что мне вздумалось от него уйти.

Все это произошло так быстро. От неожиданности я только и успела, что отшатнуться.

Удивительно, но и этого оказалось достаточно. Без того плохо стоящий на ногах Веня не смог вовремя притормозить. Вместо этого, он окончательно потерял равновесие и растянулся на полу, прямиком у моих босых ног. Само собой, все это только сильнее его разозлило. Бранясь на чем свет стоит, мужчина начал подниматься на ноги. Вот только теперь это давалось ему гораздо хуже. Вениамин то и дело заваливался на спину, сопровождая это действо невнятной руганью, сквозь которую все отчетливей слышалась настигающая его усталость. 

– ЛИЦЕМЕРНАЯ ТЫ МРАЗЬ, ВАСЛЯЕВА!

Меня же охватила полнейшая апатия. Я до сих пор стояла в двух шагах от балкона. Просто не могла заставить себя сдвинуться с места. Ноги вконец отказывались слушаться. За все это время я даже не шелохнулась, если не считать тремора, который и не думал отступать. Мои колени дрожали, а руки тряслись им в такт с удивительной синхронностью. Складывалось впечатление, что эта ночь длится вечность.

В конце концов, до Вениамина начала доходить плачевность собственного положения. Видимо, какая-то не тронутая алкоголем часть мозга моего мужа поняла, что резкий подъем – не лучшая из его затей. Веня больше не пытался вскочить на ноги. Он медленно встал с пола, а потом так же медленно поднялся на колени. Те тут же затряслись, и двигаться дальше мужчина пока не решался. 

К тому моменту царивший в спальне мрак стал понемногу развиваться. Жаль, я не могла сказать того же о своей душе.

Последняя мысль заставила меня опомниться. Сейчас я как никогда остро ощущала нехватку никотина. Стоило мне сделать один единственный шаг назад, и Вениамин мигом сделал очередной рывок. Он так и не смог твердо встать на ноги, и скорее рухнул обратно на пол, обхватив руками мои колени. Его взъерошенная борода едва ли успела коснуться моего живота, когда тишину комнаты нарушил еще один незнакомый голос.

– ПРОЧЬ ОТ МЕНЯ!

Яростный вопль повторился. Фраза эхом отразилась от стен. Лишь когда крик стал гулять по бетонной поверхности я уловила в нем знакомые загробные нотки. Тогда и поняла, что этот голос принадлежит мне. 

– Но ведь я люблю тебя, – просто сказал Веня.

Так, словно это что-то меняло. 

Он продолжал обнимать меня за ноги, но неожиданно отшатнулся, стоило мне вновь повысить голос.   

– КАТИСЬ ТЫ К ЧЕРТУ СО СВОЕЙ ЛЮБОВЬЮ! – не без истеричных ноток выкрикнула я.

Затем поспешно вышла на балкон и трясущейся рукой заперла за собой дверь.

<div style="text-align: center;">***</div>

И вот я стою у края незастекленного балкона, всерьез подумывая с него выброситься. Воздух здесь, как и всегда, пахнет морем. Город еще спит и лишь в паре окон виднеются одинокие искорки света. В это время суток улочки безлюдные и настолько тихие, что можно услышать, шепот морских волны, ударяющихся о камни во время утреннего прибоя. 

Тьма окончательно развеялась. Над горизонтом заблестели первые лучи поднимающегося солнца. Вскоре над водой показалась верхушка алого диска, из которого во все стороны струилось теплое сияние. Оно моментально поглотило воду, окрасив ее во все существующие красно-желтые оттенки, а затем принялось игриво подбираться к крышам стоявших вблизи моря домов. Спустя каких-то пару минут солнце поднимется еще выше. Тогда оно сможет дотянуться и до крыши нашего дома, и до соседних домов, и даже до тех, что находятся позади, далеко-далеко за пределами видимости.

Солнечный диск продолжал плавно вырисовываться над линией горизонта и вскоре из него уже струились миллионы янтарных потоков света. Они хаотично разлетались во все стороны, отражались в безмерном количестве поверхностей и игриво переливались в блеске волн, на морской пене да на песке вдоль береговой линии. Вскоре солнце заполнило собой подавляющую часть окружающего меня пространства. Оно лишь наполовину вынырнуло из-за линии горизонта, накрывая город пеленой мерцающего света.  

В призме рассветного сияния весь мир казался мне не настоящим, плоским и каким-то двумерным. Да и с настройками контраста явно было что-то не то. Куда ни глянь, уголки Севастополя скорей походили на те идеализированные пейзажи, что с полвека назад было принято печатать на открытках. Знаете, все эти картинки с искусственно усиленной яркостью и заведомо преувеличенными масштабами небесных светил. Однако, в отличие от изображений с винтажных открыток, распростершаяся передо мной картина была настоящей. Солнечные лучи в действительности были такими пестрыми, какими их рисуют, а само солнце и впрямь оказалось огромным. Вскоре его лучики блеснули на каменных ступенях, что каждый день вели меня домой, и теперь скользили по прядям моих волос.

Я смотрела на это невообразимых размеров солнце, зависшее над лазурными волнами, и все размышляла о том, как же это не справедливо: наградить столь паршивое утро таким невероятным закатом. Нет, так не должно было быть.

Но так было.

Наряду с ужасами прошлой ночи происходящее с трудом укладывалось в голове. Затем я подумала о том, что, подстраивайся погода под наше душевное состояние, человечество уже бы давно позабыло о том, как выглядит солнце. 

Ведь всегда найдется кто-то, кому еще хуже.

Еще секунд двадцать и солнце окончательно встанет.

Я подкурила то ли вторую, то ли третью за утро сигарету. Охватившая меня ночью дрожь, наконец, начала угасать. Или мне просто этого очень хотелось. В любом случае, пальцы рук, как и мои коленки, периодически подергивались. Из них выскользнула тлеющая сигарета. Она упала на пол и еще какое-то время катилась по балконному полу, чтобы затем исчезнуть где-то в дальнем углу. 

Мне страстно захотелось последовать ее примеру. 

Все это время истерика то и дело пыталась накрыть меня своими шальными волнами. Чем дольше я с ней боролась, тем сильнее становились эти приступы. Наконец, я опустилась на пол, развернулась спиной к солнцу, и прислонилась к сырой стене. Слишком холодной, как для середины лета. Откровенно говоря, я даже не удосужилась запахнуть полы халата. Просто подтянула колени ко лбу и обхватила их руками – вот и все, на что меня хватило. 

Казалось, я вот-вот заплачу, или даже впаду в истерику, но глаза оставались сухими. Было в этом что-то очень тоскливое. Бесконечная пустота оказалась всем, что я чувствовала. Она проглотила меня целиком и сделала это без лишних церемоний. Я прижималась к холодной цементной стене, пытаясь отыскать внутри себя хоть что-нибудь, способное помочь развеять это чувство – ощущение полнейшей безысходности.

– Хоть что-нибудь, – прошептала я, обращаясь к своей всегда такой славной памяти.

В конечном счете, стало ясно, что внутри меня не осталось ни одной теплой мысли, ни одного лучика света, за который я могла бы ухватиться. Увы, тем утром я так и не смогла отыскать ни одного счастливого воспоминания. Во мне не было ни надежд, ни мечтаний, ни сожалений. Не нашлось ни единой доброй мысли, которая смогла бы помочь остаться на плаву. 

Казалось, меня здесь уже тоже не было.

Лишь кромешная пустота, и больше ничего.

Где-то высоко за моей спиной солнце, наконец, достигло своей вершины. Оно величественно парило над водой, отражаясь в морских силуэтах, оставляя на каждом из них частичку себя. Волны шуршали и смеялись, переливаясь всевозможными оттенками лазури. Они словно губка впитывали в себя солнечный свет, чтобы затем унести его зарево в неведомые дали. 

Я опустила голову на колени и в полном безразличии смотрела на каменную стену.

А солнце все сияло и блестело, заставляя так же неистово сиять и блестеть все, до чего могли дотянуться его янтарные лучи. Над морем вспыхнули последние огни рассвета, и на какое-то мгновенье весь мир обратился пейзажем Уильяма Тернера.

Тем утром я ни разу не обернулась, чтобы полюбоваться разыгравшимся рассветом. Как выяснилось, мне было на него наплевать.

Что-то определенно пошло не так. И это что-то уже произошло.
