# Часть II. Аквариум {-}

# 56 {-}

Жара этого дня застала меня в пути. Подобно любому другому транспорту, встретившемуся на крымских дорогах, автобус ехал не просто быстро. Он буквально мчался, заставляя гравий подпрыгивать под колесами. Потускневшие от пыли осколки горных пород синхронно ударялись о шины, отскакивали от них и с характерным дребезжанием разлетались на все четыре стороны. Так звучал голос дороги. Вслушиваясь в него, я не могла не радоваться спокойствию, обволакивающему мысли. Как и всегда, оно дало о себе знать, стоило мне запрыгнуть в кабину и отправиться в путь. 

Чем сильнее автобус отдалялся от Севастополя, тем настойчивей за стеклом начинали проступать горы. Сперва это были лишь призрачные силуэты. Прикрытые таинственной дымкой, они возвышались вдали от трассы. Тем не менее, с каждым преодоленным километром, эти образы приближались. Они становились все ярче и отчетливей. Куда ни глянь, перед глазами появлялись все новые и новые горы, которые, казалось, выныривали из ниоткуда. 

Так длилось до тех пор, пока автобус не добрался до середины пути. Больше не нужно было напрягать глаза, всматриваясь вдаль в поисках новых вершин. Теперь они виднелись повсюду. Горы раскинулись по обе стороны дороги, ведущей автобус к Симферополю. На фоне яркого, безоблачного неба они выглядели максимально внушительно, и я не без благоговения подумала, что некоторым из этих отложений более двухсот миллионов лет.

Вы когда-нибудь задумывались о том, каким наш мир видится морю, лесу или солнцу? Растянувшиеся за стеклом горные хребты величественно смотрели на меня с высоты птичьего полета. В свете полуденного солнца, они были изумительны. Большинство встретившихся в дороге гор появилось еще до окончания Юрского периода. Возникли в виде острова и формировались на протяжении тысячелетий, постепенно обрастая разломами и прогибами. И, все-таки, даже после этого крымским горам понадобилось еще около двадцати миллионов лет, чтобы стать картиной, которую мы привыкли сегодня видеть – утонченные, сказочные вершины, размашисто обрамляющие полуостров. Ни один изгиб, ни один надкол не повторялся, а присмотревшись внимательней, можно заметить не только разницу в камне, но и разницу в песке, что его окружает. Каждая из проплывающих за окном гор была уникальна и так прекрасна в своей непохожести.  

Двадцать миллионов лет.

Эта цифра и по сей день не прекращает меня поражать. Приходит в голову каждый раз, когда я касаюсь взглядом каменных вершин. Двадцать миллионов лет. Именно столько времени понадобилось природе для завершения одной из своих лучших работ. Сколько книг можно написать за это время? Скольких людей полюбить? А самоубийства? Сколько раз можно возненавидеть жизнь, полюбить ее снова и опять разрушить?

Двадцать миллионов лет.

Горы возникли в этом месте задолго до моего рождения. Они сформировались прежде, чем появился интернет или начались полеты в космос, задолго до возникновения психиатрии и до того, как мой диагноз стал отдельной нозологической единицей, которую Эмиль Крепелин окрестил маниакально-депрессивным психозом. Их дремлющие в дымке вершины видели динозавров, эволюцию, формирование современной флоры и фауны. Горы застали инквизицию, темные времена, охоту на ведьм и крестовые походы. А первый человек, которому открылись эти пейзажи, наверняка полагал, будто наша планета плоская и расположена на треххоботных млекопитающих, которые, в свою очередь, стоят на панцире одного немыслимых размеров пресмыкающегося.    

В общем, горные пики возвышались в этих краях задолго до основания городов, изобретения языка и появления человечества. Мне нравилось думать о том, что горы останутся здесь и спустя тысячи лет после того, как меня не станет. Они никуда не денутся, когда мой пепел растворится в морском ветре. По какой-то странной причине, эта мысль меня утешала. Что бы ни случилось со мной, с вами, с городами, в которых мы живем и с людьми, которых мы любим, приковывающие взгляд горные долины по-прежнему будут возвышаться над этими дорогами в своем невозмутимом спокойствии.

Удалось ли бы мне написать что-нибудь настолько же дивное и бесподобное, будь в моем распоряжении так много времени?  Я еще раз обвела взглядом открывшийся из окна пейзаж и решительно покачала головой. Нет, никаких миллионов лет не хватит на то, чтобы тягаться с природой.

До въезда в Симферополь оставались считанные минуты, когда у автобуса вдруг спустило колесо. Мчался он на всех порах, так что теперь кабину раскачивало из стороны в сторону. Вслед за непредвиденным сбросом скорости, горстка безделушек, сигаретная пачка, а также многочисленные крупные и мелкие купюры взлетели в воздух. В сопровождении прочих вещей, лежавших на водительской панели, они стремительно разлетелись по салону. Заброшенные на полки сумки моих попутчиков тоже не отставали. Они с грохотом приземлялись на пол, в то время как автобус продолжало заносить на склоне. 

Общую картину ничем не обещанного хаоса дополнил плач ребенка дошкольного возраста. Им оказался кудрявый мальчик в клетчатых штанах с подтяжками, чье место находилось передо мной. Ребенок неслабо ударился об оконное стекло сразу после того, как шина дала трещину. Поле удара у малыша не хватало переднего зуба, что он радостно демонстрировал побледневшей от испуга матери. И мне.

– Вы его не подержите? – произнесла женщина.

Я не сразу поняла, что она обращалась ко мне, ведь кому может прийти в голову доверить ребенка человеку вроде меня?

– Кто? Я?

– Угу, – протянула мать мальчика.

– Не думаю…

Не думаю, что это хорошая идея, собиралась сказать я. Но незнакомка усадила ребенка мне на руки еще до того, как я успела произнести и треть реплики. Она улыбнулась мне быстрой, но благодарной улыбкой, и вместе с другими пассажирами исчезла в проходе в поисках упавших куда-то сумок.

Короче говоря, автобус сошел с дороги, а внутри него стоял настоящий переполох. Пассажиры, во главе с водителем, метались по салону, пытаясь отыскать свое имущество. Многие из них ругались друг с другом, эмоционально размахивая в воздухе конечностями. Некоторые уже начинали звонить своим близким. Они рассказывали одну и ту же историю и, что было мочи, старались перекричать других звонивших. Говорили, что на въезде в город у автобуса спустило колесо и просили людей по ту сторону трубки чуть больше времени провести на вокзале. К их голосам подключились встревоженные дети. Их было не меньше восьми единиц на автобус. Вначале один за другим подняли рев груднички. Вслед за ними раздался чуть более осознанный плач, исходивший откуда-то из хвоста автобуса. Всего полминуты, и к хору ноющих детей добавилось еще несколько голосов. Кто-то из них без конца жаловался на жару, топал ножкой и требовал мороженного. Кто-то откровенно истерил, наполняя своим визгом кабину автобуса и параллельно подначивая остальных детей заняться тем же. 

Последней в ряды раскисших тем днем вступила круглолицая девочка в очках-звездочках, надетых поверх волос, сплетенных в два высоких хвостика. Похоже, выглядела она чуть старше своих лет: фигура ребенка смотрелась так, словно через пару-тройку месяцев законодательство позволит ей заниматься сексом, тогда как одежда и прическа красноречиво говорили о том, что девочка только готовилась вступить в подростковый возраст.

И, все же, лифчик бы ей не помешал, подумала я.

В общем, Очки-Звездочки перекинулась парой слов с сопровождающим ее пожилым мужчиной. 

(Я очень надеялась, что имя тому не Гумберт.)

Затем она о чем-то долго просила сидевшего рядом старика. Похоже, безуспешно потому, как уже совсем скоро девочка вцепилась в собственные косы и оперативно впала в истерику. И, хотя она сидела в соседнем ряду, я не смогла разобрать ни единого слова. Голос девочки моментально слился с общим гулом, который все это время старательно поддерживали собравшиеся в автобусе дети. Правда, теперь мне начинало казаться, что некоторые совершеннолетние слабонервные также присоединились к образовавшейся какофонии. 

Обеспокоенная старушка справа от меня что-то спросила. Ей пришлось повторить свой вопрос еще раз, а затем еще один. Старушка старалась говорить громко, но ее голос исчезал под гнетом общего стона. Мне практически пришлось читать слова по губам.

– Когда вернется водитель? – спрашивала она.

В ответ я развела руками. Тогда она опять что-то спросила. Кажется, это было:

– А где он? 

Водитель ушел звонить диспетчеру около десяти минут назад, но до сих пор не вернулся. Похоже, он это предвидел, потому как дверь выхода из автобуса оказалась заблокированной. Между тем, находиться в салоне становилось невыносимо. Без проветривания воздух обратился чем-то затхлым, так что дышать становилось все труднее. Одежда моментально прилипла к мокрому телу, а пот градом катился вдоль моего позвоночника.      

Спустя еще десяток очень жарких и медленно протекающих минут, место у руля все так же пустовало. Водитель и впрямь куда-то запропастился. Теперь это начинало напрягать многих, включая моего внутреннего нытика. Шум рос и рос в геометрической прогрессии. Единственным, кого устраивала сложившаяся ситуация, оказался мальчик в клетчатых штанах с подтяжками. Он первым отказался от этой затеи со слезами. Отсидев у меня на коленках положенное время, мальчишка смирно перебрался на руки матери, откуда все с той же с неиссякаемой гордостью продолжал демонстрировать мне дырку на месте зуба. Должно быть, в глазах малыша, подобная потеря делала его взрослее.

На самом деле, в автобусе был еще один пассажир, который плевать хотел как на незапланированную задержку в пути, так и на парилку, моментально образовавшуюся в салоне автобуса. Все это время Вениамин монотонно похрапывал, уложив голову мне на плечо. Как и следовало ожидать, попытки его разбудить оказались безуспешными. Как бы сильно не трясло автобус, как бы громко не ссорились пассажиры и как бы звонко не плакали дети, лицо моего мужа не выражало ничего кроме спокойствия. Веня не проснулся даже когда я поднялась со своего места и направилась к выходу, полная решимости открыть эту чертову дверь.

– Приехали? – сквозь сон спросил он и, не дожидаясь ответа, продолжил смотреть свои сны.

Кнопка аварийного выхода сработала незамедлительно. Двери автобуса разошлись, впуская в салон потоки свежего горного воздуха. Я вышла ему навстречу и, вдоволь надышавшись, опустилась на траву, что росла подле обочины. Шея ныла, голова раскалывалась, а глаза вот-вот обещали лопнуть: я не спала с того момента, как обнаружила себя на балконе, и это уже понемногу начинало сказываться на моем самочувствии. Долго не думая, я улеглась на землю и, заложив руки за голову, продолжила рассматривать окружавшие меня горы, скалы, долины и все то, что было среди них.

Одна мысль не давала мне покоя. Та самая, что всю дорогу дрыхла под боком и уже завладела моим сердцем. 

*Что мне делать с Вениамином?*

*Ничего. Мне нужно уйти. Я не могу уйти.*

*Что мне делать с Вениамином?*

*Не могу его бросить.*

*Что мне делать?*

*Сойду с ума, если не уйду. А если уйду – тоже сойду с ума.*

*Так что мне делать?*

*Ничего. Просто смотри на горы.*

И я смотрела.

