# &nbsp; {#chapter-58}

– Так что же изменилось? – продолжала спрашивать я, отправляясь обратно в спальню.

Нужно признать, перспектива, что писательский запал уйдет так же быстро, как и пришел, начинала меня тревожить.

На этот раз я позволила себе зажечь в комнате свет. Он бы все равно не смог разбудить Вениамина, даже если бы в светильнике оказалась не одна, а сто одна лампочка. За окнами уже стояла глухая ночь – мое самое продуктивное время суток. Терять драгоценные минуты не хотелось, так что я поспешила укрыть Вениамина одеялом, продолжая настойчиво размышлять о природе настигших меня перемен.

Тем не менее, мне показалось, что этого мало, и я склонилась над Веней, заботливо подоткнула одеяло, а затем даже умудрилась подсунуть ему под голову подушку. Уже собиралась возвращаться к работе, но мимо воли застыла около этого мирно посапывающего тела. Во сне Вениамин выглядел таким спокойным. Он совсем не был похож на того обезумевшего мужчину, который позволил себе…

Но я так и не смогла закончить это предложение. Как выяснилось, мне было сложно признаться в произошедшем даже себе самой. У меня совершенно не получалось называть вещи своими именами. Сколько ни старалась, я просто не смогла заставить себя закончить последнюю фразу. 

В общем и целом, мое состояние оставалось стабильным. Было горько, грустно и до скрежета в зубах обидно. К тому же, в этот и без того малоприятный коктейль добавилось невесть откуда взявшееся чувство вины. В чем конкретно нужно себя винить было не совсем ясно, но это вовсе не усмиряло охватившего меня ощущения. Я чувствовала себя так, словно накануне совершила какой-то гнусный поступок и теперь очень этого стыдилась. Вот только никаких поводов для стыда у меня не было, ведь это не я провела ночь, бросаясь оскорблениями и распуская…

Я постаралась отмахнуться от вновь накинувшихся на меня депрессивных дум. Получилось, конечно, так себе.

Еще и эти проклятые фразы, которые я никак не могла закончить. Они все крутилась и вертелась в моей голове, не желая убираться прочь. И вот, когда я подумала, что на большую подлость мое подсознание не способно, звонкий голос Вениамина перекрыл все остальные мысли. 

*Я слышал, что в таком случае мысли надо озвучивать*, сказал голос.

Полный ласки и любви, он так поразительно отличался от того пропитанного ненавистью крика, что я слышала совсем недавно и который до сих пор стоял у меня в ушах. Это был голос мужчины, которого я любила. 

*Когда ты не можешь с чем-то свыкнуться*, надо это произнести. 

Я не сразу вспомнила, при каких обстоятельствах слышала эти слова.

*Ты услышишь собственную мысль несколько раз и быстрее поймешь ее смысл.*

Затем это произошло, и новая волна боли накрыла мое сердце.

*Давай же, попробуй! Скажи, что ты теперь невестушка!*

Тишину спальни нарушил стон нового триггера моей депрессии. Он проворчал что-то нечленораздельное и перевернулся на бок. Теперь Вениамин лежал лицом к свету, что позволяло разглядеть на нем каждую морщинку, каждый волосок и каждое покраснение, что непременно проступало на коже после алкогольной интоксикации. Я пристально всматривалась в венины черты, подолгу задерживая взгляд на той или иной части тела. Но как ни старалась, ничего нового мне так и не открылось. Спящий на полу мужчина вновь был человеком, которому я отдала свое сердце. Ясное дело, в его лице мне не виделось ничего чужого. Тогда я положила голову на плечо Вениамина, но и его запах был все тем же родным. 

Продолжая беспорядочно рассматривать спящего, я в тайне надеялась найти что-то важное. Какую-нибудь незаметную деталь, что поможет расставить все по своим местам. Меня не покидало ощущение, словно я что-то упускаю, и я изо всех сил напрягала извилины в попытках выяснить, что именно. 

В этот момент голос Вениамина во второй раз нарушил тишину нашей спальни. Он звучал гораздо четче, и на этот раз мне удалось разобрать слова. 

– Люблю тебя, Васляева, – чуть слышно произнес Веня.

Некогда такие желанные, теперь эти слова не вызывали в моей душе ничего кроме гнева. Они возвращали к событиям прошлой ночи быстрее любого гипноза. Я тупо смотрела на мужа, особо не отдавая себе в этом отчета. Так прошла четверть часа, в ходе которой я уже ничего не пыталась понять. Просто сидела на полу в ожидании того момента, когда удушающая меня депрессия слегка ослабит хватку, чтобы я могла встать на ноги и провести остаток ночи без истерик.

Наконец, я поднялась и бросила последний взгляд в сторону спящего тела. Будто почувствовав на себе мой взгляд, Венька плавно поднял краешки губ и улыбнулся сквозь сон. Если не считать закрытых глаз, эта улыбка ничем не отличалась от той, что встречала меня каждым новым утром. 

Каждым, кроме сегодняшнего, напомнил мне внутренний голос.

Тем временем улыбка на губах мужа шире. Он еще пару раз произнес во сне мое имя, но это было вовсе не обязательно. Мне хватило одной улыбки, одной блядской теплой улыбки, увидев которую я вдруг осознала, что все так же сильно люблю этого растянувшегося на полу алкоголика. Теплившаяся во мне любовь никуда не исчезла. Просто забилась в угол, почувствовав опасность. Как бы меня это не злило, любовь к Вениамину Ларионову по-прежнему была сильнее всех тех чувств, что я когда-либо испытывала. Она скрывалась в каждом атоме моей души и, казалось, вовсе не планировала сокращать свой пыл. Становилось ясно, что даже мой возлюбленный едва ли может как-то на это повлиять. 

Он же смог… Он просто взял и сделал со мной все это. 

Без предпосылок и предупреждений. Разве можно любить после такого?

Как оказалось, можно и более чем, отчего на душе становилось еще гаже. Я не заметила, как по щеке сползла первая слезинка. Застывшая внутри меня пустота исчезла под новой волной боли, от которой хотелось кричать, пока не сядет голос.

С этими размышлениями я вернулась на кухню.

*Скажи это*, спокойно настаивал внутренний голос, пока я шла по темному коридору. *Скажи это* – эта фраза звучала в моей голове каждый раз, когда в памяти всплывали ночные ужасы.

*Скажи это. Просто скажи.*

Любовь оказалась не единственным сильным чувством, возникшем в моей душе благодаря Вениамину. Последующие за ней эмоции оказалась не менее значительными. Вскоре я уже без особого удивления осознала, что никогда прежде не знала столь яркой боли, что без устали душила меня изнутри вот уже не первый десяток часов. Помимо всего прочего, она несла с собой целый букет леденящих душу воспоминаний. Некоторые картины сплывали в памяти всего на пару секунд, сверкнув заревом вспышки. Иные же – вроде Вениамина, занесшего руку перед ударом или этого презрительного взгляда стальных глаз – просто застывали перед мысленным взором. Картины вроде этих были самыми невыносимыми. Они вовсе не хотели исчезать, и часами стояли перед глазами, таскаясь за мной мертвым грузом.

Такие картины делали мою жизнь невыносимой. А мою прозу – живой.

*Давай же, попробуй! *

Что-то подобное происходило со мной и сейчас. Пальцы инстинктивно сжимали карандаш, который я до сих пор держала в руке. А боль все нарастала. Казалось, она уже не может быть сильнее, но флешбеки минувшего вечера с неумолимой скоростью всплывали в моей голове. Они были слишком реалистичными и никак не позволяли забыть хотя бы крохотную часть того, о чем так не хотелось помнить. 

*Скажи это. Скажи это. Скажи это.*

И я не просто сказала, я это из себя выплюнула. Первая фраза оказалась самой сложной, но, покончив с ней, я уже могла выдала остальное.

– Мужчина, которого я люблю… Вчера он… Он поднял на меня руку? – спустя множество заминок и внутренних пререканий произнесла я. 

Вышло как-то неуверенно. Как будто я то ли задаю вопрос, то ли ставлю сказанное под сомнения. Оно и не удивительно! Какая-то часть никак не могла в это поверить. Не знаю, стала ли тому виной гордость, а, может, это было лишь следствие обрушившегося на меня шока, но что-то внутри наотрез отказывалось принять правду. В добавок ко всему, в моей голове еще вчера поселилась новая упрямая мысль. Она помогала игнорировать произошедшее, с жаром заверяя, что подобные вещи не случаются – ну просто не могут случиться – с такими как я.

Домашнее насилие – это удел домохозяек. Оно касается робких женщин, что слепо прислуживают своим мужчинам, слабовольных жен, полностью отдавших себя во власть мужьям, выходцев из неблагополучных семей, которые просто не знают о существовании других моделей отношений, и так далее и тому подобное. Разве что-то из этого хоть как-то связано с Елизаветой Васляевой – феминисткой в восьмом поколении, способной заткнуть самого Жириновского? – несмотря ни на что, даже сейчас эта мысль казалось мне куда правдоподобней предыдущей.        

С этим нужно было что-то делать. Я решила попробовать еще раз.

*Скажи это.*

– Мой муж поднял на меня руку, – без малейших признаков эмоций объявила я.

*Умница. А теперь скажи эти слова так, чтобы ты сама смогла им поверить.*

– Мой муж поднял на меня руку. Мой муж поднял на меня руку. Мой муж поднял на меня руку. Мой муж поднял на меня руку…

Мне понадобилось произнести эту фразу раз двадцать, чуть ли не вытягивая слова пинцетом. Только после этого я смогла принять их содержание. Но все так же не соотносила эту ситуацию с собственной жизнью.

– Мой муж поднял на меня руку. Мой муж поднял на меня руку. Мой муж… Вчера Вениамин ударил меня. Он бил меня по лицу и таскал за волосы. Мой муж швырнул меня в стену и отвесил пощечину. Всего одну, это же не считается? Просто пощечину какую отвешивают при истерике. В этом нет ничего страшного, со мной случались травмы и похлеще. Да, всего одну, но должны были быть еще пощечины. И они бы были, не подскочи я вовремя. Потом он вырвал мне клок волос и сжал руку с бешеной силой. И как ему удается избегать отметин синяками? А еще он постоянно оскорблял меня. Ну, называл всеми теми словами, на какие только стало воображения. И почти все время кричал, – я громко выдохнула, после чего сделала глубокий вдох и продолжила: – Прошлым вечером Вениамин поднял на меня руку. Он таскал меня за волосы, бил по лицу и не только. Мой муж все время выкрикивал мне в лицо оскорбления. И он… Он несколько раз душил меня. А еще был секс. Он пытался сделать это без моего согласия.

*Ты что, боишься меня?*

*Да ладно, я думал ты любишь по-жесткому!*

На этот раз передышка потребовала больше времени. Произносить подобные вещи оказалось гораздо сложнее, чем мне представлялось. Сдерживать слезы с каждым словом становилось все труднее, ровным счетом, как и перечислять события минувшей ночи. Вначале это были просто слова, но в какой-то момент я поняла, что чем больше их повторяю, тем сложнее мне это дается. Казалось, фразы наполнялись смыслом лишь после того, как я их произносила, и вскоре я уже не могла говорить отстраненно. 

– Вчера муж жених поднял на меня руку, – в третий раз начала я.

Сейчас эта фраза звучала вполне правдоподобно. Я даже слегка покрутила ее на языке, с удивлением думая о том, что вчера муж действительно поднял на меня руку, и был таков. На протяжении всех этих монологов я не прекращала сжимать в пальцах карандаш, и делала это со всеми задатками будущей невротички.

– Мужчина, которого я люблю всей душой, не раз причинил мне физическую боль. Прошлым вечером он швырнул меня в стену, отвесил пощечину, таскал за волосы,  и душил, но… – я неожиданно поняла, что это не самое страшное. – Но хуже всего не это. Хуже всего то, что он делал все это без каких-либо причин, без предупреждения. Вениамин предал меня. Он выбрал момент, когда я была максимально уязвима, а затем…

Стоило мне это произнести, и слезы ручьем хлынули из глаз. Картинка перед взглядом то и дело расплывалась. Кухонный натюрморт вскоре обратился каким-то странным абстракционизмом, но я решила, что глупо останавливаться на половине дела.  

– Человек, которому я решилась открыть душу, просто взял и ударил меня. Он ничем не объяснил свое поведение. Только нес бред об изменах и интригах, которых никогда не было. Откровенный бред! Вчера мужчина, которого я люблю, не раз сжимал мою шею до хрипоты и головокружения. Там были алые следы его хватких пальцев. Такие же, как и на моем запястье. Он все кричал и кричал, бросаясь в меня бесконечными оскорблениями. Черт, он ведь даже переходил на личности! Вениамин намеренно пытался задеть меня за живое, называя дерьмовым писателем. 

Тем не менее, ничто из этого глупого списка, ни один из причисленных ушибов, не мог сравниться с по-настоящему пугающей болью, что теперь жрала меня изнутри. После такой в душе не остается ничего, даже отблесков надежды. А самым страшным было то, что эту боль мне причинил не кто-то там. Это сделал мой жених, мужчина, которого я любила каждой веной своего сердца. Человек, ради которого я переехала в другую страну, оставив позади семью, собак, друзей, работу, свой дом… Да все, что можно было оставить.

*За что?*

Перебравшись в Севастополь, я оказалась предоставленной самой себе. Здесь у меня не было ни одной родной души, ни одного приятного собеседника или хотя бы хорошего знакомого. По сути, Веня оказался всем, что у меня было. Он был моим лучшим другом, моим любовником и моим возлюбленным. С ним я всегда оставалась честна, а потому разразившийся прошлой ночью скандал так сильно меня шокировал. 

Все это было так неожиданно. Так беспочвенно. И так болезненно. Ввиду никому не ведомых причин, Вениамин выплеснул на меня все, на что оказался способен. Собравшаяся за последние сутки боль бурлила и приумножалась, подкрепляемая по-детски искренним, возможно, даже тупым непониманием происходящего. Он и впрямь предал меня, не особенно задумываясь о последствиях, а я даже не знала, за что.

«За что?!» – теперь это был единственный вопрос, оставшийся без ответа. Чем сильнее я пыталась найти этому объяснение, тем глупее себя чувствовала и вскоре с новыми силами начинала злиться на дрыхнувшего на полу спальни мужчину. Но ярость быстро улетучилась, оставив меня лицом к лицу со стремительно возрастающей болью. 

Последняя, словно, уже жила отдельной жизнью. Казалось, еще немного, и эта боль вырастет настолько, что больше не сможет уместиться в моей душе. Интересно, что же тогда с ней будет?

