# 59 {-}

Горький ком подступил к горлу. Я приложилась губами к чашке с чаем, не обращая никакого внимания на бьющие ключом слезы. Поначалу еще как-то пыталась их стряхивать, но довольно быстро поняла всю бесполезность этой затеи. Выступавшие слезинки скатывались по щекам, но на их месте тут же появлялись новые. Соленые капли появлялись в уголках моих глаз даже раньше, чем их предшественницы успевали достигнуть подбородка.

Карандаш, который я до недавнего времени неосознанно сжимала в ладонях, покатился вдоль подоконника. Затормозил у левого края и теперь лежал в компании прочей канцелярии, ожидая следующего творческого наводнения. Или очередной истерики, плавно переходящей в затяжную депрессию.

– Да ну сколько можно! – нетерпеливо протянула я, почувствовав, что на подходе очередная партия слез.

Никогда бы не подумала, что человек может так долго плакать. По моим подсчетам, слезы должны были иссякнуть еще несколько часов назад. А они все выливались из глаз, подгоняя друг друга в своей последней гонке. Тем не менее, кое-что начинало меня напрягать: как выяснилось, чем дольше я плакала, тем сложней мне потом было этого не делать.

И я с силой сжала руку в местах самых заметных повреждений. Опухлости тут же заныли под натиском пальцев, что только заставило меня усилить хватку. Как и прежде физическая боль сделала свое дело. Она отвлекала от терзающих душу мыслей и уже через каких-то десять-пятнадцать минут на моем лице не было ни единой слезинки.

– Всегда работает, – сказала я.

Затем взглянула в зеркало. Увиденное меня, в общем-то, удовлетворило. Теперь мне не оставалось ничего, кроме как завалиться в постель, которая непременно окажется холодной без спящего в ней Вениамина.

Имя мужа вот-вот обещало вызвать приступ предрассветной меланхолии. 

И тут меня осенило.

– Неужто дело только в этом? – с едва различимым разочарованием в голосе спросила я. 

И тут же решила, что есть только один способ все прояснить. Так что, я подхватила с подоконника карандаш и блокнот, одним глотком опустошила чашку, и вошла в утренний полумрак спальни.

<div style="text-align: center;">***</div>

Теперь мой избранник лежал на другом боку, и это было единственным изменением в спальне. Семи минут в его компании вполне хватило на то, чтобы вывести меня на начальную, предистеричную стадию. Слезы уже вовсю заливали лицо, спускалась по шее и исчезали под халатом, оставляя соленые отпечатки на его внутренней стороне.

– Я так тебя люблю, – повторил Вениамин.

За то короткое время, что я находилась в спальне, он не раз успел произнести эти слова, чем заметно ускорил ход моего эксперимента. Само собой, все эти признания любви, сказанные им во сне, не несли в себе никакого негативного подтекста. Они звучали естественно, как звучали и сотни раз до этого, когда Веня прижимал меня к себе и повторял, как сильно он меня любит. Нет, в сказанной муженьком сквозь сон фразе не было ничего необычного. Именно это меня и задевало.

Жуткая мысль посетила меня. 

*Что если так теперь будет всегда?* 

Что если слезы, досада, обида и, самое главное, эта до ужаса острая боль в груди будут появляться каждый раз, когда он скажет, что любит меня?

Затем я попыталась подсчитать, как часто я слышу от Вени любовные признания, но довольно быстро отказалась от этой затеи. Лишь по утрам я слышала о любви с добрых пять раз. Пять приступов за сутки – это уже много, что же говорить о других отрезках дня?

– Жуть то какая получается! – подытожила я, не придавая особого значения тому, что говорю вслух.

– И я тебя, – голосом, полным энтузиазма, отозвался Вениамин.

При других обстоятельствах, это показалось бы мне забавным. Возможно, даже комичным, будь на душе так горько. Да что за сны такие ему снятся?

Нет, так не пойдет, наконец, произнес внутренний голос. 

Он всегда был практичней и гораздо спокойней моего собственного. Это был классический баритон успешного психотерапевта. Тщательно выработанный и отшлифованный, он вызывал у слушателя полное доверие. Ни для кого не секрет, терапевты частенько пользуются такого рода приемами. Считается, что верно подобранный голос не только помогает найти подход к пациенту, но и способствует тому, чтобы услышанная на сеансе информация отложилась в его или ее подсознании.

Все это уже давно не было для меня секретом, чего нельзя сказать о происхождении моего внутреннего голоса. Хотя его нотки и звучали в точности как у опытного терапевта, они не были похожи на голоса всех тех мозгоправов, с которыми я когда-то сотрудничала. К тому же, в отличие от их голосов, этот не был болтлив. Он был со мной сколько себя помню и всегда оказывался прав.

Если не прекращу плакать от его любовных признаний, я сойду с ума гораздо быстрее, чем мне это представлялось.

– Люблю, – стоял на своем Веня.

Хотя с другой стороны…

Вопрос о том, что именно ему снится, начинал интересовать все больше и больше.

*Какие сны в том смертном сне приснятся, когда покров земного чувства снят?* 

Словно почувствовав, что старым репертуаром здесь никого не впечатлить, мужчина разжился еще парочкой вырывающихся из сна фраз. Некоторые из них оказалось вопросами и уже до тошноты успели надоесть.

С другой стороны, это даже может сыграть мне на руку.

– А ты меня? – спросил Веня. – Ты правда меня любишь?

*Уходи от него, Лиза.*

Выходя из спальни, я поняла, что совсем потеряла счет времени. Я понятия не имела, как долго я пробыла этой тусклой комнатке, и не видела причин, по которым это могло бы меня волновать. Еще с полсотни страниц я вряд ли смогу выдать, – я и без того никогда не писала так много и за один присест – а остальные занятия меня мало интересовали. Оставалось лишь сидеть на подоконнике и лениво наблюдать за тем, как над городом поднимается очередной денек.

*Беги прямо сейчас и не оглядывайся. Другого шанса не будет.*

Но я оглянулась.

Уже сжимала в пальцах дверную ручку, когда все тот же вопрос прозвучал за моей спиной.

– А ты меня? – правда, теперь в нем отчетливо слышались нотки печали.

– И я тебя, – наконец, ответила я, выскальзывая в коридор.

Думаю, этого было достаточно.

<div style="text-align: center;">***</div>

Когда солнце взошло над Севастополем, мой блокнот пополнился еще двадцатью тремя страницами, заполненными мелким почерком. Я умостилась на подоконнике и изучала их с неподдельным интересом, словно рассматривала диковинную вещь, какой никогда не видела прежде.

– Так вот оно что, – протянула я, все еще не решаясь довериться своим глазам на все сто процентов. – Неужели все и впрямь так просто?

Теперь я знала, почему так долго находилась в творческом застое. Ступоре, от которого никак не удалось избавиться. 

Что ж, моя жизнь никогда не было идеальной. Ее и простой то не назовешь, но временами, когда мозг не был заражен вирусом депрессии, мне думалось, что в этом и кроется прелесть бытия. Так или иначе, мое существование всегда несло в себе душевные терзания. Как бы долго и усердно я с этим не боролась, внутри всегда оставалась боль. Временами ее было слишком много, временами чуть меньше, но, сколько бы ее ни было, душевная боль никогда полностью не покидала меня. По иронии судьбы, писательство оказалось единственной сферой деятельности, на которую никак не могло повлиять мое психическое расстройства. Как бы плохо мне не было, я могла писать свои книги в любом состоянии, даже когда находилась в середине самых тяжелых фаз биполярки. 

Вместе с тем, я вдруг поняла, что все мои лучшие произведения были написаны на пике депрессий. Более того, именно благодаря писательству я не раз вытаскивала себя из этого состояния. Почему я прежде об этом не задумывалась? Ведь все литераторы без умолку твердят о том, что боль – это хлеб поэта, так что же я раньше этого не заметила? 

Или заметила?

Но я знала ответ на этот вопрос. Я ничего не заметила просто потому, что и знать не знала, что могу чувствовать себя как-то иначе. На протяжении долгих лет и до недавнего времени, момент, когда ты впервые перечитываешь только что законченную рукопись и понимаешь, что она идеальна, был для меня самым счастливым. Ситуация переменилась весной этого года. Где-то между тем днем, когда я впервые упала в объятья своего будущего мужа и тем вечером, которым приняла его повторное предложение.

Наконец, мне все стало ясно. Мне нужно было страдать для того, чтобы писать, и чем больше я страдала, тем лучше был результат. Как бы странно это не звучало, но типичная депрессия стала для меня лучшим катализатором творчества. Находясь в подавленном, нестабильном или эмоционально уязвимом состоянии, я могла найти покой только в компании карандаша и нескольких пустых страниц. Большего мне не было нужно.

Выходит, все слова о том, что я никогда раньше не чувствовала себя такой счастливой, были абсолютной правдой. Эта мысль вызвала на губах улыбку. Разумеется, в моей жизни случались хорошие моменты, но все они были слишком быстротечны. По-настоящему же счастливой я почувствовала себя не так уж и давно.

– Иногда мне кажется, что это просто плата за талант, – однажды сказал мне Адам, – и мне суждено провести жизнь в одиночестве.

Такая мысль не раз посещала меня, но я старалась не воспринимать ее всерьез. Иначе можно просто свихнуться.

Страдать ради искусства или жить счастливо, но без него – не самый простой выбор для человека вроде меня. Правда, в моем случае, выбор временами отсутствовал, ведь биполярное расстройство еще никто не отменял. Мой диагноз оставался без изменений, так что я и думать забыла о таких вещах как постоянная гармония и всеобъемлющее счастье. 

*Быть или творить, вот в чем вопрос.*

К тому же, даже если бы мне выпал шанс сделать подобного рода выбор, я бы вряд ли остановилась на первом варианте. И не только потому, что я по умолчанию не могу быть счастливой, когда жизнь лишена искусства. Счастье, оно ведь так непостоянно! Большинство тех, кто когда-то мог меня осчастливить, рано или поздно оказывались способными огорчить меня с не меньшей силой. Люди так часто меня обижали и разочаровывали, что сам выбор в их пользу стал казаться мне редкостной глупостью. 

Что же касается искусства, оно никогда меня не предавало. В отличие от людей, которых я так любила, искусство оставалось со мной даже в самые темные времена. 

*Быть или творить?*

– Когда-нибудь у меня получатся оба варианта сразу, – произнесла я, пытаясь утихомирить внутреннего Гамлета. – В такое верится с трудом, но однажды я приду в себя и поработаю над этим. 

Если не суициднусь, конечно.

Солнечные лучи фамильярно проникли сквозь кухонное окно и тут же разбрелись по стенам. Выставив голые ноги навстречу приближающемуся теплу, я продолжала сидеть на подоконнике. Силы окончательно иссякли, так что мне уже точно ничегошеньки не хотелось, – ни быть, ни творить – но сна по-прежнему не было видно.

Картавый голос Бродского как нельзя кстати раздался в моей голове.

*Я сижу у окна. Я помыл посуду.*

– Я был счастлив здесь, и уже не буду, – автоматически ответила я прежде, чем до меня успел дойти смысл сказанного.
