# &nbsp; {#chapter-6}

За окном моросил октябрьский дождь две тысячи тринадцатого года выпуска, отчего внутри становилось крайне уютно. Обернувшись одеялом, я сонно смотрела в окно. Передо мной стояла чашка кофе, кола и наполовину пустая бутылка виски. По ту сторону стекла уже начинало темнеть, и я наблюдала, как в окнах соседних домов зажигаются огни. Одно за другим. Прямо как в детстве, но без виски, разумеется. До шестнадцати я пила только вино.

С минуту я разглядывала стоявшие на подоконнике жидкости, после чего потянулась кофе. Любовь пагубно влияла на мой алкоголизм.

За моей спиной скрипнула дверь. Обернувшись, я увидел, стоявшего в дверном проеме Адама. Дождь к тому моменту усилился, и мужчина уже стягивал с себя промокшую до нитки куртку. Несмотря на это, выглядел он как никогда очаровательно. На губах играла мечтательная улыбка, а карие глаза сияли, делая взгляд еще более выразительным. Не говоря ни слова, Адам подошел ко мне и, опустившись напротив, коснулся своими губами моей руки.

До этой минуты я и подумать не могла, что такой банальный и даже старомодный жест способен вызвать во мне целую бурю эмоций. Но он вызвал. Я смущенно улыбнулась, и Адам улыбнулся в ответ. Своей самой широкой улыбкой, открывающей ямочки на щеках. Забыв о кофе, я коснулась рукой темных волос, что вскоре начнут доставать до плеч, и вновь улыбнулась. На этот раз куда шире. 

Адам поцеловал меня, и я вдруг осознала, что люблю его.

Той ночью ни один из нас не смог уснуть. Сначала мы были слишком заняты для такого скучного дела, а затем…

– О чем ты думаешь? – спросил Адам, когда я собрала растрепавшиеся волосы и растянулась на подушке.

Я повременила с ответом.

– Я думаю о том, что в бутылке подозрительно много виски как для пятничного вечера.

Адам вздохнул.

– Не хочешь говорить?

– Пожалуй, нет, – медленно ответила я, ласково взглянув на своего собеседника.

Он обхватил меня за плечи и крепко поцеловал.

– А теперь?

Я мужественно молчала. 

– Нет, ну так не честно! Я думал, мы договорились говорить друг другу всю правду, – Адам обиженно отодвинулся от меня. – Милая, ты заставляешь меня нервничать.

Так себе аргумент как для двадцатипятилетнего мужчины, но я и правда не знала, что ответить.

– Не думаю, что сейчас подходящий момент.

Десятисекундная пауза.

– Так о чем? – вновь спросил Адам и я сдалась.

– Думаю, я люблю тебя.

После этой фразы Адам молниеносно изменился в лице. Позже он утверждал, что знал, что я скажу именно это. Более того, он так настаивал именно потому, что думал, что сможет ответить мне тем же. Однако, в последний момент вдруг понял, что не сможет – вся суть мужчин.

– Мне нужна сигарета, – отрезал Адам и покинул постель.

С этого момента наши мимолетные отношения круто переменились. Адам стал первым мужчиной, к которому я питала сильные чувства во взрослом возрасте. Конечно, мне было всего девятнадцать, но неплохой рабочий стаж, несколько написанных книг, вовремя уплаченные налоги и уйма забот позволяли мне считать себя взрослой. 

Мы расстались спустя полтора месяца. Тем приятным погожим днем, когда я меньше всего этого ожидала. Без криков и прочих тягостных выяснений отношений. Он ушел, а я проплакала всю ночь. К утру замкнулась в себе и перекрасила волосы в алый.

– Нельзя говорить человеку о любви на второй день знакомства! – заявил Адам спустя дня три после этого самого второго дня знакомства. Кстати, формально мы были знакомы куда дольше, но никогда прежде не виделись. – Это ненормально!

Никогда не забуду того, с каким чувством он произнес последнее слово. Ненормально. Словно это было не одно, а целых четыре отдельно существующих слова. Не-нор-маль-но. Так обычно разговаривают с детьми или умственно отсталыми.

Куда делся тот парень, который уговаривал меня дать шанс этим отношениям? В одной из моих книг персонаж по прозвищу Молния чуть не лишается своей возлюбленной из-за того, что признается ей в любви на второй день знакомства. Никто и не знает, насколько автобиографична эта сцена. 

<div style="text-align: center;">***</div>

Теперь же меня занесло в Крым.

Поездка оказалась невыносимо долгой. В какой-то момент я даже уснула, что редко бывает со мной в общественном транспорте. Точнее, попросту отключилась. Сегодня ведь уже ни для кого не новость, что происходящее во сне проносится в мозге за долю секунды? 

Что ж, тем вечером в моей голове пронеслось немало. Проснулась я в тревожном состоянии, и тут же потянулась к часам. Чувствовала себя так, словно проспала часов двадцать. На деле же – тринадцать минут. Вот уж не думала, что освоенная в студенческие годы практика кратковременного сна однажды мне пригодится.

Так вот, проснулась я в тревожном состоянии. Мне снился Адам. Как всегда, сон оказался чересчур реалистичным, так что я не сразу пришла в себя. И пускай выглядела я абсолютно спокойной, внутри уже начинал мельтешить страх отношений. С одной стороны, я всем сердцем хотела полюбить кого-то сильнее, чем когда-то любила своего бывшего. С другой – я боялась этого до умопомрачения. Именно поэтому на протяжении последних трех лет я никому не позволяла сблизиться со мной. Даже поцелуи во время секса были запрещены. Мне думалось, что они вызывают слишком интимную связь, как бы абсурдно это не звучало.

И вот я вновь куда-то ехала. На этот раз без планов о чем-то серьезном и с куда большими надеждами одновременно. От подобных мыслей сердце начинало колотиться так сильно, что становилось сложно дышать.

К тому моменту бутылка виски совсем опустела. Автобус проезжал Симферополь. Он показался мне до невозможности скучным и очень напоминал бесконечную улицу Чигрина – не самый благополучный район моего родного города.

«Спокойно, Васляева, – сказала я себе. – Тебе уже не девятнадцать. Ни в кого ты поспешно не влюбишься.»

Вот она, самая распространенная из всех возможных человеческих глупостей: отчего-то полагать, что ты стал умнее.

