# 60 {-}

Очнувшись ото сна, что занял почти тридцать часов, Вениамин мало что помнил о событиях той злосчастной ночи. 

– Готова ехать? – с привычной бодростью спросил он, подразумевая, конечно же, поездку в Симферополь, которую мы запланировали еще на прошлой неделе.

Само собой, я была не готова. Последние два дня оказались невыносимыми, так что предстоящая поездка, как и множество других вещей, успешно вылетела из головы. Тем не менее, именно о ней в первую очередь заговорил Веня, когда нашел меня сидящей в кресле в окружении блокнота и карандаша. 

До этого момента я не была толком уверена в своих чувствах. Вернее, в том, что от них осталось за последние сорок восемь часов. Вот только стоило мне услышать голос Вениамина, и сердце предательски затрепетало в груди. 

– Ну, надо же, ты снова пишешь! – радостно заметил Веня.

Я ничего не ответила. Медленно подняла взгляд и принялась рассматривать своего возлюбленного. 

Ночь прошла для меня в непрекращающихся слезах и работе над старой задумкой. И как же просто было понимать людей, пускай даже и незнакомых, когда о них пишешь! Что же касалось семейной жизни, на практике это дело оказалось куда сложнее. Я пристально наблюдала за стоявшим у постели Вениамином, не упуская из виду ни один вдох своего мужа, но! Как бы старательно я ни всматривалась в его глаза и сколько бы ни анализировала его поведение – все без толку. Мне не открылось ничего, хоть немного напоминавшего о существовании того второго Вениамина с чужим голосом и стальным взглядом, от мыслей о котором по спине пробегал холодок. 

Нет, с какой стороны ни глянь, передо мной стоял все тот же Венька.

– Что я натворил? – вдруг спросил он.

Этот вопрос поставил меня в тупик. Я открыла рот, чтобы ответить, но так и не смогла выдавить из себя хоть слово. Меня охватил не иначе как ступор. Только уже не писательский, а вполне себе бытовой. Казалось, ничто в мире не смогло бы заставить меня озвучить и половину кипевших в голове мыслей. 

– Неужели ты ничего не помнишь? – спросила я только для того, чтобы хоть что-то сказать.

Естественно, он ничего не помнил.

Вениамин благополучно забывал все сказанное и сделанное еще до того, как пришел в себя. Я видела это, когда он пытался заняться со мной любовью, и слабо верила, что после пробуждения к нему вернется память.

И, все-таки, ответ прозвучал не сразу. Лицо мужчины исказилось в задумчивой гримасе. Все еще без одежды, он опустился в соседнее кресло, прищурил глаза, поджал губы и принялся перебирать в пальцах бороду – классический Вениамин Ларионов в момент глубоких раздумий. Он долго молчал, погруженный в собственные мысли, а затем резко выдохнул. В глазах мелькнула тень испуга, и стало ясно, что кое-что из событий той ночи все же отложилось в его памяти.

Наши взгляды встретились и теперь мы безмолвно смотрели друг на друга. Прямо как тем далеким весенним вечером, когда насквозь промокший под дождем Вениамин вошел в зал ожидания местного автовокзала. 

Память об этом моменте – все еще таком ярком и вместе с тем невозможно далеком – не могла не вызвать во мне печали. Первые слезинки с готовностью возникли на глазах. Они скатились по моим щекам и упали на открытую страницу блокнота, превращая мой и так нечитабельный для простых смертных почерк в настоящие каракули. 

Заметив мои слезы, Веня вынырнул из своих мыслей. 

– Не плачь, деточка, – ласково сказал он. – Прошу, не надо. Тебе ведь нельзя плакать.

*А помнишь, каким он был, когда душил тебя?* 

*Душил до жжения в легких и продолжал пить, кричали голоса в моей голове. *

*Разве тогда ему было дело до твоих слез?*   

С неожиданной робостью, чего я прежде никогда не видела, он коснулся моей ладони. Еще с минутку держал ее, желая убедиться, что я не отдерну руку. Этого так и не произошло, и вскоре Вениамин уже обнимал меня двумя руками, прижимая к своей горячей груди. 

*А помнишь, каким он был, когда бил тебя?*

– Что бы я тогда ни сказал, это не имеет никакого значения, – наконец, произнес он. – Совершенно никакого. Те обидные слова, которые я мог тебе сказать… 

*Отвесил пощечину, швырнул в постель и продолжил орать. *

– Клянусь тебе, это был всего-навсего пьяный бред, не больше! Это никак с тобой не связано, понимаешь?

*А пряди твоих волос? Те, что застряли в оправе его кольца, их-то ты помнишь?*

– В такие моменты ничего не понимаю. Просто не могу себя контролировать…

Голоса внутри меня продолжали стоять на своем, мешая мне успокоиться. Их гул нарастал с каждым мгновеньем, пронзая голову все новыми и новыми приступами мигрени. Я игнорировала этот гул что было сил, но чем больше муж говорил, тем громче становились эти никем непрошеные напоминания. В конце концов, мне показалось, что разыгравшийся в мыслях шум вот-вот перерастет в приступ шизофрении. Он практически затмил собой все остальные звуки, и вдруг исчез.

– То, что я говорю под белкой, не имеет никакого значения. Просто забудь об этом, Васляева. Ты ведь сможешь сделать это для меня, деточка? 

Закончив говорить, Веня принялся вытирать мое лицо от слез. 

Терзающие сердце голоса умолкли, но вместо них ко мне тут обратился другой, куда менее спокойный голос.

*ЛЕЖИ, БЛЯДЬ, КОГДА Я С ТОБОЙ РАЗГОВАРИВАЮ! *

Он объявился слишком неожиданно и звучал так правдоподобно, что я не сразу поняла, откуда доносились слова. 

*НЕ СМЕЙ ОТ МЕНЯ УХОДИТЬ!*

– Ну, что же ты плачешь, любимая? – озадаченно спросил Вениамин. – Говорю же тебе, это все глупости! Все те слова предназначались не тебе. Что бы я тебе ни говорил…

*Я, БЛЯДЬ, НЕ ЗНАЮ, ЧТО С ТОБОЙ СДЕЛАЮ!*

– Ты поднял на меня руку, – наконец, смогла произнести я.

Леденящий душу голос тут же исчез из моей головы.

<div style="text-align: center;">***</div>

– А кому? – спросила я, подкуривая сигарету.

– Что? – тихо отозвался Веня.

За все это время он не проронил ни слова. Заправил постель и принялся приводить себя в порядок, время от времени бросая в мою сторону всевозможные виноватые взгляды. Но стоило мне поднять голову, муж сразу же отворачивался, не решаясь встретиться со мной взглядом. При этом он не отходил от меня ни на минуту, словно и впрямь боялся, что я сбегу при первой же возможности. Только я поднялась с кресла, чтобы отправиться на перекур, Веня незамедлительно последовал за мной. Он прикрыл за собой дверь и уселся на пороге, приняв вид самого несчастного в мире человека.

– Ты сказал, что все те слова предназначались не мне, – напомнила я. – Так кому же, если не мне?

Вениамин медлил с ответом. Несколько раз открывал рот, но так и не решался мне ответить. Что бы там ни было, становилось ясно одно: ему было очень не просто в этом признаться.

– Моей матери, – с очередным тяжелым выдохом сказал Веня.

– Как давно это с тобой происходит?

Еще одна минута молчания.

– Лет десять.

– Десять лет? – переспросила я, не веря собственным ушам. – Целых десять лет ты вымещаешь свой гнев на женщинах, которые тебя любят? 

– Я...

– Ты был в курсе этого, но все равно продолжал пить?!

Веня медленно кивнул, внимательно вслушиваясь в каждое слово. Складывалось впечатление, что до этого момента он никогда не задумывался о своих проблемах, ни с кем их не обсуждал, и уж точно не признавал собственных пьяных проступков. В отношении последнего я была убеждена.

– Как так, Веня?

– Ну, вот так, – он развел руками. 

– И ты хочешь мне сказать, что никогда не думал о лечении? Или хотя бы о том, чтобы обратиться к терапевту? 

– Нет, никогда.

– Почему?

– Меня все устраивало, – он нервно затянулся сигаретным дымом. – До сегодняшнего дня.

– Допустим, так, но это не могло устраивать остальных. Им ты тоже не решался смотреть в глаза из-за чувства вины? 

– А я и не чувствовал никакой вины, – нехотя признался Веня. – Как можно чувствовать себя виноватым за то, чего не помнишь?

– Как можно не помнить того, о чем и так знаешь? 

Видимо, говорить правду для него было совсем не просто. Даже самые короткие ответы моего возлюбленного сопровождались предшествующей им минуте молчания. Что же касалось более длинных реплик, их он обдумывал неприлично долго.

– Потому, что мне было плевать на тех женщин, – еще одно признание. – Они были свободны. Могли катиться на все четыре стороны. Я много раз пытался с ними расстаться. Даже открыто изменял, но они все время возвращались и умоляли меня простить их. Одна так вообще подкараулила меня у работы. Сумасшедшая оказалась баба. Упала на колени, схватила меня за ноги и еще несколько метров протащилась за мной по улице, хотя мы даже толком не встречались. Все те женщины, о которых ты говоришь, они не были мне нужны. Но они все возвращались и возвращались. Просили дать им второй шанс.

– И ты им его давал?

– Не всем и не сразу, но да, давал.

– Зачем?! – не без эмоций воскликнула я, и тут же добавила: – Можешь ничего не говорить. Я и так знаю ответ.

– Правда? 

– Конечно. Я поняла это довольно быстро.

– И зачем же? – в его голосе промелькнули нотки заинтересованности.

– Больше всего на свете ты боишься одиночества. Ты совсем его не понимаешь, Веня. Потому, что не понимаешь себя самого. И каким бы мужественным ты не старался выглядеть, ты просто не можешь быть предоставленным самому себе. Что трезвый, что вхламину пьяный.

Сидевший на пороге балкона мужчина страшился одиночества на протяжении всей своей жизни. В моих умозаключениях не было ничего сверхъестественного, но на Вениамина они произвели неизгладимое впечатление. Он выглядел подавленным, сбитым с толку и обескураженным.

– А ведь знаешь, – глухо произнес муженек. – Кажется, об этом я тоже никогда не думал. 

*Кажется, ты вообще никогда не думал.*

– Похоже на то.

– Это как-то связано с самостью, о которой ты говорила?

Я кивнула и бросила окурок в переполненную пепельницу. За выходные о ней ни разу не позаботились, и останки наших сигарет то и дело вываливались на пол. Перешагнув один из них, я направилась к выходу, когда сидевший на моем пути Вениамин поднялся на ноги. Он взял меня за руки и впервые с того самого момента, когда я упомянула о применении физической силы, заглянул мне в глаза.    

– Я не так хорош, как ты можешь думать, Васляева, – говорил Веня; я до сих пор могла уловить в его дыхании алкогольные нотки. – Ты первой поняла, чего я на самом деле боюсь, и ты единственная, кому я признался, что держу злость на мать. Скажи, теперь я тебе противен?

– Вовсе нет.

– Может и так! Но если бы ты знала меня в прошлом… Нет, ты бы точно не захотела иметь со мной ничего общего потому, что… До встречи с тобой я, как бы это сказать, не уважал женщин. Они все были одинаково глупыми, а я этим пользовался. Однажды я даже решил их коллекционировать. 

– Тоже мне новость. Мужики все время так делают.

– Не в том смысле, что ты подумала, – по-прежнему не отводя глаз, говорил Вениамин. – По молодости я знакомился со многими девушками и специально делал все для того, чтобы они в меня влюблялись. И я бросал их как только это происходило. Наверно, это худшее, что я мог натворить. Только прошу, не спрашивай, зачем я это делал. 

– И не собиралась. Тебе это просто нравилось.

– Мне это просто нравилось. И после этого я тебе не противен? 

– Не знаю. Мне пока еще слишком сложно поверить в то, что мстительный и эгоцентричный сукин сын, о котором ты говоришь, и мужчина, с которым я живу – одно и то же лицо. 

Я никогда не стеснялась в своих выражениях.

– Понятное дело, но мужчины, с которым ты живешь, не существовало до нашей встречи. Вся моя жизнь изменилось, когда я увидел тебя в том зеленом платье, понимаешь? 

Конечно же, я понимала. Именно это и произошло со мной, если исключить из списка зеленое платье. 

– В тот вечер ты просто взглянула на меня, и я сразу понял, что теперь все будет по-другому. Вот для чего я все это тебе рассказал. Ты единственная меня понимаешь, деточка, и это только одна из многих причин, по которым я тебя так сильно люблю. Ты на самом деле все, что мне нужно от жизни.

От этих слов мне вспомнилась встреча с малышкой Таей.

Солнце вальяжно опускалось над волнами. Вениамин наблюдал за ним до наступления заката, и только потом спросил:

– Как думаешь, ты сможешь простить меня?      

– Не думай, что это произойдет быстро, – ответила я, и лицо мужа осветила улыбка.

Такая же яркая и теплая, как последние лучи скрывающегося за морем солнца.

– И раз уж мы заговорили о прощении… В свое время мать очень плохо с тобой поступила, но это никак не оправдывает твоих поступков, ты ведь в курсе? 

Веня с готовностью кивнул, и я продолжила.

– Тебе придется простить ее. Только так можно избавиться от этого гнева. Поверь мне, алкоголизм здесь не при делах. Он нужен тебе только для того, чтоб оправдывать свое блядское поведение. Детские травмы всегда провоцируют самые затяжные гештальты. Твои злость и обида слишком сильны чтобы исчезнуть без постороннего вмешательства. Этот гнев никуда не денется, даже если ты бросишь пить. Слишком уж долго ты его в себе взращивал, Веня.

– Но я не могу простить ее, – растерянно пробормотал он. – Если бы все было так просто! Думаешь, я не пытался? Еще как пытался, да вот только ничегошеньки у меня не вышло.

Произнося эти слова, мой мужчина выглядел как никогда уязвимым. В лучах уходящего солнца черты его лица стали мягче. Сейчас я видела перед собой всего лишь одинокого подростка, которого бросила родная мать. Его переполняли отчаянье и обида, что только росли с каждым годом. Мне вдруг открылась вся боль, таящаяся в сердце моего любимого, и я поняла, что Вениамин никогда с ней не расставался.

– Ничегошеньки не вышло, – повторил он.

– Не вышло в одиночку, но теперь у тебя есть я, – с этими словами я обняла Вениамина за плечи. – И я буду рядом, чтобы тебе помочь.

– Ты мне обещаешь? 

Я ответила, что обещаю, и мой мужчина заметно воодушевился. 

Думаю, тогда мы оба в это верили.


