# 61 {-}

Над Симферополем ярко светило солнце, когда исходивший духотой автобус, наконец, скрылся из поля зрения. Было приятно оказаться под открытым небом: после того как его занесло, автобус двигался мучительно медленно. Птицы пели во весь голос, деревья переливались зеленью, а покрывшиеся испариной горожане все так же деловито метались по улицам. Один за другим они пересекали мостовую. Смеялись, пили кофе, кому-то звонили, болтали со своими спутниками и так далее, и тому подобное.

Словом, вокруг не было ничего напоминающего об ужасах позапрошлой ночи. О ней кричала только скопившаяся в душе пустота. Должно быть, именно благодаря этой пустоте мне и удавалось без труда лежать на поверхности абсолютно несоленой воды. Со всех сторон меня окружали утки и еще несколько видов птиц, названий которых я не знала. Были среди них и смешные. С круглыми толстыми тельцами, болтающимися на длинных тоненьких ножках, они нелепо скакали по камням, мостовой и камышовым островкам. Полные спокойствия утки медленно плавали вокруг, периодически скрываясь из виду, чтобы спустя несколько секунд вынырнуть где-то поблизости.

Нагретая солнцем вода обволакивала мое тело, с настойчивостью озабоченного подростка пробираясь под одежду. На мне были солнцезащитные очки, и, раскинув руки, я бездумно разглядывала прожженное солнцем небо. Неестественно яркое, без единого облачка. Платье на мне промокло до нитки, и теперь складки его юбки томно колыхались в тон ветру.

Стоит ли говорить, туфли я тоже снять не потрудилась. Одна из них соскользнула с ноги и мигом пошла на дно. Пришлось и самой исчезнуть под водой, чтобы поймать ее. 

– Эй там! – раздался голос из соседних кустов.

Вслед за ним на причал вышел видавший виды старик.

– Эй там, на воде! – звонко повторил он, распугивая остатки моих мыслей и собравшихся на воде птиц.

Судя по тому, как он выглядел, теперь старик должен был попросить у меня то ли денег, то ли сигарет. Все это, в общем-то, уже лежало на причале у его ног, так что и спрашивать бы не пришлось, но речь пошла о другом.

– Вы это, осторожней там! Здесь нельзя купаться!

– Почему? 

– Это очень глубокий пруд! Дна нигде не найдешь, люди только так и топятся, – старик перевел дыхание и напоследок добавил: – Мой армейский товарищ так и пропал. Обкурился анаши да полез в воду посреди ночи! Так его и не выловили, так что и вам здесь делать нечего!

– А анаши случайно не осталось?

– Что?! Нет, но…

– Жаль.

Разговор перестал меня интересовать.

– ...Здесь очень опасно! Говорю же, товарищ мой так коньки отбросил. Небось бился всю ночь о камни, а выбраться не смог. До сих пор не выловили беднягу. Так он и лежит где-то на дне, представляете?

– Я дам вам знать, если его встречу, – сказала я.

Затем раскинула руки и вновь растянулась поверх воды, разглядывая переливающееся синевой небо. Прежде чем скрыться в кустах, старик пробормотал еще что-то, но я его не услышала. Возможность утонуть показалась мне слишком привлекательной.

<div style="text-align: center;">***</div>

– Ты точно не идешь? – десятью минутами ранее спрашивал Вениамин.

Он направлялся в центральный офис, где должен был встретиться с коллегами, бухгалтерами и прочими сотрудниками, прилагающимися к начальству. Последнему почему-то уже который месяц не терпелось со мной познакомиться, и Веня в сотый раз повторил свой вопрос. 

– Может, все-таки передумаешь? Или ты думаешь, что слишком хороша для такого общества? 

Общества, которое в основном состояло из Инны, непосредственной начальницы Вени, дочки владельцев сети магазинов золота, бывшей стриптизерши, которой она стала, когда первый муж Инны бросил ее из-за лишнего веса; ее нынешнего мужа Питера, богатого русского немца и набожного католика, который любил стрип-клубы и тучных женщин, так что женился на стриптизерше и уже несколько лет успешно способствовал появлению жировых отложений на ее теле; бухгалтера по имени Настя, что едва успела выйти из второго декрета, где настолько истосковалась по общению, что теперь тарахтела без остановки, и ее мужа Леши, который посещал бордели каждую субботу и без зазрений совести звал Вениамина с собой; а также еще нескольких не вызывающих доверия лиц.   

Находиться в их обществе означало бы все время притворяться. Веня давно привык вести себя подобным образом, а мне просто не хотелось лицемерить, так что я ответила:

– Да, ты прав. Именно так я и думаю.

– Бабы даже вина купили к нашему приезду. Ну, пойдем же! – продолжал Веня, не обращая внимания на мои слова.

– В другой раз.

Для него было крайне важно мое присутствие. Вовсе не потому, что Вениамин и дня не мог провести без меня. Просто мнение окружающих всегда интересовало моего избранника куда больше, чем собственное. Конечно же, подобно всем мужчинам, он так ни разу этого и не признал.

– Все будут спрашивать, почему ты не пришла, – торопливо объяснял он, а затем принялся перечислять имена женщин и мужчин, которые все время интересовались моей личной жизнью и по совершенно непонятным причинам уже третий месяц ждали знакомства со мной. – Они не отстанут, пока не узнают, почему я пришел без жены. И что мне им на это сказать?

– Можешь сказать им правду, – заметила я.

Похоже, это вернуло Вениамина к реальности, потому как новых вопросов не последовало.

– Ну как знаешь, – обиженно сказал Веня.

Вскоре я осталась в одиночестве и впервые в жизни была этому рада.

Оказавшись предоставленной самой себе, я инстинктивно направилась к воде, как обычно делаю в моменты печали. Что бы ни случилось, внутренний компас всегда приводит меня к ближайшему водоему. На этот раз им оказалось городское водохранилище, что располагалось всего в нескольких минутах ходьбы от офиса Вени. Внешне это место напоминало большой пруд, окруженный густой лесополосой. 

Мне все так же хотелось забиться в какой-нибудь темный угол. Пришлось обойти весь водоем, прежде чем я смогла найти себе место в зарослях у дальнего причала. Почти такого же шаткого и старого как тот, по которому деревенская детвора из моего детства гоняла в ожидании катера. 

– Сойдет, – произнесла я и заметила вдали Вениамина, спешащего на встречу с начальством.

Тот быстро пересек мостовую и вскоре исчез из поля зрения. 

С минуту я простояла у края причала, пытаясь понять, чем хочу заняться дальше, но вскоре поймала себя на том, что завидую местным уткам, и, долго не думая, шагнула в воду.


