# 62 {-}

В начале следующей недели муж вернулся с работы и радостно объявил:

– Деточка, мы едем в Керчь!

– Когда?

– Да хоть сегодня! 

Я не разделяла его энтузиазма, но в итоге была вынуждена признать: смена обстановки явно пошла нам на пользу. Она помогла мне отпустить накопившиеся обиды и даже сумела закрыть парочку гештальтов, из которых уже начинало сквозить. Буря, разыгравшаяся в моей личной жизни, наконец, сменилась умиротворяющем штилем. 

Надолго ли?

Спустя восемь часов пути (два из которых автобус простоял в пробке) я оказалась в родном городе Вениамина. Поездка была долгой и душной. Она окончательно меня вымотала, чего нельзя было сказать о моем спутнике. На протяжении всего пути он сладко спал на моем плече, как, в общем-то, делал всегда, и теперь был полон энергии.

– Ну, как тебе? – с нетерпением спрашивал Веня.

Приличия ради, я осмотрелась. Справа от нас была дежурная аптека и парочка забегаловок, что работали круглосуточно. Слева находилось ничем не примечательное здание автовокзала. Впереди виднелась усеянная фонарями дорога, а позади – темная трасса, которой автобус привез нас в Керчь. Не хватало только Бродского.

– Не знаю, Веня. Мы же все еще на вокзале.

Дело близилось к четырем часам утра.

– Ах, ну да! 

Муж подхватил чемодан и, взяв меня за руку, повел вперед. В сторону относительно освещенной дороги.

– Будем дома через десять минут, – обнадеживающе пообещал он, когда мы ступили на мост. – От силы пятнадцать.

По мере приближения к конечному пункту, я неосознанно стала замедлять шаг. Впереди ждало знакомство со свекровью и, чем больше историй о ней я слышала, тем меньше была готова к встрече с этой женщиной. Некоторые люди бывают просто невыносимы, иным же удается зайти дальше. Они становятся сгустком злобной энергии, который ненавидит все и вся, не замечая при этом собственных пороков. Такие люди считают себя святыми, так что только и ждут шанса пожаловаться. Они бесцеремонно вторгаются в чужое пространство, чтобы заполнить его отрицательными эмоциями. Стоит потерять бдительность хоть на минутку, и к тебе тут же присасываются как пиявки, отравляя мысли и душу.  

Как выяснилось, мать моего мужа как раз относилась ко второму типу. Наталья Яковлевна была сверхневыносима: она везде и всюду сеяла негатив. Ни одно предостережение так и не смогло должны образом подготовить меня к этой встрече.

– Вот он, мой дом, – Веня указал на пятиэтажное здание, которое было ближе всех к проспекту.

Лифтов в таких домах отродясь не водилось, но квартира была на первом этаже, что несказанно меня порадовало. Сейчас даже самый короткий подъем показался бы мне Потемкинской лестницей.

Родительский дом Вениамина встретил нас приветливым лаем собак, едким запахом кошачьей мочи и звуками орущего телевизора. Все это выглядело довольно шумно, но так и не разбудило хозяйку дома. Лицом в подушку, она лежала в полном отрубе, растянувшись на диване посреди гостиной. Рядом стояла бутылка, на дне которой виднелось еще немного вермута. Мать моего мужа спала без памяти, и, глядя на это, я впервые обрадовалась чужому алкоголизму.

<div style="text-align: center;">***</div>

Нельзя сказать, что я ждала чего-то особенного от спальни Вениамина. Скорей, не ожидала ничего, но, войдя в комнату, тут же ощутила запах блядства. Такой приторный и до ужаса въедливый душок, в настойчивости своей сравнимый разве что с ароматами гниющей плоти. Даже смраду кошачьей мочи, источником которого оказался Венин диван, не удалось перебить этот запах. Лишь один вдох, и я увидела их всех – женщин и девушек, отчаянно и во всех позах любивших Вениамина.

Меня не смутили разбитые сердца, следы которых виднелись на каждом углу. Не смутили ни крики, ни стоны, ни слезы, чьи отзвуки эхом отдавались в моей голове. Напрягло лишь одно: их было слишком много. Гораздо больше, чем должно было быть, исходя из рассказов Вениамина. И куда больше, чем бы мне того хотелось.

Но черт с ними, с моими желаниями. Я давно научилась относиться к ним как к капризным детям, с молчаливым пониманием и толикой снисхождения. Эго может и подождать. Ведь нет ничего дурного в том, чтобы весело провести молодость, не так ли?

*Пока это не загубит чью-то чужую молодость.*

Смутило меня другое: полнейшее отсутствие какого-либо отклика. Во всей этой кавалькаде страданий я пыталась разглядеть фантом Вениамина, но не видела ровным счетом ничего. Кроме пустоты и какого-то легкого раздражения. Вот что меня на самом деле смутило. И эта не состыковка в подсчетах вагинальных единиц на одного бородатого бродягу Дхармы.

Все это могло значить лишь одно: Веня мне врал. И хорошо, если только о количестве прошедших через его постель женщин. Мне вдруг стало ясно, что он никогда никого не любил. И я взглянула на мужа. Подняла глаза, и увидела, что тот с интересом наблюдает за мной, по-прежнему стоящей у порога его спальни.

– Ты никогда никого не любил, Веня. Никого из этих несчастных, правда?

Он словно немного вздрогнул и даже мельком взглянул по сторонам, пытаясь понять, о каких таких несчастных я говорю. А я никак не могла вспомнить, как много уже успела рассказать мужу о своей эмпатии. В моменты вроде этого моя феноменальная память давала сбой. Слишком уж много информации поступало, дабы отличить сказанное от того, что я когда-то собиралась сказать.

*Сейчас он начнет врать*, пообещал внутренний голос.

Но Веня не соврал.

– Да, не любил, – сказал он, и спокойно добавил: – Я ведь говорил тебе об этом, деточка.

*Сейчас он скажет, что ты первая женщина, которую он по-настоящему полюбил.*

– Ты первая женщина, кого я по-настоящему полюбил, помнишь?

*Ты перевернула его представление о мире.*

– Ты перевернула мое представление о мире.

*И он никогда прежде не любил так, как любит тебя.*

– И я никого не любил так, как люблю тебя, Лизонька.

Три из трех. Прямое попадание, дамы и господа. От этого мне сделалось как-то не по себе. Слова Вениамина вдруг показались мне шаблонными. Словно передо мной стоял не муж, а какой-то актер, зачитывавший реплики из хорошо отрепетированного сценария.

– Ты разбила все мои стереотипы о женщинах.

И эту фразу я тоже предвидела. Происходящее казалось мне уж слишком неестественным. Я попыталась вспомнить хоть раз, – хоть разочек – когда Веня действительно выразил бы собственную мысль. Не цитировал бы факты, прочитанные в копирайтерских статьях, не возмущения на все и вся, да собственные признания в любви, а именно мысль. Попыталась, но не смогла вспомнить ничего подобного.

Паника в моей душе нарастала, и это начинало сводить с ума.

*Для того, чтобы сойти с ума, в ум надо сначала войти*, заметил внутренний голос. А ты с детства не от мира сего.

Эта внезапно пришедшая мысль меня рассмешила.

Вениамин продолжал что-то говорить мягким, успокаивающим голосом. Взгляд его был под стать этим любовным нотам, но в сиявших лазурью глазах все еще виднелся интерес.

*Он знает, что я знаю*, подумалось мне. *Знает, но не может понять, откуда.*

Я и сама не знала откуда. Казалось, я просто родилась с этим знанием. За время, прожитое с Вениамином, я практически прекратила видеть вещи, выходящие за границы реальности. Стала воспринимать их как часть своего психического расстройства, но! Рано или поздно все эти нежданные приливы оказывались правдой, даже когда я не пыталась до нее добраться. И в этом заключалась проблема.

Легко признать себя сумасшедшим, если ты в чем-то не похож на других людей. Куда труднее, когда это сумасшествие начинает находить себе подтверждение. А ты даже не пытаешься ничего прояснить. Просто стоишь и смотришь на то, как правда выливается наружу, а потом еще этот голос со своими «Вот видишь!» и «Я тебя предупреждал».

Так, неужели Вениамин на самом деле врал мне все это время? Но в чем? И для чего ему все это?

*Нет, он любит тебя и обожает*, не без сарказма ответил голос.

– И я люблю тебя всем сердцем, Васляева.

– Любишь?

– Люблю. И до безумия обожаю!

*Вот только он всем это говорит.*

С приходом последней мысли мне сделалось по-настоящему дурно. Быть может потому, что я разглядела в ней правду? Не знаю, но дышать становилось все тяжелей. Я пошатнулась и, что было сил, вцепилась рукой в дверной косяк, надломив пару ногтей на правой руке.

– Господи, деточка, да ты же устала! – спохватился Веня.

Он взял меня под руки и усадил на диван. Одним рывком, заставив меня удивиться этой силе.

– Тебе нужно как следует отдохнуть.

Идея об отдыхе на этом диване показалась мне самой мерзкой мыслью на свете.

– Здесь нечем дышать, – наконец, нашлась я.

Списала все на аллергию и кошек. Веня постелил мне в спальне сестры, пожелал сладких снов и удалился. Спустя несколько минут я уже слышала его раскатистый храп. Звук этот казался мне столь родным и привычным, так что я быстро пожалела о решении провести остаток ночи в одиночестве.

– Ты просто поехавшая, Васляева, – сказала я себе. – Привыкла окружать себя лживыми людьми, а теперь по инерции ищешь изъяны в любимом человеке.

*Он не знает, что такое любовь*, напомнил внутренний голос.

– Ой, да теряйся уже!

Как скажешь.

Голос исчез. На смену ему пришло пение птиц, лившееся из открытого окна. За ним уже вовсю сияло утреннее солнце, и я вновь стала нормальной на какие-то пару недель.


