# 63 {-}

Валя, сестра Вениамина, должна была вернуться дней через двадцать, и я искренне надеялась, что к тому времени мы уже будем далеко-далеко за пределами Керчи. Как бы там ни было, выспаться мне так и не удалось. Бессонная и уставшая я пролежала в чужой постели с час. Может больше. Время теряет смысл, когда тебя одолевает бессонница.

В какой-то момент дверь отворилась. На пороге возникла Наталья Яковлевна. Даже в затертом до дыр халате, накинутом поверх ночной сорочки, она до ужаса походила на моего мужа. Или правильней будет сказать, что это Веня походил на мать. Те же черты лица, те же движения, а как позже выяснилось, еще и те же пагубные пристрастия и интонации в голосе.

Свекровь громко зевнула. Потянулась, а затем, наконец, подпрыгнула, заметил меня на кровати дочери.

– Ой! – сказала она.

– Ай, – ответила я.

– Это ты, Лиза?

– Я.

Так и познакомились.

<div style="text-align: center;">***</div>

– Значит решила из моего сына человека сделать? – как бы невзначай поинтересовалась Наталья Яковлевна.

Ее появление быстро вырвало меня из полудремы. Свекровь предложила сделать ей кофе, аргументировав это дело фразой «ты ж бармен». Мне хотелось спросить, а не написать ли ей мемуары? Ведь я ж еще и писатель, но с горем пополам я воздержалась. Сварила ей кофе, и вот мы сидели на скамейке подле окна, за которым сопел муженек.

Вдохнув сигаретный дым, я с пару секунд помолчала, в надежде, что Наталья Яковлевна скажет что-нибудь еще. Что-то без вопросительных интонаций в конце, но она замолчала, и мне пришлось ответить:

– И в мыслях не было.

– Но ты же решила женить на себе Веню.

– Это Веня решил на мне жениться, – поправила я. – Я вообще замуж не хочу.

– Это как же так не хочешь?

– Да вот так, не хочу и все тут.

– Ну, конечно! 

Последнее слово она произнесла так, как миллион раз до этого произносил его Вениамин. С характерным придыханием на первом слоге, так что получалось что-то вроде «к-хонечно».

– Тебе сколько лет?

– Двадцать два.

– Я в двадцать два уже Веню из садика забирала, – гордо заметила Наталья Яковлевна.

Потом как-то резко поменялась в лице и добавила:

– Красавишна, так может ты беременна?

Я ответила, что это вряд ли, но женщина все равно продолжала глядеть на меня с подозрением.

– Детей что ли тоже не хочешь?

Я покачала головой.

– Но ты согласилась выйти за моего сына. Почему?

– Потому, что я его люблю. И если для счастья Вене нужен штамп в паспорте, то так тому и быть. Мне не жалко.

– Но сама ты замуж не хочешь? 

– А чего тут хотеть-то? – с улыбкой спросила я.

И тут Наталья Яковлевна как бы подвисла. Сложила губки – прямиком как Венька, когда его голову терзает какой-то вопрос – и принялась думать. Затем попросила у меня сигарету. Ее профиль – классические черты учительницы: острый нос, тонкие губы, узкие глазки, щурившиеся из-под очков в тонкой оправе, да не по-женски высокий лоб, что то и дело хмурился  – филигранно вырисовывался на фоне синего-синего неба.

Свекровь затянулась сигаретным дымом и принялась рассказывать о давно минувшей молодости. Ей было слегка за сорок. Не так уж много, как по мне, но женщина говорила о счастье как о каком-то призрачном мираже. Извечно далеком и навсегда утраченном. Быть может, это присуще всем старикам? Вот только, она не была старой, пускай подсознательно уже давно окрестила себя ни на что не годной старой клячей. Само собой, Наталья Яковлевна никогда бы в этом не призналась. Не только мне, но и самой себе – думаю, в этом и кроется корень неудач большинства людей.

Да, сидевшая рядом женщина в душе считала себя неприлично старой. Все рассказывала и рассказывала мне о своей так называемой молодости. Что в этом нового? Да, в общем-то, ничего, разве что в ее словах напрочь отсутствовало упоение, с каким обычно вспоминают радостные моменты жизни.

Говорила Наталья Яковлевна преимущественно о плохом. Ее муж – теперь уже бывший – зарабатывал хорошие деньги, но большую часть получки тратил на гульки, принося домой лишь жалкие гроши. С двумя детьми на руках, свекровь целыми днями сидела голодная пока отец семейства разгуливал по Керчи в компании чужих, а то и вовсе ничейных женщин. Еще муж бил ее, когда напивался. А напивался он часто.

– Разбил мне как-то голову в двух местах. Я с сотрясением потом в больнице лежала, когда Леша решил открыть моим лбом вон ту калитку, – она указала на ржавеющие ворота у входа во двор. – Ты видишь? Там справа все еще видно погнутые прутья.

Со слов свекрови муж изменял ей на протяжении многих лет. Наталья Яковлевна просыпалась ни свет, ни заря, чтоб приготовить мужу завтрак. Провожала его на работу, детей – в школу, и принималась за уборку. 

– Ведь мужчина должен возвращаться в чистый дом! – гордо говорила она.

Мыла, терла и драила квартиру весь день. Потом готовила обед и снова что-то мыла, дожидаясь прихода супруга. Затем накрывала на стол

– Первое, второе, закуска и десерт, – все с той же гордостью добавила свекровь.

и садилась напротив мужа, чтобы узнать, как прошел его день. После еды мужчина отправлялся отдыхать, а она шла убирать со стола, мыть посуду, приводить кухню в порядок и снова что-то стряпать. 

*Ну, до чего же умопомрачительная идиллия!*

От этой картины моей матке захотелось самоуничтожиться, чтобы наверняка никого не родить.

Так вот, женщина все драяла и стряпала двадцать четыре часа в сутки, а муж брал и изменял ей, вы представляете?

– И весь город был в курсе! – возмущенно воскликнула моя собеседница.

Все обо всем знали, но никто ничего с этим не сделал. Тут я, наконец, открыла рот и поинтересовалась, почему сама свекровь ничего с этим не сделала. Та поглядела на меня как на дуру, пробормотала что-то вроде «У нас же дети!», и дальнейшие вопросы как-то отпали.

Так продолжалось долгие годы, но идиллия не могла длиться вечно. Однажды Леша встретил…

– Эту, как там ее, Снежану!

… и окончательно заявил, что уходит из семьи.

Уж не знаю, сколько косяков мне нужно было выкурить, чтобы поверить будто свекровь могла хоть на мгновенье забыть имя второй жены своего бывшего. Хотя бы потому, что тем же днем эту Как-Там-Ее-Снежану она упомянула еще раз десять. Примерно столько же лет назад Алексей Вениаминович ушел от первой жены.

Она прикончила уже, наверное, четвертую из моих сигарет, когда в голосе собеседницы вдруг проступили мечтательные нотки.

– А я каждый день его жду, – с трепетом произнесла женщина, глядя в сторону ворот. – Вот прямо вижу как он с цветами заходит в эту самую калитку…

(Ту самую, чьи прутья он помял ее головой.)

– Поднимается по ступенькам и стучится в двери. А я выхожу на порог и зову его домой. С прической как у Мэрилин Монро. Такая у меня была, когда мы жили вместе. Надо бы осветлиться, как думаешь, Лиза? Я была красавишной? Ведь если он вернется, я ему все прощу! И мы как раньше заживем душа в душу. Ох, если бы он только вернулся! Я бы все ему простила. Так что я буду ждать.

Мечтательность в ее голосе вызвала у моих феминизмов острое желание повеситься где-нибудь в тихом уголке бессонного разума.

<div style="text-align: center;">***</div>

– Быть женой – это прекрасно! – следующим днем заявила свекровь.

Мне пришлось вымыть комнату Вали, а до этого кухню, а до этого диван в гостиной, где спала Наталья Яковлевна, и комнату Вени, чтобы хоть как-то угомонить эту женщину. Сама свекровь в уборке на слишком-то участвовала. Только руководила. Уперев руки в бока, она то и дело возвышалась надо мной с видом  «я свое уже отмыла», но это еще ничего.

Все это время женщина рассказывала мне о Вене. Говорила, какой плохой человек этот ее сынок и все поражалась тому, откуда он такой взялся. Свекровь без устали перечисляла бывших девиц моего мужа, во всех красках описывая, как тот их пользовал, бил и пялил. Бил и пялил. Пялил и бил. Взаимосвязи между поведением сына и моделью семьи, в которой тот рос, она не видела, но местами прерывалась на стенания о собственной жизни, чтобы пожаловаться на вениного отца и Эту-Как-Там-Ее-Снежану. А затем вновь возвращалась к сыну, который бил и пялил. Такой вот крохотный ад на Земле.

Мне стало жаль эту женщину, теряющую настоящее за воспоминаниями о прошлом, бывшем муже, что предпочел ей другую да счастливой семейной жизни, которой вообще никогда не было. Что она вспоминала? О чем говорила? Сплошной негатив, но Надежда Яковлевна цеплялась за него как за последнее, что осталось в ее жизни.

Возможно, так оно и было.

Короче говоря, я живо распознала барышню в депрессии. Рыбак рыбака, как говорится. В ее квартире был бедлам, (одни только блохи чего стоили) но свекровь постоянно повторяла, как важно держать дом в чистоте. Осуждала всех кроме себя. И винила в своих неудачах всех кроме себя.

Мне почему-то подумалось, что Надежде Яковлевне полегчает, если я приберусь. Стоит ли говорить, что ежедневная уборка едва ли входила в круг моих интересов. Готовить мне тоже никогда не нравилось, но я убирала и готовила, надеясь, что это хоть чуточку поможет свекрови воспрять духом. Да только куда там! Мои игры в домохозяйку ее только подхлестывали.

Так продолжалось несколько дней. Свекровь говорила и говорила. О прошлом, своем и венином, делая это исключительно в негативном, наполненным злобой ключе. Что-то из ее воспоминаний было правдой, но, все-таки, довольно искаженной правдой. Женщина рассказывала свои истории, все время добавляя новые детали, стараясь выставить бывшего полным кретином. Как будто самого факта измены или того, что муж поднимал на нее руку, было недостаточно. В какой-то момент сюжеты стали повторяться, но Наталья Яковлевна, казалось, того совершенно не замечала. Раз за разом она описывала мне одни и те же темы, накрепко засевшие в ее подсознании. О том, как бывший повез любовницу в Севастополь, как купил той дорогущие чулки со вставками каких-то драгоценных камней, как объявил, что уходит и как по пьяни принялся утаскивать за собой все, что попадало под руку.

– Он вынес коней! – неистово верещала Наталья Яковлевна, подразумевая набор статуэток, что годами пылился за стеклом серванта. – Кон-е-е-ей! Ты можешь себе это представить? Дочь пошла на экзамен, а он коней вынес! Совсем уже сдурел со своей этой… как там ее? Все же знают, что будет, если вынести из дома вещь перед экзаменом!

Я отложила швабру и взглянула на собеседницу сквозь упавшие на лицо кудри.

– И что же будет?

– Не сдаст! Не сдаст! НЕ СДАСТ! – пуще прежнего завопила та. – Дочь на экзамене, а он конец вынес! Вот она и не сдала. Это вообще моих родителей кони. Нам их на свадьбу подарили… Коней вынес, нет, ну ты себе это представляешь? Кон-е-е-ей!

Шел третий день пыток. Свекровь опять пересказывала одно и тоже. Ее визги продолжали звенеть в моей голове даже в драгоценные минуты тишины, когда женщине требовалось в туалет. Если в туалет шла я, Надежда Яковлевна становилась под дверью и продолжала говорить. С перекурами было то же самое. Она не просто пересказывала свои обиды. Хуже того, переживала их по кругу.

– А я видела те чулки! – говорила свекровь. – На меня он никогда таких денег не тратил. Все ей, ей нес! Какой-то дворничке! А ты мой-мой, не отвлекайся. Вон там на плинтусе пятно пропустила.

И женщина вновь переключилась на Вениамина, извергая подозрительно детальные описания странствий его детородного органа. Вениамина, который пялил и бил. И опять все обо всем знали, но никто ничего не делал. От этих историй голова шла кругом, а уже ближе к вечеру мной овладел так хорошо знакомый демон, имя которому – Депрессия.

Все говорят, «я в депрессии», но выражение это в корне неправильно: это депрессия в тебе, а не ты в ней. Вот ты есть. Думаешь, любишь, творишь. У тебя имеются какие-то планы, мечты и цели, к которым ты идешь не один год, а, может, и всю жизнь.

А потом приходит депрессия. Забирается тебе под кожу с упрямством южноафриканского паразита. Она медленно, но уверенно выедает твои внутренности: все эти мечты, чувства, стремления. Очерняет душу, оставляя за собой зияющую дыру, в которой мог бы утонуть и сам Космос. Все, что ты делал и к чему стремился, в одночасье становится бесполезным. Теперь нет никакого смысла. Ни в чем. Любые надежды рассыпаются с неумолимой скоростью, а ты только и можешь, что стоять да поражаться тому, какими, оказывается, хрупкими были твои мечты. Вот они были, и вот их уже нет. Нет любви, нет смысла, нет будущего.

И тебя тоже нет.


