# 64 {-}

Венька пришел немногим раньше семи. Никогда еще я не была так рада его возвращению с работы. Завидев лицо сына, Наталья Яковлевна ретировалась в дальнюю комнату и тихонько прикрыла за собой дверь.

Не разуваясь, муж прошел в кухню. Поглядел на меня, всю в мыле, и вскоре его губы, укрытые пеленой пшеничных усов, изогнулись в ласковой улыбке.

– И давно ты тут убираешь?

– Весь день, – ответила я, на автомате продолжая возиться с кафелем.

– Вставай, – что-то в этом голосе, спокойном и властном, заставило меня мигом отшвырнуть тряпку и подняться на ноги.

За окнами послышались первые признаки пробирающегося к нам дождя.

– Мне так стыдно за нее, – извиняющимся тоном произнес муж. – Так неловко, что тебе пришлось все это делать.

Он указал на ведро с водой, что к тому времени уже успела стать холодной.

– Это же она тебя заставила?

– Нет. Мне просто надоели блохи.

Хотела перевести все в шутку, но вместо нее с губ сорвался непонятный смешок. Я подошла к любимому, позволив себе раствориться в его объятьях.

– Выглядишь будто ты в депрессии, – заключил Веня.

– И чувствую себя примерно так же.

– Что эта женщина тебе наговорила? Это обо мне?

Тогда я осознала, что Вениамин никогда не называл свекровь матерью. Говорил исключительно «она» или «эта женщина».

– Все в порядке, – соврала я.

– Она рассказывала, как я бил бывшую?

– Немного.

– Все было не так, как она говорит.

– Я понимаю.

– И об отце еще, небось, говорила?

– Да.

Веня вздохнул.

– Ума не приложу, что мне делать с этой женщиной. Когда я привел домой свою первую девушке она увела ее курить и стала ныть, какой я плохой. Сказала той девушк, что я подонок и ей нужно…

– Бежать от тебя куда подальше. Ты уже это говорил.

Повисла долгая пауза, неловкая в своей тягостности. Дождь тем временем усилился. Из редких капель он постепенно обращался полноценным ливнем.

– И что же мне теперь с тобой делать? – спустя пару часов спросил муж.

Свой ужин он давно съел и теперь наблюдал, как я с отстраненным видом колупаюсь в тарелке. К моменту моей расправы над едой Керчь была окутана ночным сумраком, а ливень уже вовсю молотил по тротуару, подоконнику и дощатым крышам виднеющихся напротив домов. Я довольно долго наблюдала движение сточных вод, когда Вениамин размашистой походкой вошел в спальню.

– Я знаю, что тебе нужно! – уперев руки в бока, заявил он.

А решимости своей Веня был пугающе похож на мать.

Вопросительно, но, в общем-то, безо всякого интереса я взглянула на мужа. Валяющаяся на моих коленях книга казалась куда интересней его идей, наступившей ночи и жизни в целом.

– Эта женщина из тебя все соки выжмет, но я то знаю, что нужно моей деточке.

Мне, все же, пришлось перебраться в его комнату. Она была единственным местом в доме, куда Наталья Яковлевна не решалась заглядывать. Но стоило покинуть пределы спальни, и свекровь вырастала на пути как гриб в дождливый день. Принималась ходить за мной по пятам, настойчиво нашептывая свои пессимистичные мантры. Она являлась даже среди ночи, когда я выходила на кухню попить воды. Дверь уборной тоже не особо спасала. Женщина просто прижималась к ней с обратной стороны и продолжала свои рассказы. Как-то она даже просунула под дверь телефон, чтобы показать мне фото яичной скорлупы у раковины да краски с кистями в творческом хаосе оставленные на подоконнике – «непростительный беспредел», оставленный бывшей девушкой Вениамина.

*Девочкой, ей было всего семнадцать.*

– Пойдем к морю, –  сказал муж.

Наконец, безразличие на моем лице стало улетучиваться. Я буквально чувствовала, как на смену ему пришло недоверие.

– Сейчас?

– Ну да!

– Но там же дождь… И ночь.

– Именно!

Муж был как никогда весел и настроен куда оптимистичней моего.

– Веня, я ничего не понимаю.

– Ну, ты любишь ночь. Любишь дождь и море. И меня ты тоже любишь! Давай вставай, ты все равно только делаешь вид, что читаешь!

Еще пару минут уговоров, и я сдалась. Пожала плечами и сказала:

– Ну пойдем.

А спустя четверть часа мы уже сидели у моря.

