# 65 {-}

В первых числах августа мы переехали в Симферополь. Ранним утром, на следующий день после того, как Вениамин возвратился из запоя, мы прибыли на Кречинский вокзал. Прошло еще четыре часа прежде, чем мы автобус высадил нас на окраине Симферополя.

Утренний город выглядел так же, как и в моих воспоминаниях. Здания были серыми, а обочины и тротуары вокруг них сплошь и рядом оказались усыпаны мусором. Даже птицы и уличные животные имели какой-то болезненный вид, так что мы быстро затерялись в толпе.

Да, здания были серыми, а обочины и тротуары – усыпаны мусором, но ничто из этого не могло сравниться с воздухом. Он был тяжелым и грязным, отчего создавалось впечатление, что ты находишься не под открытым небом, а в каком-нибудь забитом общественном транспорте с закрытыми окнами, внутри которого, к тому же, еще разместилась бригада потных шахтеров, только что отработавших ночную смену.

– Столица Крыма.

Вениамин обвел рукой этот унылый пейзаж и с пугающей любовью в голосе добавил:

– Вот мы и дома, деточка. 

Однако дома мы оказались только спустя четырнадцать часов. Четырнадцать очень долгих и жарких часов. Все это время, с вещами наперевес, мы скитались по местным агентствам недвижимости, а потом отправлялись смотреть очередное жилье. Квартиры здесь оказались по-столичному дорогими и по-отечественному не привлекательным.

Стрелка на часах уже давно перевалила за одиннадцать вечера, когда мы, наконец, въехали. Это был просторный одноэтажный дом, внутри которого находилась светлая студия. За двойной дверью нас встретила плетеная мебель, королевских размеров кровать, огромные окна и даже крохотная терраса с видом на горы.

Единственной проблемой оказалась локация и тот факт, что дом и сам находился на горе. Но мы осознали это лишь с приходом холодов. Когда все вокруг покрылось льдом, а спуск и подъем стали слегка травмоопасным занятием.

– Желаете чаю? – предложил арендодатель.

Я читала контракт, Вениамин подписывал каждую из его страниц, а хозяин квартиры развлекал нас болтовней. Как и большинство мужчин, он почему-то не решался завести со мной разговор в присутствии Вениамина. И даже обращаясь ко мне, он обращался к моему жениху.

Арендодателя звали Владимир. Тихий, невысокий мужчина средних лет, который большую часть времени проводил на работе. Он был в разводе и жил по соседству. Каждые выходные Владимир забирал своих детей, чтобы смотреть вместе фильмы, ходить в походы и жарить шашлыки прямиком перед домом.

– А чем занимается ваша супруга?

Вениамин не отвечал. Он был слишком увлечен контрактом.

– Я писатель, – ответила я, и тут же заметила, как Веня изменился в лице.

Странная и чуть ли не презрительная ухмылка. Это длилось всего мгновение, но я была почти уверена в том, что мне не показалось.

Обычно после этих слов я слышу что-то вроде: «Настоящий писатель? И книги пишете? Прямо как Пушкин/Лермонтов/Достоевский…?» В общем, в конце можно вставить любого литератора из тех, чье имя встречалось вам в школьной программе.

Тем не менее, Василий ответил иначе.

– Вот это да! Быть того не может! – воскликнул он, и в ответ на мой удивленный взгляд добавил: – Так ведь я и сам писатель! Правда, в моем случае, это больше похоже на хобби.

– А о чем пишите?

– По большей части о Крыме и его выдающихся местах. А вы о чем пишите, Елизавета?

Тут-то я и подвисла. Наступила пауза, в ходе которой я всячески пыталась понять, о чем именно я пишу. Моя проза никогда не зацикливалась на какой-то конкретной тематике.

Длина паузы уже начала казаться мне неловкой, и я поспешно произнесла:

– Я пишу о жизни… и о смерти… А иногда еще и том, что происходит между ними.

Слишком абстрактно, я знаю, но это был самый правдивый ответ из тех, что пришли мне на ум.

– И об этом тоже когда-нибудь напишите? – заговорческим тоном поинтересовался Василий.

– Надеюсь, что нет.

– Это еще почему?

– Просто я не пишу об отношениях, в которых состою.

– Боитесь спугнуть удачу?

– Сама не знаю. Почему-то мне это кажется неправильным.

– Готово! – радостно объявил Вениамин.

Он протянул контракт Владимиру.

– Давайте выпьем за знакомство, – предложил хозяин квартиры, когда мы внесли в комнату все свои немногочисленные пожитки. – У меня есть коньяк.

Я мельком взглянула на мужа. При упоминании спиртного его уставшее лицо заметно воодушевилось. Затем наши взгляды встретились, и все это воодушевление как рукой сняло.

– Спасибо, но мы вот как раз решили какое-то время не пить, – медленно и с расстановкой ответил мой мужчина.

Мне подумалось, что именно таким штучкам учат завсегдатаев АА.

– Очень жаль, – заметил Владимир, не подозревая о том, что только что озвучил не только Венькины мысли.

Мне страшно хотелось выпить.

Хозяин квартиры пожелал нам спокойной ночи и удалился.

– Ну, что скажешь? – спросил Веня, когда мы остались одни.

Его вопрос не требовал уточнений, и я ответила:

– Ты меня удивил. Это факт.

– И чем тогда займемся?

Последние две с половиной недели я не видела ни ванной, ни горячей воды. Единственным похожим на мытье действием с моей стороны было ежедневное обливание ледяной водой из колодца, который, к тому же, находился на приличном расстоянии от дачи отца Вени. Каждое утро мужу приходилось отправляться к колодцу, а затем возвращаться обратно с баклажками наперевес.

– Сначала в душ, – решительно сказала я, и ничто в мире не могло меня остановить.

Когда я вернулась, Вениамин уже крепко спал, развалившись поперек кровати. Я улеглась рядом и тут же отключилась, даже не потушив свет.

<div style="text-align: center;">***</div>

Затем наступило утро. И, как это частенько бывает по утрам, я проснулась с чувством легкой эйфории. Ах, эти волшебные мгновенья после пробуждения – когда мозг еще не до конца очнулся, и не помнит всех тех вещей, что тяготили тебя минувшей ночью – они просто бесценны. Просыпаться совершенно не хотелось, но особого выбора мне не представилось.

В комнате стоял аромат кофе с корицей и слегка уловимыми нотками моего светлого будущего. В отличие от меня, солнце уже давно встало и теперь настойчиво стремилось проникнуть в комнату. Его тонкие полоски света проскальзывали сквозь жалюзи, покрывая стены, постель, мои ноги и все вокруг. Почему-то, это напомнило мне о детстве.

Я распахнула дверь на террасу и села на кровати. Если не опускать голову и смотреть исключительно прямо, забыв об убогих домишках и брошенных участках, что находились ниже, с трассы открывался очаровательный пейзаж. Передо мной возвышались горы, у основания которых раскинулся величественный лес, а чуть ниже тянулось извилистое шоссе. 

Машин тем утром я не увидела. Лишь птицы без устали кружили над лесом. Им было плевать на зной. 

– Проснулась? – послышалось со стороны кухни.

Спустя мгновенье в дверном проеме появился Вениамин. В руках у него был поднос с кофе и шоколадными кексами. 

– Доброе утро, любовь моя, – он поставил поднос у изголовья кровати и поцеловал меня.

К тому моменту, когда мы выбрались из постели, кофе совсем остыл.


