# 66 {-}

Жизнь в Симферополе оказалась, мягко говоря, унылой. Просторное жилье и открывающийся с его импровизированной террасы вид – вот, в общем-то, и все, что мне здесь нравилось. По остальным же параметрам столица Крыма явно уступала остальным городам полуострова. 

На протяжении первых после переезда недель я ежедневно спускалась с горы и отправлялась в город. Но грязные улицы, затхлый воздух и вечно спешащие куда-то люди с грустными лицами быстро успели мне надоесть. Слишком уж все это походило на Николаев – город, в котором я родилась двадцать два с половиной года назад и от которого всю жизнь пыталась убежать. 

Как и следовало ожидать, все это вгоняло меня в уныние. Вскоре мне все меньше и меньше хотелось покидать пределы спальни, а опустевшая пачка сигарет была единственным, что заставляло меня выходить из дому.

– Человек, доченька, это социально зависимое существо, – любила повторять мама, стоило ей увидеть признаки депрессии на моем лице. – Тебе нужно выбраться в люди. Нужно куда-то ходить, с кем-то общаться! Это не сложно. Тем более люди сами к тебе тянутся.

Пускай подобные речи казались бессмысленными и потому чертовски раздражительными, когда мне было пятнадцать, последняя фраза оказалась правдой. Сколько себя помню, людей всегда ко мне тянуло. Даже тихие, обычно замкнутые в себе собеседники без смущения открывали передо мной душу, когда я об этом не просила. Еще задолго до того, как я стала барменом, люди приходили ко мне за советом и без стеснения делились со мной своими самыми сокровенными тайнами. 

– Но я не люблю людей! – упрямо повторяла я из года в год, на что мать не менее упрямо отвечала:

– Это не имеет значения. Тебе не обязательно их любить, но не забывай о том, что ты тоже человек. 

– Ты должна выйти в люди, – заявила мама спустя пару недель после того, как Адам со мной расстался. – Общение и внимание общества – они нужны тебе, как и всем людям!

– Но я не люблю общество!

– А кого любишь? 

Я чуть было не сказала, что Адама, но вовремя осеклась. Как выяснилось на примере с Эриком, самовнушение – штука страшная. Если я и разрешала себе говорить о любви, должна была делать это исключительно в прошедшем времени.  

– Ох, доченька, ну что же мне с тобой делать? Все эти депрессии тебе просто не по возрасту. Ведь еще так молода! Вокруг все дети как дети, только ты на себе добровольно петлю затягиваешь! И чего ради? Да в мире нет мужика, который бы стоил таких страданий. Послушай мать и бросай это гиблое дело. 

Спустя четыре месяца я смогу дать своему состоянию куда более исчерпывающее объяснение, ну а сейчас мне вот-вот должно было исполниться двадцать. Я ничегошеньки не знала о маниакально-депрессивном психозе и могла сказать разве что что-то вроде:

– Дело не в мужике. Точнее, не только в нем.

– Ну что тебе стоит смотаться в центр? Погуляешь, подышишь воздухом, поболтаешь с подружками. Ноги разомнешь, в конце концов. Ты ж уже вторую неделю из постели не вылезаешь. Марш в душ и начинай приводить себя в порядок. 

Пройдет еще немало лет, прежде чем я научусь использовать внимание социума в борьбе с депрессией. 

– Тебе необходимо развеяться!

– В крематории развеюсь.

Затем я добавила, что там же меня приведут в порядок, но мать лишь глубоко вздохнула.

– Люди нужны тебе сильней, чем ты думаешь. Как бы тебе ни хотелось, чтобы это было не так.

Слова эти, как и многие другие схожие с ними наставления, теперь одно за другим всплывали в моей памяти. Очутившись в Симферополе, я проводила бессонные ночи за чтением, а днями в одиночестве сидела на террасе, пытаясь что-нибудь написать. Само собой, жизнь моя этим не ограничивалась. И все же о чем бы я ни думала, чем бы ни занималась, меня все время преследовало ощущение отрешенности и собственной ненужности. Назвать это чувство одиночеством было бы слишком просто. 

Да, окружающие всегда приходили ко мне за советом, тогда как мне не с кем было разделить свою боль. Равно как не с кем было разделить и моменты радости, которых становилось все меньше и меньше. Депрессия, о которой я как-то наивно думала как о пройденном этапе, мертвой хваткой держала меня в своих объятьях. Тоска мешала мне трезво мыслить, и я ненавидела ее за это. 

Еще больше я ненавидела себя. За постоянные слезы, то и дело одолевающие меня перепады настроения, за неиссякаемые печали и время, потраченное впустую. Но прежде всего я ненавидела себя за то, что после стольких лет мучительной работы над собой, я вновь оказалась заложницей своего психического расстройства. Я ненавидела себя за депрессию, считая ее роскошью, которой уже не могла себе позволить.

*Тебе нужно выбраться в люди*, напомнил голос в моих мыслях. Тихий, размеренный голос с едва различимыми нотками усталости. Голос моей матери.

*Тебе необходимо развеяться.*

Несмотря на кучу свободного времени, которым я располагала, моя социальная жизнь оставалась в плачевном состоянии. Каждое утро я просыпалась с четким пониманием того, что больше не хочу жить. Затем шла в душ, укладывала волосы, наносила на лицо косметику и выбиралась из дому. Ехала в центр, чтобы провести хоть немного времени среди других людей, но на душе становилось лишь тяжелее. Часами я бродила по раскаленным солнцем улицам в компании музыки и пачки сигарет и никак не могла найти себе места. Просто не знала, куда приткнуться. Казалось, этим летом я была единственным в этом городе человеком, которому не требовалось никуда бежать. 

И это сводило меня с ума.

Должно быть, жизнь в Симферополе и впрямь меня доконала, потому как я все чаще стала задумываться, а не найти ли себе работу? Втайне от Вениамина я обошла с чертову дюжину питейных заведений, так и не услышав ничего нового. Во многие бары требовался бармен, но с небольшим условием. 

– У нас официальное трудоустройство, – говорил каждый из встретившихся мне администраторов. – У вас крымская прописка?

На этом наш разговор обычно заходил в тупик. Некоторые, правда, спрашивали о виде на жительство, но в моем случае его получение обещало занять как минимум шесть месяцев.

– Есть вариантик оформить вас как беженку, – предложил управляющий небольшого паба, что находился в центре. 

Тучный мужчина с раздражающей привычкой коверкать слова и длинным именем, которое я никак не могла запомнить. Он стал первым крымским татарином, повстречавшимся мне за все время, что я жила на полуострове.   

– Политическую беженку? – уточнила я, пытаясь сдержать рвущийся наружу смешок.

– Обычно мы тут таким-с не занимаемся, но для вас я готов сделать исключеньице.

– И что же для этого нужно?

Управляющий выставил перед собой ладони, как бы показывая, что здесь нет ничего сложного.

– Плевое дельце, – ответил он. – Нужно всего-навсего отказаться от текущего гражданства. Написать заявленьице и в нем попросить политического убежища у властей Российской Федерации. Если хотите, поможем составить.

Я не хотела.


