# 68 {-}

– Видеть я больше не могу этот твой Симферополь! – бросила я, когда Вениамин в очередной раз отказался провести выходные вне города.

В десяти минутах ходьбы от нашего дома находилась автобусная остановка. Идущий в Ялту маршрут останавливался здесь каждый час, я не раз видела его, в одиночестве гуляя по окрестностям. Ехать было от силы минут сорок, но муж упрямо отказывался хоть на денек покинуть Симферополь. Никакие уговоры здесь не срабатывали. Веня словно прирос к этому городу, тогда как я в нем просто задыхалась.

– В Симфере есть все, что нам нужно, – упрямо повторял он. 

Это спокойствие уже начинало меня раздражать.

– Да будь он проклят! – выпалила я, и в слезах убежала в лес.

Со мной бывает.

И вот я вновь иду по пустынным улицам так ненавистного мне города. Вся в печали, соплях и слезах. Волосы развиваются на ветру, ревет гром и хлещет ливень – картина, достойная античной трагикомедии. Непередаваемое ощущение, скажу я вам. Думаю, каждому нужно хоть раз в жизни вот так вот пройтись.

Изредка на моем пути встречаются другие люди, но мне нет дела до их настороженных, а порой даже смущенных взглядов. Мокрые и продрогшие от холодного ветра незнакомцы спешат по своим делам, стараясь как можно скорее убраться с улицы. С высоты моей депрессии их действия всего лишь размытым фоном. Для меня они просто массовка, от которой никуда не деться.

Тем вечером я гуляла дольше обычного. Около пяти часов бродила вдоль озера, по лесу и горам, густо заросшим хвойными деревьями. Я не останавливалась ни на минуту, решив, что буду ходить то тех пор, пока усталость не выбьет последние нотки истерики из моих мыслей.

В итоге, рядовой ливень превратился в грозу, а мои волосы – в прическу Роберта Смита. Деверья вокруг стонали и сотрясались под давлением обрушившихся на них потоков ветра. Их ветви обламывались и с треском падали на землю, а голос грома становился все громче. В небе над озером то и дело сверкала молния, содрогая пространство своими ударами. Наконец, ее электрический заряд угодил в видавший виды дуб, что находился в паре-тройке метров от меня. Дерево воспламенилось быстрее, чем я успела подумать: «Хера се!», и только это заставило меня закончить с прогулкой. 

Мой обратный путь проходил мимо нескольких закусочных. Несмотря на непрекращающийся ливень, улица была пропитана настойчивыми ароматами жаренных крылышек, бургеров и прочих источников калорий. Это напомнило мне о том, что я не то ли с утра, то ли с прошлого вечера, и я вошла в одну из фастфудных. 

Но-но-но, сказала мне совесть, когда я вышла из закусочной. Какое-то время я помялась у порога, и зашла обратно, чтобы купить ужин для Вениамина.

Что тут скажешь, я никогда не умела как следует обижаться.

<div style="text-align: center;">***</div>

Последствия минувших кутежей мужа пагубно сказывались на моей психике, чего нельзя было не заметить. С каждым новым днем, проведенным в столице Крыма, Вениамин делался все более заботливым и обходительным. Коэффициент ласковых слов, сказанных в мою сторону, уже давно вышел за все допустимые рамки приличия. Веня делал комплименты моей внешности, хвалил мою стряпню, устраивал нам выходы в свет каждую пятницу и оставался все таким же страстным в постели, вот только… 

Вот только я никак не могла отделаться от этого нового ощущения. Паршивого чувства полнейшей отчужденности, которое накрыло меня еще на грязной обочине пустующей трассы. Когда за день до переезда в Симферополь я растерянно шагала вдоль затянутой тьмой дороги. Где-то там, между Керчью и Аджимушкайем, я в полной мере ощутила собственную ненужность и беспомощность.  

Ночь давила на меня своей чернотой. Куда ни глянь, я видела лишь укрывшую поля тьму да редкие очертания деревьев, что смутно виднелись где-то вдали от дороги. Если рядом и находились какие-нибудь дома, свет в них оставался выключенным, но, судя по всему, цивилизацией здесь и не пахло. Никаких тебе фонарей, светящихся вдали окошек чьих-то спален или огней проезжающих мимо попуток. Вокруг меня не было ни единого лучика света. 

Только ночь.

Сложно сказать, как долго я шла вдоль этой темной дороги. Пейзаж по обе стороны от меня оставался неизменным, и я давно потеряла к нему всяческий интерес. Денег у меня при себе не было. Сигареты так и остались лежать на балконе собутыльника моего мужа, а батарея телефона вот-вот обещала откланяться. К тому же, я знать не знала, где нахожусь. Даже не была уверена, что двигаюсь в нужном направлении. Просто шла километр за километром, чтобы хоть что-то делать.

Спустя минут тридцать, или около того, возле меня остановилась черная иномарка. 

– Тебя подкинуть? – спросил водитель.

Мне с трудом удалось подавить в себе желание подпрыгнуть от неожиданности: настолько бесшумным было его появление. 

Не останавливаясь, я окинула взглядом незнакомца. Тонкие черты лица, выступающие вперед скулы, густые брови, непослушные кудри, ясно синие глаза и небрежная щетина немного темней шевелюры – он до невозможности походил на Теда Банди в самом расцвете сил. 

Автомобиль приблизился к обочине и теперь катился рядом со мной на нулевой передаче. В тишине ночи я слышала каждый камешек гравия, что отскакивал от колес. Такой приглушенный стук, знаете. Бам-бам-бам, после чего шины еще каких-то полметра шуршат по гравию. Затем от них отскакивают все новые и новые осколки дороги. Ты опять слышишь их бам-бам-бам, и все повторяется.

Этот звук всегда напоминал мне припев одной из песен Лу Рида.

*Bum, bum, bum satellite of love*, сообщала мне дорога.

*Bum, bum, bum satellite of love.*

Водитель молчал. Он пристально наблюдал за мной в ожидании ответа, а я все никак не могла решить, что делать. Если не считать явного сходства с одним из наиболее продуктивных серийных убийц в истории, незнакомец выглядел вполне безобидно. Красивый, прилично одет и без шлейфа алкоголя. Само собой, его помощь пришлась бы мне очень кстати.

Соблазн запрыгнуть в невесть откуда взявшееся авто был слишком велик. Я попыталась вспомнить хотя бы один случай, когда решение сесть в машину незнакомца не привело к негативным последствиям, но так и не смогла. По натуре своей, будучи ночным жителем, я частенько привлекала внимание припозднившихся куда-то водителей. В каком бы городе я не находилась и куда бы не направлялась, рано или поздно на горизонте показывалась одинокая машина с товарищем, готовым предложить мне помощь. 

Короче говоря, одиноких водителей тянуло ко мне как магнитом. Возможно, у меня был вид дамы попавшей в беду, и это попросту пробуждало в них базовые мужские инстинкты, но женщина ни разу не предложила мне помощь. 

Как ни крути, а толку в этом по-прежнему было мало. Последняя поездка с незнакомцем закончилась его попыткой склонить меня к оральному сексу. Да такой настойчивой, что пришлось удирать через все кладбище. До сих пор помню сковавшее меня отвращение, когда таксист как бы невзначай коснулся моих собранных на затылке волос. 

«Настоящие?» – поинтересовался он.

Еще мгновенье, и от прически не осталось и следа. С утра мне пришлось провести у зеркала не менее двадцати минут, чтобы уложить волосы так, как того требовал этикет работы за барной стойкой. Ни один волосок не должен был выпасть из пучка на протяжении рабочего дня, иначе выговора от управляющей не миновать. Непослушание вьющихся локонов заставляло меня тратить уйму времени на прическу, но сальные пальцы незнакомца разрушили ее за считанные секунды. 

Таксист ухватил меня за волосы и силой наклонил в сторону ширинки своих штанов. Несмотря на охватившие меня шок и возмущение, я тут же уловила затхлый запах его промежности.

Этот смрад продолжал стоять в носу, когда я выскочила из машины. Я продолжала слышать его и когда всех ног помчалась в сторону входа на городское кладбище, и даже когда пряталась за одним из надгробий. Таксист выпрыгнул следом. Правда, с небольшой задержкой, вызванной новообретенными проблемами со зрением. 

Быть может, других девочек с детства учили манерам, правильной походке и прочим социально приемлемым глупостям, но я выросла в девяностые. И это не раз спасало мою честь, если не жизнь. 

Прежде чем стать государственным адвокатом, мой отец несколько десятилетий прослужил в милиции. Он посвятил молодость борьбе с организованной преступностью и как никто другой знал обо всех тех ужасных вещах, что с наступлением ночи происходили на улицах. Местность, где прошло мое детство, по сей день входит в тройку наиболее криминальных районов города, тогда как сам Николаева уже давно числится в топе самых опасных городов Украины. Еще с тех самых девяностых он успешно держит лидерство по части количества зафиксированных убийств. 

Тем не менее, отец никогда не забивал мне голову подобного рода статистикой. Он всего лишь достал из серванта ветхую книжечку с грубыми листами из серой бумаги, и заставил пообещать, что я прочту каждую из ее страниц. Согласилась я почти сразу же, ведь мануал не превышал карманных размеров, и только погодя заметила, насколько мелкий шрифт заполнял страницы. 

Так в моих руках оказалось краткое пособие по самообороне, которое в свое время служило Библией будущим хранителям правопорядка. Несмотря на свои крохотные размеры, буквы в книге были объемными и как будто вдавленными внутрь. Должно быть, ее  напечатали на одной из тех старых пишущих машинок, много-много лет назад, но даже это не добавляло шарма содержанию учебника. Читать литературу вроде этой не так уж просто, когда ты ребенок дошкольного возраста. Каких-то две-три страницы, и мои мысли уносились прочь от скуки монотонных абзацев и сухо изложенных терминов. То ли дело практические занятия!

