# 69 {-}

Когда мне было пять, папа впервые взял меня с собой на опознание тела, а тем же вечером по многочисленным просьбам отвел меня в морг. Им оказалось старое кирпичное здание, которое я не раз видела прежде и о котором и подумать не могла, что это и есть морг. Оно находилось около областной психиатрической лечебницы, откуда мне удалось феерически сбежать тринадцать лет спустя. 

У входа уже стоял ментовской бобик. Из него выскользнул молодой сержант, стоило нам миновать ворота. Он перекинулся парой слов с курившими под стенкой санитарами и характерной для своей профессии походкой зашагал нам навстречу.

«Как всегда, секунда в секунду, Валерий Петрович, – обратился он к моему отцу. – Прозектор как раз закончил осмотр».

Сержант распахнул перед нами дверь и, держа отца за руку, я с трепетом в сердце ступила на порог морга первой городской больницы.  

То, что скрывалось внутри, поразило меня так же сильно, как и разочаровало. На протяжении последних месяцев я была убеждена, что хочу стать патологоанатомом. Начиная с того хмурого дня у реки, которым я узнала о разводе родителей, я слезно просила папу отвести меня в морг, и теперь с детской жадностью впитывала увиденное.

Внутри все оказалось совсем не так, как я себе представляла. Отечественные морозильные камеры больше походили на изжившие свое холодильники для мороженного, чистота и стерильность явно не были здесь в почете, а этот запах… О таком не предупреждали ни в Комиссаре Рексе, ни в Кобре-11, ни в одном другом полицейском сериале моего детства. 

«Что с ее ногами?» – удивленно спросила я, разглядывая те немногие части тела, что не были скрыты пожелтевшей простыней. 

Лица девушки, лежавшей на столе, – кстати говоря, также абсолютно не таком, каким в моем представлении был стол патологоанатома – тоже не было видно. Его прятала под собой белоснежная марля, зачем-то оставляя просвет для левой щеки убитой, но для первого раза мне и этого было достаточно.

Конечности покойной девушки повсеместно укрывали разных размеров пятна, цветовая гамма которых охватывала все сто восемьдесят оттенков синего и сто девяносто шесть вариаций фиолетового, существующих в палитре Пантеон. Ярче всех оказалось самое масштабное из пятен; оно находилось на лице мертвой девушки. Сложно было поверить, что такие штуки способны сами по себе появляться на человеческом теле. Казалось, кто-то из сотрудников морга случайно перепачкал щеку покойницы краской.

«Зачем здесь это пятно?» – спросила я, указывая на самую яркую отметину.

«Это значит, что тело двигали», – ответил отец. 

Затем он объяснил, как по трупным пятнам можно определить, в каком положении человек находился во время смерти, когда наступила смерть, а также понять, что с телом делали после нее, и я окончательно влюбилась в патологическую анатомию.  

Помнится, я еще спросила, будут ли у меня когда-нибудь пятна вроде этих. Ответ поступил незамедлительно.

«Нет, если будешь слушать, что я тебе говорю».

Тогда папа подозвал своего помощника и на примере юного милиционера показал, куда нужно бить противника: шея, солнечное сплетение и пах. Шея. Солнечное сплетение. И пах. Шея, солнечное сплетение и пах – отец повторил эти слова раз десять, пока, наконец, не убедился, что я их запомнила, а потом произнес то, что я и так уже слышала с полсотни раз.

«Если не знаешь, что делать, всегда атакуй глаза. Зрение для нападающего важней всего остального. Когда на помощь звать некого, в случае опасности – он вытянул перед собой руку и оттопырил два пальца, демонстрируя жест мира во всем мире, – просто два пальца в глаза и беги как можно дальше».

«В случае опасности – просто два пальца в глаза…» – я слышала эти слова сколько себя помнила. Настолько часто, что они волне могли бы быть первыми словами, которые я услышала, попав в этот мир.

Воображение каждый раз рисовало мне брызги крови, пустую глазницу и вытекающий из нее глаз, что больше походил на содержимое сырого яйца, и я взвизгнула:

«Но это же такое фу, папочка! А вдруг я его этим убью?»

«Это вряд ли, но не велика беда, – все так же спокойно ответил отец. – Тут либо ты на кладбище, либо он. Когда такое происходит, нет места никаким фу. Есть вещи и похуже, доченька.»

«Как запах смерти?»

«Еще хуже, – к тому моменту отец уже закончил с работой и собирался сводить меня в кафе «Малыш» на мороженное. – Не забывай об этом.»

И я не забыла.

Прошло еще семнадцать лет, прежде чем мне впервые пришлось воспользоваться отцовским советом. На практике, все оказалось куда проще. Я сделала это машинально, о сомнениях и речи быть не могло. Просто засадила ногтями в глазницы пытавшегося меня трахнуть таксиста, нащупала дверную ручку и пулей вылетела из салона авто.

«Тебе пизда!» – с нечеловеческим ревом пообещал водитель.   

 Он миновал несколько надгробий, прикрывая ладонями пораненные глаза и выкрикивая мне вслед ругательства, но так и не решился зайти вглубь кладбища. В своей темноте, та ночь ничем не уступала сегодняшней, и мне просто повезло. Я хорошо знала местность.

