# 70 {-}

– Так что? – спросил Тед Банди, прерывая череду неприятных воспоминаний, что одно за другим будоражили мои мысли.

Его тонкие губы растянулись, демонстрируя полную дружелюбия улыбку. Увидев ее, я уже наверняка знала, что не сяду в катившийся рядом автомобиль. Губы водителя приветливо улыбались мне, но остальные части его лица оставались без изменений. Кустистые брови не поднялись ни на миллиметр, а вокруг глаз не появилось гусиных лапок и прочих мимических морщин, что обычно сопровождают искреннюю улыбку. Об этом говорилось в стареньком пособии по самообороне. 

Тед Банди улыбался лишь ртом, и это мне не понравилось. 

– Садишься? 

Я отрицательно покачала головой, чем немало удивила предложившего мне помощь мужчину, и тот спросил:

– Что не так? 

– Фары дальнего света, – ответила я. 

Они не были включены. Вот из-за чего я не заметила приближения автомобиля. Теперь мне стало ясно, почему его появление сразу же заставило меня насторожиться. Ну кто будет разъезжать посреди ночи, еще и в такой глуши, без огней дальнего видения? Разве что серийный убийца.

Об этом, кстати, тоже говорилось в пособии. 

– Я это учту, – загадочно произнес Тед Банди, и я увидела, что он больше не улыбается.

Незнакомец резко развернул машину, чтобы та выплюнула из-под колес еще больше гравия.

*Bum, bum, bum satellite of love*, пропели камни, когда он выжал педаль газа. 

Мужчина с внешностью Теда Банди исчез во тьме, из которой и появился, оставив меня в полнейшем замешательстве стоять у обочины. 

Пускай подозрительного незнакомца больше не было рядом, отсутствие денег, сдыхающий мобильный и прежде всего Вениамин, нагадивший мне в душу, никуда не делись. На дворе стояла глухая ночь, а я застряла в какой-то богом забытой дыре и не имела ни малейшего понятия, где именно нахожусь. Идти мне было некуда, как неоткуда было ждать помощи. Обида и задетое самолюбие не позволяли мне вернуться обратно. Но это не удалось бы мне и при всем желании. Первые полчаса после конфликта были как в тумане. Я не помнила, как вообще попала на эту трассу.

Кому позвонить я тоже не знала. На всем полуострове Вениамин был единственным близким мне человеком, но по иронии судьбы именно он стал виновником моего плачевного положения. Размышляя об этом, я вдруг осознала, какой беззащитной я стала. С горечью поняла, что стала зависимой от собственного мужа, и груз тотальной беспомощности обрушился на мои плечи. А хуже всего оказалось то, что все это так не было похоже на меня.

Беззащитность? Вряд ли найдется и один человек, что хоть раз применял это слово в мою сторону. Тем не менее подавленность, бессилие и беззащитность были всем, что я ощущала, стоя на пустынной трассе Керчь-Аджимушкай. В них можно было винить кого угодно, для этого впереди ждала целая ночь, но я начала с себя. 

Собрав остатки сил, я старалась взять себя в руки, но на деле лишь злилась на собственную беспомощность, пока новая мысль не заслонила собой все предыдущие.

*Любовь делает меня уязвимой.*

Такая простая, но при этом такая тугодогоняемая мысль. Почему она прежде не приходила мне в голову? 

*Потому что никто не ждет этого от любви*, ответил внутренний голос, мастерски копируя тон моей матушки.

И он был прав. 

Вениамин с его сладкими речами и холодящей кровь бранью, Вениамин с его горячими поцелуями и звонкими пощечинами, Вениамин с его очаровательной улыбкой и сардоническим смехом, Вениамин с его нежными объятьями и тасканием за волосы, Вениамин с его влюбленными глазами и стальным взглядом, полным уничижения, – все это делало меня уязвимой. Как он мог этого не понимать?

*Он понимает*, раздалось в моих мыслях.

Я отрицательно замотала головой, словно надеясь, что благодаря этому жесту неприятные мысли выпадут памяти, как грибы из переполненного лукошка, но голос продолжал: 

*Он все прекрасно понимает. Твой муженек хочет, чтобы ты от него зависела. Целиком и полностью.*

– Бред какой-то! – неестественно громко возразила я, и звук моего голоса иглой пронзил тишину загородной ночи.

*Это все бред*, я твердила себе об этом без остановки, приписывая неприятные мысли расшатанным нервам, психическому расстройству и невозможности трезво смотреть на мир. 

Во время неоднократных попыток лечения терапевты постоянно говорили мне об этом. Мол, биполярное расстройство искажает восприятие, что, в свою очередь, мешает мне здраво оценивать действительность. По мнению докторов местной психиатрии, биполярка заставляла меня слишком многое принимать близко к сердцу. Они считали, что большая часть того, что происходило в моей жизни, была вовсе не такой уж болезненной, как мне виделось. Что я смотрела на все сквозь призму негатива, неосознанно приписывая окружающим неприятные черты характера, которых на самом деле никогда у них не было. И что еще важней, психиатры всегда заостряли внимание на моем недоверии к людям. Они слышать не хотели об интуиции и были убеждены, что я – само собой, все так же неосознанно – выискивала в поведении других людей злые умыслы и прочий отрицательный подтекст. Врачи говорили, что я воспринимала бы жизнь с куда меньшей трагедией, будь моя психика в норме.

Хоть я и скептически относилась к отечественной медицине, ни один час терапии не исчез из моей памяти. Я помнила каждый вывод, к которому так или иначе приходили работавшие со мной психологи и психиатры. Знала о своей склонности драматизировать и на протяжении долгих лет училась жить заново. Так, чтобы своей нездоровой психикой не отравлять собственную жизнь и жизни тех, кого я любила.

*Он все прекрасно понимает*, – но вот одна-единственная мысль положила начало моему недоверию. Не без удивления я поймала себя на том, что испытываю презрение в сторону любимого мужчины. 

Мозг отказывался воспринимать эту информацию за неимением прямых или косвенных улик, но какая-то часть меня уже и так знала, что она была правдивой. Осознание этого факта, такое же резкое и внеплановое, как и все события этой ночи, натравило на мою душу новую бурю эмоций. Преимущественно негативных. Я отмахивалась от них как могла, но был ли смысл?

*Твой муженек хочет, чтобы ты от него зависела.*

Стоило моим опасениям преобразоваться в слова, они в мгновение ока свели в могилу весь мой внутренний феншуй.       

Связи не было, сигарет тоже. Все так же некому позвонить, некуда пойти, негде искать помощи и даже выплакаться некому, а до наступления утра по-прежнему как до Луны. Я обхватила голову руками и села на гравий, стуча зубами от холода. Этот раздражающий звук вскоре вызвал мигрень, верную спутницу всех моих странствий. Чем больше я пыталась найти решение проблемы, тем сильнее становилась головная боль. Длилось это до тех пор, пока из глаз не посыпались искры. Тогда я откинулась на спину и улеглась прямиком посреди трассы.

– Что же мне делать дальше? – спросила я у звезд.   

Насколько мне помнилось, в пособии об этом ничего не говорилось.

