# 71 {-}

Так вот, со времени переезда в Симферополь Вениамин заметно переменился. Нежданно-негаданно он вдруг стал куда более ласковым и любящим. Это проявлялась в каждой мелочи, что непременно бы осчастливило любую влюбленную девушку. Любую нормальную девушку, но только не меня. 

Чем заботливей становился мой муж, чем больше участия проявлял, тем более неестественным казалось мне его поведение. Обычно вымотанный после работы, вечерами Веня вел себя оживленно. За ужином он сделался как никогда болтливым, будто пытался этим как-то компенсировать мою молчаливость. 

Так пролетело еще несколько недель. 

Происходящее стало выглядеть максимально нереалистично, когда, вернувшись с работы, Вениамин впервые на моей памяти добровольно взялся за генеральную уборку. Он мыл, тер, подметал и пылесосил без остановки все, что видел на своем пути, чем немало меня озадачил. Однако, покончив с домашними хлопотами, Веня отправился к соседу и до наступления темноты помогал тому покрыть крышу шифером. Вернулся он с довольной улыбкой и глубоким порезом на предплечье, из которого струились потоки алой крови.

– Спасибо, любовь моя, было очень вкусно, – произнес Веня, расправившись с ужином. 

Я как раз заканчивала накладывать ему на руку повязку.

– Эти крылышки в соевом соусе – ну просто объеденье! Что ты в них добавляешь?

– Соевый соус.

Я никогда не мнила себя великим кулинаром.

После ужина Вениамин вымыл посуду и поставил на плиту чайник. 

– Какая же ты у меня красивая, – ласково произнес он и уволок меня в спальню еще до того, как чай успел настояться. 

Чем не идеальный муж? 

Казалось бы, живи и радуйся, но! Изменения в его поведении напрягали меня все больше и больше, а эпизод с шифером так и вовсе застал врасплох. Обсуждать личные темы с кем-нибудь из родителей мужа, да к тому же за его спиной я не решалась, но совет знающего человека мне бы не помешал. Пришлось действовать методом исключения. Я вычеркнула из списка собутыльников Веньки, его бывших и нынешних коллег, постоянных клиентов, ставших приятелями, а также всех женщин, что когда-либо имели виды на моего мужчину. В конечном счете в моем воображаемом списке осталось всего одно имя, так что на следующем перекуре я взяла в руки телефон и набрала номер сестры Вениамина.

– Твой брат ведет себя странно, – сказала я после традиционного обмена любезностями.

– Странно типа как?

– Он очень изменился после переезда. Вдруг стал таким общительным и гиперактивным.

– Опять бухает, что ли? Веня стал бить тебя или типа того? 

Вале совсем недавно исполнилось восемнадцать. Домашнее насилие она упоминала с той же небрежностью, с какой когда-то это делала я. Так, словно это какой-то инопланетный вирус, который никогда тебя не коснется.

– Нет. Он уже месяц как не напивался.

– Так я не пойму, че ты тогда паришься? 

Я ответила на этот вопрос настолько развернуто, насколько это было возможно. Рассказала обо всем, кроме того, что касалось постели, и закончила последним эпизодом: с многочасовой уборкой и соседской крышей.

– А может, ты и не зря паришься, – после небольшой паузы заметила Валя. – В нашей семье обычно начинают убираться, когда случилось что-то плохое. Или если тебя что-то гложет.

Мне тут же вспомнились комки шерсти, слои пыли и полчища блох, что искусали мои ноги, стоило мне сесть на диван в гостиной матери Вали и Вениамина, зассанные котами ковры, несчастные собаки, коим никогда не мыли лапы, и мать моего мужа, которая только и делала, что рассказывала, какими безрукими засранками оказывались пассии ее сына. 

В общем, я не удержалась.

– Ну, судя по тому, что я видела, сейчас у вас в семье все в порядке.

Шутку Валя не поняла.

Мы еще немного поболтали о всякой девичьей ерунде, и я повесила трубку. 

– И что же тебя гложет, Гилберт? – спросила я у спавшего поперек кровати мужа.

Разговор с его сестрой дал мне больше вопросов, чем ответов.

