# 72 {-}

Очередным августовским вечером мы взбирались на гору, совершая традиционный ритуал возвращения домой. Как и всегда, Вениамин сжимал в зубах сигарету, создавая вокруг себя табачное облако. Он красочно жестикулировал, с воодушевлением рассказывая мне о своих карьерных планах. 

Добравшись до ведущей на нашу улицу тропинки, я остановилась перевести дыхание, после чего прервала монолог мужа все тем же вопросом:

– Ну почему? Почему именно этот блядский город?

– Потому что я считаю, что здесь нам будет лучше всего, – по обыкновению спокойно ответил мой спутник.

– Но я терпеть не могу Симферополь, Веня! Я возненавидела его еще в тот день, когда ты пытался познакомить меня с начальством.

– Глупости.

Я повернулась к Вениамину и, стараясь звучать как можно серьезней, произнесла: 

– Это не глупости, дорогой. Это то, с чем мне ежедневно приходится сталкиваться. То, что делает меня несчастной, понимаешь? Мне абсолютно не нравится Симфер, и я искренне не понимаю, чем он так полюбился тебе. Мы живем здесь всего месяц, а мне уже рвет крышу. Что же будет через год?

– Все так же будем жить вместе, но уже со штампами в паспортах, – чуть ли не мечтательно ответил Веня.

Он напрочь игнорировал истерические нотки, что уже начинали сквозить в моей речи.

– Но я не хочу жить в Симферополе! Никогда не хотела! Неужели ты этого не понимаешь?

– Не понимаю.

– Симферополь, да он же как две капли воды похож на мой родной город! Я чувствовала себя чужой в Николаеве на протяжении многих лет, но он никак не хотел меня отпускать. Знал бы ты, как это невыносимо: провести свою жизнь в месте, которому ты не принадлежишь. Так вот, Симферополь – это, по сути, тот же Николаев, только воздух грязнее и жителей тысяч на сто меньше. А потом ты приходишь ко мне и заявляешь, что здесь нам будет лучше всего. Здесь, в Симферополе, что так напоминает город, из которого я всю жизнь пыталась сбежать. Ты вообще в курсе, что местоимение «мы» относится как минимум к двум людям? 

Вероятно, Веня нашел мой вопрос риторическим. Он ничего не ответил, но я и без того прекрасно помнила все его аргументы. В основном, их список состоял из «В Симферополе мне стали больше платить!», «В Симферополе мы смогли снять квартиру с ремонтом!» и, конечно же, «Симферополь – это же самый центр Крыма!».

Как выяснилось, теперь в этом списке было одним аргументом больше.

– Из Симферополя легче всего уехать. В любом направлении.

Из моих губ вырвался нервный смешок.

– А толку-то? Ты и на денек не можешь уехать из своего самого центра Крыма.

Еще одна из моих реплик осталась без ответа.

– Послушай, Веня, я могла бы прожить здесь какое-то время. Не стала бы возражать, если это нужно для твоего промоушена и черт знает чего еще. Вот только я же вижу, что этого недостаточно: ты хочешь пустить корни в своей драгоценной столице Крыма. Ты схватился за Симферополь как за последнее, что есть в твоей жизни, и я даже не хочу знать почему. Но я хорошо знаю, чем все это закончится.

– Знаешь?

– О да. Скорей всего, ты пообещаешь, что со временем мы переедем жить в другое место, подальше от Симферополя. При первой же возможности или когда ты будешь доволен своим карьерным ростом, и пройдут годы, прежде чем я пойму, что этого так никогда и не произойдет. Но к тому времени я уже не смогу представить свою жизнь без тебя в ней. Блядь, да я и сейчас не могу представить свою жизнь без тебя!

– А я уже давно не могу представить свою жизнь без тебя, Васляева. Я предложил тебе выйти за меня, как только это понял.

– Так вот, к тому времени я уже не смогу представить свою жизнь без тебя. Поэтому я никуда не уеду. Я останусь здесь, с тобой, пускай и буду чувствовать себя загнанной в угол. С каждым днем меня все больше и больше будет накрывать уныние. Затем оно перерастет в тоску, что вскоре станет печалью. Печаль превратится в грусть, которая будет стремительно увеличиваться, и в один прекрасный день собственное будущее покажется мне окончательно безнадежным. Я начну бояться потерять тебя, так что буду держать себя в руках как можно дольше, но я себя знаю. Притворяться всю жизнь у меня не получится. Безысходность сведет меня с ума. Рано или поздно я сорвусь с катушек, уйду в глубочайшую депрессию. Не исключено, что пару-тройку раз попытаюсь наложить на себя руки, даже если и нет…

На этом моменте я прервалась, чтобы достать из сумки сигареты. Подкурила одну из них, набрала в легкие дыма и, выдыхая, продолжила:

– Я вновь буду пить, не просыхая, до тех пор, пока планка моих моральных ценностей не опустится ниже плинтуса. Один за другим я начну совершать плохие, необдуманные поступки, и мне не будет никакого дела до их последствий. Но ужасней всего то, что когда-нибудь я просто забуду, каково это – быть счастливой. В лучшем случае я стану нервной и замкнутой, в худшем – превращусь в агрессивную истеричку. Мне будет плевать на все то, что когда-то могло меня осчастливить. Ни одна из этих вещей больше не сможет вселить хоть немного радости в мое сердце. Я разучусь испытывать положительные эмоции и сделаюсь безразличной ко всему, что может их вызвать. Даже к тебе. Тогда во мне не останется ничего, кроме отчаянья, что двадцать четыре часа в сутки будет разрывать меня на части. Оно-то меня в итоге и доконает.

Я замолчала и выдержала паузу, дожидаясь, пока до Вени дойдет смысл этой импровизированной тирады. Когда минута молчания закончилась, я обхватила лицо мужа руками и, пристально глядя в любимые глаза, спросила:

– Разве о такой жене ты всегда мечтал?

По всей видимости, сраженный моим монологом, Вениамин не сразу смог обрести дар речи. Мы так и продолжали стоять на склоне горы, глядя друг другу в глаза, пока Веня не накрыл мои ладони своими.

– Я тебе не верю, – тихо сказал он.

– А вот стоило бы…

– Нет-нет-нет, радость моя, я совсем тебе не верю. Ты самый любящий, самый верный и искренний человек из всех, кого я встречал. Все это прозвучало очень убедительно, но Веньку ты так просто не проведешь. Ты вообще не такая, какой себя рисуешь. Я-то тебя знаю.

– Ты не знаешь меня в депрессии.

– Да ладно!

– В настоящей депрессии, я имею в виду. Ты не знаешь, что такое депрессия, и меня в таком состоянии ты тоже не знаешь. На самом деле никто не знает, а те, кто пытался узнать, бежали из моей жизни как крысы с тонущего корабля.

– Всего лишь трусливые людишки, – Вениамин крепче сжал мои руки. – А я вот никуда от тебя не сбегу.

Я улыбнулась ему печальной улыбкой.

– Прости, но теперь я тебе не верю.

– Окстись, окаянная! Не хочешь ли ты мне сказать, что потеряла веру в любовь мужа своего?

– Я хочу сказать, что та, кого ты называешь своей женой, и та, кем я становлюсь на пике депрессии – это два совершенно разных человека.

– Ты преувеличиваешь, – сказал Веня, но уверенности в его голосе поубавилось. 

– Совсем нет. Но мне бы очень хотелось, чтоб я преувеличивала.

Похоже, до него, наконец, стало доходить, что я говорила вполне серьезно.

– И что мы с этим будем делать? – после длительных раздумий спросил муж.

– Не знаю. Может, мне стоит уехать, пока еще не поздно?

Вениамин одарил меня скептическим взглядом.

– Не поздно для кого, Лиза?

– Для нас обоих.

– Вот оно что! А я-то, дурак, думал, что местоимение «мы» относится как минимум к двум людям! Но если тебя интересует мое мнение, а я все-таки надеюсь, что оно тебя интересует, твое «не поздно» для меня уже давно пиздец как поздно!

Он был прав, и я это понимала.

– Веня…

– Я говорил тебе об этом весной и скажу сейчас. Если ты решишь меня бросить, я это пойму. Скорей всего, я уйду в длительный запой и буду трахать все, что движется, но это никогда не сделает меня счастливым.

Мой мужчина с яростью отшвырнул остатки сигареты. Нахмурившись и сложив губы трубочкой, как это всегда случалось во время серьезных раздумий, он развернулся на девяносто градусов. Вениамин подпер бока руками и замер в этой позе, глядя на раскинувшиеся вдали горы.

Не проронив ни слова, он простоял так почти три минуты. Две минуты и пятьдесят четыре секунды, если быть точнее. Стоя позади, я мысленно отсчитывала время. Не то чтобы это было моим хобби. Просто тщательная концентрация на мелочах вроде этой мешала тягостным думам проникнуть в голову.

– Посмотри мне в глаза и скажи, что пока еще не поздно расстаться, – сказал Веня, по-прежнему держась взглядом за горные вершины.

– Не могу.

– Потому что ты никогда не врешь?

– И поэтому тоже.

Он повернулся в мою сторону, и я увидела то, чего никак не ожидала увидеть. Лицо моего возлюбленного искажала невыразимая боль. Почти такая же едкая и отчаянная, как та, что не раз смотрела на меня из зеркала.

– Тогда зачем ты это сказала?

– Ох, милый, я совсем другое имела в виду.

– Например?

Во избежание новых трагедий мне пришлось помедлить с ответом, но нужные слова никак не хотели находиться, так что я просто сказала:

– Я хотела сказать, что если все равно мне придется уехать… В общем, лучше сделать это прежде, чем мы натворим глупостей.

– Натворим глупостей?

– Прежде чем мы распишемся, Венька.

Пару секунд лицо моего мужа выражало искреннее недоумение. Потом он залился звонким смехом, от звука которого у меня тут же отлегло от сердца.

– Натворим глупостей! – сквозь хохот говорил Веня. – Так вот как ты называешь священные узы брака!

– Ни одному штампу в паспорте еще не удалось помешать супружеской измене. Если подобное когда-нибудь случится, я буду первой, кто признает эту печать священной. Ну а пока этого не произошло, она все так же остается для меня бесполезным штампом в паспорте.

– Вот! Вот теперь я узнаю свою деточку!

Только когда обстановка окончательно разрядилась, я почувствовала, как сильно на самом деле устала. Пришла пора возвращаться домой.

За то время, что мы выясняли отношения, сиявшее над горными пиками солнце успело полностью скрыться за горизонтом, а я этого даже не заметила. Как на протяжении последних месяцев не замечала и других закатов и рассветов. Когда я это поняла, поздние сумерки уже обволакивали город своей вязкой пеленой. Они нагоняли на меня сонливость, и я шагнула на тропинку, что вела домой.

– Куда ты уходишь? – удивился Веня.

Он выглядел абсолютно счастливым и, похоже, давно успел забыть, что мы возвращались домой.

– В депрессию.

Мой муж широко улыбнулся и театрально поднял бровь.

– А ты разве уже не в ней? – спросил он, чем одновременно рассмешил и разозлил меня.

– Мне напомнить тебе, после чего я уже которую неделю не могу прийти в себя? – эти слова были первым, что пришло мне в голову, и тут речь шла вовсе не о переезде в Симферополь.

Озвучивать свои мысли я не стала. Слишком уж негативными они были, и честно говоря, меня уже понемногу начинало мутить от обилия негативных мыслей. К тому же я поняла, что ни керчинская попойка, ни то, что произошло после нее, теперь не имело никакого значения. Оставленная событиями той ночи боль не покидала меня на протяжении целого месяца. Она стремительно разрасталась где-то внутри, закрывая собой остальные чувства, а потом вдруг исчезла. Так быстро и просто, словно ее никогда и не было, и я даже толком не могла сказать, когда именно это произошло.

