# 75 {-}

Сколько себя помню, смерть всегда манила меня своей таинственностью. Морги, гробы, крематории и надгробные плиты – в общем, все то, к чему питают страх все нормальные люди, с ранних лет вызывало трепетное благоговение в моей душе. Кладбища быстро стали для меня привычной средой обитания, а их постоянные обитатели – лучшей компанией. 

Где бы я ни находилась, некрополь вселял покой и позволял укрыться от городской суеты. Я могла часами гулять, рисовать и лежать в траве с любимой книгой в руках. Порой я даже выполняла здесь домашнее задание, а, повзрослев, стала работать над рукописями. Какие бы мысли ни тяготили мне голову, на выходе из кладбища я знала, что с ними делать. Подобно морю и лесу, место меня успокаивало, помогало разобраться в себе и навести в мыслях порядок. Только вот, в отличие от моря или леса, кладбище можно было встретить в любом городе.

По сей день помню свое первое кладбище. Мне еще не было четырех лет, когда поезд привез нас с матерью в ее родной город, что находился к востоку от Николаева. Мы купили цветов и отправились на Максимовское кладбище, где под огромной гранитной плитой лежала моя бабушка.

Памятник девочки с книгой одним из первых встретился на пути. Он выглядел свежим, и, обойдя статую, я увидела цифры: 1988–1995. Должно быть, когда-то отец видел меня великим математиком. Он с ранних лет учил меня не только законам логики, но и простейшим подсчетам. К тому моменту таблицу умножения я знала на зубок и без труда подсчитала, что памятнику не было и года, а покоившейся под ним девочке – всего семь лет.

Было и всегда будет. 

На Максимовском кладбище было много таких могил, и это впервые заставило меня осознать собственную смертность. Оказывается, дети тоже могли умирать так же часто, как взрослые. До этого момента смерть казалась мне исключительно прерогативой стариков. 

– Не страшно? – заботливо спросила мама, заметив внимание, с которым я рассматривала окружавшие нас кресты, памятники и надгробные плиты.

– Не-а, – безмятежно ответила я.

Мне было жутко интересно. 

Это было время проводков. Дни, когда народ отовсюду сходился на кладбище, чтобы помянуть близких, и по причинам, что не ясны мне и по сей день, собирался группками, которые пили и ели на их могилах. В такие дни кладбище пользовалось огромной популярностью среди бездомных, пьянчуг и цыган. Последних здесь было особенно много. По традиции люди оставляли на могилах родственников алкоголь, конфеты, печенье и прочие сладости. С громадными серыми мешками в руках цыганские дети кружили вокруг плит, дожидаясь шанса сгрести в них угощения для мертвецов. 

Еще одной традицией было угощать сладостями других. Незнакомцы то и дело подходили друг к дружке, чтобы вручить наполненный конфетами пакет. Мама объяснила мне, что таким образом они поминают покойников, но я как-то не уловила здесь логической взаимосвязи.

Через пару крестов от нас копошилась старушка. Опираясь на палочку, она пыталась расчистить траву на могиле супруга, с которым периодически разговаривала. На вид бабушке было лет триста, и ее действия больше напоминали замедленную съемку. Я таращилась на эту старушку довольно долго, пока моя добродушная матушка не подумала, что мне ее жаль.

– Вот, – мама протянула мне мешочек со сладостями. – Можешь дать это ей.

Смысл этого действия оставался для меня совершенно не ясным, но отказываться я не стала. Только спросила:

– А что говорить?  

– Не обязательно что-то говорить, – ответила мама. – Просто скажи что-нибудь вежливое, когда она тебя поблагодарит.

*Звучит несложно*, решила я и направилась к старушке.

Подойдя ближе, я молча протянула ей мешок. Старушка этого не заметила. Она была слишком занята своими хлопотами, и я еще с минуту простояла с вытянутой вперед рукой. Затем втихаря достала из пакета несколько конфет, по-быстрому от них избавилась и подошла еще ближе.

Теперь старушка находилась в полуметре от меня. Я вновь протянула ей поминальные сладости, но она по-прежнему меня не замечала.

– Это вам, – решилась заговорить я.

Медленно-премедленно старушка повернула голову. Ее лицо растянулось в беззубой улыбке, демонстрируя больше морщин, чем я видела за всю свою жизнь.

– Спасибо, доця, – ответила старушка.

Она взяла из моих рук пакет с непонятными словами:

– Царствие небесное и земля пухом.

Все шло по плану. Оставалось только сказать что-то вежливое в ответ. Ну я так и сделала.

– Спасибо большое. И вам того же!

Услышав эти слова, старушка заметно переменилась в лице, но прошел еще не один год, прежде чем я поняла, что в этом диалоге пошло не так.

По возвращении домой мне всю ночь снились серые плиты, надгробья и кладбищенские тропинки. Но в этих снах не было ничего пугающего. Они больше напоминали красочные впечатления, с какими обычно возвращаются из путешествий в экзотические страны. Проснувшись, я чувствовала себя умиротворенно, если не считать желания вернуться на кладбище. И чем больше времени проходило, тем сильнее становилось это желание. Я и понятия не имела, что в нем было что-то ненормальное, пока мне об этом не сказали.

<div style="text-align: center;">***</div>

– Можешь сказать мне, что ты здесь нарисовала? – спустя год спросила детский психолог.

Этими словами начинался практически каждый из ее вопросов.

Детсадовским воспитателям настолько не понравилось мое творчество, что они отправили меня в кабинет психолога. Поначалу это казалось мне обидным, но доктор задавала мне много вопросов и проводила различные тесты, а это было гораздо интересней того, чем они занимались в садике.

– Вот это солнышко, вот это тучки, – ответила я, указывая на соответствующие части рисунка, – вот это холм, вот это могила, а вот тут скамейка возле нее, вот еще одна могила и еще одна.

– Некоторых воспитателей смущают твои рисунки, – мягко сказала психолог.

Но я-то давно заметила, что мои рисунки не то что смущали воспитателей. Они пугали их до усрачки, а я и не знала, почему.

– Можешь сказать мне, зачем ты нарисовала все эти могилы?

Я взглянула на психолога как на полную дуру.

– Так они сами сказали мне это сделать! – и я изложила доктору задание, которое нам дали на уроке рисования.

В нем ясно было сказано нарисовать место, в котором ты бы хотел очутиться прямо сейчас. Так я и сделала, отчего происходящее казалось мне максимально несправедливым. 

– А ты бы хотела оказаться на кладбище?

Я кивнула.

– Можешь сказать мне, почему?

– Там тихо и красиво. Мне нравится. А еще людей мало.

Детский мозгоправ что-то черкнула в блокноте. 

– Можешь сказать мне, что такое кладбище?

– Там хоронят людей.

– Тебя это разве не пугает?

– Нет, – но меня начинало пугать то, как часто люди об этом спрашивали.

– Ты знаешь, что происходит с людьми, которых хоронят на кладбище?

– Их черви едят.

Услыхав такой ответ, психолог ужаснулась. 

– О, господи! – воскликнула она и поспешно замотала головой. – Я не это имела в виду. Сколько тебе лет?

– Четыре года и пять месяцев.

Судя по всему, ее опыт общения с детьми был не таким уж большим.

– Ты знаешь, почему люди попадают на кладбище?

– Потому что они умирают.

– И ты можешь сказать мне, что такое смерть?

Я призадумалась. Психолог успела написать еще несколько строк в своем блокноте, прежде чем я ответила.

– Смерть – это когда тебя больше нет.

Она оторвалась от записей и взглянула на меня с недоверием.

– Нет? А как небеса, куда наши души попадают после смерти? Что ты об этом думаешь? Ты знаешь, что такое рай?

– Рай – это мифическое место на небесах. 

– Мифическое?

– Ну да. Люди его выдумали. Как Деда Мороза.

– Зачем?

– Чтобы им не было страшно умирать.

Доктор обреченно вздохнула. Она провела со мной еще несколько тестов с лицами, картинками, разноцветными квадратами и черными пятнами различных форм. Потом попросила меня подождать в кресле-качалке. Та находилась в другой части кабинета, и док внимательно наблюдала за мной, делая вид, что занимается своими записями.

Через десять минут дверь распахнулась и в кабинет влетела моя мама. Сидеть ничего не делая быстро мне наскучило. К моменту ее прихода я перевернулась вверх тормашками и, закинув ноги на спинку кресла, энергично его раскачивала. При виде этой картины волнение на лице матери слегка поутихло, но голос дрожал, когда она обратилась к доктору.

– Что она выкинула на этот раз?

– Присядьте, – психолог указала рукой на пустующий стул, а когда мама села рядом, спросила: – Ваша дочь часто бывает гиперактивной?

– Как и все дети…

– Но она не думает так, как должен думать ребенок в ее возрасте. Вы когда-нибудь это замечали?

Продолжения я не услышала. Они отправили меня в коридор под предлогом взрослого разговора, но стены в этом здании были картонными. Прижавшись к одной из них, я могла уловить отрывки их диалога. В нем не было ничего интересного, пока психолог не упомянула какой-то психоз.

– Маниакально-депрессивный психоз?! – вдруг крикнула мама, да так громко, что можно было и не подслушивать. – Ей всего четыре!

Послышался приглушенный голос доктора, который прервал негодующий мамин голос.

– Если Лиза мыслит не так, как другие, это еще не делает мою дочь психбольной!

Мгновенье спустя она уже вышла из кабинета, с грохотом хлопнув дверью.

– Ты на меня злишься? – нерешительно спросила я.

– Конечно, нет, дочик. 

– Но ты злишься. Почему?

– Эти психологи совсем с ума сошли, – пробормотала мама, беря меня за руку. – Только и знают, что навешивать ярлыки без разбору!

Ее так и трясло от злости.

– Не переживай, мама. Этот доктор все равно не настоящий.

Мама улыбнулась.

– А какой настоящий?

– Психотерапевт, – серьезно сказала я.

Улыбка мигом исчезла с ее лица.

– Не нужен тебе никакой психотерапевт, – отрезала мама.

– Почему?

– Потому что моя дочь не сумасшедшая!

Она выросла в Советском Союзе, где ни психология, ни психиатрия не были развитыми науками, а такой банальный диагноз, как «хроническая депрессия» становился настоящим клеймом. Будучи задокументированными, даже самые незначительные проблемы с психикой могли сделать человека изгоем. Они отталкивали от него такое правильное совдеповское общество, мешали образованию и напрочь закрывали доступ к работе на достойной должности. 

Мне поставили диагноз еще в четырехлетнем возрасте. Быть может, и жизнь моя сложилась бы совсем иначе, знай я об этом. Однако описанная выше ситуация едва ли изменилась с наступлением девяностых, и мать изо всех сил оберегала меня от появления этого клейма. Она всем сердцем старалась меня защитить, и разве можно винить ее в этом?  

