# &nbsp; {#chapter-76}

Перенесемся на восемнадцать лет вперед, к тому злосчастному дню, которым я говорила с Риммой. Последнему дню лета две тысячи шестнадцатого года.

Депрессия застала меня врасплох, стоило лишь ненадолго расслабиться и почувствовать себя счастливой. Она сводила меня с ума, выуживая из подсознания самые страшные думы, включая и те, о которых мне давно удалось забыть. Задыхаясь, я металась туда-сюда по квартире как загнанное животное. Я попросту не знала, что мне делать дальше, а в голове была всего одна мысль.

Я хочу умереть. Я хочу умереть. Я хочу умереть.

Очень настойчивая мысль, которая не покидала меня ни на минуту. Страшней всего было то, что я не просто хотела умереть. Я должна была умереть, чтобы прервать череду душевных страданий. Жить с этой болью я больше не могла, уж слишком много лет я потратила на борьбу с ней. Смерть больше не казалась мне таинственной или привлекательной.

Она была мне необходима.

*When routine bites hard…*

От этих мыслей было никуда не деться. Я вытащила из шкафа чемоданы и второпях укладывала в них свои вещи, а в следующий миг обнаружила себя с Вениным галстуком в руках, из которого я уже сооружала узел Линча.

*And love, love will tear us apart again.*

Все происходило как во сне и я напрочь потеряла контроль над ситуацией. На фоне Кёртис извергал свою загробную поэзию, когда я накинула петлю на шею и без раздумий сделала шаг вперед, пнув стул, на котором стояла. Шелк галстука тут же сжал горло, заставив меня хрипеть и дергаться, раскачиваясь в петле.

*Why there’s something so good just can’t function no more?*

*And love…*

Сейчас все закончится, и боль вся исчезнет, c облегчением подумалось мне, но успех был недолгим.

Галстук оборвался, и я с грохотом завалилась на пол.

– По-моему, кому-то пора худеть! – произнесла я, хотя на деле мои слова звучали куда менее членораздельно.

Я разразилась громогласным смехом, голова от которого раскалывалась. Меня то и дело сотрясал кашель, голос охрип, а живот сводило судорогой, но я никак не могла остановиться. Смеялась до тех пор, пока меня не покинули последние силы.

– Подумать только! – прохрипела я, разглядывая клочья алого галстука, что остались висеть на перекладине и нехотя вспоминая тот далёкий весенний вечер, которым мы под проливным дождем убегали из лесу. – Второй раз я решаю повеситься и опять заканчиваю тем, что лечу жопой вниз.

За этими словами последовала новая волна истерического смеха. Мало того, что я не могла нормально жить, так я еще и не могла нормально умереть! Мысль об этом почему-то казалась мне очень комичной, и я смеялась и смеялась до тех пор, пока голос окончательно не пропал.	

Затем я, наконец-то, почувствовала себя как никогда измотанной. Голова шла кругом, в глазах темнело, а все тело стонало от боли. Мои глаза затмевала пелена слез, но это не мешало им закрываться под гнетом усталости. Казалось, я не спала без малого неделю.

Держась за стену, я медленно поднялась с пола и на ватных ногах побрела в сторону постели. Упала в нее, не раздеваясь, и моментально вырубилась, забыв о смерти, изменах и боли, которая мертвой хваткой вцепилась в сердце.

С самоубийством у меня вновь не сложилось.

<div style="text-align: center;">***</div>

Меня разбудил звук открывающегося замка, за которым последовали поспешные шаги. Не поднимаясь с постели, я сладко потянулась, а затем обо всем вспомнила. Просыпаться мне тут же расхотелось. Я накрыла голову подушкой, изо всех сил пытаясь вернуться в мир грез, но свет в комнате зажегся. Теплая ладонь Вениамина легла на мое плечо. 

– Ты как, детка? – спросил он, поглаживая меня по волосам.

– Который час?

– Без пяти девять.

Я нехотя выползла из-под подушки.

– Я вернулся больше часа назад. Все это время нарезал круги около дома. Боялся, что тебя здесь уже не будет.

– Так и должно было быть, – ответила я, толком не зная, говорю я о самоубийстве, или о наполовину собранных чемоданах, что так и остались стоять у стенки.

– У нас с ней ничего не было! – заявил муж так, словно это что-то меняло.

Я чувствовала себя слишком уставшей, чтобы кричать.

– Какая разница? Ты хотел этого, ты собирался мне изменить.

– Но не изменил же!

– Только потому, что она тебе отказала.

Наплевав на условия контракта аренды и на тот факт, что хозяин квартиры находился за стенкой, я достала из пачки сигарету и подкурила прямиком в постели.

– Да и откуда мне знать, что после этого ты не написал кому-нибудь еще? У тебя же море бывших в Керчи, помнишь?

– Зачем я только об этом тебе рассказал…

Веня всплеснул руками. Взявшись за голову, он сел у подножья кровати.

– Как я могу загладить свою вину? – то и дело повторял муж. – Ну, что мне сделать, чтобы загладить свою вину?

Ответа на этот вопрос я не знала.

– Я никогда не была на твоем месте, – устало ответила я. – Я не знаю, что тебе делать.

– Ты же у меня такая умничка. Ты всегда знаешь, что делать…

Я посмотрела на Вениамина, и тот тут же опустил взгляд. Смотреть мне в глаза он не решался.

– Давай сходим куда-нибудь? Хочешь в кино или в ресторан?

– Не хочу.

– О, или можем куда-то поехать! Давай махнем завтра в Ялту? Или в любое другое место, ты только скажи, что мне делать, Васляева.

– Не хочу.

– А чего хочешь?

Мне хотелось бежать, куда глаза глядят, но я только указала на чемоданы.

– Ты не можешь вот так уехать…

– Почему нет?

Вениамин взял мои руки в свои, прижал их к губам и прибег к своему любимому аргументу, который я слышала после каждого из его проступков.

– У нас же любовь.

На этот раз, я ничего не ответила.

– Прости глупого Веньку, – тоскливо произнес муж. – Я никогда не видел тебя такой печальной. И как же я себя ненавижу!

С этими словами Веня сжал пальцы в кулак, и со всей силы ударил себя по лицу. Раз, затем еще один. Я перехватила руку мужа прежде, чем он успел сделать это в третий раз. 

– Как мне все исправить? Только скажи, как мне все исправить? – звучал все тот же вопрос.

В итоге, Веня последовал моему дурному примеру и закурил в постели.

– Любимая, пожалуйста, не молчи.

– Я не знаю, что тебе делать, Веня, но я знаю, чего тебе не делать, – я сняла с пальца обручальное кольцо, и протянула его Вениамину.

– Что это значит?

– Я передумала. Не нужно мне больше никаких штампов в паспорте, никаких священных уз брака.

– Но ты не можешь передумать, у нас же…

– Что? Любовь?

– Да, любовь.

– И где твоя любовь была, когда ты ставил меня одну, без денег и абсолютно беспомощную посреди ночи в чужом городе? Да со мной ведь что угодно могло произойти, ты вообще это осознаешь? Но разве ты переживал за меня? Нет, ты кинулся писать Римме и предлагать ей услуги своего члена!

Он не ответил. Лишь лег позади, и нерешительно прижался ко мне, ожидая, что я вот-вот оттолкну его, но этого так и не произошло. В какой-то момент Веня уткнулся носом в мое плечо, и я почувствовала на своей шее что-то влажное. Лежавший рядом мужчина плакал.

Так мы и лежали, в полнейшей тишине, пока вечер не сменился ночью. Слез становилось все больше, и я накрыла ладонь Венькину своей. Пускай на мне больше не было его кольца, я по-прежнему считала Вениамина своим мужем. Хотелось бы мне, чтобы избавиться от этого чувства было так же легко, как избавиться от кольца, что до этого дня оставалось на безымянном пальце моей правой руки.

Увы.

