# 77 {-}

Спустя несколько дней глухой депрессии меня отпустило. Случилось это погожим вечером, на подходе к центру крымской столицы. Мы брели по пустому переулку, наполненному кольцевыми отзвуками где-то притаившейся мечети, к которым ни одному из нас так и не удалось привыкнуть за месяцы жизни в Симферополе. Вениамин был по-трезвому прекрасен и явно пребывал в добром здравии, что в итоге передалось и мне. 

– Я зайчик, – заявил муж, который не шел, а, скорей, шагал вприпрыжку, размахивая пакетом с гамбургерами. 

Пустота переулка очень быстро закончилась и возвращающиеся с работы люди вновь начинали обращать на нас внимание. Помню, на мне было длинное платье в горох – одна из немногих вещей, которую я смогла позволить купить себе вне секонд-хенда – и временами приходилось придерживать юбку, чтобы не угодить подолом в лужицы, то тут, то там преграждавшие

Среди многочисленных интересных словечок, существующих в иностранных языках мне как-то приглянулось «hoppipolla», что дословно значит «прыжки по лужам». Вообще, потрясающий народ эти исландцы, если вообще додумались придать значение этому процессу как отдельному имени существительному. И, что касается недавней депрессии, она, наконец, оборвалась где-то в пересечении с нашей hoppipolla.

Мне думается, это что-то сродни нетрадиционной медитации или несанкционированного возвращения в детство: просто взять и отдаться внезапному порыву радости, где бы ты ни находился. Всегда работает.  

Да и кольцо вновь было на мне.

Есть в этом что-то обсессивно-компульсивненькое – дергать туда-сюда обручалку, но кому какое дело, когда ты скачешь сквозь отражающееся в грязи солнышко с любовью в ушах вместо музыки.

Следующим днем меня ждал автобус в Николаев, что только добавляло романтики уходящему дню. Прощания, они такие.

<div style="text-align: center;">***</div>

Быть может, стоило никуда не уезжать или хотя бы перенести визит ближе к отцовским именинам – официальной причине поездки как таковой, но правда была в том, что я засиделась в Симферополе, который по-прежнему недолюбливала, да и мысль о том, чтоб немного отдохнуть друг от друга после затяжного конфликта казалась мне вполне логичной.  

Короче, в начале сентября того года я закинула свой starter pack в старый чемоданчик и оправилась на родину. На сей раз поездка прошла без эксцессов и я, как умудренная опытом женщина, уже не отходила от автобуса, который, кстати говоря, ехал практически без остановок.

На въезде в Николаев меня вдруг обняло какое-то удивительное чувство давно забытой радости, точнее сказать, приветливости в сторону этого места. В наушниках раздавалось 

Hello darkness, my old fiend

I’ve come to talk with you again..

что в принципе гармонировало с настроением и серостью города как таковой. За стеклом всплывали каменные силуэты все тех же полузабытых кем-то сооружений, словно я все это время сидела на месте, а фон вокруг куда-то двигался как в кинолентах времен старых вестернов.

Было нечто удручающе пленительное в этой тоске. Совсем не похожее на откровенную депрессию, когда ты реально отрезан от жизни. Просто маленький переворот в царство бетонной заразы и молчаливого спокойствия.

О чем тогда были мои мысли? 

Преимущественно о доме, предстоящем обходе друзей, веселой болтовне за чашечкой кофе или чего покрепче, ночным прогулкам да чему-то неуловимо знакомому, что ощущаешь по возвращении в пускай и ненавистный, но, все же, твой город.

Тем сентябрем я зачитывалась Достоевским. 

Страницы перелистывались одна за другой, как частенько бывало со мной во времена тоски. Такими днями я могла сутками не отрываться от книги, а потом подолгу сидеть у реки, размышляя о прочитанном. 

Это был тихий вечер на даче. За окном моросило, в печи потрескивали поленья, а я валялась на диване с «Идиотом» в руках, совершенно не подозревая, что однажды не просто пойму, а прочувствую это ощущение, о котором Федор Михайлович писал, что в сильные минуты радости ему всегда становилось грустно.

Примерно такими были мои мысли, когда в окно постучали. Не буквально, а в то, которое в голове каждого заядлого читателя между повествованием автора и какой-то там отдаленной реальностью. Это был Вениамин, накануне исчезнувший, а теперь вдруг заявивший, что он в стрипклубе. Голос муженька выдавал явный похмел, что в сочетании с разлукой, воображением, тотчас намалевавшем возлюбленного в компании оголенных девиц и бренностью бытия в целом привело меня в состояние ангедонии.

Я знала, что Веня в принципе не умел подолгу находиться в одиночестве. Иначе его буквально крыло. Без общения со мной он не обходился, но я едва ли нашла умилительным то, что муж решил возобновить его таким вот извращенным образом.

– Ты там один? – как бы невзначай поинтересовалась я.

– С Питером.

Тем самым корпоративным водителем, что недавече распространялся о своих похождениях в бордель, куда, кстати говоря, приглашал Вениамина.

– И что ты там делаешь?

– Как что? Я же мистер Кутеж!

Голос муженька явно выдавал тот факт, что режим кутежа продолжался не первые сутки. 

– Тут девки танцуют, – восторженно заявил он.

Связь то и дело прерывалась, на фоне грохотало какое-то техно (как будто мне и без того мало страданий!) и меня начало лихорадочно трясти.

– Ты считаешь это нормальным?

– А что тут такого?

– Веня…

– Васляева, ну, перестань, я просто пришел покутить…

Затем еще больше техно вперемешку с женским смехом и голосом то ли Питера то ли пидора и связь вообще прервалась. Я попыталась перезвонить, но разговор как-то не удался. Муж крикнул в трубку что-то совершенно нечленоразделительное и пропал еще на сутки.

А я что? За ночь дочитала огромных размеров роман.

