# &nbsp; {#chapter-78}

После того разговора моя тоска попыталась усилиться, но я изо всех сил отпиралась от затеи повторного входа в депрессию. Поплакала в подушку да пошла зависать с подругами. Марта как раз вернулась из Беларуси и мы почти каждый вечер проводили за веселыми историями и моими перфомансами. Она слушала, я исполняла. Это водилось за мной с самого детства: чем грустнее мне было, тем веселей я становилась на публике. Похоже, подсознательно переводила фокус внимания и впадала в состояние стенд-ап комика на полставки. 

Людям нравились мои веселые истории. Наверное, это и есть причина, по которой они никогда не предавали особого значения тому, что было вне юмора. На заметку всем биполярникам: очень легко стать популярным в компании, если вовремя оседлать свои эмоциональные качели. 

Тут можно бесконечно рассуждать о феномене внутреннего света и умении держать себя в руках, но суть выхода из душевного застоя одна. Ее еще пару сотен лет назад выразил Шопенгауэр: весел тот, что весел. И все тут.

Возможно, поэтому обществу в принципе были безразличны порезы на моих руках или ожоги от окурков. Никто и никогда не пытался уложить меня в больничку за подобного рода самоуничтожение. Тут, правда, стоит признать, что я, все же, старалась визуально прикрывать улики. Ну, окромя моментов срывов, когда вообще не придаешь значения ничему, причесываешься ключами в лифте и приходишь на встречу в пижаме… В любом случае, дуальность мира порой сводила меня с ума.

К примеру, среднестатистический обыватель, скорей, осудит, чем похвалит девушку, кружащуюся в танце среди надгробий, а то и вовсе припишет наркотическое опьянение, ну а тот, кто таки решится спросить о причинах подобного поведения, поймет, не поймет, но узнает, что когда мне грустно я танцую.  

Так я протанцевала весь сентябрь, преуспевая в самонастрое пока переживала разлад с Вениамином. Общались мы ежедневно, но при этом становилось понятно, что что-то в этих отношениях явно пошло не так. Быть может, стрипклуб или алкоголизм, кто его знает. Той осенью я успела засветиться, наверное, во всех барах города Н и практически ни одного вечера не проводила вне компании, которую сама же и заводила. Люди то и дело подтягивались, ощущая эту искру и тут еще один занимательный факт: я в принципе не пьянела. 

Еще я успела дать концерт, отплясывая в местном фонтане, частенько исполняла в общественном транспорте, приняла участие в экспериментальной пьесе «Крестного отца», выступая в роли женской версии Марлона Брандо без предварительной подготовки, пила самбуку с груди одной знакомой лесбиянки, украла из кофейни томик Маяковского, которого потом всю ночь цитировала в центре города, провела философский вечер, лежа на проезжей части в стиле персонажей «Дневника памяти» и даже записала несколько импровизаций под гитару вроде следующей:

*Мне снова хочется вскрыть себе вены,*

*Облиться кислотой как эпилептик пеной,*

*Шагнуть опять с моста вместо вписки*

*И выпить яду с сисек какой-нибудь киски.*

*А потом можно повеситься и долго болтаться*,

*Как будто в этом мире больше нечем заняться,*

*Ведь мне для счастья так мало надо,*

*Но я расстроена как эта гитара.	*

Композиция из четырех аккордов завершалась гранжевым съездом и исполнением первой строки похоронного марша. 

Гитара действительно была расстроена. 

Это если кому интересно, каким образом мне удалось прожить в буйной, но гармонии с собой и окружением. А ближе к октябрю я вернулась в Крым.

<div style="text-align: center;">***</div>

Незадолго до отъезда со мной произошел еще один занимательный случай. Той приближающейся к утру ночью я вернулась домой измотанной и, швырнув пальто в сторону вешалки, завалилась прямиком в спальню. Стоявший в коридоре чемодан лишь мельком привлек мое внимание. Я знала, что оставила его в спальне, но тогда не придала этому особого значения. Вместо этого я отворила дверь спальни и вдруг увидела себя, сидящую на полу у окна. Эта другая я выглядела тощей и невероятно подавленной. Она записывала что-то в блокнот, используя кровать вместо стола, как это бывало со мной в старые добрые времена депрессий, когда не было ни сил, ни желания дойти до кабинета. 

Картина, скорей, заинтересовала, чем ошарашила. Я видела подобное в детстве, но почти успела забыть об этом. Встреча эта произошла за несколько лет до того, как мне удастся с головой уйти в трансендальную медитацию, так что столь неожиданная деперсонализация не могла не ошеломить. Я застыла в проходе, даже не выпустив из руки дверную ручку, и завороженно рассматривала мрачную версию себя. Последней, казалось, не было до меня никакого дела. Она медленно подняла голову, взглянула куда-то сквозь меня, застыла на пару секунд, а затем как ни в чем не бывало вернулась к писанине.

При виде ее лица я резко выдохнула. Никакой реакции. Мой одолеваемый музой двойник был целиком и полностью погружен в тоску и творчество. Неплохой коктейль в моменты печали. Еще какое-то время я разглядывала ту, другую Лизу, раздумывая о том, что мы не просто похожи, а одинаковы, если не считать отсутствия света в ее глазах. Тонкие пальцы с невероятно длинными ногтями, бледные скулы, ярко выраженные брови, выглядывающее из-под темных одеяний плечо и толика пофигизма, с которой она отбрасывала с лица прядь вьющихся волос – все это было таким знакомым и в то же время далеким, непривычным с этой стороны реальности. Должно быть, так чувствуют себя карты старше десятки при виде своего зеркального двойника.  

– Ну, хоть нет проблем с писаниной, – произнесла я, заинтересованно рассматривая этот бледный силуэт.

После этих слов Лиза подняла бровь. Все еще не отрывая руку от тетради она без особого участия посмотрела в сторону выхода, и на мгновенье наши взгляды встретились. Это было сродни того, чтобы заглянуть в глаза Йену Кертису в ночь перед самоубийством. Только вместо музыки были тексты. И все тот же изъеденный болью взгляд, струящийся откуда-то из глубин подсознания. Я словно открыла дверь в прошлое и теперь глазела на образец самой себя, утопающий в пучине затянувшейся депрессии.

«Интересно, это которая из них?» – подумалось мне, но я так и не успела задуматься о подходящих месту и времени депрессиях.

– И то верно, – безразлично прохрипел мой двойник. – Хоть с писаниной проблем нет.

Звук ее голоса и сам факт завязавшегося диалога заставил меня отшатнуться. В голову пришло смутное осознание того, что происходящее в комнате – в принципе, не совсем нормально. Да и голос этот оказался куда ниже, чем мне думалось. В сочетании с нависшей над записями фигурой, судорожно царапающей бумагу, звуковой ряд казался чем-то сумасбродным. 

Опять же, дело было задолго до того, как я ушла в метафизику, так что меня, наконец, одолел шок. Заинтересованность скрылась за чувством страха то ли за себя, то ли за свою кукуху. Медленно, словно боясь, что двойник вдруг рывком перепрыгнет через кровать и побежит в мою сторону, неистово размахивая карандашом вместо ножа, я сделала шаг назад, а затем поднялась на носочки и принялась медленно отступать в сторону кухни.

– Что делать будем? – спросила я, оказавшись наедине с собой.

*А что тут делать? Как всегда, чай*, вовремя нашелся мой внутренний доктор.

Я последовала его совету и спустя пару чашек решилась заглянуть в спальню. Конечно же, там было пусто.

– Ну, и измена, – озадаченно пробормотала я, глядя в то место, где еще с четверть часа назад видела свою депрессивную версию.

*И, что самое выдающееся, на трезвую голову*, не без восхищения заметил док.

Той ночью я легла спать в кабинете.

<div style="text-align: center;">***</div>

Пускай мне и удалось обратить кутежный сентябрь в месяц без удручающих мыслей, в автобус я уселась с легким тремором в коленках. Мне думалось, что муженек либо впал в полнейший кутеж, либо и вовсе не выходил из дома. Понятия не имею, почему последнее пришло мне в голову, но в итоге именно это оказалось правдой.

Дорога выдалась серой и почти такой же тоскливой как мой внутренний мир той неудавшейся осенью. На самом деле за внешней говорливостью и бесконечной улыбкой скрывался один простой факт: мне было страшно. На этот раз не влюбиться, а вылюбиться так сказать. Я совершенно не знала, чего ожидать от встречи с Вениамином и всем силами пыталась найти хоть одну адекватную причину с ним не расставаться. В итоге причина нашлась, а, может, и всегда была. Я поняла это, когда мы въехали в Симферополь и вместо привычной радости меня сковало ощущение тревожней всех тревожностей. Казалось, транспорт двигался слишком быстро и все вокруг грозило вот-вот доставить меня домой. Это было раннее утро: на улицах практически нет людей, дорожки по ту сторону тротуара завалены пожелтевшими листьями, за стеклом лениво накрапывает дождик, а я слушаю Янку и, цитируя великую поэтессу времен перестройки, размышляю, как же мне хуёво. 

Как-то слишком быстро, подумалось мне, когда за окном нарисовался сюжет уже хорошо знакомого автовокзала. Странная мысль для девушки, которой не терпится возвратиться к любимому, не правда ли? Мне безумно хотелось его увидеть и не хотелось вовсе. Причиной тому бы страх разлада и тот откровенно раздражающий факт, что я действительно любила этого человека. 

Есть у любви один удручающий момент. Она делает нас слабыми в разлуке с тем, кто дорог. А еще навевает боязнь потерять любимого. Мне всегда думалось, что подобному раскладу место, скорей, в нездоровых, созависимых отношениях. Быть может, именно это со мной и произошло. Хотя, что может быть прекрасней, чем найти такого же идиота, как и ты сам, веселого, задорного и преисполненного весьма двояких взглядов на этот мир?

В подобного рода философских размышлениях я провела еще минут двадцать, загадочно разгуливая по вокзалу. Затем избавилась от промокшей под дождем сигареты и вызвала такси. Пятнадцать минут, и я на месте. К тому моменту люди уже понемногу начинали выходить из домов, самозабвенно спеша на работу. Я рассчиталась с таксистом и уселась на бордюр около какой-то лужи. В ней отражался фонарь у дома, частичка забора и мое несостоявшееся будущее. Мысли о жизни, любви и в целом вдруг стали столь беспощадными, что я натянула капюшон и, закурив, улеглась на землю. Почти как Марк Рентон, только вместо героина по моим венам кружила любовь. Такая же сильная и убийственная, как героин, наверное. 

*Можешь дождаться, пока муж уйдет на работу, собрать вещи и уехать с концами*, заботливо посоветовал внутренний голос.

– Долго придется ждать. Сегодня воскресенье.

*И кого воскрешаем?*

Должна признать, с юмором у него гораздо лучше, чем с временными рамками.

Я собралась ответить что-то едкое, но со стороны дома послышался какой-то шорох, следом за которым на крыльцо выполз Вениамин. Заспанный и с кучей мусорных мешков в руках. Их было штук шесть, не меньше. Я даже забыла подняться, очарованная этим появлением. 

Весело позвякивая бутылками, муж виновато улыбнулся. Оставил в покое мусор и одним рывком поднял меня с земли.

– Васляева, – радостно пробормотал он, обнимая меня за талию, – а я думал ты позже будешь. Собирался тебя встретить. 

– Я такси взяла…

– Чтобы я не успел замести следы?

– … чтобы застать место преступления.

Мы сказали это одновременно и уже мгновенье спустя дворик у дома наполнился смехом. Мы целовались и смеялись как парочка городских сумасшедших в компании дождя и пакованов с мусором. На пороге соседнего дома появился Владимир. Он замер на крыльце, наблюдая эту семейную идиллию словно в какой-то малобюджетной романтической комедии.

Пришлось ретироваться в дом.  

Обстановка внутри оказалась чуть лучше того, что я себе представляла. Маман бы давно упала от такой в обморок. Муж заварил чаю и с видом нагадившего в углу котенка уселся напротив.

– Я не успел прибраться, – зачем-то сказал Веня.

*Неужто зреньем бог меня обидел, чтоб я на небе солнца не увидел?* ¬– удивился мой внутренний Шекспир.

– Правда?

– Ну, да.

И здесь нас настигла минута молчания. В свете последних событий, устроенный Вениамином бардак казался последней из существующих в этом мире проблем. С нее-то я и решила начать. Отправила мужа в магазин, врубила музыку и взялась отмывать дом. 

*На засранку напала чистота*, прокомментировала Ма.

Она любила повторять эту фразу, как часть и тщательно бы я не убирала.

Всего три с половиной часа беспрерывной уборки и наша студия выглядела лучше, чем в день заселения. Веня был вне себя от радости. Знай я, что его так просто осчастливить, уже давно наняла бы клиннинг. 

Я вышла из душа и попала прямиком в руки мужа. Тот утащил меня в сторону постели, где начался очередной счастливый период наших отношений. 

