# &nbsp; {#chapter-79}

Поразительно, сколь многое любовь меняет в нашей жизни. И дело здесь вовсе не в сексе и совместных приобретениях, а в том, как на эту самую жизнь смотреть. Двое несчастных могут стать самыми счастливыми, не потратив при этом ни копейки. С любовью мир вокруг становится красивее и все вокруг приобретает смысл, словно кто-то меняет обыденные декорации на праздничные. И где бы ты ни находился, хватает одного взгляда любимых глаз, дабы понять, что это место самое спокойное и уютное на свете. 

Как выяснилось, в душе я всегда была романтической натурой. Настолько доверчивой и по-детски наивной, что приходилось скрывать это в потоках юмора и сарказма. Мне всегда думалось, что если я кому-то доверюсь на все сто, то рискую потерять себя. Тогда на кой черт я решила выбрать бабника-алкоголика с явными признаками шизоэффективного поведения?

Что ж, полагаю, некоторым вопросам суждено остаться риторическими. 

Месяцем ранее я нашла себе работу, от которой периодически страдала. Писала тексты на заказ. Вовсе не о том, о чем хотелось, но все равно писала. Мне вдруг понравилось готовить, и с каждым днем рацион становился все разнообразнее. Все эти простые бытовые моменты казались мне настолько чуждыми и оттого удивительными в своей приятности. 

Если не считать этого консервативного отступления, семейная жизнь оставалась все такой же рок-н-ролльной. Мы делали вылазки в центр каждые выходные и ежедневно бродили по округе в поисках приключений, одолеваемые радостью и болтовней.

Одна из таких вылазок закончилась неудачно. Укрытый первым снегом камыш выглядел очаровательно на фоне серых многоэтажек. В воздухе чувствовалось приближение зимы и дорога на гору, где стоял наш дом, сплошь покрылась льдом. Спуск стал еще круче. Можно было сломать ногу, а то и обе, но вместо этого я провалилась под лед, кружа по замерзшей поверхности близлежащего водоема. Тем днем мы опять повздорили из-за венькиного пьянства, так что я была одна. Явилась домой промокшей до нитки и, видимо, где-то в пути схлопотала ангину.

Лежать под капельницей мне совсем не понравилось. Я читала «Морфий», то и дело ощущая себя лирическим персонажем Булгакова. Только я была непростительно трезвой.

Жизнь в больничных стенах оказалась более унылой, чем мог бы представить самый заядлый пессимист. Серость комнаты и однотипность пространства, да его замкнутость, давили на меня с невероятной силой. Словно кто-то отключил приток кислорода к палате или моему больному мозгу. Минуты тянулись как вечность, а пространство вокруг продолжало сжимать в тески пока сознание совсем не помутилось. До этого я и не думала, что детским травмам все еще суждено до меня добраться, но вот температура вновь поднимается, дышать становится все сложней, я чувствую сдавливающую виски пульсацию, и мир вокруг растворяется, унося меня в забытие, где один за другим всплывают кадры двадцатилетней давности.

Удивительно, как много мыслей одолевает голову, если находиться в полном уединении и молчании. Препараты действовали как-то прискорбно. Внутренний голос куда-то делся. Никто не шутил, не пытался язвительно комментировать происходящее. Не было ничего, лишь стена, окно и койка, лежа на которой я безучастно наблюдала за сомнительным прогрессом в пакете у стоящей рядом капельницы. Картину дополнял завывающий за окном ветер.

Свет в палате был настолько тусклым, что чтение превращалось в какую-то каторгу. Приходилось додумывать половину слов – кощунственное дело, особенно, когда речь идет о классике. Так я и не узнала, справился ли Бомгард со своей зависимостью.

Вместо этого меня одолел внутренний монолог, ужасный в своей бесконечности. Слишком многое можно узнать, если сутками лежать без дела. В моей голове пронеслось так много воспоминаний, детских травм и прочих удручающих событий, которые обычно заканчиваются гештальтами, что впору было повеситься на той самой капельнице. Уход отца, истерия матери, летящие в мою сторону предметы, когда она возвращалась уставшей с работы, смерть домашних питомцев, отказ в музыкалке, разлука с друзьями, травля в школе, издевательства в художке, смена школы, травля во второй школе пока я не научилась давать отпор, еще один развод родителей, после которого я вообще себя плохо помнила, смерти близких, встречи с Эриком, его измены, отказы издательств, расставание с Адамом, еще больше отказов издательств, и вот я здесь. Лежу, глядя в стену, и даже не могу плакать.

Мне вспомнилось, как мать в порыве гнева, (он у нее неизбежно сочетался с гиперопекой) зарядила в меня ножницами. Мне было лет шесть и за последние пару лет я уже успела привыкнуть к ее истерии, что то и дело мешалась с многочасовыми монологами о том, как она меня любит и как паршиво я с ней поступаю. Практически каждая вылазка в люди заканчивалась скандалом с ее стороны. Особенно хорошо это ощущалось по праздникам. Она заводила меня в свою комнату и лупила, стоило гостям разойтись. В какой-то момент я даже привыкла. Правда, каждый раз чувствовала пустоту, когда люди уходили, ведь при них Ма была абсолютно другим человеком. Едва ли она отдавала отчет собственным действиям. 

Короче говоря, я привыкла и стала воспринимать подобного рода всплески негатива как неотъемлемую часть семейной жизни. Правда, чем старше я становилась, тем сильней во мне росло ощущение, словно я живу без семьи. Так вот, однажды Ма зарядила в меня ножницами и те пробили перепонку между большим и указательным пальцами. Дело было в районе первого класса и меня удивил вид крови, и то как она стала заполнять ладонь. Вскоре вся рука была красной, а я смотрела на нее как баран на новые ворота. Первой мыслью было что-то вроде «Какого черта? Я же ею рисую.» От вида крови матери стало дурно. Она расплакалась, пришлось успокаивать. Ма всегда пила много таблеток. Работала с больными людьми по двенадцать часов на ногах и, очевидно, плохо владела собственными эмоциями. Как и памятью, ведь случай с ножницами она отрицала уже на следующий день и все чаще задавалась вопросом, отчего у нее такая дерьмовая дочь. 

Так вот, ожидание многочасового монолога с некоторой примесью оплеух стало для меня ожидаемым завершением выхода в свет. Однажды я разбила стакан с соком, сидя в каком-то кафе в компании детсадовцев и их мамаш. Мы о чем-то смеялись. Я по привычке бурно жестикулировала и задела чертов стакан рукавом. Помню, как замерло мое пятилетнее сердечко при виде рассыпавшихся по полу осколков. Этот проступок показался мне чуть ли не худшим преступлением на свете. Я в ужасе посмотрела на мать, но та лишь отмахнулась и продолжила мило беседовать со сверстницей. Уже позже я поняла, что дело здесь было в наличии других людей: в компании мы всегда стараемся выглядеть лучше. Возможно, именно поэтому дети частенько идеализировали мою Ма. Правда, зачем ей тогда, по их мнению, было периодически резко утаскивать меня в подъезд или куда-то за угол для «серьезного разговора»? Не подарки же она мне там дарила, в конце концов.

До меня вдруг дошло, как трудно матери было признаться в недовольстве собственной жизнью. Не то чтобы мне – себе самой. И чем сложней становились времена, тем истеричней делалась мать. Она неистово повторяла, что всем довольна, но не могла остаться наедине со своими мыслями, так что по возвращении с работы искала повод на мне сорваться и при наличии малейшего закатывала красноречивые скандалы. Спустя пару часов она уже распиналась о том, как меня любит, а окружающим гордо сообщала, что я буйная, но отходчивая. А я всегда боялась стать на нее похожей, поэтому привыкла говорить правда и перекрывать истерики юмором. Но некоторым людям просто удобно показывать вещи такими, какими им нужно для оправдания себя перед, собственно, собой же. Едва ли знакомых интересовало, как долго я не могла уснуть или сколько кругов вокруг дивана намотала под вечер. Возможно, им гораздо интересней было бы услышать о том, что мать сделала, дабы перенаправить мою энергию в полезное русло вместо того, чтоб ставить меня как цветок на полку и возмущаться последующей за застоем активности. 

И, все-таки, сомнительная радость, скажу я вам, увидеть родителя с книгой под названием «Что делать с трудным ребенком?». Пожалуй, такому чтиву не помешала бы двойная обложка с нейтральной надписью. Но поводы отнести меня к сложненьким всегда были потрясающими воображение.

Все в том же дошкольном возрасте Ма обозлилась из-за того, что я перешла дорогу со двора в близлежащий парк. Не то, чтоб я была одна. Все дети туда побрели да и дорога была узкой. Не какая-то там трасса, но! Ма это привело в ярость и она приняла решение – после многочасового выступления, само собой – отдать меня в детдом. Показательно собирала вещи, комментируя это дело:    

– Чтобы у тебя были теплые носочки… Колготочки надо еще новые положить…

При этом пришла мамина коллега по имени тетя Настя. Она принесла пакет печенья и стала бурно советоваться с Ма, стоит ли мне его вообще давать, ведь другие дети отобрать могут. К счастью, я никогда не любила печенья. Все это время я молча наблюдала ситуацию, и лишь когда меня завели за забор детского дома начала нервничать. Мне были знакомы здешние пейзажи и, проходя мимо, я не раз видела этих несчастных деток, пролазивших через забор, чтоб попросить у прохожих мелочь и сигареты. Как-то напротив детдома установили памятник и один из постояльцев искренне ответил в прямом эфире, что мечтает нюхать клей, когда вырастет. Словом, обстановочка не из ламповых. Я до последнего думала, что родительница блефует, но вот на порог выходит какая-то женщина. Она забирает мои вещи и на полном серьезе куда-то меня уводит. Наступает напряженный момент из серии «кто сорвется первым». Сорвалась в итоге я. Вылетела обратно во двор и разревелась раз в пятый за все свое детство. Мать обняла меня со словами:

– Ну что, ты готова извиниться?

Знаете, у меня никогда не было диплома психолога, но душевнобольным философам он и не нужен. Лежа под капельницей я все чаще вспоминала эту мизансцену. Быть может, этим женщинам заплатили? Иначе, кем надо быть, чтобы потакать истеричке в подобного рода воспитании? Детские травмы и их последствия простираются куда дальше синяков и криков. Они не всегда проходят по классическим сценариям, и мало-кто обращает внимание на то, как легко родителю заиграться в бога. Подобно шаловливым детям они группируются и создают условия для этой страшной взрослой игры, построенной на принципе: я прав(а), а ты – нет. Здесь стоит удивиться тому, что суицидальный уровень дошкольников столь низок. Мне всегда казалось, что правильное воспитание – это, в первую очередь, правильный пример и подобные срывы до крайности нелогичны, а в словах «Мне стыдно за твое поведение перед знакомыми!» куда больше иронии, чем смысла.

Пару лет меня продержали в экспериментальном классе с математическим уклоном – реальном аду для гуманитария. Каждый день было по шесть-семь занятий математикой и куча домашки в придачу. Я делала ее по вечерам, с грустью слушая задорные крики детей на площадке под окнами. Остальное время читала и рисовала. Ма, почему-то, ставила под сомнение мою импровизированную живопись. Стоило мне исполнить что-либо более-менее внятное, она тут же утверждала, что я ее обманываю и это нарисовал кто-то другой. Книги ее и вовсе бесили. Приходилось покупать их на деньги, собранные за праздники и подработки. И чем больше я читала, тем сильней она сердилась. 

Однажды Ма нашла мои стихи и принялась реветь над ними, утверждая, что это бред шизофреника. Мою первую печать она охарактеризовала таким же образом. Изрядно повторяющийся критик. 

Отец был единственным лучиком света в этом затянувшемся мраке. Он умело скрывал эмоции, никогда не злился, не повышал голос, и мне хотелось быть такой же. Быть может, поэтому, папа всегда принимал сторону матери, какой бы не была проблема. А их, в общем-то, и не было. Он никогда не видел, как та меня лупила и все это действо официально называлось «Ударила один раз полотенцем, с кем не бывает. Ты, наверное, ее довела.» Еще я часто слышала о других гипотетических детях, родители которых алкоголики и наркоманы и о том, что даже те при этом любят свою семью.

Я тоже любила. Причем бесконечно сильно. И чем старше я становилась, тем сильней забивала на эти травмирующие воспоминания, пока не очутилась под капельницей. В кромешном одиночестве серых стен, наедине с детскими травмами.

<div style="text-align: center;">***</div>

Мне было десять, когда родители сошлись. В те дни я освоила отцовский Зенит и то и дело их фотографировала, а проявляя пленки тихо радовалась этому воссоединению. Мне нравилось смотреть, как они шли по улице, держась за руки пока я возилась с Тасей, а по утрам я о и дело просила маму поцеловать отца, когда тот первым уходил на работу. Мы вместе ужинали, смотрели телевизор и делали все те простые вещи, которыми полны жизни множества других семей. Это время казалось мне волшебным. Я начала заниматься спортом, писать прозу и мечтать о том, как однажды мы переедем куда-нибудь в Англию или Францию. Отец сделал ремонт в квартире, подарил мне первую гитару и всегда был рад заглянуть со мной в книжный – о лучшей жизни не стоило и мечтать.

Мне было одиннадцать, когда Ма вновь его прогнала, и я совершенно не помню последующего года своей жизни. Странный поворот для эйдетика. А рукописи она зачем-то сожгла.


