# &nbsp; {#chapter-80}

Вычухалась я на удивление быстро, учитывая мой эпический уход под воду, но говорят, беда не приходит одна. В конце ноября Вениамин не вернулся с работы вовремя. Телефон был отключен, и сперва я списала его отсутствие на какую-нибудь пьянку с коллегами. Правда, обычно в таких случаях он снимал трубку, орал в нее «Васляева, твой мистер Кутеж опять нажрался» и только после этого пропадал.

Вечер плавно переходил в ночь. Время тянулось невыносимо медленно, а я все никак не могла уснуть. Отвлечься от дурных мыслей никак не получалось. Изредка за окном проезжали машины. Отвратительное, скажу вам, занятие: вслушиваться в тишину и при первом признаке скользящих по льду шин бежать к окну в надежде обнаружить за ним выходящего из такси мужа. Бывало, Веню приносили домой коллеги, но, в основном, он добирался своим ходом и всегда предупреждал, если собирался задержаться.

К полуночи мне сделалось по-настоящему страшно. Телефон мужа все так же был на автоответчике, а я металась между постелью, окном и террасой, куда выходила курить. Подкуривала сигарету и тут же ее тушила. От привкуса табака начинало тошнить. Я пробовала пить, но становилось только хуже. И сна ни в одном глазу. Если я когда-то чего-то и боялась, то разве что поставить себя в уязвимое положение. К часу ночи пришлось признать, что это оно и было. Меня сковал какой-то животный страх. Сердце неистово билось в груди, а внутренний голос, то и дело орал:

*С ним что-о случилось! С НИМ ЧТО-ТО СЛУЧИЛОСЬ!*

И вот после очередного вопля я подрываюсь с кровати и вновь бреду к окну. Захожу на кухню и теряю дар речи: воздух заполняет туман, от которого все вокруг словно сделалось черно-белым. Он густой и каким-то вязкий. В доме холодно, но я не придаю этому особого значения. Пытаюсь включить свет, вот только светильника не оказывается на привычном месте. Тогда я делаю пару шагов в сторону окна, но и его там нет – лишь сплошная стена да двери на улицу. 

Слева доносится какой-то скрежет. Я выныриваю из тумана и вижу во мраке хорошо знакомые силуэты: своего крестного и деда. Оба покойники. Сидят за моим кухонным столом в полнейшей тишине и никакого внимания на туман не обращают.

– Вы что тут делаете? – говорю.

– Чай пьем, – отвечает дед.

– Давай с нами, – произносит крестный.

Несмотря на мглу, я буквально чувствую, как тот улыбается. Как всегда, с отеческой добротой. 

– Но у меня только два стула.

Мне совсем не страшно. Скорей, непонятно, как такое вообще возможно.

Дед вздыхает.

– А чего без света сидите?

– Так нет его, – отвечает дед.

Я щипаю себя за щеку, прикусываю палец и чуть ли не танцую на одной ноге, пытаясь разобраться в сюрреализме ситуации.

– У меня что галлюцинации? – спрашиваю я.

Дед качает головой. Крестный отвечает, что ни в коем случае.

– Тогда что вы здесь делаете?

– Чай пьем, – опять говорит дед.

Я начинаю смеяться. Крестный тоже. Такое себе позднее застолье, а дед отчего-то притих.

– Правильно делаешь, что не садишься с нами, – наконец, заявляет он. – Тебе вообще здесь делать нечего.

– Мне?

Я в недоумении перевожу взгляд с деда на крестного и обратно, пытаясь понять, кто из нас обкурился и когда это произошло.

– Мы вообще по другому поводу пришли, да только будить тебя не хотели.

– По какому? 

И тут я начинаю переживать. Не за себя, разумеется.

– Мужика твоего ждем, – говорит дед.

Он вытягивает руку, сжимает ладонь в кулак, и я вижу очертания надписи ТОЛЯ, выбитой на костяшках. 

Внутренний голос все так же молчит. 

Я наклоняюсь к деду, стараясь удостовериться в его реальности. Никаких полупрозрачных силуэтов или признаков разложения. 

– В последний раз мы виделись, когда я гладила тебе волосы и плакала, – говорю. – Ты тогда в гробу лежал, припоминаешь? 

Дед ничего не отвечает. Лишь качает головой, словно, я ребенок, демонстрирующий плохое поведение.

*Может быть, покойникам не стоит напоминать, что они умерли?* – проносится в голове.

– Нечего тебе здесь делать, – повторяет старик.

– Но…

Крестный кладет свою ладонь мне на руку. Я гляжу на это действо, все еще пораженная его реальностью. Затем не выдерживаю, обнимаю крестного отца и прижимаюсь к его плечу.

– Как же сильно я по тебе скучала!

– Тебе надо уезжать, – шепчет крестный. 

Внезапно кухню наполняет какой-то грохот. Я подпрыгиваю на месте и гляжу по сторонам. Покойников и след простыл, но кто-то бешено колотит по ту сторону входной двери. Несколько секунд я тупо смотрю на дверь, все еще под впечатлением от ночных гостей. Наконец, понимаю, что неплохо бы включить фонарь. Иду в спальню за телефоном, а, возвратившись, замечаю, что окно вернулось на свое место. Мгла, правда, все еще присутствует и кто-то неистово ломится в дверь.

Грохот пропал так же неожиданно, как и появился. Приблизившись к двери, я заглянула в глазок: тьма да и только. Дверная ручка стала ходить ходуном. Кто-то по ту сторону двери явно хотел, чтобы его впустили. Быть может об этом меня предупреждали покойники?

Стук повторился, а затем раздался до боли родной голос:

– Васляева!? Васляева, впусти меня!

Словно камень с души, но чувство радости продлилось недолго. Я отворила дверь и увидела испуганное лицо мужа. Он весь дрожал от холода и, вероятно, стыда. Вениамин был голый, весь в кровоподтеках и слезах. 

– Лиза, – практически рыдая произнес он и упал на колени. – Лиза, прости меня!

Я затащила мужа в спальню и укрыла пледом. Включила фонарик и обомлела от ужаса. На Вене не было и живого места. Торс и конечности покрывали гематомы и ссадины невероятных размеров, кусок бороды был оторван и за ухом виднелся какой-то порез. Кровь вперемешку с болотом покрывала тело моего мужчины.

– Кто это сделал? 

– Я не помню.

Вениамина трясло.

Я заварила чай и обтерла мужа мокрым полотенцем. Открытых ран не было, если не считать тех, что та лице, но они меркли и бледнели в сравнении с синяками на его теле. Кровь успела засохнуть. Судя по всему, какое-то время Веня провел в снегу.

– Кто сделал это с тобой? – повторила я.

Меня трясло от ярости, мужа – от холода.

– Они затолкали меня в машину, отвезли и избили.

– Куда отвезли?

– Там была вода.

– И это все?

Веня с грустью взглянул на меня.

– Больше ничего не помню.

– А почему ты голый?

– Они заставили меня раздеться.

– Кто?

– Васляева, я без понятия. Последнее, что я помню, как зашел в пивную под домом. Сегодня же день зарплаты.

– Твою ж мать.

– Теперь нечем платить за квартиру.

– Я заплачу.

Веня шмыгнул носом.

– Ну, ты хоть что-нибудь помнишь?

Он развел руками и тут же скривился от боли.

– Я проснулся в болоте и побежал домой.

– А где это было?

– Я не помню. У какой-то воды.

Здесь было как минимум три таких места.

– Долго бежал?

– Я не помню.

– Твою мать. Веня, надо звонить ментам.

– Ни в коем случае!

– Почему?

– Менты меня не любят… Да и толку от них никакого.

И, все-таки, я позвонила в полицию. Муж был прав, там нам не помогли. Протаскали до утра по разным кабинетам и сказали приходить на следующий день, чтобы составить заявление. В итоге никто ничего не нашел, а перепуганный муж так ничерта и не вспомнил. Он остался без документов, а побои оказались хуже, чем мне думалось. Ребра пострадали, так что ближайшие пару недель Вене суждено было провести в постели.

– О чем ты думал? – вдруг спросила я, укладывая непутевого муженька в кровать. – Ну, когда они это с тобой делали?

Странный вопрос, но я всегда была философом.

– О тебе, – не мешкая ответил Вениамин.

– Фу, как банально, – я поцеловала его в здоровую щеку.

Чуть позже мы решили поиграть в детективов. Обошли половину города, посетили местные водоемы, но муж так ничего и не вспомнил. Рюкзак его тоже не нашелся. В итоге, дело закрыли, так никого и не поймав. 


