# &nbsp; {#chapter-81}

Две тысячи семнадцатый год застал нас в Керчи. На половине пути автобус застрял в сугробе, и мы вполне могли встретить Новый год в дороге. Тем вечером у меня поднялась температура, так что подобные мелочи едва ли могли меня взволновать. Жар разыгрался не на шутку. Я с трудом стояла на ногах, ехать никуда не хотелось, а чашка чая и теплая постель были всем, о чем я мечтала.

Тем не менее, в Керчь мы прибили за считанные минуты до наступления Нового года. Веня поймал такси, и вскоре мои мечты стали реальностью. Теперь я сидела на просторной кухне возлюбленной отца Вениамина, в компании пледа и горячих напитков. Помимо них здесь был Алексей Вениаминович, Света с дочерями, ее зять и сват. В отличие от остальных присутствующих, в руках последнего не было бокала. Он слыл ярым приверженцем здорового образа жизни, что не мешало мужчине источать марихуановый шлейф, и это заметно напрягало хозяйку дома.

– За любовь! – произнесла она, поднимая первый бокал. – Я хочу, чтобы в наступающем году любовь была в каждом из вас.

Света обещала устроить небольшой семейный праздник, но на деле закатила настоящий пир. Она хлопотала вокруг стола, загружая его все новыми и новыми блюдами. Женщина шутила и смеялась, весело пританцовывала и даже пропела пару строк какой-то старой песни, обнимая своего мужчину. И, все же, сколь непринужденным не выглядело ее поведение, Света то и дело бросала тревожные взгляды в сторону отца избранника ее старшей дочери, сидевшего напротив.

– Как я могу быть спокойна! – наконец, призналась она, когда на кухне не осталось никого кроме нас двоих. – От него же постоянно несет этим… Тьху, куревом! Моя дочь и ее мальчик живут с ним под одной крышей! А ей всего девятнадцать!

– Правда?

На самом деле, я знала, сколько лет ее дочери, и просто хотела отвлечь Свету от мрачных мыслей. Все равно, от них не было никакого толку. Только тоска, сонливость, да измученная переживаниями лицо.

– Недавно исполнилось.

– И зачем же люди женятся так рано? – спросила я, пытаясь прикрыть рукой рвущийся наружу зевок.

– Я тоже вышла замуж рано!

– И чем это закончилось?

Моя собеседница отмахнулась.

– Ты же знаешь, чем все закончилось.

– Могу только догадываться.

– Вениамин разве не говорил тебе? – судя по ее тону, Света восприняла мои слова скептически.

– Не-а, я редко лезу в чужое белье. Только если оно мешается с моим.

– Что ж, девятнадцать и правда рановато, – после коротких раздумий согласилась Света. – Но вот двадцать три – это уже другое дело!

Она подмигнула.

– Уже подумываешь о замужестве?

– Никогда всерьез не думала о замужестве, – призналась я, – но замужество подумало обо мне.

– В каком смысле?

Я подняла руку, демонстрируя обручальное кольцо, которое снова носила, а дальше произошло то, чего я никак не ожидала. Светлана завизжала от радости, как это бывает в романтических комедиях, когда главная героиня впервые показывает подружкам свою обручалку. 

– Быть того не может! – она отставила бокалы и потянулась через стол, чтобы меня обнять. – Когда?

– Прошлой весной.

– Прошлой весной и до сих пор не женаты?!

– А куда спешить?

Света подоткнула бока руками и взглянула на меня так, как смотрят на ясельных детей или на недоразвитых взрослых.

– Куда спешить? Ты вообще в курсе, что бабы к Вене так и липнут? Ларионовы – это же порода! Их не так-то просто заполучить. Их надо еще добиться. Я вот девять лет этим занимаюсь. Говорю тебе, хватай его пока горяченький и сам в печку лезет!

– Кто куда лезет? – раздался раскатистый бас.

Дверь позади нас скрипнула, и на пороге кухни появился Алексей Вениаминович в сопровождении Вениамина Алексеевича. Оба готовенькие и с довольными улыбками на бородатых лицах.

– Пойдемте смотреть салют! – крикнул старший из Ларионовых. 

– Только надень шубу, – добавил младший. – Там снег валит.

Он уже заботливо накидывал на мои плечи какое-то меховое покрытие.

– Но у меня нет шубы, Венька!

От этих слов мой муж принял крайне потерянный вид. Наблюдая за ним, я изо всех сил старалась не рассмеяться. Это было не так уж просто, учитывая ядерную смесь алкоголя и антибиотиков, что были во мне той новогодней ночью.

Остаток зимних праздников мы провели в спальне Александра Вениаминовича. Слишком замученные, чтобы покинуть пределы дивана. За окном без устали сыпал снег и ледяной ветер то и дело забрасывал в наше окно пару-тройку снежинок. Отсюда заснеженная деревня казалась уютным местом, но никто из нас так и не решился выйти наружу. Я по-прежнему была уставшей из-за одолевающей меня болезни, тогда как Веня страдал от непрекращающегося похмелья, которое сам же и провоцировал каждым новым вечером. 

– Хочу кутить! – с наступлением темноты упрямо заявлял муж.

– Не дай мне сделать это еще раз, – просил он следующим утром, запивая рассолом обезболивающее.

В один из этих увлекательных дней к нам присоединилась Света. Облачившись в пуховик и обмотав шею сразу несколькими шарфами, она сновала вдоль дома и беззаботно лепила снеговика. Вскоре к ней присоединились мужчины, и теперь все трое старательно скатывали собравшийся во дворе снег, превращая его в огромные белые шары. Сидя у окна, я лениво наблюдала за этой семейной идиллией. Смотрела, как Венькина борода покрывается инеем, и поняла, что впервые за долгое время могу наблюдать мужа со стороны.  

За исключением предкутежного состояния, он был как огурчик. За полгода, что мы прожили в столице Крыма, Вениамин заметно набрал в весе. Муж больше не выглядел бледным и голодным, а вид его когда-то пугающе выпирающих ребер теперь с трудом мог меня смутить. К тому же, к Рождеству его ноябрьские травмы практически исчезли. Ссадин и царапин больше не было видно, и лицо моего мужа вновь стало презентабельным. Теперь он мог передвигаться без боли, так что, в следующий понедельник Вениамину предстояло вернуться к работе.

– Не хочу работать! – произнес он наступившим воскресеньем, и эти капризные нотки в его голосе вполне можно было назвать милыми.

– Так давай сбежим отсюда. Уедем во Львов или куда душе угодно, и там тебе не придется работать. У меня украинское гражданство и большущий опыт работы в разных сферах. Ты сможешь отдохнуть, а я… 

– Лиза, не начинай.

– Я готова хоть целый год работать за двоих, только бы мы убрались из Симферополя. Ну же, Веня, соглашайся!

К тому моменту мы уже вернулись в Симфер. Метель сменилась проливным дождем, что превращал все вокруг в одно сплошное болото. К вечеру, правда, дождь прекратился, а ночью вновь пошел снег.

– Я просто не хочу возвращаться на работу.

– А чего хочешь?

На мне не было ничего, кроме банного полотенца. Я распаковывала чемодан, а Веня сидел в плетеном кресле, тщетно пытаясь найти фильм ужасов, который мы еще не видели.

– Блинчиков! – неожиданно заявил он.

– Блинчиков?

Надо признать, проведя неделю без секса, ожидаешь чего-то более эротичного.

– Ты же знаешь, я не умею их готовить. Но я умею кое-что другое… – я сняла полотенце и отшвырнула его в сторону.

Увы, на Веньку этот жест не произвел должного впечатления. 

– Ну, пожа-а-алуйста, – попросил муж, не отрываясь от компьютера. 

Пришлось надеть халат и отправиться на кухню.

Говорят, первый блин всегда комом, но, как по мне, эта фраза многого недоговаривает. Первые десять блинов всегда комом, а то, что выйдет после них, все равно с трудом соответствует ожиданиям и больше напоминает уже кем-то пережеванную пищу – вот как на самом деле обстоят дела. К тому моменту, как я закончила возиться с готовкой, мне уже не хотелось ни есть, ни жить.

– М-м-м, с грибами и сыром, – протянул Веня, уминая результат моего труда. – Я думал, они будут без начинки.

На самом деле, я тоже так думала, но блины вышли слишком кривыми, и мне пришлось завернуть их конвертиками и засунуть что-то внутрь, чтобы спрятать оборванные края. 

– Я женюсь на идеальной женщине, – подытожил Венька, когда на столе не осталось ничего, кроме грязной посуды.

– Я женюсь на идеальной женщине, – повторил он спустя сорок минут, одну сигарету и два оргазма. 

Это был вечер воскресенья.
