# 82 {-}

Понедельник встретил нас ярким солнцем и заснеженными дорогами. За ночь выпало так много снега, что некоторые сугробы были практически моего роста. В них вполне можно было бы потеряться, и это напомнило мне о детстве.

Зима девяносто пятого. Мороз и солнце, на котором переливались высоченные сугробы. Тем днем на улицах не было ни души, и даже круглосуточные магазины были закрыты из-за непогоды. Отец отвел меня на футбольный стадион, который теперь напоминал один гигантский пласт никем не тронутого снега.

У меня были очки и трубка аквалангиста, надев которые, я с радостным визгом ворвалась в блестящую, хрустящую снежную массу. Огромное белоснежнее поле, превратившиеся в сугроб вдвое выше меня – и все это принадлежало лишь мне одной!

– С детства не видела такого снега, – произнесла я, заворожено глядя на всю эту красоту. – А ты?

– А я вообще никогда такого не видел, – ответил Веня. – Если не считать той зимы, когда я был в шестом классе. Меня оставили после уроков переписывать контрольную по математике. Я сидел в классе совершенно один, когда за окном вдруг посыпал снег…

Тем утром мой муж был болтливее, чем когда-либо. Одну за другой он вспоминал истории из детства и рассказывал их мне на протяжении всего пути. Обычно дорога до его офиса длилась от силы минут тридцать, но из-за непогоды транспорт ходил редко и медленно, так что путь занял вдвое больше времени.

Если честно, Веня говорил так много, что я с облегчением выдохнула, когда мы, наконец, приблизились к воротам склада.

– Лак для волос, лак для ногтей и… Что еще там у тебя закончилось?

– Бальзам для волос.

– Точно, бальзам! Не хочешь зайти и выбрать сама?

– Мне нужно успеть на рынок, милый. Хочу успеть попасть в ту лавку до того, как у них закончатся домашние куры, – соврала я.

Никакой лавки с домашними курами я не знала. Я покупала мясо в супермаркете, но несуществующая точка на рынке уже не впервой служила мне отмазкой от встречи с начальством Вениамина.

– Так у нас на ужин будет курица?

– Ага. Я запеку ее с ананасами и еще какой-нибудь херней.

– Жду не дождусь, – Венька поцеловал меня в обе щеки и подкурил.

– Хорошего дня, любимый.

– Хорошего дня, деточка.

Он поцеловал меня снова. На этот раз в губы, да так трогательно, что на какой-то миг почва ушла из-под моих ног.

Около ворот я оглянулась посмотреть на своего мужчину. Все так же попыхивая сигаретой, он уже увлеченно рассказывал о чем-то высыпавшим на крыльцо коллегам. Держа сигарету в зубах, Веня красочно жестикулировал обеими руками. Сколько раз я видела его таким? Должно быть, сотни две, не меньше.

Его борода и волосы очень быстро покрылись снегом, но Венька то и дело что-то повторял, указывая на свой блокнот. Затем муж резко обернулся, словно почувствовал на себе мой взгляд. Он махнул рукой и улыбнулся мне сквозь миллиарды падающих с небес снежинок. Я улыбнулась в ответ и зашагала в сторону остановки, с ног до головы охваченная облаком эйфории.

<div style="text-align: center;">***</div>

Снег все сыпал и сыпал. Улицы больше не выглядели грязными, облаченные в снежный покров деревья сияли в лучах зимнего солнца, покрывшийся льдом пруд блестел и лоснился, и все вокруг вновь казалось мне прекрасным. Я вновь чувствовала себя счастливой. Одна лишь мысль о Вениамине вызывала на моем лице широченную улыбку, и ни холод, ни грубость прохожих, ни напрочь подгоревший кофе, который мне подали в попавшейся на пути кофейне, не могли стереть с моих губ эту улыбку.

А что если дело и правда не в городе? Быть может, и в этом доктора были правы, подумалось мне.

Вдруг я действительно драматизирую, а город – это всего лишь предлог, чтобы оправдать очередную депрессию. Если доктора не ошиблись, я буду несчастна в любом месте. Буду винить города и менять их до тех пор, пока не пойму, что дело во мне…

Мы никогда не ссорились по пустякам, не ругались из-за быта, банального недопонимания и прочих вещей, на которые обычно жалуются живущие под одной крышей люди. Половина наших семейных ссор была вызвана Венькиными кутежами, а все остальное – моей жаждой как можно скорее убраться из Симферополя.

Так, не лучше ли признать это сейчас? Пока твое упрямство окончательно не разрушило это счастье?

Ох уж эти проблемы с головой! С ними никогда толком не знаешь, какое из твоих а-что-если откровений окажется верным, а какое нужно отнести с беспросветно бредовым идеям.

«Ты не способна трезво оценивать ситуацию», – на протяжении многих лет все кому не лень внушали мне эту мысль. В свои двадцать три я, наконец, этому поверила и теперь с трудом могла отличить правильные мысли от неправильных. Я была прекрасным оратором, могла убедить кого угодно и в чем угодно, а потому, что бы ни пришло мне в голову, это всегда звучало правильно и убедительно.

*Своими разговорами о переездах ты только ебешь мужу мозги*, прошипел голос в моих мыслях.

*Разве этого ты хочешь, деточка?*

– Нет! – импульсивно ответила я, заставив обернуться проходившую мимо парочку.

Погруженная в собственные размышления, я и не заметила, как свернула не в ту сторону. Вместо привычного короткого маршрута я выбрала длинный и куда менее удобный в нелетную погоду путь. Он лежал через находившееся на холме кладбище, и я поняла, где нахожусь, лишь когда поднялась на самую вершину.

Как я уже говорила, это место всегда притягивало меня своей тишиной и спокойствием. Но больше всего я любила кладбище за это непередаваемое ощущение уединения, какое бывает разве что в лесах и под водой.

Стоя на вершине холма, я разглядывала раскинувшийся у подножья город. Его большая часть скрывалась под снежной пеленой, а открывающиеся глазу дороги, дома и улочки выглядели спящими. Куда ни глянь, все вокруг излучало умиротворение. Словно невидимыми потоками, это умиротворение поднималось над городом и проникало в меня каждый раз, когда пропитанный свежестью воздух наполнял легкие.

Какое же странное это чувство – счастье, думала я, мечтательно рассматривая окрестности.

Когда ты счастлив, все вокруг вдруг обретает смысл и жизнь больше не кажется тебе такой уж паршивой. Меня охватил покой, и я буквально чувствовала, как его ветви расползаются вдоль и поперек моего тела.

Мне захотелось прогуляться по кладбищу прежде, чем возвращаться к домашним делам. Спешить было некуда. Время уже давно перевалило за полдень, так что всех домашних кур в несуществующей мясной лавке, куда я заглядывала каждый раз после того, как провожала мужа на работу, уже все равно разобрали. И я неспешно зашагала по кладбищу, разглядывая усыпанные белизной надгробья и с по-детски трепетным наслаждением слушая, как снег скрепит под подошвой моих ботинок.

Подавляющее большинство встретившихся на моем пути тропинок были идеально ровными. Лежавший на их поверхности снег не был тронут ногой человека, и я не могла удержаться от того, чтобы первой по нему пройтись, а Дилан в моих наушниках пел:

*Позволь же мне раствориться*

*В кольцах дыма моего разума бремени,*

*Проникнуть в туманные руины времени,*

*Подальше от листьев замерзших*

*Призрачных деревьев иссохших,*

*Далеко на ветреном пляже,*

*Где цепким рукам даже безумной печали меня не достать.*

*Там, где под бриллиантовыми небесами я смогу плясать*

*Размахивая свободной рукой,*

*Вырисовываясь на фоне пучины морской, в кругу бурлящих песков*

*Моей памяти и судьбы оков,*

*Что погружаются глубоко под волн покров,*

*Позволь мне забыть сегодня, пока не наступит завтра.*

Я пробиралась сквозь покрытые инеем заросли и кружилась в вихре снежинок, ведомая охватившей меня радостью, но этой прогулке не суждено было продлиться. В разгар следующей песни я шагнула в очередной сугроб, но тот оказался лишь горсткой снега, прикрывающей яму. Какая-то доля секунды, и я уже лежала на дне приготовленной для кого-то могилы. Слишком влажной и глубокой, чтобы я смогла самостоятельно выбраться. 

*И что мы будем делать, гений?*

Размышляя об этом, я положила руку под голову, извлекла из кармана пальто сигарету и покурила, наблюдая за тем, как кружившие в небе снежинки плавно опускались на землю.
