# 83 {-}

– Говорят, это плохая примета, – раздалось откуда-то сверху.

За голосом последовали приглушенные шаги, и вскоре я увидела пожилого мужчину. Его заросшее неопрятной бородой лицо склонилось над могилой и теперь в волнении глядело на меня сверху вниз.

– Помощь нужна?

– Нет, что вы, я просто прилегла немного отдохнуть.

– Ну как знаете…

Поразительно, но в мире до сих пор существуют люди, неспособные распознать нотки сарказма в моем голосе. Незнакомец выпрямился и, по всей видимости, собрался уйти, так что я выплюнула сигарету и поспешно вскочила на ноги со словами:

– Да, мне нужна помощь!

Этот мужчина был одним из многих бездомных, которых частенько можно встретить на кладбище. Обычно я не водила с ними знакомств, но, глядя на это не знавшее мыла лицо, была уверена, что прежде мы уже встречались.

– Я вас знаю? – спросила я после того, как мужчина помог мне выбраться из свежевырытой могилы.

Издали он походил на старика, но при ближайшем рассмотрении я поняла, что незнакомцу от силы лет сорок.

– Все может быть, – ответил он. – Если вам нравится фотография.

Затем бездомный улыбнулся мне, но как-то очень грустно.

– Фотография?

– Я был преподавателем. Ездил по всему Крыму. Читал лекции по фотографии для старших курсов. Даже несколько учебников написал в свое время, до того, как меня вышвырнули на улицу. Но я такой не один. Многих вынудили уйти, когда мы отказались играть по их правилам.

Несмотря на свой неприятный внешний вид, мужчина говорил четко и с расстановкой. Он звучал куда грамотней большинства моих знакомых, которым было где жить.

– Каким таким правилам?

– Я был против того, чтобы Крым стал частью Российской Федерации. Многие были против, раз уж на то пошло. С приходом новой власти нас просто вышвырнули на улицу. Не угостите меня сигаретой?

Я вновь достала из кармана сигаретную пачку и протянула ее своему спасителю.

– Нет-нет, – краснея произнес тот; он стыдливо опустил глаза и добавил: – Достаньте сами, мои руки… Они очень грязные.

Это определенно был самый вежливый бездомный в моей жизни. Я дала ему сигарету и указала на пустующую могилу.

– Почему вы сказали, что это плохая примета?

– Так в народе говорят. Вы не поверите, в старину люди не боялись кладбищ. Покойников часто хоронили под порогом дома, а на месте кладбищ даже строили целые поселения, чтобы…

– Чтобы покойники защищали их дома от злых духов, я знаю.

– Все верно.

Мужчина выпустил несколько колец дыма и продолжил:

– В народе говорят, что упасть в чужую могилу – это не к добру. Считается, что таким образом кладбище предупреждает нас о чем-то.

– О чем?

– Толком не знаю. О чем-то плохом.

Я вежливо улыбнулась и сказала, что не верю в приметы.

– Можете не верить, – серьезно ответил мужчина, – но это место мертвых, и вам здесь делать нечего.

Последнюю фразу он произнес на повышенных тонах, и я, наконец, вспомнила, почему лицо бездомного показалось мне знакомым. Его армейский товарищ обкурился конопли и пропал в том самом пруду, где я откисала прошлым летом, когда мы с Веней впервые приехали в Симферополь.

«Так его и не выловили, так что и вам здесь делать нечего!» – крикнул мужчина тем утром.

Происходящее казалось странным. Мне вдруг сделалось не по себе и захотелось убраться отсюда как можно скорее. Я наспех поблагодарила мужчину за помощь и поспешила к обратной стороне холма.

– Можете не верить, – крикнул мне в след бездомный. – Но кладбище вас предупредило.

Я сделала вид, что не услышала его слов.

Что ж, я никогда не боялась могил или кладбищ, а потому толком не могла понять, почему слова незнакомца вызвали в моей душе тревогу. Мне пришлось еще часа три бродить по городу, дожидаясь пока это чувство исчезнет. Домой я вернулась лишь с наступлением темноты.

«Ты дома?» – написал Вениамин, стоило мне появиться в онлайне.

Я ответила, что дома. Вслед за этим раздался телефонный звонок.

– Привет, родной!

– Собирай вещи, Лиза, – без приветствий сказал Веня. – Твой автобус отходит через четыре часа.

– Что?

Это походило на очень неудачную шутку, но голос Вениамина был полон серьезности.

– Я хочу, чтобы к моему возвращению тебя здесь уже не было.

– Что случилось?

– Ничего, – холодно отрезал Веня. – Просто я тебя больше не люблю.

И он отключился.

Перезвонил через пару часов, чтобы узнать, собрала ли я вещи.

– Поговорим, когда вернешься домой, – мягко ответила я, всей душой стараясь скрыть следы одолевшей меня накануне истерики.

– А может, я не вернусь сегодня?

– Я не против.

Мужчина по ту сторону телефона явно ждал другой реакции. Он резко вдохнул и затаил дыхание.

– И что ты будешь делать? – удивленно спросил Веня.

– Подумываю заварить чаю.

И я отключилась, невольно поражаясь своей актерской игре.  

Это был понедельник.
