# 84 {-}

Стрелки на часах, казалось, двигались с невыносимо медленной скоростью. В какой-то момент они и вовсе отказались шевелиться. Я бродила вдоль крохотной террасы, глядя куда-то сквозь горы. Мерила шагами спальню, не имея ни малейшего представления о том, что меня ждет.

Обычно Вениамин заканчивал работу к шести, но тем вечером он не вернулся домой к половине седьмого. Как не вернулся и в семь, и тремя часами позже. За это время меня охватила не просто паника. Это был настоящий ужас. Ни с чем не сравнимый животный страх, какого я никогда прежде не испытывала.

До наступившего вечера я и подумать не могла, что способна бояться чего-то настолько сильно, и теперь с печальной улыбкой вспоминала, как когда-то так же думала и о счастье. Просто не верила, что могу быть настолько счастливой. Удивительно, как один и тот же человек способен вызвать в тебе настолько яркие, но до неприличия противоречивые эмоции.

Мои руки тряслись, мешая поджечь сигарету, но к полуночи я выкурила целую пачку, а Германа все не было. Я прикончила купленную к ужину бутылку вина, а его все не было. Я сменила постель, приготовила ужин и в сотый раз вышла на террасу, а Вени по-прежнему не было дома. И чем дольше я ждала, тем сильней становился охвативший меня страх.

Сложно объяснить, чего именно я так сильно боялась. Чувство это росло с каждым часом, что я проводила в слепом ожидании. Контролировать его становилось все труднее и труднее. Вместо мыслей в голове у меня образовался настоящий винегрет. Десятки внутренних голосов, непонятно кому принадлежавших, стонали, орали, ныли и слезно скулили наперебой, так что я не могла разобрать ни слова. Они задавали слишком много вопросов, ответов на которые я не знала. Но даже это не мешало мне то и дело прислушиваться к уличной обстановке.

Стоило какой-нибудь машине появиться на нашей улице, и я тут же мчалась к окну. В один из таких забегов я бросила взгляд на встретившееся мне зеркало, чтобы увидеть несколько поседевших волос, что заметно выделялись на фоне темных локонов.

– Этого еще не хватало!

Мне только исполнилось двадцать три, и я не без интереса провела рукой по седым волоскам, даже не подозревая, что к утру их будет гораздо больше.

Наконец, паника добралась и до остальных частей моего тела. Сперва задрожали колени, а вскоре меня уже вовсю колотило от страха. Мои глаза потеряли фокус. Мир перед ними поплыл, все сделалось желтым, а затем почему-то еще и синим – два ненавистных мне цвета. Сама не знаю почему, они всю жизнь вызывали во мне раздражение. Цвета как бы накладывались друг на друга, так что кровать, на которой я сидела, комод, плетеные кресла с круглым столиков и другие предметы в комнате раздвоились, став одновременно и желтыми, и синими. 

Нарастающий гул в ушах достиг апогея, и я поняла, что не чувствую собственного тела.

Кажется, я теряю сознание, успела подумать я, и упала на подушки.

<div style="text-align: center;">***</div>

Входная дверь нашего дома с грохотом распахнулась, вытаскивая меня из беспамятства. Вениамин быстро пересек кухню, включил в спальне свет и разочарованно произнес:

– Так и знал, что ты не уедешь.

Затем он развернулся и исчез на кухне.

Лежа в постели, я слышала, как муж тарахтит посудой и роется в холодильнике.

– Курица в духовке, – напомнила я.

– Я не стану ее есть.

– Почему?

Веня ничего не ответил. Выскользнув из постели, я на цыпочках подошла к дверному проему и тупо наблюдала за тем, как муж делал бутерброды из того, что смог найти в холодильнике. Я провела в дверях несколько минут, не зная, что и сказать. Думаю, простояла бы там еще дольше, если бы Вениамин не обернулся.

– Значит, уедешь утром, – бросил он, исподлобья разглядывая мои голые ноги.

Я с опаской подошла к сидевшему за столом мужчине и опустилась напротив.

– Венька, ну что же ты делаешь?

Ответа не последовало.

– Ты встретил другую женщину?

– Нет.

– Тогда в чем дело? – я положила руку на плечо Вениамина, но он тут же ее сбросил.

– Ни в чем. Я просто больше не хочу тебя видеть.

– Но как так? Я не понимаю! Этим утром ты говорил, что любишь меня, а теперь…

– Я тебе врал, – без заминки ответил Веня, и спокойствие в его голосе меня убивало. – Я тебя больше не люблю.

– А теперь посмотри мне в глаза и скажи это еще раз.

Он наклонился и обхватил мое лицо руками. Сейчас Веня был так близко, что я могла ощутить его горячее дыхание, и с ужасом поняла: Вениамин был абсолютно трезв. Откинув со лба волосы, муж взглянул на меня с раздражением и произнес, четко выговаривая каждое слово:

– Я. Больше. Тебя. Не. Люблю. Васляева.

– Давно?

Он пожал плечами и вернулся к ужину, не обращая никакого внимания на слезы, что уже во всю текли по моим щекам.

– Ты никогда не станешь любящей женой и заботливой матерью, – вдруг добавил он. – Ты не способна вдохновить ни одного мужчину. Я больше не хочу тебя видеть в своем доме.

Почему эти слова были мне так знакомы? Или только интонации? Нет, слова, точно слова! Я слышала их в начале лета, когда муж впервые поднял на меня руку.

Нужно было уехать от него еще той ночью, с болью подумала я. Почему я не уехала от него той ночью?!

Но стоя посреди кухни в слезах и полной растерянности, я понимала, что, даже если бы самый мудрый человек в мире подошел ко мне той знойной ночью и рассказал, как закончатся наши отношения, это все равно ничего бы не изменило. Знай я обо всех предстоящих пьянках и изменах, которых, кстати, оказалось куда больше, чем я думала, я бы все равно никуда не уехала. Я бы осталась с ним и сделала бы все возможное для того, чтобы не допустить подобного конца. Даже если бы знала, что это невозможно.

Такой вот я была дурой.
