# 85 {-}

– Прошу тебя, просто объясни, в чем дело?

Сидевший напротив меня мужчина был все так же спокоен, чего нельзя было сказать обо мне. Я старалась говорить максимально спокойно, но чувствовала, что еще немного, и я упаду перед Веней на колени и начну умолять не бросать меня. Прямо как одна из тех бесчисленных девиц, о которых он мне рассказывал.

– ДА ПРОСТО СКАЖИ МНЕ, В ЧЕМ, МАТЬ ТВОЮ, ДЕЛО? – неожиданно для себя самой заорала я. – ТЫ НЕ МОЖЕШЬ ВЕСТИ СЕБЯ СО МНОЙ КАК С ДЕШЕВОЙ ШЛЮХОЙ, ВЕНЯ!

– Вообще-то могу.

И он улыбнулся самой отвратительной в мире улыбкой, чем разозлил меня еще сильнее. Поддавшись слепой ярости, я схватила стоявшую на столе тарелку и запустила ею в Вениамина. Та пролетела в паре сантиметров от головы моего мужа и с грохотом разбилась позади него.

Вениамин словно только этого и ждал: он тут же подскочил. Мгновение спустя я уже была прижата к стене, а пальцы Вениамина сомкнулись на моем горле.

– Не заставляй меня делать то, о чем мы оба будем жалеть, – прошипел он.

– Но я люблю тебя, Веня! Я не могу без тебя!

– Сможешь.

– Ты меня убиваешь.

– Нет. Я делаю тебя сильнее, – сухо ответил он и убрал руку.

Пекущий зуд в горле вернулся, но я продолжала говорить, не придавая ему особого значения.

– Все это время, что тебя не было, я была как в аду, понимаешь? Неужели, я, по-твоему, не заслуживаю нормальных объяснений?

– И как, тебе понравилось?

– Что?

– Тебе понравилось быть в моем аду?

Я лишь покачала головой, глядя на своего собеседника полными боли глазами.

– Так вот, если ты не уедешь, я превращу всю твою жизнь в ад, – пообещал Вениамин не оставляющим сомнений тоном.

Я вспомнила яму, в которую угодила минувшим утром. Вспомнила холод кладбища, запах сырой земли, да копошившихся в ней червей, и вдруг поняла, что совершенно не хочу умирать.

– Я не хочу умирать! – с удивлением произнесла я.

Вениамин ухмыльнулся.

– Какая прелесть.

Сделал пару шагов в сторону стола и как бы невзначай добавил:

– Но если ты вдруг передумаешь, сделай это подальше от меня, – сказал мужчина, которого я любила куда больше, чем следовало.

<div style="text-align: center;">***</div>

Что же мне делать? – этот вопрос то и дело звучал в моих мыслях.

Всю ночь я ворочалась в опустевшей постели – Вениамин больше не проронил ни слова, лишь указывал мне на стоявший в углу чемодан, изредка отрываясь от телефона, и показательно лег спать на полу – и чувствовала себя самым уставшим представителем человеческой расы. Но так и не смогла забыться сном.

Временами я закрывала глаза, чтобы хоть как-то унять боль, что зародилась в висках и вскоре охватила всю черепную коробку. А что было толку? Ведь стоило мне хоть на мгновенье прикрыть глаза, и перед ними тут же вырастали картины нашей совместной жизни. Какое-то время я поддавалась этим видениям из подсознания, но не хотела заходить слишком далеко, боясь, что после этого вернуться к реальности окажется куда сложнее.  

Колесо Сансары вращалось до самого рассвета. Я бездумно смотрела в никуда, прежде именуемое потолком, до тех пор, пока головная боль не опускалась в глазные яблоки. Затем закрывала глаза, мимо воли окунаясь в сюжеты из последнего года моей жизни. Они напоминали призрачные слайды и тут же исчезали, стоило мне присмотреться к деталям. Затем вновь открывала глаза, и все повторялось. Таким образом прошла большая часть ночи.

Наконец, наступил момент, когда самообладание принялось сдавать. Я уже не могла открещиваться от призывов подсознания и с выдохом напрочь иссякшего человека позволила одной из этих картинок увести меня за собой.

По какому-то комичному стечению обстоятельств ею оказалось воспоминание о ночи, которой Веня клялся мне в вечной любви, проводя ножом по загоревшей плоти. Зависшая над севастопольским морем луна ухмылялась мне своей бездушной гримасой; лезвие ножа сияло в ее холодном свете.

– Я люблю тебя, Васляева, и буду любить вечно, – шептало на ухо горячее дыхание. – Я люблю тебя, как не любил ни одну женщину…

Вениамин поднес мою пострадавшую руку к своим губам. Поцеловал в месте будущего шрама, перепачкавшись кровью, вновь приложился к порезу и сделал несколько глотков моей крови.

От увиденного меня начало мутить, но Вениамин без запинок протянул мне свою руку.

– Всего пару капель, – мягко сказал он, прижимаясь рукой к моим губам.

Спорить я не стала.

– Теперь мы муж и жена! – с мальчишеским восторгом провозгласил Веня. – Я люблю тебя, радость моя, и клянусь хранить тебе верность. Теперь мы всегда будем вместе. Отныне и навек.

Он заключил меня в объятья, и долгий поцелуй унес нас куда-то далеко над морем, спящим городом и без устали бушующей линией моря.

– Но нам все равно нужно расписаться, – чуть погодя добавил муж.

– Зачем?

– Я люблю тебя, как не любил ни одну женщину. И я хочу жениться на тебе как можно скорее, деточка. Хочу, чтобы ты стала Елизаветой Ларионовой, и тебе никогда бы не понадобилось уезжать от меня. Разве ты мне не веришь?

– Верю и клянусь тебе в том же. Но если ты обидишь меня, я возьму этот самый нож и проткну им твое сердце. В этом я тебе тоже могу поклясться.

– Проткни, – ответил муж, обнимая меня за плечи. – Мне все равно не нужна эта жизнь без тебя.
