# 86 {-}

На этом воспоминание оборвалось. Я переместилась в настоящее, вынужденная вновь пережить события минувшего дня. Вот Веня звонит мне, чтобы сообщить, что больше не любит. Вот он возвращается с работы, разочарованно глядя на меня, спящую в нашей постели. Вот он прижимает меня к стене, покидает кухню, удаляет со своей страницы все наши фото и без зазрений совести начинает знакомиться с другими женщинами.

Вот он показательно укладывается спать на полу, а я лежу на кровати – в метре от него, но при этом в полнейшем одиночестве – лишенная сна и повторяю один и тот же вопрос.

Что мне делать?

*Что мне делать? ЧТО МНЕ ДЕЛАТЬ?*

В душе я понимала, что смогу жить без Вениамина. Пускай боль обиды и разочарования была сильна, она не могла быть невыносимой. Ведь мое сердце не остановилось, кровь не застыла в венах, а легкие продолжали дышать. Значит, я могла вынести эту боль, но…

Было здесь кое-что еще. Меня не покидало давящее чувство несправедливости, что в итоге превратило печаль в исступление. Все эти женщины, которых я почувствовала, впервые приехав в Керчь, все эти молодые девушки на пике первой влюбленности – все эти истерзанные души, которых муж обрек на жалкое существование. Те, кого он так просто втоптал в комплексы, лишил воли к жизни и веры в любовь. Сколько из них по сей день не могут обрести покой?

*Хочу, чтобы ты стала Елизаветой Ларионовой…*

Сколько жительниц полуострова сейчас бессонно лежит в своих постелях, со слезами или страхом вспоминая Вениамина Ларионова? Сколько из них пустились во все тяжкие и стали спать со всеми подряд, разуверившись в идеалах любви да семейного очага? Сколько душевных девочек стало черствыми эгоцентристками, отравляющими жизнь близким? А сколько из них пытались наложить на себя руки и кому в конце концов это удалось?

*… и тебе никогда бы не понадобилось уезжать от меня.*

Сколько бы их ни было, в конечном счете они оказывались отравленными Вениамином. И, быть может, сами того не зная, несли этот яд по жизни, наполняя им окружающих.

Никто не имел права так с ними поступать. Тем более осознанно.

*Так сколько же их было? А сколько еще будет?*

Но не ответ на этот вопрос занимал мою голову. Все, чего я хотела – прервать этот порочный круг раз и навсегда.

*Что же мне делать?*

Помнится, сперва я желала, чтобы этого человека никогда не было в моей жизни, но к наступившему моменту сна во сне мое эго зарылось глубоко в землю. Меня интересовала не перспектива собственных обид, а мысль о том, сколько еще юных жизней будет разбито моим мужем.

*Я люблю тебя, как не любил ни одну женщину.*

Кто-то должен был это остановить.

*Что мне делать?*

*Я люблю тебя, Васляева, и буду любить вечно. Разве ты мне не веришь?*

*Заткнись.*

*Мне все равно не нужна эта жизнь без тебя.*

*ДА ЗАТКНИСЬ! ЗАТКНИСЬ! ЗАТКНИСЬ ТЫ, СУКИН СЫН!*

Крик собственного голоса выбил меня из сна. Я подорвалась на ноги и тут же упала: щиколотки были перемотаны скотчем. Как и кисти рук. Что-то в этом положении казалось мне смутно знакомым.

– Это я сукин сын?! – яростно выкрикнул Вениамин, когда я вновь поднялась на ноги.

Ударил меня наотмашь тыльной стороной ладони. Повалил на кровать и, прыгнув сверху, принялся хлестать по щекам. Как ни странно, чем больше ударов он наносил, тем меньше меня это беспокоило.

В итоге боль окончательно притупилась. Я ощущала лишь ее призрачные отголоски на своих щеках и тупо смотрела в стальные глаза мужа, понимая, что отсутствие реакции на боль злит его куда сильнее самой ситуации.

А почему, собственно, он меня лупит? И откуда взялся этот скотч на моих конечностях?

Это не может быть реальностью. Но все это со мной как будто уже происходило. Да, происходило. Осенью, когда я вернулась из Николаева, куда бежала на целый месяц, узнав от Риммы о назревающей измене.

Осенью. А разве сейчас осень?

– Ты сама выкопала себе эту яму, Васляева!

Яму?

Еще один удар.

– Не нужно было со мной спорить. Ты сама меня спровоцировала. Зачем ты стала себя резать? Ты же знаешь, как меня это раздражает!

*Выкопала яму…* – эти слова показались мне очень важными.

Я вцепилась за них как утопающие хватаются за спасательный круг.

– Но ты сказал, что я стою того, чтобы мне изменить, – почти автоматически ответила я. – Сказал это, когда боль измены была еще свежа!

– Я такое сказал?

– Да!

– Быть этого не может!

– Да только что сказал!

– Я такого не помню, а значит – этого не было.

Классическое оправдание Вениамина.

Муж громко выдохнул и потянулся к прикроватной тумбе. Взял свой складной нож и парой механических движений распорол сковывающий мои руки скотч. Похоже, Веня начинал трезветь.

Смотреть на него было тошно. Я отползла подальше от мужа и забилась в дальний угол нашей однушки, принявшись растирать пальцами кожу головы. Последняя жалостливо постанывала от недавних приключений.

– Прости, что таскал тебя за волосы, – вдруг сказал Вениамин.

Даже не глядя, я знала, что его глаза понемногу начинают приобретать прежний изумрудный оттенок.

– Да ничего.

– Я этого не хотел, но ты сама вырыла эту яму и сама же в нее угодила.

Эти слова заставили меня оторваться от волос.

– Что ты сейчас сказал?

И я в упор посмотрела на Веню. Тот сидел на кровати, подперев голову руками и без особого интереса рассматривал лезвие ножа.

Вырыла яму?

– Что ты сейчас сказал? – повторила я.

– Не помню, а что?

Угодила в яму? Так он сказал?

Муж был одет в одно исподнее. Это показалось мне странным: дом был холодным, когда я ложилась спать. Вслед за этой мыслью потянулась следующая – о снежных хлопьях, мирно парящих за окном.

– Какое сейчас время года, Веня?

Муж посмотрел на меня как на дуру.

– Идиотский вопрос, – заключил он. – Совсем, что ли, с катушек съехала, Васляева?

И я вновь повторила вопрос.

– Сейчас лето.

– Быть того не может.

– Посмотри в окно и узнаешь, – сухо ответил Веня, возвращая свое внимание ножу.

Мои вопросы ему явно наскучили.

Я перевела взгляд в сторону окна и…

Никакого окна в комнате не оказалось. Теперь не его месте виднелась лишь глухая стена, заменившая собой еще и дверь на террасу.

*Не забывай о яме*, строго напомнил внутренний голос.

Вениамин, казалось, ничего не замечал. Лишь продолжал натирать лезвие своего перочинника.

*Думай о яме.*

Какой яме?

Тогда я поднялась на ноги и медленно подошла к тому месту, где прежде было окно. Сейчас о нем напоминала лишь прозрачная занавесь, что по-прежнему свисала с карниза.

Присмотревшись я поняла, что занавеска колышется. Протянула к ней руку и мигом ощутила леденящий душу холод, сквозящий словно из ниоткуда и в то же время отовсюду.

*В которую ты угодила.*

Перед мысленным взором вновь возникли сияющие хлопья снега. Они беспечно парили в воздухе и медленно опускались на землю, наворачивая круги вокруг собственной оси.

*Говорят, это плохая примета. Упасть в чужую…*

И тут я все вспомнила. События минувшего утра калейдоскопом пронеслись перед моими глазами.

– Так это сон, – прошептала я, но от этой мысли меня охватила тревога. – Всего лишь дурной сон. Сон и больше ничего.

За спиной раздался смех. Ледяной, как тот холод, что настойчиво заполнял комнату.

Мне не хотелось оборачиваться.

Занавеска взметнулась, сорвалась с карниза и с бешенной скорость свалилась на пол, оставляя за собой звук бьющегося стекла.

Точно сон! Ведь занавеска была слишком легкой, чтобы падать так стремительно. И она уж точно не могла звенеть.

– Это всего лишь дурной сон, Васляева. Тебе нужно проснуться, – и с силой зажмурила глаза, воображая, как проснусь в теплой постели. За окном будут парить снежинки, солнце засияет совсем по-зимнему, а муж будет мирно храпеть у меня под боком, и весь этот ужас – его звонок и слова, и боль, и крики – окажутся лишь дурным сном.

Но я не просыпалась.

*Вот, Веня, там спит твоя жена.*

Смех повторился. А когда я все-таки обернулась, ожидая увидеть себя спящей, кровать оказалась пустой. Лишь в самом центре аккуратно застеленного одеяла виднелся перочинный ножик.

Вениамин в уличных одеждах спал на полу, по обыкновению подложив руки под голову. Даже сейчас, во сне, он казался мне до ужаса прекрасным.

*Я не обижу тебя.*

Я медленно обошла кровать и застыла у ног своего мужа, пытаясь понять, как мне проснуться. Сама того не заметив, я вернулась к вопросу, с которого все началось.

*Что мне делать?*

*Скольких еще он отравил?*

*Буду собирать твое разбитое сердце по кусочкам до тех пор, пока ты не почувствуешь себя в безопасности.*

Голоса вернулись.

*Он с самого начала знал, что так будет.*

*Что мне делать?*

*И ты знала.*

Их становилось все больше и больше с каждой минутой, что я проводила, склонившись над спящим мужем.

*Что же мне делать?*

*Кто-то должен прервать этот круг.*

*Что делать?*

*Ты знала, но не хотела верить.*

*Тебе просто необходимо было кого-то любить.*

*Что мне делать?*

*Себя-то ты любить не способна.*

*Но что я могу?*

Наконец, я перестала различать, кому принадлежат эти голоса, а затем смысл сказанного и вовсе стал туго доходить. Мозг продолжал получать информацию, но наотрез отказывался ее как-либо обрабатывать.

*Любовь делает тебя уязвимой.*

*Хочу, чтобы ты стала Елизаветой Ларионовой…*

*Ты никогда не станешь любящей женой и заботливой матерью.*

*Мы жили вместе полтора года. Я ее не любил.*

Так больше не может продолжаться.

Голоса звенели и звенели. Они шептали и орали, плакали и о чем-то просили, ругая меня на чем свет стоит. Слова любви переплетались с проклятиями, образуя дурманящий гул.

*Лживая самовлюбленная шлюха с комплексом самоубийцы!*

*Лежи, блядь, когда я с тобой разговариваю!*

От этих криков голова шла кругом. Я прикрыла глаза, надеясь унять танцующую во мне мигрень. Ей явно нравилась босанова.

*Теперь мы всегда будем вместе.*

Боль отказывалась отступать. Голоса орали, и я больше не могла им противиться.

*Упасть в чужую могилу – это не к добру.*

*Посмотри на меня, деточка,* – ласковый голос, невыносимо безжалостный в своей правдоподобности, заставил меня распахнуть глаза.

*Сейчас я проснусь в своей кровати*, подумалось мне перед этим.

Но я по-прежнему стояла над спящим на полу мужем.

*Давай же, просыпайся!*                           	

Вот только комната, казалось, стала ярче.

*Так сколько же их было? А сколько еще будет?*

*Что мне делать?*

Прервать этот порочный круг раз и навсегда.

– Но я не могу, – на этот раз вслух произнесла я.

Ты можешь гораздо больше, чем думаешь.

И я увидела нож. Тот самый нож, которым так интересовался Вениамин в предыдущей главе этого странного, бесконечного сна. Нож, которым он проводил вдоль потемневшей под майским солнцем руки, произнося свою клятву.

*Если ты обидишь меня, я возьму этот самый нож и проткну им твое сердце.*

Все это время мои пальцы сжимали холодную рукоятку.

*Ты знаешь, что делать.*

Я опустилась на колени.

*Беги от него!*

*Если ты обидишь меня, я возьму этот самый нож и проткну им твое сердце.*

А почему, собственно, нет?

*Если ты обидишь меня, я возьму этот самый нож и проткну им твое сердце.*

Все это – сон и больше ничего.

*Не смей от меня уходить!*

Правая рука, казалось, жила своей жизнью. Она взметнулась вверх и на мгновенье застыла над грудью спящего мужчины.

*Мне все равно не нужна эта жизнь без тебя.*

*Теперь мы муж и жена.*

*Не смей от меня уходить!*

*Отныне и навек.*

Рука опустилась.

Каких-то полметра разделяли острие ножа с сердцем моего возлюбленного, когда я заметила солнечные блики, игриво скачущие по лезвию.

Окно нашей спальни возвратилось на место, а я – в реальность.

*Как давно я проснулась?* – мелькнуло в голове.

Но затуманенный разум уже дал команду руке, и та не желала останавливаться. Пришлось задействовать вторую конечность.

Собрав последние силы, я перехватила левой рукой правую, направив ее на себя.

Последовавшая за этим боль сразу же меня отрезвила. Голоса тут же исчезли, и я с каким-то недоверием разглядывала нож, торчавший из моего левого бедра.

– Это что сейчас такое было? – спустя несколько минут произнесла я, закрывшись в ванной и отмывая нож от собственной крови.

После чего взглянула в зеркало, где теперь виднелось куда больше седых волос.

Храп Вениамина продолжал доноситься до моих ушей, когда я перематывала пострадавшую ногу. Он сладко спал, ни о чем не подозревая.

*Нужно убраться отсюда*, поняла я, и как можно скорее.

Иначе моя жизнь обещала обернуться сплошным сюрреализмом.
