# Часть III. Все мои самоубийства {-}

# 87 {-}

– Ты можешь в это поверить? – с восторгом спрашивает Венька, разглядывая широкое кольцо, что теперь блестело на безымянном пальце его правой руки.

Глаза его сияли под стать волнам, бушующим за спиной моего мужа. У моих ног раскинулся Фиолент. Где-то совсем близко в лучах заката море сотрясало скалы своим страстным дыханием. Мы стояли на самой верхушке мыса, чья красота способна очаровать даже самого бывалого путника, а я не видела ничего, кроме глаз мужчины, за которого только что вышла. Они светились сотнями тысяч изумрудов, и я в который раз поняла, что никогда не видела его таким счастливым.

– Ты можешь в это поверить, Васляева? – он повторил свой вопрос и тут же расплылся в широкой улыбке. – Ой, я хотел сказать, ты можешь в это поверить, Ларионова?

Веня деловито сложил губы в трубочку и о чем-то задумался, не сводя глаз с наших рук, переплетенных пальцев и колец, что играли в лучах майского солнца.

– Нет, – он клацнул языком. – Мне все еще хочется называть тебя Васляева.

– Технически я все еще Васляева…

– Но ты ведь это исправишь?

– Я подумаю.

Веня прижал меня к себе и крепко поцеловал. Время и пространство вокруг нас перестали существовать, стоило мужу коснуться моих губ своими. Его поцелуй заставил голоса наших друзей затеряться где-то в бесконечности, и лишь шепот морских волн отзвуком проникал в мое сознание.

– А теперь что скажешь? – кокетливо поинтересовался он еще до того, как я успела распахнуть глаза.

– Скажу, что вышла бы за тебя год назад, если бы знала, как это на тебе отразится.

Муж подмигнул.

– Дождись нашей брачной ночи, и ты захочешь выйти за меня снова, – торжественно пообещал он.

И я вдруг с удивлением обнаружила, что залилась краской.

– Александра Валерьевна Ларионова – красиво звучит.

*Только если в твоем алфавите все буквы на месте*, не без ужаса подумала я.

– Словно персонаж из русской классики…

– Эй, голубки, долго вы там еще? – донеслось издалека.

На склоне, метрах в двадцати от нас стояла Лина. На ней были легкие брюки и алый пиджак, который подруга несколько раз успела перешить за то время, что мы переносили свадьбу. В руках девушки были хрустальные шампанки, в глазах читалось нетерпение, но по губам скользила по-матерински теплая улыбка. Эта улыбка как бы говорила: «Ну хорошо, еще минутку можете пообниматься, но затем ноги в руки и шагом марш обратно к реальности».

Подруга махнула нам рукой и отвернулась, но вскоре вдали появилась еще одна фигура. Она ловко сбежала вниз и замерла у основания холма.

– Я принесла шампанское! – радостно крикнула Марта. – И знаете что? Оно само себя не выпьет!

– Кажется, нам пора, – прошептал Веня.

– Похоже на то, – ответила я, с неохотой выбираясь из объятий мужа.

Я бы могла провести здесь вечность, но, пускай я уже успела об этом пожалеть, мы не были единственными на этой свадьбе. Марта, Лина, Вера, Семен и другие из наших немногочисленных гостей были предоставлены сами себе вот уже минут с двадцать, и, кажется, я слышала звук открывающейся бутылки.

Все так же держась за руки, мы медленно двигались в сторону друзей. Вениамин продолжал восторженно разглядывать наши кольца, мое платье и все, что только могло напомнить ему о свадьбе. Прижимаясь к плечу мужа и чувствуя прикосновение его пальцев, я ощущала себя настолько счастливой, что и говорить не хотелось. Но один вопрос у меня все-таки имелся.

– Чувствуешь какие-то изменения?

Венька пожал плечами.

– А ты?

– Нет, – без раздумий ответила я. – Все так же люблю тебя.

– Так это ведь прекрасно, радость моя! Или нет? – добавил он, уловив в моем взгляде сомнение.

– Но разве все так и должно быть? Без изменений?

– Конечно! А ты чего ждала?

– Не знаю. Может быть, того, что после росписи мы тут же возненавидим друг друга? Что в середине церемонии мне на голову вдруг выльют ведро свиной крови? Или того, что кто-нибудь меня ущипнет, и я наконец проснусь в психиатрической лечебнице, из которой мне так и не удалось сбежать?

После этих слов Венька остановился. Он положил руки мне на бедра и с плохо скрытой улыбкой ущипнул за мягкое место.

– Вот, – серьезно произнес муж, – ты не спишь и не в психушке. А что касается ненависти, для этого у нас впереди целая жизнь.

И он вновь обнял меня, на мгновенье скрыв от всего мира. И я опять упала в эти объятья так, словно ждала этого момента на протяжении не одной, а целых десяти неудачных и эмоционально нестабильных жизней. Я спрятала лицо в хемингуэевской бороде, вдохнула этот самый родной в мире запах и на миг провалилась в вечность. Перед глазами промелькнули отрывки из моего прошлого: не прекращающие литься слезы; одинокие вечера, полные самокопания; бессонные ночи, что посещали меня все чаще и чаще; истерики, становившиеся все более настойчивыми, бесконечные скитания по краям собственной депрессии и все мои самоубийства. Сколько бы боли ни причинила мне любовь прежде, это была чья-то чужая скорбь, чья-то чужая депрессия и жажда смерти. Теперь это не имело ко мне никакого отношения.

*Кажись, оно того стоило*, с трепетом в сердце подумала я, поглубже зарываясь в Венькины объятья.

В них я чувствовала себя спокойней, чем где бы то ни было. Мир вне этих объятий исчез, как это случилось в момент нашей первой встречи. Сейчас вокруг не существовало ничего, кроме Вениамина и его крепких рук, укутывающих мои плечи. На этот раз даже море замолкло.

Размышляя об этом, я почувствовала скользнувший по телу ветер. Он вдруг усилился, а спустя пару секунд я уже слышала клацанье собственных зубов. Это заставило меня вспомнить о приближении вечера и об уже, должно быть, совсем заждавшихся нас друзьях, так что я подняла голову. Распахнула глаза, но все так же не видела перед собой ничего, кроме сгустившейся темноты.

– Веня? – тихо позвала я.

Ответа не прозвучало.

– Венька?

Я повторила имя мужа несколько раз. И с каждым новым молчанием я ощущала нарастающую в груди панику.

– Веня?

Тьма сомкнулась вокруг меня удушливой петлей. Внутренний голос предательски молчал, а сердце стучало так сильно, будто готовилось побить скоростной рекорд по отбиванию азбуки Морзе.

*Кажется, я сошла с ума.*

– Веня! – я коснулась безымянного пальца правой руки.

Кольца на нем не было.

Мне понадобилось пятнадцать минут, семь сигарет, один косяк, бутылка рома и три вида транквилизаторов, чтобы вспомнить почему.
