# 88 {-}

Вениамин ушел минут сорок назад, может больше. Разве здесь есть хоть какая-то разница? Он ушел, а я все стояла на крыльце, глядя в ту самую точку, где наша улица плавно переходила в аллею, что исчезала за углом и вела к спуску с горы. 

Спустя еще одну сигарету из соседнего дома вышел Владимир. 

– Доброе утро, Лизавета, – как всегда поздоровался он.

Сосед уже направлялся к машине, когда я вдруг ответила:

– Да ну нахуй!

Это был первый и, в общем-то, последний раз, когда я позволила себе изъясниться подобным образом в присутствии Владимира. Его лицо вытянулось в таком комичном и откровенном удивлении, и мне пришлось объяснить, почему я ставлю под сомнение доброту сегодняшнего утра.

– Вы ничего не путаете? – удивленно спросил сосед.

Я одарила собеседника красноречивым взглядом, благодаря которому он тут же понял, что я ничего не путаю.

– Езжайте в Германию, Лиза. Одна моя подруга там всего ничего, а уже вот какие фотки присылает!

И он действительно принялся показывать мне какие-то фотографии какой-то женщины в каком-то пригороде Германии. Приличия ради я выждала, пока на экране его телефона сменится несколько снимков, а затем сказала:

– Похоже, пора прощаться. Мне нужно еще собрать вещи.

Какое-то время Владимир колебался. Было видно, что ему хочется как-то меня утешить, но тем утром на земле не нашлось бы и половины человека, которому это было бы под силу. Утешить эмоционально нестабильную женщину, от которой только что ушел жених, не оставив никаких объяснений – это что-то из мира фантастики.

– Вам не кажется, что Вениамин еще может передумать? Может, лучше остаться и подождать его?

Я отрицательно покачала головой.

– Нет, мне нужно убраться отсюда как можно скорее.

– Но почему?

– Список слишком длинный.

Владимир стоял всего в паре метров от меня. Он медленно развел руки и просто застыл в этой позе. 

Прямо как Вениамин в день нашей первой встречи.

С долей явной заторможенности я поняла, что сосед хочет меня обнять. Этого никак нельзя было допустить. Я чувствовала, что стоит кому-нибудь меня пожалеть, и я непременно разревусь. А если я разревусь сейчас, то просто не смогу остановиться. Нет, этого никак нельзя было допустить.

– До свидания, Владимир, – сказала я и попятилась к крыльцу.

– Прощайте, Елизавета, – ответил сосед, а потом зачем-то добавил: – Надеюсь, вы найдете то, что ищете.

Я закрыла за собой дверь и едва удержалась от того, чтобы сползти по ней, как героини сопливых фильмов. Вместо этого я выключила музыку, которая до сих пор продолжала играть, 

*Walk in silence...*

*Don’t walk away in silence.*

и начала усиленно пытаться придумать, кому бы мне позвонить.

Позвонить мне, как выяснилось, было некому. В памяти не нашлось ни одного человека, чей голос я бы сейчас хотела услышать.

Кроме, конечно же, любимого мужчины.

– Теперь ты должна называть его бывшим, – отстраненно сказала я, случайно увидев себя в зеркале. 

Зрелище, скажу я вам, довольно жалкое. Растрепанные волосы, непривычно бледная кожа, дрожащие руки, опухшие от слез веки, а под ними мешки размером с Гренландию – все это было ожидаемо. Вот только лицо, смотревшее на меня из зеркала, больше напоминало лицо сумасшедшего, чьи хрустальные замки были беспощадно разрушены. Это были глаза завсегдатая психиатрии. Тусклые, отчужденные, наотрез отказавшиеся принимать происходящее вокруг за действительность. Глаза человека, которого вдруг силой вышвырнули из мира собственных иллюзий и заставили стать частью отвратительной суровой реальности.

– Всегда может стать еще хуже, – добавила я, глядя в эти пустые глаза.

Откровенно говоря, эта фраза никогда не могла меня утешить. Не утешила и на этот раз. Происходящее здесь и сейчас просто не укладывалось в голове. Для него не нашлось ни утешений, ни объяснений.

– Ты знаешь что делать, Васляева. 

*Слова приобретают смысл, когда произносишь их вслух.* 

*Или что-то вроде того.*

*Скажи это.*

И я сказала, слегка удивившись тому, что мне удалось сделать это с первого раза.

– Вениамин ушел от меня. Без прощаний, объяснений и извинений. Ушел молча и без эмоций. Он сделал это с такой легкостью, словно меня никогда и не было в его жизни. Будто я и не бросала ради него все и всех! Я единственная оставалась рядом, когда ему было плохо! Переступала через себя, но проглатывала все те ужасные слова! Мирилась с его пьяными выходками! Забывала так много дерьма… Господи, да ведь я даже блядство ему простила! – я не заметила, как перешла на крик. – Но он и глазом не моргнул! Просто решил, что я больше ему не нужна, и велел мне катиться ко всем чертям. 

Я перевела дыхание.

– Веня ушел от меня… Блядь, не так. ВЕНЯ МЕНЯ БРОСИЛ! МОЙ МУЖ, МОЙ ЛУЧШИЙ ДРУГ, МОЙ ЛЮБИМЫЙ ЧЕЛОВЕК, МОЯ СЕМЬЯ, МОЕ ВДОХНОВЕНИЕ, ОН МЕНЯ БРОСИЛ И ГЛАЗОМ НЕ моргнуЛ! 

*Твое вдохновение?*

*(Ты никогда не сможешь вдохновить мужчину.)*

*Твое вдохновение?*

Где-то в моих мыслях – так близко, что это вполне можно было спутать с реальностью – раздался чудовищный смех.

*Ты и строчки рядом с ним не написала.*

– ОСТАВЬ КЛЮЧИ ПОД КОВРИКОМ! ВОТ И ВСЕ, ЧТО Я ЗАСЛУЖИЛА УСЛЫШАТЬ НАПОСЛЕДОК! И ВОТ Я ЗДЕСЬ, СТОЮ В КОРИДОРЕ И ОРУ НА СОБСТВЕННОЕ ОТРАЖЕНИЕ! ОСТАВЬ КЛЮЧИ ПОД КОВРИКОМ, НУ НАДО ЖЕ! – на этом я изо всех сил ударила кулаком по стене.

Затем еще раз. И еще раз. Била до тех пор, пока рука не онемела, а кровь из разбитых костяшек закапала на пол. Тогда я поняла, что не могу разогнуть пальцы и нехотя прекратила колотить стену. Вытерла лицо от слез и переместилась на террасу. Навеса здесь по-прежнему не наблюдалось. Сидеть на деревянных перекладинах было совсем неудобно, но сейчас это место почему-то сделалось мне еще милее, чем прежде. 

Трясущейся рукой я извлекла из пачки последнюю сигарету. 

– Оставь мне сигарет, – попросила я Вениамина этим утром.

– И не подумаю.

– У меня совсем мало осталось, а все мои деньги за книгу на твоей карте. Ты пришлешь их, когда восстановишь документы?

– Ага.

Он застегнул на себе куртку и принялся укладывать волосы под шапкой, которая когда-то была моей.

– Оставь ключи под ковриком, – бросил муж и скрылся за дверью.

Несколько секунд я провела в полнейшей прострации. Затем кинулась за ним.

– И это все, что ты мне скажешь? – с порога крикнула я.

Вениамин к тому моменту уже закрывал калитку.

– Я опаздываю, – как ни в чем не бывало заметил муж.

Босиком я прошла по снегу, практически не замечая холода. Подошла к Вениамину, в напряжении застывшему у дорожки, чтобы крепко обнять его напоследок. Затем заглянула в эти лазурные глаза и на крохотное мгновение уловила в них отголоски мужчины, который той далекой лунной ночью клялся мне в вечной любви.

– Я очень тебя любила – чуть слышно произнесла я.

Потом он ушел.

А спустя две четверти часа я обнаружила себя сидящей на нашей заснеженной террасе...

<div style="text-align: center;">***</div>

Подкурила и позволила себе в последний раз насладиться открывающимся с террасы видом. Казалось, раскинувшиеся передо мной горы стали еще величественней, а окружавший их лес был еще гуще. И даже птицы как-то особенно красиво парили над извилистым шоссе. Так, словно знали, что мы с ними больше не встретимся, и желали напоследок покрасоваться размахом своих крыльев, столь очаровательно контрастирующим с укрывшимися снегом горами.

Теперь я с жадностью впитывала каждую деталь этой картины, хотя знала ее наизусть. Сидела на полу со скрещенными под собой ногами, безотрывно глядя на царивший вдали пейзаж. Мой взгляд скользил по горным вершинам, холмам, дорогам и деревьям, которые я видела каждый день в течение последних пяти месяцев. Он подолгу задерживался то тут, то там, подмечая все новые и новые детали, а я зачем-то старалась не моргать. Как будто боялась, что обязательно упущу что-то важное, если хоть на миг закрою глаза.

Нет, видневшийся с террасы пейзаж еще никогда не был так очарователен. Странно было осознавать, что я больше никогда его не увижу.

*Разве я могу что-то изменить?*

Вопрос был скорее риторическим. От него веяло холодом, на душе скребли кошки, а в голове сделалось пусто, так что я просто сидела на полу террасы, напрочь забыв о босых ногах, и завидовала спокойствию этих гор, птиц и деревьев.

Я чувствовала себя золотой рыбкой, чей аквариум только что разбился в дребезги. Аквариум, о существовании которого она даже не подозревала. Всего лишь глупой золотой рыбкой, которая теперь задыхалась. Трепыхалась и извивалась в предсмертных конвульсиях, с ужасом таращась на разбросанные вокруг осколки, что не так давно были для нее всей жизнью. Теперь же оказывается, что это рыбка была заложницей своего аквариума. Без него ей не удастся прожить и дня.

*А мне?*            	

Сигарета в моих пальцах давно потухла. Ветер подхватил скопившийся на ней пепел, и тот вскоре исчез в зимнем пейзаже. Хотелось бы мне последовать за ним.

Но вместо этого я в последний раз взглянула на разыгравшуюся передо мной красоту, стараясь сохранить в памяти каждую мелочь. Поднялась на ноги и вошла в дом.

Настало время собирать вещи.

У меня не было представлений о том, как быть дальше. Где мне жить? Куда податься? Чем заняться? С кем общаться? Найти себе новую работу, остаться на нынешней или послать все к чертям? Не было представлений о том, где взять силы на то, чтобы идти дальше, где бы это дальше ни находилось. 

*Как мне теперь доверять людям? Как подпускать их к себе?*

Как выяснилось, я совершенно не знала, чего хочу, не знала, почему Вениамин так со мной поступил, и конечно же, не понимала, как мне быть со всем этим.

Вопросы сыпались один за другим, но все они оставались без ответа. И лишь одно я знала наверняка. Тем утром внутри меня что-то сдохло. И я практически слышала эти тошнотворно-сладкие нотки разложения собственной души.

Знала, что больше никогда не буду той мечтательной девушкой, находившей время на закаты и рассветы. Она исчезла вместе с иллюзией счастливого брака, в которой жила. А вслед за ней ушли все мысли, мечты и надежды, но я знала еще кое-что.

Никогда прежде мне так не хотелось умереть.
