# 91 {-}

Мишель.

*Мишель. Мишель, ma belle.*

О ней я тоже вспоминала. О наших зимних посиделках, о выходных, которые мы традиционно проводили в ее старом доме. Просто валялись на чердаке, часами слушая старые записи, а потом бродили в посадках и около реки по первому снегу. Я вспомнила тот день, когда мы впервые по-настоящему подружились, а потом и нашу первую встречу.

*Привет, я Миша. Давай дружить.*

О ней я тоже рассказывала в одном из писем Марте.

Вспомнила я и о Матроскиной, подруге моего детства. Мы познакомились еще сидя в колясках и думали, что всегда будем друзьями. Вспомнила о Владиславе, которого знала так же давно и которого не видела уже больше года. Думала о школьных друзьях, о нескольких приятелях из института… Я даже вспомнила молчаливого мальчика, с которым подружилась в детском саду. Его звали Юрчик.

Помню, как год, проведенный в садике, подходил к концу. Наступало лето, и нас ждал финальный утренник. Там были танцы, какие-то костюмированные истории и прочая белиберда. Мы сидели под стенкой, наряженные и красивые. Все никак не могли дождаться того заветного момента, когда вся эта мишура закончится и можно будет со спокойной душой обожраться сладким.

Заиграла музыка. Дети вокруг нас принялись разбиваться по парам.

– Давай сюда, – сказал Юрчик.

Он протянул мне руку с таким видом, будто это действие было чем-то само собой разумеющимся. Словно мы уже лет сорок находились в законном браке. Музыка продолжала играть. Теперь ей вторил гул детских голосов. Я вложила свою детскую ручку в костлявую ладонь Юрчика.

Мы были друзьями, и тогда нам казалось, что эта дружба уже длится вечность. Что мы знакомы полжизни.

Мне исполнялось четыре. По сути, так оно и было.

*Ну и где же ты сейчас, друг?*

Как Юрчик поживает, где он и кем стал, я не знала. С тех пор прошло два десятилетия.

И вот я сижу на пустующей террасе с остывшим кофе, а ледяной дождь все продолжает моросить. Промокшая до нитки, я не чувствую холода. Вместо этого я ощущаю себя настоящей старухой. А ведь мне всего двадцать, мать его, три. Двадцать три года, а я уже чувствую себя слишком старой, чтобы жить.

Невозможно подсчитать, сколько имен, сколько воспоминаний пронеслось тем утром в моей голове. Ольге понадобилось бы с полсотни сеансов на то, чтобы все это выслушать. И раза в три больше для того, чтобы это прокомментировать. Разложить все по полочкам. Объяснить мне собственное сумасшествие.

– Ще кави? – спросила официантка.

Я покачала головой, и девушка поспешно укрылась от дождя.

Как выяснилось, я пробыла здесь гораздо дольше, чем думала. Часы показывали начало четвертого. Утро внезапно перешло в вечер. Должно быть, этот кофе выдался самым долгим в моей жизни, а я ведь даже не притронулась к чашке.

Наконец, я стала подниматься, сунув купюру под кофейную чашку.

На пороге показалась официантка. Она вновь несла мне плед.

– Можно прибрати зi столика?

Я кивнула.

Держа поднос тыльной стороной руки, официантка протянула свободную конечность к моему столику. Она подняла чашку прежде, чем успела заметить лежавшую под ней купюру. Ту моментально сдуло на пол.

Мои манеры внезапно дали о себе знать. Не отрываясь от нескончаемого потока мыслей, я наклонилась поднять деньги. Пальцы как раз коснулись промокшей купюры, и в этот момент из кармана моего пальто вывалился револьвер. Он с грохотом шлепнулся на землю, а затем грациозно проехал по мокрой поверхности с полметра, не меньше.

На крыльце кофейни повисла гробовая тишина.

Тогда я сделала медленный шаг в сторону оружия, лицензия на ношение которого истекла задолго до нашей встречи с Вениамином. Убедилась, что официантка стоит неподвижно, и подняла пистолет.

– Спасибо, – я извиняющимся взглядом смотрела на ошарашенную официантку, – но плед мне не понадобится.

В той кофейне меня больше не видели.

<div style="text-align: center;">***</div>

Пора нам вернуться к теме револьвера. Точнее, к тому факту, что я уже не первый день таскала его с собой. В том же кармане, где у меня лежали ручка и клочок бумаги. Я собиралась застрелиться, это очевидно. Кажется, чем-то похожим незадолго до смерти занимался Маяковский. Так что же мне мешало последовать его примеру?

Не то чтобы я ждала подходящего момента или какого-нибудь второго пришествия для своего самоубийства. Я была готова к нему уже много лет. Если опустить биполярное расстройство, сложно сказать, что конкретно повлияло на мое мировоззрение подобным образом – то ли Йен Кертис, то ли гадалка, однажды сказавшая, что я обрету свое счастье в этом возрасте, – но я всегда знала, что умру до тридцати. В какой-то момент – очень радостный и захватывающий миг моей жизни – я даже забыла об этом. Но вот я снова здесь, вот мы и подошли к тому, с чего все начиналось. 

Жалкая съемная квартирка, вечно работающий телевизор, создающий иллюзию чужого присутствия, полуфабрикаты на ужин, поедая которые думаешь исключительно о еде, бессонница и таблетки, которые все равно не могут ее предотвратить, полное отсутствие жизненно важных эмоций, алкоголь, о котором не помнишь, что там в бутылке, но инстинктивно все равно продолжаешь к ней прикладываться, отчаянье, сны, которые ярче жизни, замкнутость от всего мира и чье-то бледное лицо, постоянно маячащее в зеркале. И целое море воспоминаний, которые буквально душат тебя своими волнами.

Так почему пистолет по-прежнему продолжал лежать в моем кармане? Почему в нем все еще оставалась пуля? Ответ на этот вопрос кажется мне очень смешным: клочок бумажки, тот самый, что покоился рядом с пистолетом, был пуст. Я так и не смогла придумать, что хочу сказать миру напоследок. Все, что когда-либо происходило в моей жизни, теперь не имело ровным счетом никакого смысла. Я никак не могла определиться, стоило ли оно того?

Вот она я. Сижу и искренне пытаюсь понять, что я хочу сказать этому миру напоследок, но все больше начинаю подозревать, что ничего. Мир так достал меня, что я попросту отказываюсь с ним говорить. Есть такое прекрасное слово в немецком языке – Weltschmerz. Дословно это переводится как мировая скорбь, но сам термин скорей обозначает те чувства, что человек испытывает, когда напрочь разочаровывается в этом мире. Пускай веселья во мне всегда было столько же, сколько и депрессии, я все равно думаю, что не распространи Жан Поль понятие мировой скорби в далеком тысяча восемьсот десятом, это непременно сделала бы я. 

Уже в который раз я достала бумажку и ручку. На одной стороне листа я написала “Оно того стоило”, а на другой “Оно того не стоило” и еще несколько секунд просто вертела записку в руках. Дождь оставлял на ней мокрые пятна. Вскоре я уже не могла разобрать собственный почерк. 

*Что я хочу сказать этому миру напоследок?*

Я ослабила пальцы, позволяя несостоявшейся предсмертной записке улететь прочь. Тогда я поняла, что говорить с миром мне совершенно не хочется.
