# 92 {-}

Как и беда, хандра не приходит одна. Той пропитанной сыростью зимой не стало малышки Таи. Что бы я не делала, как бы не уставала и как бы не загружала себя работой, она постоянно мелькала у меня перед глазами. Как двадцать пятый кадр, на который я все время запрещала себе смотреть. И который все равно не могла не видеть. Я всеми силам запрещала себе думать о ней. Просто повторяла, что сейчас никак нельзя позволить себе заплакать, что у меня очень сложный и важный этап в жизни. Я заставляла себя жить так, словно все у меня в порядке. Словно не произошло ничего такого, что могло бы подкосить меня.

И, пожалуй, именно из-за этого я больше не могла испытывать подлинную радость. Мне казалось, что я больше никогда не смогу быть абсолютно счастливой. И чем больше времени проходило, тем лучше я понимала, что так оно и есть. 

– Что же я буду делать, когда ее не станет?

С тех пор прошло семнадцать лет, а я по-прежнему не знала ответа.

<div style="text-align: center;">***</div>

Одним серым февральским вечером я была в гостях у Марты. Моя подруга тогда еще жила в Беларуси. Каждые три месяца мы приезжали в родной город в одно и то же время, чтобы на пару недель отдохнуть от всего мира. Вот только на этот раз я приехала немного раньше назначенной даты и, что немаловажно, срок моего пребывания в Николаеве был весьма неопределенным.

Но вот прошел месяц, и я сидела в гостиной дома родителей моей подруги. Мама Марты как раз поставила передо мной чашку с чаем. Она была со мной слишком вежлива, и от этого делалось неловко. Создавалось впечатление, что из трех присутствующих в комнате людей, Марта и я не единственные, кто в курсе моего любовного фиаско.

*Тебе кажется*, сказала себе я.

– Марта рассказала мне, что у тебя произошло, – следом произнесла мать моей подруги.

Я выдохнула и откинулась на спинку кресла со словами:

– Это хорошо. 

– Почему?

– Теперь хотя бы можно не улыбаться.

И я улыбнулась.

Тогда-то мне и предложили погадать. Еще пару месяцев назад я бы вежливо отказалась от такой затеи, но сейчас мне было плевать на многие вещи, среди которых оказался и мой хронический скептицизм. Так что я ответила:

– Почему нет?

Матушка Марты была понимающей и очень гостеприимной женщиной. Она всегда имела в запасе парочку жизненных советов, обожала лепить вареники и с радостью угощала ими каждого, кто попадал на кухню. К тому же, мать моей подруги также была главой кафедры математических наук, что уже само по себе делало ее отнюдь не типичной гадалкой. 

Мы переместились в гостиную, где мама Марты уже раскладывала карты. Все, в общем-то, проходило стандартно. Я вытащила из колоды пиковую даму, которая, очевидно, символизировала меня. За ней потянулся ряд мелких карт той же масти. Их было так много, что в какой-то момент я просто сбилась со счета и стала сомневаться в том, что в колоде в принципе есть карты другого цвета. В конце концов, на столе появился белобрысый король.

– Ох, деточка, – протянула мама Марты. Она указала на последнюю карту: – Ты еще долго будешь ему верна.

Я всегда считала, что если что и может быть хуже ноября, то это определенно февраль – не просто самый грустный, самый безнадежный месяц в году. В феврале моя жизнь всегда была похожа на пейзаж за окном. Она была серой, тоскливой и до отчаянья одинокой. 

Что ж, я запретила себе думать о Вениамине Ларионове еще в тот самый момент, когда за мной в последний раз захлопнулась дверь нашего дома в Симферополе. Никаких надежд на счастливый конец, никаких мыслей о том, что Веня захочет вернуться, никаких попыток возобновить эти отношения. Он был типичным абьюзером в самом расцвете шизофрении, и я удивлялась тому, что раньше этого не замечала. Я не позволяла себе и мысли о нашем счастливом воссоединении. 

Но я не могла запретить себе любить его, так что просто грустила каждый миг этого проклятого февраля. 

<div style="text-align: center;">***</div>

Вернемся на десять часов назад. Этим утром мне нужно было проверить корпоративную почту, чего я не делала, наверное, с осени. Имея в запасе литровую чашку кофе, я открыла ноутбук и нажала на иконку ящика. Внутри оказалось двадцать три новых письма и все со странными названиями.

Отхлебнув кофе, я открыла последнее. На экране появился очень длинный, безграмотно написанный текст, а под ним – домашнее порно в исполнении одной тучной барышни.

*Странный скам нынче пошел*, подумала я, открывая следующее письмо.

Внутри оказались фото такого же содержания. Только они были от другой девушки. А затем еще от одной. Наконец, я присмотрелась к тексту, и это заставило меня взглянуть на имя ящика.

Тот оказался не моим. Очевидно, Веня был последним, кто пользовался почтой на моем компьютере.

Затем я нашла его переписку с той другой моей подругой. Ума не приложу, чего этой девице так дались мои мужики, но попытки охомутать Адама оказались детским лепетом в сравнении с тем, что я видела теперь.

Потому, что, в отличии от Адама, (с кем нас в дальнейшем связала дружба, гораздо более крепкая и плодотворная, чем несостоявшиеся отношения) Вениамин был вовсе не против, чтобы та другая моя подруга под него ложилась.

<div style="text-align: center;">***</div>

И вот я сижу в гостях у Марты, а ее мама с сочувствием во взгляде берет меня за руку и говорит:

– Ох, деточка, ты еще долго будешь ему верна. 

Как я уже сказала, мне было грустно всю зиму. Я просыпалась в четыре утра, читала труды давно умерших поэтов, а затем встречала поздние рассветы покрасневшими от слез глазами. При этом я часто просыпалась в слезах, а бывало даже, что и от собственного плача. И каждый раз мне было страшно засыпать.

Во снах я постоянно видела свою прежнюю жизнь. Все было настолько правдоподобно, что после пробуждения заново приходилось напоминать себе о том, что произошло. Мне было крайне паршиво, так что каждый мой вечер заканчивался в баре, а ночь начиналась с поимки такси. Я напивалась до такой степени, что порой забывала, что живу не в Крыму. Называла свой старый адрес, а потому никак не могла попасть домой. Такими ночами такси еще долго возило меня по опустевшему городу в поисках дома и улицы, которых здесь никогда не существовало. 

Лишь окончательно отчаявшись, я будила кого-нибудь из подруг.

– Привет, а где я живу? – вскоре эта фраза возглавила список вопросов, которые мои друзья меньше всего хотели услышать глубокой ночью.

Тамара Петровна уже успела перетасовать карты и сложить их обратно в секретер, но ее предсказание все еще звенело в моей голове.

*Ох, деточка, ты еще долго будешь ему верна. *

Не нужно быть гадалкой, чтобы это понять, но услышанное мне не понравилось. В основном потому, что оно оказалось правдой. Вопреки любым законам логики, во мне по-прежнему было слишком много любви. Мысль о том, чтобы прикоснуться к другому мужчине, казалась мне почти кощунственной.

– И что, это никак нельзя изменить? – растерянно спросила я.

– А как ты это изменишь? Ты же любишь его всей душой.

*Февраль. Уже поплакал, а что дальше?*

И в самом деле тяжелый месяц. Пережить его оказалось не так уж просто, но сейчас я впервые за долгое время почувствовала что-то кроме грусти. 

Этим последним вечером февраля, я, наконец, разозлилась.

– Нет, так не пойдет, – задумчиво произнесла я.

Мне практически не удавалось предаваться сну. Как много бы я не выпила, что-то неистово стонущее внутри – возможно, истерзанное сердечко – ежедневно заставляло меня подрываться в четыре утра. Я курила сигареты одну за другой, безразлично наблюдая, как во тьме за окном понемногу начинает вырисовываться до чертиков знакомый переулок. Могла сидеть так часами, одолеваемая душевной пустотой и обрывками стихотворений любимых классиков.

Очередное утро близилось к своему началу. Я ползу по коридору в сторону вытяжки, отдаленно напоминая себе женскую версию Грегора Замзы и слышу, как Маяковский скандирует:

*Время!*

*Хоть ты, хромой богомаз,*

*Лик намалюй мой*

*В божницу уродца века!*

*Я одинок, как последний глаз*

*У идущего к слепым человека!*

К тому моменту мне уже надоело объяснять себе, что именно со мной произошло, так что я написала шпаргалку и уложила ее на подоконник.

*Ты здесь потому, что Венька тебя покинул. Да, это правда. Нет, он не вернется. Вспомни Буковски и не пытайся. Это произошло после Нового года, и никто не знает, почему. Возможно, он тебя разлюбил, а, быть, может, и вовсе утратил способность чувствовать, но, если думать об этом слишком долго, ты никогда не выйдешь из лимба. Да, это правда насчет твоих подруг. Прошу тебя, не думай об этом. Тебе еще встречать рассвет, знаешь ли. Все эти мысли невыносимы, как и цикл повторяющихся действий, которые ты исполняешь здесь день за днем.* 

*Короче говоря, ты уже не в браке, это уже не ново. Найди в себе силы укрепиться в этой мысли и сразу же о ней забыть. К чему такие акценты? Даже в печали можно быть самой свободной. Выбирайся из этих стен. Ну, или хотя бы прислушайся к Иосифу Александровичу: давай уже, танцуй, поймав босанову. Пальто ты знаешь, где. Ботинки тоже. К чему все эти сопли, если их все равно придется вытереть и спрятать от мира? Ты же не хочешь, чтобы люди знали, что тебя все еще может зацепить уход другого человека, особенно, мужчины.*

*Доброе утро, и не спеши посылать меня. Поверь, для меня оно ничем не лучше.*

С момента нашего расставания прошло почти два месяца и, хоть я и запрещала себе думать о бывшем возлюбленном, в глубине я по-прежнему была верна этой любви. И я решила во что бы то ни стало, изменить это.

Наступила весна.
