# &nbsp; {#chapter-93}

Итак, я была достаточно умной, дабы понять, что заводить новые отношения так быстро – это не выход. И достаточно глупой для того, чтобы сворачиваться в клубок и предаваться истерике от спонтанно нахлынувших воспоминаний о моей несостоявшейся семейной жизни. Различные разговоры и события, однажды забытые ввиду неважности, теперь выныривали из недр памяти. Временами воспоминания казались мне куда реальней самой реальности. Какие-то шутки, обрывки диалогов, слова любви и элементы постельных сцен – все это было слишком ярким, слишком правдоподобным.

Это случалось ежедневно, на протяжении тех двух месяцев, что я была одна. Наконец, наступил день, вернее, ночь, когда я поняла, что так больше не может продолжаться. Глядя на разложенные передо мной гадальные карты Тамары Петровны, я пообещала себе избавиться от этой злосчастной верности.

Вот только я не имела ни малейшего понятия о том, как это сделать. И чем дольше я размышляла над этой проблемой, тем сильнее отдалялась от ее решения. Вместе с тем ощущение собственной слабости росло в геометрической прогрессии. Что бы я ни делала, мне не удавалось повлиять на собственную жизнь.

*Ох, деточка, ты еще долго будешь ему верна.*

Так я провела трое суток. Семьдесят два часа, лишенных сна, покоя и какого-либо смысла. Я знала, что теряю контроль над своей жизнью. Практически чувствовала, как все те ниточки, которыми я на протяжении многих лет выравнивала свою нервную систему, натягивались под гнетом очередного приступа депрессии.

Затем они стали рваться.

Отправной точкой стало отвлечение в письме. Я вдруг испугалась, что забуду Веню. На самом деле забуду. Хотя я прекрасно понимала, что боялась забыть не мужа, – да как тут его забудешь – а то чувство безмятежности и жизни, что я ощущала до наступления темных времен. Мне стало страшно утратить само воспоминание об этой эмоции. Словно последний лучик надежды вернуться в себя скрывался от моих глаз, и, подорвавшись очередным ранним утром я схватила блокнот. Покидать спальню показалось мне бессмысленным.

*Зачем выходить оттуда, куда вернешься вечером*

*Таким же, каким ты был, тем более – изувеченным?*

Соскользнув с кровати, я схватила блокнот, наточила карандаш и плюхнулась на пол. На этот раз писательский ступор обошел меня стороной. Я принялась судорожно записывать счастливые воспоминания минувшей весны. Хотелось занотировать как можно больше, пока боль любовной травмы не превратила чувство счастья в пыль – очередную иллюзию пытающего сердца, не больше.

Понятия не имею, сколько времени прошло, но дверь в комнату медленно отворилась. Она была прикрыта, не закрыта, так что меня это не смутило. Меня, в принципе, мало что могло смутить, на самом-то деле. Я ненадолго подвисла. Взглянула перед собой, пытаясь уловить мысль, а после тут же вернулась к заметкам.

*Ну, хоть нет проблем с писаниной*, пронеслось в голове.

Я подняла бровь и, не отрываясь от письма, бросила еще один взгляд в сторону двери. Ничего занимательного.

– И то верно, – безучастно заметила я. – Хоть с писаниной проблем нет.

 Последняя фраза вдруг вызвала у меня дежавю. То ли текст, то ли тембр севшего от слез голоса – все это показалось мне жутковато знакомым. Как будто я попала в собственный кошмар.

На пути в ванную комнату мне повстречалось зеркало. Я машинально взглянула в него, откинув с лица волосы, и тут же поняла, что к чему. 

– Так вот что это было, – произнесла я, разглядывая свое бледное личико.

Имевший место осенью случай внезапной деперсонализации показался мне забавным и таким понятным. Мне вспомнилась тогдашняя я. Сияющая несмотря на невзгоды и конфликты, а после сделалось бесконечно жаль, что я так и не смогла уберечь эту глупышку от очередного вихря депрессии.

Три дня и три ночи, показавшиеся мне вечностью, и никакого результата. Текст был, но морально не отпускало. Мне было отвратительно собственное существование, как и чувство жалости, что вызывало существо в зеркале. В итоге, мои силы исчерпались, и продолжать эту каторгу я уже не могла. Тогда я вернулась к самому первому и, по сути, единственному варианту, который у меня имелся. Старому доброму способу, к которому испокон веков прибегают мужчины и женщины, когда хотят забыть своих любимых.

Как показал опыт последних недель, избавить сердце от Вениамина гуманными не получалось. Я не сумела просто взять и забыть о нем так, как он забыл обо мне. Но я все еще могла последовать примеру миллионов брошенных возлюбленных и вытрахать из себя бывшего мужа.

Эрик – моя школьная любовь – был первым, о ком я подумала. Первым, кому удалось украсть мое сердечко. Прошло уже так много лет, а наши ночи, полные страсти и выпивки, все так же жили в глубинах моего подсознания. Прекрасный Эрик, играющий на фортепиано, живущий в своем мире, да танцующий посреди парка под музыку, которую слышал только он. Хотя нет, пару раз я тоже ее слышала.

<div style="text-align: center;">***</div>

Последние дни ноября две тысячи одиннадцатого года таяли как сало на солнце.

На улице вдруг резко похолодало и сделалось по-февральски неуютно. Обычно, в такие ночи снаружи можно встретить очень мало людей, да и те пытаюсь как можно скорей убраться восвояси. Несмотря на это ощущение, мне даже чем-то нравилась такая атмосфера. Обычно в ней таилось немало странных, веселых и даже жутких вещей, о которых потом вспоминаешь как о чем-то сокровенном. Как, скажем, о шабаше.

Фонари освещали девственно чистые аллеи центральной улицы. То тут, то там виднелись красочные ситилайты, что тянулись вдоль всей панорамы, создавая очаровательную зеркальную иллюзию. Мы приближались к небольшой часовне, за которой я впервые позволила себе лишнего, будучи ещё школьницей.

По забавнейшему стечению обстоятельств тем счастливчиком оказался Эрик. Было это полтора года назад.

И все же, чувствовалось так, словно произошло это как минимум парочку жизней назад.

Дойдя до поворота, Эрик начал двигаться в противоположном церквушке направлении. Я потянула его за руку, указывая головой в сторону места наших подростковых прелюбодеяний.

– Хочешь туда? - он улыбнулся.

Слегка пошло, и я подумала, что Эрик первый мужчина в моей жизни, в исполнении которого пошлые взгляды выходят такими милыми. Больше я таких не встречала. Благодаря этим взглядам я когда-то простила так много косяков.

Мои губы растянулись в ответной улыбке, и Эрик тут же поспешил добавить:

– Ой, да не гони, там холодно.

Мы свернули за часовню, позади которой был небольшой обрыв. Внизу его виднелась летняя забегаловка. Сейчас она была закрыта и пропала из поля зрения в темноте ночи.

Проходя вдоль парапета, я взглянула на то самое место, где мы когда-то зависали. Раньше там лежало огромное дерево, на которое можно было присесть и даже прилечь. Позже его срубили. Слишком низко, чтобы обустроиться на оставшейся части.

– Была бы здесь одна запрещенная скамейка... – начал Эрик. – Ох, так все еще она здесь!

Я присмотрелась. В паре метров от обрыва и впрямь стояла лавочка. С трех сторон ее окружали кустарники и ветви деревьев. Такой себе крохотный оазис посреди грязного города.

До декабря оставалась ровно неделя, – подумать только, я буду так гордиться собой, если смогу продержаться и не впасть в депру до конца текущего года – но в воздухе по-прежнему не пахло зимой.

Было на самом деле холодно. Я натянула пальто как можно ниже на задницу, и опустилась на скамейку. Эрик остался стоять. Он принялся копошиться во внутренностях своего рюкзака.

На протяжении всех тех лет, что мы были знакомы, я никак не могла понять, можно ли назвать Эрика красивым. В его чертах не было и признака слащавости как и признаков той шаблонной красоты, которую мы каждый день видим в журналах и рекламе, но бабы на Эрика так и липли. Он обладал невероятной харизмой и той исключено мужской красотой, что досталась Линчу, Буковски и, скажем, Дэвиду Духовны. Только черты лица были более утонченными и даже какими-то аристократичными.

Закинув ногу на ногу, я молча разглядывала сидевшего напротив молодого человека. Ему было девятнадцать, мне вот-вот обещало исполниться семнадцать.

Свет от церковных фонарей проникал сквозь листву, оставляя на лице Эрика причудливые тени. Над скамьей возвышалась немалых размеров береза, и теперь ее практически голые ветви свисали по всему периметру нашего импровизированного оазиса.

Эрик вынырнул из рюкзака, держа в руках бонг, что я подарила ему на день рождения. Незадолго до этого он также извлек переносную колонку, и теперь атмосферу дополняли ностальгические айдиэмные мотивы.

Парень протянул мне бонг, и я затянулась. Потом еще раз, ощутив на губах и языке лучший из всех мерзких привкусов, какие только можно встретить.

Пополнив запасы, Эрик проделал то же самое. Он медленно выдохнул дым, и тот плавно скользил, зависая в холодном воздухе. Позади мужского силуэта шумела темнота, а где-то на фоне виднелись огни моста и ведущей к нему набережной.

А может и не виднелись. Скорей всего, вид на огни закрывали деревья, и я просто знала, что они там были.

Музыка продолжала играть. Какие-то шуршащие неведомые мне вайбсы. Они вливались в обстановку с нежностью шелка. Я все молчала, и наслаждалась окутавшей нас атмосферой. Думаю, мы оба ею наслаждались.

Мне очень повезло с мужчиной.

<div style="text-align: center;">***</div>

Официально мы были вместе около двух месяцев. Неофициально – с конца прошлого июня. Я слышала об отношениях, в которых ежедневные распри – обычное дело, но никогда их не понимала. В моих предыдущих серьезных связях конфликты были редким явлением, но, как позже выяснилось, любовью в них и не пахло.

Затем я встретила Эрика. Снова. Мне было двадцать, ему – без малого двадцать три.

Бывало, мы ссорились по мелочам как настоящие сумасшедшие, и тут же мирились. Наши отношения походили на чаши переполненные чаши весов. С одной стороны, мы были взрослыми людьми, у которых было достаточно жизненного опыта для того, чтобы взвешивать все «за» и «против», принимая здравые решения.

(Ну, так нам, по крайней мере, казалось.)

С другой же, мы любили друг друга этой прелестной школьной любовью, которая вызывала так много амбиций. Порой, зависая на чьей-то вписке с Эриком, я чувствовала себя глупой школьницей. К тому же, по уши влюбленной. И не было моментов волшебней этих.

Знаете, временами женщине ну просто необходимо побыть дурой. Самодостаточность – это, конечно, хорошо, но все эти проблемы взрослых людей очень выматывают. Вообще трудно быть счастливым человеком, когда твой уровень интеллекта равен ста семидесяти. Сразу начинаешь видеть все недостатки этой жизни. Причем уровень твоего развития прямо пропорционален количеству проявляющегося вокруг дерьма.

Вот я и говорю, иногда женщине не помешает побыть дурой, поболтать о косметике, просадить хорошенькую сумму в суши-баре, разреветься из-за пустяка и все такое прочее. Так уж сложилось, что все оставшееся время женщины думают о своих возлюбленных. Ты, конечно, можешь быть феминисткой в десятом поколении, пахать на работе и осознавать, что твой внутренний мир не сводится на одном только мужике.

И все равно ты о нем думаешь. Помнишь, что нужно разогреть ужин, потому что сам он поленится и опять останется без горячего. Помнишь, что по пути домой, нужно зайти в аптеку, потому что мужики по им самим неизвестной причине отказываются пить таблетки даже при внушительных размеров температуре, а о том, чтобы купить их, вообще и речи быть не может. Как будто в этом действии есть что-то постыдное. Зато, в секс-шоп они всегда первые.

Так вот, получается, что побыть дурочкой – единственная возможность расслабиться. Некоторым это дано природой. Я им немного завидую. Что же касается мужчин… Что ж, они как раз наоборот – расслабляются все свое свободное время.

Эрик был музыкантом, но, почему-то, терпеть не мог, когда его так называют. Он был высоким и плечистым, а еще обладал самыми сексуальными в мире ногами и восхитительными глазами-хамелеонами. Мне нравилось прижиматься к нему по утрам, наблюдая за тем, как глаза меняют цвет от изумрудных до карих с проблесками золота. В такие моменты Эрик обычно запускал руки в мои волосы, которые уже отросли до самой задницы.

Мне все время хотелось подстричься.

– Ни за что не состригай их, – говорил Эрик, пропуская сквозь пальцы мои густые локоны.

Вид у него был прямо-таки счастливый.

<div style="text-align: center;">***</div>

Мы выкурили еще по одной сигарете и отправились домой к Эрику.

Обычно проводили время в моем родном гетто, но с приближением зимы все чаще ночевали у Эрика. Наверное, все дело было в том, что его квартира находилась в центре, а значит, в нее можно было оперативно вернуться, стоило нам замерзнуть.

На входе в спальню мой слегка накуренный взгляд задержался на эриковом рабочем месте. Последнее представляло собой огромный угловой стол и такое же огромное кресло, что стояли совершенно противоположно тому, как обычно стоят столы и кресла у нормальных людей. Мне это очень понравилось. К тому же, сама я уже и не помнила, когда в последний раз работала за столом. И это, будучи писателем. Его у меня попросту не было.

В левом углу комнаты находилось мягкое кресло. Спинкой к стене. Стол же обрамлял его, углом наружу, так что образовывалось небольшое замкнутое пространство. Повсюду висели полароидные снимки, – отрывки детства Эрика – но была среди них и парочка моих фотографий. Причем обе довольно старые. Одна – со школьного выпускного, вторая – с первого курса университета, на ней у меня еще были прямые рыжие волосы.

Около месяца назад мы поссорились. В который раз. Было это у меня дома.

– Я целыми днями работаю. Сижу в этих четырех стенах, от которых меня уже тошнит. Пишу сраные статьи, под которыми стоит чужое имя, и жду вечера, чтобы с тобой отдохнуть, – вскипела я после того как Эрик опять отказался выйти со мной в свет. – Ну, неужели это так сложно: просто куда-то сходить?

– Ну, почему ты не ценишь то, что мы вместе? Мне вот наплевать, будет это здесь, или в другом месте. Я просто рад тому, что мы снова встретились.

– Я тоже рада. И я скучала не меньше твоего, но я устала работать. Устала торчать здесь. Если все и правда так, как ты говоришь, то почему ты не можешь просто сходить со мной в кино? Мне просто хочется убраться отсюда.

– Придется подождать пока я не найду работу. За твои деньги я в кино не пойду.

Работу Эрик искал, как бы, сквозь пальцы, посвящая большую часть своей жизни музыке. Как художник художника, я его понимала, но как девушка...

Ирония была в том, что я совершенно не злилась на Эрика. Отсутствие у него работы меня напрягало лишь на пике депрессии, когда у самой не было сил работать. Зато меня крайне злил тот факт, что за мой счет он в кино идти не хотел, а любую работу со средним заработком сразу же отклонял. Я же привыкла бывать в кино каждую неделю, зависать вечерами в барах и пить кофе в каком-нибудь приятном глазу месте. В итоге выходило, что я не могу развеяться потому, что на абы какую работу Эрик не соглашается, так что денег нет, но и за мой счет он из гордости никуда не пойдет. Спрашивается: на кой черт я тогда днями просиживаю за работой?

Мне всегда думалось, что взрослые отношения подразумевают куда больше чем простое взаимопонимание. Это очень особая гармония как совмещение несовместимого. Временами приходится жертвовать собственной зоной комфорта на радость своей половинке. Я не просила Эрика днями просиживать в офисе, меня и саму тошнило от такого времяпрепровождения. В какой-то степени мне даже повезло с писательством, пускай оно и было коммерцией, которую заказчики выдавали за свое творчество.

И, вместе с тем, такая работа меня исписывала. Когда пишешь так много на собственные книги не то что времени, писалки не остается. Я все чаще и чаще начинала задумываться о том, а не стать ли кем-то еще. Учителем английского мне работать наскучило, айтишником тоже. Быть может, барменом? Буду наблюдать за людьми да развлекать их своей болтовней.

Увы, мой Отелло был против. И я оставалась призраком писателя, которому очень не хватало совместных неспешных прогулок и других радостей простых смертных. Я искренне недоумевала, почему парень не может сделать такой незначительный шаг в мою сторону.

Эрик был непреклонен. Он обладал поистине женской чертой, которой во мне никогда не было: умел делать меня виноватой, а потом говорить, что виноватым делаю его я. Так произошло и в этот раз. Тогда я закапризничала и на мгновенье усомнилась в чувствах Эрика.

– Думай что хочешь, – отрезал Эрик – но ты первая девушка, чьи фото я поместил на свое рабочее место.

В его голосе больше не было злости. Он звучал настолько тоскливо и одиноко, что мне сразу же стало стыдно за свое поведение. Я всхлипнула и прижалась к груди Эрика – мое любимое место во всей вселенной.

В кино мы тем вечером так и не пошли.
