# 94 {-}

За окнами назревала весна две тысячи семнадцатого,

*Ох, деточка, ты еще долго будешь ему верна.*

но я упорно ее не замечала. Калейдоскоп воспоминаний уносил меня все дальше и дальше, погружая в давно минувшие университетские дни.

Теперь я глядела на стол Эрика. На нем стояли колонки, монитор, две клавиатуры, включая миди-, окруженные всякими мелочами вроде миниатюрного скейтборда, а со стены мне улыбался собственный портрет.

Не скрою, я всегда предпочитала старый добрый пост-панк, рок-н-ролл, индии, гранж и классику. И, все же, творчество Эрика я любила почти так же сильно как самого Эрика. Было в нем что-то неуловимое, космическое. Как флешбеки из жизни, которую ты не помнишь, а, возможно, только собираешься прожить.

Переодевшись в безразмерную кофту своей второй половинки, я уселась в кресло.

– Из моего нового, – сказал Эрик. – Все это нужно редактировать. Я их еще никому не показывал.

Он надел на меня огромные наушники, и вскоре я погрузилась в музыку.

Здесь было очень уютно. Местами печально, местами смешно, но в большинстве своем спокойно и как-то эфирно. Слушала эти упоительные мотивы, я прикрыла глаза, ощущая пространство вокруг становилось все шире и шире. Подобное со мной обычно происходит во время медитации.

Стены спальни моего парня исчезли, а кровать, пианино, шкаф и прочие предметы слились в однотонную воронку, фоном окружающую нас. Несмотря на долгие часы, которые я проводила за чтением при плохом освещении, зрение мое было в порядке. И, все-таки, вокруг появились звезды. Музыка визуализировала их. Казалось, что в спальне не осталось ничего земного. Лишь стол да кресло, на котором мы сидели в обнимку.

– Музыка для нашмеканных, – любил говорить Эрик о своем творчестве.

Он говорил о планокурах, растаманах, травниках и так далее и тому подобное. И ошибался. В некоторых моментах мой возлюбленный был классическим примером творческой личности. Он то считал свою работу гениальной, то полнейшим дерьмом. Среднего почему-то никак не предусматривалось. Временами мне думалось, все могло бы сложиться куда лучше, найди он эту середину.

Спустя полчаса треклист закончился. Предметы вернулись по местам. Эрик встал, чтобы заварить нам чай. Помнится, он все еще стоял около кресла, о чем-то задумавшись, (вероятно, как всегда, раздумывал, а достаточно ли ярко выражен бас в его новом творении?) когда я повернула голову.

Этим мгновеньем парень выглядел особенно красиво. Говорят, женщины расцветают, когда их любят. Поверьте, с мужчинами происходит то же самое. Вероятно, Эрик поймал мой взгляд: он наклонился чтобы поцеловать меня. Поцелуй длился минуту, может, больше. Моя рука непроизвольно потянулась к низу живота Эрика. Затем скользнула ниже. Все еще сидя в кресле, я провела пальцами по линии его белья, после чего кончиками пальцев я принялась стягивать с него штаны. Затем белье, целуя и облизывая низ живота. Наконец, одежда перестала мешать, и я опустилась ниже. На самом деле трава никогда не действовала на меня как возбудитель.

Эрик – всегда.

<div style="text-align: center;">***</div>

Предаваясь воспоминанием, я вдруг вспомнила, как сильно любила Эрика. Он был единственным мужчиной, которого я всегда оказывалась готовой принять обратно. И даже не подозревала об этом. Внезапно осознала, что обожаю его безгранично как девочка, которая обнимает свою первую школьную любовь, и вместе с тем хочу всей душой и телом как женщина, в чьей жизни было слишком много дерьма, и она просто хочет покоя и стабильности.

Может быть, это и есть переломный возраст? Не так давно мне исполнилось двадцать три года, а значит, я должна либо убить себя, либо окончательно распрощаться с этой бессонной, вечно страдающей суициденткой? Февраль уже обратился весной. Совсем скоро он окажется летом, затем обратится осенью и, наконец, зимой. Наступит новый декабрь, и мне уже никогда не будет двадцать три.

Ведь именно в этом возрасте я обещала наложить на себя руки,

*У тебя просто аллергия на суицид.*

а теперь никак не могла понять, то ли у меня кишка тонка, то ли Вселенная, зачем-то меня бережет. А может, я и впрямь настолько сильна духом? И вдруг, не война, но битва закончилась. Я поняла, что последний вариант – правильный, и впервые по-настоящему собой загордилась.

Такое чувство бывает, когда долгое время работаешь над книгой. Размышляешь о ней перед сном, записываешь что-то в маршрутках, на унитазе и вообще, находясь в любой из ситуаций, в которых люди обычно листают новостную ленту социальных сетей. Сидишь за завтраком, нахмурив брови и размешиваешь сахар в чае левой рукой потому, что правой уже записываешь что-то на салфетке. Когда позволяешь себе курить в постели, без устали пьешь вино и карандашом натираешь мозоли на пальцах. А затем думаешь, что всю депрессию истратил на произведение, но все еще дописываешь его. После этого книга обычно перечитывается и наступает осознание того, что ты написал шедевр. В моменты как этот, я всегда чувствую целый вихрь эмоций. Моя жизнь остается прежней и проблемы не улетучиваются, но я внезапно понимаю, что написала что-то стоящее. Понимаю, что вся та боль, через которую мне пришлось пройти, оказалась не напрасной.

На протяжении жизнь с Веней я практически не касалась писательства. Что-то там писала, но это не длилось более недели. Да и за месяцы, минувшие с нашего разрыва, я ничего не заканчивала кроме сомнительных потусторонних стихотворений. Конечно, я соскучилась по этому чувству идеального завершения чего-то очень важного, и вот, вспоминая прошлое с Эриком, вдруг ощутила его в реальной жизни.

Вспомнила, как когда-то давно взяла Эрика за руку и прижалась к его плечу. Нос уже начинал мерзнуть от холода, пальцы сводило и постоянно куда-то поддувало. Мне захотелось сказать парню, как сильно он мне дорог. Мне было восемнадцать, ему - двадцать два. Обе мои стороны – и маниакальная и депрессивная – ценили каждое мгновение, проведенное с Эриком. Впервые за очень долгое время я чувствовала себя ласковой, любимой и, в конце концов, нормальной девушкой, а не той депрессивной нестабильной девочкой с огромными синяками под глазами и шрамами на руках. Может быть, это и есть любовь?

Черт его знает, но эта мысль вернула меня обратно к Вениамину.

*Ох, деточка, ты еще долго будешь ему верна.*

Неужели этого нельзя изменить? Будь так, народ бы вещался гораздо чаще обычного.

*А как ты это изменишь? Ты же любишь его всей душой.*

Нужно было как можно скорее вытрахать Веню из своего сердца.

Интуиция подсказывала мне, что стоит только захотеть, и Эрик вернется в мою жизнь, вот только…

Побродив по воспоминаниям своих школьных и студенческих лет, я осознала, что, вопреки многочисленным скандалам, наша связь с Эриком для обоих была сакральной. Я попросту не могла позволить себе опошлить это волшебство.

Так я и сидела у окна, наблюдая как за стеклом начинает светать. Снег прекратил, на улице не было и шороха, и только серый дым без устали сочился с крыш окружающих меня домов.
