# 95 {-}

С блядством у меня не сложилось. Как, в общем-то, и всегда.

Но пришла весна семнадцатого, и я старательно собирала остатки, чтобы вновь отыскать смысл жизни. За этим я кинулась к единственному верному другу, что, подобно музыке, оставался со мной и в горе и в радости – к морю. Лишь несколько часов пути по разбитым дорогам, и мы вновь были вместе.

Укрывшись широким капюшоном своего старого пальтишка, я бесцельно бродила закоулками Одессы, раздумывая о том, а какой он, собственно, может быть, этот мой смысл жизни?

На подобного рода размышления ушел целый день, но к вечеру я и мое эго сошлись лишь в одном: мой гипотетический смысл жизни не должен быть связан с другими людьми.

Так вот, в самый разгар этих дум мне встретился Николай.

Он оказался удивительным мужчиной. Никогда прежде я не встречала человека, которому бы так разительно не подходило собственное имя. Высокий и плечистый, с копной рыжих волос и веснушками, игриво разбросанными матушкой-природой на светлой коже. Он вполне мог сойти за какого-нибудь Абрахама, Рэналфа, или, на худой конец, Далласа.

Короче говоря, Николай было последним словом, которое могло придти в голову при виде этого мужчины. Густая борода, пылкий нрав и практически полное отсутствие моральных ценностей лишь подливали масла в огонь.

У нас довольно быстро завязались приятельские отношения.

– А я сегодня бабу отморозил, – с гордостью заявил Коля.

Нужно сказать, этим он часто промышлял. Круг его общения в подавляющем большинстве занимали барышни. Вполне себе привлекательные девушки, среди которых едва ли нашлось бы и с полдюжины тех, с кем у Коли ничего не было. Но, если же он с ними еще не спал, то непременно собирался это сделать.

– Фригидной что ли оказалась?

– Нет, с ней можно было бы перепихнуться, но она меня раздражает.

– Чем это?

– Своим мышлением.

– И что с ним не так?

– Сидит два месяца без работы и постоянно об этом ноет. Отказывается идти официанткой. Типа, не хочет работать обслуживающим персоналом. Но на этой неделе она пошла работать в камвхоринг!

Вот уж никак не думала, что в этом мире еще остались мужики, способные отказаться от легкодоступных баб ввиду каких бы то ни было принципов. Почему-то эта новость меня чуток воодушевила.

И я рассмеялась.

Хотя, с другой стороны, в изложенных мужчинами историях зачастую присутствует довольно видоизмененная правда. В основном, они говорят, чтобы говорить и скорей волнуются о том, как бы выставить себя мужественней, чем о сути сказанного как таковой. Случается, мужчины говорят просто для того, чтобы говорить. Нет никакого смысла воспринимать их серьезно.

Мой собеседник перевел дыхание и с чувством добавил:

– Где здесь вообще логика?!

– Могу найти.

– Где?

– Все тот же обслуживающий персонал, только платят больше.

– Хоть ты тресни, Васляева, не понимаю я такой херни! Как можно быть такой тупой?

Теперь его голос звучал почти обиженно.

«Должно быть, не дала…» – не без иронии подумала я.

– Так ты ведь сам постоянно выбираешь таких девиц, а потом жалуешься, какие они тупые. Никак не пойму, ты совсем что ли в людях не разбираешься? Мне вот и одного взгляда достаточно, чтобы понять, насколько это тупой человек.

– Ну, об этой я всегда знал, что она тупая. Но меня внешность интересует в первую очередь. Не мозги же трахать, уж прости.

– И что эта девушка, красивая?

– Фигура у нее отпадная. Все как я люблю. Самое то для перепихона.

– Так и что ж ты ее отморозил? – я подняла бровь и пристально взглянула на Николая. – Уже давно мог бы трахнуть, раз там все как ты любишь.

Какое-то время он молчал, очевидно, раздумывая над ответом. Затем повторил:

– Бесит это ее мышление.

– Так ведь сам говоришь, что тебе внешность нужна в первую очередь. Тогда в чем проблема?

Повисла еще одна пауза, в ходе которой Николай выглядел так, словно и сам никак не мог понять, в чем была проблема.

– Не хочу, – наконец, ответил он.

– А мне вот показалось, что очень даже хочешь…

– Нет. Когда баба вот так выставляет сиськи и жопу на показ - это слишком мерзко, – заявил самый продуктивный из всех знакомых мне бабников.

Я не могла не заржать.

Как я уже сказала, в основном, Коля предпочитал женскую компанию, и та отвечала ему взаимностью. Не то чтобы он обладал блистательной красотой или голливудской улыбкой, но ведь мужчинам они вовсе не нужны. Вместо этого Николай получил кое-что получше: чрезмерную самоуверенность, чертовски соблазнительный взгляд, не по-славянски обаятельную харизму, вспыльчивый характер и закоренелый гедонизм с нескрываемыми нотками классического мужского мудизма. Такие вещи работают куда лучше какой-то там призрачной красоты. Они притягивают женщин как магнит, мне ли не знать?

– Нет, такую я точно не хочу, – подытожил Коля. – Лучше уж проститутку снять.

Мужчины, повествующие о желании снять проститутку – еще один занимательный типаж. Обычно они все время возвращаются к этому вопросу в диалоге, но так никого и не снимают. То ли их привлекает возможность кого-то купить, то ли они спрашивают моего одобрения – никогда не ясно наверняка, но всегда довольно забавно наблюдать, как оппонент сам себе кажется от этого круче.

– Прекрасно тебя понимаю.

Он встретил эту фразу с заметным недоверием.

– Да ладно тебе!

– Ну, да. Среди моих знакомых очень много привлекательных мужчин. И очень мало умных мужчин. Именно поэтому число моих партнеров еще не скоро станет двузначным.

Николай ухмыльнулся, и мы, наконец, сменили тему.

Тем не менее, это был не первый и далеко не последний случай, когда Коля рассказывал мне о своих постельных похождениях, прошлых или будущих. Об удачных или неудачных попытках затащить очередную девушку в постель, а также о том, как кто-нибудь из них пытался сделать то же самое. Не скажу, что хоть что-нибудь в этих историях могло меня удивить. Порой они бывали смешными, а иногда надоедали настолько, что меня начинало мутить от одной мысли о Коле и его непрестанно расширяющемся гареме, но было здесь еще кое-что.

Кто бы мог подумать, но этот рыжеволосый бабник оказался самым честным мужчиной среди всех, кого я знала, и даже среди тех, кого мне еще предстояло узнать. Он никогда ничего не скрывал. Не боялся говорить правду, даже если та выставляла его далеко не в лучшем свете. Николай оставался прямолинейным в любой ситуации, и, хотя эта его черта частенько граничила с грубостью, о существовании которой сам Коля и не подозревал, я почти никогда на него не злилась. В этом мире слишком много лживых людей, куда больше, чем можно подумать. Жизнь вынудила меня замечать их с первого взгляда, и к своим двадцати трем годам я мало что ценила так, как честность.
