# &nbsp; {#chapter-96}

– Сделаешь мне кофе? – спросила я, вернувшись после душа.

Похоже, все моего отсутствия Николай оставался статичен. Он все так же полулежал на диване, закинув ноги на журнальный столик. На нем был лишь махровый халат, и тот нараспашку, да мечтательная улыбка, неизвестно к кому обращенная.

– Ой, ну, сделай сама, – ответил Коля. – Кофе в шкафу на кухне, ты найдешь.

После чего еще глубже втиснулся спиной в подушки.

*Ну, блядь, идеал, а не мужчина.*

Он взял в руки ноутбук, на экране которого тут же появился игровой интерфейс. Затем громко вздохнул, уставился в компьютер, и со словами «Что-то я устал…» на некоторое время из моей жизни.

У этого человека не было особых целей, стремлений или планов на будущее, а если что и имелось, Николай это мастерски скрывал. Один за другим, он проживал дни, занимаясь тем, чего душа пожелает, и совершенно этого не стыдился. В общем и целом, рутина Николая была насквозь пропитана гедонизмом, а временами и самым настоящим утилитаризмом. В отличие от меня, он не ставил перед собой заоблачных задач, а потому не бывал несчастен из-за их недостижимости.

Как и следовало ожидать, в обществе поведение сродни этому вызывало неприязнь и сильное раздражение, а я вот не видела в гедонизме ничего предосудительного. Чем плохо жить в свое удовольствие, если это не мешает другим? Как по мне, такая жизнь - это то, о чем, рано или поздно, мечтают все выходцы из рабочего класса, и именно то, в чем они так сильно боятся себе признаться. Оттого и сердятся. Иначе какое, в принципе, дело, что там у кого да как?

– Нашла? – донеслось из гостиной.

Я ответила, что нет, и Коля предложил мне поискать получше.

– Ты просто идеал! – крикнула я, не в силах перестать смеяться.

Очаровательный блядун и откровенный лентяй, который любил свой байк не меньше, чем общество красивых женщин. Безмятежность этого шалопая могла сравниться, разве что, с той страстью, что он проявлял в постели. Но и за ее пределами, Коля каким-то волшебным образом умудрялся оставаться мужественным. ничего при этом не делая. От него буквально пахло мужчиной даже в самых нелепых и комичных ситуациях.

Бабник, разгильдяй, мудак и отличный любовник - в такого не мудрено втрескаться. Думаю, я бы вполне могла влюбиться, не будь я так увлечена собственной депрессией, не будь мое сердце разбито и все такое прочее. Однако, несмотря на гложущее меня одиночество, любовь была последним, чего мне хотелось наступившей весной. Нормального сна я не видела с того самого дня, как в последний раз пересекла Крымскую границу. Просто не могла уснуть в пустой постели. Но это вовсе не значило, что я хочу обзавестись отношениями. С каждым любовным фиаско, мне становилось все страшнее и страшнее отдавать свое сердце другому человеку. К тому же, даже если бы я вдруг сошла с ума и решила влюбиться…

Из этого вряд ли могло что-нибудь выйти. Не из-за страха столкнуться с новой болью: она меркнет и бледнеет, как только ты вновь находишь себя по уши влюбленным. Ты можешь изнывать от этой боли годами, а потом в один момент напрочь о ней забыть, как матери, решившие завести второго ребенка, забывают о невыносимых муках, которые испытывали во время родов.

Нет, дело определенно было не в страхе перед новыми отношениями и не в боли, оставленной бывшими возлюбленными. Я просто чувствовала, что и при всем желании не смогла бы сейчас влюбиться. Конечно, всегда можно сослаться на хроническую мизантропию, но…

*Ох, деточка, ты еще долго будешь ему верна.*

Вот только слова матери моей лучшей подруги по-прежнему не давали мне покоя. «Ты еще долго будешь ему верна» – все это было чистейшей правдой, и оттого так сильно меня бесило.

Какой бы стойкой я не была, как настойчиво не запрещала себе думать о Вениамине, он по-прежнему оставался где-то там, на задворках моей изъезженной души. Изгнать его так просто не удалось бы и самому бывалому экзорцисту Ватикана.

Конечно, я всячески старалась избегать этой темы, но это едва ли что-то меняло. Веня без труда стал моим бывшим, а чувства к нему до сих пор были настоящими. Убедить общество в обратном оказалось не сложно, но я не могла обмануть себя. По крайней мере без помощи деменции.

*Ох, деточка, ты еще долго будешь ему верна.*

Каждый раз при этих мыслях меня охватывала самая настоящая ярость. Правда, с нотками детской истерии. Хотелось упасть на пол и с ором топать ножками до потери сознания.

А что если я этого не хочу? Что если я не хочу быть ему верной?

Казалось бы, глупое, но до чего же живучее чувство эта ваша любовь! Черт бы ее побрал вместе с верностью и прочими атрибутами! Вопреки всем стараниям, – среди которых было что-угодно, от Буддизма, йоги и медитаций до регулярных сеансов психотерапии с медикаментозным лечением – мне никак не удавалось искоренить это бесполезное чувство. Я не просила Вселенную вернуть мне Вениамина так же, как не ждала появления нового возлюбленного в своей жизни. Только бы ничего не чувствовать – единственное, о чем я просила на протяжении того пугающе долгого февраля.

Так было до последнего вечера зимы, что я провела в родительском доме Марты. До того, как восемь простых слов, участливо произнесенных глубоким голосом ее матушки окутали мою грусть, превратив ее в гнев.

*Ох, деточка, ты еще долго будешь ему верна*, сказала Тамара Петровна, но это не имело никакого смысла!

Я не могла быть с тем, кто намертво прирос к моему сердцу. С другими мужчинами я тоже не могла быть. Для них в моей душе попросту не нашлось бы места. Проблема была в том, что сложившаяся ситуация влияла не только на мою личную жизнь и ее отсутствие. Она затрагивала практически все аспекты моего существования, превращая его в кошмар наяву.

*Если останешься, я превращу твою жизнь в ад*, пообещал мне Вениамин последним из вечеров, которые мы провели под одной крышей.

Что ж, дорогой мой, я уехала. Вот только ад остался.

<div style="text-align: center;">***</div>

Той деточка-ты-еще-долго-будешь-ему-верна ночью я вышла из родительского дома подруги окончательно разбитой. Время давно перевалило за полночь, но, вернувшись домой, я так и не смогла уснуть. Моя печаль вернулась. Теперь она была даже сильнее, но внезапно охватившая меня злость не отступала. Охваченная этими противоречивыми чувствами, я тупо лежала на кровати, а голоса людей из прошлого хаотично всплывали в моих мыслях. Сердце болело и билось так сильно, словно за ним гнались из самой преисподней, отчего дышать стало трудно. По традиции, не обошлось без мигрени и тремора в конечностях. Добавьте к этому непрекращающуюся бессонницу, и эффективный способ сойти с ума готов.

По этой простой причине, Николайи засветился в мрачной рутине моих будней.

С этими мыслями о той ужасной ночи я побрела обратно в комнату.

– Нашла? – машинально спросил Коля, стоило мне появиться на пороге.

Он был целиком и полностью поглощен увлекательным миром цифровых технологий.

– Ага.

– А что так долго?

На кухне я провела по меньшей мере двадцать минут, что превратило приготовление этой чашки кофе в рекордно долгий процесс.

– Сахар никак не могла найти.

– В шкафчике на кухне смотрела? – и глазом не моргнув произнес Николай.

Несколько секунд я в недоумении смотрела то на него, то на кофе, и все никак не могла понять, был ли этот вопрос шуткой.

В итоге решила, что нет.

– Пойду еще раз посмотрю, – ответила я.

– Давай.

Само собой, никакого сахара на кухне я не нашла. Думаю, я бы сумела обнаружить его еще в один из тех тридцати раз, когда заглядывала в этот проклятый шкаф.

– Да нет там никакого сахара, – сказала я с куда большим раздражением в голосе, чем собиралась.

Как ни крути, а безкофеиновая ломка давала о себе знать. С двенадцати лет я регулярно начинала, продолжала и заканчивала дни с напитком бодрости. Как и у всех, мои вкусы трансформировались по мере взросления, но кое-что оставалось неизменным. Я не могла притронуться к кофе, в котором нет одной-двух ложек сахара.

– В шкафу точно нет?

– Нет. Где еще посмотреть?

И я услышала то, что боялась услышать.

– Хм… Если в шкафу нет, значит сахар закончился.

*Твою ж мать*, обреченно подумала я и зачем-то повторила эту выдающуюся мысль вслух.

– Твою ж мать.

Я отхлебнула кофе, и поняла, что теперь эта чашка была не только самой долгой, но и самой отвратительной чашкой кофе в моей жизни.

Еще и муж бросил.

– Господи, мерзость-то какая! Как вообще можно не знать, что у тебя закончился сахар?

Впечатленный этими страданиями молодого Вертера, Николай даже ненадолго оторвался от монитора.

– Ну, я как-то не особо за таким слежу, – ответил он.

Затем развел руки и пожал плечами.

Совсем не так, как Веня. Мне это понравилось. С некоторых пор я, в принципе, стала симпатизировать людям, в которых не планировала влюбиться.

Дело было в Одессе. Мы познакомились в оживленной толпе, когда Николай возвращался с неудавшегося свидания, а я задумчиво бродила по покрытым остатками снега переулкам старого города в поисках смысла жизни. Изначально я приехала к морю: его отсутствие убивало, особенно в моменты душевных падений.

Мы переспали почти сразу же после знакомства, но это ничего не изменило. Затем переспали еще раз пять, чтоб наверняка, и я, наконец, сдалась. Пришлось признать, что верность едва ли связана с плотскими утехами, да и последние, раз уж на то пошло, довольно быстро перестали меня радовать.

Первый секс с Колей меня немного отвлек, а остальные разы протекали как-то механически. Мыслями я витала далеко за пределами чужой постели. Думаю, Николай чувствовал то же самое, ведь я практически сразу разглядела в нем разбитое сердце. Правда, он тогда в этом ни разу не признался. Наверное, не хотел разрушать годами выстроенный образ альфа-самца.

Последняя попытка вытрахать бывшего мужа достигла своего логического завершения. Стоя на колином балконе в чем мать родила и без особого интереса глядя на раскинувшиеся внизу одесские дворики, я продолжала слышать голос Тамары Петровны.

*Ох, деточка, ты…*

– Деточка-хуеточка! Ненавижу это слово! – раздраженно бросила я.

– Не понял, – раздалось из гостиной.

Коля просунул голову в дверной проем и удивленно взглянул в мою сторону.

– С кем ты разговариваешь?

– С самым умным человеком на свете, – ответила я, и вернулась к сигарете.

Мне пришлось переступить через целый ряд собственных моральных принципов, и это не принесло результата. Сказать больше, я чувствовала себя так, словно только усугубила ситуацию.

А в голове на репите крутилась все та же фраза про деточку, подгоняемая смехом бывшего мужа.
