# &nbsp; {#chapter-97}

– Ты куда? – спросил Коля.

Общества Коли – цезуры ради, назовем это так – утомило меня спустя трое суток,

Он едва протер глаза и застал меня в коридоре, натягивающей на ноги ботинки.

В доме одесского бабника я провела почти трое суток. Наступившим утром пришлось признать: если даже это не помогло выбросить из сердца Вениамина, значит, я определенно где-то не там ищу.

– На поиски смысла жизни, – ответила я.

Улыбнулась и скрылась за дверью.

– Лиза, постой!

Коля догнал меня на лестничной клетке. Все в том же неизменном халате.

– Я тебя обидел? – участливо спросил мужчина.

– Вовсе нет.

– Тогда почему ты уходишь?

– А зачем мне оставаться?

– Ну, не знаю. Мы могли бы заказать пиццу. Посмотреть какой-нибудь фильм с Патриком Уилсоном. Тебе же нравится Патрик Уилсон, да?

– Да.

– Тогда оставайся.

Оторвавшись от грязи собственных ботинок, я взглянула на Николая, и вдруг ясно увидела в нем кем-то покинутого мальчика. Стало ясно, что в душе этот страстный альфа альф по-прежнему оставался ранимым мальчишкой. Подобно мне, он просто боялся быть брошенным.

– Нет, Коль, мне нужно идти. Мужчины сейчас последнее, что мне нужно, понимаешь?

Он кивнул.

– Опять весь день будешь шататься по незнакомым улицам?

– Возможно.

– Ты точно не обиделась.

– Да точно-точно.

Коля немного выждал, раздумывая над правдивостью моих слов.

– Удивительная ты женщина, Васляева, – констатировал он. – Ебанутая, конечно, на всю голову, но удивительная. Такую и маме показать не стыдно.

– Приятно, что ты оценил.

Я чмокнула Колю в щеку.

– Что ж, звони если понадобится повторная оценка.

Николай игриво поднял бровь, и я рассмеялась.

Так и попрощались.

<div style="text-align: center;">***</div>

Я продолжила одинокие прогулки по Одессе. Прошлась у моря и заглянул в эзотерическую лавку.

– Ищите что-нибудь конкретное? – поинтересовался продавец.

– И да и нет, – отвечаю.

Парень заинтересованно поднял брови.

– Это как? Что бы вы не искали, у нас это непременно найдется. Есть камни, кристаллы, свечи, обереги… Что именно вас интересует?

– Смысл жизни.

На этой ноте консультант слегка подвис. 

Мне стало до неприличия смешно и, сделав лицо, как модно серьезней я еще какое-то время посмотрела на вышеупомянутые кристаллы, а затем скрылась с поля зрения продавца.

Ночи все еще были холодны, но спать мне совершенно не хотелось. Ехать обратно – тоже, так что я всю ночь бродила вдоль береговой линии, разглядывая звезды и старясь отпустить шальные мысли. К рассвету я не выдержала и таки окунулась. Надеялась, что от холода сведет ногу или я потеряю сознание и Черное море унесет меня куда-то к берегам Турции… 

Какой там, я проплыла с добрых сто метров и, зависла на поверхности воды в ожидании смерти, которая так меня и не настигла вопреки времени года, алкоголю и прочим вспомогательным обстоятельствам. В итоге, пришлось нехотя выбраться обратно на берег.

Мое пальто ждало на песке. Я укуталась им сложно в полотенце и в задумчивости уставилась на поднимающееся над водой солнце. Как же чертовски мне не хватало себя самой тем морозным мартовским утром…

<div style="text-align: center;">***</div>

Еще один мартовский день проведенный на улицах, имен которых я не знала, близился к вечеру. Помнится, море тогда выглядело особенно встревоженным. А может, встревоженной выглядела я, а море, всего лишь отражала это качество, пока я бродила по укрытому остатками снега песку?

Смысл жизни я так и не нашла. Зато нашла круглосуточный ресторанчик, где подавали мое любимое десертное винишко. Вокруг сновали парочки всех возможных возрастов, окрыленные весной и собственной любовью, а из колонок доносились сладкие тексты Элвиса:

*It’s now or never*

*Come hold me tight*

Во всем ресторане я была единственным человеком, сидящим за одиночным столиком. Посетители то и дело стреляли в меня сочувствующими взглядами. Казалось, я должна была чувствовать себя лишней на этом празднике любви. Но я, почему-то, не чувствовала.

Между кофейной чашкой и бокалом вина лежал видавший виды блокнот, и я сосредоточенно записывала в него обрывки воспоминаний.

*Как в старые добрые*, подумалось мне.

Как в старые добрые.
