# &nbsp; {#chapter-98}

– Пройдите к другим пассажирам, – произнес водитель. – Дежурный автобус подберет вас через пятнадцать минут. Максимум час.

Следующим днем я отправилась домой. По традиции, автобус встал на половине пути, и теперь наотрез отказывался ехать дальше. Было это где-то недалеко от Очакова, в районе некого Шурино, и пассажиры уже вовсю ругались, не в силах поделить еще недавно пустующую на обочине скамейку. Из было за двадцать, а скамейка всего одна.

Вениамин настойчиво пробирался мне в голову, – все наши поездки, путешествия и сломанные автобусы вновь и вновь выныривали из памяти – но я с не меньшей настойчивостью гнала его что было сил.

На месте мне не сиделось, и я принялась хаотично шагать бродить трассы, когда внезапно поняла, что больше не хочу садиться в автобус.

Тогда я запахнула полы пальто и, перекинув через плечо ремень дорожной сумки, зашагала по дороге. Прочь от кричащих и светящихся людей.

– Куда это вы? – крикнул мне вслед водитель. – Не заходите далеко! Автобус приедет совсем скоро! Некогда мне вас по полям ловить!

– Дальше я пешком.

Суета, вызванная скамейкой, притихла. В очередной раз я невольно завладела внимание незнакомой группы людей.

– Каким пешком? До Николаева больше часа езды!

Но я только отмахнулась.

Водитель покрутил у виска и вернулся в кабину, а я как ни в чем не бывало продолжила шагать по трассе.

Теперь я знала, куда бежал Форрест.

<div style="text-align: center;">***</div>

Прошло около четырех часов прежде, чем я позволила себе остановиться. Дежурный автобус давным-давно обогнал меня, но торчащие из него любопытные лица лишь подстегнули меня идти дальше.

Машины в такую погоду встречались редко. Только у дорог, ведущих к неизвестным мне деревушкам, но автомобили меня не смущали: они исчезали так же быстро как появлялись. В основном меня окружали голые ветви, какие-то холмы, да покрытые инеем поля, которым не было конца и края.

Близился вечер. По предварительным расчетам мне оставалось идти еще часа полтора-два. Не так уж много, если учесть, что я всю жизнь бежала от собственных проблем.

Наконец, я поняла, что больше не хочу бежать. Притормозила и, спустившись в овраг, что неизменно тянулся вдоль обочины, направилась видневшемся вдали холмам.

Последние оказался куда дальше, чем мне казалось. Я все шла и шла вдоль поля, мысленно перечисляя вещи и людей, которые когда-то были для меня если не смыслом жизни, то неотъемлемой его частью.

*Больше их нет*, напомнил внутренний голос.

Как будто я хоть на мгновение могла об этом забыть?

– Но что же осталось? – дрожащим голосом спросила.

*Небо*, подумала я, с нежностью глядя на расцветающий над холмами закат.

*Небо осталось. И солнце, и звёзды. И закаты, да!*

Огромное количество закатов и рассветов, что расстилались над реками, горами, лесами, долинами, озерными краями и бессчетным количеством городов, в которых я никогда не была.

А ещё у меня по-прежнему были книги. Миллионы несказанных слов, сотни тысяч ненаписанных строк и уйма невыраженных мыслей, о которых толком никогда не знаешь, которая из них окажется стоящей.

Все это когда-то уже было моим. Оно по-прежнему мое, стоит только протянуть руку.

Яркие полосы весеннего солнца заполняли ещё совсем недавно хмурое небо. Я машинально отбросила с лица надоедливую прядь, и, расправив плечи, глубоко вдохнула вечерний воздух.

Сложно было признать, но с уходом Вениамина небо надо мной оставалось все таким же бескрайним, море – манящим, а закаты и вовсе не думали терять своей красоты. Едва ли замечая подкрадывающийся холод, я с любовью во взгляде наблюдала за тем, как солнечный диск скрывается за воображаемой линией, дабы завтра вновь осветить наступивший день.

Я вновь наполнила лёгкие весенним воздухом и с едва уловимым удивлением в голосе сказала в никуда:

– А ведь я все еще дышу, Веня. Дышу сквозь те осколки, которые ты оставил в моей душе.

Как это возможно? Я не знала.

Единственное, о чем я могла сказать наверняка – и во многом благодаря достигшему меня в дороге закату – так это то, что я больше никогда не хочу видеть Вениамина. Конечно, я все так же любила его (о чем мало кто знал, благодаря моему веселому нраву и, видимо, неплохому актерскому таланту) и лишь одно воспоминание о тех ужасных январских событиях заставляло мое сердце сжиматься с болезненной силой. Но было во мне кое-что куда сильнее и осмысленнее любви к этому человеку. И этим кое-чем оказались не столько гордость и самолюбие, сколько четкое осознание того, что ни с кем не должно происходить то, что произошло со мной.

Да, я по-прежнему любила Вениамина и именно поэтому дала себе слово никогда не вспоминать о нем. Так что, вопреки всяческим душевным терзаниям, я знала, что больше не захочу встретить взгляд его переменчивых глаз.

Размышляя об этом, я в последний раз взглянула за прячущееся за небосводом солнце. Переливаясь под поздними золотыми лучами, покрытые инеем деревья по-прежнему хранили на себе тепло уходящего солнца.

Нет, ни один алкоголик не в силах отнять у меня эти закаты. И эти рассветы. Земля не остановилась после того как Вениамин Ларионов разбил мое сердце, а солнце не застыло на небе.

Мир продолжал двигаться и мне приходилось двигаться вместе с ним.
