# 99 {-}

Еще в январе, во время одного из наших первых сеансов Оксана рассказала мне о своем так называемом месте силы – выкопанном из-под земли киммерийском лабиринте, заложенном еще за тринадцать веков до нашей эры.

С ее слов, лабиринт находился практически в центре Николаева, совсем близко к тому месту, где мы когда-то зависали с Эриком. Я проходила там сотни раз, почему-то, о никогда о нем не слышала, о чем и сказала доктору.

– Елизавета, ваше подсознание знает гораздо больше, чем вам кажется, – заметила психотерапевт, когда я сказала, что уже не раз проходила мимо ее места силы.

– Мне бы с Высшим Я побеседовать…

Доктор никак не отреагировала на эту реплику и продолжила рассказывать мне о месте силы.

– Было время, когда это место служило своеобразной столицей территории от Дуная до Днепра и от Черного моря до севера сегодняшнего Николаева и примыкающих к нему областей. Тогда там стоял настоящий городище солнцепоклонников. Как у вас с историей, нормально? Тогда вы уже должны были понять, что это был не просто киммерийский город. Это был самый настоящий портовый городище, который служил ключевой точкой на пересечении всех торговых путей. Вы же знаете, что в те времена торговля осуществлялась через воды? Ну, конечно, знаете! Простите, ко мне приходит слишком много тупых пациентов.

Оксана сделала глоток воды и продолжила:

– Самое занимательное в этом городище не сам порт, а его конструкции.

– А что с ними? – я задала этот вопрос исключительно из вежливости.

– Они буквально идентичны тем, что были найдены в Трое! Вам ведь нравится Гомер?

– В Трое, той самой Трое?

На этой фразе что-то в моей душе встрепенулось. Мне нравился Гомер и большую часть детства я провела за штудированием античной литературы.

– Отправляйтесь туда, когда будете готовы, – не терпящим возражений голосом сказала терапевт. – Найдете там руины каменного лабиринта. Он поможет вам избавиться того, от чего вы хотите избавиться. Так же как поможет вернуть то, что вы хотите вернуть.

– Что-то я не поняла, вы точно психолог?

Я улыбнулась, но Оксана оставалась серьезной.

– Все вы поняли, Лиза. Идите туда, но не сейчас. Только когда примите правильное решение и поймете, что готовы.

– И что мне нужно делать?

Я сама удивилась тому, что задала этот вопрос.

– Пока ничего. Решите раз и навсегда, чего вы хотите: оборвать или вернуть?

– А потом?

– Потом идите к лабиринту с четким пониманием того, о чем собираетесь просить. Пройдите от начала до конца, если хотите вернуть прошлое, и от конца до начала, если решитесь с ним распрощаться.

Скептик во мне и не думал соглашаться с услышанным.

– И что, вы хотите сказать, что каждый может прийти туда и пожелать чего душе угодно?

Оксана покачала головой.

– Далеко не каждый, но вы можете.

– Почему?

– Только высокодуховные люди могут войти в Храм Солнца. Остальные просто пройдут мимо. Даже если от него остались одни руины.

*Прямо-таки Хогвартс какой-то*, подумалось мне.

– По-вашему, я высокодуховный человек?

Разговор становился все интереснее и интереснее.

– Вы себя совсем не знаете, Елизавета, – и она поспешно добавила прежде, чем я успела возразить: – Вы знаете свое расстройство. Но вы не знаете себя. Сейчас вы спите, но однажды проснетесь, и поймете, о чем я толкую.

– Разве для этого мне не нужно услышать свое Высшее Я?

– Да забудьте вы об этом Я хоть на минутку! Сейчас не время для поисков самости!

Я удивленно взглянула на доктора.

– Еще успеете погрузиться, – уже спокойным тоном произнесла она.

– Но почему не сейчас?! – сдерживая слезы простонала я. – Мне нужны ответы!

– Вы все равно их не получите, Лиза.

– Но почему?

Док окончательно вышла из выбрала, поднялась над столом и совсем по-матерински накрыла рукой мою ладонь.

– Сегодня ваше Высшее Я вам ничего не скажет. Неужели вы до сих пор этого не поняли? Оно не одобряет то, каким человеком вы стали, Лиза.

По моей коже пробежал мороз, но я старалась сохранить спокойствие. Хотя бы визуально.

– Вы о депрессии?

– Депрессии, суициде, мужчинах, которых вы любите.

– Но я больна! – эта фраза показалась мне глупым оправданием, но я, зачем-то повторила: – Больна, док.

– Ерунда, и вы это знаете не хуже моего. Вы гораздо сильней депрессии.

– Думаете вы просто так выбираете себе разрушительных спутников жизни? Нет-нет-нет, это Высшее Я их находит.

*Он с самого начала знал, что так будет.*

*И ты знала.*

– Обычно я не говорю с пациентами в таком ключе, но не сочувствие вам сейчас нужно. Все, что вы пережили – всего лишь кармический урок. Вы должны усвоить что-то очень важное, деточка, и тогда сможете… Лиза, вы в порядке? Простите ради бога, я совсем не хотела вас задеть! Почему вы плачите?

– Просто не называйте меня деточкой.

– Хорошо простите. Хотите воды? – она дала мне время успокоиться, а затем спросила: – Голос из прошлой жизни?

– Да, он самый.

В дверь постучали.

– Одну минуту! – крикнула Оксана и вернулась в кресло. – Сегодня с я вас денег не возьму, но возьму кое-что другое.

– Что же?

– Обещание, что вы оставите попытки самости до тех пор пока не сделаете правильный выбор.

– Ладно. Хорошо, но… Как я узнаю, что сделала правильный выбор?

– О, дет… Лиза, вы это поймете. Сомнений и быть не может. А затем поймете гораздо больше того, что хотите понять.

Я неотрывно смотрела в глаза сидящей напротив женщины. Большие и карие, как мои собственные.

– Пойму когда проснусь?

– Ну да. А теперь простите, у меня пациент.

– А как мне найти этот лабиринт? – уже уходя спросила я.

– Он сам вас найдет, когда вы будете готовы к этой встрече.

Это был январь две тысячи семнадцатого.

<div style="text-align: center;">***</div>

Май того же года застал меня врасплох. Мне думалось, что с Веней покончено, но в преддверии лета меня охватила настоящая депрессия. Погода, прибой, царившие в городе запахи – все это возвращало меня назад, в самое начало нашего с Вениамином романа.

Воспоминания оказались ярче, чем ожидалось, а боль – сильней, чем мне бы того хотелось, и я сама не заметила, как из медитации и восстановления очутилась в очередной затяжной депрессии.

Сперва я еще как-то пыталась бороться, но однажды силы иссякли. Я вновь погрязла в болоте собственной боли, и в какой-то момент перестала бороться. Уставшая да разочарованная во всех и вся, я позволила зыбучим пескам депрессии утащить меня на самое дно.

Так вот, сидя на этом дне, я вспомнила о месте силы моего бывшего терапевта. Хотя, вполне возможно, что все было наоборот, и это лабиринт обо мне вспомнил. Я нашла его абсолютно случайно, слоняясь предрассветными переулками старого города. Решила передохнуть и умостилась на обрыве, затуманенным взглядом рассматривая темные воды, что бушевали далеко внизу.

Было в этом месте что-то умиротворяющее. Казалось бы, деревья как деревья, да и река под ногами ничем не отличалась от той, что встречается в других частях города, но...

*Здесь легче дышать*, подумала я, поражаясь собственным мыслям.

Затем взошло солнце. Моя фляга опустела, и я собралась идти то ли домой, то ли за добавкой, а когда обернулась, увидела ряд тысячелетних камней, торчащих из-под земли и выложенных причудливой спиралью.

Сомнений быть не могло, это был он, Храм Солнца. Но почему я не заметила его раньше? Почему видела такого внушительного сооружения, сотни раз проходя мимо? Почему, на худой конец, не споткнулась о камни этим утром, когда во тьме брела к обрыву?

Казалось, все это были пустые вопросы. Вопросы, ответы на которые больше не имели значения. Вместо них в памяти всплыли слова Ольги:

*Идите к лабиринту с четким пониманием того, о чем собираетесь просить. Пройдите от начала до конца, если хотите вернуть прошлое, и от конца до начала, если решитесь с ним распрощаться.*

Вспомнив об этом, я подорвалась на ноги и стремительно направилась к началу лабиринта. На половине пути вдруг остановилась и с куда меньшей решимостью побрела в конец строения, но так до него и не дошла. Мне оставалось всего пару метров, когда я опять замерла как вкопанная.

Так и бродила вокруг лабиринта, окончаьельно запутавшись в чувствах и желаниях. В какой-то момент рука инстинктивно потянулась к пустующей фляге, и меня осенило.

Мне вовсе не обязательно было прощаться с чувствами к алкоголику. Для начала стоило проститься с самим алкоголем.

И я уверенно зашагала к концу лабиринта.

*Только бы не передумать*, пронеслось в голове, и я перешла на бег.
