# 100 {-}

Спустя год после разрыва с Вениамином я все-таки с некоторой робостью села за печатную машинку. С робостью потому, что я никогда не писала о своей жизни настолько откровенно. В моих предыдущих работах есть персонажи, места и даже целые диалоги, взятые непосредственно из моей жизни. И все же прошлые книги были полуабтобиографичны, не более. 

Тем вечером я до рассвета смотрела сначала на пустой лист бумаги, затем в открытый блокнот, ну и, конечно же, на текстовый документ. В итоге я сдалась. Отправив все эти атрибуты к чертовой матери, я поднялась в кладовку и после продолжительной экскурсии по стопкам полнейшего хлама притащила домой печатную машинку. Она была старше меня лет на двадцать, но все еще в пригодном для работы состоянии. Первые двадцать шесть страниц были отпечатаны именно на этой старушке. 

Сложно было поверить, что времена, когда вино казалось мне неотъемлемой частью образа, творчества, да и жизни в целом, внезапно прошли. Скорее инстинктивно я наполнила свой бокал доверху, но так к нему и не притронулась. Когда я успела превратиться в трезвенницу? 

Что ж, я бросила алкоголь прошлой зимой. Наши отношения оказались самыми стойкими из всех, что были в моей жизни, но даже они закончились. Когда-то алкоголь полностью заполнял мою жизнь. Я работала с ним по шестнадцать часов, каждый день в моем доме находилась парочка винных бутылок, которые непременно пустели к вечеру, и я заканчивала свои дни как настоящий завсегдатай баров. В моем шкафу до сих пор можно найти диплом бармена. Каждый из моих литературных альтер-эго не выпускает из рук стакан, а если и выпускает, то лишь для того, чтоб плеснуть в него следующую порцию горючего. Даже моя подпись содержит крохотный винный бокал. На моей левой руке есть татуировка, которую я сделала в восемнадцать – цитата из «Синей птицы» Буковски. Она о сигаретном дыме, алкоголе и чувствах израненной души.

В каком-то смысле, у меня есть явная предрасположенность к алкоголизму, потому что я писатель и я нестабильна. А еще мой IQ 170, что по умолчанию делает меня несчастным человеком. Окружающие привыкли видеть меня с ручкой, бокалом и сигаретой. Шутки в сторону, если вы введете в Гугл «почему писатели…», первыми результатами поиска будут: пьют, в депрессии, алкоголики, странные и суицидальные. 

Вернемся к тому, что я уже двенадцать месяцев как не была пьяна. Честно говоря, я не могу сказать, что горжусь собой или вроде того. Я никогда не посещала встречи анонимных алкоголиков и вообще не делала ничего для того, чтобы бросить пить. Единственными моими действиями были любовь и ненависть к алкоголику. Так что же все-таки случилось?

Я просто чуть не вышла замуж за того, кто уже был женат на водке.

Спустя пару месяцев после моего отъезда он начал жить с женщиной, которая гораздо старше меня. Она даже старше его самого и чертовски похожа на мать Вени, которую тот так ненавидел. С женщиной, о которой говорил: «Ее звали Алла, она работала в школе, и я ее не любил». Они жили в нашем доме, в Симферополе. Ели за нашим столом и трахались в нашей постели. Я видела ее фото с моей чашкой в руках. До этого Веня полтора года прожил с девочкой, недалеко ушедшей от подросткового возраста, о которой он говорил: «Ее звали Рима, она художница, и я ее не любил», – а до нее с кем-то там еще. Затем он женился на девушке, которую знал всего ничего. Интересно, она уже спрашивала у Вени, делал ли он прежде предложение руки и сердца? Если нет, то обязательно спросит: женщины постоянно этим занимаются, и я даже знаю, что он ответит.

*Ее звали Лиза, она была писателем, и я ее не любил.* 

Вам никогда не казалось странным то, с какой легкостью порой люди заводят новые отношения? Они завтракают вместе, гуляют за руку, делают покупки, обсуждают совместное будущее и засыпают в обнимку. У таких людей есть шутки, которые понятны только им, места, которые памятны лишь дня них, любимые заведения и все такое прочее. А потом это вдруг обрывается и появляется другой человек, с которым ты занимаешься всем тем же так, словно это впервые.

Обычно никто не говорит тебе: «Эй, давай поиграем в семью еще пару месяцев, пока мне не надоест? Ты не переживай, затем я нагуляюсь и найду другую временную дурочку, с которой буду играть в семью. Но сейчас-то мы семья, так что иди ко мне, деточка».

Нет, обычно так не говорят, но порой мне кажется, что это могло бы стать не самым плохим вариантом.

Веня – что вообще это было? Боюсь, это была любовь. Блядская, ничем не прикрытая любовь. Без сомнений, жить, не зная о подобном чувстве, было бы проще. Но гораздо бессмысленней.

Я помню каждый день, что мы провели вместе, а также все вечера, ночи и то, что было между ними. Разговоры, шутки, ссоры. Разные мелочи, но всего не запишешь. К тому же писать об этом оказалось чертовски больно. Я словно была вынуждена пережить эту историю еще раз. Что ж, с трудом взявшись за прозу, я смогла преодолеть эмоциональный барьер. И вот я ее закончила. 

Если говорить откровенно, мне ничего в жизни не давалось так сложно, как этот текст. Дело здесь отнюдь не в том, чтобы правильно восстановить хронологию. Я помню все имена, даты, события, диалоги и так далее до подробнейших деталей. Могу без труда вспомнить, во что был одет человек пять лет назад, что он говорил, в каком настроении был и почему. Могу сказать, какая за окном стояла погода, что за музыка играла в проезжающей мимо машине и о чем я в тот момент думала.

Говорят, мне повезло с памятью, но я так не думаю. Есть вещи, которые непременно стоит забыть. Странно осознавать, что в конечном счете все мои чувства, надежды и мечты смогли вместиться в каких-то 400 страниц. 

Здесь они и останутся. 

Я практически никогда о нем не думаю. Не вспоминаю о нем, когда слышу старые мелодии, звучащие в машине, или где-нибудь в торговом центре. Не вспоминаю, когда вижу гигантские порции, не вспоминаю, когда встречаю логотип КФС, не вспоминаю, когда поднимаюсь на эскалаторе. Я не вспоминаю о нем, даже когда слышу знакомые нотки одеколона от случайных прохожих. 

И лишь поздней весной, когда солнце сияет совсем по-летнему, когда волны играют в его лучах так, словно сегодняшний день – особенный, когда я вдыхаю легкий бриз, пришедший откуда-то издали, я не могу не вспомнить о Вениамине Ларионове. До моих ушей доносятся звуки парящих над лазурной гладью чаек, шум прибоя и смех толпы, празднующей что-то на пляже. В такие моменты меня одолевает внезапное чувство ностальгии, когда ощущения настолько яркие, что тоска по ним становится куда сильнее и важнее самих воспоминаний. Это состояние уходит так же резко, как и появляется. И каждый раз меня охватывает тяжелая, невыносимая пустота, вырвавшаяся откуда-то из глубин моей души. 

Я больше не скучаю по Вениамину. Я скучаю по себе. По той себе, которая не боялась быть счастливой.

Это была сумасшедшая любовь. Такой ее показывают в рекламе кофе. Внезапная, всеобъемлющая, волшебная. И закончилась она в лучших традициях волшебства. Каждый день, проведенный в этих отношениях, казался вспышкой. Молниеносное мгновенье, которое каким-то необъяснимым образом длилось вечность. Уйма амбиций, эмоций и непрекращающаяся эйфория. Это определенно была любовь, и она определенно была сумасшедшей. Пожалуй, любовь научила меня всему, чему только можно научить такого человека, как я. Наши отношения исчезли с той же скоростью, с которой появились на свет. Все, что от них осталось – обручальное кольцо с ироничной надписью. 

Да и тому не суждено было у меня остаться.
