# &nbsp; {#chapter-101}

Почему все получилось так, как получилось? За это время я успела понять, куда делась жизнерадостность Кобейна, отчего повесился Кертис, что случилось с матерью Леннона, как ушел Маяковский и что имел в виду Джим Моррисон, вопрошая со сцены: «Хоть кто-нибудь меня понимает?». Если об этом думать, можно довольно быстро сойти с ума. Однако, с ума сходить мне как-то не хотелось. Разве что на минутку, чтоб осмотреться по сторонам да вернуться обратно в русло. Ведь мне всегда думалось, что сойти с ума – не так уж и плохо. Куда хуже стать безумным.

Кстати о безумцах. Уже ближе к лету мы с подругой гуляли по Киеву. Деревья были совсем зелеными, а птицы пели уже совсем по-летнему. Мне нравилось вдыхать ночной воздух, глядя как над городом колышутся верхушки увесистых крон. 

– Допустим, у тебя есть шанс начать любые отношения с чистого листа. Но только одни отношения. Кого ты выберешь? – спросила Марта.

Повисла затяжная пауза, в ходе которой я вдруг ясно осознала, что Веня – это тот, о ком я никогда в жизни не скажу, что готова начать с чистого листа. А еще я поняла, что он тот, с кем бы я очень сильно хотела хотеть начать что-то сначала. 

– Так, почему не начнешь? 

– Потому, что я бы и хотела ошибаться… Но я не ошибаюсь.

– И каково это никогда не ошибаться?

– Дерьмово, - только и сказала я.

– Да уж, это печально, - прокомментировала Марта.

И, кажется, расстроилась. Куда больше, чем я.

– Как-то раз, влив в себя чуть больше водки, чем требовалось, Вениамин сказал мне: «Нам стоило бы умереть тогда, весной. Тогда мы были бы всегда молоды, счастливы и полны любовью друг к другу.» 

Это было незадолго до нашего разрыва, о наступлении которого, я, само собой, и не подозревала. Хотя, кого я обманываю? Я чувствовала это всем сердцем, но всячески игнорировала подобные мысли. Боялась снова оказаться сумасшедшей.

Нам стоило бы умереть тогда, весной.

А, может быть, это была моя бредовая мысль. Моя, а не Вениамина, ведь он настолько пошатнул мою и без того нестабильную психику, что я и по сей день поражаюсь тому, как живу, слыша посторонние голоса у себя в голове. В общем, кто бы ни был первоисточником этой мысли, я определенно помню, как Веня говорил что-то подобное.

Вечно несгораемые чувства первых серьезных отношений – обычно такое бывает лишь в кино. Что касается реальной жизни, есть только две опции: любо отношения заканчиваются смертью одного из участников, либо огромнейших масштабов скандалом. Вопреки сопутствующей ей болезненности, в обоих случаях концовка почему-то остается открытой, так что ты никогда не знаешь наверняка, что именно пошло не так.

– Почему он так сказал? – продолжала спрашивать Марта. 

В тот день в ней было немного амфа, который явно порождал любознательность.

– Ну, как почему? Наверное, в момент пьяного отчаянья, он вдруг понял, что уже никогда не будет так молод. И уж точно никогда не будет так влюблен. Вообще-то, раньше я бы сказала наоборот. Я бы сказала: уже никогда не будешь так влюблен и уж точно никогда не будешь так молод, но сейчас понимаю, что все наоборот. Ты можешь быть молод на протяжении целых двадцати, тридцати, а то и сорока лет. Черт, да ты и в пятьдесят можешь вообразить себя молодым и стать счастливым, но… Но, знаешь, ты уже точно не сможешь полюбить так, как полюбил однажды. В самый первый раз.

Я говорила не о школьных влюбленностях и не об импульсивных опрометчивых идеях. Речь шла о самой настоящей первой любви. О человеке, за которого тебе вдруг захотелось замуж, хотя прежде ты никогда не мечтала о свадьбе. О том, с кем не страшно было состариться. О том, кто стал твоей семьей.

После этих слов Марта с недоверием посмотрела на меня.

– Не хочешь ли ты мне сказать, что ты не любишь Эрика?

– Можно полюбить еще раз, - с улыбкой сказала я. – И полюбить ничуть не меньше, а может даже и больше. Полюбить новой, взрослой и предусмотрительной любовью. Но во время этих отношений ты постоянно будешь бояться, что жизнь никогда не станет такой простой, какой она казалась во время первой любви. Тогда я ничего не боялась, и не было ничего, что могло заставить меня опустить руки. Любые вершины казались доступными пока он был рядом и все такое. А теперь я знаю, чем все может обернуться и боюсь, что как раньше уже не будет не из-за того, что я до сих пор люблю Веню, а из-за того горького осадка, который оставила за собой эта любовь.

– А это правда?

– Не-а.

Я пожала плечами.

– Хуйня какая-то получается, – подытожила Марта.

Как всегда лаконично.

<div style="text-align: center;">***</div>

Следующим днем мы отправились на пляж. Последний день лета, все-таки. Путь оказался не близкий. Дорога шла через лес. Мы гуляли по нему вприпрыжку, раскуривая косяк да распевая старые хипповые песни. Верней, пела я, а Марта пританцовывала идя чуть впереди. 

*Here comes the sun*

Скрывающееся за соснами солнце словно поддержав подругу, решило примкнуть к танцу. Мы долго шли, наступая на хрустящие ветки и наблюдая солнечные лучи, колышущиеся в такт музыке. В воздухе застыло пленительное спокойствие. В такие моменты ты словно ощущаешь себя частью вечностью, из которой мы все созданы.

*Here comes the sun*

*And I say, it's all right*

*Little darling…*

На возвышении лежало старое дерево, а сквозь его ствол струились солнечные лучи, яркими стрелами пронзая завесу лесного дыма. Подруга стремительно побежала вверх по склону.

– Там внизу поляна! – крикнула Марта.

Цветастые юбки мелькнули над упавшим деревом, и подруга исчезла из моего поля зрения.

Я поспешила за ней, но, поднявшись на холм, решила задержаться. Уселась на ствол и принялась внимательно разглядывать открывшийся отсюда вид: глухую лесную стену, ярко освещенную поляну и Марту, с широко разведенными руками кружащуюся на зеленой-зеленой траве. Рыжина ее волос подыгрывала в такт солнцу, но что-то в этой идеальной картинке показалось мне странным.

Она протянула мне трубку, но курнуть я не решилась.

– Лиза, с тобой все в порядке? – спросила лесная Марта.

– И да и нет, – отвечаю я, не без удивления вспоминая университет да понимая, что уже видела эту сцену в прошло.
