# 102 {-}

Этим утром у меня наблюдалось какое-то особенно расслабленное состояние. Будь у меня чуть больше свободного времени, я бы обязательно посвятила его прокрастинации.

Вот я лежу вот в кресле-мешке под импровизированной пальмой в виде огромного фикуса и вдыхаю аромат свежесваренного кофе. Я люблю его так же страстно, как сам агент Купер, но сейчас предпочла бы вдыхать морской бриз. Ещё здесь есть такое же импровизированное солнце в виде электрического белого шара, таинственно подвязанного к потолку переговорки, и вполне настоящие люди.

Это сотрудники, чьи голоса звучат где-то на фоне. У нас летучка, так что голоса делятся утренними новостями. О челленджах, священниках-педофилах из Пенсильвании, какой-то птице, что залетела в комнату, нагадила на ноутбук и умерла, сексуальной статистике в Британии и чём-то там ещё.

У меня тоже есть новости. О подростке, которая сбежала из больницы при помощи восьмидесятилетней бабули-колясочницы, и о мальчике, который продал свою свинью-чемпионку, чтобы помочь девочке, больной раком. Затем свинья сбегала, как в старой шутке, и мальчик продавал ее снова… А еще о том, что кто-то позарился на мой запас седативных, так что я так и не успела их принять.

Это все интересно, наверное. Но я лишь лежу и думаю: как жаль, что оазис у нас бутафорский.

<div style="text-align: center;">***</div>

Киев расцвел вечерними огнями, когда я умостилась на Андреевском. Уселась и тут же вскочила обратно: мне вдруг очень захотелось потанцевать.

Мне не хватает общения, но я терпеть не могу людей. Это настолько иронично, что здравствуйте и сразу до свидания.

Наверное, стоит начать с того, что я хронический мизантроп. Сперва я как-то старалась это перебороть и подпускала к себе только парочку проверенных друзей, но после n-ного предательства этих самых друзей ситуация усугубилась. Причём истории были настолько неадекватными, что над ними плакал бы весь каст ‘Санта-Барбары’. Говорить о них мне совсем не хочется.

Мой лучший друг – социофоб и самый настоящий интроверт. Пропасть без предупреждения и объяснения для него нормальное дело. В последний раз я видела его года полтора назад, так что понятия не имею, где он и как поживает. Его не было рядом, когда в моей жизни происходили ужасные вещи, так что вряд ли уместно называть этого человека другом. Последних подруг, каким-то чудом оставшихся со мной, я потеряла после переезда в Киев. Ситуация, в общем, стандартная: сегодня тебя называют лучшим другом и говорят, что ряди тебя готовы пойти хоть на убийство, а завтра о тебе уже никто не вспомнит. Мне всегда казалось это странным.

Конечно, я уже давно убедилась в том, что куда проще жить, не подпуская к себе других людей. Так тебя никто не сможет обидеть. Но случаются моменты – и сегодня как раз один из таких дней – когда мне так грустно и одиноко, что я вот-вот начну бросаться на прохожих и умолять их стать моим другом.

Раньше в такие моменты я начинала плакать и предаваться селф-харму, а сегодня... Сегодня я танцую. Просто включаю любимую музыку и начинаю танцевать, как только мне становится грустно. К чему я веду? А к тому, что если вы однажды увидите меня неожиданно танцующей в странном месте, не обессудьте. Скорей всего, мне просто одиноко, так что можете присоединиться к танцу.

<div style="text-align: center;">***</div>

*Больше так не могу*, решила я ближе к осени и взяла билет в Симферополь.

Слишком много вопросов накопилось у меня за это время. Слишком много раз я переживала депрессию. Слишком много боли я подавляла, превращаясь при этом в бесчувственного биоробота.

Мне надоело вариться в котле собственной печали. Так что я сказалась на работе больной и села в поезд до Николаева. Там меня ждало побитое жизнью обручальное кольцо и револьвер, все так же заряженный одной-единственной пулей. Вместе мы отправились в Симферополь, а оттуда – в Севастополь, и вот я уже стояла на смотровой площадке напротив памятника затопленным кораблям.

Волны все так же бились о гранитные камни, словно я никогда и не покидала этого места. В лучах полуденного солнца они блестели и разбивались на миллиарды крохотных частиц, которые затем так же играли и блестели на скалах, камнях и носках моих туфель – на всем вокруг. Высоко в небе кружили чайки, бриз становился все холоднее, и только воздухе все еще можно было уловить нотки царившего здесь лета.

Лето моей жизни давно закончилось, и мне хотелось уйти вместе с ним.

Я посмотрела вниз – на волны, камни, скалы – и подумала, что нет лучшего способа покончить со всем этим. Всего-то один шаг, и вода заберет тебя в свои крепкие объятья. Хватит с меня всех этих фиаско по части самоубийств. Тут я могла довериться только морю.

Море знало, как сильно я его любила.

Затем я разжала пальцы и взглянула на содержимое своей левой ладони. Кольцо с ироничной надписью Love Will Tear Us Apart тут же заиграло на солнце. Держа его мизинцем, я перевела взгляд на правую руку. Туда, где был револьвер.

Оружие было все тем же. Я лишь добавила еще одну пулю. Хотела, чтобы все было честно.

Я закрыла глаза, сделала глубокий вдох и позволила себе то, чего не позволяла долгие годы: я по-настоящему вспомнила Вениамина.

Пряди пшеничных волос игриво падают на лицо, извечная сигарета все так же в зубах, и пепел с нее уже начинает падать на мягкую клетчатую рубашку. А на губах играет моя любимейшая из всех улыбок в мире, частично скрытая пышной бородой. Он либо задумчив, либо болтлив до невозможности, но каким бы Веня не был, его взгляд оставался неизменным. Каждый раз, глядя в эти зеленые глаза, я понимала, что не боюсь ничего на свете, пока он вот так на меня смотрит.

Таким он был в моем сердце. Вениамин Ларионов в расцвете шизофрении.

Я выдохнула и открыла глаза. Волны все так же бились о гранитные камни, солнце ярко светилось в небе, птицы кружили высоко-высоко, а я до сих пор была единственной, кто пришел на набережную полюбоваться морем перед дождем.

Но воспоминания о прошлой жизни не желали развиваться.

– Море перед дождем по-новому очаровательное, – говорю я той далекой весной.

Мне двадцать два, я много раз пыталась покончить с собой и теперь наивно полагаю, что все самое худшее в моей жизни уже позади. Короче говоря, я в кои-то веки счастлива, а потому позволяю себе задумываться о таких вещах, знаете.

– Море перед дождем, – говорю я, – по-новому очаровательное. Сначала оно очень тихое, но если прислушаться, можно услышать, как дневной бриз превращается в ночной. Затем появляются волны.

Тем вечером мы в обнимку бежали домой через пустые улицы Севастополя, целовались в подворотнях, как подростки, и промокли до нитки.

Воспоминание оказалось таким ярким, что я буквально чувствовала ладонями холод. Взглянула вниз и не без улыбки поняла, что переоценила свое воображение. Первые капли вполне себе реального дождя опускались на волны, на скалы, на камни и на мои туфли.

Над морем возвышался памятник затопленным кораблям. Казалось, он так близко, что стоит сделать только шаг и можно коснуться его рукой.

*Всего один шаг. Один выстрел*, эта мысль не давала мне покоя.

Тогда я еще раз взглянула на кольцо, потом – на зажатый в руке револьвер, словно взвешивая значимость каждой из вещей.

*Пришло время в себе разобраться, Васляева.*

*Раз и навсегда.*

*Достаточно набегалась.*

*Ты либо живешь, либо умираешь.*

На этом я крутанула барабан, приставила револьвер к виску, что было духу нажала на курок и была такова.

Голоса в моей голове исчезли.

В ушах раздался гул, непременно обещающий напомнить о себе головной болью. Похоже, меня слегка оглушило, и сердце колотилось с бешеной скоростью. Но я не умерла, и осознание этого факта оказалось веским поводом для того, чтобы жить.

Я улыбнулась памятнику, протянула к нему руку и разжала пальцы. Кольцо выскользнуло из них, ироничная надпись в последний раз блеснула на солнце и тут же исчезла в морской синеве.

Вдруг я поймала себя на мысли, что просто стою и вспоминаю, как когда-то была счастлива. В жизни мне всегда чего-то не хватало. Чего-то или кого-то, а затем спустя год или пять лет, или даже все десять, я мельком вспоминала то время и вдруг понимала, какой счастливой я тогда была на самом деле. Мне бывало трудно, бывало одиноко. Я страдала от многих вещей, а временами мне просто нечем было позавтракать, и я сновала по квартире в поисках мелочи на пачку самых дешевых сигарет. Мне было шестнадцать, восемнадцать, двадцать. Я не понимала современное общество и терпеть его не могла, а общество в свою очередь не принимало меня. И мои книги, что было особенно болезненно. А еще я очень долго и упорно любила людей, которые не любили меня. Иногда – хотя скорее чаще, чем иногда – я чувствовала себя такой одинокой, что мне просто хотелось орать, бить и крушить все вокруг. 

В такие моменты я собирала скопившиеся в доме пустые бутылки из-под алкоголя и шла на старое городское кладбище. Там, далеко от цивилизации, в самом забытом вселенной уголке, стояла видавшая виды каменная стена. Именно к ней я и направлялась. Здесь не было ни единой живой души в радиусе нескольких километров, так что я доставала из сумки бутылки и со всей дури бросала их в стену. А дури во мне имелось немало, и я все швыряла да швыряла бутылки, громко ругаясь на все то, что меня так достало. Со временем на душе становилось легче. Я выкуривала парочку сигарет, а затем принималась собирать стекло обратно в сумку.

Теперь же, вспоминая тяжелые и удивительно странные годы своей жизни, я ощутила тоску. Мне было откровенно дерьмово, но у меня были цели и целое море амбиций. Я всегда знала, чего хочу, и понимала, почему этого хочу. Я вдруг осознала, как сильно мне не хватало этой сумасшедшей версии себя.

Уже на обратном пути, спеша укрыться от проливного ноябрьского дождя, я услышала голос деда. Тот самый голос, который не могла припомнить со дня его смерти дождливым зимним утром две тысячи восьмого.

*Молодость – это такая штука*, сказал дед. *Она быстро проходит.*

<div style="text-align: center;">***</div>

И вот мне двадцать пять. Я снова здесь, в Киеве. Стою у окна чужой съемной квартиры, параллельно пытаясь найти в сети подходящее жилье. Смотрю на то, как туман сгущается у Северного моста, и всей душой стараюсь не думать обо всех других съемных квартирах, комнатах и домах, жизнь в которых так и не приблизила меня к основной цели.

Да, револьвер не выстрелил тем дождливым днем, но есть еще один.

Другой револьвер, который крутится в душе каждого пограничника, и пускай мне удалось обуздать свою депрессию, какая-то часть меня по сей день ждет, что на барабане выпадет пуля.

Суицидальные мысли – они как алкоголизм, и любой подверженный депрессиям человек рано или поздно это понимает. Пускай о таком и не принято говорить в обществе. Но правду знает каждый, кого однажды доставали из петли, кому заштопывали вены или промывали желудок.

Ты можешь потратить годы на реабилитацию, начать жизнь с чистого листа и все такое прочее. Вот только сколько бы гештальтов ты ни закрыл, желание свести счеты с жизнью никуда не денется. Оно может лишь уснуть, притаиться где-то на поверхности твоего подсознания, выжидая удобного случая, чтобы вновь о себе напомнить.

Смерть – это как секс или героин. Стоит хоть разочек ей отдаться и назад дороги нет. Лучше сразу убедиться, что тебя не вернут с того света, коль уж ты решился на подобный шаг. В противном случае идея самоубийства навсегда останется в твоей голове.

Это вовсе не значит, что все несостоявшиеся самоубийцы только и делают, что ходят да размышляют, как бы себя порешить. Хотя некоторые поэты именно этим и занимались. Проблема в том, что до определенного момента суицидент может и не знать о том, что он таков. ⠀

Никто не просыпается в один прекрасный день с мыслью о том, что надо бы застрелиться. Суицидальные думы обычно дают о себе знать постепенно и вообще как бы невзначай, принимая тактику твоего бывшего.

Только вот избавиться от таких мыслей куда сложней, чем от всех вместе взятых бывших. Наверное, потому что мысли эти – это и есть я. Ну или та часть меня, о которой я думала, что её уже давно нет. Но вот ее нет, в вот она здесь, и временами приходится подавлять желание исчезнуть.

*Усопнуть, умереть, уснуть.*

Так я и играю в эти mind games с собственным подсознанием. Но знаете, что меня утешает на пике депрессий?

Я выиграю при любом раскладе.

Что же тогда делать? Жить, господа.

Просто жить, не позволяя себе растворяться в других людях. Не позволяя себе ничего, что хоть как-то может отравить ментальное состояние. ⠀

По сей день я толком не могу объяснить, почему больше не хочу любить так, как любила Вениамина Ларионова, но если вы хоть раз в жизни испытывали подобные чувства, мне и не придется.
