# &nbsp; {#chapter-14}

Севастопольская вариация KFC находилась около большого торгового центра, куда мы с Веней в дальнейшем не раз заглядывали. Это было милое местечко с разноцветными диванами, широкими столиками, которых было от силы штук пять, и огромными окнами, плавно переходящими в стеклянные двери. 

Потягивая ледяное пиво, Веня пытался скачать какой-то фильм. Я расположилась справа от него и, закинув ноги на коленки своего спутника, размышляла над чувством внезапно охватившей меня эйфорией. Вернее, более углубленной ее формой. Теперь к списку моих ласкательно-уменьшительных имен добавилась еще и «невестушка». Воодушевленный изменениями в семейном статусе, Вениамин старался не упустить ни одной возможности называть меня так.

Втрескаться, втюриться, втюхаться, потерять голову, влюбиться по уши, отдать сердце, воспылать любовью, быть без ума, души не чаять, сохнуть, запасть и неровно дышать – все это, в общем-то, лишь малая часть тех эмоций, которые я испытывала. Предмет моих воздыханий сидел напротив. Он уплетал третий бургер подряд, а я потягивала лимонад и думала о том, что это удивительное чувство внутри, видимо, и есть пресловутые бабочки. 

Почему это произошло лишь спустя несколько дней? Можно много рассуждать о моем прошлом, разбитом сердце и защитном механизме, с которым явно что-то не то, раз он сдался так быстро, но правда в том, что я не знаю ответа. За что я его полюбила? Без понятия, но мне всегда казалось, что любят не за что-то, а кого-то и одним воодушевляющим весенним днем этим кем-то стал Вениамин Ларионов.

– Нужно раздобыть тебе кольцо, – деловито сказал Веня, покончив с бургером.

Я взглянула на свою руку. Нынешнее и правда было великовато. Вене пришлось согнуть его заднюю часть, чтобы кольцо хоть как-то держалось на моем пальце.

– Да, наверное.

Вскоре к нам присоединилась Неля с ее прайсами. Это была весьма крупная женщина бальзаковского возраста. Она носила броский макияж из девяностых и короткую стрижку со странной треугольной челкой. Еще Неля была громкой и невыносимо много болтала. Ее историям конца и края не было видно, но имелось в них что-то по-домашнему приятное. Мне она сразу понравилась. Неля стала первым человеком, заказавшим при мне семь бургеров и что-то там еще, а затем употребившим все это прежде, чем я допила свой кофе. 

За время выполнения заказа, Неля успела рассказать о своем сыне, долгах, кредитной истории, районе, в котором она живет, зарплате, каталогах, маникюре и, почему-то, Екатеринбурге. 

– Так вы двое и правда женитесь? – внезапно спросила Неля.

За время ее монолога я слегка забыла о том, что умею разговаривать, так что ответила не сразу.

– Правда, – сказал Веня.

Он взял меня за руку.

– Думаю да, – добавила я.

Неля смотрела на нас с каким-то странным уважением. Затем объявили ее номер, и девушка, хотя, скорее, женщина поспешила забрать свой заказ. Позже она написала Вене о том, что в диком восторге от его выбора. Сказала, что со стороны мы смотримся как современные Курт и Кортни.

*Что ж*, подумала я. *Надеюсь, эти отношения не закончатся самоубийством одного из нас.*

На обратном пути мы заехали в несколько ювелирных. На самом деле я еще не пришла в себя от внезапно охвативших меня чувств, что уж говорить о перспективе внепланового замужества. Удивление прошло не сразу. Мне понадобилось месяца полтора, дабы свыкнуться с мыслью о том, что я чья-то невеста.

– Какое ты хочешь? – Вениамин увлеченно доставал кольца с подставок. – Такое? Нет? Тогда может это? Или нет, подожди, вот это!

Говоря о кольце, мне не хотелось ничего особенного. Простая обручалка, тонкая, выполненная из серебра, меня вполне устраивала. Я никогда не любила золото. Увы, все, что встречалось на нашем пути, непременно содержало какие-то цветастые камни, стразы и бог его знает, что еще. Мы нашли парочку подходящих вариантов, но все кольца были либо малы, либо до безобразия велики. Вениамина это огорчило куда больше чем меня.

– Оно того не стоит, – ласково произнесла я, заметив грусть в глазах своего мужчины.

– Деточка, – вздохнул он, – такое чувство, что сегодня все против нас.

Я обняла его за плечи.

– Вовсе нет. Мы встретились четыре дня назад и уже сутки как помолвлены. По-твоему, все действительно выглядит настолько мрачно?

Веня избавился от сигареты и поцеловал меня.

– А, знаешь, ты права.

– К тому же, – чуть погодя добавила я, – вдруг это знак?

– Знак?

– Ну, да. Может быть, перед принятием самого важного решения в жизни, нам стоит пожить вместе чуть дольше? Ты сам-то не хочешь хорошенько обдумать этот вопрос? – говоря это, я переживала, что Вениамин вновь затоскует, но он продолжал смотреть на меня спокойным, полным любви взглядом.

– С ума сошла? Я думал об этом целых три дня! – наконец, ответил Веня. – Я вообще никогда прежде так долго ни о чем не думал.

Мы рассмеялись, хотя оба знали, что, в большинстве своем, так оно и было.


