# &nbsp; {#chapter-15}

Очередной бар и мы в нем. Сидим, наслаждаясь прохладой кондиционера и потягивая напитки. Это была одна из многочисленных пивных, что разбросаны по всему Севастополю. 

Вениамин зачем-то предлагает мне пиво. Я как всегда отказываюсь.

Совершенно не люблю пиво. И это вовсе не значит, что я не пила хорошего пива, как думают большинство тех, кто слышит это заявление. Я была на нескольких пивоварнях и долгое время работала за стойкой. Словом, перепробовала целую кучу сортов. Итог был один: пиво я на дух не переношу. Оно для меня как черный чай без сахара – слишком горькое и бесполезное, чтобы пить. 

Однажды в разгар маниакального эпизода я окажусь в Варшаве, где впервые добровольно закажу себе пива. Проделаю то же самое в Праге и Берлине, а потом еще в Бремене и парочке других немецких городов. Просто так. Потому, что могу. Я буду пить кофе без молока и чай без сахара с абсолютным безразличием, но… Случится это спустя годы, а пока мне все еще двадцать два и пиво – совсем не по душе этому персонажу. 

По этой простой причине, тем вечером мне достался вишневый сидр. Вениамин же предпочел классику, и приканчивал уже второй бокал своего хмельного напитка. У нас был целый стол пивных закусок, разнообразию которых позавидовал бы сам Пантагрюэль. По телеку транслировали «Брюса Всемогущего». В детские годы этот фильм был одним из моих любимых фильмов, и это придавало особого уюта нашему вечеру.

– Я сейчас так счастлив, – с чувством сказал Вениамин. – Никогда в жизни не был таким счастливым.

– Это потому, что я не против каждый день ошиваться в барах? – улыбаясь, уточнила я.

– Вовсе нет, глупышка. Хотя, возможно, и не без этого, – он подмигнул и тут же стал совсем серьезным. – Я счастлив, потому что все вокруг кажется таким… идеальным. Я сижу в пустом баре посреди ночи, смотрю старое кино. Нет никаких конфликтов и мордобоев. Просто тихий, приятный вечер. Рядом сидишь ты, вся такая идеальная. С моим кольцом на пальце. А я смотрю на все это, и не могу поверить в то, что мне и в самом деле так повезло.

Он протянул руку, чтобы погладить проходившего мимо старого кота.

Вениамин любил животных. Думаю, это и была одна из причин, по которым я решилась ему довериться. Он обожал котов, я же души не чаяла в собаках. Сколько себя помню, животные всегда были мне близки. Гораздо ближе людей, так что я никогда бы не связала свою жизнь с человеком, не любившим животных. 

Каждый день, гуляя по городу, направляясь на рынок, или попивая пиво в каком-нибудь из севастопольских двориков, Веня останавливался, чтобы потискать очередную животинку. Таких остановок бывало по полсотни в день. Частенько мы покупали еду и отправлялись кормить уличных животных. Это качество я всегда ценила гораздо выше, чем физическую красоту или, скажем, умение управляться с клитором.

– Расскажи мне о своих бывших, – попросила я тем тихим вечером в пивной.

Вопреки тому, что большую часть вечера мой мужчина был разговорчив, – даже болтлив – он всячески избегал темы своих бывших отношений. В юношеские годы я слыла той еще ревнивицей и непременно оценила бы этот жест, но теперь такой расклад не мог не настораживать. В конце концов, я уже давно осознала, что ревновать к прошлому – крайне глупо, и даже научилась уважать это самое прошлое. Проблема была в том, что Веня, естественно, не отрицал того, что не раз состоял в серьезных отношениях, но при этом, почему-то, вел себя так, словно этого не было. 

– Ее зовут Римма. Мы жили вместе полтора года. Я ее не любил, – вот максимум выдаваемой Вениамином информации.

– Зачем же ты тогда жил с ней так долго?

Обычно в ответ на этот, казалось бы, логичный вопрос, Веня просто пожимал плечами. Один раз, правда, заметил, что ему просто было одиноко. Что ж, на этот раз мне хотелось услышать более информативный ответ.

– Расскажи мне о своих бывших? 

– Что ты хочешь знать? – внезапно спросил Веня.

Я настолько изумилась этому вопросу, что как-то сразу и забыла, чего я там хочу знать. Почувствовала себя эдаким растерянным свидетелем Иеговы, которого впервые в жизни пустили на порог. Да так неожиданно, что бедняга и вовсе забыл, о чем положено говорить дальше.

Стоило собраться с мыслями прежде, чем болтливость моего жениха успеет улетучиться.

– Хочу знать о той, кого любил, конечно же.

– Ты первая женщина, которую я по-настоящему полюбил, – просто ответил Веня.

Я не могла оставить это заявление без поцелуя.

– В таком случае, – продолжила я, оторвавшись от жениха, – расскажи о той, о ком думал, что любил. Давай начнем с простого. Как она выглядела? 

И он рассказал. Она была заметно старше и теперь преподавала в школе. Позже, взглянув на фото этой женщины, я в который раз убедилась в привычке человеческого мозга идеализировать прошлое. Вениамин описывал ее как натуральную блондинку с зелеными глазами и большой грудью. Со снимка же на меня смотрела более чем просто полная дамочка домашнего образца с какими-то серыми волосами. Она носила жуткую бабушкину одежду и выглядела куда старше своего возраста. 

*Баба как баба*, подумала я. *Если уйдет, то точно не к ней.*

Не стану врать, все это как-то плохо вяжется с моей жизненной философией, но увиденное меня порадовало. Я была моложе, стройнее и привлекательней. И из моей постели еще никто не выходил полным сил. 

Преимущество над бывшей любовью Вениамина казалось мне очевидным, и я тут же забыла об этой женщине, вычеркнув ее из мысленного списка своих потенциальных раздражителей. Сама мысль о том, что кто-то может изменить мне с ней казалась нелепой. 

Паршиво так думать о людях, но мне было едва за двадцать и мне частенько срали в душу, так что чего вы теперь от меня хотите? Было непросто доверять людям, и, если осознание чьей-то серости на моем фоне могло предотвратить приступ ревности, этим стоило воспользоваться. 

– Когда я впервые привел Аллу домой, мать увела ее на балкон и на протяжении часа уговаривала бежать от меня куда подальше.

– Как так? – удивилась я, но Веня не ответил.

– Я даже звал ее замуж, – признался он. – Договорился о том, чтобы устроить фаер-шоу около одного обрыва и сделал ей предложение. 

С одной стороны, меня это очень удивило. Мои эгоцентричные женские нотки, все же, предпочли бы думать, что я была единственной, на ком Веня захотел жениться. С другой, он сделал мне предложение третьей ночью после нашей встречи. И почему меня должно было это удивить?

*И где мое фаер-шоу?*

– И что же произошло?

– Сам не знаю, но вскоре я передумал жениться. Просто выносить ее не мог. Она, знаешь, была совершенно неинтереснейшим человеком и вела себя как моя мама, не как девушка. Понимаешь, о чем я?

– Понимаю. 

– И что ты понимаешь?

– Есть три типа отношений. Два из них провальные и твой как раз вписывается в их рамки.

– А третий? – спросил Веня.

– А третий это то, что у нас с тобой, – ответила я.

<div style="text-align: center;">***</div>

– Еще была Римма, – продолжал Вениамин. – Она очень много врала. Без особых причин. Рассказывала, что над ней издеваются родители, которые оказались замечательными людьми. Рассказывала, что кто-то пытался изнасиловать ее в автобусе. Рассказывала, что ее постоянно хватают за задницу какие-то незнакомцы и что она все время падает, спотыкается, ударятся и все такое. 

– Сколько ей лет-то было когда вы сошлись?

– Семнадцать.

– Красивый пример юношеского максимализма. Кстати говоря, она красивая?

Веня отхлебнул пива.

– Вообще нет. В очках еще более-менее.

Меня всегда настораживали подобного рода ответы.

– Так почему ты с ней полтора года прожил?

Он традиционно пожал плечами.

– Дальше стало хуже. Она начала рассказывать людям о том, что я ее избиваю. Как-то пыталась убедить моих друзей, что была беременна. Узнав об этом, я якобы избил ее прямо посреди улицы.

– О, у меня тоже был один товарищ с явным дефицитом внимания. И тоже патологический лгун.

– Тоже беременный?

– Ну, почти. Умеем мы выбирать… – я подняла бокал. – За умение выбирать спутников жизни.

– А то! Даже не помню, когда в последний раз разговаривал вот так вот по душам, – признался Веня. – Если вообще разговаривал. Я имею в виду, с девушкой. А что насчет твоих бывших?

– Ну, мне повезло больше, – я ухмыльнулась. – До встречи с тобой я практически три года провела вне отношений.

– Серьезно?

– Ага.

– Почему? – лицо моего возлюбленного выражало крайнее недоумение.

– Да все очевидно. Я не могу размениваться на мимолетные отношение. Секс без любви – это нормально, но вот отношения без любви меня пугают. Так что, да, пришлось немного побыть без них.

– И каково это?

– Ты действительно никогда не был один?

Веня отрицательно покачал головой. Он выглядел смущенным.

– Нет. А как оно?

– Преимущественно, печально, если поддаваться стереотипам системы, но есть свои плюсы. Например, поиски самости.

– Какой такой самости?

– Когда ты вне отношений не нужно циклиться на этих самых отношениях. Подстраиваться под кого-то, ждать одобрения и идти на постоянные компромиссы. Не нужно соответствовать чьей-то картине жизни. У тебя уйма времени, чтобы понять, кто ты, почему ты, и зачем ты. А стоит это осознать, начинаешь, к тому же, задумываться еще и о том, куда ты…

Вениамин задумчиво почесал бороду.

– Я не могу быть один. 

– Тогда ты никогда так и не узнаешь, кто ты.

– Мне с собой скучно и грустно. Это я знаю наверняка. Терпеть не могу свою компанию, а ты говоришь, что мне это нужно. Вот предположим, гипотетически я и так знаю, что я мудак. Конченный человек. Тогда зачем мне поиски этой твоей самости?

– Затем, что гипотетически ты такой именно из-за отсутствия поисков себя.

– Господи, тебя не переубедить. Хорошо, а если я себе не понравлюсь? 

– Это не важно. 

– Почему?

– Да потому, что к тому моменту ты уже будешь знать, кем ты хочешь быть, кем ты можешь стать, и что для этого нужно делать.

Жених взглянул на меня с недоверием, за которым, тем не менее, виднелись проблески интереса.

– И что потом, Васляева?

– А потом просто делать.

– Что-о-о делать?!

– Узнаешь, когда найдешь себя.

Веня откинулся на спинку кресла и задумчиво вздохнул.

– Ты мне сейчас мозг сломаешь, – признался он. – Как мне понять, что делать, если я не знаю, кто я? И что значит, зачем я и почему я? Почему что? Нет, я точно не могу быть один. Но теперь мне интересно, что все это значит, деточка? Ты же знаешь, я у тебя любопытный.

Он посмотрел на меня с просьбой во взгляде.

– Ну, хотя бы объясни, каково это жить без отношений? Тебя послушать, так это чуть ли не обязательно.

– Вроде того.

– Потому, что только так я смогу узнать, кто я и…эм… почему я?

– Правильно.

– Ну, так и что мне теперь делать, если я хочу это узнать, но не хочу и не могу быть один?

– Да это не так уж и сложно, – я улыбнулась. – Попробуй при случае.

