# &nbsp; {#chapter-18}

Есть у меня давняя подруга – Марта Ульянова. Она познакомилась со своим мужем за год до нашей встречи с Вениамином. Хотя и повстречались они во Львове, Семен был родом из Беларуси. Он никогда толком путешествовал, имел суицидально-агрессивные порывы на почве алкоголизма, отсутствие жизненных перспектив, послужной список принятых внутривенно веществ и не менее послужной список вариаций на тему самоубийства. У него не было хоть какого-нибудь опыта работы, образования, выдержки и одного глаза. При всем при этом, человеком Семен оказался, в общем-то, неплохим. Позже мы с ним даже подружились.

Так вот, рассказав мне о своих первых внеплановых отношениях, (которые к тому же были единственными) Марта ожидала услышать в моем голосе нотки разочарования.

– В глазах общества у меня самый хреновый мужик на свете, – заявила она.

И вышла замуж, когда они были знакомы всего два месяца. Процесс исцеления был долгим, не спорю, но по истечении нескольких лет Семен избавился от каждой из перечисленных выше характеристик. Ну, кроме отсутствия глаза.

В общем, услышав о моем внезапном, но очень серьезном (что делало его еще более внезапным) романе с Вениамином, первым делом Марта спросила:

– Вы принимали вместе ванну?

То есть, я рассказала ей о том, что Веня предложил мне руку и сердце и о том, что мне, по всей видимости, придется переехать в Крым. А ей были интересны совместные купания. Но я не слишком-то удивилась. Марта – она такой человек, который оценивает любые ситуации, основываясь исключительно на своих действиях, вкусах, планах и воспоминаниях. Все дело в том, что одним из первых счастливых воспоминаний Марты и ее мужа стало принятие ванны.

Чтоб вы понимали, природа наградила Марту быстрым умом, способным усваивать, анализировать и вырабатывать тонны информации. Она была экспертом по таймменеджменту и гордостью всех учебных заведений, в которых когда-либо училась. Все это выработало в ней комплекс отличницы, из-за чего Марта отказывалась собирать волосы в косу, даже когда те ей мешали. А том, что она втихоря носит очки, я вообще узнала спустя десять лет после нашего знакомства.

Мы ходили в одну школу, имели общие интересы и общих друзей, но никогда толком не общались. Я постоянно слышала ее фамилию в списках претендентов на получение разного рода грамот и дипломов. Марта же знала меня визуально.

*Такую девушку-вечеринку сложно не заметить*, позже сказала она.

Думаю, это продолжалось бы и дальше, если бы не события одного осеннего дня две тысячи шестого года.

В школе я всегда была чем-то средним между отличницей и троечницей. Как это вообще возможно? Секрет прост: я принципиально занималась лишь теми предметами, которые мне нравились и никогда ни у кого не списывала. Нравились мне языки и литература, искусство и многое другое. Зато математика во всех ее проявлениях стала мне более чем ненавистной. Это случилось благодаря экспериментальному классу, в который меня отдали в возрасте шести лет. Из-за этого последующие два года я имела по семь-восемь уроков математики каждый божий день, включая субботу. Таким образом, сменив школу, я читала книги на алгебре и писала собственные рассказы на геометрии.

Можно сказать, что эксперимент не удался. Если его целью не было пробуждение внутреннего гуманитария.

Так вот, по окончанию средней школы, мне нужно было написать несколько тестов по литературе и дополнить все это дело своим эссе. Это вроде как открывало передо мной перспективы бесплатного обучения в одном неплохом заведении, которое должно было дать мне корочку для поступления в ВУЗ – так считала моя учительница литературы. И после долгих уговоров ей удалось убедить меня написать мой первый текст на заказ.

Каково же было мое удивление, когда я увидела финальные списки претендентов. Там было сказано, что помимо меня чести удостоилась еще и некая Марта из параллельного класса. Но место было всего одно, и я никак не ожидала встретить конкуренцию на последнем этапе отбора.

*Нужно выяснить, что это за сучка*, подумала я.

Так я познакомилась со своей лучшей подругой, Мартой.

<div style="text-align: center;">***</div>

Близкое общение началось спустя четыре года, в институте, когда мне исполнилось шестнадцать. Тогда мы обе учились на факультете иностранной филологии. В те дни у Марты не было ни пирсинга, ни татуировок, ни черных волос, ни каре, ни, кстати говоря, сисек. Все это появилось спустя лет пять. Говоря же о наших студенческих деньках, Марта была очень стройной и носила длинные рыжие волосы. Невероятно красивые.

Расцвет этой дружбы как раз припал на пик моей необъяснимой тоски по шестидесятым. И глядя на то, как Марта – в ее свободных, извечно цветастых одеждах – дополняет что-то на лекциях и без конца тянет руку на семинарах, меня то и уносили флешбеки несуществующего прошлого. Какие-то отрывки воспоминаний о временах без Интернета, днях и ночах, которыми люди живут в настоящем и полностью поглощены этим процессом.

Танцы, палатки под звездным небом, песни у костра и очень много дороги – все это молниеносными волнами пролетало сквозь меня пока я в очередной раз наблюдала за тем, как подруга рассказывает что-то скучающей аудитории. Погрузиться в картинку полноценно мне не удавалось, (или тогда я просто еще не умела этого делать) и я просто восторженно наблюдала за этими едва уловимыми всплесками сознания, стараясь хоть что-то сохранить в памяти.

Лишь один эпизод мне удалось запомнить более-менее детально. Дело было в каком-то лесу. Нас окружали высокие хвойные деревья, чьи верхушки, должно быть, касались неба. Где-то за ними скрывалось солнце, и мы долго шли по хрустящим веткам пока, наконец, не добрались до какого-то холма. Сперва до моих ушей еще доносился гул дороги, но вскоре он исчез. Здесь было пленительно спокойно. Даже птицы молчали. Тишину нарушало лишь парящее в воздухе пение.

*Here comes the sun*

Я прекрасно знала слова потому, что сама их пела.

*Here comes the sun*

*And I say, it's all right*

На возвышении лежало старое дерево, а сквозь его ствол струились солнечные лучи, яркими стрелами пронзая завесу лесного дыма. Марта стремительно побежала вверх по склону.

– Там внизу поляна! – крикнула она.

Цветастые юбки мелькнули над упавшим деревом, и подруга исчезла из моего поля зрения.

Я поспешила за ней, но, поднявшись на холм, решила задержаться. Уселась на ствол и принялась внимательно разглядывать открывшийся отсюда вид: глухую лесную стену, ярко освещенную поляну и Марту, с широко разведенными руками кружащуюся на зеленой-зеленой траве. Рыжина ее волос подыгрывала в такт солнцу, но что-то в этой идеальной картинке показалось мне странным.

Ее волосы! Они были раза в три короче.

– Когда ты подстригла волосы? – спросила я на спуске с холма.

Должно быть, я выглядела странно. Подруга взглянула на меня как на лунатика и продолжила танцевать. Тогда я поймала ее руку и повторила свой вопрос.

– О чем ты говоришь? – с улыбкой спросила Марта. – Они только-только отрасли. На лучше курни. Видок у тебя странный!

Она протянула мне трубку, но курнуть я не решилась. Голова раскалывалась, лесная картинка шла кругом, а девушка передо мной раздвоилась: одна Марта, с волосами ниже плеч, по-прежнему стояла посреди поляны, вторая, с волосами до талии, взялась непойми откуда. Обе подпирали руками бока и смотрели на меня с неприкрытой тревогой.

– Лиза, с тобой все в порядке? – спросила лесная Марта.

– Лиза, с тобой все в порядке? – спросила Марта с волосами до талии.

Голос последней звучал издали. Игнорируя головную боль, я сосредоточилась на второй Марте, и вскоре обнаружила, что та находится в пустой аудитории. Позади девушки виднелся пустой экран проектора, а передо мной лежала открытая тетрадь, но вместо конспекта под сегодняшней датой 26.09.2010 виднелась надпись:

_**Hic Sol Venit**_

Рядом был набросок крохотной елки.

– Лиза?

Происходящее обескураживало, и мне понадобилось какое-то время, чтобы вспомнить, что Лиза – это я.

– Лиза, ты на связи? Прием.

– Прием-прием, – наконец, ответила я, и поднялась со своего места. – Пара давно закончилась?

– Минут пять назад. У тебя все в порядке?

– Да, просто уснула.

– Но я видела, ты сидела с открытыми глазами!

Я отмахнулась.

– Мне такое уже говорили. Иногда я сплю с открытыми глазами, когда сильно устаю.

– Ничего себе вот это у человека бессонница! – восхитилась Марта.

Она продолжила укладывать канцелярию в сумку.

– А что за пара хоть была? – как бы невзначай поинтересовалась я прежде, чем последовать ее примеру.

– Латынь, а что?

– Да ниче. Одолжишь конспект на вечерок?

<div style="text-align: center;">***</div>

Марте о своих флешбеках я, конечно же, ничего не говорила. Пару раз та ловила мой взгляд и, видимо, решала, что я в восторге от ее знаний, потому как начинала говорить еще громче и серьезней.

Мне было все равно, что этих воспоминаний никогда не существовало в нашей Вселенной. Просто не могло существовать, ведь я родилась слишком поздно. Да и запомнить большинство таких флешбеков не делалось возможным, но их атмосфера – ощущение покоя и счастья нахождения на своем месте – никак не хотела забываться.

*Я так когда-нибудь суициднусь*, подумалось мне после очередного припадка. *Очнусь, обнаружу, что все это неправда и суициднусь. Точно-точно.*

И я решила, что однажды я обязательно верну шестидесятые. Ну, если не суициднусь.

<div style="text-align: center;">***</div>

Как-то в конце сентября мы возвращались домой. На остановку с нами шла еще одна девочка – Алена. Это была школьная подруга Марты.

– По ночам я тихонько подкрадываюсь к своему братику, – говорила Алена, – и дырявлю ему палец своим острым ногтем. Потом присасываюсь и пью кровь пока родители не придут с работы…

Она еще долго рассказывала истории вроде этой, а я разрывалась между желанием включить диктофон и порывом орнуть в голосину. Ведомая этими эквивалентными чувствами, я посмотрела на Марту. Как и всегда, вид у нее был очень серьезный.

На протяжении всего пути Алена продолжала рассказывать свои неадекватные истории. Затем, наконец, увидела свою маршрутку и помчалась в ее сторону.

– Как же мне осточертели эти люди.

Я едва сдерживала улыбку.

– Мне тоже, – поддержала меня Марта.

– У тебя есть друзья?

Она призадумалась.

– Нет. Думаю, нет.

– Почему?

Марта пожала плечами, а затем указала на отдаляющуюся от нас Алену.

– Вот, наверное, поэтому.

– Ну, так давай дружить! – я протянула ей руку.

– А давай!

И мы действительно стали друзьями. Вот так вот просто, по обоюдному согласию. Как в каком-нибудь старом фильме. И вот, спустя шесть лет я позвонила в Волковыск, рассказала Марте о своем женихе, а та спросила:

– Вы принимали вместе ванну?

К тому моменту она уже успела посетить уйму стран, переехать в Беларусь, обзавестись мужем, татуировками и обширным опытом принятия различных веществ. Кое в чем я тоже не отставала.

– Так точно! – отчиталась я.

В первые дни знакомства мы действительно купались вместе. Ванна была маленькой, а вот я – не очень. Вениамин же был стройным, но высоким. Каким-то чудом мы, все-таки, поместились в крохотную ванную, да так, что в ней даже оставалось место.

– Ты так приятно пахнешь, – произнес мой мужчина, обнимая меня сзади.

– Жаль, не могу сказать того же.

И мы рассмеялись.

Вся ванна была наполнена пеной. Кран оставался открытым, и скорее пена начала вываливаться за пределы ванны. Она напоминала огромные хлопья снега, которые как по волшебству перенеслись в этот жаркий предлетний день. У меня есть фотография этого феерического момента. К счастью, ее мало кто видел, но должна признать: я никогда прежде не была замечена с такой детской улыбкой.

Покончив с водными процедурами, мы принялись плескаться водой, бросая друг в друга остатки пены. Единственной вещью, которую Вениамин никогда не снимал, были деревянные бусы, купленные им у одного этнического старца, ежедневно расхаживающего по набережной Севастополя. Мой возлюбленный бесился с такой силой, что эти бусы то и дело подлетали, цепляясь за его нос. Низ его лица превратился в сплошную пену, благодаря чему Веня напоминал мальчишку, который измазался мылом, пытаясь сделать себе искусственную бороду. Думается, сейчас, до кончика волос измазанный пеной для ванны и улыбаясь во все зубы, он и был мальчишкой.

– Странно… – начала я.

Мы уже выпустили воду из ванной. Веня смывал бальзам с моих волос. Я сидела под стенкой, обхватив руками колени.

– Что?

– Такое непривычное чувство.

– Что за чувство?

– Кажется, я счастлива. Даже припомнить не могу, когда я в последний раз была счастливой и чувствовала себя так… – я замолчала, пытаясь подобрать верное слово.

Перед глазами всплывали картины раннего детства.

– Как?

– Так спокойно.

Не сводя взгляда друг с друга, мы на какое-то время забыли о разговорах, наслаждаясь долгожданным спокойствием.

– Ну, а что насчет тебя? – наконец, спросила я. – Ты-то когда в последний раз чувствовал себя счастливым.

– До встречи с тобой?

Я кивнула.

– Почти уверен, что никогда.


