# &nbsp; {#chapter-23}

Он был тем самым молодым человеком, подходящим моему правилу трех «п» – преданный своему делу, полон жизни и похотливый. Признаться, я влюбилась в его голос еще до того, как увидела самого Адама. 

Миновав поле, поезд заехал на акведук. По обе стороны простирался Днепр. Я мечтательно любовалась извилистыми линиями на воде, оставленными после небольших волн и поражалась тому, с какой красотой в них играют солнечные блики. 

Отдавала ли я себе отчёт в том, что бывала счастлива лишь когда мое сердце переполняла любовью и любая из ее производных? Думаю нет, но я искренне верила, что это и есть настоящее счастье. Вдоволь насмотревшись на проносящиеся за окном поля, леса, долины и озера, я взгромоздила на колени огромную записную книгу и принялась писать. Вместо ожидаемого очерка из-под моей руки вышло сентиментальное письмо, занявшее три с половиной листа. Его я вручила своей подруге и попросила показать мне лишь в том случае, если я сама об этом попрошу.

*Здравствуй, милая моя!*

*Этой ночью я практически не спала, волнение было столь сильным, что у меня (впервые в жизни!) тряслись коленки. Однако, утром меня охватило странное спокойствие и сейчас, сидя за этим письмом в поезде, я все так же спокойна.*

*Только что осознала, что, зайдя в вагон, почувствовала, что вернулась домой. Все поезда для меня одинаковы и в каждом я ощущаю себя дома. Подумать только, сколько эмоций я пережила за эти двадцать лет, находясь в дороге. У меня так много воспоминаний, но я знаю одно: я никогда еще не была так спокойна и счастлива как сейчас.*

*В моем городе невыносимый холод и совершенно отсутствует золотая осень, чего не скажешь о местах, которые видны из окна. Слева замерзшее поле, а по правую сторону раскинулся лес. Он невероятно прекрасен. Кое-где мелькают небольшие домики – это то, о чем я мечтаю, милая. Все эти осенние цвета, я так влюблена в них, приятный холод и шуршание листьев… вся моя жизнь прошла бы осенью, будь это возможно. *

*Снова-таки, впервые в жизнь, я чувствую, что встретила того самого и это изменило меня, сделала той, кем мне стоило бы быть. *

*Странно, что мне пришло это в голову, но мне весьма нравятся мои короткие волосы (хотя, кто-то бы их таковыми не назвал), это так удобно, а главное – они такие живые, ведь я уже почти избавилась от всех испорченных волос. *

*Как видишь, мои мысли – бесконечно хаотичны. Пожалуй, это единственное, что меня огорчает, ведь в наушниках любимая музыка и я думаю о тебе, о нашей дружбе и о том, что, наконец, увижу тебя, ведь ты мой дорогой друг и я безумно тебя люблю, не забывай об этом.*

*Только что выяснила, что курить в поезде уже совсем нельзя. Очень жаль, ведь, зная свою удачу, я обещала Адаму не сходить на перрон до Москвы. Увидев мой трагический взгляд, проводник дала мне вафель. Черт возьми, я перечитала предыдущее предложение и просто не могу остановить смех, шикарно. Я даже не буду его убирать, надеюсь, ты улыбнешься, прочитав это. Хорошее предложение, такое можно диктовать деткам в школе, как пример сложноподчиненного, чертовски смешно. *

*Очень хочется курить, но еще больше мне хочется обнять своего избранника, поэтому я здесь.*

*Знаю, тебе сложно в это поверить, но я ни разу не чувствовала того, что чувствую сейчас к нему. И это чудесно. *

*P.S. Ох, я, все же, не удержалась и пару часов назад вышла прогуляться. Удивительное место, названия которого я не запомнила, станция находится прямо около леса и невероятная осенняя погода: свежий ветер, нежаркое солнце, а вокруг – сплошная осень. Сейчас я проезжаю места, подобные тому, но погода здесь уже не так дружелюбна. Представляю, что ждет меня в Москве, но главное ведь, кто ждет меня там, правда? *

*Бывает ведь так, я еще не разу не видела его, но уже безумно влюблена и очень тоскую хотя бы по тому, что не могу слышать его голос. *

*B вагоне шумно, а я так устала, чувствую себя невероятно вымотанной, это и не удивительно.  И все же, меня весьма удивляет, что я совсем не волнуюсь, думаю, я начну переживать в самый  последний момент, хотя  я знаю, все в порядке, все в абсолютном полном порядке. *

*Возвращаю свое внимание книге. Не стану окончательно с тобой прощаться, ведь мы с тобой совсем скоро встретимся. Подумать только, спустя несколько часов я его увижу…  и это делает меня счастливой. *

*Всего хорошего, милая.*

*Твой верный друг, *

*Васляева*

<div style="text-align: center;">***</div>

Наконец, день сменился вечером, а за ним подкралась долгожданная ночь. Пассажиры уже давно отдыхали на своих полках, наполняя плацкарт храпом всех видов и размеров. Мы как раз подъезжали к белорусской границе. За стеклом проносились черные силуэты деревьев растущих здесь лесов, напоминая о детстве и о традиционных летних поездках в Черниговскую область. О лесе и прилегающему к нему хутору, о ежедневных походах за грибами, о дальней родственнице-тезке, которая была мне как родная бабушка, о дедушке, который на самом деле не был мне родственником. Но все же, о дедушке с его самокрутками, печкой-лежанкой и мастерски написанными стихотворениями, их собаках, самодельном пруде, деревянной беседке посреди дикого озера, огромном дубе, растущим за участком, песчаных карьерах, вафельных тортах и термосе с кофе, которые мы с кузеном утаскивали на плот прежде, чем уплыть вглубь озера. 

*С кофой* – так говорила бабушка Лиза.

Воспоминания одно за одним проносились перед моими глазами. Подложив руки под голову, я укуталась в одеяло и прикипела глазами к незашторенному окну, мечтательно глядя на звёзды.

В январе в моей голове зародилась идея нового романа. Мысль о нем я вывешивала без малого девять месяцев и лишь в сентябре начала делать первые заметки. Книга была о Луне и относилась к научной фантастике, чего нельзя было сказать ни об одной из моих прошлых работ, ни о моих литературных вкусах в целом. И, все-таки, мне она нравилась. Я даже как-то по-матерински полюбила эту книгу и теперь, разглядывая звезды, думала о том, как расскажу о ней Адаму. Этот монолог раз десять успел пронестись в моих мыслях прежде чем я, наконец, уснула.

Наступило утро. Взволнованная я проснулась часа на полтора раньше будильника. До Москвы оставалось более двух часов езды, и я знала, что сейчас Адам по-прежнему дрыхнет в своей постели. Мысль об этом на мгновение наполнила меня пока ещё ничем не обоснованной радостью, как всегда происходило со мной в моменты предвкушения чего-то хорошего, а главное – долгожданного.

<div style="text-align: center;">***</div>

– Я устала от отношений, – с уверенностью заявляла я в свои неполные двадцать лет. – Просто хочу чего-то приятного. Совместных прогулок, вечернего распития вина, походов в кино и поцелуев в пустом переулке. Положительных эмоций мне! И душевного тепла подайте. Как в книгах Ремарка и Хемингуэя, что тут сложного? Хочу всепоглощающего романа, который не продлится дольше двух недель. Чтобы потом не нужно расхлебывать все это пост-любовное дерьмо. Пускай будет волшебство, а потом пускай его не будет. Мне бы только нужных эмоций да вдохновения...

Говоря это, я действительно верила, что желания мои были далеки от долгосрочных отношений. Все, что я делала прежде, так это необдуманно скакала из одних длительных отношений в другие, стараясь забыть первую школьную любовь. В какой-то момент мне это даже удалось, но я почему-то продолжила встречаться с теми, кого не любила. Наверное, по инерции. Думаю, таким образом мое подсознание пыталось защитить меня от перспективы разбитого сердца, ведь я ничего не чувствовала по отношению к тем парням, а значит они не могли причинить мне боль. К тому же, все это создавало иллюзию отсутствия одиночества. Хотя что может быть хуже, чем отдавать себя не тем людям?

Так длилось около четырех лет. Когда мне стукнуло девятнадцать, я поняла, что окончательно излечилась от Эрика головного мозга. Ещё я поняла, что была глубоко несчастна. Конечно, есть вещи и похуже того, чтобы просыпаться рядом с нелюбимым человеком, но и в этом приятного мало. Словом, обнаружив себя на тонущем корабле односторонних отношений, я их прекратила.

И осталась одна. Дышать стало неописуемо легче. Тут же отпала нужда в том, чтобы посвящать время тому, кого не очень-то горишь желанием видеть. Рядом с собой или вообще. Отпала потребность идти на уступки другому человеку и заниматься тем, чем заниматься вовсе не хочешь. Наконец-то, я могла спокойно писать. Тогда я поняла, что больше никогда не стану строить отношения с нелюбимым человеком. Одиночество меня совсем не пугало. Я даже успела по нему соскучиться и решила, что лучше буду одна, нежели опять стану тратить своё время и энергию на неправильного человека. О таких обычно говорят, что он герой не твоего романа. Это выражение можно было применить к каждому из моих бывших. К тому же, даже в отношениях можно быть самым одиноким.

Распрощавшись со странными, ненужными и непонятными отношениями, я углубилась в работу. Помимо писательства у меня было ещё два менее любимых, но более оплачиваемых дела – я работала IT-шником и давала уроки английского. Большая часть весны и целое лето прошли в работе и раздумьях. Я старалась разобраться в себе пока последней ночью августа две тысячи тринадцатого не поняла природу всех (ну или хотя бы большинства) своих жизненных ошибок и осознала, что готова идти дальше.

Той же ночью Адам признался, что запал на меня. Мы вели переписку около года и он никогда прежде не видел меня, если не считать фотографий и видео-звонков. Мне нравилась его музыка и постоянное желание дискуссий. Зачастую это была лишь приятная болтовня о погоде, искусстве и том как у кого дела пока однажды, последней ночью лета того года, мы не завели разговор по душам.

Адаму было двадцать пять и незадолго до этого он потерял отца.

– Я устала от серьёзных отношений. Эта фигня себя не оправдывает. Теперь мне просто хочется отдохнуть и посвятить время поискам самости.

– А я хочу серьёзных отношений, – не прекращая повторял Адам. – Хочу найти девушку на который однажды решу жениться. Можно сказать, я вообще не ищу девушку. Я ищу сразу жену.

Он говорил, что устал от одиночества и считал, что готов завести семью. Наверное, как и каждый одинокий человек, которому стукнула четверть века.

– Как знаешь, – ответила я, когда монолог Адама о радостях семейной жизни был окончен. 

Мне никогда прежде не хотелось выйти замуж и я никогда не воображала деталей своей свадьбы или того, как я буду идти по церковному проходу с букетом в руках. 

– Я все равно предпочту остаться в стороне.

Адам, конечно же, возражал. Между нами были две тысячи километров и парочка разногласий, которые каждый пытался решить своим путём. Адам рассказывал мне о своей музыке и много спрашивал о моих книгах. Я слушала его и незаметно влюблялась, наивно продолжая полагать, что не хочу ничего кроме коротенького романа.

Месяц и неделя прошли как-то странно. Они тянулись вечность, а вместе с тем умудрились пролететь за один день. И вот я стояла у наглухо закрытого окна в конце вагона и смотрела на стремительно приближающуюся ко мне столицу соседней страны.


