# &nbsp; {#chapter-24}

Вы когда-нибудь просыпались в переполненном купе от криков незнакомого младенца, от неожиданности решив, что он ваш, проспав при этом часа три, а затем пытались принять душ в отечественном поезде, (где ванной и вовсе нет) движущемся по еще более отечественным дорогам, уложить волосы и нанести первоклассный макияж? Если так, вы должны понимать, на что мне пришлось пойти ради этого мужчины.

Искусно скрыв хронические мешки под глазами, и сделав вид, что именно такой цветущей и посвежевшей я сегодня и проснулась, я подхватила свой чемодан и неспешно зашагала к выходу. В те дни я носила чёрные волосы с холодным, синим отливом. Они спускались чуть ниже плеч и игриво завивались на концах. Я всегда предпочитала пробор не по центру, так что передние локоны слегка закрывали левую половину лица. Одежду я носила в тон волосам – черное платье, черное пальто, черное белье, черные чулки, шляпа и, конечно же, черные сапоги. Еще у меня был парфюм с запахом лаванды и пирсинг над верхней губой. Благодаря постоянным отбеливающим маскам от природы смуглая кожа к тому времени стала почти фарфоровой, и я чувствовала себя прекрасно. 

Единственное недоразумение представлял собой чемодан, что по незамысловатым обстоятельствам оказался ярко розовым. Мой (чёрный, понятное дело) сломался незадолго до поездки, а единственным который Марта смогла мне одолжить, был этот. Что ж, розовый чемодан вызывал во мне некую неуверенность, но я поспешила принять вид, словно это абсолютно меня не смущало. Удивительно, насколько важной кажется подобная херня в юном возрасте, правда? Спустя пару лет я буду спокойно выходить в магазин в берцах и халате.

Дверь поезда распахнулось. В лицо ударил приятный утренний холод. Свежий осенний воздух приятно обволакивал, навевая целую стопку воспоминаний.

Я выросла около железной дороги. Засыпала, слушая шум отбывающих поездов и голос диктора, объявляющего новые. Толком не знаю почему, но я всегда любила железнодорожные вокзалы по утрам. Вероятно, это было связано с моими детскими разъездами по стране и тем, какие эмоции охватывали меня в предвкушении этих поездок. В такую рань большинство детей спали на руках родителей. Я же энергично прогуливалось вдоль перрона, жадно впитывая царившую на вокзале атмосферу. Вдыхала запахи железной дороги, наслаждалась тишиной и ожидала прибытия поезда.

Лишь с лихвой вдохнув утренний воздух, я взглянула на перрон. Адам стоял в толпе встречающих. Теперь между нами были от силы пять метров. Как я и, он был одет неожиданно легко для такой погоды. И, все же, он был здесь. Стоял совсем близко и улыбался мне счастливой, немного смущенной улыбкой, открывающей ямочки на щеках.

Не отрывая взглядов, мы смотрели друг на друга секунд десять, прежде чем я вспомнила, что преграждаю путь другим пассажирам. Опомнилась, опустила глаза, и заметила, что последняя ступенька подо мной слишком высокая, дабы с неё можно было спокойно сойти. В руках у меня был огромный чемодан, 

*Сраный розовый чемодан!*

а на ногах красовались каблуки. Зная о прелестях местного транспорта, я, все же, как-то упустила этот момент и теперь с тревогой, но не без улыбки, вообразила, каким эффектным может стать мое появление.

В конце концов, в узких кругах я была известна именно благодаря таким представлениям. От этих мыслей мне вдруг захотелось громко рассмеяться. И застрелиться.

Тем временем Адам уже шёл навстречу. Он мужественно пытался пробраться сквозь толпу встречавших, но по-прежнему был недостаточно близко, чтобы мне помочь. Пассажиры за моей спиной уже начинали рассерженно толкать друг друга, когда произошло чудо. Пожилой проводник, стоявший около поезда, внезапно взял мой багаж одной рукой. Второй он подхватил меня за талию и буквально спустил на землю вместе с чемоданом.

– Спасибо, – удивленно произнесла я. 

Проводник молча подмигнул мне и вернулся на исходную.

Я сделала несколько шагов в обход толпы, стараясь принять безразличный вид, когда лицом к лицу столкнулась с Адамом.

– Ну, здравствуй, – улыбнулся он.

– Здравствуй, – ответила я, уткнувшись носом в плечо Адама потому, что к тому моменту он уже крепко обнимал меня.

В отличии от меня, Адам и не пытался скрывать свои чувства. Он заметно покраснел и неловко выпустил меня из объятий. Зрачки его расширились, что только придавало красоты этим карим глазам.

– Привет, – ещё раз поздоровался Адам.

– Привет, – глупо повторила я.

Молодой человек предложил взять его под руку, что я и сделала, вручив ему свой чемодан. Мы поспешно зашагали прочь от перрона.

Киевский вокзал оказался чересчур оживленным местом. Почти таким же оживленным, как и сама Москва. Чем дальше мы отдалялись от железной дороги, тем больше становились толпы окружавших нас людей. Павильон кишел суетливыми, спешившими во все стороны гражданами.

Мы остановились на перекур, хотя скорее это был лишь предлог для того, чтобы лучше рассмотреть друг друга. Поднеся к губам сигарету, я с облегчением облокотилась на стену, впервые заметив какие высокие здесь потолки.

Увлеченные собственным обществом, мы поговорили о погоде, о том, как плохо этой ночью спалось каждому из нас и еще какой-то ерунде.

– Я часа три не мог уснуть, – признался Адам.

– А я и не пыталась.

– Испугался даже, что просплю. А потом встал раньше будильника.

У него был этот быстрый московский акцент, который так портит женщин и так идет мужчинам. Как и все москвичи, Адам, конечно же, полагал, что разговаривает с единственно правильным произношением. При этом он искренне умилялся моему южному акценту.

Сворачивая в сторону парковки, я впервые с удивлением осознала, что вскоре останусь наедине с по сути незнакомым мне человеком. Буду не один час, а вероятно и не один день находится рядом с мужчиной, которого я никогда прежде не видела. Странно, но эта мысль ничуть не пугала.

Мой спутник настоял на том, чтобы я пристегнулась. Он вел свой черный «Мерс» конца 90-х спокойно и сдержанно, не отрывая взгляда от дороги. Ехали мы часа полтора и это с учетом того, что тем утром практически не было пробок. Лишь останавливаясь на светофоре, Адам отводил взгляд от дороги, чтобы одарить меня полной нежности улыбкой. Где-то на половине пути мы угодили в небольшую пробку, и я поймала Адама на том, что он пялится на мои ноги. Я, и обе моих нижних конечности были мысленно польщены этим вниманием, но, приличия ради, я, все-таки, одарила Адама скептическим взглядом. Мужчина тут же покраснел и виновато улыбнулся, явив миру те самые очаровательные ямочки на щеках.

