# &nbsp; {#chapter-28}

– Взгляни на это! – возбужденно воскликнула я, наблюдая невиданных размеров солнце, что стремилось к небосводу.

– Все это, конечно, чудесно, но нам нужно в аптеку, – напомнил Веня, пристыженно поглядывая на мой глаз.

Должна сказать, последний и впрямь был представлен не в лучшем свете. За десять минут до этого мой женишок в порыве страсти не смог совладать с собственными силами и нечаянно спустил прямиков мне в око. Он проделал это с точностью, достойной зависти оперативника, так что теперь глаз покраснел и невероятно опух. Что еще хуже, из него постоянно текли слезы. Я толком ничего не видела этим глазом. Для тех, чей зрительный орган ни разу не контактировал со спермой, замечу, что чувство это наиприятнейшее. Однажды навстречу мне дул яростный ветер, и кусочек горящей сигаретной головки занесло все в тот же многострадальный глаз. Нынешняя боль отдаленно напоминала тот ожог, только вот чувствовалось это так, словно весь минувший день Вениамин накапливал не сперму, а настоящую кислоту.

	*Что говорить о мужчинах, если даже их семя настолько разрушительное?*

Сперва мы оба хохотали над ситуацией, – ох, это прекрасное пятисекундное неведение – а затем меня настигла неописуемая боль. Глаз стремительно начал опухать. Вот вам еще одно доказательство того, что мужчины – ядовитые создания. Осознав плачевность сложившихся обстоятельств, Веня спохватился и позвонил Валерчику, чья девушка работала медсестрой. После неизбежной минутки смеха нас снарядили списком жидкостей, названия которых я благополучно забыла, как только глаз перестал печь. И вот, мы уже были в нескольких метрах от торгового центра. 

На улице стояла внезапная прохлада, более характерная для середины осени. На мне был плащ Вениамина и куча другой, спонтанно попавшейся под руку одежды. При этом я, кажется, впервые за долгое время выскочила на улицу без макияжа и прочих сопутствующих прихорашиванию штук. Пострадавшим глазом оказался левый. Это было не так уж и плохо потому, что я по-прежнему носила косой пробор и ниспадающие на лицо пряди находились как раз таки с левой стороны. 

Несмотря на начинавшую набирать обороты боль, на моих губах играла улыбка. Словом, я не теряла бодрого настроя и даже успела умилиться огромному солнечному диску, застывшему над нашими головами.

– Прости глупого Веньку, – в который раз повторил мой любимый.

Особой нужды в извинениях не было, но с того дня Вениамин навсегда сделался для меня просто Венькой. Конечно, были еще Венечка, Веня, и на худой конец даже Венюша, но именно эта ласкательно-уменьшительная форма имени показалась мне самой теплой. Сама не знаю, почему.

Внутренне разрываясь между состоянием крайней неловкости и желанием засмеяться на все помещение, мы вошли в аптеку. Веня что-то рассказывал фармацевту, подкрепляя это полученным накануне списком лекарств. Я стояла в сторонке, усердно имитируя неслыханный доселе интерес к детскому питанию.

– А что с глазом? – раскатистым басом спросил аптекарь.

Он произнес это настолько громко, что в нашу сторону уже смотрело большинство покупателей, стоявших на кассах напротив аптеки. Было как-то неловко. Я повернулась спиной к посторонним и приподняла волосы, демонстрируя боевую рану. Увидев ее, фармацевт деловито прищурил глаза. Он резко повернулся к Вене и одарил моего мужчину до неприличия недоверчивым взглядом.

– Аллергия или инфекция? – продолжил спрашивать мужчина.

Мы ответили секунда в секунду.

– Аллергия, – с каменным лицом сказала я.

– Инфекция, – не менее серьезно сказал Вениамин.

По всей видимости, наш фармацевт перечитал криминальных сводок. В частности тех, в которых рассказывается о домашнем насилии. Не веря ни единому слову Вени, мужчина продолжал задавать какие-то неуместные вопросы. 

Тем временем глаз продолжал печь. Покраснение также росло в размерах. 

– Дайте уже эти хреновы капли! – вспылил Вениамин, увидев, как на моем лице проступает страдальческая гримаса времен Данте.

Он стукнул кулаком по прилавку, что, наконец, подтолкнуло продавца к единственно правильному действию. Через пару секунд я уже заливала глаз каплями. К тому моменту как мы добрались до парковки боль начала притупляться, и окрыленная этим, я снова принялась любоваться солнцем. Порой у меня такое чувство, что большую часть жизни я именно этим и занимаюсь. Зависаю в моменте, впитываю каждую его деталь, а затем выкладываю увиденное на бумаге. Не самый плохой вариант, на самом деле.

– Он явно подумал, что я бью тебя, – сказал Веня, когда мы оказались наедине. 

– Мне тоже так показалось, – я улыбнулась. – Пожалуй, наши БДСМ-ные игры не в счет?

– Пожалуй, что нет.

И мы принялись обмениваться сопутствующими теме шутками, что одна за другой слетали с губ.

– Ты знаешь, – произнес Веня немного погодя. – А ведь моя бывшая рассказывала нашим знакомым, что я ее избиваю.

– Ты это уже говорил.

– Да, но этот противный мужик в аптеке… От него мне стало как-то не по себе. Ты видела, как он на меня смотрел? Да он был уверен, что это я тебя ударил! И как ему такое только в голову пришло? Чтобы я бил свою деточку – это, блядь, невообразимо! – он резко притормозил посреди улицы. – Какого хрена вообще? Какого хрена вообще он позволил себе так на нас смотреть, Лиза?! Знаешь что! Сейчас я вернусь. Ты стой здесь, а я сейчас вернусь и скажу ему все, что думаю!

Никогда прежде я не видела жениха таким разъяренным, но тесный контакт с различными психами, одним из которых являлась и я сама, научили меня правильному поведению в подобных ситуациях.

*Tiefe Wasser sind nicht still*, напомнил внутренний голос.

*Ой, так вы у нас из Германии!*

Я знала, что делать, дабы избежать конфликта. Нужно было всего лишь отвлечь Вениамина, переключить его внимание на другую тему, и я как бы невзначай спросила:

– Так и что эти друзья, они верили твоей бывшей?

Мужчина пожал плечами.

– Некоторые верили. Только в самом начале. Затем и они прекратили.

– У нее были синяки?

Вениамин взглянул на меня с удивлением.

– Конечно, не было!

– Тогда я не понимаю.

– Я тоже. Как-то раз она пришла в гости к моим друзьям и принялась рассказывать им, что я колотил ее всю ночь. Я в это время был на балконе и толком не слышал, что она говорит. Но в тот же вечер мне об этом рассказали. И рассказали это именно потому, что никто ей не поверил.

Затем Вениамин сказал, что подобное поведение длилось около года. Я показательно вздохнула, обдумывая услышанное.

– Жертв насилия всегда очень легко опознать. Особенно если речь идет о домашних побоях. Ты знаешь, меня удивляет даже не то, что она врала о тебе такие гадости, а то, что она продолжала при этом с тобой жить.

Веня не нашел, что на это ответить. 

Вскоре он забыл о желании поговорить с аптекарем, и мое внимание опять переключилось на небесные красоты. Через дорогу от нас находился детский городок, а рядом тянулась широкая дорога, что спиралью поднималась вверх, уводя автомобили в центр города. На возвышенностях по обе стороны трассы виднелись небольшие домики. За ними то и садилось солнце. Небо сделалось ярко розовым. Лишь кое-где мелькали лиловые просветы. Я смотрела на немыслимых размеров солнечный диск, на деревья, крыши и фонари. Смотрела и как никогда ярко осознавала, как же сильно я люблю этот раскинувшийся в горах городок. 

Все это вдруг напомнило мне о старых добрых временах. О тех днях, когда у меня еще была Мишель, которую даже после разрыва продолжала считать своим самым лучшим другом. Возможно, даже единственным. 

<div style="text-align: center;">***</div>

Это были первые недели две тысячи четырнадцатого года. Над городом и за его пределами стояла холодная зима. Кучи блестящего, никем не тронутого снега обволакивали загородную трассу со всех сторон. Миновав блокпост, установленный тут с осени прошлого года, – именно тогда конфликт Украины с одной близлежащей страной стал наиболее явным – мы выехали на извечно пустующую в это время года трассу. Справа поворот на Одессу, слева – моя дача и соседствующий с ней загородный домик подруги. Туда мы и направлялись. 

Не прошло и трех месяцев после расставания с Адамом, отчего я чувствовала необратимую печаль каждый божий день. Наверное, это нормально, когда тебе всего двадцать, но мое сердце болело, подкрепленное душевным расстройством, о наличии которого я к тому моменту не имела ни малейшего понятия. Внезапно для всех я превратилась в одновременно очень печального и очень веселого человека. И чем печальнее я себя чувствовала, тем энергичнее я становилась. Как все бывшие возлюбленные и кем-то брошенные люди, сидя в компании, я постоянно перебивала кого-то на полуслове для того, чтобы с несчастным видом сказать:

– Такой же одеколон был у Адама!

– Такая же погода стояла, когда мы встретились!

– Эта музыка играла, когда он впервые поцеловал меня!

– Именно этот виски мы и пили той ночью!

И так далее и тому подобное по списку. Никогда бы не подумала, что умею быть такой абсурдно грустной. Апогеем стало мой отказ смотреть «Идальго» потому, что однажды на Адаме были те самые трусы с лошадками. Видимо, очень памятные моему переживающему не лучшие времена сердцу. 

Обычно после парочки таких заявлений я погружалась в молчание. После чего вскакивала из-за стола или с любого другого места, в котором я находилась, и принималась сходить с ума. Петь песни посреди пешеходного перехода, отплясывать на барной стойке, прыгать с разгона в кусты и творить еще целую кучу вещей, которыми обычно занимаются наркоманы и прочие нетрезвенники. 

Вот только я была трезвой.

Конечно же, все эти шалости сопровождались неиссякаемым запасом шуток, за которые друзья меня обожали. Ну, что я могу сказать? Каждый по-разному переживает депрессию.

И вот, на пути к дому Миши, мне в очередной раз сделалось тоскливо. То ли небо было того же оттенка, что и на третий день наших отношений с Адамом, то ли ветер также дул с запада, я уже толком и не помню. Но помню, что от этих мыслей природа за окном вдруг стала серой и совсем непривлекательной. Как и моя жизнь. 

Утопая в этой бесперспективности бытия, я сделала музыку громче.

Мы обсуждали любимые сериалы и пели малоизвестные песни Битлз на протяжении всего пути. Где-то там впереди, за облысевшими ветвями деревьев начинало опускаться солнце. Это был ярко оранжевый диск громадных размеров, который, по мере нашего приближения, делался все больше и ярче. Я опустила окно и подкурила сигарету. Мишель тем временем напевала ту самую песню, из-за которой получила свое прозвище. 

Я взглянула на свою подругу, ее зеленые глаза и пухлые пальцы, то и дело барабанящие по рулю в такт музыке. Взглянула и подумала, как же здорово, что она есть в моей жизни. Большинство моих знакомых имели огромные круги общения. Я же могла похвастаться таким количеством друзей, разве что, в школьные годы. Со временем рамки моего доверия стремительно сужались и, в итоге, я поняла, что доверять стоит лишь паре-тройке человек. Однажды, еще когда я только готовилась к выпускному классу, Эрик сказал мне, что друг может быть только один. Остальные это просто знакомые. Теперь же я начинала понимать, что в этом вопросе предмет моих школьных грез не был далек от правды.

*И, все-таки, хорошо, когда у тебя есть всего один, но очень близкий и любимый друг, который не то, что тебя с полуслова понимает, а иногда словно сам вкладывает тебе в голову эти самые слова*, думала я. 

Потому, что в моменты затяжной депрессии нет ничего лучше, чем мчаться по дороге с близким человеком и слушать любимую музыку, наблюдая впереди, возможно, самый красивый закат в твоей жизни.

В те дни прошедшие годы казались мне старыми добрыми временами. Теперь же, воспоминания пронеслись передо мной яркими вспышками. Я поняла, что сегодня именно те холодные дни, проведенные в обители Миши, стали для меня старыми и добрыми. Пожалуй, осознание важности чего-то невозвратного – это процесс необратимый. 

Колесо Сансары сделало свой оборот.

<div style="text-align: center;">***</div>

– Снова ты со своими закатами, – проследив мой взгляд, с любовью в голосе произнес Веня.

Я подумала, что наверняка однажды буду стоять где-нибудь у окна с видом на исландские долины, пить крепкий черный чай и думать о том, какими славными были дни, проведенные в советской севастопольской квартирке. 

С Исландией это, конечно, было не точно, но вот на счет чая я могла быть полностью уверена.

Я виновато улыбнулась.

– Солнце скоро сядет за холм. Дай полюбоваться еще минутку.

Вдруг Веня взял мою руку и, весело подмигнув, принялся пересекать улицу, само собой, утаскивая меня следом. Мы бежали квартала два, а я, в общем-то, и не знала куда. И вот, когда я, будучи абсолютно неспортивным человеком, уже почувствовала, что в боку сейчас что-то явно сломается, мы так же внезапно остановились.

– Вот, – гордо объяснил ситуацию Веня.

С трудом отдышавшись, я обернулась. Мы стояли на тот самом холме, за которым еще пару минут назад собиралось скрыться солнце. На лбу моего Сусанина проступил пот и, усевшись на траву, он принялся вытирать лицо краем рубашки. Я опустилась рядом и уложила голову на плече Вениамина.

Так мы провели самый потрясающий из всех крымских закатов.


