# &nbsp; {#chapter-31}

Спустя четыре месяца мне представилась такая возможность. Антон позвонил мне в первые дни сентября две тысячи пятнадцатого. Он рассказал о нехватке рук и очень просил прийти на стажировку в «Штиль». Тем летом я побывала за обратной стороной стойки в парочке заведений, но ни в одном из них так и не задержалась. Постоянный шум, ненормированный график, низкая оплата и куча невоспитанных и нетрезвых клиентов вызывали во мне отвращение. И, все же, я вспомнила о данном себе обещании и не смогла отклонить просьбу бывшего учителя. А еще мне нужно было что-то кушать.

И вот мы стояли за клубной стойкой. До этого дня я не бывала в «Штиле», но не без удивления отметила, что все здесь выглядело именно так, как я себе это представляла. Зал заполняло человек двести. В основном они делились на три категории: пьяные мужики, выплясывающие в компании себе подобных и периодически прославляя ВДВ, что были не прочь склеить каждую встречную-поперечную, одинокие алкоголики, танцующие сами по себе, словно в другом космическом измерении, и лишь изредка пытавшиеся войти в контакт с другими представителями своего вида и девицы, пришедшие сюда, чтобы подцепить папиков. Последние выглядели куда вульгарней местных проституток. Они просто становились перед обрамляющими зал зеркалами и без устали крутили бедрами, закусывали губы и запускали руки в волосы, рассматривая собственное отражение. За этих мне было особенно стыдно.

В календаре значилась пятница, что принесло клубу переполненный зал и миллион заказов. На стойке то и дело накапливалась гора грязной посуды. Рядом виднелись груды скомканных салфеток и переполненные пепельницы. В то же время чистой посуды катастрофически не хватало, но всем срочно от меня что-то требовалось. Классическое завершение рабочей недели.

Сначала я разливала пиво в вышедшие из пользования бокалы с надписями уже не существующих в «Штиле» марок. Затем подавала Текилу Санрайз в двойном хайболе, водку в рюмке для абсента, а американо в чайной чашке. Официанты, то и дело снующие вдоль стойки, всячески игнорировали мои просьбы. Они отмахивались, когда я просила сходить за чистой посудой, а то и вовсе делали вид, что не слышат меня, стоило мне попросить очистить барную от грязных стаканов и заменить пепельницы. Ситуация накалилась, когда за баром закончились чайники. К тому моменту официанты вокруг тоже закончились. Скрепя зубами, я отправилась на мойку.

На пути мне встретилась горстка тех самых официантов, лениво сидевших в курилке. Картина эта меня разозлила. Я всегда была лояльной к подобного рода отдыху хотя бы потому, что не расставалась с сигаретой с шестнадцатилетнего возраста. Проблема была в том, что из всех сидевших около лифта барышень, лишь одна была курильщицей. И, все-таки, я ничего им не сказала. Проходя мимо, я только с грустью подумала о том, что мой последний перекур был три часа назад. 

Тут следует сказать, что я всегда была человеком эмоциональным и прямолинейным. Порою даже слишком. Я никому не позволяла разговаривать с собой на повышенных тонах и не стеснялась в выражениях, когда меня что-то не устраивало. По этой простой причине любой из тех, кто знал меня в юности, усомнился бы в своем зрении, завидев то, с каким спокойствием я прохожу мимо развалившихся в проходе официанток. На самом деле, череда несбывшихся надежд, разрушительная школьная любовь, меланхолия, которая длилась не один год и ситуация с Адамом слегка умерили мой пыл. От всего этого я сделалась грустной и, когда мне стукнуло двадцать, впала в затяжную депрессию. 

Моряк не злится на рыбок за то, что те его замечают.

*Особенно, моряк, который решил утопиться.*

Как бы смешно это не звучало, уныние и впрямь сделало меня рассудительной, понимающей и терпеливой. Но даже самое душещипательное расставание не сделало бы меня святой. Я по-прежнему воспламенялась при виде несправедливости, но теперь уже далеко не сразу. Обычно у оппонента было всего две попытки для того, чтобы поступить правильно. Во время этих двух попыток мною владело полнейшее безразличие, – как внешне, так и внутренне – а затем я выходила из себя. Случалось это столь бурно и особенно внезапно для незнающего человека. 

– Мне нужны винные бокалы, – произнесла я уже ближе к концу смены.

Стоявшая рядом официантка и бровью не повела. К счастью, рядом находился Антон. Он громко повторил мой запрос, и официантка нехотя отправилась его выполнять. Вскоре вымытые мной чайники вновь подошли к концу. Не хватало также коньячных рюмок, мартинок и еще уймы всякой всячины, а заказы все сыпались и сыпались. Размышляя об этом, я поставила на раздачу последнюю чашку для эспрессо и в замешательстве посмотрела на экран. Там виднелся новый заказ: четыре эспрессо, бутылка коньяка с посудой на четверых и двенадцать мохито. Помимо всего прочего, для последних не было ни льда, ни стаканов, ни даже мяты.

Окинув взглядом этот список, я со спокойной душой отправилась на первый за ночь перекур. Долгожданная сигарета отказалась приятной, но даже она не смогла подарить мне то удовольствие, которое я испытала по возвращению за стойку. По другую сторону перегородки стояла все та же официантка, внезапно вспомнившая о моем существовании. Девицу уже вовсю распирало от ярости. Ее длинный крючковатый нос то и дело трясся, раздувая широкие ноздри. 

– Где кофе? Где коньяк? – неистово верещала она. – Где Мохито? ГДЕ МОХИТО?

Так кричал бы Хемингуэй, вошедший в любимый бар после очень длинного дня, проведенного на солнце.

– Где посуда? – спокойно спросила я.

– Да иди ты нахуй со своей посудой! Я тебя спрашиваю, где мой заказ?

Меня не было минут десять. Все это время весьма нетрезвые клиенты донимали ее аналогичными вопросами и, я полагала, что заданы они были не в самой вежливой форме. 

Я развела руками.

– Мне не в чем его готовить. 

К тому моменту около нее появилось еще несколько официантов. Все ждали свои заказы, которые я и не думала делать.

– Да мне поебать, что тебе не в чем его готовить! Могла бы уже давно поднять свою жирную сраку и принести сюда посуду! Нехуй становиться барменом, если ты нихуя не хочешь делать! 

– Нужно отнести грязную посуду на мойку и принести мне чистую.

Официантка продолжала орать и разошлась еще сильнее, когда другие официанты принялись ей вторить. 

Я глубоко вздохнула и вопросительно посмотрела на Антона. Тот медленно кивнул, вероятно читая мои мысли. Он то был в курсе моего взрывного характера. 

Получив молчаливое разрешение начальства, я не без радости повернулась к все еще не закрывающим рот фицам. Обвела взглядом их покрасневшие от воплей лица и принялась орать в ответ. Да так, что дремавший за стойкой мужик, которого полночи тщетно пыталось разбудить сразу трое охранников, с хриплым визгом подскочил со своего места. 

Той ночью я переорала их всех. И переорала бы еще десятерых, потребуйся мне это, но так и не поняла, для чего это нужно.

Не припомню, дабы после этого хоть одна из клубных девиц обращалась ко мне в неуважительной форме. Прошло полтора месяца, и, вняв моим просьбам, руководство перевело меня в ресторан. А уже в конце зимы я начала стажировать нескончаемый поток молодых людей, пришедших работать в «Штиль». К тому моменту мне исполнилось двадцать два.

Одним из стажеров, что продержались дольше пары смен, оказался двадцатилетний компьютерщик. Я уже говорила о его стеснительности, которая временами граничила со слабоумием. Бармены снизу иногда являлись для того, чтобы взять какой-нибудь товар, но чаще всего для этого посылались официантки. Они-то и наводили на паренька кромешный кошмар. 

Все такие же кричащие и обозленные на окружающий мир, они выхватывали из рук моего новоиспеченного сменщика нужные бутылки и мчались обратно в клуб, расталкивая всех на своем пути. Иногда вместо официанток являлась кассир. Она не была особенно старой, но вела себя с наглостью николаевских старух. Карина была полной женщиной очень низкого роста, что не мешало ей разгуливать по «Штилю» с вздернутой вверх головой и гордо выпяченной вперед грудью, которая плавно переходила в живот и коротенькие ножки. Сотрудники называли ее не иначе как Гномиком. Пожалуй, она была единственным из знакомых мне людей, чьи параметры представляли собой идеальный квадрат. 

В любом случае, ни Карина, ни официанты, пришедшие из клуба, никогда не вносили в журнал забранный товар. Тем временем мой напуганный сменщик боялся и слово лишнее вставить, а про журнал и думать забыл. Само собой, все это привело к недостачам, которые влетели ему в стоимость заработной платы, и парнишка поспешил ретироваться обратно, в мир растворимого кофе и умных технологий. 

В итоге, мне вновь пришлось работать за двоих.

Откровенно говоря, я вовсе не винила скоропостижно сбежавшего сменщика. Проведя несколько лет в сфере IT, я прекрасно понимала причины, побудившие парнишку вернуться к старому делу: короткий рабочий день, комфортные условия, возможность отвлекаться на любимые сериалы и оклад, в десятки раз превышающий зарплату бармена. И, хотя однажды я и дала себе слово, никогда больше не работать на нелюбимой работе, порой мысли о добровольно утраченной зоне комфорта тоской отзывались в моей душе.


