# &nbsp; {#chapter-35}

Когда, спустя восемнадцать месяцев, Марта сказала мне, что запала чуть ли не на первого встречного, я вовсе не удивилась. Должно быть, она ждала от меня мудрого совета, который пристало иметь каждому, кто хоть раз состоял в бурной романтической связи. Однако, видя ее неистовое воодушевление, слыша дрожащий от волнения голос, сопровождаемый взглядом совсем по-детски наивных глаз, я только и смогла выдавить из себя:

– Ох, деточка…

Мне хотелось сказать ей о том, что ни одна любовь не длится вечно. Рассказать о горечи, что следует за пылкими чувствами. Завести долгий монолог о том, что любовь – это вообще крайне страшная штука. Она и впрямь походит на наркотики и прочие приносящие вред пристрастия. Виной всему служит тот простой факт, что, как бы плохо тебе не было по окончании отношений, придет день, и ты вновь кого-нибудь полюбишь. И чувства эти будут даже сильнее тех предыдущих, которые, казалось, принесли тебе самую страшную боль. 

А затем все закончится, и ты вдруг поймешь, что первая боль и вовсе не была болью в сравнении с тем, что ты имеешь теперь. С каждым новым разом любовь растет в геометрической прогрессии, а вместе с ней растет и уровень тяжести всех вытекающих из любви последствий. Увы, даже осознав это, ты никак не можешь отделаться от этого примитивного желания – любить и быть любимым. Казалось бы, все просто, но нет! Любовь вызывает привыкание. Она окрыляет, делая самый убогий дом уютным. Так, искренне любящий человек чувствует себя чуть ли не бессмертным. Когда любишь, то и море по колено. Потому-то, даже испытав на себе все любовные горести, ты больше не можешь мириться с одиночеством и подсознательно продолжаешь поиски новой любви. Продолжаешь просто потому, что больше не можешь жить без этого чувства.

Тем днем мне многое хотелось сказать Марте. Думаю, она едва ли предполагала, что за этим невзначай и не без юмора брошенным «Ох, деточка…» могли скрываться такие долгие внутренние диалоги. Конечно, мне хотелось помочь ей. Ну, или хотя бы объяснить, что в лучшем случае принесенная любовью радость будет равна той боли, что обрушится на тебя по завершении отношений. 

Но я не смогла. Слишком счастливой была моя подруга. Она вовсе не заслуживала таких грустных разговоров и так напоминала меня саму каких-то пять лет назад. Глядя на это ни с чем не сравнимое счастье первой влюбленности, что прямо-таки струилось из каждой клеточки девушки, я почувствовала, что где-то на задворках моего сердца теплиться надежда. В конце концов, не все ведь обязаны жить с разбитым сердцем, правда? К тому же… Порой разрушать чужие иллюзии куда сложнее, чем собственные.

Что же касается меня, слишком уж долго я сторонилась отношений. Слишком часто отказывала мужчинам. Я провела не один год в отношениях с нелюбимыми людьми, отчаянно пытаясь забыть Эрика, свою первую школьную любовь. И хотя однажды мне удалось избавиться от этих настойчивых чувств, я не могла забыть той радости, того сумасшедшего прилива сил, который я испытывала каждый раз, когда Эрик был рядом. Даже когда мы не были парой в традиционном понимании этого слова. 

Теперь, конечно, уже сложно сказать, что именно пошло не так, но с моих пятнадцати лет он так и не смог полюбить меня. А я так и не смогла полюбить тех парней, что опрометчиво старались завладеть моим сердцем. Все это делало меня грустной и злой. Дошло до того, что я и вовсе возненавидела отношения. Мне была противна сама мысль о том, чтобы вновь пустить кого-то в свое личное пространство, или того хуже – в свою душу.

В итоге, пришлось признать: игра эта сильно затянулась. К тому моменту мне уже исполнилось девятнадцать, и я разорвала свои последние бесполезные отношения. С Эриком мы не виделись без малого полтора года, когда я вдруг осознала, что уже и думать о нем забыла. Должно быть, в юности этот человек и впрямь имел для меня немалое значение, но потом… Я поняла, что любила его словно по привычке. На самом же деле, Эрик уже давно не был мне нужен. Все, что мне было нужно – это воодушевляющие чувства, которые я испытывала рядом с ним. Мысль о том, что источником этих чувств являюсь я, а не Эрик, неоднократно наведывалась в мою голову, а я снова и снова гнала ее как прокаженного бездомного, что под покровом ночи пытается проникнуть в старый сарай.

К счастью, Эрик оказался не единственным мужчиной, способным дать мне все это. Незадолго до своих двадцати лет я встретила Адама и, сама того не желая, запала на него. На этот раз чувства были более взрослыми. Естественно, и любовь моя была в разы сильнее той, предыдущей. Как и следовало ожидать, боль расставания оказалась невыносимой. 

Мне исполнилось двадцать. Я вновь возненавидела любовь. Я проклинала свое глупое сердце за чувства, которых не должно было в нем быть, и злилась на вселенную за то, что та наградила меня такой упрямой, никому не нужной верностью. Я с легким презрением смотрела на девушек, рассказывающих мне о своих первых чувствах так, словно они и правда верили в то, что отношения эти будут единственными в их жизни. Злилась на любовь потому, что знала, какой двуличной и коварной бывает эта сука, но еще больше потому, что чувство это было моей единственной слабостью. А я ненавидела свои слабости. И ненавидела себя за то, что не могла избавиться от них.

И, все же, я и дня не могла прожить без любви, как не могла проснуться без табака и чашки крепкого черного чая. Это была самая настоящая зависимость, и, как бы я ни старалась от нее избавиться, какой бы циничной и независимой я не делалась, в конце концов, пришлось признать, что любовь нужна мне хотя бы для того, чтобы жить. Быть может, это выглядело чересчур странно, но ведь я писатель, а творческие люди, знаете ли, не самые адекватные. 

Я так долго была несчастной и одинокой, что и вовсе не верила в то, что встречу родственную душу. Однажды я уже собрала все свои рукописи в увесистую стопку, уложила их на кухонном столе и готова была застрелиться подле этой унылой картины. Подумать только, мне был всего двадцать один год, а уже в который раз чувствовала себя слишком старой и уставшей для того, чтобы жить. Но мне удалось выйти из депрессии и никого это не удивило больше, как меня саму. Общество почему-то всегда считало меня сильной, тогда как я с каждым годом все меньше и меньше верила в возможность восстановления своего морального состояния. Ситуация значительно упростилась, когда я услышала свой диагноз.

Так или иначе, после семи долгих лет, полных печали, одиночества и неразделенной любви и чего-то там еще, я встретила Вениамина. И подумать не могла, что все еще могу испытывать такие сильные чувства. Но я полюбила его. Как никогда никого не любила. А этот белобрысый дурашка теперь лежал напротив и в самом деле сомневался в том, что я вернусь к нему.


