# &nbsp; {#chapter-38}

– Я люблю тебя, как не любил ни одну женщину, – произнес Вениамин.

Нож по-прежнему оставался в его руке. Веня нажал на кнопку, и в лунном свете мелькнул одинокий блеск лезвия. Не медля ни секунды, мой жених приставил нож к своей руке и сделал надрез чуть выше кисти. Какое-то мгновенье ничего не происходило. Кожа на его руке оставалась все такой же бледной, а затем хлынула кровь. Порез оказался куда глубже, чем мы рассчитывали.

– Еще один шрам, – сказала я, проводя пальцами по руке Вениамина. Они тут же окрасились в алый. – Будет что детям рассказать.

– На то и расчет, – улыбнулся Веня.

Он перевернул нож лезвием к себе и протянул его мне.

К тому моменту небо над морем стало гораздо светлее. Тьма начинала рассеиваться, уступая дорогу предрассветным часам. Я взяла нож и какое-то время разглядывала его лезвие. Местами запачканное кровью моего сумасшедшего мужчины, оно было таким же серым, как небо, что как раз начинало алеть над нашими головами. 

Я провела краем лезвия по коже правой руки, но это была всего лишь царапина. Тогда я со всей силы надавила на рукоятку, чувствуя, как под ней рвется кожа, и повторила процесс. Еще одна царапина, не больше. И тут я вдруг поняла, что в кои-то веки не хочу себя калечить. Я была абсолютно счастлива.

– А я ведь тоже тебя люблю.

В моем голосе звучало ничем неприкрытое удивление, словно я впервые узнала о своих чувствах к будущему мужу.

– Ты не обязана себя резать, – заметил Вениамин, хотя прекрасно понимал, что без этого его затея не имеет смысла. 

Все это время его рана оставалась ничем не прикрытой, и теперь кровь окрасила всю ладонь мужчины.

Я отрицательно покачала головой.

– Знаю, что не обязана. Но я хочу.

И я протянула нож Вене.

– У тебя получится лучше моего. Я уже потеряла навыки селфхарма.

Однако, у него ничего не получилось. Это была очередная царапина.

– Не могу я причинять тебе боль, – виновато произнес Вениамин. – Эти твои царапины, они ведь тоже милые. Мы можем просто…

Но я уже его не слышала. Просто поставила нож на балконные перила, а затем что было духу ударила по нему наружной стороной руки. На этот раз правой. Подняла ее, чтобы полюбоваться проделанной работой, но так и не успела оценить масштабы травмы. Кровь мигом залила все вокруг.

Прерванный на полуслове Вениамин широко улыбнулся. Он принялся целовать мою руку, затем меня. В общем, вскоре мы оба уже изрядно перепачкались в собственной крови.

– Любовь моя, – торжественно начал Веня. – Я люблю тебя, как не любил ни одну женщину. И я хочу жениться на тебе как можно скорее, деточка. Хочу, чтобы ты стала Елизаветой Ларионовой, и тебе никогда бы не понадобилось уезжать от меня.

Он еще раз поцеловал мою руку, а затем приложил ее к своему порезу и бросился клясться в вечной любви.

– Ты веришь мне? – спросил Веня.

– Верю, и клянусь тебе в том же, – честно ответила я, а затем так же честно добавила: – Но, если ты обидишь меня, я возьму этот самый нож и проткну им твое сердце. В этом я тебе тоже могу поклясться.

Это прозвучало гораздо серьезней, чем должно было, и я с опасением взглянула на Вениамина. Тот стоял с крайне беспечным видом, едва ли напуганный моими словами.

– Проткни, – ответил он, обнимая меня за плечи. – Мне все равно не нужна эта жизнь без тебя.

Солнце вот-вот обещало показаться за горизонтом. Мы стояли на балконе, в обнимку, обращенные лицами к уходящей тьме. Всего лишь двое городских сумасшедших в ожидании рассвета.

<div style="text-align: center;">***</div>

Автобус мы вновь упустили, но особого выбора у меня не было. Пришлось мчаться в конец города, надеясь перехватить рейс там. Как ни странно, нам это удалось. Более того, Веня, (к тому моменту достаточно трезвый и спокойный для того, чтоб сесть за руль своей развалюхи) даже перестарался. Теперь мы остановились на выезде из Севастополя. Недалеко от Инкермана. Предварительные расчеты говорили, что до появления автобуса оставалось около десяти минут. Мы молча смотрели вдаль, готовые в любой момент сорваться с места и, подхватив чемодан, остановить автобус.

И при этом не готовые вовсе.

Пожалуй, тем утром никто из нас не знал, что следует сказать. Все и так было сказано. И не раз. На моей руке красовалось кольцо Вениамина, слишком широкое для носившего его пальца. Чуть выше виднелся новенький шрам. Длиной он был лишь в несколько сантиметров, но почему-то оказался крайне глубоким. 

По обе стороны от нас виднелись одни только скалы да небольшие горы. Местами их разбавляла пробивающаяся через камни зелень. «Таврия» стояла на съезде спиралевидного шоссе, из-за чего приближающийся транспорт до последнего не было видно. Вскоре послышался шум двигателя. Спустя несколько секунд мимо нас на бешеной скорости пронесся очередной автомобиль. Еще мгновенье, и машина вновь скрылась за поворотом. Какое-то время до моих ушей доносился удаляющийся шум мотора, но и он быстро исчез. Тогда в воздухе вновь повисла тишина. Та самая неповторимая стеклянная тишина, какая бывает лишь в горах. Время шло, но ни один из нас не решался ее нарушить.

Вениамин подкурил бессчетную сигарету. Я сделала то же, но тут же избавилась от своей сигареты: уровень никотина в моей крови оказалась слишком высоким как для не так давно начавшегося утра. От табачного дыма начало мутить. Время не просто тянулось. Оно двигалось со скоростью трехпалого ленивца, чью шерсть покрывает мох, принимая его за бревно ввиду сидячего образа жизни. Однажды что-то подобное случилось с моим приятелем.

Мой мужчина загадочно и вместе с тем сосредоточенно глядел вдаль. Правда, даль ограничивалась всего парой-тройкой метров, за которыми был поворот вверх по дороге. Воспользовавшись первым из этих фактов, я позволила себе расслабиться. И тут же заплакала. Без звука, как герои немого кино, но Веня сразу же это заметил.

– Держи, глупышка, – он протянул мне платок, который в те дни зачем-то все время носил с собой.

Я взяла его, смахнула слезы и постаралась так же элегантно избавиться от мгновенно появившихся соплей.

– Нет, так дело не пойдет. Давай как я учил.

Терять мне было нечего, так что я сделала глубокий вдох и высморкалась с запалом заядлого астматика. Где-то в середине этого процесса из-за угла выглянул тот самый автобус.

От неожиданности я выронила платок, и сопли, вперемешку со слезами, уже стекали по моему подбородку. Куда менее изящно, чем мне того хотелось. Веня среагировал практически вовремя. Он выскочил на дорогу и уже энергично махал руками. Автобус притормозил в нескольких метрах от нас. Не успев толком остановиться, водитель тут же принялся жать на клаксон. Одной рукой я подхватила чемодан, второй же безуспешно пыталась удержать продолжающие течь сопли, начиная при этом бежать в сторону автобуса. При виде этой картины мой будущий муж расхохотался смехом, что был неприлично детским, учитывая масштабы его бороды.

Мы остановились у самого входа в автобус.

– Это самое нелепое прощанье в моей жизни, – сказала я, стараясь прикрыть нижнюю часть лица.

Веня отбросил мою руку. Он крепко поцеловал меня и ответил:

– Потому, что это не оно.

Водитель нетерпеливо жал на гудок. Я выпустила руку Вениамина из своей и вошла в автобус. К тому моменту мы провели в ожидании более двадцати минут. Математика никогда не была моей сильной стороной. Как и прощания.

