# &nbsp; {#chapter-39}

Чем сильнее я отдалялась от Севастополя, тем более заметным становилось ухудшение погоды. Солнечный город – с его бескрайним морем, горными долинами и залитыми солнцем пляжами – остался за спиной. 

Я сидела у окна автобуса, наблюдая за тем, как стремительно сереет небо. Слева от меня расположилась крашеная блондинка лет тридцати пяти. Она читала электронную книгу и с завидной настойчивостью пыталась поймать мобильную связь каждые пять минут. 

Автобус заехал в Армянск и, выйдя из него, я почувствовала на своем лице первые капли дождя. До границы оставалось где-то десять минут езды. При мне был заметно утяжелившийся вином чемодан без малейшего намека на колесики, полноценный макияж и не менее полноценная укладка. Зонта у меня, конечно же, не имелось, так что отсутствующий во всех прогнозах погоды дождь едва ли удивил. Мне было всего двадцать два, несколько лет разделяли меня от того, чтобы отказаться от комплексов и косметики без особого случая, но этот закон подлости я к тому моменту уже успела усвоить: если ливню и суждено меня настичь, то это непременно случится на границе. 

*Ох, чувствую, скоро повеселимся!*

Пугающе длинные очереди на шесть контрольных пунктов, (по три с каждой стороны) отсутствие подвесного покрытия, едва ли асфальтированная дорога длиною в несколько километров и целая куча ям на любой вкус – ну, разве не идеальное место для очередной комической сценки под дождем со мной в главной роли?

Раздумывая об этом, я решила поступить так, как обычно поступаю в любой хоть сколько-нибудь озадачивающей ситуации: отправилась пить кофе.

<div style="text-align: center;">***</div>

– Ты знаешь, куда здесь идти? – спросила блондинка. Та самая, что ехала на соседнем от меня сидении. 

Сейчас ее электронная книга и мобильник скрылись в пределах сумки, и женщина, что было духу, пыталась перекричать раскаты грома, доносившиеся со всех сторон. На несчастной были туфли на высоченной шпильке и коротенькое белое платье. Теперь оно стало практически прозрачным под влиянием беспощадного ливня.

Сказать, что лило как из ведра – в принципе, не сказать ничего. Я простояла в очереди на паспортный контроль всего с четверть часа, но за это время у меня сложилось впечатление, что где-то там наверху боженька с похмелья споткнулся о земной шар, ушиб мизинец и, разозлившись, пнул Землю еще сильнее, отчего та перевернулась, и теперь на меня извергались все воды Антарктического океана.

Очевидно, я слишком долго не отвечала потому, как незнакомка из автобуса повторила свой вопрос.

– Ты знаешь, куда здесь идти? – еще громче крикнула она.

Я посмотрела направо: там был высоченный забор с подсветкой и колючей проволокой. Затем посмотрела налево – абсолютно идентичная картина. На всякий случай я еще взглянула через плечо: там виднелся первый контрольный пункт, который мы как раз прошли, а за ним возвышался автобус, что довез нас до границы.

*А ты вот как думаешь?* – хотелось ответить мне. 

Но я посмотрела на эту до нитки продрогшую барышню на десяток лет старше меня, и мне стало жаль ее. Еще одна любительница нафуфыриться в дорогу.

– Туда, – ответила я, указывая в, в общем-то, единственном не прегражденном заборами направлении.

Раз в сотый подряд я отбросила с лица мокрую прядь волос, (она заняла прежнее место ровно через десять секунд) покрепче вцепилась пальцами в замерзшую ручку чемодана, что так и норовила выскользнуть из мокрых рук, и принялась прокладывать путь сквозь болото, лужи и скрывающиеся под ними ямы. 

Прошла я метров сто пятьдесят, когда услышала голос все той же блондинки. Теперь ее слова окончательно терялись в гуле непогоды. Кажется, она застряла каблуком в одной из тех самых ямок, что прячутся за лужами. В общем, мне пришлось вернуться.

Спустя каких-то пять минут незнакомка из автобуса была спасена. Правда, за это время я окончательно промокла. Оказавшись на воле, женщина – она представилась Витой – радостно заявила мне:

– А теперь бежим!

До следующего автобуса оставалось практически полтора часа, а ни на одной из нас не осталось сухого места, так что я спросила:

– А зачем?

И, окутанные пеленой неугомонного ливня, мы зашагали по этим бюджетным декорациям к сериалу «Ходячие мертвецы».

<div style="text-align: center;">***</div>

Перенесемся в тот момент, когда я вновь проделывала все тот же путь: паспортный контроль, проверка багажа, пограничный контроль и более детальная проверка документов. Все это под открытым небом, без малейшего намека на укрытие.

Выстояв последнюю очередь, я, формально, оказалась на родине. В общем-то, ничего не изменилась. Дождь и не думал утихать. Холодные капли продолжали беспощадно хлестать по лицу. К счастью, к тому моменту я замерзла настолько, что практически этого не чувствовала. До отправления следующего автобуса оставалось еще минут с пятнадцать. 

Он стоял в чистом поле, но, устроившийся внутри водитель был против того, чтобы кто-то заходил в салон раньше времени отправления. Я швырнула чемодан на какие-то изломанные дождем ростки то ли пшеницы, то ли кукурузы, умостилась сверху и закурила.

Вита стояла рядом. По-прежнему на шпильках, которые теперь вдоль и поперек были облеплены грязью. Обхватив себя руками, она дрожала и нетерпеливо поглядывала на часы. Сейчас ее довольно миловидное лицо больше походило на древнюю маску с гротескно растянутыми чертами. Платье настолько промокло, что сквозь него без труда просматривалось не только точеная фигурка женщины, но и все то, что должно было скрыть белье. Наблюдая за спутницей, я пообещала себе никогда не надевать стринги под короткое светлое платье. Потом вдруг вспомнила, что с утра и сама была немного при параде. В общем, я решилась достать из сумочки зеркало…

Картина открывалась, прямо-таки скажем, пугающая. Мои прекрасные волосы, которые совсем недавно шелковистыми волнами ниспадали на плечи, теперь потускнели, став каким-то безжизненным начесом из восьмидесятых. Лицо вообще представляло собой отдельную тему, касаться которой в приличных кругах явно не следует. Должно быть, именно так смотрятся шлюхи после тяжелой ночной смены. Все выглядело настолько дурно, что, попытайся я это исправить, сделалось бы только хуже, так что я подхватила перепачканный мокрой землей чемодан и с безразличным лицом вошла в автобус.

<div style="text-align: center;">***</div>

– Как думаешь, мы когда-нибудь остановимся? – спросила Вита.

Мы расположились на галерке, получив возможность слегка подсохнуть после продолжительного ливня. Последний, кстати говоря, все так же барабанил в окна автобуса. Прошло около трех часов, а мы ни разу не остановились. Несмотря на царившую за пределами автобуса сырость, в салоне было очень душно. Но открыть окно все равно никто не решался. Было в этой ситуации кое-что позанятней духоты: мы уже битый час ехали через поле. Причины этому никто не знал, но навигатор в телефоне сообщал, что таким образом мы прибудем в пункт назначения на пару часов раньше, так что я особо не возражала.

Автобус остановился лишь в Херсоне, впервые за пять, а может и шесть часов.

– У вас двадцать минут, – объявил водитель, который еще в начале пути показался мне подозрительной личностью.

Пассажиры тут же ринулись к выходу: избавляться от старой жидкости и наполняться новой. На протяжении всего пути Вите требовалось в дамскую или уже хоть какую-нибудь комнату с наличием унитаза, так что не успел автобус заехать на стоянку у автовокзала, моя новая знакомка уже стояла около двери.

Я, конечно же, отправилась за кофе. Зашла в миниатюрный бар-кафе, который, к тому же, был еще и шашлычной, и уже даже не удивилась внезапной встрече. За прилавком стояла Тома. Все в той же полосатой футболке. Только ее подстриженные под миллиметр волосы, казалось, стали еще короче. В такие моменты мне думается, что у проекта о моей жизни очень низкие рейтинги и маленький бюджет, которого хватает всего на пару статистов. Девушка сразу же меня узнала, (что так несвойственно для работников подобных привокзальных заведений, особенно когда ты врываешься в них в макияже, поплывшем после проливного дождя) и даже назвала по имени.

– А я вот с мужем развелась и вернулась в Херсон, – сказала Тома, протягивая мне кофе. – А ты там что? Замуж хоть еще не вышла? Видок у тебя какой-то таинственный. 

Я подумала о том, что встречать незнакомых или практически незнакомых людей куда приятнее, чем людей из прошлого. Им ты вряд ли сможешь вот так просто открыть душу, не рискуя загадить последнюю. Как раз собиралась ответить на вопрос Томы, когда та вдруг захохотала. Бармен-бариста-официант и теперь, очевидно, грильщик, указывала пальцем в сторону окна.

Проследив за этим жестом, я увидела женщину. Она бежала за стремительно удаляющимся автобусом и энергично размахивала руками.

– Еще одна, – сказала Тома. – Каждый день такое вижу.

– Еб твою мать, – ответила я.

Той женщиной была Вита.




