# &nbsp; {#chapter-45}

Дни тянутся неописуемо медленно, когда ты молод. Другое дело, когда ты загружен работой. Это выручает. Я не видела любовь всей своей жизни практически месяц, но у меня просто не было времени грустить по этому поводу. И вот, наконец, наступил день Х: работы у меня больше не было. До отъезда оставалось лишь три дня, а время вдруг начало нестись как сумасшедшее. Так, словно оно пыталось наверстать все те моменты, когда час был равен вечности. 

Перед отъездом меня ждало еще несколько дел. Несколько встреч, посиделок, душевных разговоров и прогулок. И, конечно же, меня ожидало и множество прощаний. Одним погожим утром я проснулась раньше обычного. К тому же, без будильника, что уже само по себе было для меня странным. Меня пробудила мысль, такая ясная в своей внезапности. Я вдруг поняла, что мне, во что бы то ни стало, нужно избавиться от своего прошлого.

Я села на кровати, подкурила сигарету и, запыхтев прямиком в постели, начала думать над тем, как это сделать. Большинство вещей из прошлого, что гложили меня прежде, не были физическими. Биться головой о стену в надежде, что я ушибу именно ту часть коры мозга, где прячутся нежеланные воспоминания, мне как-то не хотелось. Я никогда не была сильна в таких делах. Все свои знания касательно анатомии человека почерпнула с судебной медицины и лекций по патологической анатомии, так что от этой идеи пришлось отказаться.

Заиграла музыка. Комнату наполнили сладкие звуки пост-панка, я прогулялась вдоль подоконника и вновь плюхнулась в постель. На соседней подушке спала малышка Тая, старшая из моих собак. Ей было тринадцать лет, но большинство незнакомых людей до сих пор принимали Таю за щенка. Если не считать парочки седых волосков, взгляд был единственным, что выдавало возраст моей собаки. Он был умным и выразительным. Словно говорил: «Я пожила. Я знаю жизнь.»

Мы всегда были вместе, и я едва ли могла припомнить, какой была моя жизнь до того, как в ней появилась Тая. Как бы смешно не звучало, это крохотное ушастое существо с большими глазами и китичками на ушах не раз спасало мне жизнь. В моменты отчаянья, в те самые дни, когда я фанатично хотела лишить себя жизнь, мою голову посещали не мысли об адских кострах и вечной агонии. Я думала о ней, моей девочке. Один небезызвестный канадский скаут сказал, что связь между человеком и собакой может исчезнуть только с жизнью. А разве я могла ее бросить?

Я обняла свою собаку. Та приоткрыла один глаз, лизнула мой нос и продолжила сопеть. Так мы пролежали еще какое-то время. Тая в своих собачьих грезах, а я в мыслях о том, что нам предстоит расстаться.

<div style="text-align: center;">***</div>

Мне было восемь, когда мы познакомились. За окном стояла ранняя осень. Третий класс, первые деньки учебного года. Несмотря на хроническую тягу к осени, этот период я всегда недолюбливала: слишком жарко, чтобы ходить в отвратительном зеленом пиджаке, как того требовала школа. Я была импульсивным ребенком, а духота лишь добавляла раздражительности.

Так вот, однажды, в первых числах сентября, возвращаясь с занятий, я по традиции зашла в аптеку, где работала моя мама. Она была занята покупателем и попросила меня перенести какие-то коробки из одного края зала в другой. Обычное дело, Ма частенько давала мне мелкие поручения. Все еще возмущенная погодой, школьной формой и чем-то там ещё, я подняла одну из коробок, – она оказалась очень лёгкой – и без особой заботы избавилась от неё. Практически швырнула в указанном направлении.

– Ты что! – вдруг крикнула матушка. – Открой, – добавила она с улыбкой, завидев мой удивленный взгляд.

Я приоткрыла коробку. Вдруг показались два крохотных уха, а за ними глазки-бусинки. Из картонного ящика выглядывало самое чудесное существо во всем мире. Наши взгляды встретились. Злость, усталость, раздражение – все это моментально исчезло, как только я встретила свою собаку. Я взяла её на руки, и я вдруг поняла, что с этого момента для меня нет никого дороже.

Да, я мечтала о собаке сколько себя помнила. И вот я держала в руках настоящего щенка, похожего на черного лисенка. Она была совсем малышкой – пушистая, едва больше моей ладони – и ни на шаг не отходила от меня на протяжении того дня. Как и все последующие годы.

Мы назвали её Таей. Вечерами собака засыпала на моей подушке, а по утрам радостно носилась вдоль кровати и будила меня своим холодным носом. Знаю, многие говорят, что их собаки умные. Моя же понимала каждое слово и различала интонации. На самом деле, никто в семье не воспринимал ее как собаку. Тая была ребенком, которого все любили и который рос рядом со мной.

Однажды я спросила у мамы:

– Что же я буду делать, когда ее не станет?

Этот вопрос истязал мой детский ум до тех пор, пока я не выросла и не решила наложить на себя руки. Такое вот простое решение любой донимающей вас проблемы.

<div style="text-align: center;">***</div>

Вспоминая наше знакомство, я довольно быстро провалилась в сон. Говорю же, ранние пробуждения – не моя стихия. В какой-то момент я отключилась и видела во сне свое детство. 

Вот мы с родителями сидим на берегу. Около реки на окраине города. За окном то ли апрель, то ли май девяносто восьмого, но на нас по-прежнему зимняя одежда. Воздух у реки холодный, а небо такое серое, что больше напоминает асфальт, нависший над водой. Отец собирает хворост вдоль тропинки. Чуть дальше сидит мама. Она заворачивает картофель в фольгу. Кроме нас троих на пляже никого нет.

Со стороны мама выглядит подавленной и ни ее пышные волосы цвета золотого каштана, ни умело наложенный макияж не могут этого скрыть. Перехватив мой взгляд, мама улыбается и машет рукой. Она молода и красива. Явно не выглядит на свои тридцать семь. Но даже это не может скрыть усталость в ее взгляде. 

Интуитивно я замечаю, что здесь что-то не чисто, но это, в общем-то, все, что я могу понять. Мне всего пять.

Тогда я поворачиваюсь к папе, надеясь получить ответ. Ведь в мире нет вопроса, ответ на который был бы ему неизвестен. В этом я уверена на все сто. Но папа просто движется по периметру, подбирая нужные ветки. Отец выглядит так, словно его не интересует ничего кроме хвороста. Я пожимаю плечами и отворачиваюсь к реке.

Камень, на котором сижу, расположен вплотную к линии воды. От сильного ветра по реке рассыпаются волны. Они бьются о песок, о берег и о камни с бешеной силой. Брызги разлетаются во все стороны, и мне это очень нравится. Настолько, что я даже не замечаю, как сильно к тому моменту промокла моя обувь. У меня в руках томик Гоголя – «Вечера на хуторе близ Диканьки». Я читаю «Майскую ночь» и останавливаюсь на самом интересном моменте. Гляжу на воду и представляю, как из нее выплывают утопленницы. Выбираются на холодный песок и начинают водить хороводы.

Наступает обед. Повесть уже давно прочитана. Родители зовут меня к костру. Отец подходит первым. Кладет ладонь на мое плечо и слегка ударяет по нему несколько раз – так подбадривают старого друга в моменты печали. Я захлопываю книгу, и мы идем к костру, где мама уже раскладывает обед по пластиковым тарелкам.

Мои родители никогда не вели задушевных бесед друг с другом в моем присутствии, но сегодня они молчат больше обычного. А если и говорят, то как-то странно, искусственно. Но я едва ли об этом задумываюсь. В моей детской голове теплится волнующая мысль: я наконец-то знаю, кем хочу стать, когда вырасту и поскорее хочу рассказать об этом своем открытии.

После ужина мама еще долго смотрит на волны. Затем она берет меня за руку и начинает свой монолог. Ее голос звучит вполне спокойно, но как-то грустно. Мама говорит о жизни, о проблемах, о любви и о том, как порой сложно бывает совместить все это и не сойти с ума. Я по-прежнему увлечена собственными мыслями. Преимущественно об утопленниках и о том, кем я хочу стать. Словом, я улавливаю далеко не каждое слово. И еще меньше понимаю.

– Мы с твоим папой тебя очень любим, – говорит мама. – Ты же знаешь, как много лет у нас ничего не получалось. Я так мечтала о том, что у меня будет дочка. Что мы с ней будем как подружки. Я очень боялась разницы в возрасте, но десять лет ушло только на то, чтобы завести ребенка. Мы уже начинали готовить документы на усыновление, когда вдруг мне стало плохо, а потом доктор… Он сказал, что у нас получилось. 

Звучит еще много слов, много вступлений и отступлений, и еще больше воспоминаний. Наконец, Ма делает паузу, а затем говорит мне то, ради чего затевался весь этот монолог.

– Лишонька, я знаю, что ты сейчас меня не поймешь, но так больше не могло продолжаться. Я больше не могла так жить. Мы с твоим папой слишком разные люди. Поэтому я подала на развод.

И она замолкает. Последнее слово я слышу отчетливей всего остального. В свои пять лет я прекрасно знаю, что такое развод. Мои друзья во дворе об этом знают, и дети в садике, и в кино все время показывают, как это бывает. 

*Развод. *

Это слово эхом отдается у меня в голове. Вдруг все волнения становятся какими-то несущественными. Все, над чем я размышляла целый день, внезапно теряет смысл, но я все равно поворачиваюсь к родителям, чтобы озвучить свой совсем недавно обретенный жизненный план.

– Мам, пап, – говорю я. – Я хочу стать патологоанатомом.



