# &nbsp; {#chapter-46}

Оставим девяностые позади, чтобы продвинуться чуть ближе к настоящему. 

Пожалуй, это был мой первый дневной выход на улицу за прошедший месяц или вроде того. Лето уже вовсю расправило свои знойные крылья. После привычной предрассветной прохлады, которая встречала меня по завершении рабочей смены, такая погода казалась особенно жаркой. 

Ко мне приехала Мишель. Попрощаться перед отъездом, до которого оставалось еще часов сорок. В итоге, этот день стал днем нашей последней встречи, только ни я, ни, даже она тогда об этом не думали. 

– Давай туда, – я указала рукой на то место, где заканчивался ряд покрывшихся ржавчиной гаражей.

Утром мы нашли бесхозную автомобильную шину и теперь тащили ее через весь двор. Пытались отыскать какой-нибудь укромный угол. На самом деле, шину тащила только я, а Миша просто создавал видимость работы. В физическом смысле она была вдвое больше и гораздо сильнее меня, но колесо оказалось не таким уж и тяжелым, так что я не возражала. Да и как тут возразишь, когда вся затея базировалась на собственной дурости.

– Приехали? – спросила меня подруга.

– Приехали.

Я пнула шину ногой и осмотрелась. С двух сторон нас окружали старые гаражи, а остальное пространство занимали какие-то заросли. Воздух здесь был приятным. Он пах зеленью, свежестью и отчужденностью, как все те заброшенные кладбища, тропинками которых я любила гулять. Место что надо.

Тогда я опустилась на землю около колеса и выпотрошила в него содержимое рюкзака. Это была бумага, очень много бумаги. Тетради, блокноты, записки, альбомные листы, разлинованные листы и листы в клетку. Ровные, аккуратно сложенные, измятые, порванные, заляпанные кофе и бог его знает, чем еще. Были там и чеки, исписанные с обратной стороны, и салфетки, и открытки. Были и какие-то бесхозные клочки бумаги, совершенно не поддающиеся идентификации. Были, конечно, и тексты, напечатанные на компьютере и машинке. Довольно много таких текстов.

Откровенно говоря, я и не думала, что у меня собралось такое количество рукописей. Внутренняя часть шины уже была наполнена доверху, а содержимое рюкзака все не заканчивалось. Все это – мысли, идеи, планы и полноценные тексты, которые я написала за прошедшие лет десять. Последней на свет явилась «Бессонница». Сомнительной ценности повесть, что я выдала за одну ночь. И, вместе с тем, единственное произведение, нашедшее видимый отклик у аудитории. Случилось это за пару лет до встречи с Адамом. 

Я протянула руку к «Бессоннице» и развернула рукопись в первом попавшемся месте. 

*Глубина твоего познания равносильна ширине твоих взглядов*, говорил мне текст.

Я перевернула страницу.

*Сторонясь людей и подолгу ни с кем не общаясь, начинаешь влюбляться в каждого встречного*, сообщил мне рассказ.

А ниже: 

*Шагаешь по старым улочкам, укрываясь шарфом; стараешься не вглядываться в пустые лица. Закрываешь глаза, заполняешь легкие дымом, чувствуешь глубокий шелест музыки, теряешься в мыслях, изношенный до невозможности, уставший, потрепанный, вывернутый наизнанку. Встречаешь чужие, но такие родные глаза. Понимаешь, что можешь быть счастлива с кем-угодно. Но не будешь. *

*Просто потому, что все мои мысли рассыпаются каждый раз, когда я вижу тебя.*

Иными словами, ода Эрику.

Я перелистывала страницу за страницей. Мне было смешно, мне было грустно. А затем смешно от того, как это грустно и наоборот. Думаю, тем днем я держала в руках худшее из своих произведений. Сколько мне было, когда я это написала? Шестнадцать? Семнадцать?

– Что ты там так долго? – спросила Мишель.

Я о ней совсем забыла. Тем временем подруга присмотрелась к титульной странице, что валялась поверх остальной макулатуры, однажды вышедшей из-под моей руки, а я швырнула «Бессонницу» в общую кучу. Мысль о том, что я больше никогда ее не прочту, оказалась самой приятной за сегодняшний день.

– Ах ты боже ж мой! Это то, о чем я думаю? – воскликнула Миша. – Дай-ка посмотреть!

Но я уже чиркнула спичкой. Всего мгновенье и мои рукописи охватило пламя. Тетради, блокноты, дневники, чеки, картонки, салфетки, билеты и прочие клочки бумаги. Мои мечты, мои печали, мои воспоминания. Они сгорали на глазах, и я не могла остановить пламя, даже если бы захотела.

Но я не хотела. Все это – мое прошлое. И теперь, как и следует прошлому, оно обращалось в пепел. 

Огонь потух так же быстро как разгорелся. Я заглянула внутрь шины. Не знаю, что именно я ожидала там увидеть. Может быть, финансовую компенсацию за потраченное впустую время или премию Эдгара Аллана По, присланную мне с того света? Может, записку от Булгакова, удивленного тем, что рукописи горят… Понятия не имею. 

Внутри ничего не было. Лишь пепел. Теперь он больше походил на прах. Останки моих писательских амбиций, мощи моей прошлой жизни. Я зачерпнула рукой горсть пепла, поднесла к лицу и расправила пальцы. И вот дух моего прошлого уже парит и разлетается в лучах июньского солнца. 

А почему собственно нет? Однажды все мы станем лишь чьим-нибудь воспоминанием.

Мишель подходит ближе. Она берет меня за руку и спрашивает:

– И что ты теперь будешь делать?

Перед нами раскинулись ветви широкого дуба. С одной из них свисает огромных размеров паутина. Солнечные лучи играют в ее узоре. Они блестят и переливаются. Под ногами растет трава самого насыщенного из всех оттенков зеленого цвета. Она отлично сочетается с цветом глаз моей подруги. Над головой раскинулось небо, ясное как поэзия пятиклассника или первые песни Битлз. Никакого намека на тучи.

– Если не книги, то что? – спрашивает подруга. – Что ты теперь будешь делать?

Я вдруг вспоминаю, что с утра так ничего и не выпила и отвечаю то же, что и всегда:

– Кофе.

<div style="text-align: center;">***</div>

Я переезжала в Крым. Не потому, что любила море и почти научилась игнорировать врожденное отвращение к жаре. Я переезжала к Вениамину просто потому, что этому сумасшедшему алкоголику каким-то образом удалось пробраться в мое сердце. Когда я думала о нем, мою душу переполняли самые теплые чувства. Чувства, о которых я и не подозревала, что все еще могу их испытывать.

Так началась наша прощальная тусовка с Мартой. 

В начале вечера мы сидели в моей старой спальне на шестом этаже. Стены в комнате были черные, а из колонок доносился рок-н-ролл. Мы сидели около распахнутого окна, на огромной кровати с кованой спинкой. 

Стоял поздний вечер, но солнце лишь начинало садиться, как это всегда бывает летом. Все тот же индустриальный вид из окна. Серые здания, грязные улицы, одинокие люди и хмурый проспект, что заканчивался разбитым зданием вокзала, оставленным здесь задолго до распада СССР. В общем, бетонная зараза во всей красе. А над ней томно раскинулся закат экспрессиониста. Слишком насыщенный для такого хмурого пейзажа.

Тогда я впервые осознала, что я как тот закат – принадлежу этому месту. Я ненавидела эту рутину и всю жизнь искала возможность уехать из Николаева. Убежать куда глаза глядят. Но на самом деле нуждалась в этом паршивом городишке как никто другой. Печаль тоска и безысходность уже давно стали неотъемлемой частью меня, и я не была уверена, что до сих пор чего-то стою без них.

– Мне нужно быть в дерьме, чтобы писать свои книги, – заявила я.

К тому моменту солнце уже почти скрылось за крышами бесконечных девятиэтажек, а мы с Мартой заканчивали пятилитровую бутыль домашнего вина, заботливо изготовленного отцом.

Подруга смотрела на меня с недоверием.

– Так это ты что же? Я не понимаю. Ты просто вдруг взяла и передумала ехать? – наконец, спросила она.

– Я просто не могу уехать, понимаешь?

Я чувствовала, что нужно открывать вторую бутылку.

– Извини, конечно, но я вижу это совсем по-другому, – продолжала подруга. 

Я попыталась перебить ее, но это не сработало.

– Я вижу совсем другое, – продолжала Марта. На ее губах заиграла улыбка. – Наша бесстрашная Лизавета испугалась серьезных отношений. 

– Ерунда. Я ничего не боюсь.

– Кому ты пиздишь, Лиза? Ты только пару месяцев как вышла из многолетней депрессии, а тут встретила Веню и решила пока не поздно войти обратно. Ты так долго была в депрессии, что теперь это твоя зона комфорта.

– Нет, вот здесь ты не права, – я отмахнулась.

Конечно же, она была права.

– Слушай, ты сожгла свои книги, чтобы избавиться от прошлого. Ну, это по твоим словам. А сейчас ты говоришь, что никуда не поедешь для того, чтобы написать новые книги. Ты сколько уже за сегодня выпила, женщина?

Мы рассмеялись и выпили еще по бокальчику.

– Ладно, – начала я.

И постаралась убрать улыбку со своего лица. Не так-то просто после количество распитого алкоголя.

– Дело здесь не совсем в книгах… Точнее, оно совсем не в книгах. Просто у меня пару раз было такое нехорошее предчувствие на его счет. Ты же знаешь, я не верю во всю эту херню. Просто у меня хорошо развита интуиция и все такое…

– Предчувствие!

Я уже знала, что Марта ответит. То же, что отвечали все близкие мне люди. Предчувствие – это как когда тебе казалось, что Мишель тебя ненавидит и очень активно обсуждает это с другой твоей подругой? Предчувствие – это как когда ты решила, что та другая подруга врет через слово? Или предчувствие – это как когда ты целый год была уверена, что она пытается переспать с Адамом? Смешно, но, в конечном счете, все эти подозрения оказались правдой. Само собой, тогда я этого не знала, и ожидала, что Марта, как и все остальные, назовет мою интуицию всего лишь бурной фантазией. Но она лишь сказала:

– М-да уж, подруга, предчувствие – это дерьмово. И что же оно тебе говорит?

Я вздохнула, обдумывая ответ. А затем допила винишко и выпалила на одном дыхании: 

– Ну, не знаю. Может быть, что у нас все будет идеально, а затем однажды один из нас не проснется, а второй будет в панике бегать вокруг окровавленного тела своей второй половинки и даже не вспомнит, что произошло. 

– И под этим бегающим кем-то ты подразумеваешь не себя?

– Ну, в общем да. Не себя.

Здесь наступила неловкая пауза. Я почувствовала, что начинаю краснеть и сказала:

– Слушай, проблема в том, что все называют мою интуицию сумасшествием. То есть, вот когда тридцатилетний бугай работает охранником ночной смены в «Штиле» и он рассказывает, что на палубе корабля-ресторана бродит призрак… Что шары для боулинга сами себя бросают, что за столиками включается радио и что кнопка вызова официанта каждую ночь мигает, а на экране показываются номера столиков, которые находятся на той палубе, где ходит призрак – вот это нормально. И когда взрослая женщина носит на запястье красную нитку с булавкой потому, что боится сглаза – это тоже ок? Или когда та вторая моя подруга рассказывает, что видела призрака в двери за моей спиной, когда мы говорили в скайпе – это ничего! А вот если я предчувствую, что кто-то поступит со мной плохо – так я сразу сумасшедшая, понимаешь? И ведь в итоге всегда оказывается, что я права! Помнишь, как я узнала, что Эрик трахается со своей бывшей в туалете клуба? Вот это и правда было для всех шоком. И меня это пугает.

– И что говорит твоя интуиция? Вениамин тебе навредит или как это должно произойти?

Я кивнула.

– Ну, не знаю, Лиза. Вот у нас с Семеном все хорошо. Живем уже второй год, и никто никого не убил. 

– Это вдохновляет.

– Что тебя вдохновляет? – Марта взглянула на меня как на ребенка с бурной фантазией. – Понапридумывала себе херни какой-то и паришься на пустом месте! Вот мы с Семеном очень счастливы.

– А что такое счастье? 

– Счастье – это найти свою вторую половинку, войти с ней в симбиоз, употреблять вместе наркотики и путешествовать! – речитативом выдала подруга.

Мне всегда думалось, что симбиоз для неполноценных личностей. Подобная мартиной формулировка была у меня лет в четырнадцать, но критиковать чужое счастье не хотелось, поэтому я ответила:

– А ты никогда не думала, что не для всех счастье такое, как для тебя?

– В плане?

– Ну, например, кто-то может быть слишком целостным для второй половинки? Что кому-то может быть нужна такая же полноценная личность, как и он сам? Что отношения – это не предел счастья? Что кому-то может хотеться большего. Или даже совершенно другого. Что симбиоз подавляет личность и не дает человеку реализовать свой потенциал. Вообще отводит от цели, мешает выполнить свое призвание. 

– Так и чего же ты на самом деле хочешь? – с улыбкой спрашивает Марта.

– Мир, – отвечаю я. – Я хочу перевернуть мир! 

– И ты готова пожертвовать ради этого своим счастьем?

– У нас разные представления о счастье, чувак. Я ночами не сплю из-за этого мира. Уж слишком долго он вертится не в ту сторону, а я чувствую всю эту боль. Ты хотя бы понимаешь, что они сделали с планетой? Как они относятся к животным? Как они относятся друг к другу, в конце концов. Человечество впало в спячку, так больше не может продолжаться! Кто-то должен его разбудить!

Но Марта только смотрит на меня все с той же улыбкой, выдыхает дым и передает мне люфу со словами:

– Ну, не знаю, о чем тут можно париться. Нам с Семеном пофиг на проблемы мира. По-моему, ты просто боишься серьезных отношений. 


