# &nbsp; {#chapter-47}

И вот я снова в дороге. Сижу на переднем пассажирском в автомобиле своего отца и смотрю на прерывистую разделительную полосу. Машина движется быстро, отчего полоса становится сплошной, и вскоре от этой картины начинает мутить. Я вздыхаю и отворачиваюсь к лобовому стеклу.

Мы выехали всего час назад и сейчас движемся по трассе Николаев-Херсон. Знаете, там есть небольшой съезд с видом на широкие поля и высокие деревья, густо высаженные вдоль дороги. Пожалуй, так можно описать большинство придорожных пейзажей моего края, но в этом отрезке пути есть кое-что особенное – идеально ровная дорога. Глянцевая поверхность без выбоин, мусора и ухабов. Внезапно схватив приступ амнезии, можно подумать, что ты находишься где-нибудь в Европе.

Само собой, длится все это счастье от силы минут десять. Затем ты возвращаешься на землю и опять едешь по пути, напоминавшему поле боя.

– Ты в порядке? – спрашивает мама.

Она тоже провожает меня до границы. Мама расположилась на заднем сидении. Старшая из моих собак спит, положив голову ей на коленки. Младшая осталась дома. Тогда Еве было чуть больше года, и она вела себя тревожно во время хоть сколько-нибудь длительных поездок. Ну, а Тая истерически не хотела меня отпускать, а потому теперь едет с нами провожающей.

– Все нормально, – отвечаю я, хотя на самом деле это не так.

Мы здорово разругались этим утром. Не то, чтобы мои родители были против Вениамина… Они просто не хотели, чтобы я принимала поспешные решения в одиночестве. Тем не менее, если речь шла о любовных делах, именно так я всегда и поступала. Никто не смог бы отговорить меня от решения поехать к Вене, как, в общем-то, и в свое время никто не смог меня отговорить от поездки к Адаму. 

Я это знала. Они это знали. Так что, мы просто спорили какое-то время, но вскоре аргументы пошли по кругу, и разговор пришлось замять.

– Ты просто не представляешь, как это сложно, – начала мама.

– Ничего не сложно, – я подвинулась к окну и подкурила сигарету. – Я всегда смогу развестись, если что-то пойдет не так.

– Ты мне, кстати, то же самое про курение говорила! И про татуировки! – продолжала мама. – Да если бы все было так просто! Если что-то пойдет не так, ты долго не захочешь выходить замуж. Опять замкнешься в себе и только потеряешь время! А так могла бы встретить достойного человека…

– Но я никогда и не хотела выходить замуж!

– Так на кой черт ты делаешь это сейчас? – вмешался папа.

– Потому, что люблю его, – ответила я.

Отец фыркнул. Он всегда был рациональным человеком Скажи я ему, что залетела, это был бы куда более веский аргумент.

– Ты просто не представляешь, как это сложно, – повторила мама, а затем добавила: – Жить с кем-то после того как ты уже пожил с кем-то. Это очень трудно.

Отец бросил в ее сторону удивленный взгляд, но промолчал. Он был вторым человеком, с которым развелась Ма.

Хотелось мне этого или нет, но большую часть жизни я была одинока. Конечно, я знала людей, которые начинали жить вместе еще в старшей школе, но никогда не понимала, на кой черт им это нужно. Наверное, я просто слишком ценила свое личное пространство. Несколько недель – таким был максимум моего совместного проживания.

– Это что, по-твоему, труднее, чем полюбить кого-то после того как ты уже любил кого-то? – спросила я.

Мама призадумалась, а затем растерянно покачала головой.

– Наверное, где-то так же.

– Ну, в таком случае, я справлюсь.

<div style="text-align: center;">***</div>

Корпоративная тарахтайка Вениамина окончательно сломалась, так что от границы мне предстояло вновь добираться на автобусах. Морально, я уже начинала себя подготавливать ко всем неприятностям, которые с вероятностью в девяносто процентов обещали случиться в дороге, когда вдруг водитель с работы моего жениха предложил свои услуги. Это произошло в последний момент и было как никогда кстати. Конечно, мне все равно предстояло как-то добраться въезда на Симферополь и стартовать в одиночку нужно было еще в Армянске, но я решила, что это, все же, лучше, чем ничего.

Тем утром на трассе стоял неописуемый зной, а на границе образовалась гигантская пробка. За часы, проведенные в очереди под палящим солнцем, я уже раз триста успела пожалеть о том, что ношу волосы по пояс и, клянусь, будь у меня в тот момент ножницы, я бы обязательно ими воспользовалась. Но проносить подобные острые предметы на территорию блокпостов запрещалось, так что мне и моей шевелюре предстояло страдать дальше.

– Вы впервые пересекаете эту границу? – спросил таможенник, когда я, наконец, приблизилась к концу последней очереди.

Это был высокий мужчина с большими карими глазами и такой широкой, нетипичной для пограничников улыбкой.

– Нет, – ответила я. – За последний месяц это как минимум мой третий визит.

– А до этого когда в последний раз границу проходили?

– С Россией?

– Ну да.

– Году в тринадцатом, – сказала я. – Только это было на въезде в Москву.

Пограничник развел руками и принялся просматривать какие-то документы на мониторе.

– Прикольно, – спустя пару минут раздумья заявил он. 

– Что именно?

Но мужчина уже принялся громко звать коллегу, что занимался проверкой багажа.

– КОЛЬКА! – кричал он. – Давай быстрей сюда, Колька! Гляди че тут показывают!

Вскоре примчался Колька годами двадцатью старше первого пограничника. Он посмотрел на монитор, затем в мой паспорт, на меня и опять на монитор.

– Вот это прикол, – выдал Колька.

– Прикол, точно!

– Да-а-а прикол не то слово!

– Да что там такое?! – не выдержала я.

– Ничего-ничего, – ответил первый пограничник.

Колька тем временем удалился. Я не унималась.

– Нет, серьезно, что там? Вы знаете, у меня сегодня был очень тяжелый день, а ведь сейчас только без пятнадцати три. Короче, парочка приколов мне точно бы не помешала, так что… Ну что там такое то?

Мужчина продолжал улыбаться, чего нельзя было сказать о собравшейся за моей спиной очереди.

– Так вы говорите, что проходили эту границу дважды?

– Да, этой весной.

– А до этого, когда вы в последний раз здесь были?

– Месяц назад.

– Нет, это не то.

В этот момент во мне проснулись какие-то утерянные украинские гены. Резко захотелось сала, опрокинуть пару стопок да пуститься в танец, послав окружающих в лучших местных традициях.

– А что – то?

– Вы до этого когда в последний раз в Крыму были?

– Когда я была здесь до этого, никакой границы и в помине не было. У власти не стоял человек с явной умственной заторможенностью, который разговаривает как Рокки Бальбоа в худшие годы своей жизни. А размышляет и того хуже, так что Крым все еще был частью Украины.

Стоит признать, что прозвучало это совсем не так устрашающе, как мне того хотелось. К тому же, я никогда не умела произносить букву «Р», и такие слова как Крым или Рокки в моем исполнении получились комичными.

– Ладно вам, девушка, – выдохнул таможенник. 

Кажется, он пытался не рассмеяться.

– Глядите сюда, – он повернул ко мне монитор.

Я взглянула на экран. Там было мое старое фото, сделанное в шестнадцать лет. Все как обычно: макияж, легкая ухмылка, какая-то темная одежда. И только волосы окрашены в иссине черный с внезапной прядью блонда впереди. 

– А ведь когда-то мне очень нравилась эта прическа, – сказала я. – Я до сих пор иногда подумываю ее вернуть…

– Смотрите ниже.

И я посмотрела. Под фото в графе имя и пол было указано...

– Это… Это что еще такое? 

Прямиком под моей подростковой фотографией значилось, что пол мужской, а ниже: 

<strong><em>Васляев Елисей Валерьевич.</em></strong>

– Да вы не переживайте так! – понизив голос, произнес пограничник. – Кажись, это при передаче документов ошибка произошла. Вы ж не думаете, что после отделения Крыма тут все тихо и спокойно было? Тут такой базар был, вот вас случайно и записали как Елисея. А мы с Колькой потом еще долго на это фото смотрели и думали, какой же привлекательный трансвестит попался. Да Колька?

– Так точно! – подтвердил Колька из-за соседней стойки.

Я как-то смутилась.

– И эта прическа вам очень шла!

– И правда, шла… – протянула я. – Ну… Я пойду?

На этой прекрасной ноте моя каторга на украино-российской границе завершилась, но почему-то все так же хотелось сала. Кстати говоря, до того дня я его на дух не переносила.

<div style="text-align: center;">***</div>

Вместо положенного времени, на границе я провела целых четыре часа, благополучно пропустив свой автобус. Опоздала и на следующий, и даже на тот, что был после него. Питер, водитель с работы Вениамина, час назад должен был оказаться в Севастополе.

– Но я уговорил его тебя дождаться, – по телефону сообщил Веня. – Я буду ждать тебя на заправке, которая сразу...

На этом мой мобильник сдох.

Долго не думая, я взяла такси до Симферополя и всю поездку пыталась сообразить, на какой именно заправке мне нужно быть.

– Так, где конкретно вас высадить? – спросил таксист.

– На заправке, – сказала я.

– На какой?

– Ну… Я все еще работаю над этим вопросом. 

*Итак, нам нужна заправка.*

*Которая из заправок?*

*Заправка у вокзала? Заправка на выезде? На въезде?  В центре? Обычная заправка? Заправка с хипстерами? Заправка с...*

И тут я вспомнила! Однажды жених жаловался, что ему пришлось сорок минут прождать Питера потому, что заправщик отказался обслуживать его машину. А отказался он потому, что у Питера не было с собой никаких документов кроме водительских прав. Насколько я помнила, на заправках никто не требовал показать документы на машину, разве только когда…

– А сколько в Симферополе станций, которые заправляют машины маслом?

– Маслом? – с недоверием спросил водитель.

– Ну да, или чем-то вроде того. Вместо бензина. Они еще обычно отказываются заправлять тачку, если у тебя нет на нее документов.

В свои двадцать два я сидела за рулем всего один раз. Мне было тринадцать и без травм не обошлось, так что за прошедшие девять лет я больше не посягала на место водителя и мало что знала об автомобилях. Удивительно, но таксист меня понял.

– Это, наверное, ВОГ, – ответил он.

К двух тысячи шестнадцатому году в Украине было более четырех сотен АЗС с названием WOG, но я решила пока не опускать руки.

– А в Симферополе их сколько?

– Да дохрена, – ответил водитель, а затем добавил: – Было. Понастроилась целая куча этих ваших ВОГ-ов. Куда не едешь, везде ВОГ и эти, как их там, вокруг толпятся. Они даже без машин, вы представляете! И приходят на заправку как в МакДональдз! А потом берут хот-доги с кофе, еще выбирают стоят, с пенкой без пенки. Я спешу, а они спрашивают какой процент жирности того молока и почему нет соевого. Кокосового им значит мало! А потом еще сидят прямиком на парапете, что и проехать заправиться невозможно. Как их там? Ну эти, как их там, латентные! Мальчики с наколками в огромных очках, клетчатых рубашках и старомодных шляпах с полями. На вид как голубые. 

*А на вкус как?*

– В наше время их принято называть хипстерами, – заметила я.

– А еще бывают девочки. Тоже в наколках. И выглядят они как наркоманки… Тьху!

При этих словах таксист буквально сплюнул через плечо, и я была рада тому, что, вопреки своей привычке сидеть впереди, решила расположиться на заднем пассажирском. Вместе со своими наколками.

– Так сколько таких заправок сейчас в Симферополе, вы не знаете?

– Так ведь их убрали уже! 

– Убрали?!

– Убрали. Остались только на Объездной да на Севастопольской. Там они теперь и собираются.

Водила звучал так, словно говорил не о подростках, а о собраниях НСДАП.

– А нам это по пути? – нетерпеливо спросила я.

Водитель многозначительно развел руками, что было не очень уместно, потому как мы как раз влились в плотный поток машин, образовавшийся перед городом.

– Не знаю, – ответил таксист. – Вы же так и не сказали, куда мы вообще едем.

– Значит, едем на Севастопольскую, – решила я.

<div style="text-align: center;">***</div>

ВОГ на Севастопольской мало чем отличался от других АЗС с таким же названием. Правда, ввиду локации, людей здесь было значительно меньше. В общем, создавалось впечатление, что скоро в Крыму станет еще одной заправкой меньше. В паре метров от входа лежала груда каких бесхозных кирпичей. Рядом стоял согнутый пополам дорожный знак и никаких тебе автомобилей.

– Кажется, это не то место, – с грустью произнесла я.

– Да, здесь приличной девушке совсем делать нечего, – заметил таксист.

Он уже повернул ключ зажигания и начал отъезжать.

– А вот еще один остался, – вдруг сказал мужчина. – Гляньте-ка на него! Сидит как ни в чем не бывало!

Я машинально подняла глаза, и увидела своего жениха, одиноко сидящего за заправкой на очередной куче камней. Вроде той, что лежала у основного входа. На Вене была его любимая клетчатая рубашка, повязанная вокруг пояса, майка, открывающая отличный вид на татуированные мышцы моего мужчины, те самые неубиваемые ботинки, с которыми я уже давно смирилась, его огромные очки и, конечно же, шляпа. Словом, все то, что так смущало моего водителя.

– Венька! – радостно крикнула я, так что таксист аж оторопел.

– Это ваш что ли? – удивленно спросил он.

– Мой! – все так же не скрывая радость, ответила я, расплатилась с таксистом и вылетела из машины.

Вениамин сидел в наушниках, так что я подкралась к нему сзади и игриво прикрыла глаза жениха ладонями. Не снимая наушников, Веня нащупал свое кольцо на безымянном пальце моей правой руки и воскликнул:

– Деточка!

Он тут же заключил меня в объятья, так что нам понадобилось еще минут десять, чтобы суметь оторваться друг от друга.

– Я уж думал, ты решила меня бросить! 

Счастливая улыбка не сходила с его лица, но по глазам Вениамина я видела, что тот говорит правду.

– Ну, что ты, Венька, – я вновь поцеловала его.

– Ну а что? Все-таки, два месяца почти прошло, а ты до сих пор со своей старой фамилией.

Я осмотрелась по сторонам. Кроме нас на заправке никого не было, так что как настоящий мастер менять тему, я поинтересовалась:

– А где Питер?

– Уехал за новым товаром, но обещал вернуться, если ты приедешь.

– Ну, вот я здесь.

И я улыбнулась, в надежде, что мой жених не захочет продолжать свою тему. Чувствовала себя слишком уставшей для подобных вопросов. По крайней мере, сегодня.

Но Веня не продолжил. Он лишь улыбнулся мне в ответ со словами:

– Я вижу.

Затем подхватил меня на руки и прижал к себе.

Питер приехал спустя минут двадцать. К тому моменту мы оба были слишком уставшими для вежливой болтовни, так что Веня скоренько закинул мои пожитки в багажник, и мы упали на заднее сиденье. В салоне было душно и жутко хотелось спать. Я прилегла на плечо Вениамина, и мгновенно ощутила, что в кои-то веки нахожусь именно там, где мне и нужно быть. Я была измучена бессонницей, дорогой, прощаниями, жарой и творческим кризисом, финансовыми трудностями и постоянными предательствами, но вот я вдохнула родной запах рубашки своего мужчины, и все эти вещи вдруг оказались такими далекими. 

Из окна автомобиля на нас смотрели величественные горы. Куда ни глянь, на фоне ясного синего неба виднелись их пастельные очертания, а где-то там, впереди, нас уже ждало море. Со всеми его изящными изгибами, игривыми волнами и лазурными берегами.

Таинственное, прекрасное море, каким оно бывает только в Севастополе. 



