# &nbsp; {#chapter-49}

Перенесемся в тот томный летний вечер, когда Вениамин вновь сделал мне предложение. Мы как раз закончили бродить по торговому центру. Единственным, что там купили, были билеты на вечерний сеанс новой ленты Джеймса Вана. По крайней мере, так я думала.

– Дай мне свою руку, – загадочно произнес Веня.

В этот момент мы спускались на эскалаторе. Стоял поздний час и кроме нас здесь уже никого не было.

– Ты ведь не собираешься делать мне предложение в торговом центре? – я улыбнулась.

– Нет, – как ни в чем не бывало ответил жених.

Затем он взял мою руку в свои ладони и поцеловал меня. Только когда наши губы разомкнулись, я увидела новенькое кольцо на безымянном пальце своей правой руки.

– Я дождусь, когда мы выйдем на улицу, и сделаю предложение там.

Тем вечером в воздухе царила праздничная атмосфера. На парковке почему-то звучали рождественские песни, но это лишь добавляло уюта. На мне было длинное черное платье с сумасшедшим декольте и босоножки на высоченном каблуке, что делали нас с Веней одного роста. Платье было чужим, я одолжила его у Вениной сестры, а вот трепет в выглядывающей из него груди определенно принадлежал мне.

Совсем недавно меня пугала даже сама мысль о том, чтобы добровольно связать себя узами брака. Теперь же мои щеки пылали, а сердце билось чаще, чем когда-либо. Я мельком поглядывала на державшего меня за руку мужчину, а в голове эхом отдавалась лишь одна мысль. 

Иногда я все еще вижу нас, идущих через парковку навстречу теплой июльской ночи. Поблизости нет ни души, и только Синатра поет свои бессмертные песни. 

*Он собирается сделать мне предложение. Он собирается сделать мне предложение. Он собирается сделать мне предложение.*

Не знаю, сколько десятков раз эта фраза успела прозвучать у меня голове прежде, чем мы миновали парковку. Теперь вокруг не было ничего кроме звезд да деревьев, чьи ветви успокаивающе шелестели от легких прикосновений морского бриза. 

Следуя за своим спутником, я сделала еще несколько шагов в темноту и вдруг оказалась в небольшом китайском садике, умело скрытом от чужих глаз живой изгородью. Взглянула на плавающие на воде кувшинки, на Луну, отражающуюся в стеклянной поверхности декоративного озера, на все эти каменные сооружение и растительность, украшенную неоновыми огоньками. Открыла рот и тут же закрыла его обратно, вдруг осознав, что в кои-то веки я просто не знаю, что сказать.

– Вот мы и на месте, – тихо произнес Вениамин.

Его ладони были влажными, и я поняла, что Веня нервничает не меньше моего. Он взглянул на часы.

– Прошло ровно два месяца и прежде чем ты ответишь… В общем, я просто хочу сказать, что не прекращу спрашивать до тех пор, пока ты не скажешь «да». Конечно, мне придется прекратить, если ты решишь меня бросить. Тогда я, скорей всего, буду очень много пить и трахать все, что движется в мою сторону, но ты должна знать, что…

– Ты и так очень много пьешь, Вениамин Алексеевич. Задавай уже свой вопрос пока ты не наговорил чего лишнего.

Он улыбнулся, опускаясь на колено.

– Любовь моя, ты…

– Да!

Вениамин замер с легкой улыбкой на губах. Прядь пшеничных волос кокетливо упала на лицо мужчины, которого я совсем скоро начну называть мужем, и я подумала о том, что еще никогда не видела его таким красивым.

– Ты не шутишь? – все тем же дрожащим голосом спросил Вениамин. – Ты правда выйдешь за меня?

Я не шутила.

<div style="text-align: center;">***</div>

Сколько себя помню, давнишние кинотеатры входили в список мест, где я могла чувствовать себя комфортно. Знаете, такие здания старого образца: со ступеньками возле экрана и всего одним выходом; они всегда меня очаровывали. Эти крохотные кинозалы казались мне уютными. Кресла – обычно в алой обивке – достаточно расшатанные для того, чтобы в них улечься, мягкий свет убаюкивает, а экран в десятки раз меньше IMAX-а, что позволяет развалиться прямиком в первом ряду. В кинорыночной терминологии такие кинотеатры называются моноэкранами потому, что в них всего один экран. Особенно сильно я любила приходить сюда на самый поздний и самый ранний сеансы – время, гарантирующее, что ты будешь единственным зрителем во всем зале. 

Дождливыми, ветряными и пасмурными днями, когда одиночество сильней обычного сводило меня с ума и начинало казаться, что от этой тоски уже никуда не деться, я находила спасение в кино. Просто хватала самый большой стакан кофе или чего покрепче, и полностью погружалась в просмотр. Уединение с кинематографом положительно влияло на мою нервную систему. Когда фильм заканчивался, я подолгу бродила по улицам такого ненавистного мне города, читала книги в пустующем салоне дежурного троллейбуса и думала о том, к чему все это меня приведет. 

Что ж, моя любовь к подобному времяпрепровождению была настолько сильна, что в октябре две тысячи двенадцатого один старый кинотеатр официально отменил утренний восьмичасовой показ. Им просто надоело крутить фильмы ради меня одной, так что тем утром меня встретила новенькая вывеска, сообщающая, что впредь кинотеатр будет работать с десяти. Что ж, мне, все-таки, пришлось посетить лекцию по трудовому праву, которую я так отчаянно стремилась прогулять.

Сегодня меня ждал очередной последний сеанс в пустом зале старого кинотеатра. Вот только город, в котором я находилась, не был мне ненавистен. На смену удручающим холодам и извечной сырости моего одиночества пришла сладкая летняя ночь. Воздух Севастополя был наполнен прохладой, в нескольких километрах за моей спиной волновалось море, – я практически слышала, как волны ударяются о бетонные плиты пустынной набережной, – а мою ладонь сжимала рука мужчины, которого я любила той самой необъяснимой, сумасшедшей любовью, что вдохновляла Шекспира, воодушевляла Байрона, терзала Есенина и, по всей видимости, стерла Трою с лица Земли.

Могла ли моя жизнь сложиться еще прекрасней?

По-прежнему держась за руки, мы сидели в самом центре традиционно пустующего зала. Кресла обрамляла темная кожа, но, в основном, картина мало чем отличалась от обстановки, в которой прошли мои тинейджерские годы. На экране появился Патрик Уилсон. По всей видимости, лирические отступления стали неотъемлемой частью фильмов ужасов потому, как Патрик взял в руки гитару и принялся исполнять Can’t Help Falling In Love Элвиса.

Как это всегда бывает со звуками или запахами, звучание этой хорошо забытой мелодии перенесло меня в прошлое. 

<div style="text-align: center;">***</div>

За окнами барабанит дождь. Обернувшись пледом, я сижу у приоткрытого окна. Вдыхаю прохладный воздух и закуриваю. Мне девятнадцать. На часах начало третьего утра, и я рада, что завтра воскресенье. Иначе мне еще пару часов назад пришлось бы идти на работу, где пять дней в неделю, ровно в полночь, я на ближайшие девять часов превращалась не в тыкву, но в агента технической поддержки одного небезызвестного зарубежного провайдера хостинга.

На мне наушники, из которых раздается Can’t Help Falling In Love, так что я не сразу замечаю звонок Адама, но, все же, успеваю поднять трубку. Затем тушу сигарету, думая, что Адам попросту звонит пожелать мне спокойной ночи. В последнее время что-то в наших отношениях явно не заладилось и тому было несколько тревожных звоночков. Однако я уже нахожусь на той стадии влюбленности, когда не представляю своей жизни без Адама, и это мешает мне трезво мыслить.

– Привет, сладкая, – говорит Адам. 

Он говорит, что устал. Желает мне спокойной ночи, но я слышу странные нотки в голосе любимого и спрашиваю:

– Что-то не так?

– Не совсем, – отвечает Адам. 

Он громко вздыхает, затем какое-то время молчит. Вероятно, обдумывает каждое из слов, которые собирается мне сказать. Этой паузы хватает на то, чтобы я подкурила новую сигарету и даже на то, чтобы половина ее превратилась в пепел.

Наконец, Адам нарушает молчание. Он говорит:	

– Я долго думал о нас.

Пауза.

– О том, к чему все это приведет.

Дальше я слышу монолог, в ходе которого вдруг выясняется, что мы слишком разные люди. Слышу многочисленные аргументы в подтверждение этого заявления. Про себя я успеваю заметить, что еще совсем недавно различия между нами не играли особой роли. В какой-то мере они даже нравились Адаму и лишь подстегивали его, когда я так не хотела серьезных отношений. Но аргументы продолжают сыпаться на меня. 

Один за другим, они всплывают монотонно и уверенно. Уровень выкупаемости происходящего растет вместе с количеством этих самых аргументов, и я начинаю понимать, что Адам меня бросает.

– Это все потому, что я не хочу детей? – спрашиваю я.

Он отвечает, что это всего лишь одна из причин.

– Но для меня она очень важна, – подчеркивает Адам.

*Мне всего девятнадцать, чувак, какие нахрен дети?!*

Мне вдруг становится тошно. Хочется накричать на него, напомнить, что я с самого начала предупреждала его о детях, как предупреждала о депрессии и, скорей всего, предупреждала обо всех остальных «ненормальных» оставляющих себя. 

Адам не назвал меня безумной, он был слишком интеллигентен для подобных выпадов, но я знала, что именно это его и спугнуло. Говорят, если в тебя влюблен писатель, ты можешь жить вечно. Что же касается душевнобольных, с такими – что не день, то сюрприз. 

Мужчин всегда влекло мое сумасшествие. Сперва они были им очарованы, а затем ненавидели меня за это. Могла ли я их за это винить? Едва ли, ведь никто не предлагал мне жизни без психического расстройства, а у этих людей такой выбор имеется. Так почему бы им не воспользоваться?

– Я хочу семью.

– Я знаю, – отвечаю я.

После этого мой возлюбленный приводит еще один ряд причин, по которым нам не суждено быть вместе. Теперь он уверен, что если не закончить эти отношения сейчас, мы будем все время ссориться и однажды просто возненавидим друг друга. А он не хочет, чтобы так все заканчивалось.

– Я не хочу, чтобы так все заканчивалось. Если мы встретимся, скажем, через пять лет, я хочу, чтобы у нас все еще был шанс, понимаешь?

*Потому, что через пять лет я могу захотеть детей, но до этого момента тебе лень со мной возиться?*

Я отвечаю, что понимаю, хотя на самом деле не понимаю нихрена. 

Тогда Адам благодарит меня за то, что этой осенью я сделала его счастливым, и спрашивает: что я могу сказать на все это?

Я чувствую себя заключенным, которого ведут сквозь полный зал молчаливых зрителей. Усаживают на электрический стул, закрепляют все нужные ремни и проверяют их, а потом предлагают сказать последнее слово. Мне смешно и стыдно от собственной ранимости, но именно так я себя и ощущаю. Вот только какой в этом смысл? 

Мне девятнадцать и я все еще не в курсе, что больна биполяркой, но все это не мешает мне понимать один простой факт: со мной что-то не так. Мое восприятие, ровным счетом, как и мое поведение, мои слова и поступки – все это заметно отличается от того, как ведет себя общество. Последнее, кстати говоря, мне противно. Я нахожу сегодняшний социум лживым, двуличным, и чертовски гнилым. Мне отвратительны все эти социально приемлемые нормы с их двойными стандартами и лицемерными суждениями. Ведь я вижу их насквозь и по-прежнему поражаюсь тому, как слепы все вокруг. 

Потому я несчастна. Чувствую себя невероятно одинокой и никем не понятой.

Пускай я и не знаю тому названия, но в моей голове точно есть что-то лишнее. Отличающееся от стандартного набора. Что-то, с чем я так и не смогла совладать. Я стала расстройством, расстройство стало мной и получать Елизавету Васляеву бывало все труднее и труднее. Разве что порционно, когда она (я) находилась в добром расположении духа. Я не знала, как избавиться от этой напасти, не сводя счетов с жизнью, и уж тем более не смогла бы придумать ни одной причины, которая заставила бы здорового человека желать подобной участи. Так что же, на милость, я должна была ответить Адаму?

Он заметил, что я непривычно молчалива. Затем все тем же низким, мурлыкающим басом, каким мужчины говорят только с любовницами, повторил свой вопрос.

– Хочешь мне что-то сказать?

На ум вдруг пришли последние слова Питера Мануэля, более известного как Зверь из Биркеншоу. 

*Сделайте громче радио, и я спокойно пойду.*

В общем, я сижу у окна и прекрасно понимаю, что, что бы я ни сказала, у этой истории есть только один конец. Адам хочет со мной расстаться, и ничто в моих словах не изменит его решения. Именно поэтому я говорю правду.

– Не думаю, что все это должно вот так закончиться.

Еще с минуту Адам молчит, а затем переводит разговор в нейтральное русло.

– И чем ты завтра займешься? – спрашивает он. – У тебя же выходной. Пойдешь с подружками на шопинг или вроде того?

– Я ненавижу шопинг! – эмоционально отвечаю я, на мгновенье забыв о расставании и искренне удивляясь тому, что мой молодой человек, да вообще любой человек на планете Земля, еще не в курсе того, как сильно я не люблю шопинг.

– Ну и чем тогда займешься? – спрашивает Адам.

Он улыбается краешком губ, и я буквально вижу это сквозь тысячи разделяющих нас километров.

– Это зависит от того, когда я усну, –  тут до меня окончательно доходит вся горечь происходящего. 

Я чувствую, как на глаза наворачиваются слезы и стараюсь сделать все возможное для того, чтобы мой голос звучал спокойно.

– А чем еще ты собираешься там заниматься в три часа ночи, если не спать?

– Я попытаюсь уснуть. 

Голос меня выдает.

– Слушай, – ласково говорит Адам. – Ты ведь позвонишь мне, если тебе будет плохо?

– Конечно.

Мы желаем друг другу спокойной ночи и разговор заканчивается.

Той ночью я так и не смогла уснуть. Как не смогла уснуть и многими другими ночами, когда мне было чертовски плохо. Но я так ему и не позвонила.

<div style="text-align: center;">***</div>

Заполнявшие кинозал звуки музыки умолкли, а вместе с ними исчезло и мои грезы об Адаме. И какими же удивительными показались теперь мне эти воспоминания! Такими далекими и несущественными. Я вдруг поняла, каково это: по-настоящему разлюбить кого-то. 

Оказалось, что это возможно. Оно того стоило? Этот вопрос я задавала себе миллион раз, конечно же, имея в виду, любовь. Теперь, когда я смотрела на профиль Вениамина, что, то исчезал в темноте, то вновь появлялся по ходу того, как на экране сменялась картинка, я вдруг осознала, каким ребячеством были мои чувства к Адаму. А еще большим ребячеством были те страдания, что последовали за нашим импровизированным романом. 

Все бы ничего, вот только колкая игла памяти коснулась моих мыслей. Казалось, что-то подобное уже однажды приходило мне в голову. Когда-то давно я наивно полагала, что нельзя любить сильнее, чем я любила Эрика, а затем я встретила Адама. Похоже, законы логики здесь напрочь не действовали: сколько бы боли не причиняла мне любовь, с каждым новым разом она оказывалась все сильнее.

Пара на экране взялась за руки. Они были вместе не одно десятилетие и по-прежнему выглядели влюбленными. Глядя на них, я думала о Вене. Мне вдруг стало страшно при мысли о том, что этим вечером я сознательно согласилась провести свою жизнь с одним единственным мужчиной. Я доверяла ему больше чем самой себе и это пугало меня еще сильнее.

Затем мой жених обернулся. Наши взгляды встретились, и этот страх развеялся так же быстро, как и появился.

Вениамин обнял меня одной рукой, и вновь повернулся к экрану. 

Волшебство вернулось в мою жизнь.









