# &nbsp; {#chapter-52}

Не буду врать, мне всегда нравился грубый секс. Нравилось, когда таскают за волосы, отвешивают пощечины и оставляют красные отпечатки на моей не самой тощей заднице. Мне нравились грязные словечки, мужское доминирование и еще много всякой всячины. Понятия не имею, откуда это пошло. Кажется, я просто родилась с такой вот странной тягой к насилию в голове. Естественно, та часть моего мозга, что отвечает за адекватность, отлично понимала: насилие – это ужасно. И, все же, насилие всегда меня возбуждало, и я ничего не могла поделать с этой частью Елизаветы Васляевой.

Тьма за окнами сгущалась. Занавесь колыхнулась, и в спальню проник холодок, пронизывающий до мурашек, какой гуляет исключительно в предрассветные часы. Тот самый, которого с ужасом ждут тяжелобольные пациенты сотен тысяч больниц и клиник, разбросанных по всему свету. Все они страшатся самого темного, самого серого и холодного времени суток – часа перед рассветом. По никем толком не объяснимой, но регулярно повторяющейся статистике, пик смертности тяжелых больных приходится именно на это время.

Разбросав волосы на подушке, я лежала без сна уже… Сколько? Час или два, не знаю. Говорю же, время течет совсем иначе, когда у тебя бессонница. 

Кухонные часы отбили четыре утра.

Если исходить из того, что каждую секунду умирает два человека, Земля лишилась как минимум полторы сотни обитателей, пока я бессонно валялась в постели, размышляя о загадке утренней смерти.

Как-то слишком долго не было видно Вени. Он до сих пор находился на балконе, и в какой-то момент, я даже забеспокоилась, но так и не решилась встать с постели. Ни очередного допроса, ни скандала, ни грубости мне, понятное дело, не хотелось. К тому же, я чувствовала себя до невозможности опустошенной. Мне сделалось настолько плохо, что я подозревала, что вставать с постели мне и завтра не захочется. 

Как и любые другие состояния, предполагающие неустойчивую психику, депрессивная фаза моего душевного расстройства имела свои триггеры. Рычаги давления, воспользовавшись которыми можно как выйти из депрессии, так и успешно войти обратно. Причем последнего обычно достичь куда проще.  

Что ж, той ночью Вениамину это удалось. Хотя я, разумеется, и не думала, что он делал это специально. В конце концов, никто ничего ни от кого не скрывал. Алкоголизм был одной из первых вещей, которые Веня о себе рассказал. Если быть точнее, третьей. Этот факт шел сразу же после его имени и места жительства. 

Ну, а я рассказала ему о биполярке. 

И ведь даже не докопаешься.

Занавесь вновь шелохнулась. Я натянула покрывало по самые плечи, готовясь к новому потоку холодного воздуха, но его не последовало. Вместо этого на пороге спальни появился Вениамин.

– Ты не спишь, – он кивнул.

– Нет, не сплю. А где твой ром?

Веня широко развел руки и пожал плечами. Этот привычный жест меня слегка успокоил.

Сама того не желая, я тут же вспомнила нашу весну. И наше лето. Вениамина, пожимающего плечами, когда кассир в очередной фастфудной забегаловке с робостью в голосе спросила, как он собирается съесть эту дюжину сэндвичей. Вениамина, озадаченно разводящего руки, когда его тарахтайка встала прямиком посреди оживленной трассы, и стало ясно, что доставить заказ вовремя он сегодня не сможет. Вениамина, сосредоточенно подбирающего мне кольцо в многочисленных ювелирках Севастополя: все обручалки были мне либо малы, либо ужасно велики, и Веня в смятении разводил руками каждый раз, когда какое-нибудь кольцо оказывалось не по размеру. Вениамина, который несколько недель собирался пойти со мной на пляж и решил сделать это в единственный дождливый день месяца; мы еще толком не успели отдалиться от дома, когда на город обрушился настоящий ливень. 

– И что ты мне на это скажешь? – с предсказуемой досадой в голосе спрашиваю я, глядя на пелену дождя.

Веня широко разводит руки и пожимает плечами. Рубашка на них уже успела насквозь пропитаться дождевой водой.

Я тут же вспомнила Вениамина, вернувшегося из супермаркета с пакетом, полным чем угодно, но только не тем, что было в моем списке. Вениамина, рассказывающего мне о своей дурной репутации, ходившей в его родном городе. Вениамина, принесшего мне пиво вместе сидра, Вениамина, упрямо отказывающегося идти в душ и едва ли способного назвать тому хоть одну разумную причину, Вениамина, который никак не мог поверить, что проехал нужный поворот.

– Деточка, ну там же не было знака, – все повторяет он с недоверием пятилетнего ребенка. При этом разводит руками то и дело поглядывает в зеркало дальнего вида. Так, словно ждет, будто чертов знак прямо сейчас вырастет откуда-нибудь из-под земли. – Скажи мне, что его там не было. Его же не было?

Само собой, знак был на месте. Я заметила его, когда мы возвращались домой. В ответ на мой ехидный взгляд Венька все так же пожал плечами. 

…Вениамина, планирующего нашу свадьбу в одной из центральных кофеен Севастополя; он как раз пытался понять, кого именно хочет видеть среди гостей и лишь пожал плечами, когда я спросила про его мать. Вениамина, вернувшегося с работы на шесть часов раньше просто потому, что работать ему в тот день не хотелось. Вениамина, который никак не мог понять, за то я так сильно люблю пост-панк, но почти сразу же согласившегося выгравировать на наших кольцах надпись Love Will Tear Us Apart.

– А я-то, дурак, думал, правильно говорить: пока смерть не разлучит вас.

– Нет, – я улыбаюсь. – Если что и способно нас разлучить, то только любовь.

– Я тебя не понимаю, – честно признается Веня. – Ты же знаешь, я у тебя глупенький, но если ты этого так хочешь…

…Вениамина, рассказывающего мне о том, как он учился владеть мечом, Вениамина, стыдливо признающегося в том, что ему нравится читать исключительно фэнтези, Вениамина, который никак не мог запомнить пароль от моего ноутбука, Вениамина, смутившегося, когда в троллейбусе к нему подсел местный бездомный и попросил рассказать об уходе за бородой, Вениамина, который был так рад меня видеть, что не мог сомкнуть глаз всю ночь, а затем Вениамина, проспавшего следующим утром работу.

Но прежде всего я вспомнила Вениамина, шагающего мне навстречу по пустому залу ожидания местного автовокзала. 

<div style="text-align: center;">***</div>

Вокруг нет ни души. Лишь дождь без устали барабанит по стеклам.

Он поправляет шляпу и останавливается в метре от меня. На губах играет счастливая улыбка, скрыть которую не способна ни одна борода. За плечами традиционно виднеется рюкзак, из которого выглядывает прайс-лист – последнее напоминание о закончившемся рабочем дне. 

Наши взгляды встречаются, отчего улыбка на губах будущего мужа начинает играть с новой силой. Он выглядит бледным, уставшим и чертовски очаровательным. Никто не решается нарушить молчание, так что мы просто глядим друг на друга, не прекращая при этом улыбаться. 

Странное зрелище, должно быть, вышло со стороны.       

Наконец, Вениамин делает еще шаг в мою сторону. Он не произносит ни слова. Просто широко разводит руки, предлагая мне свои объятья. Я падаю в них без лишних раздумий и тут же осознаю, что, возможно, впервые нахожусь там, где мне на самом деле стоит быть. Только вот, понимаю – не совсем правильное слово.

Я это чувствую.

Судя по всему, я не одинока в своих наблюдениях. Вениамин отстраняется всего на мгновенье для того, чтобы поцеловать меня. Сначала в лоб, затем в обе щеки. Наконец, он касается моих губ своими и мир вокруг меня кажется таким далеким. 

– Я до последнего не верил, что ты приедешь, – негромко говорит Веня. 

Он прижимает меня к себе так, словно боится, что я вот-вот передумаю, прыгну в первый же автобус до Николаева. И я отвечаю:

– Я тоже, – но я уже уткнулась носом в плечо Вениамина, так что слов не разобрать.

Они, в общем-то, и не нужны.

Вениамин обнимает меня двумя руками. Я с удивлением ловлю себя на том, что дрожу и даже не сразу понимаю, что холод здесь совсем не при чем. Мужчина, чьей женой я соглашусь стать спустя каких-то три дня, вновь целует меня, и я буквально слышу, как мое прошлое – вся моя жизнь ровно до этого самого момента – с треском сгорает где-то там, позади. 
Мне ее ни капельки не жаль. 

