# &nbsp; {#chapter-57}

Вернемся к предшествующим поездке событиям. Тем вечером я проснулась от того, что дрожу. Правда, на этот раз от холода.

– Венька, – по привычке позвала, но быстро замолчала.

События прошлой ночи одно за другим всплывали в памяти, словно изображения внутри какого-то извращенного калейдоскопа: полуночный бред Вениамина, пустые бутылки из-под рома, безжизненные глаза, крики, пощечины и пальцы, что мертвой хваткой сомкнулись на моей шее.

Балконная дверь оставалась закрытой, а дело по ту сторону перил уже близилось к ночи. Мигрень незамедлительно дала о себе знать, стоило мне поднять голову. Старая добрая мигрень – мой самый преданный жизненный спутник.

Как выяснилось, прикроватную лампу никто так и не выключил. Она продолжала тускло гореть, частично освещая комнату по ту сторону стекла. Сколько времени уже прошло? Темнело в это время года довольно поздно. Должно быть, часов семнадцать, не меньше. Я поднялась на ноги и осторожно подошла к двери. Спальня выглядела такой же, как утром, когда, после многочисленных попыток, я, наконец, смогла из нее вырваться. Подушки оказались примяты, большая часть простыни сползла на пол, а покрывало – в окружении моего ноутбука, книг, мужской одежды и пустых бутылок – валялось в нескольких шагах от кровати. Вениамина в ней не было.

Не оказалось его ни в одном из кресел, ни где бы то ни было еще в пределах видимости. По ту сторону двери царила полнейшая тишина. Я вслушивалась в нее добрых пять минут прежде, чем решилась войти. Босые ноги уже успели привыкнуть к сложившейся обстановке. Холода я больше не ощущала и,  пожалуй, смогла бы еще денек-другой провести здесь, на балконе. Стоит признать, такой расклад показался мне заманчивым. Покидать балкон совершенно не хотелось. Разве что через окно да с летальным исходом. 

Я рассмеялась. Куда громче, чем рассчитывала. 

Мысль о том, чтобы выйти на улицу через окно шестого этажа, почему-то, показалась мне забавной. Сказать больше, это была самая адекватная мысль из тех, что мне удалось отыскать в голове после пробуждения. Все остальное больше походило на выдержки из дневников наркомана, записанных во время настигших его отходняков. Это были довольно абстрактные и не всегда понятные отрывки фраз, на первый взгляд никак между собой не связанных. Словно пока я спала кто-то проглотил все мои мысли, хорошенько переживал их, а после выплюнул остатки этих славных дум обратно мне в голову – вот как это звучало.

Наконец, я отодвинула щеколду и осторожно толкнула балконную дверь, стараясь при этом издавать как можно меньше шума. Та частично отворилась. Я выглянула в открывшийся проход, но не увидела ничего, кроме ночника да полумрака. Тогда я толкнула дверь сильнее. 

БАХ, ответила мне дверь.

Она наполовину отворилась и с глухим стуком ударилась о что-то тяжелое. 

От неожиданности я даже вскрикнула: этим чем-то оказался мой муж. Подобно прикроватной лампе и всему, что ее окружало, Вениамин тоже оставался нетронутым. Он так и лежал на полу, около выхода на балкон. В той же позе и без одежды. 

Мой крик не произвел на Веню должного впечатления. Присмотревшись к нему, я поняла, что зря парилась насчет шума. Вы когда-нибудь слышали о спячке, в которую алкоголик впадает после того, как спирт в крови достиг максимального уровня? В таком состоянии его сложно отличить от трупа. Частенько можно встретить случаи, в которых ни в чем не повинных уличных бухариков доставили в больницу потому, что обеспокоенные прохожие попросту приняли их за покойников. 

Должна признать, сходство и впрямь удивительное. Не знайся я с алкоголиками прежде, непременно бы испугалась состояния своего избранника. Он был бледней обычного и выглядел так, словно замерз. Вениамин дышал беззвучно и очень-очень плавно, что делало движения его грудной клетки неуловимыми для невооруженного глаза.

Понаблюдав эту картину еще пару минут и крепко убедившись в ее неизменности, я перешагнула через обездвиженный силуэт и вышла из спальни. Прошла по темному коридору и свернула на кухню, где машинально заварила целый чайник черного чая, самого крепкого из тех, что я смогла найти, а затем взяла в руки блокнот. Я потянулась к нему, скорей, по привычке, и была искренне удивлена, когда на неразлинованной странице появилась первая строка. За ней последовала еще одна, а той и все остальные. 

– Да ладно! – воскликнула я, наблюдая за тем, как из-под моей руки появляются новые строки.

Последние месяцы я была счастлива как никогда, но не могла при этом и слова из себя выдавить. Писательский блок стал единственным, что омрачало лето две тысячи шестнадцатого. Без прозы я чувствовала себя потерянной и заблудшей. Казалось, без писательства я лишь напрасно проживаю эту жизнь. Как бы много усилий я не прикладывала, за все это время из-под моего пера не вышло ничего хоть отдаленно напоминающего стоящий текст.

Сегодня же буквы вылетали из меня как пули из пулемета. Они складывались в предложения. Те становились абзацами, которые, в свою очередь, превращались в полноценные главы. И, как это всегда бывает во время творческих припадков, я просто не могла остановиться. На моей правой руке проступили привычные рабочие мозоли: один на большом пальце и еще несколько на безымянном, там, где карандаш касался кожи. Они начинали ныть каждый раз, когда я выводила в блокноте новое слово, но даже эта боль казалась мне самым прекрасным чувством на свете. Сказать больше, я обрадовалась ей как ребенок, пришедший на долгожданную встречу с Сантой. За годы, проведенные над рукописями, я успела привыкнуть к таким ощущениям. Стала относиться к ним как к признаку собственной продуктивности и даже начинала волноваться, если к концу дня рука болела меньше обычного.

– Быть того не может, – бормотала я, перелистывая заполненные только что блокнотные листы. 

Мой почерк был из компактных, но тем вечером я исписала больше тридцати страниц.  

– Быть того не может! – решила я и пересчитала еще раз.

Вышло тридцать две страницы, как и в первый раз. Тридцать две страницы, глядя на которые я почувствовала резкий прилив сил и при этом понимала, что сегодня я вполне смогу написать еще с полсотни страниц.

То, чего мне никак не удавалось добиться жаркими днями и тихими вечерами, теперь происходило так естественно и непринужденно. Все, что мне нужно было сделать, так это взять в руку карандаш и раскрыть блокнот на чистой страничке. Остальное происходило само по себе. Слова выскальзывали из моей головы с бывалой скоростью как в старые добрые, и я поспешно записывала их на бумагу.

– Но что изменилось? – время от времени я задавала себе этот вопрос, но так и не могла найти на него ответ.

Только когда стрелка кухонных часов перевалила далеко за полночь, я с неохотой оторвалась от писанины. Это случилось, когда я отвлеклась, чтобы заглянуть в спальню. Сказать, что по отношению к Вене я испытывала очень противоречивые чувства, не сказать ничего. Покидая балкон, я была уверена, что сержусь на него самым яростным в мире гневом. В тот мрачный миг мысль разорвать эти отношения пока еще не так поздно впервые мелькнула в моей голове. Но все забылось, как только я взяла в руки блокнот, а спустя пятьдесят рукописных страницы и вовсе бесследно исчезло. 

Глядя на проделанную работу, я растирала волдыри, что образовались на пальцах, и не могла поверить царившему в душе спокойствию. Возможность превращать мысли в книги вернулась, и это делало меня по-настоящему счастливой.


