# &nbsp; {#chapter-67}

Увольняясь со «Штиля», я собиралась посвятить все свободное время писательству, но даже с ним у меня теперь не клеилось. Как и в прошлый раз, пьянство мужа и последовавшие за этим приключения плодотворно сказывались на моем творчестве. 

Еще в Севастополе Вениамин дал мне слово не напиваться, и на самом деле не брал в рот и капли алкоголя. И, все же, за день до выезда из Керчи, он вдруг принял экстренное решение ужраться в стельку. Что и проделал это с небывалой скоростью, словно пытался компенсировать проведенные в трезвости недели.

– Ну, наконец-то! – радостно воскликнул мой муж, приложившись к портвейну.

Скорей всего, ничего бы не случилось, ограничься он одним портвейном. Но за крепленым вином последовало обычное полусладкое, а за ним подтянулся и весь алкогольный список, что включал в себя водку, пиво и даже домашнюю цитрусовую настойку. 

Под воздействием перечисленных выше жидкостей Вениамин оживился. 

– Хочу в Керчь! – заявил он и исчез на чердаке, чтобы переодеться.

Убедившись, что дверь за его сыном захлопнулась, Алексей Вениаминович повернулся ко мне и полушепотом произнес: 

– Нельзя его отпускать. В таком состоянии никак нельзя.

– И что вы предлагаете? – без особого интереса спросила я.

– Как что? Скажи, что ты против, – вмешалась Света. – Скажи, что ты строго-настрого запрещаешь ему ехать!

Хоть и вдрызг пьяный, Веня выглядел весьма доброжелательно. Конечно, от количества потребленной выпивки он сделался гиперактивным и шумным, но в остальном не особо отличался от своей трезвой версии. Более того, собираясь на последний автобус из Аджимушкая, Вениамин только не светился от счастья. Сейчас радости в нем было не меньше, чем алкоголя, но ситуация в любой момент могла круто перемениться. Одной попытки помешать долгожданному веселью моего мужа вполне хватило бы для того, чтобы вызвать новый приступ гнева.

– С ума, что ли, сошли? – не веря своим ушам, поражалась я, переводя взгляд то на отца Вениамина, то на его любимую женщину. – Или это у вас такие шуточки?

Первым меня понял Алексей Вениаминович. По всей видимости, он прикинул в голове предстоящий расклад событий и одарил меня виноватой улыбкой, что как два капли воды была похожа на виноватую улыбку его сына. Последней я уже давно не видела, и мне совсем не хотелось это менять.      

– Тогда надо его переубедить, – стояла на своем Света. – К тебе он прислушается.

На следующий день выяснилось, что она никогда не видела Веню по-настоящему пьяным. Мне стоило сразу об этом догадаться.

– Ты единственная, кого он вообще слушает, – говорила женщина. – Леш, ну разве не так? 

Но Вениамин к моим словам не прислушался. Как не прислушался и к словам своего отца. До слов заботливой мачехи моему возлюбленному тоже не было дело. В прочем, как и до тех, что были сказаны ее дочерьми.

– А я хочу кутить! – весело заявлял Веня в ответ на всяческие уговоры остаться.

Он впрыгнул в вечерний автобус, и мне пришлось сделать то же самое.

– Хочу гладить козла! – неожиданно объявил мой мужчина, как только мы сошли с автобуса. 

Услышав о его новом желании, я залилась смехом. Вениамин заулыбался еще шире. Он нетерпеливо тряс меня за руку, напоминая большого ребенка, и изо всех сил старался увести меня в нужном ему направлении со словами: 

– Хочу гладить козла! Пусти меня гладить козла! 

Его поведение меня совсем не раздражало. Как ни странно, оно даже показалось мне умилительным.

– Какого такого козла? 

– Вон того, – серьезно ответил Веня, показывая куда-то перед собой.

Вдали у забора по другую сторону дороги промелькнуло какое-то движение. Только подойдя ближе, я увидела несколько рогатых животин, синхронно поедающих ветки сирени. 

– Ты имел в виду какого-то конкретного козла? – спросила я, когда мы уже переходили на другую сторону улицы.

– Ну а то! 

– Какого?

– Вон того! – он указал на белоснежного козла, чья борода оказалась самой длинной. 

– Что ж, вполне логично…  

Веня остановился в метре от животного, протянул к нему руку и замер.

– Ну, так можно? 

Я поняла, что он и в самом деле ждет моего разрешения. 

– Конечно, можно, – ответила я сквозь смех.

Затем достала из пачки сигарету и, подкурив ее от последней спички, с улыбкой наблюдала за происходящим. Увы, идиллия, возникшая между керчинским козлом и моим мужем, оказалась не долгой. Ее нарушил визг старухи, что вдруг выпрыгнула из-за куста сирени как чертик из табакерки. 

– ПОПАЛИСЬ!

Напуганные шумом животные разбежались по сторонам. Все, кроме Венькиного козла. Тот, как ни в чем не бывало, продолжал томно жевать оккупированную ветку. 

– Ваш козел? – по-старушечьи прищурившись, спросила хозяйка куста сирени.

– Никак нет, – ответил Веня, который все так же продолжал поглаживать по носу своего нового фамильяра.  

Однако, старуха нам не поверила. Возможно, виной всему был обыкновенный маразм, а может этот рогатый уже пятнадцатый год терроризировал ее живую изгородь. Как бы там ни было, бабуля явно не собиралась вести переговоры. Она нырнула руками в карман своего передника и, наполнив ладони мелкими камнями, стала бросаться ими во все стороны. Козел сбежал с места преступления первым, но старуха не останавливалась. Несколько камешков угодило в стоявшего рядом Вениамина, так что тот подхватил меня за руку, и вскоре злобная старуха превратилась в крохотную точку позади нас.

Чуть позже выяснилось, что муж где-то выронил свою зажигалку. Частный сектор по обе стороны от нас не спешил заканчиваться, а магазинами тут и не пахло. Дело шло к восьми вечера, кроме нас на улице, как назло, никого не было. Тогда голову моего мужчины посетила следующая мысль. Он решил тормозить проносящиеся мимо нас попутки.

– Так это ж гениально! – я рассмеялась. – Они остановятся потому, что будут думать, что ты голосуешь. К тому же, даже у некурящих водителей имеется прикуриватель.  

Схема с попутками сработала с первым же притормозившим автомобилем.  

*Какой чудесный вечер*, подумалось мне. *Только бы он таким и остался.*

Я отмахнулась от унылых мыслей, и продолжила идти по покрывшейся испариной дороге, с нетерпением ожидая момента, когда дневная духота, наконец, отступит, открыв путь ночной прохладе. 

Потребовалось еще минут пятнадцать-двадцать, чтобы достичь пункта назначения, а что было дальше вы и так знаете. Той августовской ночью Вениамин снова обратился незнакомцем с серыми глазами. Он впал в исступление и причинял мне боль, за которой последовал сильнейший упадок духа. После него я, как и в прошлый раз, не могла спать или есть, но вот слова… Как по волшебству, они стремительно высыпались из-под пера, создавая новые и новые строки.  


