# &nbsp; {#chapter-73}

– Может, психиатры не так уж и ошибались?

– Какие еще психиатры? – раздалось в ответ, и я поняла, что подумала эту мысль вслух.   

– Которые считали, что я подсознательно запрещаю себе быть счастливой.

– Как-то это совсем нелогично. Зачем кому-то запрещать себе быть счастливым?

*Затем, чтобы потом не быть несчастным, конечно же.*

Ответ на этот вопрос казался мне до невозможности очевидным. Я вновь подумала, что терапевты вполне могли оказаться правы.

– Понятия не имею.

И я крепко поцеловала Вениамина, предотвращая появление новых вопросов. 

Я могла бы многое рассказать ему о докторах, лечении, психическом расстройстве с которым жила почти десятилетие, о его фазах и симптомах. О психоанализе, закрытии гештальтов, гуманистической психологии, бихевиоризме, разговорной, экзистенциальной, когнитивно-поведенческой, интерперсональной и социально-ритмической терапии, о стабилизаторах настроения, антидепрессантах, бензодиазипинах, антипсихотических препаратах и так далее по списку. 

Мой багаж знаний по части психиатрии никогда не прекращал пополняться, и я могла провести вечность, демонстрируя его слушателю. Этих историй хватило бы как минимум до наступления две тысячи двадцатых, но мне не хотелось загружать ими Вениамина. Подобные россказни были последним, что ему требовалось по завершении тяжелого рабочего дня.  

– А такое вообще возможно? – спросил Веня, как только наши губы рассоединились.

– Что?

– Не разрешать себе быть счастливым. Еще и делать это неосознанно. Разве такое возможно?

– У меня вот не получилось, – я улыбнулась. – А ведь я эксперт в том, как быть несчастной.

На этой ноте Веня отворил входную дверь, и мы завалились домой.

– Постой-ка, постой-ка, – произнес он, улыбаясь собственным мыслям. – Так значит, ты со мной, все-таки, счастлива?

– Бывает, – бессовестно соврала я.

До нашей встречи я никогда не чувствовала себя счастливой дольше пары часов. Я частенько бывала веселой, общительной, энергичной и всецело увлеченной какой-нибудь новой идеей. Много шутила и быстро становилась душой компании, во многом благодаря маниакальным эпизодам таившегося во мне психоза. 

О том, что такое счастье, – не мимолетная радость, не восторг или удовольствие, а самое настоящее счастье, что согревало сердце и не давало опустить руки, даже когда все в этом мире было против меня – я узнала лишь после знакомства с Вениамином. До этого я и вовсе не подозревала, что подобное чувство существует вне любовных романов и уж тем более не думала, что оно так долго может оставаться в моей душе. 

Счастье всегда представлялось мне чем-то хорошим, а все хорошее обычно заканчивалось, едва успев появиться в моей жизни, так что я уже давно не удивлялась эмоциональным качелям, что то и дело подкидывала мне судьба. Но вот мы прожили вместе почти четыре месяца, что, правда, ощущались как пару лет, и, несмотря на алкоголизм со всеми вытекающими из него последствиями, периодически прогрессирующую шизофрению и прочие прозаические неприятности, Веня был первым и единственным человеком, которому удалось сделать меня счастливой. Какой бы отвратительный не выдался день, я забывала обо всех проблемах, стоило мужу заключить меня в объятья, а один-единственный теплый взгляд его изумрудных глаз мог вызвать во мне сладкое чувство эйфории.

Конечно, будь у него такое желание, Веня с той же легкостью мог сделать меня самой несчастной девушкой на свете. Наша любовь наполняла меня новыми силами перед лицом всего мира и, вместе с тем, делала меня чертовки слабой, когда дело казалось самого Вениамина. Она заставляла меня быть ранимой только для одного мужчины, защищая от остальных семи с половиной миллиардов людей, населявших Землю в две тысячи шестнадцатом году. Но, прежде всего, наша любовь наполняла меня счастьем, что так и не исчезло, и лишь росло с течением времени. 

– Ты и впрямь бываешь со мной счастливой? – переспросил Венька, смущенный лаконичностью прошлого ответа.

– Гораздо чаще, чем ты думаешь.

На этот раз, мой ответ оставил Вениамина довольным. В ярком свете дневных ламп, я видела, как его глаза засияли сотнями малахитовых огоньков, а на губах показалась по-мальчишески мягкая улыбка.

*Похоже, он на самом деле счастлив*, подумалось мне.

Эта мысль теплом разлилась по моему телу, заставив сердце волнительно трепыхаться в груди. Словно дело было не за столом, где мы ужинали изо дня в день, а на первом свидании, которого у нас на самом деле никогда не было.

Уложив подбородок на ладони, я неспешно разглядывала сидевшего напротив мужчину. Эти широкие плечи, пшеничные волосы, покрытые шрамами и татуировками руки и едва заметные родимые пятна, местонахождение которых я могла указать не глядя. Изумруды продолжали пламенем сиять в глазах моего мужа, и, ох, как же сильно я его любила!

Пройдясь по каждому из открытых участков тела, я почему-то вспомнила о загаре, что покрывал Венькину спину. Затем подумала о созвездиях родинок, хаотично разбросанных вдоль позвоночника, а спустя несколько секунд, я уже раздевала своего мужчину взглядом.     

От собственных мыслей мне сделалось жарко. На щеках проступили первые краски румянца. Я чувствовала, как их количество увеличивалось с каждой новой деталью, что рисовало мне воображение. Когда жарко превратилось в душно, я попыталась прервать это ментальное раздевание. Подняла голову с ладошек, случайно перехватила взгляд Вениамина, и неожиданно поняла, что все это время муж делал то же самое.

Все так же безмолвно, мы одновременно встали из-за стола и теперь находились на расстоянии пары метров. Веня преодолел его за долю секунды. Одной рукой он обнял меня за плечи и, поглаживая рассыпавшиеся по ним волосы, медленно провел языком по моим губам. Вениамин покрывал мои лицо, шею и плечи поцелуями, от нежности которых подкашивались колени. Его свободная рука скрылась под моей юбкой, и тишину кухни пронзил слетевший с моих губ стон.

Ни один из нас так и не проронил ни слова, когда Веня обхватил меня за талию и усадил на стол, не отрываясь от поцелуев. Из них вдруг исчезла вся нежность. Ее сменила бешеная страсть, и это еще сильней вскружило мне голову. Грохот пульсирующей в ушах крови затмевал все окружающие нас звуки, создавая атмосферу полнейшего уединения. Я позволила себе в ней раствориться, откинулась назад и легла на скатерть. Вениамин кусал мои губы, будоража кожу горячим дыханием. Он среагировал молниеносно: мои ноги оказались на его плечах еще до того, как лопатки коснулись деревянной поверхности стола. 

Прежде чем мы занялись любовью, Венька откинул назад упавшие на лоб волосы. Его лицо целиком и полностью излучало вожделение, но даже густой пелене похоти не удалось скрыть счастье, что по-прежнему сияло в глазах моего мужа. 

Если подумать, уязвимость перед любимым человеком была не такой уж высокой платой, учитывая все то, что я получала взамен.

