# &nbsp; {#chapter-74}

Да, уязвимость казалась мне мелочной платой за любовь и счастье, что она приносит. Но вот прошло совсем немного времени, и наступил последний день лета, который заставил меня усомниться в адекватности таких мыслей.

Это случилось где-то в первой половине дня. Погода была солнечной, небо безоблачным, а птицы пели так звонко, что создавалось впечатление, будто им за это приплачивают. В общем, ничего не предвещало беды. Это был ничем не отличительный летний день в Крыму. Каких уже было много и, как я думала, будет еще больше.

Помню, я стояла на террасе: развешивала мокрое белье и пыталась придумать, что бы приготовить на ужин. Содержимое холодильника и нелюбовь к готовке не оставляли особого выбора, но мне хотелось порадовать мужа. Я уже подумывала бросить это гиблое дело и просто состряпать что-нибудь съедобное, когда раздался звонок.

На экране телефона высветился неизвестный мне номер. Вернее, не совсем известный…

Меня всегда напрягало то, как усердно муж скрывал содержимое своих гаджетов. Он знал пароли от всех моих устройств и ежедневно ими пользовался, но никогда не позволял мне взять в руки свой мобильный. Валя говорила, что виной тому предыдущие отношения ее брата. Мол, Римма постоянно шарилась в его переписках и всячески ограничивала любые контакты с противоположным полом, чем оставила неприятный осадок, и я могла это понять потому, как и сама состояла в подобного рода отношениях.

Тем не менее, эта информационно-технологическая скрытность не давала мне покоя. Не всякая из попоек моего мужа заканчивалась агрессией или рукоприкладством, но, выпив все, что было в доме, он каждый раз забывался мертвым сном. Еще весной я заметила подозрительную активность в звонках и сообщениях Вениамина. Они исходили от номера, который даже не числился в адресной книге моего мужа.

– Не хочешь ответить? – спрашивала я после очередного пропущенного звонка.

– Я не отвечаю незнакомым номерам в такое время, – обычно отвечал Веня.

И, все-таки, я очень быстро запомнила тот телефонный номер. Ведь нужно быть последней дурой, чтобы не догадаться, кому принадлежали исходящие от него попытки общения.

Подобное повторялось не раз, чем вызывало во мне все новые и новые подозрения. Поднимать панику без сколько-нибудь стоящих аргументов было не в моем стиле, а тут еще эти чертовы врачи, убеждающие, что я нетрезво воспринимаю действительность и, к тому же, подсознательно ищу зло в окружающих.

В общем, я решила раз и навсегда разрешить эту дилемму. Однажды я украдкой подсмотрела пароль от мобильного Вени и воспользовалась им, стоило последнему впасть в алкогольную спячку. Хорошего в этом было мало, я знала. Вторжение в личное пространство любимого человека вызывало во мне отвращение. Это было недопустимым нарушением границ доверия, но я ничего не могла с собой поделать. Как и следовало ожидать, те звонки и сообщения были от Риммы, и мне сделалось еще более совестно, когда я увидела, что муж ей так ни разу и не ответил.  

Выходит, я только зря предала его доверие, подумала я, глядя на храпящего под боком Веньку.

Оставалось лишь надеяться, что он никогда об этом не узнает.

Увы, эти звонки редко, но, все-таки, продолжали поступать, пока мы жили в Севастополе. Они не исчезли и в Керчи, и даже когда мы перебрались в Симферополь. Последний так вообще случился прошлым вечером, и тут уж моя душа не выдержала. Наступившим утром я проводила мужу на работу и набрала хорошо отпечатавшийся в памяти номер. Трубку никто не снял, так что я растворилась в домашних хлопотах и думать забыла об этой затее, но прошло несколько часов, и чириканье птиц заглушил звук моего мобильного.

Звонили предыдущие отношения Вениамина.

– Вы мне утром звонили, – произнесли по ту сторону телефона – а я не расслышала. Только проснулась.

Ее голос был низким и отдавал хрипотцой, которую большинство мужчин считает сексуальной. Он звучал до ужаса знакомо, но я была уверена, что прежде никогда его не слышала. И только уловов полное отсутствие звука «р» в речи Риммы, я поняла, почему ее альт казался таким знакомым. Я бы с легкостью могла спутать его с собственным голосом.

– Не хотела тебя будить, – в моих словах не было и толики злости. – Я всего лишь хочу узнать, что тебе нужно от моего мужа?

– Лиза?

– Да, это я.

– Как я рада тебя слышать! Я так давно хотела с тобой познакомиться!

Ее слова меня слегка обескуражили.

– Это еще зачем?

– Как зачем? Ты мне сразу понравилась, но Веня сказал, что убьет меня, если хоть шаг в твою сторону сделаю.

– Окей…

Я почти забыла, на кой черт вообще сюда звонила.

– Но у тебя нет поводов волноваться. Даже когда я встретила Веню на прошлой неделе, я просто кивнула ему и прошла мимо. Я не сделала ничего плохого, клянусь.

Уж не знаю, было здесь дело в моей пресловутой интуиции или в чем-то еще, но я тут же спросила:

– А кто сделал?

В трубке повисла затяжная пауза. Я знала, что на самом деле нервные клетки не способны гибнуть от стресса, но во время этого молчания буквально чувствовала, как, один за другим, мои нейроны сводят счеты с жизнью.

– Римма? – не выдержав, позвала я. – Ты хочешь мне что-то сказать?

– Угу.

Она продолжала молчать.

– Мы остановились на том, что ты не сделала ничего плохого.

– Да…

– Но?

– Но я не могу сказать того же о твоем муже.

– Выкладывай.

– Это произошло в Керчи, – говорила Римма, и я слышала, с какой силой она выталкивает из себя каждое слово, – в ту ночь, когда он выгнал тебя на улицу.

– Ты и об этом знаешь?

Этого я точно не ожидала.

– Ну да. Я спросила, где ты, как только он мне написал.

– Логично.

– Я как раз собиралась спать. Лежала дома и пересматривала «Королеву проклятых», как вдруг начали приходить сообщения. Много сообщений. Он спрашивал, что я делаю. Настаивал на том, чтобы встретиться. А когда я прямо спросила, зачем, ответил… – это была самая мучительная пауза в моей жизни. – Он ответил, что соскучился и хочет заняться со мной сексом.

Пришла моя очередь молчать.

– Лиза? Ты еще здесь?

– Да.

– И что ты на все это скажешь?

– Неплохой фильм, – спокойно ответила я. – Правда, «Интервью с вампиром» нравится мне намного больше.

– И все?

– А ты ждешь, что я начну орать на тебя за чужое дерьмо?

– Ох, прости меня! Я должна была сразу же обо всем тебе рассказать, но…

– Так вы встретились?

– Нет, нет, нет! Мы не встретились. Следующим утром Веня написал мне. Говорил, какой он мудак и что сам рушит свое счастье. Он умолял меня ни о чем тебе не рассказывать.

– У тебя еще есть эта переписка? – спросил человек, который никогда не устраивал скандалы без соответствующих доказательств.

– Есть.

– Можешь мне ее прислать?

– Он убьет меня, если узнает, что я тебе все рассказала!

– Не убьет, не переживай.

– Он угрожал мне.

– Неужели я должна поверить тебе на слово? Ты ведь до сих пор к нему не остыла. Думаешь, я этого не вижу? Так как я могу поверить твоим словам без доказательств? – повторила я, хотя на самом деле ей верила.

Я умела убеждать. Спустя пару минут переписка была у меня и, должна сказать, в своем рассказе Римма явно пыталась пощадить мои чувства. Я прочла этот текст дважды, когда телефон вновь зазвонил.

Это был Вениамин.

– Звоню узнать, как там дела у моей деточки, – с привычной бодростью в голосе говорил он. – Я в торговом центре и меня тут появилась свободная минутка. Хочешь, зайду в супермаркет и куплю че-нить к ужину?

– А в этом супермаркете есть строительный отдел?

– Думаю, да, а что?

– Тогда купи мне, пожалуйста, какую-нибудь прочную веревку.

– Какую веревку?

– Покрепче той, на которой мы сушим белье. Двух метров будет вполне достаточно.

– Зачем тебе веревка? – с недоверием спросил муж, и я слышала, как он улыбается в ожидании очередной шутки.

– Я собираюсь на ней повеситься.

– Ну, что ты такое говоришь, радость моя! Ты ведь только-только вышла из депрессии. Откуда такие мысли?

Притворяться дольше я не могла.

– Самовлюбленный сукин сын! – крикнула я, распугивая последних птиц, оставшихся на террасе. – Выставил меня за дверь и тут же принялся писать своей бывшей. Я-то никак не могла понять, отчего это ты вдруг стал таким заботливым! А теперь вот не могу понять, как я могла стать такой слепой!

Вениамин тяжело вздохнул.

– Ты говорила с Риммой?

– А ты приглашал в гости еще кого-нибудь?

– Вот же мразь! Никак не может оставить нас в покое!

Я рассмеялась.

– Лизонька, милая, успокойся. Может, я и ответил на какое-то из ее сообщений, но я ничегошеньки не помню о той ночи.

– Все ты помнишь!

– Девочка моя, ну ты же знаешь, что со мной происходит во время запоя. После него я ничегошеньки не помню. А эта завистливая тварь…  Она бегает за мной с самого расставания! Она что угодно тебе скажет, чтобы разрушить наше счастье!

– Но ты все помнил, когда писал ей на следующий день.

Тогда муж предпринял еще несколько попыток оправдаться. Он говорил о том, как сильно любит меня и что его бывшей нельзя доверять, то и дело настаивая на ее сумасшествии.

Вениамин засыпал меня бесконечными аргументами, но все они потеряли свою силу, как только я сказала:

– Хватит уже, Веня. Я читала вашу переписку.

Похоже, этим я застала его врасплох.

– Ты унизил меня при своих друзьях! Оскорбил меня и выставил на улицу в два часа ночи! В городе, которого я не знаю! Где у меня нет ни друзей, ни даже знакомых! И тут же бросился ей писать!

– Лиза, Лизонька, любовь моя, обещаю, я все тебе объясню, – повторял Веня, лишившись последнего аргумента. – Радость моя, любимая, счастье мое, ну, прошу тебя, не молчи.

Я молчала.

– Васляева, я ведь так сильно тебя люблю! Прошу тебя, никуда не уходи до того, как я вернусь. Я отпрошусь с работы пораньше и дома мы все...

На этом я повесила трубку.

Вопрос с ужином, наконец, перестал теребить мои мысли. Теперь оставалось понять, как именно я хочу расстаться с жизнью.

