# &nbsp; {#chapter-89}

Двадцать лет. Переломный момент.

В чем конкретно заключается его переломность – толком не было ясно, но с возрастомстановилось понятно: она определенно была.

Помню, как совершенно случайно сделала третью татуировку, а затем так же случайно проколола бровь. У меня были красные волосы. Густые алые волосы ниже лопаток, которые всем так нравились. В этот цвет я, кстати говоря, тоже перекрасилась по случайности. В двадцать лет я все делала на моменте. Просто потому, что моментом и жила. Ведь я никогда не планировала состариться, помните?

Похоже, навязчивая идея покончить с жизнью в двадцать три, временами играла мне на руку.

В те дни я была уверена в том, что Адам – это все, что мне нужно от жизни. И ничего в мире не могло убедить меня в обратном. Именно поэтому мне было так больно после нашего разрыва. Разумеется, теперь эта боль казалась мне детской, не говоря уже о том, что я думала насчет своей подростковой привязанности к Эрику. В обоих случаях прогрессирующее биполярное расстройство могло бы стать оправданием моему поведению. Но, почему-то, не стало.

Тем не менее, я совершенно не ассоциировала себя с той, старой Лизой. Конечно же, я ничего не забыла, но ее поступки не были моими поступками, а слова или мысли – те так и вовсе казались мне чужими.

– Я хочу, чтобы вы написали мне имена мужчин, которые повлияли на вашу жизнь, Елизавета, – однажды сказала мне двенадцатая по счету психотерапевт.

Это случилось в феврале. Спустя тысячу сто пятьдесят семь дней после того, как мне стукнуло двадцать. И спустя месяц после того, как Вениамин приказал мне оставить ключи под ковриком.

Я спросила:

– Каким образом повлияли?

– Это не важно. Просто напишите первые имена, которые приходят вам в голову. Может быть, негативный любовный опыт. Подумайте о боли. Напишите имена тех мужчин, которые причинили ее вам.

*Подумайте о боли – это я умею.*

И я написала: Эрик, Адам, Вениамин.

– Теперь напишите имена тех, кого вы любили, – продолжила Ольга.

На мой первый список она не взглянула.

– Тех, с кем хотели серьезных отношений.

И я вновь написала: Эрик, Адам, Вениамин.

– Теперь я хочу, чтобы вы написали имена мужчин, в отношениях с которыми были счастливы.

*Или думали, что счастливы*, лукаво заметил внутренний голос.

И вновь те же на манеже.

Эрик.

Адам.

Вениамин.

– Сравните списки, – сказала терапевт, хотя не так много мужикову меня было, чтобы сверять списки. – Видите?

– Неужто зреньем бог меня обидел, чтоб я на небе солнца не увидел?

– Что?

– Это Шекспир. Можете не продолжать.

Но доктор продолжила. Такая вот у нее работа.

Мы разложили по полочкам некоторые мои воспоминания. Речь шла только о самых ярких – в плохом или хорошем смысле – моментах, так что еще десятки сотен воспоминаний остались беспорядочно кружить в памяти. Поговорили о моем первом сексуальном опыте и о том, почему меня так много лет возбуждало насилие.

При этом Ольга постоянно спрашивала о том, не посещают ли меня суицидальные мысли. По ее мнению, вид у меня был не очень.

– Очень дерьмово выглядите, – так она и сказала. – Нельзя себя так истязать. Иначе вы этого не переживете. Не с вашим прошлым и не с вашим диагнозом.

Понятное дело, я знала, о чем она говорит. Бледность кожи бывалого героинщика, впавшие щеки и мешки под глазами, способные позаботитьсяо картофельном запасе Беларуси вернулись. Дома у меня было зеркало, и я все еще помнила, как им пользоваться, а потому и без доктора знала: ситуация действительно была так себе.

– Как часто у вас бывают суицидальные мысли? – повторила свой вопрос психотерапевт.

Она сменила тактику и больше не ставила под вопрос наличие у меня желания самоубиться. Врать мне никогда не нравилось, и я продолжала увиливать от ответа. На сеанс я пришла с револьвером, заряженным всего одной пулей. Его увесистая рукоятка оттягивала карман моего пальто, и я придерживала ее кончиками пальцев на протяжении всего разговора с терапевтом.

– Не-а, – наконец, ответила я. – Уже давно не бывают.

На самом деле, я никогда не хотела открываться Ольге, как глубоко в душе не хотела открываться и другим своим психотерапевтам или психологам. Ничего из того, что говорила доктор, не стало для меня новостью. Транки, которыми меня пичкали, лишь усугубляли ситуацию. Физически я была заперта внутри себя, но морально…

Поток терзающих меня мыслей не знал конца и края, а невозможность отдать эти думы бумаге убивала куда сильнее. К тому же, еще до совершеннолетия выяснилось, что все эти анти-шизоидные препараты меня попросту не берут, как не берут и многие психоделики. Сколько их не принимай, от психотропных у меня были одни побочки.

Зачем тогда мне понадобилось приходить на этот сеанс еще и с револьвером в кармане?

Наверное, мне просто нравилась Ольга. Она была умной и опытной женщиной, которая прекрасно понимала возможную степень человеческого сумасшествия. А мне как раз нужен был такой собеседник. Вообще, выбросить несколько тысяч на терапевта – это, пожалуй, лучшее, что может сделать для своих близких такой человек как я. Мне не хотелось никого грузить.

– А сейчас вы все еще хотите? – спросила Ольга.

– Хочу чего? Убить себя?

Тут я вдруг поняла, что потеряла нить разговора. Док смотрела на меня неодобрительно. *Я так и знала*, говорил мне этот взгляд. И вот я осознала, как жестоко облажалась.

– Мы говорили о ваших мужчинах, – напомнила терапевт. – О тех, с которыми вы когда-то хотели иметь серьезные отношения.

– Ах, да…

– А что сейчас? Все еще хотите?

Она указала своим многократно окольцованным пальцем на короткий список имен.

Эрик, Адам, Вениамин – вот как прошла моя жизнь. По крайней мере, та ее часть, которой уже точно не вернуть. Я смотрела на имена своих бывших возлюбленных так, словно вижу их впервые. Ответа на вопрос доктора я не знала. Все, чего мне теперь хотелось, это не чувствовать все то, что я чувствовала.

Мое время истекло. Сеанс назначили на утро, и в половину одиннадцатого я уже вышла из кабинета своего психотерапевта. Это был последний раз, когда мы виделись.
