# &nbsp; {#chapter-90}

На улице моросил дождь. Знаете, такой ледяной навязчивый февральский дождь, который не прекращается по три дня к ряду.

Такими днями жизнь вне дома становится максимально неуютной. Все вокруг залито грязью. Она течет вдоль дорог, с крыш и водостоков, напоминая мне о ночи, которой рак прикончил моего деда. В погоду вроде этой улицы всего города пустуют. Встречаются лишь одинокие пешеходы, да и те стараются как можно скорее убраться куда подальше.

Шляпы на мне не было. Перчаток или шарфа – тоже, но я медленно шла по тротуару практически застывшей центральной улицы.

Одиноким людям обычно некуда спешить. Нас нигде не ждут.

Спустя квартал я перешла на другую сторону улицы, заказала литр кофе и уселась на крыльце локальной Львовской кофейни. Официантка настойчиво предлагала мне зайти внутрь или хотя бы взять плед, – крыльцо было без навеса – но я отказалась.

– Впевненi? – уточнила девушка.

В руках она теребила угол клетчатого пледа и по-прежнему смотрела на меня с недоверием.

– Не схоже, що дощ скоро скiнчиться.

Прежде чем исчезнуть, официантка еще раз взглянула на меня из-под

– Точно не бажаєте долучитись до інших гостей? Ще трохи й тут буде справжня повінь.

*Когда-то и у меня была непокрытая трасса*, подумала я, и улыбнулась.

Мысль эта унесла меня обратно в январь. Перед глазами тут же выросли отголоски новогоднего отпуска, сияющие огни светыной ёлки, мои неловкие попытки испечь блины, парящие в небе птицы, отцовская машина, везущая меня обратно в Николаев и Эдит Пиаф тоскливо поющая в ночи крымских дорог.

Официантка ждала моего ответа.

– Спасибо, здесь идеально.

Сидя над кофе, я думала о временах, когда считала себя несчастной. Обо всех тех днях, месяцах, годах, начиная то ли с тринадцати, то ли с пятнадцати лет. И в особенности о том времени, когда мне исполнилось двадцать.

*Если тогда я была несчастной, то как назвать мое сегодняшнее состояние?*

Ох, как же мне хотелось вернуться назад! Знать то, что я знаю сейчас, или хотя бы понимать, как много я еще не знаю. Как часто я бывала подавленной и депрессивной, не отдавая себе в этом отчета. Зацикленной на собственной, непонятно откуда возникшей модели идеальной жизни. На факте ее недостижимости, который приводил меня в бешенство, что, правда, быстро сменялось тоской. Не зная о своем душевном недуге, я так часто называла жизнь никчемной, но каким же счастливым было то время! Время, когда я не знала, какой несчастной на самом деле могу стать.

<div style="text-align: center;">***</div>

Перед моим мысленным взором возникла спальня в родительском доме. Мне было семнадцать. Я окончательно распрощалась с Эриком, наглоталась транквилизаторов, шлифовнув все это дело бутылкой дешевого бренди, включила грустные британские песни и легла умирать.

Но умирать все никак не получалось, и мне даже пришлось поднять задницу с дивана, чтобы сменить пластинку: плейлист подошел к концу, а идея умереть под аккомпанемент соседской дрели не виделась мне поэтичной.

*Fade into you*

*Strange you never knew*

Музыка вернулась, а смерть что-то и не думала появляться. Тогда я вытряхнула из верхнего ящика комода весь свой запас многочисленных транков, антидепрессантов, нейролептиков и нормотимиков, и почапала к холодильнику за водкой.

Никогда ее не любила, но чего не сделаешь ради возможности покинуть этот мир?

*Fade into you*

*I think it’s strange you never knew*

Вторая попытка, казалось, начала меня убивать. Головокружение оказалось таким сильным, что мне пришлось затушить сигарету, чтобы случайно еще и не кремироваться.

Я слышала, как окурок зашипел, коснувшись своим кончиком остатков чая.

А затем – темнота.

Прямиком как у Эдгара По: Тьма и больше ничего.

Но смерть так и не пришла в мои семнадцать.

– Бля… опять, – проворчала я, узнав очертания потолка.

Тем летом я нашла себя валявшейся на полу и долго не могла понять, как я здесь оказалась. Когда, наконец, вспомнила, (в этом мне помогли бутылки и пустые упаковки таблеток, хаотично разбросанные по периметру спальни) не без удивления обнаружила, что проспала почти трое суток.

*Вот это прикол*, подумалось мне, *кому скажи – не поверят.*

После этого было еще немало попыток самоубийства. Я неоднократно вешалась, шагала с моста, принимала смертельные дозы различных препаратов и все такое прочее, но никак не умирала. Временами, я даже делала это на автомате, и, очнувшись от забытья, совершенно не помнила ведущих к нему событий.

Последняя из таких ситуация заставила меня повторно обратиться к врачам. Случилось это вскоре после наступления двадцатилетия, когда раны от разрыва с Адамом еще не думали заживать, я нашла себя спящей на железнодорожных путях.

Ото сна меня пробудил свет фонарика, настойчиво скользящий по моему лицу. Затем из мрака выплыло другое лицо, морщинистое и, казалось, напуганное до усрачки. Им оказалось лицо вокзального охранника.

Я поднялась с холодной земли и, судорожно извиняясь, бросилась прочь от вокзала.

Той декабрьской ночью две тысячи четырнадцатого я еще долго бродила по спящему городу, не имея ни малейшего представления о том, как оказалась на вокзале. Шум удаляющегося поезда и бессонница оказались единственными флешбеками, которые мне удалось выудить из трясины собственной памяти. И только найденный в кармане паспорт со вложенной в него лаконичной запиской

**_Мне все это надоело. Я больше не могу это чувствовать. Просто хочу уснуть._**

помогли понять мне, что к чему.

<div style="text-align: center;">***</div>

В двадцать я узнала о биполярке и, начиная с двух тысячи пятнадцатого года, прилагала все усилия, чтобы обуздать свои эмоциональные качели. Или хотя бы научиться правильно на них раскачиваться. Должна признать, дело шло на поправку и немногим больше года я привела себя в относительную норму. Благо, я всегда любила немецкий философов, ну, и врожденная склонность к самоанализу сыграла свою роль. А затем…

Затем случился Вениамин. Но я не позволяла себе о нем думать. Я думала о своих двадцати годах.

Думала о Марте. О том, как вечерами мы разгуливали по холодным николаевским улицам. Затем приходили домой, пили вино, курили ганжу и проводили ночи за дружеской болтовней. О письмах, которые мы писали друг другу, живя в разных странах. Обо всех тех редких, но таких грандиозных встречах. Порой я рассказывала ей о Мишель,

*Привет, я Миша. Давай дружить.*

предавая особое значение встречам с ней, о нашем детстве и отрочества. А однажды поняла, что эти разговоры с Мартой оказались куда важнее, чем сами воспоминания.

Сидя на залитой дождем террасе Львовской кофейни мне впервые захотелось перечитать эти письма, но под рукой было лишь одно.

<div style="text-align: center;">***</div>

**_
Вчера, кажется, это было вчера, я закончила вторую часть «Маятника» и тут же перешла к третей. Все шло хорошо, слова сами рождались у меня в голове, как всегда бывает, если поймаю волну, но в определенный момент, уже утром, я почувствовала, что устала. Переутомилась от работы над романом, а это значит только одно: что бы я ни написала, результат будет отвратителен, но что еще хуже – сам процесс подобного времяпровождения просто невыносим. Ты как будто пытаешься просраться при воспаленном геморрое. У тебя нихренашеньки не получается и все старания непременно идут насмарку. Короче говоря, как бы я не любила писательство, голове требовался отдых, и я нашла его в вечерней прогулке по кладбищу.
_**

**_
На этот раз мне повезло больше. Никаких наркоманов, или, возможно, бездомных, припарковавшихся где-нибудь поблизости, я не встретила. Меня окружали только спокойные очертания чьих-то могил и голые ветви деревьев, что сонно покачивались на фоне лишенного звезд неба. Вот за что я так люблю ночь! Она накрывает собой любое дерьмо, делая города одинаковыми, и на мгновенье можно представить, что ты, наконец, сбежал из этого ненавистного сердцу места. Ты не поверишь, но здесь даже стали убирать мусор.
_**

**_
Было кое-что еще. Половина десятилетия минуло с той поры, как я впервые гуляла под луной по нашему некрополю, и вдруг поняла, что успела забыть, а, может, просто никогда не замечала, как меняется это место с приходом ночи. Я имею в виду, визуально: дороги почему-то кажутся гораздо шире, а деревья, по мере отдаления от входа в кладбище, будто бы, опускаются, приближаясь ко мне.
_**

**_
Ты когда-нибудь замечала, что стоит лишь войти на кладбище, и окружающий его мир резко замирает? Не слышно шума машин, гула неотесанных аборигенов или детского плача. Даже ветер куда-то исчезает. Что-то похожее я обычно чувствую в лесу. Некрополь скрывает тебя от всего мира, и как никогда ярко ощущаешь настоящий момент, проживая каждое его мгновенье. Я нахожу это особенно очаровательным.
_**

**_
На этот раз я была не одна. С Мишель, как ты, конечно же, догадалась. На нашем кладбище все так же нет фонарей, из-за чего мы бродили по нему интуитивно, полагаясь на мою память да божью помощь, хотя в никто из нас никогда не верил в последнюю.
_**

**_
Бродили и болтали. О литературе, мертвецах, музыке и жизни в целом. Не думаю, в том, чтобы пересказывать наши диалоги есть какой-то смысл. Агата идеальное отображение моей печальной стороны, тогда как Нора во многом списана с Миши (или, по крайней мере с моей любимой части Миши). Даже имя свое эта героиня получила благодаря «Элеанор Ригби» – любимой битловской песне моей подруги. Так что, читая роман, над которым я сейчас работаю, ты имеешь более чем полное представление о том, как происходят наши с Мишей разговоры. На самом деле, я с особым трепетом отношусь к таким моментам, пускай и не всегда это показываю.
_**

**_
Хотя нет, одну фразу я тебе, все-таки, процитирую. Мишель не прекращает повторять, что у меня аллергия на суицид. Не знаю, что это значит, но звучит довольно прозаично. Думаю, когда-нибудь, я внесу эту фразу в графу «об авторе».
_**

**_
Так к чему я, собственно, все это говорю? Полагаю, при более близком контакте, общество сочло бы меня странной. «У тебя в голове только трупики и гомики!» – так они всегда говорили, помнишь? Вот только штука в том, что я не нахожу себя странной. Да, мои увлечения, а иногда и образ мышления, слегка выходят за рамки, зачем-то установленные социумом. Социумом, который я так ненавижу. Логично, что и понятие «странности» в моих глазах приобретает другой оттенок.
_**

**_
Скажу тебе больше, мне определенно нравится быть человеком, которого большинство нарекло бы исключительно ебанутым. Мне по душе танцевать на кладбище, закидываться травой, штудировать биографию выдающихся маньяков, применять по отношению к последним прилагательное «выдающийся» вместо общепринятого «известный»… Меня привлекает патологическая анатомия, БДСМ и биография Теда Банди, а еще я мечтаю увидеть собственные пост-мортем фото. Такой список можно продолжать еще не одну страницу, но суть состоит вот в чем: я склонна считать, что только во время «неадекватной и странной» реакции на что бы то ни было, ты чувствуешь, что не просто существуешь, а создаешь воспоминания. Историю, о которой однажды сможешь написать или рассказать. Такую, о которой приятно будет вспомнить на пороге смерти. И дело тут не в фарсе, как сказал бы мой папа, а в том, что именно в такие моменты я по-настоящему чувствую себя живой. Быть может, именно так ощущали себя представители бит-поколения, и это мне по-настоящему нравится.
_**

**_
Так вот, всем этим я пытаюсь ответить на твой вопрос: да, мне интересно – действительно интересно – читать о ваших посиделках, снующих по кухне тараканах, людях, которых я не знаю, но которые, по всей вероятности, не дураки выпить, кустарном изготовлении драпа и многом другом. Мне интересно все, что способно вызывать сильные эмоции, позитивные или негативные.
_**

**_
В конечном счете, все, что ты мне рассказываешь, как и то, что ты еще расскажешь – это и есть ничто другое, как история.
_**

**_
А она-то мне и нужна.
_**

**_
Твоя Васляева
_**

**_
27 декабря 2015
_**
